### ISSUE TITLE
Improve exit message when interrupting worker

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1005]
Users commonly close dask-workers with Ctrl-C.  It would be nice to avoid displaying tracebacks to them when they do this.

```
mrocklin@carbon:~$ dask-worker localhost:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:43139'
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:39124
distributed.worker - INFO -              nanny at:            127.0.0.1:43139
distributed.worker - INFO -               http at:            127.0.0.1:45878
distributed.worker - INFO -              bokeh at:            127.0.0.1:8789
distributed.worker - INFO - Waiting to connect to:       tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   10.01 GB
distributed.worker - INFO -       Local Directory:        /tmp/nanny-93h1t2qp
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:             tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Nanny 'tcp://127.0.0.1:43139' starts worker process 'tcp://127.0.0.1:39124'
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mrocklin/Software/anaconda/lib/python3.6/multiprocessing/forkserver.py", line 164, in main
    rfds = [key.fileobj for (key, events) in selector.select()]
  File "/home/mrocklin/Software/anaconda/lib/python3.6/selectors.py", line 445, in select
Process ForkServerProcess-1:
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mrocklin/Software/anaconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mrocklin/workspace/distributed/distributed/nanny.py", line 363, in run_worker_fork
    loop.run_sync(run)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 452, in run_sync
    self.start()
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 862, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt
```

@pitrou is this easy for you?

**Comment by pitrou** [comment]
The forkserver traceback at least should now be silenced in CPython: https://bugs.python.org/issue30185
