### ISSUE TITLE
Long list of socket errors after client shutdown

### ISSUE THREAD

**Issue by bschreck** [dask/distributed#1031]
If i initialize a client with a LocalCluster and then shut it down like this:
    c = Client()
    c.shutdown()

I get many repeated errors that look like:

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP 'tcp://127.0.0.1:57338'>
Traceback (most recent call last):
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/distributed/compatibility.py", line 216, in _exitfunc
    f()
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/distributed/compatibility.py", line 140, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/distributed/comm/tcp.py", line 127, in finalize
    stream.close()
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/tornado/iostream.py", line 434, in close
    self.io_loop.remove_handler(self.fileno())
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/tornado/ioloop.py", line 732, in remove_handler
    fd, obj = self.split_fd(fd)
  File "/Users/bschreck/FeatureLabs/featuretools/ENV/lib/python2.7/site-packages/tornado/ioloop.py", line 652, in split_fd
    return fd.fileno(), fd
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor

I tried figuring out exactly why but not sure. It's very annoying when I write test cases that need to shutdown the cluster. If I wrap the line it refers to in comm/tcp.py with a try/except socket.error block these go away. I'm not sure if there's actually something to do to prevent the errors from cropping up in the first place, or if the best solution is just to try/except

**Comment by mrocklin** [comment]
Yeah, I've been seeing these in tests as well.  FWIW these are not present
on Python 3.  We should probably figure out what's going on regardless
though.  Does anyone have experience on what this might be?

We could also just try-except on this error, but it would be interesting to
know what's going on.

**Comment by pitrou** [comment]
What happens in you replace `self.loop.close(all_fds=True)` with `self.loop.close(all_fds=False)` in `Client.shutdown`? I suspect this may be the culprit, since basically Tornado closes the sockets a first time, and then we try to close them a second time by closing the streams.

**Comment by pitrou** [comment]
Note the different behaviour of `socket.fileno()` on Python 2 and Python 3.
Python 2.7:
```
>>> sock = socket.socket()
>>> sock.close()
>>> sock.fileno()
Traceback (most recent call last):
  File "<ipython-input-11-48fa6cbadfe1>", line 1, in <module>
    sock.fileno()
  File "/home/antoine/miniconda3/envs/dask27/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/home/antoine/miniconda3/envs/dask27/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```
Python 3.6:
```
>>> sock = socket.socket()
>>> sock.close()
>>> sock.fileno()
-1
```

**Comment by bschreck** [comment]
Changing to `all_fds=False` removes the errors for me

**Comment by mrocklin** [comment]
I think that this is now resolved.
