### ISSUE TITLE
Compression tests are fragile

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#1093]
Under Python 2.7, if I have `blosc` and `snappy` installed, I get:
```
____________________________________________________________ test_serialize_list_compress ____________________________________________________________
Traceback (most recent call last):
  File "/home/antoine/distributed/distributed/protocol/tests/test_serialize.py", line 177, in test_serialize_list_compress
    assert sum(map(len, L)) < x.nbytes / 2
AssertionError: assert 8000122 < (8000000 / 2)
 +  where 8000122 = sum([24, 98, 8000000])
 +    where [24, 98, 8000000] = map(len, ['\x02\x00\x00\x00\x00\x00\x00\x00b\x00\x00\x00\x00\x00\x00\x00\x00\x12z\x00\x00\x00\x00\x00', '\x87\xc4\x05count\x01\...0fB@\xc4\x04type\xc4\rnumpy.ndarray', <read-write buffer for 0x7f890bfa0580, size 8000000, offset 0 at 0x7f890c819a70>])
 +  and   8000000 = array([ 1.,  1.,  1., ...,  1.,  1.,  1.]).nbytes
```

If I also install `lz4`, that error disappears but the following errors appear:
```
________________________________________________________________ test_compress_numpy _________________________________________________________________
Traceback (most recent call last):
  File "/home/antoine/distributed/distributed/protocol/tests/test_numpy.py", line 146, in test_compress_numpy
    assert all(c == 'blosc' for c in
AssertionError: assert False
 +  where False = all(<generator object <genexpr> at 0x7f2f5435d4b0>)
__________________________________________________________ test_maybe_compress_memoryviews ___________________________________________________________
Traceback (most recent call last):
  File "/home/antoine/distributed/distributed/protocol/tests/test_protocol.py", line 210, in test_maybe_compress_memoryviews
    assert compression == 'blosc'
AssertionError: assert 'lz4' == 'blosc'
  - lz4
  + blosc
```

For some reason, Python 3 works fine. @mrocklin

**Comment by GenevieveBuckley** [comment]
Thank you for the report @pitrou 

I don't think this was ever worked out, but Dask no longer supports python 2.7 so I'm going to close the issue now.
