### ISSUE TITLE
Import error in `dask-scheduler`

### ISSUE THREAD

**Issue by bluenote10** [dask/distributed#1120]
After following the [installation instructions](http://distributed.readthedocs.io/en/latest/quickstart.html) and installing via `pip install dask distributed --upgrade`, running `dask-scheduler` errors with:

```
Traceback (most recent call last):
  File "/home/fabian/.virtualenvs/dask/bin/dask-scheduler", line 7, in <module>
    from distributed.cli.dask_scheduler import go
  File "/home/fabian/git/dask/dask/distributed.py", line 13, in <module>
    raise ImportError(msg)
ImportError: Dask's distributed scheduler is not installed.

Please either conda or pip install dask distributed:

  conda install dask distributed          # either conda install
  pip install dask distributed --upgrade  # or pip install
```

To verify that I have the latest versions on PyPI: 

```
$ pip freeze | grep "dask\|distributed"
dask==0.14.3
distributed==1.16.3
```

Is this an issue of the documentation or are these packages broken?

**Comment by mrocklin** [comment]
Hrm, here is my experience from a fresh environment.

```
mrocklin@carbon:~$ conda create -n test-1120 python pip
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/mrocklin/Software/anaconda/envs/test-1120:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2l-0     
    pip:        9.0.1-py36_1 
    python:     3.6.1-2      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      

openssl-1.0.2l 100% |################################| Time: 0:00:00   7.88 MB/s
python-3.6.1-2 100% |################################| Time: 0:00:01   8.66 MB/s
wheel-0.29.0-p 100% |################################| Time: 0:00:00  11.24 MB/s
#
# To activate this environment, use:
# > source activate test-1120
#
# To deactivate this environment, use:
# > source deactivate test-1120
#

mrocklin@carbon:~$ source activate test-1120
(test-1120) mrocklin@carbon:~$ pip install dask distributed
Collecting dask
  Using cached dask-0.14.3-py2.py3-none-any.whl
Collecting distributed
  Using cached distributed-1.16.3-py2.py3-none-any.whl
Collecting six (from distributed)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting click>=6.6 (from distributed)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting zict>=0.1.2 (from distributed)
  Using cached zict-0.1.2-py2.py3-none-any.whl
Collecting tornado>=4.2 (from distributed)
Collecting sortedcollections (from distributed)
  Using cached sortedcollections-0.5.3-py2.py3-none-any.whl
Collecting psutil (from distributed)
Collecting tblib (from distributed)
  Using cached tblib-1.3.2-py2.py3-none-any.whl
Collecting msgpack-python (from distributed)
Collecting cloudpickle>=0.2.2 (from distributed)
  Downloading cloudpickle-0.3.1-py2.py3-none-any.whl
Collecting toolz>=0.7.4 (from distributed)
Collecting heapdict (from zict>=0.1.2->distributed)
Collecting sortedcontainers (from sortedcollections->distributed)
  Using cached sortedcontainers-1.5.7-py2.py3-none-any.whl
Installing collected packages: dask, six, click, heapdict, zict, tornado, sortedcontainers, sortedcollections, psutil, tblib, msgpack-python, cloudpickle, toolz, distributed
Successfully installed click-6.7 cloudpickle-0.3.1 dask-0.14.3 distributed-1.16.3 heapdict-1.0.0 msgpack-python-0.4.8 psutil-5.2.2 six-1.10.0 sortedcollections-0.5.3 sortedcontainers-1.5.7 tblib-1.3.2 toolz-0.8.2 tornado-4.5.1 zict-0.1.2
(test-1120) mrocklin@carbon:~$ dask-scheduler 
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at: tcp://192.168.50.100:8786
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-h2o4_kct
distributed.scheduler - INFO - -----------------------------------------------
```

Everything seems to work fine.

Can you provide more information about exactly what you do such that things fail?

**Comment by bluenote10** [comment]
Stupid me: I was running `dask-scheduler` from within the Dask repository (the working directory being `./dask`, yay).

**Comment by NatLun091238** [comment]
HI! I experience the same issue. I use Datalab instance on Google cloud platform (GCP). For DASK installation I use the following command in the cell:
`!pip install dask[complete] distributed --upgrade `
Installation goes well and I can verify it:
`!dask-scheduler ` which produce an output:

`distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://172.17.0.2:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-XAWu9a
distributed.scheduler - INFO - -----------------------------------------------
`

On the other hand, I get 

` ImportError: cannot import name future_set_exc_info` pointing to
`100 from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
 101                                 future_add_done_callback, future_set_result_unless_cancelled)`

when I call `from distributed import Client`..........
Any ideas how to solve this???

**Comment by mrocklin** [comment]
I recommend providing a minimal example and full traceback.
