### ISSUE TITLE
self.workers.remove(w) fails trying to remove worker.

### ISSUE THREAD

**Issue by sjperkins** [dask/distributed#1166]
Probably a nit, but this code:

```python
import dask.array as da

from distributed import (Client,
    LocalCluster)

import numpy as np

cluster = LocalCluster()
client = Client(cluster.scheduler_address)

ones = da.ones(shape=(1000,1000), chunks=(100,100), dtype=np.float64)

A = client.persist(ones)

print A

f = client.compute(A)

print f.result()

client.shutdown()
cluster.close()
```

fails in the following way:

```bash
dask.array<wrapped, shape=(1000, 1000), dtype=float64, chunksize=(100, 100)>
[[ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 ..., 
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  1.  1.  1.]]
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0b0f24c8>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0a012af8>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0a012db8>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0b12d158>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0a021e68>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b09f70368>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0b0f28e8>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f7b0b0f2d08>
Traceback (most recent call last):
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/mb/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/work/ska/code/distributed/distributed/deploy/local.py", line 206, in _stop_worker
    self.workers.remove(w)
ValueError: list.remove(x): x not in list
```

**Comment by pitrou** [comment]
Could you guard your code with a `if __name__ == "__main__"` statement and try again?

**Comment by sjperkins** [comment]
> Could you guard your code with a `if __name__ == "__main__"` statement and try again?

It still occurs

**Comment by pitrou** [comment]
This bug is now fixed. Thank you @sjperkins  for reporting!
