### ISSUE TITLE
Issue with obtaining large output from worker machines

### ISSUE THREAD

**Issue by faheem00** [dask/distributed#1189]
This problem is a bit hard to explain, as it encompasses various experiments I did with Dask, but I will try to go step by step. 

I have been using Dask for a while now along with the distributed library. My current setup is a cluster with one master and 9 homogeneous worker machines. I've set up dask workers in each machines without trouble, and so far I've done experiments on various large scale workloads, including Word Count and Sort.

A key characteristics of the above mentioned experiments is that, while the input data given to mappers can be gigantic (I've tested upto 32 gigs of input), the output provided by each task is quite small. Recently, I've been attempting to parallelize a bioinformatics application. For that implementation, the input is quite small (around 2-4 gigs). However, each task is supposed to output a pandas dataframe of around 1000 rows and 11 columns. So the output of each task for this application is bigger than my previous experiments.

First, I ran the application using a single machine with multiple cores acting as task handlers. From that run, I determined the total output size of around 160 tasks to be 141 megabytes, so on average each task provides an output of 0.88 megabytes.

However, when I try to run the same application on Dask, the execution stalls. I used dask bag to parallelize the input, then provide the mapper with the mapper function. After I call the compute function, the terminal halts. No output is shown.

I checked the memory of master and worker machines while executing. When computation starts, master machine's memory quickly starts to fill up. Before execution, around 4GB of memory is full (out of 32GB). When the used memory is around 12GB, the filling process stops. After that, no activity is recorded for the master machine memory. As for the workers, I did not detect any such memory or CPU surge while computation was ongoing.

Along with the memory problem, I encountered another problem which is similar to issue #1012.  While the computation was running, all the workers were removed with the following general error messages - 
```
Worker 'tcp://X.X.X.X:40028' failed from closed comm: Stream is closed
Remove worker tcp://X.X.X.X:40028
```
This happened with almost all the workers. After being removed, the connections were established again, although the computation was still stuck. 

I thought this might be a problem with python queue, as python queue can get stuck if too much data is inserted into it. so I used  [Data Streams with Queues](https://github.com/dask/distributed/blob/master/docs/source/queues.rst) to insert input manually into a queue, send the queue to workers and then tried to get output from the stream. I was unsuccessful with this method also; the computation was still stuck.

So, the main problem here is that *dask distributed computation is getting stuck when working with tasks which are supposed to produce large outputs. Workers streams are being closed and removed, and master machine memory continues to fill up without explanation*.

I should mention here that due to bokeh/tornado incompability (which I learned from issue #1057), I am using tornado 4.4 instead of the latest versions. All other packages are updated up to 7 days ago as of this writing.

I realize I may not have been eloquent with my description of the problem, so please let me know if I need to explain anything further about any individual detail. If possible, I want to solve this problem myself, so a bit of hint about where the problem may lie will also be helpful. All these experiments are related to my masters thesis, and I might have a publication in near future should I solve this problem ;) Thanks for your time.

**Comment by mrocklin** [comment]
Sorry for the delay in response, I was away last week.  I recommend looking at the diagnostic web pages to see if they can provide you with more information about what is going on: http://distributed.readthedocs.io/en/latest/web.html

**Comment by mrocklin** [comment]
Any update here @faheem00 ?  Generally moving around megabytes of data shouldn't be a problem.  Many people use Dask with significantly larger output.

**Comment by faheem00** [comment]
Sorry, I was in a car accident and was admitted to a hospital for a few
days. I will have a look at the diagnostics again aa soon as I return to
work.

**Comment by mrocklin** [comment]
I'm sorry to hear this.  I hope everything will be ok.

**Comment by faheem00** [comment]
So, I've done the experiment again, with the same result - nothing happens. When I execute the script, nothing is shown on the diagnostics page. It seems the execution does not reach the stage at which the diagnostic page is notified. However, I have log excerpts from the dask scheduler and the actual execution which I can post here to provide a better idea.

First, I'll post an excerpt from the code base. This excerpt contains the dask bag and the mapreduce portion. The following is a method of a particular python class - 

```python
def run(self,dist):
        self.logger.info('Starting local map reduce')
        if(self.client_ip_port is not None):
            client = Client(self.client_ip_port)
        else:
            client = Client()
        if(dist.nested is not None):
            mapped_values = map(dist.nested, dist.input_seq)
        else:
            cache = Chest(path='/tmp', available_memory=self.available_memory)
            mapped_values = db.from_sequence(dist.input_seq,npartitions=len(dist.input_seq)).map(dist.mapper).compute(cache=cache)
            progress(mapped_values)
        return dist.reducer(mapped_values)

```

As it can be seen from the code excerpt above, the dask bag is taking an input sequence, upon which a mapper is being applied. A cache is also being used for computation.

The following log excerpt is from dask schedular. This shows how the workers are automatically removed and streams are closed without any explanation.
```
distributed.scheduler - INFO - Receive client connection: Client-317fadf0-65b2-11e7-a95d-c1c6f372dd35
distributed.scheduler - INFO - Worker 'tcp://192.168.1.202:43841' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.202:43841
distributed.scheduler - INFO - Removed worker tcp://192.168.1.202:43841
distributed.scheduler - INFO - Register tcp://192.168.1.202:37979
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.202:37979
distributed.scheduler - INFO - Worker 'tcp://192.168.1.202:38701' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.202:38701
distributed.scheduler - INFO - Removed worker tcp://192.168.1.202:38701
distributed.scheduler - INFO - Register tcp://192.168.1.202:32790
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.202:32790
distributed.scheduler - INFO - Worker 'tcp://192.168.1.201:35188' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.201:35188
distributed.scheduler - INFO - Removed worker tcp://192.168.1.201:35188
distributed.scheduler - INFO - Remove worker tcp://192.168.1.201:33790
distributed.scheduler - INFO - Removed worker tcp://192.168.1.201:33790
distributed.scheduler - INFO - Remove worker tcp://192.168.1.202:41763
distributed.scheduler - INFO - Removed worker tcp://192.168.1.202:41763
distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: Stream is closed
distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Register tcp://192.168.1.201:45179
distributed.scheduler - INFO - Register tcp://192.168.1.202:37125
distributed.scheduler - INFO - Register tcp://192.168.1.201:43413
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.201:45179
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.201:43413
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.202:37125
distributed.scheduler - INFO - Worker 'tcp://192.168.1.201:40393' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.201:40393
distributed.scheduler - INFO - Removed worker tcp://192.168.1.201:40393
distributed.scheduler - INFO - Remove worker tcp://192.168.1.203:36756
distributed.scheduler - INFO - Removed worker tcp://192.168.1.203:36756
distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.201:46082
distributed.scheduler - INFO - Removed worker tcp://192.168.1.201:46082
distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Register tcp://192.168.1.203:45116
distributed.scheduler - INFO - Register tcp://192.168.1.201:36093
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.203:45116
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.201:36093
distributed.scheduler - INFO - Register tcp://192.168.1.201:40581
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.201:40581
distributed.scheduler - INFO - Worker 'tcp://192.168.1.203:42168' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.203:42168
distributed.scheduler - INFO - Removed worker tcp://192.168.1.203:42168
distributed.scheduler - INFO - Worker 'tcp://192.168.1.203:41470' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.203:41470
distributed.scheduler - INFO - Removed worker tcp://192.168.1.203:41470
distributed.scheduler - INFO - Register tcp://192.168.1.203:32981
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.203:32981
distributed.scheduler - INFO - Register tcp://192.168.1.203:43868
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.203:43868
distributed.scheduler - INFO - Worker 'tcp://192.168.1.204:33518' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.204:33518
distributed.scheduler - INFO - Removed worker tcp://192.168.1.204:33518
distributed.scheduler - INFO - Register tcp://192.168.1.204:37321
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.204:37321
distributed.scheduler - INFO - Worker 'tcp://192.168.1.203:45998' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.203:45998
distributed.scheduler - INFO - Removed worker tcp://192.168.1.203:45998
distributed.scheduler - INFO - Worker 'tcp://192.168.1.204:39092' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.204:39092
distributed.scheduler - INFO - Removed worker tcp://192.168.1.204:39092
distributed.scheduler - INFO - Worker 'tcp://192.168.1.203:45852' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.203:45852
distributed.scheduler - INFO - Removed worker tcp://192.168.1.203:45852
distributed.scheduler - INFO - Register tcp://192.168.1.203:42150
distributed.scheduler - INFO - Remove worker tcp://192.168.1.204:35264
distributed.scheduler - INFO - Removed worker tcp://192.168.1.204:35264
distributed.scheduler - INFO - Register tcp://192.168.1.204:45291
distributed.scheduler - INFO - Register tcp://192.168.1.203:38599
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.203:42150
distributed.scheduler - INFO - Worker 'tcp://192.168.1.203:45716' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.203:45716
distributed.scheduler - INFO - Removed worker tcp://192.168.1.203:45716
distributed.scheduler - INFO - Register tcp://192.168.1.204:33226
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.203:38599
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.204:45291
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.204:33226
distributed.scheduler - INFO - Register tcp://192.168.1.203:42360
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.203:42360
distributed.scheduler - INFO - Worker 'tcp://192.168.1.204:44125' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.204:44125
distributed.scheduler - INFO - Removed worker tcp://192.168.1.204:44125
distributed.scheduler - INFO - Remove worker tcp://192.168.1.204:32904
distributed.scheduler - INFO - Removed worker tcp://192.168.1.204:32904
distributed.scheduler - INFO - Register tcp://192.168.1.204:38139
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.204:38139
distributed.scheduler - INFO - Register tcp://192.168.1.204:43453
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.204:43453
distributed.scheduler - INFO - Worker 'tcp://192.168.1.204:39015' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.204:39015
distributed.scheduler - INFO - Removed worker tcp://192.168.1.204:39015
distributed.scheduler - INFO - Register tcp://192.168.1.204:35188
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.204:35188
distributed.scheduler - INFO - Worker 'tcp://192.168.1.205:33799' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.205:33799
distributed.scheduler - INFO - Removed worker tcp://192.168.1.205:33799
distributed.scheduler - INFO - Worker 'tcp://192.168.1.205:40056' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.205:40056
distributed.scheduler - INFO - Removed worker tcp://192.168.1.205:40056
distributed.scheduler - INFO - Register tcp://192.168.1.205:41525
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.205:41525
distributed.scheduler - INFO - Register tcp://192.168.1.205:34244
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.205:34244
distributed.scheduler - INFO - Worker 'tcp://192.168.1.205:36325' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.205:36325
distributed.scheduler - INFO - Removed worker tcp://192.168.1.205:36325
distributed.scheduler - INFO - Register tcp://192.168.1.205:42835
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.205:42835
distributed.scheduler - INFO - Worker 'tcp://192.168.1.205:40660' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.205:40660
distributed.scheduler - INFO - Removed worker tcp://192.168.1.205:40660
distributed.scheduler - INFO - Register tcp://192.168.1.205:41973
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.205:41973
distributed.scheduler - INFO - Worker 'tcp://192.168.1.205:35865' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.205:35865
distributed.scheduler - INFO - Removed worker tcp://192.168.1.205:35865
distributed.scheduler - INFO - Register tcp://192.168.1.205:38389
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.205:38389
distributed.scheduler - INFO - Worker 'tcp://192.168.1.205:35451' failed from closed comm: in <closed TCP>: Stream is closed
distributed.scheduler - INFO - Remove worker tcp://192.168.1.205:35451
distributed.scheduler - INFO - Removed worker tcp://192.168.1.205:35451
distributed.scheduler - INFO - Remove client Client-317fadf0-65b2-11e7-a95d-c1c6f372dd35
distributed.scheduler - INFO - Close client connection: Client-317fadf0-65b2-11e7-a95d-c1c6f372dd35
distributed.scheduler - INFO - Register tcp://192.168.1.205:41988
distributed.scheduler - INFO - Starting worker compute stream, tcp://192.168.1.205:41988
```

Finally, I am providing the traceback of the execution after I press Ctrl + C when the execution continued to go on without any visual progress.

```
distributed.utils - ERROR - ("('from_sequence-map-mapper_closure-77c686290aed8d6d70eb1bce1912b959', 1)", 'tcp://192.168.1.205:35451')
Traceback (most recent call last):
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/home/hduser/.local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/hduser/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/hduser/.local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/client.py", line 1235, in _gather
    traceback)
  File "<string>", line 2, in reraise
KilledWorker: ("('from_sequence-map-mapper_closure-77c686290aed8d6d70eb1bce1912b959', 1)", 'tcp://192.168.1.205:35451')
Traceback (most recent call last):
  File "test_dask_fastlmm.py", line 25, in <module>
    results_df = single_snp_all_plus_select(test_snps=snp_reader,G=snp_reader,pheno=pheno_fn,do_plot=False,runner=runner)
  File "/home/hduser/fastlmm/fastlmm/association/single_snp_all_plus_select.py", line 430, in single_snp_all_plus_select
    chrom_index_to_best_sid = _best_snps_for_each_chrom(chrom_list, common_input_files, runner, G, n_folds, seed, pheno, covar, force_full_rank, force_low_rank, mixing, h2, k_list, GB_goal)
  File "/home/hduser/fastlmm/fastlmm/association/single_snp_all_plus_select.py", line 366, in _best_snps_for_each_chrom
    runner=runner)
  File "/home/hduser/fastlmm/fastlmm/util/mapreduce.py", line 174, in map_reduce
    return reducer(map(nested,input_seq))
  File "/home/hduser/fastlmm/fastlmm/association/single_snp_all_plus_select.py", line 358, in mapper_find_best_given_chrom
    reducer=reducer_find_best)
  File "/home/hduser/fastlmm/fastlmm/util/mapreduce.py", line 174, in map_reduce
    return reducer(map(nested,input_seq))
  File "/home/hduser/fastlmm/fastlmm/association/single_snp_all_plus_select.py", line 267, in mapper_gather_lots
    GB_goal=GB_goal,  force_full_rank=force_full_rank, force_low_rank=force_low_rank, mixing=mixing, h2=h2, runner=runner)
  File "/home/hduser/fastlmm/fastlmm/association/single_snp.py", line 166, in single_snp
    runner=runner)
  File "/home/hduser/fastlmm/fastlmm/association/single_snp.py", line 640, in _internal_single
    runner=runner)
  File "/home/hduser/fastlmm/fastlmm/util/mapreduce.py", line 181, in map_reduce
    result = runner.run(dist)
  File "/home/hduser/fastlmm/fastlmm/util/runner/LocalMapReduce.py", line 44, in run
    mapped_values = db.from_sequence(dist.input_seq,npartitions=8).map(dist.mapper).compute(cache=cache) #map(dist.mapper, dist.input_seq)
  File "/home/hduser/.local/lib/python2.7/site-packages/dask/base.py", line 98, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/hduser/.local/lib/python2.7/site-packages/dask/base.py", line 205, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/client.py", line 1893, in get
    results = self.gather(packed)
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/client.py", line 1355, in gather
    direct=direct, local_worker=local_worker)
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/client.py", line 531, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/home/hduser/.local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/hduser/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/hduser/.local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/hduser/.local/lib/python2.7/site-packages/distributed/client.py", line 1235, in _gather
    traceback)
  File "<string>", line 2, in reraise
distributed.scheduler.KilledWorker: ("('from_sequence-map-mapper_closure-77c686290aed8d6d70eb1bce1912b959', 1)", 'tcp://192.168.1.205:35451')
```

These are the traces I was able to gather while trying to execute the script. Any suggestion as to the cause of this problem will be much appreciated. I am also trying to debug the error, but narrowing down the problem will be a big help.
