### ISSUE TITLE
'DaskS3FileSystem' object has no attribute 'config_kwargs'

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1238]
Hello,

I'm running Dask in a distributed setup.
Scheduler and workers run on EC2 instances, access to S3 is set up by attaching IAM roles to instances.
I'm trying to simple word count, data file to be processed is stored on S3 bucket that belongs to different account - IAM role of the EC2 instances has granted access to the bucket (I checked with AWS CLI, boto and using s3fs directly).

Code run on client (more or less):

from dask.distributed import Client, progress
client = Client('xxxx')

b = db.read_text('s3://xxxxx',
                 blocksize=1000000)
wordcount = b.str.split().flatten().frequencies().topk(10, lambda x: x[1])
future = client.compute(wordcount)
print(future)
progress(future)
results = client.gather(future)
print(results)

Errors that I'm seeing on the worker:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 258, in __setstate__
    self.s3 = self.connect()
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 211, in connect
    **self.config_kwargs)
AttributeError: 'DaskS3FileSystem' object has no attribute 'config_kwargs'
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/core.py", line 121, in loads
    value = _deserialize(head, fs)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 161, in deserialize
    return f(header, frames)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 23, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 258, in __setstate__
    self.s3 = self.connect()
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 211, in connect
    **self.config_kwargs)
AttributeError: 'DaskS3FileSystem' object has no attribute 'config_kwargs'
distributed.worker - ERROR - 'DaskS3FileSystem' object has no attribute 'config_kwargs'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/distributed/worker.py", line 1040, in compute_stream
    msgs = yield comm.read()
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib64/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/distributed/comm/tcp.py", line 169, in read
    msg = from_frames(frames, deserialize=self.deserialize)
  File "/usr/local/lib/python2.7/site-packages/distributed/comm/utils.py", line 30, in from_frames
    return protocol.loads(frames, deserialize=deserialize)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/core.py", line 121, in loads
    value = _deserialize(head, fs)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 161, in deserialize
    return f(header, frames)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 23, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 258, in __setstate__
    self.s3 = self.connect()
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 211, in connect
    **self.config_kwargs)
AttributeError: 'DaskS3FileSystem' object has no attribute 'config_kwargs'
distributed.core - ERROR - 'DaskS3FileSystem' object has no attribute 'config_kwargs'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/distributed/core.py", line 260, in handle_comm
    result = yield result
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib64/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/distributed/worker.py", line 1040, in compute_stream
    msgs = yield comm.read()
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib64/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib64/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/distributed/comm/tcp.py", line 169, in read
    msg = from_frames(frames, deserialize=self.deserialize)
  File "/usr/local/lib/python2.7/site-packages/distributed/comm/utils.py", line 30, in from_frames
    return protocol.loads(frames, deserialize=deserialize)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/core.py", line 121, in loads
    value = _deserialize(head, fs)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 161, in deserialize
    return f(header, frames)
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 23, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
  File "/usr/local/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 258, in __setstate__
    self.s3 = self.connect()
  File "/usr/local/lib/python2.7/site-packages/s3fs/core.py", line 211, in connect
    **self.config_kwargs)
AttributeError: 'DaskS3FileSystem' object has no attribute 'config_kwargs'

**Comment by martindurant** [comment]
Thanks for the report. Do you have the same version of s3fs on all your workers? 'config_kwargs' was a relatively recent change.

**Comment by konrad-roze** [comment]
Actually, I did have same version of s3fs on workers and scheduler, but the s3fs on client was older. After upgrading client, things seem better. I was not aware that it might matter.. Is it the case?

Currently the computation seems to run correctly but I get following error after printing the results:

distributed.utils - ERROR - 'StreamClosedError' object has no attribute 'real_error'
Traceback (most recent call last):
  File "xxxxxxxxxxxxxxxx/distributed/utils.py", line 381, in log_errors
    yield
  File "xxxxxxxxxxxxxxxx/distributed/client.py", line 742, in _handle_report
    msgs = yield self.scheduler_comm.comm.read()
  File "/opt/brazil-pkg-cache/packages/Python-tornado/Python-tornado-4.2.6.212/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/opt/brazil-pkg-cache/packages/Python-tornado/Python-tornado-4.2.6.212/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/opt/brazil-pkg-cache/packages/Python-tornado/Python-tornado-4.2.6.212/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "xxxxxxxxxxxxxxxx/distributed/comm/tcp.py", line 166, in read
    convert_stream_closed_error(e)
  File "xxxxxxxxxxxxxxx/distributed/comm/tcp.py", line 101, in convert_stream_closed_error
    if exc.real_error is not None:
AttributeError: 'StreamClosedError' object has no attribute 'real_error'

**Comment by konrad-roze** [comment]
I figured out that the last error occured because of Tornado 4.2 with 4.5.x it works ok.

**Comment by martindurant** [comment]
OK to close?

**Comment by konrad-roze** [comment]
Yes, version synchornization solved the problem. Although it seems a bit problematic that you need s3fs (and in the same version) on each client machine. If you want to share cluster, keeping workers and scheduler in sync is relatively easy, but it's hard to force update on client machines.

**Comment by martindurant** [comment]
Changes requiring version updates should be relatively rare, but I don't suppose we can be completely immune to such issues, however careful we are.
