### ISSUE TITLE
Stray processes in distributed multi-process workers

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1243]
Hello

I'm trying to use dask distributed on cluster of machines. Workers are running in multi-processing mode. However, most of time when I start the workers, the number that scheduler GUI reports is lower than what I specified. Looks like some processes are going stray, because when I stop the worker I'm getting messages like:

File "/usr/local/lib/python2.7/site-packages/distributed/nanny.py", line 385, in _wait_until_running
    raise ValueError("Worker not started")

and

tornado.ioloop.TimeoutError: Operation timed out after None seconds
distributed.process - WARNING - reaping stray process <Process(Process-3, started daemon)>

Then I need to kill the stray processes manually and try to restart the worker (sometimes helps). Number of cores as reported by scheduler never goes up to maximum by itself.

**Comment by mrocklin** [comment]
Hrm, interesting.  I've never observed this behavior before.  My first guess is that the workers are having difficulty connecting to the scheduler.  Perhaps you are on a somewhat restrictive network?  Do you experience this behavior if you are just on the same machine and connecting to localhost?

**Comment by konrad-roze** [comment]
I might experiment with it a bit more, however.. I'm running it on EC2 hosts within the same VPC, same subnet and unrestricted traffic.

**Comment by mrocklin** [comment]
Hrm, that is surprising then.  Any more information you can dig up, like worker logs, would be useful.

**Comment by konrad-roze** [comment]
Sorry for late answer, I was solving some other issues. There seem to be no log entries from the stray processes, but if you do `ps -aux` you can see all of them (9 processes in our case for nprocs=8). Also there is attempt to reap them on worker shutdown:

Worker startup:

```
    Starting dask worker
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:36883'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:33523'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:34013'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:44319'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:44195'
    No handlers could be found for logger "bokeh.server.server"
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:41375'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:41109'
    No handlers could be found for logger "bokeh.server.server"
    No handlers could be found for logger "bokeh.server.server"
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.35.91:46695'
    No handlers could be found for logger "bokeh.server.server"
    No handlers could be found for logger "bokeh.server.server"
    distributed.worker - INFO -       Start worker at:     tcp://10.0.35.91:34959
    distributed.worker - INFO -              bokeh at:           10.0.35.91:41433
    distributed.worker - INFO -               http at:           10.0.35.91:42981
    distributed.worker - INFO -              nanny at:           10.0.35.91:33523
    distributed.worker - INFO - Waiting to connect to:     tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          1
    distributed.worker - INFO -                Memory:                    1.18 GB
    distributed.worker - INFO -       Local Directory:    /tmp/dask/worker-jTJH2_
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -       Start worker at:     tcp://10.0.35.91:33587
    distributed.worker - INFO -              bokeh at:           10.0.35.91:33751
    distributed.worker - INFO -               http at:           10.0.35.91:37127
    distributed.worker - INFO -              nanny at:           10.0.35.91:34013
    distributed.worker - INFO - Waiting to connect to:     tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          1
    distributed.worker - INFO -                Memory:                    1.18 GB
    distributed.worker - INFO -       Local Directory:    /tmp/dask/worker-3iw6Y2
    distributed.worker - INFO - -------------------------------------------------
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    No handlers could be found for logger "bokeh.server.server"
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.core - DEBUG - Connection from 'tcp://10.0.59.223:34950' to Worker
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.worker - INFO -         Registered to:           tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.core - DEBUG - Message from 'tcp://10.0.59.223:34950': {'reply': False, 'op': 'compute-stream'}
    distributed.core - DEBUG - Calling into handler compute_stream
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.core - DEBUG - Connection from 'tcp://10.0.59.223:34936' to Worker
    distributed.core - DEBUG - Message from 'tcp://10.0.59.223:34936': {'reply': False, 'op': 'compute-stream'}
    distributed.core - DEBUG - Calling into handler compute_stream
    distributed.worker - INFO -         Registered to:           tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -       Start worker at:     tcp://10.0.35.91:33715
    distributed.worker - INFO -              bokeh at:           10.0.35.91:36799
    distributed.worker - INFO -               http at:           10.0.35.91:46647
    distributed.worker - INFO -              nanny at:           10.0.35.91:44319
    distributed.worker - INFO - Waiting to connect to:     tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          1
    distributed.worker - INFO -                Memory:                    1.18 GB
    distributed.worker - INFO -       Local Directory:    /tmp/dask/worker-QKVe1F
    distributed.worker - INFO - -------------------------------------------------
    No handlers could be found for logger "bokeh.server.server"
    No handlers could be found for logger "bokeh.server.server"
    distributed.worker - INFO -       Start worker at:     tcp://10.0.35.91:34755
    distributed.worker - INFO -              bokeh at:           10.0.35.91:36015
    distributed.worker - INFO -               http at:           10.0.35.91:39325
    distributed.worker - INFO -              nanny at:           10.0.35.91:41375
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.worker - INFO - Waiting to connect to:     tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          1
    distributed.worker - INFO -                Memory:                    1.18 GB
    distributed.worker - INFO -       Local Directory:    /tmp/dask/worker-53EXyT
    distributed.worker - INFO - -------------------------------------------------
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.core - DEBUG - Connection from 'tcp://10.0.59.223:54604' to Worker
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.worker - INFO -         Registered to:           tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.core - DEBUG - Message from 'tcp://10.0.59.223:54604': {'reply': False, 'op': 'compute-stream'}
    distributed.core - DEBUG - Calling into handler compute_stream
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.core - DEBUG - Connection from 'tcp://10.0.59.223:46246' to Worker
    distributed.worker - INFO -         Registered to:           tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.core - DEBUG - Message from 'tcp://10.0.59.223:46246': {'reply': False, 'op': 'compute-stream'}
    distributed.core - DEBUG - Calling into handler compute_stream
    distributed.worker - INFO -       Start worker at:     tcp://10.0.35.91:40275
    distributed.worker - INFO -              bokeh at:           10.0.35.91:35317
    distributed.worker - INFO -               http at:           10.0.35.91:33223
    distributed.worker - INFO -              nanny at:           10.0.35.91:41109
    distributed.worker - INFO - Waiting to connect to:     tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          1
    distributed.worker - INFO -                Memory:                    1.18 GB
    distributed.worker - INFO -       Local Directory:    /tmp/dask/worker-RyJeqz
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -       Start worker at:     tcp://10.0.35.91:43995
    distributed.worker - INFO -              bokeh at:           10.0.35.91:44433
    distributed.worker - INFO -               http at:           10.0.35.91:45199
    distributed.worker - INFO -              nanny at:           10.0.35.91:46695
    distributed.worker - INFO - Waiting to connect to:     tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          1
    distributed.worker - INFO -                Memory:                    1.18 GB
    distributed.worker - INFO -       Local Directory:    /tmp/dask/worker-jcnwTo
    distributed.worker - INFO - -------------------------------------------------
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.core - DEBUG - Connection from 'tcp://10.0.59.223:52078' to Worker
    distributed.worker - INFO -         Registered to:           tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.core - DEBUG - Connection from 'tcp://10.0.59.223:57588' to Worker
    distributed.worker - INFO -         Registered to:           tcp://10.0.59.223:8192
    distributed.worker - INFO - -------------------------------------------------
    distributed.core - DEBUG - Message from 'tcp://10.0.59.223:52078': {'reply': False, 'op': 'compute-stream'}
    distributed.core - DEBUG - Calling into handler compute_stream
    distributed.core - DEBUG - Message from 'tcp://10.0.59.223:57588': {'reply': False, 'op': 'compute-stream'}
    distributed.core - DEBUG - Calling into handler compute_stream
    distributed.worker - DEBUG - Heartbeat: tcp://10.0.35.91:34959
    distributed.worker - DEBUG - Heartbeat: tcp://10.0.35.91:33587
```

Worker shutdown:

```
    distributed.dask_worker - INFO - Exiting on signal 15
    distributed.dask_worker - INFO - End worker
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:36883'
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:33523'
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:34013'
    distributed.worker - INFO - Stopping worker at tcp://10.0.35.91:34959
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:44319'
    distributed.worker - INFO - Stopping worker at tcp://10.0.35.91:33587
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:44195'
    distributed.worker - INFO - Stopping worker at tcp://10.0.35.91:33715
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:41375'
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:41109'
    distributed.worker - INFO - Stopping worker at tcp://10.0.35.91:34755
    distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.35.91:46695'
    distributed.worker - INFO - Stopping worker at tcp://10.0.35.91:40275
    distributed.worker - INFO - Stopping worker at tcp://10.0.35.91:43995
    tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f045bf5a368>
    Traceback (most recent call last):
      File "...site-packages/tornado/ioloop.py", line 605, in _run_callback
        ret = callback()
      File "...site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "...site-packages/tornado/ioloop.py", line 626, in _discard_future_result
        future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "...site-packages/distributed/nanny.py", line 135, in _start
        response = yield self.instantiate()
      File "...site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "...site-packages/distributed/nanny.py", line 194, in instantiate
        yield self.process.start()
      File "...site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "...site-packages/distributed/nanny.py", line 300, in start
        yield self._wait_until_running()
      File "...site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "...site-packages/distributed/nanny.py", line 385, in _wait_until_running
        raise ValueError("Worker not started")
    ValueError: Worker not started
    tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f045bf5a368>
    Traceback (most recent call last):
      File "...site-packages/tornado/ioloop.py", line 605, in _run_callback
        ret = callback()
      File "...site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "...site-packages/tornado/ioloop.py", line 626, in _discard_future_result
        future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "...site-packages/distributed/nanny.py", line 135, in _start
        response = yield self.instantiate()
      File "...site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "...site-packages/distributed/nanny.py", line 194, in instantiate
        yield self.process.start()
      File "...site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "...site-packages/distributed/nanny.py", line 300, in start
        yield self._wait_until_running()
      File "...site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "...site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "...site-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "...site-packages/distributed/nanny.py", line 385, in _wait_until_running
        raise ValueError("Worker not started")
    ValueError: Worker not started
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=10, interval=2
    distributed.comm.tcp - DEBUG - Setting TCP user timeout: 30000 ms
    Traceback (most recent call last):
      File ".../dask-worker", line 9, in <module>
        load_entry_point('distributed==1.17.1', 'console_scripts', 'dask-worker')()
      File "...site-packages/distributed/cli/dask_worker.py", line 231, in go
        main()
      File "...site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "...site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "...site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "...site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "...site-packages/distributed/cli/dask_worker.py", line 226, in main
        loop.run_sync(close_all)
      File "...site-packages/tornado/ioloop.py", line 457, in run_sync
        raise TimeoutError('Operation timed out after %s seconds' % timeout)
    tornado.ioloop.TimeoutError: Operation timed out after None seconds
    distributed.process - WARNING - reaping stray process <Process(Process-5, started daemon)>
    distributed.process - WARNING - reaping stray process <Process(Process-1, started daemon)>
```

**Comment by konrad-roze** [comment]
Just as an update to this one. We moved from using --nprocs on cluster workers to launching and babysitting separate worker processes under our own process manager. With this setup we don't have stray processes anymore. Seems like --nprocs doesn't work well in distributed setup.

**Comment by mrocklin** [comment]
Thank you for taking the time to respond here with your solution @konrad-roze .  I apologize for not being more responsive on this.

**Comment by karims** [comment]
> Just as an update to this one. We moved from using --nprocs on cluster workers to launching and babysitting separate worker processes under our own process manager. With this setup we don't have stray processes anymore. Seems like --nprocs doesn't work well in distributed setup.

Can u tell how to do this? I am facing the same issue.

**Comment by tarjintor** [comment]
me too
I am use dask in kubernetes.
