### ISSUE TITLE
Strange worker shutdowns and lost tasks

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1249]
I'm trying to narrow down the cause, and I don't have anything deterministically reproducible yet. But the symptom is that during my usage of a distributed cluster, my workers decide to shut down for some reason. For instance -

On the scheduler:

    2017-07-10 14:28:51,487 [INFO] distributed.scheduler | Remove worker tcp://...:44210
    2017-07-10 14:28:51,494 [INFO] distributed.scheduler | Removed worker tcp://...:44210
    2017-07-10 14:28:51,494 [ERROR] distributed.scheduler | Workers don't have promised keys. This should 
    never occur
    NoneType: None

On the worker corresponding to the removed worker above (timestamp corresponds, just different offset for whatever reason) - this leads to the worker/nanny process exiting with exit code 0. I have no idea who is trying to shut it down or why!?

    2017-07-10 18:28:51,495 [INFO] distributed.worker | Stopping worker at tcp://...:44210
    2017-07-10 18:28:51,507 [INFO] distributed.worker | Close compute stream
    2017-07-10 18:30:03,811 [INFO] distributed.worker | Comm closed
    2017-07-10 18:30:03,819 [ERROR] distributed.worker | Thread Pool Executor error: cannot schedule new futures after shutdown
    2017-07-10 18:30:03,820 [INFO] distributed.nanny | Closing Nanny at 'tcp://...:53147'
    2017-07-10 18:30:04,040 [INFO] distributed.dask_worker | End worker

Sometimes I get a bunch of RPC errors on the worker (`distributed.core.RPCClosed`) that interrupt the fairly clean log I see above.  For example (from another run / worker):

	2017-07-10 17:00:33,032 [INFO] distributed.core | Collecting unused comms.  open: 512, active: 43
	2017-07-10 17:03:04,110 [INFO] distributed.core | Collecting unused comms.  open: 512, active: 21
	2017-07-10 17:04:08,631 [INFO] distributed.worker | Stopping worker at tcp://172.23.70.173:46711
	2017-07-10 17:04:13,495 [INFO] distributed.worker | Comm closed
	2017-07-10 17:04:22,495 [INFO] distributed.worker | Comm closed
	2017-07-10 17:04:22,495 [INFO] distributed.worker | Close compute stream
	[17:04:27.868 ERROR  ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f92f010b510>, {'client': 'Client-3da8588c-658f-11e7-b0d4-248a07799e50', 'op': 'client-releases-keys', 'keys': ['SelectColumns_54b7ababbf_20030101_20030401_meta_False']})
	Traceback (most recent call last):
	  File "/lib/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback
		ret = callback()
	  File "/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
		return fn(*args, **kwargs)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8-py3.5.egg/distributed/batched.py", line 101, in send
		raise CommClosedError
	distributed.comm.core.CommClosedError
	[17:04:27.904 ERROR  ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f92f0e30ea0>, {'client': 'Client-3da8588c-658f-11e7-b0d4-248a07799e50', 'op': 'client-releases-keys', 'keys': ['SelectColumns_18564e68b4_20011001_20020101_meta_False']})
	Traceback (most recent call last):
	  File "/lib/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback
		ret = callback()
	  File "/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
		return fn(*args, **kwargs)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8-py3.5.egg/distributed/batched.py", line 101, in send
		raise CommClosedError
	distributed.comm.core.CommClosedError
	2017-07-10 17:04:29,850 [ERROR] distributed.utils | RPC Closed: while trying to call remote method 'who_has'
	Traceback (most recent call last):
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8-py3.5.egg/distributed/core.py", line 429, in send_recv_from_rpc
		comm = yield self.live_comm()
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 307, in wrapper
		yielded = next(result)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8-py3.5.egg/distributed/core.py", line 392, in live_comm
		raise RPCClosed("RPC Closed")
	distributed.core.RPCClosed: RPC Closed

I don't know what is closing my worker. Then, inevitably, I see a cascade of other errors in my main process driving the dask interaction, some of which are:

   ----
    result = f.result()
    File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 157, in result
    raise result
    TypeError: exceptions must derive from BaseException

----
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 1050, in submit
		resources={skey: resources} if resources else None)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 1859, in _graph_to_futures
		'submitting_task': getattr(thread_state, 'key', None)})
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 628, in _send_to_scheduler
		raise Exception("Client not running.  Status: %s" % self.status)
	Exception: Client not running.  Status: closed
----
	Traceback (most recent call last):
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/comm/tcp.py", line 170, in read
		n_frames = yield stream.read_bytes(8)
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	tornado.iostream.StreamClosedError: Stream is closed

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/core.py", line 430, in send_recv_from_rpc
		result = yield send_recv(comm=comm, op=key, **kwargs)
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
		yielded = self.gen.throw(*exc_info)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/core.py", line 316, in send_recv
		response = yield comm.read()
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
		yielded = self.gen.throw(*exc_info)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/comm/tcp.py", line 184, in read
		convert_stream_closed_error(self, e)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/comm/tcp.py", line 122, in convert_stream_closed_error
		raise CommClosedError("in %s: %s" % (obj, exc))
	distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
		result = f.result()
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 153, in result
		self._result, raiseit=False, callback_timeout=timeout)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/utils.py", line 234, in sync
		six.reraise(*error[0])
	  File "/lib/python3.5/site-packages/six.py", line 686, in reraise
		raise value
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/utils.py", line 223, in f
		result[0] = yield make_coro()
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
		yielded = self.gen.throw(*exc_info)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 178, in _result
		result = yield self.client._gather([self])
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
		yielded = self.gen.throw(*exc_info)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/client.py", line 1259, in _gather
		response = yield self.scheduler.gather(keys=keys2)
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
		value = future.result()
	  File "/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
		raise_exc_info(self._exc_info)
	  File "<string>", line 4, in raise_exc_info
	  File "/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
		yielded = self.gen.throw(*exc_info)
	  File "/lib/python3.5/site-packages/distributed-1.18.0+1.ge7c74cf8.dirty-py3.5.egg/distributed/core.py", line 433, in send_recv_from_rpc
		% (e, key,))
	distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'gather'

**Comment by adamklein** [comment]
Perhaps this is the result of a timeout somewhere in the code, I'm tinkering with timeouts again and it seems to alleviate the issue. It  would be nice to see in the log whether `distributed.worker | Stopping worker at tcp://...:44210` has a cause attached to it - I don't see a timeout specifically and I'm not sure how to trace back to what caused this.

**Comment by adamklein** [comment]
I have a hypothesis that the `ConnectionPool` on the worker machine whose default size is `512` is running out of connections (all my workers talk to each other) and I'm getting time outs even when the timeout is very large because it has to wait for new connections to open up. I'm trying to validate this hypothesis now. It might be helpful to put warnings when you start to exhaust connections ...

**Comment by adamklein** [comment]
Closing, don't think this is still an issue for me.
