### ISSUE TITLE
Occasional spurious stack trace 

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1273]
We get the following spurious output, probably because of the combination of our kernel and our virtual environment:

	Traceback (most recent call last):
	  File "lib/python3.5/site-packages/tornado/ioloop.py", line 1026, in _run
		return self.callback()
	  File "lib/python3.5/site-packages/distributed/system_monitor.py", line 38, in update
		ioc = psutil.net_io_counters()
	  File "lib/python3.5/site-packages/psutil/__init__.py", line 2087, in net_io_counters
		rawdict = _psplatform.net_io_counters()
	  File "lib/python3.5/site-packages/psutil/_pslinux.py", line 934, in net_io_counters
		with open_text("%s/net/dev" % get_procfs_path()) as f:
	  File "lib/python3.5/site-packages/psutil/_pslinux.py", line 204, in open_text
		return open(fname, "rt", **kwargs)
	NotADirectoryError: [Errno 20] Not a directory: '/proc/net/dev'

Seems similar to this: https://github.com/DataDog/dd-agent/issues/1175

Wondering if it's easy to quiet down / ignore.

**Comment by mrocklin** [comment]
Yes, that's certainly doable.  We could either disable the system monitor entirely or just avoid collecting that data with a try-except block.

**Comment by mrocklin** [comment]
cc @jcrist , if you have time and interest

**Comment by jcrist** [comment]
@adamklein, this *should* be fixed in #1280. If you have a chance to test this patch it'd be much appreciated.
