### ISSUE TITLE
Error Timed out  running distributed.Client

### ISSUE THREAD

**Issue by sephib** [dask/distributed#1282]
Hi  
I'm trying to run the [distributed example-computation](http://distributed.readthedocs.io/en/latest/web.html#example-computation)  from the `dask` documentation , from a  stand alone `Windows Server 2012R2` that is not connected to the Internet.    
When I try to run the following line  
`client = Client('127.0.0.1:8786')`
I'm getting the following error (the first line of the error is probably due to the lack of `Internet` connection)

```
C:\ProgramData\Anaconda3\lib\site-packages\distributed\utils.py:114: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [WinError 10051] A socket operation was attempted to an unreachable network
  % (host, default, e), RuntimeWarning)  
distributed.utils - ERROR - Timed out trying to connect to 'tcp://127.0.0.1:8786' after 5 s: in <distributed.comm.tcp.TCPConnector object at 0x000000804B862C88>: ConnectionRefusedError: [Errno 10061] Unknown error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\comm\core.py", line 185, in connect
    quiet_exceptions=EnvironmentError)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.gen.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\utils.py", line 223, in f
    result[0] = yield make_coro()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\client.py", line 680, in _start
    yield self._ensure_connected(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\client.py", line 714, in _ensure_connected
    connection_args=self.connection_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\comm\core.py", line 194, in connect
    _raise(error)
  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\comm\core.py", line 177, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://127.0.0.1:8786' after 5 s: in <distributed.comm.tcp.TCPConnector object at 0x000000804B862C88>: ConnectionRefusedError: [Errno 10061] Unknown error
```
  
Any suggestions?

**Comment by mrocklin** [comment]
Have you started a local `dask-scheduler` process?  http://distributed.readthedocs.io/en/latest/setup.html

**Comment by sephib** [comment]
No I didn't - so I added  
```
from distributed import LocalCluster
c = LocalCluster(processes=False)
```
and then changed to 
`client = Client(c)`
Now it is working - Thx!
