### ISSUE TITLE
TypeError: update_graph() got an unexpected keyword argument 'submitting_task'

### ISSUE THREAD

**Issue by tadas-subonis** [dask/distributed#1287]
I am getting this exception on the scheduler

I am using version 0.15.0 of Dask

The client just hangs waiting for the result

```
distributed.scheduler - INFO - Close client connection: Client-83dfa074-7140-11e7-9378-a08cfd80144d
distributed.core - ERROR - update_graph() got an unexpected keyword argument 'submitting_task'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 260, in handle_comm
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 1140, in add_client
    yield self.handle_client(comm, client=client)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 1213, in handle_client
    result = handler(**msg)
TypeError: update_graph() got an unexpected keyword argument 'submitting_task'
```

**Comment by mrocklin** [comment]
I suspect that you have a version mismatch of dask.distributed .  You might try calling 

    client.get_versions(check=True)

**Comment by tadas-subonis** [comment]
Actually, I just fixed that by reinstall dask and distributed from conda. I think I had "distributed" from pypi which is newer.

**Comment by mrocklin** [comment]
You can use the newer version, but you need to use it everywhere.  The error you experienced was from having different versions of scheduler and client

**Comment by tadas-subonis** [comment]
Thanks for the client.get_versions(check=True)

On Jul 25, 2017 17:14, "Matthew Rocklin" <notifications@github.com> wrote:

You can use the newer version, but you need to use it everywhere. The error
you experienced was from having different versions of scheduler and client

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dask/distributed/issues/1287#issuecomment-317751010>,
or mute the thread

**Comment by mrocklin** [comment]
Closing as resolved.  Let me know if there is still an issue here and we can reopen.
