### ISSUE TITLE
TypeError: 'Future' object is not iterable when using dask.bag.Bag.accumulate with get=dask.get

### ISSUE THREAD

**Issue by ogrisel** [dask/distributed#1294]
Here is a reproduction case (I tried to simplify it but could not get rid of the scikit-learn dependency even tough it seems unrelated):

```
pip install scipy scikit-learn 
```

```python
import numpy as np
import scipy.sparse as sp
from sklearn.linear_model import SGDClassifier
import dask
import dask.bag as db

n_features = int(1e3)
n_informative = int(1e2)

n_chunks = int(1e1)
chunk_size = int(1e2)

rng = np.random.RandomState(42)
true_coef = rng.randn(n_features)
true_coef[n_informative:] = 0


def make_chunk(n_samples, true_coef, chunk_idx, format='csr',
               density=1e-3, noise=1e-1):
    rng = np.random.RandomState(chunk_idx)
    n_features = true_coef.shape[0]
    input_data = sp.rand(n_samples, n_features, format=format,
                         density=density, random_state=rng)
    noise = rng.normal(loc=0, scale=noise, size=n_samples)
    target = input_data.dot(true_coef).ravel() + noise
    return chunk_idx, input_data, (target > 0).astype(np.int32)


def scan_fit(model, next_chunk):
    chunk_idx, X, y = next_chunk
    return model.partial_fit(X, y, classes=[0, 1])


if __name__ == "__main__":
    from distributed import Client
    client = Client()
    b = db.from_sequence([(chunk_size, true_coef, i)
                          for i in range(n_chunks)])
    b = b.starmap(make_chunk).persist()

    model = SGDClassifier(loss='log', penalty='l1')
    last_delayed = b.accumulate(scan_fit, initial=model).to_delayed()[-1]

    # Using the distributed scheduler works:
    print("distributed scheduler")
    print(last_delayed.compute()[0])

    # Trying to use the single-threaded dask scheduler on a pipeline of delayed
    # operations defined **after** the distributed client was initialized:
    print("sequential scheduler")
    print(last_delayed.compute(get=dask.get)[0])
```

The second call to `compute` (the one with `get=dask.get`) triggers the following exception:

```
Traceback (most recent call last):
  File "/home/ogrisel/tmp/dask_bug.py", line 51, in <module>
    print(last_delayed.compute(get=dask.get)[0])
  File "/home/ogrisel/code/dask/dask/base.py", line 98, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ogrisel/code/dask/dask/base.py", line 205, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/ogrisel/code/dask/dask/local.py", line 562, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "/home/ogrisel/code/dask/dask/local.py", line 508, in get_async
    fire_task()
  File "/home/ogrisel/code/dask/dask/local.py", line 504, in fire_task
    callback=queue.put)
  File "/home/ogrisel/code/dask/dask/local.py", line 551, in apply_sync
    res = func(*args, **kwds)
  File "/home/ogrisel/code/dask/dask/local.py", line 295, in execute_task
    result = pack_exception(e, dumps)
  File "/home/ogrisel/code/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/home/ogrisel/code/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/home/ogrisel/code/dask/dask/bag/core.py", line 1275, in accumulate_part
    res = list(accumulate(binop, seq, initial=initial))
  File "/home/ogrisel/.virtualenvs/py36/lib/python3.6/site-packages/toolz/itertoolz.py", line 58, in accumulate
    seq = iter(seq)
TypeError: 'Future' object is not iterable
```

I filed this problem on the distributed issue track because it does not happen if I comment out the `client = Client()` line so it has to be related to distributed in one way or another.

I use the current master branches both for dask and distributed.

**Comment by ogrisel** [comment]
Note that I also get a bunch of logs such as:

```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fe703a1a378>, {'op': 'client-releases-keys', 'keys': ["('starmap-make_chunk-3c8262eb9692bd18b8c1b64d44596c66', 8)"], 'client': 'Client-0c45ce30-721c-11e7-b21c-4485002c84f4'})
Traceback (most recent call last):
  File "/home/ogrisel/.virtualenvs/py36/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/ogrisel/.virtualenvs/py36/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ogrisel/code/distributed/distributed/batched.py", line 101, in send
    raise CommClosedError
distributed.comm.core.CommClosedError
```

I did not get those logs when using the last released version of distributed.

**Comment by mrocklin** [comment]
After you call `persist()` your data lives in the dask.distributed workers.  When you then call `compute(get=dask.get)` the local scheduler doesn't know how to locate this data.  The bag's task graph now contains futures which point to remote data but the single machine scheduler doesn't know how to interpret these.

**Comment by ogrisel** [comment]
Indeed I just discovered that in //. Then it's a matter of improving the error message.

**Comment by mrocklin** [comment]
I'm also curious about your logged errors.  Do those occur as you close down the cluster or during the error?

**Comment by ogrisel** [comment]
I get them even when I don't make the second call that triggers the error.

**Comment by mrocklin** [comment]
When do you get them?  During normal operation or when you close your cluster/interpreter?

**Comment by ogrisel** [comment]
Here is a simpler reproduction case now that I understood that the `Client()` /  `persist()` combo is the cause of the problem:

```
import dask
import dask.bag as db


if __name__ == "__main__":
    from distributed import Client
    client = Client()
    b = db.from_sequence(range(10)).map(lambda x: x ** 2).persist()

    from operator import add
    result = b.fold(add)

    # Using the distributed scheduler works:
    print("distributed scheduler")
    print(result.compute())

    # Trying to use the single-threaded dask scheduler on a pipeline of delayed
    # operations defined **after** the distributed client was initialized:
    print("sequential scheduler")
    print(result.compute(get=dask.get))
```

**Comment by ogrisel** [comment]
I get the log when quitting the interpreter.

**Comment by mrocklin** [comment]
> Then it's a matter of improving the error message.

I agree with this.  The challenge here is that the single machine scheduler has no knowledge of the distributed scheduler.  From its perspective the task graph has all of these strange `Future` objects where instead there should be lists or numpy arrays or something.

cc @jcrist for thoughts on how we might be able to cleanly improve error reporting here

**Comment by ogrisel** [comment]
When calling `.persist` on a `Delayed` instance there should be a way to let the currently active backend to tag the `Delayed` instance that it can only be "computed" by itself from that point on.

**Comment by jcrist** [comment]
The best option that comes to mind would be to add checks in the local scheduler for futures in the graph and error if found. We'd need to check for futures inside tasks, lists, and (I think) dicts. Could probably tack it on to an existing pass through the graph somewhere. To keep decoupled from distributed could do either:

```python
try:
    import distributed
    def is_future(x):
        return isinstance(x, distributed.Future)
except:
    def is_future(x):
        return False
```

or 

```python
def is_future(x):
    typ = type(x)
    return typ.__name__ == 'Future' and typ.__module__.startswith('distributed')
```
