### ISSUE TITLE
Unhandled exception when shutting down client and cluster

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#1310]
Came up in dask_drmaa, which uses a `LocalCluster(n_workers=0, ip='')`

```python
import time
import sys
from distributed import Client, LocalCluster

if __name__ == '__main__':
    cluster = LocalCluster(n_workers=0, ip='')
    client = Client(cluster)
    time.sleep(1)
    sys.exit(0)
```

The stacktrace isn't always the same, but probably has the same underlying issue (which I haven't discovered yet)

```pytb
Exception ignored in: <generator object handle_client at 0x10a73a410>
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/distributed/distributed/scheduler.py", line 1254, in handle_client
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 125, in __exit__
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

```pytb
Exception ignored in: <generator object add_client at 0x1115695c8>
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/distributed/distributed/scheduler.py", line 1168, in add_client
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 319, in wrapper
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1001, in __init__
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1143, in handle_yield
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/functools.py", line 803, in wrapper
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/functools.py", line 778, in dispatch
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/weakref.py", line 394, in __getitem__
TypeError: 'NoneType' object is not callable
```

**Comment by TomAugspurger** [comment]
Hmm https://github.com/dask/distributed/issues/1283 looks pretty similar (I'm running the latest master though).

After some more tests, it seems like the it doesn't matter whether there are no workers or no IP; these just seem to increase the likelihood that the exception occurs.

**Comment by mrocklin** [comment]
These may have been resolved by https://github.com/dask/distributed/pull/1318 ?

**Comment by TomAugspurger** [comment]
Yeah, I'm not seeing it on master anymore. Thanks.
