### ISSUE TITLE
Job fails when I use an InfiniBand network with Dask!

### ISSUE THREAD

**Issue by mkhoshle** [dask/distributed#1312]
Hi I am trying to run my job on a cluster with a high performance network (InfiniBand). I specified the  network interface to the dask-scheduler and dask-worker executables. I setup my network using 
```
dask-scheduler --interface ib0  --port=8786
ssh $host dask-worker --interface ib0 --nprocs 24 --nthreads 1 $SCHEDULER:8786 
```

I am ruuning a simple test case, but it fails. 

```
#!/usr/bin/env python
from dask.distributed import Client
import sys
from dask import delayed

Scheduler_IP = sys.argv[1]
#SLURM_JOBID = sys.argv[2]
print (Scheduler_IP)
print (type (Scheduler_IP))
#print (Client(Scheduler_IP))
c = Client(Scheduler_IP)

def your_function(i):
    from distributed.worker import thread_state
    key = thread_state.key
    return key

out = []
for i in range(72):
    out.append(delayed(your_function)(i))

out = delayed(out)
out = out.compute(get=c.get)

print(out)
```
The version of different packages is as below:
```
cloudpickle-0.3.1 dask-0.15.1 distributed-1.18.0 tornado-4.5.1
```
Here is the error:

```
distributed.utils - ERROR - Timed out trying to connect to 'tcp://comet-22-15.sdsc.edu:8786' after 5 s: in <distributed.comm.tcp.TCPConnector object at 0x2b25cf54b4d0>: error: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/client.py", line 680, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/client.py", line 714, in _ensure_connected
    connection_args=self.connection_args)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/comm/core.py", line 194, in connect
    _raise(error)
  File "/home/mkhoshle/miniconda2/lib/python2.7/site-packages/distributed/comm/core.py", line 177, in _raise
    raise IOError(msg)
```

Does anyone know why this is failing?

**Comment by mkhoshle** [comment]
I was providing the wrong name for the interface!  So I close this issue!
