### ISSUE TITLE
CommClosedError when using client.submit

### ISSUE THREAD

**Issue by mkhoshle** [dask/distributed#1340]
Hi I am trying to run the following example in my notebook, but I get the following error when I use client.submit:
```
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f417b08d6d8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/nfs/homes/mkhoshle/.local/lib/python2.7/site-packages/distributed/batched.py", line 101, in send
    raise CommClosedError
CommClosedError
```
and here is the code I am trying to run:
```
import numpy as np
import pandas as pd
from distributed import Client
from distributed.diagnostics import progress

def test_model(k, n, seed=42):
    np.random.seed(seed)
    # ...
    return {'sparsity': k, 'n_observations': n, 'success': 1 if error < 0.1 else 0}

client = Client('yamsolo:8786')
data = [client.submit(test_model, k, n, seed=repeat*n*k)
        for n in np.logspace(1, 3, num=60)
        for k in np.logspace(1, 1.7, num=40, dtype=int)
        for repeat in range(10)]
```
Does anyone know why I am getting this error?

**Comment by mrocklin** [comment]
What is the status of the client when the error occurs?  Are you able to provide a minimal reproducible example that others can try to reproduce the error?  Are you on master?

**Comment by xwang777** [comment]
Did you wait on the "data" list? If not, the program will exit after the "data = ..." line and probably the async send  in the background will be writing to a closed socket and may cause this error?

**Comment by mkhoshle** [comment]
@mrocklin Thanks. The status of the client was running. I restarted my workers and it is working. 
It was happening on my own code, and I just tried  the above code to see if I get the error or not. But I have no idea why this happens sometimes. I am not able to get rid of it by client.restart or client.shutdown. I just have to kill all the dask workers and restart them again to get it to work. 
@xwang777  No, I did not.

**Comment by mrocklin** [comment]
Are you able to provide a minimal reproducible example that others can try to reproduce the error?  If you can produce a small example that we can use to reproduce your error locally then that will help us to be able to identify and resolve the problem.  

https://stackoverflow.com/help/mcve

**Comment by mkhoshle** [comment]
@mrocklin Thanks. OK, I will try to see if I can reproduce the problem!

**Comment by quakberto** [comment]
Hi, I am getting the same error.

In my case, I have dask-workers running on a cluster and whenever I start a LocalCluster on my local machine, they would connect to its scheduler. My submitted tasks would then also sometimes lead to erred futures and erred_future.exception() also shows the CommClosedError.

I can't produce a MCVE and the errors seem to occur randomly. However, I'm thinking this inconsistent behaviour might be related to the following:
While trying out things I'm constantly killing and restarting the local process containing the scheduler. I started to notice that tasks were more likely to fail right after killing a scheduler and submitting tasks with a freshly invoked one. Now, after restarting the workers on the cluster (scheduler.restart()) and then also restarting the scheduler, so far I haven't experienced any erred futures anymore.

So might the errors be related to some internal state of the workers which is kept although they connect to a new scheduler?

**Comment by mrocklin** [comment]
It is not unreasonable to expect a `CommClosedError` when unexpectedly closing a scheduler, worker, or client
