### ISSUE TITLE
Worker shutdown causes cluster job to fail

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1352]
We're deploying dask.distributed on EC2 cluster. A typical case is to terminate one of the worker instances (e.g. due to downscaling or host replacement). I'd expect the cluster to survive the case of disappearing workers (with loss of some data of course), but it seems to (randomly) cause cluster jobs to fail either with CancelledError or KilledWorker. Host replacement is not an uncommon situation - what can we do to protect ourselves against it? Is there any way to shutdown the worker in a graceful way?

Currently workers seem to receiver either SIGTERM or SIGKILL directly.
I've seen two failure cases:
1) CancelledError

```
distributed.client - WARNING - Client report stream closed to scheduler
distributed.utils - ERROR - list-b9b8877a-7ed3-4f38-8c26-53651b35a1b5
Traceback (most recent call last):
  File "...site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "...site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "...site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "...site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "...site-packages/distributed/client.py", line 1152, in _gather
    None)
  File "<string>", line 2, in reraise
CancelledError: list-b9b8877a-7ed3-4f38-8c26-53651b35a1b5
Traceback (most recent call last):
  File "clean_data.py", line 201, in <module>
    cleaned.to_textfiles('s3://...')
  File "...site-packages/dask/bag/core.py", line 647, in to_textfiles
    compute, get=get)
  File "...site-packages/dask/bag/core.py", line 186, in to_textfiles
    delayed(out).compute(get=get)
  File "...site-packages/dask/base.py", line 97, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "...site-packages/dask/base.py", line 204, in compute
    results = get(dsk, keys, **kwargs)
  File "...site-packages/distributed/client.py", line 1764, in get
    results = self.gather(packed)
  File "...site-packages/distributed/client.py", line 1263, in gather
    direct=direct)
  File "...site-packages/distributed/client.py", line 489, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "...site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "...site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "...site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "...site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "...site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "...site-packages/distributed/client.py", line 1152, in _gather
    None)
  File "<string>", line 2, in reraise
concurrent.futures._base.CancelledError: list-b9b8877a-7ed3-4f38-8c26-53651b35a1b5
```

2) KilledWorker

```
distributed.utils - ERROR - ('read-block-860000000-d6b7e8b51f9a707af5634868329f5741', 'tcp://...')
Traceback (most recent call last):
  File "...site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "...site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "...site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "...site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "...site-packages/distributed/client.py", line 1156, in _gather
    traceback)
  File "<string>", line 2, in reraise
KilledWorker: ('read-block-860000000-d6b7e8b51f9a707af5634868329f5741', 'tcp://...')
Traceback (most recent call last):
  File "test.py", line 150, in <module>
    f2.to_csv('s3://....csv')
  File "...site-packages/dask/dataframe/core.py", line 960, in to_csv
    return to_csv(self, filename, **kwargs)
  File "...site-packages/dask/dataframe/io/csv.py", line 481, in to_csv
    delayed(values).compute(get=get)
  File "...site-packages/dask/base.py", line 97, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "...site-packages/dask/base.py", line 204, in compute
    results = get(dsk, keys, **kwargs)
  File "...site-packages/distributed/client.py", line 1764, in get
    results = self.gather(packed)
  File "...site-packages/distributed/client.py", line 1263, in gather
    direct=direct)
  File "...site-packages/distributed/client.py", line 489, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "...site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "...site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "...site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "...site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "...site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "...site-packages/distributed/client.py", line 1156, in _gather
    traceback)
  File "<string>", line 2, in reraise
distributed.scheduler.KilledWorker: ('read-block-860000000-d6b7e8b51f9a707af5634868329f5741', 'tcp://...')
```

**Comment by mrocklin** [comment]
`KilledError` is caused when the same task is on five workers that have been unexpectedly killed.  In this case the task is deemed too suspicious to run again, and so it errs.  You can solve this in two ways:

1.  Increase the `allowed-failures` config option in `~/.dask/config.yaml` to a very high number
2.  Close workers gracefully, such as with the `scheduler.retire_workers` command.

```python
client.sync(client.scheduler.retire_workers, workers=[...], close_workers=True)
```

This tries to move data off of the worker before it shuts down.

**Comment by konrad-roze** [comment]
Thanks, seem that `allowed-failures` might be what we need - we run multiprocessing workers, so shutdown of one host takes out more than 5 of them. EC2 can always take down host without notifying us, so option 2 doesn't fully solve the problem.

**Comment by mrocklin** [comment]
The cost to this option is that now the following can send your cluster into a bad state of continuously shutting down and starting up workers:

```python
import sys
future = client.submit(sys.exit, 0)
```

**Comment by mrocklin** [comment]
When EC2 shuts down a worker does it give you any warning?  Ideally you want to interface with a resource scheduler that says "I need to reclaim this machine, you have 60 seconds to clean up gracefully".

**Comment by konrad-roze** [comment]
In general - yes, we can work around this problem by setting up lifecycle hooks on auto-scaling-group and try to retire the workers to avoid losing data.
