### ISSUE TITLE
How to silence tornado errors (with observed work-stealing KeyError)

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1364]
Using this contrived example (as of 2379eec92e0d6805dd2c669ad440b59a10d1e3d9) to ask a couple questions:

	from distributed import LocalCluster, Client, worker_client
	import time

	def task_of_task(i):
		time.sleep(1)
		return i

	def task(i):
		with worker_client() as wc:
			return wc.submit(task_of_task, i)

	if __name__ == "__main__":
		lc = LocalCluster()
		client = Client(lc)
		futs = [client.submit(task, i) for i in range(25)]
		results = client.gather(futs)
		print(results)

First: this results in an error that I've seen in other contexts -

	tornado.application - ERROR - Exception in callback <bound method WorkStealing.balance of <distributed.stealing.WorkStealing object at 0x7f982a6ef2b0>>
	Traceback (most recent call last):
	  File "lib/python3.5/site-packages/tornado/ioloop.py", line 1026, in _run
		return self.callback()
	  File "lib/python3.5/site-packages/distributed-1.18.1+14.gff153322-py3.5.egg/distributed/stealing.py", line 231, in balance
		duration = s.processing[sat][key]
	KeyError: 'task_of_task-56c5e9c3ab5dfd64b7ab1d4037fc6d2e'

Second: this and other tornado errors coming from workers are not silenced because the `silence_logging` seems to apply only to `distributed` hierarchy. Is there a way to suppress them?

**Comment by mrocklin** [comment]
Taking a look now

**Comment by adamklein** [comment]
Also, this is basically my setup generating lots of verbose tornado errors:

    from distributed import LocalCluster, Client, worker_client, as_completed
    import time
    
    
    def task(i):
        time.sleep(1)
        if i == 10:
            raise Exception("Boom")
        return i
    
    
    def cancel_all(client):
        for w, tlist in client.processing().items():
            if len(tlist):
                client.cancel(tlist)
    
    
    if __name__ == "__main__":
        lc = LocalCluster()
        client = Client(lc)
    
        watch = as_completed(loop=client.loop)
    
        for i in range(25):
            watch.add(client.submit(task, i))
    
        for f in watch:
            e = f.exception()
            if not e:
                print(f.result())
            else:
                cancel_all(client)
                raise e

This generates tons of:

	tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fc324455158>, <tornado.concurrent.Future object at 0x7fc3244caf60>)                                                                                                                                         
	Traceback (most recent call last):                                                                                                                           
	  File "lib/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback                                             
		ret = callback()                                                                                                                                         
	  File "lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper                                       
		return fn(*args, **kwargs)                                                                                                                               
	  File "lib/python3.5/site-packages/tornado/ioloop.py", line 626, in _discard_future_result                                    
		future.result()                                                                                                                                          
	  File "lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result                                                
		raise_exc_info(self._exc_info)                                                                                                                           
	  File "<string>", line 4, in raise_exc_info                                                                                                                 
	  File "lib/python3.5/site-packages/tornado/gen.py", line 1063, in run                                                         
		yielded = self.gen.throw(*exc_info)                                                                                                                      
	  File "/home/aklein/src/distributed/distributed/client.py", line 2943, in track_future                                                                      
		yield _wait(future)                                                                                                                                      
	  File "lib/python3.5/site-packages/tornado/gen.py", line 1055, in run                                                         
		value = future.result()                                                                                                                                  
	  File "lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result                                                
		raise_exc_info(self._exc_info)                                                                                                                           
	  File "<string>", line 4, in raise_exc_info                                                                                                                 
	  File "lib/python3.5/site-packages/tornado/gen.py", line 1069, in run                                                         
		yielded = self.gen.send(value)                                                                                                                           
	  File "/home/aklein/src/distributed/distributed/client.py", line 2826, in _wait                                                                             
		raise CancelledError(cancelled)                                                                                                                          
	concurrent.futures._base.CancelledError: ['task-34e907e7cf97f71ea3ffba6b0e483f5f']     

Presumably from throwing an exception out of the `as_completed` iterator. How do I properly do `raise e`?

**Comment by mrocklin** [comment]
It's fairly trivial to turn of tornado logging generally.  

```diff
gmrocklin@carbon:~/workspace/distributed$ git diff distributed/deploy/local.py
diff --git a/distributed/deploy/local.py b/distributed/deploy/local.py
index 34deb6e..adf486c 100644
--- a/distributed/deploy/local.py
+++ b/distributed/deploy/local.py
@@ -71,6 +71,7 @@ class LocalCluster(object):
         self.silence_logs = silence_logs
         if silence_logs:
             silence_logging(level=silence_logs)
+            silence_logging(level=silence_logs, root='tornado')
         if n_workers is None and threads_per_worker is None:
             if processes:
                 n_workers = _ncores
```

However I'd like to get to why these errors are popping up.  

In the first case with stealing it looks to me like this only shows up during shutdown.  I suspect that we are not cleaning up the stealing extension's state when we lose a worker.  The second case with as_completed seems a bit more serious to me.

**Comment by mrocklin** [comment]
Taking a look now, though my afternoon is about to be sacrificed to meetings :/

**Comment by adamklein** [comment]
Nice, thanks for the quick turnaround!

**Comment by adamklein** [comment]
Think we can close this out -
