### ISSUE TITLE
Wrong lower bound of tornado requirement

### ISSUE THREAD

**Issue by bluenote10** [dask/distributed#1369]
Distributed 0.18.1 has a requirement of `>=4.4.3` on tornado, but it seems that it actually needs a newer tornado version (it is working with 4.5.2). For instance:

```bash
$ pip install distributed==1.18.1 tornado==4.4.3
$ dask-scheduler &
$ dask-worker tcp://10.128.4.209:8786
```

results in

```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.128.4.209:41351'
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/bin/dask-worker", line 11, in <module>
    sys.exit(go())
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/distributed/cli/dask_worker.py", line 270, in go
    main()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/distributed/cli/dask_worker.py", line 258, in main
    loop.run_sync(run)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/distributed/cli/dask_worker.py", line 253, in run
    yield [n.start(addr) for n in nannies]
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 1097, in handle_yield
    self.future = convert_yielded(yielded)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 1223, in convert_yielded
    return multi(yielded)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 686, in multi
    return multi_future(children, quiet_exceptions=quiet_exceptions)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 778, in multi_future
    children = list(map(convert_yielded, children))
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask_tmp/local/lib/python2.7/site-packages/tornado/gen.py", line 1229, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
tornado.gen.BadYieldError: yielded unknown object None
distributed.process - WARNING - reaping stray process <Process(Process-1, started daemon)>
distributed.dask_worker - INFO - Exiting on signal 15
```

**Comment by mrocklin** [comment]
Confirmed.  I suspect that I'll make another micro-release in the next few days.

**Comment by mrocklin** [comment]
Thank you for raising this issue @bluenote10

**Comment by bluenote10** [comment]
Great thanks! 

Have you considered also modelling the dependency on bokeh explicitly? As far as I can see, bokeh currently does not exist as a proper extra requirement, i.e., the dependency between distributed/tornado vs bokeh remains unclear. I think the tornado 4.4 based versions want bokeh ~0.12.4 while the new tornado 4.5 based version seem to have a hard requirement on 0.12.7. It would be nice if these dependencies were explicitly specified.

**Comment by mrocklin** [comment]
I'm not sure I understand your last comment.  It's not clear to me that this issue is due to bokeh at all.  

Bokeh is an optional dependency for dask.distributed.  Tornado is a hard requirement.  It looks like recent code dask.distributed genuinely requires tornado 4.5.

**Comment by bluenote10** [comment]
What I meant is that the dashboard only works with certain Bokeh versions. For instance with the current distributed 0.18.1 and tornado 4.5.2 I see the following behavior:

- bokeh 0.12.4 -- index.html works but all apps time out
- bokeh 0.12.5 -- index.html works but all apps time out
- bokeh 0.12.6 -- Crashes when launching the scheduler (in `start_services` / `scheduler.py`)
- bokeh 0.12.7 -- works

It would be nice to specify this dependency explicitly by having an extra dependency, e.g. `bokeh>=0.12.7` for the current versions because older bokeh versions don't work. This would allow users to install `distributed[bokeh]` or maybe `dask[bokeh]` and automatically get an appropriate version.

**Comment by mrocklin** [comment]
I see, yes, something like that might make sense.  It's a little odd to
model Bokeh's version issues within Dask though.  I wonder if there is a
way to push this concern upstream.  This isn't just that Dask dashboards
don't work, it's that all Bokeh server applications don't work with certain
tornado versions.
