### ISSUE TITLE
Unknown opcode error on tutorial

### ISSUE THREAD

**Issue by alvarouc** [dask/distributed#1373]
I setup a cluster with 4 servers. The first server is the scheduler, call it 'A'. The other three are workers ('B', 'C', 'D'). 

WIth I run the compute line on tutorial https://github.com/dask/dask-tutorial/blob/master/04_distributed.ipynb with 'B', I get the following error: 

```
distributed.utils - ERROR - unknown opcode
Traceback (most recent call last):
  File "/home/aeulloacerna/.virtualenvs/main/lib/python3.4/site-packages/distributed/utils.py", line 227, in f
    result[0] = yield make_coro()
  File "/home/aeulloacerna/.virtualenvs/main/lib/python3.4/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/aeulloacerna/.virtualenvs/main/lib/python3.4/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/aeulloacerna/.virtualenvs/main/lib/python3.4/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aeulloacerna/.virtualenvs/main/lib/python3.4/site-packages/distributed/client.py", line 1246, in _gather
    traceback)
  File "/home/aeulloacerna/.virtualenvs/main/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "<ipython-input-2-dc5253b6f090>", line 9, in dec
    time.sleep(3)
SystemError: unknown opcode
```

Could you help me figure out what went wrong?

A is running red hat. B,C,D are running debian. Before running the dask-scheduler and dask-worker commands, I activated a virtual enviroment.

**Comment by mrocklin** [comment]
You might want to verify that you are using identical versions of Python,
dask, etc.. on all machines.  Try client.get_versions(check=True) .

**Comment by alvarouc** [comment]
I tried that and I got missmatch for bokeh and pandas, would that be an issue?

bokeh
+--------------------------+---------+
|                          | version |
+--------------------------+---------+
| client                   | 0.12.7  |
| tcp://... | None    |
| tcp://...| None    |
+--------------------------+---------+

pandas
+-----------+---------+
|           | version |
+-----------+---------+
| client    | 0.20.3  |
| scheduler | None    |
+-----------+---------+

**Comment by mrocklin** [comment]
Can you try running with identical software environments everywhere and see
if the issue goes away?

**Comment by alvarouc** [comment]
Will do, I appreciate your help.

**Comment by alvarouc** [comment]
You are right, the problem was that one worker had python 3.6 on it. Once I put every worker and scheduler to 3.4 it worked. 

Thanks Again, I just wish this came up as a warning when you call dask-worker

**Comment by mrocklin** [comment]
Raised https://github.com/dask/distributed/issues/1376
