### ISSUE TITLE
distributed.utils - ERROR - 'int' object is not iterable

### ISSUE THREAD

**Issue by stscript** [dask/distributed#1374]
when I invoke `d.to_csv('/tmp/tt-*.csv')` the d is a dask.dataFrame
```
distributed.utils - ERROR - 'int' object is not iterable
Traceback (most recent call last):
  File "/data/db1/anaconda3/lib/python3.6/site-packages/distributed/utils.py", line 229, in f
    result[0] = yield make_coro()
  File "/data/db1/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/data/db1/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/data/db1/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/data/db1/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 1246, in _gather
    traceback)
  File "/data/db1/anaconda3/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
  File "/opt/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 800, in _make_skel_func
  File "/opt/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 792, in _reconstruct_closure
TypeError: 'int' object is not iterable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-71871b188704> in <module>()
----> 1 d.to_csv('/tmp/tt-*.csv')

/data/db1/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py in to_csv(self, filename, **kwargs)
    957         """ See dd.to_csv docstring for more information """
    958         from .io import to_csv
--> 959         return to_csv(self, filename, **kwargs)
    960 
    961     def to_delayed(self):

/data/db1/anaconda3/lib/python3.6/site-packages/dask/dataframe/io/csv.py in to_csv(df, filename, name_function, compression, compute, get, storage_options, **kwargs)
    503 
    504     if compute:
--> 505         delayed(values).compute(get=get)
    506     else:
    507         return values

/data/db1/anaconda3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
     97             Extra keywords to forward to the scheduler ``get`` function.
     98         """
---> 99         (result,) = compute(self, traverse=False, **kwargs)
    100         return result
    101 

/data/db1/anaconda3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    204     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    205     keys = [var._keys() for var in variables]
--> 206     results = get(dsk, keys, **kwargs)
    207 
    208     results_iter = iter(results)

/data/db1/anaconda3/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, **kwargs)
   1921         if sync:
   1922             try:
-> 1923                 results = self.gather(packed, asynchronous=asynchronous)
   1924             finally:
   1925                 for f in futures.values():

/data/db1/anaconda3/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1366             return self.sync(self._gather, futures, errors=errors,
   1367                              direct=direct, local_worker=local_worker,
-> 1368                              asynchronous=asynchronous)
   1369 
   1370     @gen.coroutine

/data/db1/anaconda3/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    538             return future
    539         else:
--> 540             return sync(self.loop, func, *args, **kwargs)
    541 
    542     def __str__(self):

/data/db1/anaconda3/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    239         e.wait(1000000)
    240     if error[0]:
--> 241         six.reraise(*error[0])
    242     else:
    243         return result[0]

/data/db1/anaconda3/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
    685             raise value.with_traceback(tb)
--> 686         raise value
    687 
    688 else:

/data/db1/anaconda3/lib/python3.6/site-packages/distributed/utils.py in f()
    227             yield gen.moment
    228             thread_state.asynchronous = True
--> 229             result[0] = yield make_coro()
    230         except Exception as exc:
    231             logger.exception(exc)

/data/db1/anaconda3/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1053 
   1054                     try:
-> 1055                         value = future.result()
   1056                     except Exception:
   1057                         self.had_exception = True

/data/db1/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py in result(self, timeout)
    236         if self._exc_info is not None:
    237             try:
--> 238                 raise_exc_info(self._exc_info)
    239             finally:
    240                 self = None

/data/db1/anaconda3/lib/python3.6/site-packages/tornado/util.py in raise_exc_info(exc_info)

/data/db1/anaconda3/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1061                     if exc_info is not None:
   1062                         try:
-> 1063                             yielded = self.gen.throw(*exc_info)
   1064                         finally:
   1065                             # Break up a reference to itself

/data/db1/anaconda3/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1244                             six.reraise(type(exception),
   1245                                         exception,
-> 1246                                         traceback)
   1247                     if errors == 'skip':
   1248                         bad_keys.add(key)

/data/db1/anaconda3/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

/opt/anaconda3/lib/python3.6/site-packages/distributed/protocol/pickle.py in loads()

/opt/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in _make_skel_func()

/opt/anaconda3/lib/python3.6/site-packages/cloudpickle/cloudpickle.py in _reconstruct_closure()

TypeError: 'int' object is not iterable
```

**Comment by mrocklin** [comment]
Try updating cloudpickle?

**Comment by mrocklin** [comment]
I take it that that resolved the issue?
