### ISSUE TITLE
Stopping a submitted function in Jupyter Notebook results in <FutureState: error> and a needed restart

### ISSUE THREAD

**Issue by gregsifr** [dask/distributed#1375]
The client enters a `<FutureState: error>` state when a job is submitted to the client and the kernel is stopped.

This is a problem because once in that state, no other jobs can be completed (`client.gather(result)` blocks but does not complete for any submitted future jobs). 

The only way to progress is to restart the Jupyter notebook kernel.

Instructions to reproduce, paste this code into a Jupyter Notebook cell:
```
import time
from dask.distributed import Client

client = Client()

def add(a,b):
    time.sleep(60)
    return a+b

def square(a):
    return a**2
```

Then run the below code and stop the kernel **prior** to the function completing (<60s).
```
result = client.submit(add, 1, 4)
client.gather(result)
```

Checking the client futures, we can see an error FutureState:
```
>>> client.futures
{'add-962bd7f68184e275518de72ad6b32ed9': <FutureState: error>}
```

Attempting to execute other functions thereafter results in the `client.gather` function blocking any further execution:
```
result2 = client.submit(square, 5)
client.gather(result2)
```

The only way to revert back to the expected behaviour is to restart the Jupyter notebook kernel (which is not ideal if a lot of data has been loaded from disk)

**Comment by mrocklin** [comment]
What kernel are you referring to?

**Comment by gregsifr** [comment]
Jupyter notebook (ipython) kernel

**Comment by mrocklin** [comment]
You have started the cluster within that process though, no?  So wouldn't you expect everything to stop?  I may not understand things clearly.

**Comment by gregsifr** [comment]
Correct, the cluster was started within that process. The problem is that the client becomes unresponsive when fetching results after a submitted job was stopped by the user prior to the job being finished (stopped and not a kernel restart).

**Comment by gregsifr** [comment]
Use case: user loads a large amount of data and submits a function for that data. The user then spots a problem with the function they submitted and stops it prior to its completion.

**Comment by gregsifr** [comment]
By stopping the job I meant clicking on the stop button in Jupyter notebook (the stop button below):
![image](https://user-images.githubusercontent.com/9390695/30064803-35dd7b6e-9296-11e7-994e-7fd9f06b6e24.png)

**Comment by mrocklin** [comment]
OK, for future reference you're not stopping a job, you're signaling a `KeyboardInterrupt`.  This is the same as pressing `Ctrl-C` on the keyboard.

I can reproduce this, which is good.  It seems like all of the workers choose to die as well when you throw a `KeyboardInterrupt`.  The simple way to avoid this short term is to make a dask-scheduler and dask-workers outside of your Jupyter notebook session

```
$ dask-scheduler
$ dask-worker localhost:8786
```

I'll have to track down why the workers are also dying when using the LocalCluster.

**Comment by mrocklin** [comment]
cc @adamklein this may interest you.

**Comment by adamklein** [comment]
Yep, interests me. FYI, I tried to get around SIGINT propagating to the local cluster, but it doesn't work.

    def spawn_cluster():
        """
        Spawn a local dask cluster. Also prevent SIGINT / KeyboardInterrupt from taking down our local cluster
        by preventing it from propagating through the multiprocessing pool.
         """
        original_sigint_handler = signal.signal(signal.SIGINT, signal.SIG_IGN)
        cluster = LocalCluster()
        signal.signal(signal.SIGINT, original_sigint_handler)
        return cluster

**Comment by mrocklin** [comment]
After interrupting I get the following logs:

```
distributed.worker - DEBUG - future state: add-b04aa734cfd341f18da4e9b81a4b8e40 - RUNNING
distributed.worker - DEBUG - future state: add-b04aa734cfd341f18da4e9b81a4b8e40 - RUNNING
distributed.worker - DEBUG - future state: add-b04aa734cfd341f18da4e9b81a4b8e40 - RUNNING
distributed.worker - DEBUG - future state: add-b04aa734cfd341f18da4e9b81a4b8e40 - RUNNING

^C  # Keyboard interrupt happens here

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mrocklin/Software/anaconda/lib/python3.6/multiprocessing/forkserver.py", line 164, in main
    rfds = [key.fileobj for (key, events) in selector.select()]
  File "/home/mrocklin/Software/anaconda/lib/python3.6/selectors.py", line 445, in select
distributed.process - DEBUG - [<AsyncProcess ForkServerProcess-1>] process 6998 exited with code 0
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
distributed.process - DEBUG - [<AsyncProcess ForkServerProcess-2>] process 7002 exited with code 0
distributed.process - DEBUG - [<AsyncProcess ForkServerProcess-3>] process 7000 exited with code 0
distributed.process - DEBUG - [<AsyncProcess ForkServerProcess-4>] process 7004 exited with code 0
```

It's slightly concerning the forkserver code is what comes up here in the traceback.

cc @pitrou

**Comment by mrocklin** [comment]
This behavior has been around since at least 1.16.2

**Comment by mrocklin** [comment]
By the way @gregsifr thank you for producing such a clean example of this issue

**Comment by adamklein** [comment]
This actually works:

	def spawn_cluster(diagn_port, max_par):
		"""
		Spawn a local dask cluster. Also prevent SIGINT / KeyboardInterrupt from taking down our local cluster
		by preventing it from propagating through the multiprocessing pool.
		 """
		import multiprocessing
		import sys
		
		parent, child = multiprocessing.Pipe()
		
		def _start(dport, nworkers, die, pipe):
			with LocalCluster(diagnostics_port=dport, n_workers=nworkers, threads_per_worker=1) as lc:
				pipe.send(lc.scheduler_address)
				die.wait()
		
		die_event = multiprocessing.Event()
		p = multiprocessing.Process(target=_start, args=(diagn_port, max_par, die_event , child,))
		original_sigint_handler = signal.signal(signal.SIGINT, signal.SIG_IGN)
		p.start()
		signal.signal(signal.SIGINT, original_sigint_handler)
		port = parent.recv()
		# print(port)
		return (port, die_event)

    cluster_info = spawn_cluster(0, 1)

    #  .... do stuff via Client(cluster_info[0]), and CTRL-C all you want

    cluster_info[1].set()

**Comment by pitrou** [comment]
> It's slightly concerning the forkserver code is what comes up here in the traceback.

Yes, basically a Ctrl-C can kill the forkserver process. This is https://bugs.python.org/issue31308 upstream (the fix is ready to apply and I don't expect a lot of controversy over it).

**Comment by mrocklin** [comment]
It looks like the next release date (tenative) for CPython is 2017-10-02

https://www.python.org/dev/peps/pep-0494/
