### ISSUE TITLE
CancelledErrors on distributed dask jobs

### ISSUE THREAD

**Issue by konrad-roze** [dask/distributed#1497]
Hi,

We're using dask distributed on EC2 cluster, however for more complex jobs with bigger data and more dependencies (at this moment its hard to tell what is the class of graphs that fail) I'm consistently seeing **CancelledError**.

We're using Python 2.7, distributed 1.19.2 and dask 0.15.4 at the moment.
Tracebacks look like this:

```
Traceback (most recent call last):
 ...
  File "...", line 109, in execute
    self.client.gather(futures)
  File ".../site-packages/distributed/client.py", line 1391, in gather
    asynchronous=asynchronous)
  File ".../site-packages/distributed/client.py", line 561, in sync
    return sync(self.loop, func, *args, **kwargs)
  File ".../site-packages/distributed/utils.py", line 241, in sync
    six.reraise(*error[0])
  File ".../site-packages/distributed/utils.py", line 229, in f
    result[0] = yield make_coro()
  File ".../site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File ".../site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File ".../site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File ".../site-packages/distributed/client.py", line 1265, in _gather
    None)
  File "<string>", line 2, in reraise
CancelledError: finalize-ee1e7f7285d58905bea741955b7b7f89
```
Jobs read data from CSV on S3 and after processing store them in another CSV on S3.

I've tried quite a few things, but cannot reproduce this problem locally, even when running workers manually in separate processes on the same host.

Logs are set to debug level, but I cannot see any ERROR messages neither in worker nor in scheduler logs.

I'm a running out of ideas and a bit desperate because it's a serious stability issue. Is there anything specific I might look for in this case?

**Comment by konrad-roze** [comment]
After some more investigation I've found that the reason is actually network communication. 
Load balancer was dropping connections after they were idle for 1 minute (which apparently happens pretty often). So it's misconfiguration issue, but some more informative error message in such case would be super-helpful!
