### ISSUE TITLE
Possibility to use IPythom.embed() on workers

### ISSUE THREAD

**Issue by bluenote10** [dask/distributed#1505]
Follow-up on our discussion with @mrocklin: It would be nice to use `IPython.embed()` directly in a worker for debugging purposes (in a cluster running locally). Example usage:

```python
from distributed import Client

def logic_to_run_on_worker():
    # ... imagine complex logic here ...
    # local embed for debugging
    import IPython
    IPython.embed()

client = Client("tcp://10.128.4.209:8786")
client.run(logic_to_run_on_worker)
```

This currently fails with

```
Traceback (most recent call last):
  File "dask_test.py", line 9, in <module>
    client.run(logic_to_run_on_worker)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/client.py", line 1819, in run
    return self.sync(self._run, function, *args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/client.py", line 559, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 248, in sync
    six.reraise(*error[0])
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 236, in f
    result[0] = yield make_coro()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/distributed/client.py", line 1773, in _run
    six.reraise(*clean_exception(**resp))
  File "dask_test.py", line 6, in logic_to_run_on_worker
    IPython.embed()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 383, in embed
    frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 158, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 439, in __init__
    self.init_prompt_toolkit_cli()
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 274, in init_prompt_toolkit_cli
    output=create_output(true_color=self.true_color))
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 81, in __init__
    self.input = input or StdinInput(sys.stdin)
  File "/home/PHI-TPS/fkeller/.virtualenvs/dask/local/lib/python2.7/site-packages/prompt_toolkit/input.py", line 67, in __init__
    assert self.stdin.isatty()
AssertionError
```

Maybe only a minor change is necessary to make this work and it could be optionally enabled via the Dask config.

**Comment by mrocklin** [comment]
I don't know much about the error you're seeing, I'll defer to @minrk 

Min, more generally how far we could take IPython integration?  For example I can imagine calling `dask_pdb()` or something in the worker task that starts IPython, sends connection information to all relevant clients, and then waits until they connect up.  Any thoughts on additional uses or approaches that you think would be helpful?

**Comment by minrk** [comment]
The isatty error is a bug that I think is fixed in more recent prompt-toolkit and/or IPython.

For a local cluster, this works now as long as `--no-nanny` is passed. I guess the nanny is wrapping the worker's stdin and/or stdout in a way that disrupts its ability to control the terminal. It will only work for one worker per terminal, of course.

But if you want an IPython *kernel*, this should work anywhere. `IPython.embed_kernel()` works ~the same as `IPython.embed()`, but launches a listening kernel instead of terminal IPython. The tricky bit is likely propagating connection info.

The second problem you are likely to run into with something like `dask_pdb()` is talking to a bunch of IPython instances at the same time can be tedious. This is basically all IPython parallel does, though, so if you launched IPython *engines* instead of kernels, you could use IPython parallel to talk to everybody.

There is not yet an `embed_engine()` to put it in a calling namespace, but this is always doable. Ultimately, it's just how the interactive namespace is initialized.

**Comment by bluenote10** [comment]
@minrk Thanks! I can confirm that using `--no-nanny` allows exactly what I was trying to do, awesome. Maybe it is sufficient to add this information to the documentation on debugging possibilities?

**Comment by minrk** [comment]
I looked into it a bit more, and multiprocessing explicitly closes sys.stdin for subprocesses. You can reopen it with:

```python
sys.stdin = os.fdopen(0)
```

to reverse the severing of the link. Maybe it makes sense for nannies to do this by default.

**Comment by minrk** [comment]
#1506 causes nannied processes to inherit stdin, which allows this to work by default.
