### ISSUE TITLE
Error when given an unhashable function

### ISSUE THREAD

**Issue by kelvyang** [dask/distributed#1614]
https://github.com/dask/distributed/blob/b258495e5e7e877170de7e0a3f03657dc8b26199/distributed/worker.py#L669

distributed will throw an error when given an unhashable function.
```
>>> import distributed
>>> client = distributed.Client()
>>> dct = {'a': 1}
>>> getter = dct.get
>>> dsk = {'return': (getter, 'a')}
>>> client.get(dsk, 'return')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/distributed/client.py", line 1975, in get
    resources=resources)
  File "/usr/local/lib/python3.6/site-packages/distributed/client.py", line 1936, in _graph_to_futures
    'tasks': valmap(dumps_task, dsk3),
  File "/usr/local/lib/python3.6/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 742, in dumps_task
    return {'function': dumps_function(task[0]),
  File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 705, in dumps_function
    if func not in cache:
TypeError: unhashable type: 'dict'
```

Functions are not hashable if their closure contains unhashable objects. Any time you have code like `if func in dict` you need to wrap it in a try/except block.

The solution is to wrap line 669 in a try/except block.

**Comment by mrocklin** [comment]
Agreed.  Thank you for identifying the issue.  

Can I interest you in submitting a PR with a fix?

**Comment by kelvyang** [comment]
@mrocklin unfortunately I can't contribute before acquiring approval from my company. Doing that would require some time, it may be faster for someone else to fix it.

**Comment by kelvyang** [comment]
@mrocklin Thanks!
