### ISSUE TITLE
Test failure on Tornado git master

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#1622]
There is a single test failure when running the test suite with Tornado git master (excluding Bokeh-and IPython-related tests), both under Python 2.7 and 3.6:
```
========================================================================= FAILURES =========================================================================
__________________________________________________________________ test_workers_to_close ___________________________________________________________________
Traceback (most recent call last):
  File "/home/antoine/distributed/distributed/utils_test.py", line 723, in test_func
    result = loop.run_sync(coro, timeout=timeout)
  File "/home/antoine/tornado/tornado/ioloop.py", line 521, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
tornado.util.TimeoutError: Operation timed out after 10 seconds
------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------
distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:33977
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:35501
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:35501
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    8.35 GB
distributed.worker - INFO -       Local Directory: /home/antoine/distributed/dask-worker-space/worker-ssw4ovw1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:43253
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:43253
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    8.35 GB
distributed.worker - INFO -       Local Directory: /home/antoine/distributed/dask-worker-space/worker-7p76rlrp
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:42055
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:42055
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    8.35 GB
distributed.worker - INFO -       Local Directory: /home/antoine/distributed/dask-worker-space/worker-0cuh8_fi
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:36653
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:36653
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    8.35 GB
distributed.worker - INFO -       Local Directory: /home/antoine/distributed/dask-worker-space/worker-om218ztt
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Register tcp://127.0.0.1:35501
distributed.scheduler - INFO - Register tcp://127.0.0.1:43253
distributed.scheduler - INFO - Register tcp://127.0.0.1:42055
distributed.scheduler - INFO - Register tcp://127.0.0.1:36653
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:35501
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:43253
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:42055
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:36653
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:33977
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Receive client connection: Client-aa2ae17a-dddb-11e7-9e65-14dae9deda7e
===================================================================== warnings summary =====================================================================
```

**Comment by GenevieveBuckley** [comment]
I believe this is outdated and can be closed. 
If I'm incorrect @pitrou please feel free to reopen with some more context. Thank you!
