### ISSUE TITLE
Sporadic hangs with LocalCluster

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1628]
The following code sporadically hangs for me (maybe 1 in 3 times) . 

It hangs after creating the worker processes. Taking a quick look in a debugger, `LocalCluster._start_all_workers` sometimes gets called more than once -- I suspect something to do with the way tornado is used, but I can't easily see quite what.

distributed==1.20.2 (I can't see any changes in master that would be relevant)
tornado==4.5.2

```python
import socket
from distributed import LocalCluster

ip = socket.gethostbyname(socket.gethostname())
cluster = LocalCluster(ip=ip, scheduler_port=8786)
print(cluster)
```

**Comment by mrocklin** [comment]
I'm running this code in a loop and am unable to get it to hang.  Can you say more about how this occurs or any output that might arise in logs?

**Comment by mrocklin** [comment]
But yes, it is possible for this to call `_start_all_workers` multiple times.  Good catch.

**Comment by mrocklin** [comment]
Hrm, actually no, I think I'm mistaken.  I don't yet see a path for `_start_all_workers` to be called twice in that situation.

**Comment by rbubley** [comment]
I have the code above in a file, `test.py`.

Sometimes:
```
russ $ python test.py
LocalCluster('tcp://192.168.1.80:8786', workers=8, ncores=8)
```
And others, it just hangs until I press ctrl-c.
```
russ  $ python test.py
^CTraceback (most recent call last):
  File "test.py", line 5, in <module>
    cluster = LocalCluster(ip=ip, scheduler_port=8786)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/deploy/local.py", line 107, in __init__
    sync(self.loop, self._start, ip)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/utils.py", line 252, in sync
    e.wait(1000000)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
```

**Comment by mrocklin** [comment]
Here is my attempt to reproduce:

```
(27) mrocklin@carbon:~$ cat foo.py
if __name__ == '__main__':

    import socket
    from distributed import LocalCluster

    ip = socket.gethostbyname(socket.gethostname())
    cluster = LocalCluster(ip=ip, scheduler_port=8786)
    print(cluster)

(27) mrocklin@carbon:~$ for i in {1..100}; do python foo.py; done
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
LocalCluster('tcp://127.0.1.1:8786', workers=4, ncores=4)
```

**Comment by rbubley** [comment]
It seems to be a difference between python 2.7 and 3.6. (My default python is 2.7.14).

It works fine for me when I run it with python 3.6; the problem only seems to crop up in 2.7.

**Comment by mrocklin** [comment]
I ran my example in Python 2.7 as well after seeing that you were using 2.7 (from your filenames)

**Comment by rbubley** [comment]
It's reproducible on my development mac, but I don't see a problem on a windows or a linux box. Not sure if this is a mac-specific issue, or something broken in my environment.

**Comment by mrocklin** [comment]
I'm away from my OSX machine this week but can take a look when I get back
to it.

**Comment by rbubley** [comment]
I’ve reproduced on a second OSX machine now, so yes, it would be great to check if you see it too.
