### ISSUE TITLE
Dask worker fails to start

### ISSUE THREAD

**Issue by rstuckey** [dask/distributed#1694]
I'm having issues starting some workers, but not others, on different machines in our cluster. The OS (Ubuntu 14.04.5 LTS), Python installation (Anaconda Python 3.6.2) and virtual environment are all the same, but there may be some small differences in the system configuration.

I'm running the latest releases: dask-core-0.16.1, dask-0.16.1, distributed-1.20.2 and tornado-4.5.3.

Below is the trace produced when I try to start a worker. At this step, the scheduler has already been started and another worker connected successfully. The error at the bottom is repeated several times before I kill the processes.

Hopefully someone will be able to spot the problem without me having to attempt debugging on this headless machine :)

Cheers

```
$ /opt/anaconda3/bin/dask-worker --nprocs 4 131.185.105.97:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://131.185.105.87:60916'
distributed.nanny - INFO -         Start Nanny at: 'tcp://131.185.105.87:50080'
distributed.nanny - INFO -         Start Nanny at: 'tcp://131.185.105.87:43717'
distributed.nanny - INFO -         Start Nanny at: 'tcp://131.185.105.87:44671'
distributed.worker - INFO -       Start worker at: tcp://131.185.105.87:48855
distributed.worker - INFO -          Listening to: tcp://131.185.105.87:48855
distributed.worker - INFO -              nanny at:       131.185.105.87:50080
distributed.worker - INFO -              bokeh at:        131.185.105.87:8789
distributed.worker - INFO - Waiting to connect to:  tcp://131.185.105.97:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                   16.71 GB
distributed.worker - INFO -       Local Directory:            worker-60s0nq8p
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at: tcp://131.185.105.87:60919
distributed.worker - INFO -          Listening to: tcp://131.185.105.87:60919
distributed.worker - INFO -              nanny at:       131.185.105.87:44671
distributed.worker - INFO -              bokeh at:       131.185.105.87:51796
distributed.worker - INFO - Waiting to connect to:  tcp://131.185.105.97:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at: tcp://131.185.105.87:54953
distributed.worker - INFO -       Start worker at: tcp://131.185.105.87:54825
distributed.worker - INFO -          Listening to: tcp://131.185.105.87:54825
distributed.worker - INFO -              nanny at:       131.185.105.87:60916
distributed.worker - INFO -              bokeh at:       131.185.105.87:36618
distributed.worker - INFO - Waiting to connect to:  tcp://131.185.105.97:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to: tcp://131.185.105.87:54953
distributed.worker - INFO -              nanny at:       131.185.105.87:43717
distributed.worker - INFO -              bokeh at:       131.185.105.87:55136
distributed.worker - INFO - Waiting to connect to:  tcp://131.185.105.97:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                   16.71 GB
distributed.worker - INFO -                Memory:                   16.71 GB
distributed.worker - INFO -       Local Directory:            worker-9_8u0qxq
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory:            worker-mok5hhci
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                   16.71 GB
distributed.worker - INFO -       Local Directory:            worker-hxkxqzc5
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/nanny.py", line 508, in run
    yield worker._start(*worker_start_args)
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 365, in _start
    yield self._register_with_scheduler()
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 283, in _register_with_scheduler
    self.scheduler_delay = response['time'] - middle
TypeError: string indices must be integersdistributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/nanny.py", line 508, in run
    yield worker._start(*worker_start_args)
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 365, in _start
    yield self._register_with_scheduler()
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 283, in _register_with_scheduler
    self.scheduler_delay = response['time'] - middle
TypeError: string indices must be integers
```

**Comment by mrocklin** [comment]
I strongly suspect that this is due to a version mismatch of of the `distributed` library.

**Comment by rstuckey** [comment]
I just checked. The version (1.20.2) is identical on the scheduler and all worker nodes.

**Comment by mrocklin** [comment]
Can I ask you to run client.get_versions(check=True)

**Comment by mrocklin** [comment]
Another vote in favor of https://github.com/dask/distributed/issues/1678
