### ISSUE TITLE
Setting retries in client.compute() throws `TypeError: unhashable type: 'list'`

### ISSUE THREAD

**Issue by tmoerman** [dask/distributed#1697]
Hi,

When setting the `retries` parameter on a distributed Client instance, e.g. `client.compute(retries=2)`, I get: `TypeError: unhashable type: 'list'`. 

Following code snippet reproduces the problem:

```
import dask
from dask.dataframe import from_delayed
from dask import delayed
import distributed
from distributed import LocalCluster, Client
import pandas as pd


def to_df(i):
    return pd.DataFrame({'label': ['bla'], 'value': [i]})


def create_graph(n=5):
    dfs = []
    for i in range(0, n):
        delayed_to_df = delayed(to_df)(i)
        dfs.append(delayed_to_df)

    return from_delayed(dfs)


if __name__ == '__main__':

    print('dask version: {}'.format(dask.__version__))
    print('distributed version: {}'.format(distributed.__version__))
    print('pandas version: {}'.format(pd.__version__))

    client = Client(LocalCluster(n_workers=1, threads_per_worker=1))

    graph = create_graph()

    # works fine
    # result = client.compute(graph, sync=True)

    # throws: TypeError: unhashable type: 'list'
    result = client.compute(graph, sync=True, retries=2)

    print(result.head())
```
```
---
dask version: 0.16.1
distributed version: 1.20.2
pandas version: 0.20.3
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/tmo/work/batiskav/installs/anaconda3/lib/python3.5/site-packages/distributed/protocol/core.py", line 100, in loads
    msg = loads_msgpack(small_header, small_payload)
  File "/home/tmo/work/batiskav/installs/anaconda3/lib/python3.5/site-packages/distributed/protocol/core.py", line 177, in loads_msgpack
    return msgpack.loads(payload, encoding='utf8')
  File "msgpack/_unpacker.pyx", line 139, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2068)
TypeError: unhashable type: 'list'
```

Is there perhaps something I am doing wrong? Any help appreciated.

Thanks,
Th.

**Comment by mrocklin** [comment]
Thank you for the excellent example.  I suspect that this may have been resolved in master

```python
dask version: 0.16.1+9.g88aa608
distributed version: 1.20.2+37.ga775042.dirty
pandas version: 0.21.0
  label  value
0   bla      0
0   bla      1
0   bla      2
0   bla      3
0   bla      4
```

**Comment by mrocklin** [comment]
Closing for now.  Please let me know if the problem persists.
