### ISSUE TITLE
StreamClosedError when shutting down Dask network

### ISSUE THREAD

**Issue by rtuason** [dask/distributed#1703]
I use the Python API to initialize my scheduler and workers. At the end of a job, I shut down my Dask network by calling the following lines in the scheduler node:

```
for w in (scheduler.workers):
    scheduler.close_worker(worker=w)
scheduler.close()
```

However, I sometimes come across instances of tornado.iostream.StreamClosedError and distributed.comm.core.CommClosedError, as shown below by the sample output.

Things that I've tried but didn't work include:
- Using time.sleep() after the workers are closed and before the scheduler is closed
- Using the Logger module to silence messages from 'distributed' and 'tornado' that are less severe than 'critical' (in scheduler and worker nodes)

My output is as follows:

distributed.scheduler - INFO - Closing worker tcp://10.0.0.4:39769
distributed.scheduler - INFO - Remove worker tcp://10.0.0.4:39769
distributed.worker - INFO - Stopping worker at tcp://10.0.0.4:39769
distributed.worker - INFO - Close compute stream
distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.0.4:37151'
distributed.scheduler - INFO - Closing worker tcp://10.0.0.6:43747
distributed.scheduler - INFO - Remove worker tcp://10.0.0.6:43747
distributed.scheduler - INFO - Closing worker tcp://10.0.0.7:41835
distributed.scheduler - INFO - Remove worker tcp://10.0.0.7:41835
distributed.worker - INFO - Stopping worker at tcp://10.0.0.6:43747
distributed.worker - INFO - Close compute stream
distributed.scheduler - INFO - Lost all workers
distributed.worker - INFO - Stopping worker at tcp://10.0.0.7:41835

tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7f10f1936cf8> exception was never retrieved: Traceback (most recent call last):
  File "/home/.../lib/python3.5/site-packages/distributed/comm/tcp.py", line 174, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/worker.py", line 407, in _close
    yield r.terminate()
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/core.py", line 516, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/core.py", line 350, in send_recv
    response = yield comm.read()
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/comm/tcp.py", line 188, in read
    convert_stream_closed_error(self, e)
  File "/home/.../lib/python3.5/site-packages/distributed/comm/tcp.py", line 124, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: ConnectionResetError: [Errno 104] Connection reset by peer

distributed.worker - INFO - Close compute stream
distributed.nanny - INFO - Closing Nanny at 'tcp://10.0.0.7:43719'

tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7f34fc07c898> exception was never retrieved: Traceback (most recent call last):
  File "/home/.../lib/python3.5/site-packages/distributed/comm/tcp.py", line 174, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/worker.py", line 407, in _close
    yield r.terminate()
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/core.py", line 516, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/core.py", line 350, in send_recv
    response = yield comm.read()
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/.../lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/.../lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/.../lib/python3.5/site-packages/distributed/comm/tcp.py", line 188, in read
    convert_stream_closed_error(self, e)
  File "/home/.../lib/python3.5/site-packages/distributed/comm/tcp.py", line 124, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: ConnectionResetError: [Errno 104] Connection reset by peer

distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - End worker
distributed.dask_worker - INFO - End worker
distributed.scheduler - INFO - Exception from worker while closing: Timed out trying to connect to 'tcp://10.0.0.7:43719' after 3.0 s: in <distributed.comm.tcp.TCPConnector object at 0x7fb2ba4028d0>: ConnectionRefusedError: [Errno 111] Connection refused
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
distributed.client - WARNING - Client report stream closed to scheduler
distributed.scheduler - INFO - Connection to client Client-42e834da-f671-11e7-81a6-000d3a15cc34 broken
distributed.scheduler - INFO - Remove client Client-42e834da-f671-11e7-81a6-000d3a15cc34
distributed.scheduler - INFO - Close client connection: Client-42e834da-f671-11e7-81a6-000d3a15cc34

**Comment by mrocklin** [comment]
Note that close_worker is a tornado coroutine.  If you want those
operations to finish before closing the scheduler then you might want to
yield or await on the results of those calls.

**Comment by rtuason** [comment]
Thanks Matthew. I've edited my code as shown below, but I still occasionally see these StreamClosedErrors and CommClosedErrors. Is there something I'm missing?

```
my_scheduler.finished()
for w in my_scheduler.workers:
    yield my_scheduler.close_worker(worker=w)
my_scheduler.finished()
my_scheduler.close()
```

**Comment by mrocklin** [comment]
I would probably do something like the following:

```python
@gen.coroutine
def close_everything(scheduler):
    yield scheduler.retire_workers(workers=scheduler.workers, close_workers=True)
    yield scheduler.close()
```

**Comment by mrocklin** [comment]
This conversation seems to have finished.  Closing.
