### ISSUE TITLE
No locks available to Client

### ISSUE THREAD

**Issue by rstuckey** [dask/distributed#1707]
Hi again,

I'm having issues starting a client in the default local cluster mode:
```
(fdenv0) [stuckey@host ~]$ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask.distributed import Client
>>> client = Client()
Process ForkServerProcess-5:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/process.py", line 175, in _run
    target(*args, **kwargs)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/nanny.py", line 470, in _run
    worker = Worker(*worker_args, **worker_kwargs)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/worker.py", line 1101, in __init__
    WorkerBase.__init__(self, *args, **kwargs)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/worker.py", line 111, in __init__
    self._workdir = self._workspace.new_work_dir(prefix='worker-')
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/diskutils.py", line 219, in new_work_dir
    return WorkDir(self, **kwargs)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/diskutils.py", line 47, in __init__
    with workspace._global_lock():
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/locket.py", line 194, in __enter__
    self.acquire()
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/locket.py", line 188, in acquire
    self._lock.acquire(self._timeout, self._retry_period)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/locket.py", line 118, in acquire
    lock.acquire(timeout, retry_period)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/locket.py", line 162, in acquire
    _lock_file_blocking(self._file)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/locket.py", line 52, in _lock_file_blocking
    fcntl.flock(file_.fileno(), fcntl.LOCK_EX)
OSError: [Errno 37] No locks available
Process ForkServerProcess-14:
...
```

My home directory, which holds the `dask-worker-space` sub-directory, is an NFSv3 network mount. However, the annoying thing is, it works fine on another presumably identical system.

Specifying the `local_dir` to a local directory works, so I will probably use that as a workaround:
```
>>> from dask.distributed import Client, LocalCluster
>>> worker_kwargs = {'local_dir': '/tmp'}
>>> cluster = LocalCluster(**worker_kwargs)
>>> client = Client(cluster)
>>> client
<Client: scheduler='tcp://127.0.0.1:41803' processes=28 cores=28>
```

Here are the relevant packages in my current environment:
```
cytoolz                   0.8.2                    py36_0    conda-forge
dask                      0.16.1                     py_0    conda-forge
dask-core                 0.16.1                     py_0    conda-forge
distributed               1.20.2                   py36_0    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
```

Thanks for any help!

**Comment by mrocklin** [comment]
Interesting.  I think that @rabernat experienced a similar issue on a network file system.  It looks like we need to take a closer look at using file-based locks on network file systems.

**Comment by mrocklin** [comment]
Actually, googling the error message results in a possible solution that your NFS just may not be set up to provide file-based locks.  You might ask your system administrator.

Regardless, Dask should probably fail gracefully when it fails to acquire the lockfile.

**Comment by rstuckey** [comment]
Yep, we're looking into that now. Moving to NFSv4 may also solve the issue, though using a common `local_dir` as above is not a bad idea anyway.

**Comment by mrocklin** [comment]
By the way it looks like if you add the following line to your `~/.dask/config.yaml` file it will avoid file locking altogether

```yaml
use-file-locking: False
```

**Comment by mrocklin** [comment]
If you have an opportunity to try your situation with the fix in https://github.com/dask/distributed/pull/1714 I would appreciate it

**Comment by rstuckey** [comment]
Unfortunately, our sysadmin just increased the maximum number of NFS connections and locks on the shared filesystem and I am now getting a different error :/
```
(dd-test0) [stuckey@host distributed]$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask.distributed import Client
>>> client = Client()
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/stuckey/.conda/envs/dd-test0/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/stuckey/Workspace/distributed/distributed/deploy/local.py", line 175, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.gen.TimeoutError: Worker failed to start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stuckey/.conda/envs/dd-test0/lib/python3.6/site-packages/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/home/stuckey/.conda/envs/dd-test0/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/stuckey/.conda/envs/dd-test0/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/stuckey/Workspace/distributed/distributed/deploy/local.py", line 175, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.gen.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/stuckey/.conda/envs/dd-test0/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/stuckey/Workspace/distributed/distributed/deploy/local.py", line 175, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.gen.TimeoutError: Worker failed to start
...
```
And the error repeats several times.

I've tested both distributed 1.20.2 and git with #1714 . Also, tornado 4.5.3 and 5.0b1.

The `use-file-locking: False` workaround has no effect either, but the locking error may have been resolved by the system changes.

I don't know how helpful it is at this point, but a colleague of mine also found [this](http://chris.improbable.org/2010/12/16/everything-you-never-wanted-to-know-about-file-locking/) article, which recommends using `fcntl.lockf()` over `fcntl.flock()` on NFS...

**Comment by rstuckey** [comment]
I just tested `use-file-locking: False` in the original virtual env (fdenv0) and it does indeed work, resulting in a valid Client object. Removing it yields the same error as above (`tornado.gen.TimeoutError: Worker failed to start`). Not seeing the original error (`OSError: [Errno 37] No locks available`) anymore though :/

**Comment by rstuckey** [comment]
Ok, I am able to get it working with `use-file-locking: True` from a local (root) account. Our network accounts still produce the same `tornado.gen.TimeoutError: Worker failed to start` error, regardless of whether the virtual env is local (`~/.conda/envs/`) or global (`/opt/anaconda3/envs/`). It would appear that tornado is using our NFS-mounted `$HOME` directories somewhere and unable to start the workers. I'll continue looking into tornado to see if I can identify this latest issue, but the file locking may have been resolved as above.

**Comment by mrocklin** [comment]
Tracebacks are particularly welcome as I try to make the current system
robust to locking issues.

**Comment by mrocklin** [comment]
Any update here?

**Comment by mrocklin** [comment]
If you have a chance to try with the latest release I would appreciate it.

**Comment by mrocklin** [comment]
I'm glad things work, though I'm sorry about the 20s wait time.  If there are things that we should be doing to decrease this time then please help!
