### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'linspace'

### ISSUE THREAD

**Issue by kylebarron** [dask/distributed#1734]
The `dask-ssh` command didn't work for me.

```
> dask-ssh hostname1-hostname7
Traceback (most recent call last):
  File "/home/barronk/local/anaconda3/bin/dask-ssh", line 4, in <module>
    import distributed.cli.dask_ssh
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/distributed/__init__.py", line 5, in <module>
    from .deploy import LocalCluster
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/distributed/deploy/__init__.py", line 5, in <module>
    from .local import LocalCluster
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/distributed/deploy/local.py", line 13, in <module>
    from ..nanny import Nanny
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/distributed/nanny.py", line 25, in <module>
    from .worker import _ncores, run, parse_memory_limit
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 26, in <module>
    from . import profile
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/distributed/profile.py", line 223, in <module>
    palette = viridis(10)
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/bokeh/palettes.py", line 1160, in viridis
    return self.linear_palette(self.Viridis256, n)
  File "/home/barronk/local/anaconda3/lib/python3.6/site-packages/bokeh/palettes.py", line 1044, in linear_palette
    return [ palette[int(math.floor(i))] for i in np.linspace(0, len(palette)-1, num=n) ]
AttributeError: module 'numpy' has no attribute 'linspace'
```

`pip show dask numpy` says that I'm using version 1.13.3 of numpy and 0.16.1 of dask.

**Comment by kylebarron** [comment]
Actually this could be a pip vs conda issue..

**Comment by jcrist** [comment]
I've seen a similar error for other packages when the package is removed from `site_packages`, but the top-level folder remains. The module is then imported as a namespace package, which has no attributes. This sometimes happens when doing `pip uninstall` on a conda installed package.

**Comment by kylebarron** [comment]
I reinstalled the packages again in a conda environment and it's working fine now. Thanks!

**Comment by KalpitRathod** [comment]
Do yo have a file called numpy.py in your working directory?
If yes, rename it.

For your task in https://python-forum.io/Thread-Question-1-Count-symbols
you do not need numpy.
