### ISSUE TITLE
Single in-process worker hanging on largish problem

### ISSUE THREAD

**Issue by bmerry** [dask/distributed#1742]
When running the code below, it seems to run forever (I gave it 200 seconds), with the CPU usage very low (around 20% of one core). I saw no signs of memory exhaustion/swapping (note: my machine has 16GB - with less it may swap). With N_BLS reduced to 1024, it runs in 4-5 seconds, so assuming linear scaling, it should finish in 30-40 seconds.

Using Python 2.7.12, distributed f0a8495, dask 7f5c6eb (latest HEAD of each), tornado 4.5.3.

Sometimes I see errors like this instead:
```
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7f9d32767d60>
Traceback (most recent call last):
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/bruce/work/sdp/env/src/distributed/distributed/client.py", line 817, in _update_scheduler_info
    self._scheduler_identity = yield self.scheduler.identity()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/bruce/work/sdp/env/src/distributed/distributed/core.py", line 466, in send_recv_from_rpc
    comm = yield self.live_comm()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/bruce/work/sdp/env/src/distributed/distributed/core.py", line 442, in live_comm
    connection_args=self.connection_args)
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/bruce/work/sdp/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/bruce/work/sdp/env/src/distributed/distributed/comm/core.py", line 194, in connect
    _raise(error)
  File "/home/bruce/work/sdp/env/src/distributed/distributed/comm/core.py", line 177, in _raise
    raise IOError(msg)
IOError: Timed out trying to connect to 'inproc://192.168.0.4/18428/1' after 5 s: connect() didn't finish in time
```

With 3+ threads per worker it seems to work, with 2 it generally gives the exception above.

Code:
```python
#!/usr/bin/env python

from __future__ import division, print_function
import dask.array as da
import numpy as np
import time

from dask.distributed import Client, LocalCluster

cluster = LocalCluster(n_workers=1, threads_per_worker=1, processes=False)
client = Client(cluster)

N_TIMES = 100
N_CHANS = 256
N_BLS = 8192
SHAPE = (N_TIMES, N_CHANS, N_BLS)

vis_raw = np.full(SHAPE, 1.0, np.complex64)
vis = da.from_array(vis_raw, chunks=SHAPE, name=False)
vis = vis.rechunk({0: 4})

Bf = da.asarray(np.ones((1, N_CHANS, N_BLS), np.complex64))
Gf = da.asarray(np.ones((N_TIMES, 1, N_BLS), np.complex64))
vis *= Bf * Bf.conj()
vis *= Gf
vis = da.sum(vis, axis=0)
vis.compute()
```

**Comment by bmerry** [comment]
I forgot to mention: I've never used distributed before, so it's possible that my environment is just broken in some way rather than it being an issue with this particular code.

**Comment by bmerry** [comment]
I've tried it on another machine. It doesn't actually hang there and I haven't yet seen the timeout exception, but performance is crazily variable. It seems to either finish in 6.5-7s, or take over a minute (1m12 once, 1m8 another time).

**Comment by bmerry** [comment]
I think this is related to worker memory limits (which I hadn't realised existed). The first machine has 16GB and 8 virtual cores, so had only a 2GB memory limit and was presumably spilling to disk like crazy. The second machine has 32GB and 8 virtual cores, so a 4GB memory limit - which still caused spilling, but not as badly. With `memory_limit=0` I seem to get reasonable results out of the second machine (the first one is at home so I can't test it at the moment).

It's still strange that performance can vary by a factor of 10 with only a single worker (which I would have assumed should behave deterministically), but I guess that could be due to the psutil measurement giving variable results when deciding what to spill.

If you're happy that spilling explains the results then this can be closed.

**Comment by mrocklin** [comment]
memory limits only exist on the distributed scheduler

**Comment by bmerry** [comment]
> memory limits only exist on the distributed scheduler

Yes. To clarify, the difficulties I was having with the distributed scheduler were related to memory limits, and once I solved that problem, the distributed scheduler worked nicely and appears not to suffer from this bug. So it is only a bug in the non-distributed scheduler.

**Comment by mrocklin** [comment]
I'm curious, did you also have this problem on latest release of dask using the single-machine scheduler?  Or is this new?

**Comment by bmerry** [comment]
I first ran into it with 0.16.1, and master didn't fix it. I don't know how long it might have been happening before it came to my attention (thanks to the OOM killer), so I don't know if it is a recent regression or not.

**Comment by mrocklin** [comment]
OK, that's useful information.

cc @jcrist .  It looks like the task ordering improvements would further improve things if we maintained sortedness of `ready` in the single-machine scheduler, such as by using a heap.  

###  Current code

```python
def finish_task(dsk, key, state, results, sortkey, delete=True,
                release_data=release_data):
    for dep in sorted(state['dependents'][key], key=sortkey, reverse=True):
        s = state['waiting'][dep]
        s.remove(key)
        if not s:
            del state['waiting'][dep]
            state['ready'].append(dep)   # <--  this needs to be changed

            heapq.heappush(state['ready'], (priority[dep), dep))   # <--  to this
```

Short term I'd prefer not to bother (there are a number of things to consider when doing this), but I thought I'd put it on your radar.  Happy to move this to a dask/dask issue, but wanted to make you aware of the conversation here. and in https://github.com/dask/dask/issues/3139 in case you had thoughts.

**Comment by bmerry** [comment]
Sorry, just realised that for the last several comments here I was confusing this issue with dask/dask#3139. Everything I said from [this comment](https://github.com/dask/distributed/issues/1742#issuecomment-363766129) onwards should probably be ignored. This is purely an issue with dask/distributed.

**Comment by bmerry** [comment]
Closing since I believe it is explained by worker memory limits.
