### ISSUE TITLE
distributed.executor - INFO - Stream closed to scheduler

### ISSUE THREAD

**Issue by ogrisel** [dask/distributed#178]
Whenever I call the `shutdown` method on an executor object (for instance using the `with Executor(host) as e` idiom, I get the following log entry in the stdout or stderr of the client program (not on the scheduler process):

```
distributed.executor - INFO - Stream closed to scheduler
Traceback (most recent call last):
  File "/volatile/ogrisel/code/distributed/distributed/executor.py", line 378, in _handle_report
    msg = yield next_message()
  File "/volatile/ogrisel/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/volatile/ogrisel/envs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/volatile/ogrisel/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/volatile/ogrisel/code/distributed/distributed/core.py", line 204, in read
    msg = yield stream.read_until(sentinel)
  File "/volatile/ogrisel/envs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/volatile/ogrisel/envs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed
```

I find this log pretty useless, it is intentional?

**Comment by mrocklin** [comment]
Fixed in https://github.com/dask/distributed/commit/12c46c8d5593fab8a0854c86a29685945ce344de

**Comment by ogrisel** [comment]
Thanks :)
