### ISSUE TITLE
Failed to deserialize during simple example

### ISSUE THREAD

**Issue by baxen** [dask/distributed#1816]
I'm trying to setup distributed, but running into an error even for simple examples:

```bash
pyenv virtualenv dask
pyenv activate dask
pip install --upgrade dask distributed
```

```python
import dask
import distributed

client = distributed.Client()

@dask.delayed
def inc(x):
    return x+1

dask.compute(inc(1))
```

This fails with the following stack trace:
```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/core.py", line 119, in loads
    value = _deserialize(head, fs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 158, in deserialize
    return f(header, frames)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 20, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
TypeError: sequence item 0: expected string, bytearray found
distributed.utils - ERROR - sequence item 0: expected string, bytearray found
Traceback (most recent call last):
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/client.py", line 1392, in _gather
    response = yield self.scheduler.gather(keys=keys)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/core.py", line 474, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/core.py", line 360, in send_recv
    response = yield comm.read()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/comm/tcp.py", line 202, in read
    msg = yield from_frames(frames, deserialize=self.deserialize)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/comm/utils.py", line 75, in from_frames
    res = _from_frames()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(frames, deserialize=deserialize)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/core.py", line 119, in loads
    value = _deserialize(head, fs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 158, in deserialize
    return f(header, frames)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 20, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
TypeError: sequence item 0: expected string, bytearray found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/dask/base.py", line 392, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/client.py", line 2048, in get
    results = self.gather(packed, asynchronous=asynchronous)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/client.py", line 1485, in gather
    asynchronous=asynchronous)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/client.py", line 608, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/utils.py", line 254, in sync
    six.reraise(*error[0])
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/client.py", line 1392, in _gather
    response = yield self.scheduler.gather(keys=keys)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/core.py", line 474, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/core.py", line 360, in send_recv
    response = yield comm.read()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/comm/tcp.py", line 202, in read
    msg = yield from_frames(frames, deserialize=self.deserialize)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/comm/utils.py", line 75, in from_frames
    res = _from_frames()
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(frames, deserialize=deserialize)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/core.py", line 119, in loads
    value = _deserialize(head, fs)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 158, in deserialize
    return f(header, frames)
  File "/Users/baxen/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 20, in <lambda>
    deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
TypeError: sequence item 0: expected string, bytearray found
```

This is with python installed via pyenv (version 2.7.13). I get the same error consistently on both OSX and a linux server. If I exclude the `client = distributed.Client()` line everything works as expected.

Any idea what might be going wrong or something else I can try?

**Comment by mrocklin** [comment]
can you try `client.get_versions(check=True)`?

**Comment by baxen** [comment]
Yes it runs without raising an error, and I see the following:

```
'client': {'host': [('python', '2.7.13.final.0'),
                     ('python-bits', 64),
                     ('OS', 'Darwin'),
                     ('OS-release', '17.3.0'),
                     ('machine', 'x86_64'),
                     ('processor', 'i386'),
                     ('byteorder', 'little'),
                     ('LC_ALL', 'None'),
                     ('LANG', 'en_US.UTF-8'),
                     ('LOCALE', 'None.None')],
            'packages': {'optional': [('numpy', None),
                                      ('pandas', None),
                                      ('bokeh', None),
                                      ('lz4', None),
                                      ('blosc', None)],
                         'required': [('dask', u'0.17.1'),
                                      ('distributed', u'1.21.2'),
                                      ('msgpack', '0.5.5'),
                                      ('cloudpickle', '0.5.2'),
                                      ('tornado', '5.0'),
                                      ('toolz', '0.9.0')]}},
```

with the same content for the scheduler and each of the workers.

**Comment by mrocklin** [comment]
Interesting.  I see that you're on Tornado 5.0.  I suspect that this is an issue there.  We may not have seriously tested Tornado 5.0 against Python 2.7

**Comment by mrocklin** [comment]
Yup, that's it.  I'm able to reproduce.  I recommend downgrading one of distributed, tornado, or upgrading Python short term.  I'll deal with this in master sometime today.

**Comment by mrocklin** [comment]
@pitrou if you're around what do you recommend for concatenating bytearrays quickly in Python 2?

```python
deserializers = {None: lambda header, frames: pickle.loads(b''.join(frames))}
```

**Comment by mrocklin** [comment]
That's alright.  I'm just glad I'm not forgetting anything obvious.  It's Python 2 anyway, no need to promise the highest possible bandwidth.  It'll be a very slight (negligible for most people) nudge to Python 3.

**Comment by mrocklin** [comment]
I've turned off the read_into optimization in Python 2 in https://github.com/dask/distributed/pull/1818

**Comment by baxen** [comment]
Thank you, really appreciate the quick response. Downgrading to tornado 4.5.3 resolved this issue for me

**Comment by mrocklin** [comment]
Thank you for taking the time to report it.  This is a critical bug.  I'll probably push out a micro-release in the next day or two.
