### ISSUE TITLE
Inconsistent unpickling errors in different modes between REPL and CLI

### ISSUE THREAD

**Issue by cottrell** [dask/distributed#1835]
The following works in both cluster and local mode from the command line, but in the REPL it succeeds in local model but fails in cluster mode. I am guessing this is just an unpickling PYTHONPATH error but am wondering what are the typical paths to debugging and working around it? 

In general, this comes up while trying to submit jobs to a cluster to iterate on some development modules. I think some sort of wrapper to set PYTHONPATH dynamically before the unpickle will solve this. 

example.py:

```
#!/usr/bin/env python
import sys
import dask
from distributed import Client
# from dask.distributed import Client
import dask.bag as db

def print_and_return_message(msg):
    print("msg:", msg)
    return "print: [{}]".format(msg)

def submit(client):
    r = client.submit(print_and_return_message, 'what')
    print("r", r.result())

def test():
    b = db.from_sequence([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    return b.map(print_and_return_message)

def cluster():
    client = Client('127.0.0.1:8786')
    submit(client)

def local():
    # dask.set_options(get=dask.local.get_sync)
    # client = Client()
    # or
    client = Client(processes=False)
    submit(client)

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'local':
        print("running local mode")
        local()
    else:
        cluster()
        print("running cluster mode")
```

CLI

```
~/projects/notebooks/dask $ python example.py cluster
r print: [what]
running cluster mode
~/projects/notebooks/dask $ python example.py local
running local mode
msg: what
r print: [what]
```

REPL

```
In [1]: import example as e

In [2]: e.cluster()
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-d9e26c0e53e0> in <module>()
----> 1 e.cluster()

~/projects/notebooks/dask/example.py in cluster()
     20 def cluster():
     21     client = Client('127.0.0.1:8786')
---> 22     submit(client)
     23
     24 def local():

~/projects/notebooks/dask/example.py in submit(client)
     12 def submit(client):
     13     r = client.submit(print_and_return_message, 'what')
---> 14     print("r", r.result())
     15
     16 def test():

~/anaconda3/envs/363/lib/python3.6/site-packages/distributed/client.py in result(self, timeout)
    169                                   raiseit=False)
    170         if self.status == 'error':
--> 171             six.reraise(*result)
    172         elif self.status == 'cancelled':
    173             raise result

~/anaconda3/envs/363/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

~/anaconda3/envs/363/lib/python3.6/site-packages/distributed/protocol/pickle.py in loads()
     57 def loads(x):
     58     try:
---> 59         return pickle.loads(x)
     60     except Exception:
     61         logger.info("Failed to deserialize %s", x[:10000], exc_info=True)

ModuleNotFoundError: No module named 'example'

In [3]: e.local()
msg: what
r print: [what]
```

**Comment by martindurant** [comment]
The first thing I would check, is `which python` and `which ipython`. 
Since you are effectively depending on being able to import a file from the local directory, the next thing would be to check what directory is "local" from the pov of the CLI python, ipython and the workers (you can use `client.run` to execute code on the workers). It would in general be better to put your code in a global place, perhaps in a PYTHONPATH that is defined in all console sessions, or as part of a package that you can install/link with `python setup.py`.

**Comment by cottrell** [comment]
Yes, I should have included the versions: 

```
~ $ ipython --version
6.2.1
~ $ python --version
Python 3.6.4 :: Anaconda, Inc
```

Same thing occurs regardless of where I run from. 

"global" is fine but am exploring a setup with the potential of shared workers and different users working on some modules in "develop" mode for example. Maybe the typical setup is just to have every user have their own worker but that is less ideal for lots of users. A cluster manager could probably help here but was hoping there is a "typical" workflow with distributed that allows me to do some run-time setup on the workers.

**Comment by martindurant** [comment]
Can you run `which python`, `which ipython` and also investigate the `sys.path` and `os.getcwd()` in python, ipython and the workers?

**Comment by mrocklin** [comment]
Checking in here.  Any updates @cottrell ?  

Generally problems like this are almost always due to people having multiple Python environments and not realizing that they're acting in one or the other.  Looking at `sys.executable` should give you an idea of which python version you're running in each environment.

Closing this in a day or so if there is no response.

**Comment by cottrell** [comment]
Sorry for delay, I checked the paths and nothing clear so far as the path of example.py is present in local mode and not in cluster mode but it works in the CLI and not in the REPL. I've checked for python versions and things seem to be consistent except for the dynamic worker directories and the cwd where I start the process/cluster. To recap, I start the cluster using

```
        cd
        dask-scheduler &
        dask-worker localhost:8786 &
```

Then I am working with this example now: 
```

#!/usr/bin/env python
import pickle
import hashlib
import os
import sys
import dask
from distributed import Client
# from dask.distributed import Client
import dask.bag as db

def print_and_return_message(msg):
    return '/Users/davidcottrell/projects/notebooks/dask' in sys.path

def submit(client):
    r = client.submit(print_and_return_message, 'what')
    print("res=", r.result())
    return r

def test():
    b = db.from_sequence([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    return b.map(print_and_return_message)

def cluster():
    client = Client('127.0.0.1:8786')
    return submit(client)

def local():
    # dask.set_options(get=dask.local.get_sync)
    # client = Client()
    # or
    client = Client(processes=False)
    return submit(client)

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'local':
        print("running local mode")
        local()
    else:
        cluster()
        print("running cluster mode")
```

CLI:

```
~/projects/notebooks/dask $ python example.py local
running local mode
res= True
~/projects/notebooks/dask $ python example.py cluster
distributed.scheduler - INFO - Receive client connection: Client-40d1ba9e-30ca-11e8-8566-c82a1452b04e
res= False
running cluster mode
distributed.scheduler - INFO - Remove client Client-40d1ba9e-30ca-11e8-8566-c82a1452b04e
distributed.scheduler - INFO - Close client connection: Client-40d1ba9e-30ca-11e8-8566-c82a1452b04e
```

REPL (I've dropped to plain python instead of IPython for simplicity of debug):

```
cd ~/projects/notebooks/dask
~/projects/notebooks/dask $ type python
python is hashed (/Users/davidcottrell/anaconda3/envs/363/bin/python)
~/projects/notebooks/dask $ python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example as e
>>> e.local().result()
res= True
True
>>> e.cluster().result()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidcottrell/projects/notebooks/dask/example.py", line 25, in cluster
    return submit(client)
  File "/Users/davidcottrell/projects/notebooks/dask/example.py", line 16, in submit
    print("res=", r.result())
  File "/Users/davidcottrell/anaconda3/envs/363/lib/python3.6/site-packages/distributed/client.py", line 171, in result
    six.reraise(*result)
  File "/Users/davidcottrell/anaconda3/envs/363/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidcottrell/anaconda3/envs/363/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'example'
```

I am guessing now that the CLI is working semi-accidentally somehow (I am looking for __file__ and inspect patterns in dask.distributed ...) and that pattern is not explicitly exposed in the submit.

If it helps clarify the pattern, in Spark you can change the worker "context" by setting spark.executorEnv.PYTHONPATH and this works quite well if you are running different code on the same cluster.

I can deep-dive on this more but I probably need to read a bit more on the dask worker setup.

**Comment by mrocklin** [comment]
Any updates on this @cottrell ?

**Comment by cottrell** [comment]
Am seeing a bit of code forking relying on __main__ \ in distributed/distributed/protocol/pickle.py and have a hunch this is part of the issue ... am now trying to launch a worker in the REPL to chase the stack there. I see dask_worker.py::main has been somewhat obfuscated by the click module. If anyone knows the Worker defaults launch pattern please point me at it. I generally try to avoid putting the defaults of function calls anywhere but in the functions ... but maybe there is a pattern with click that is like the old but good argh module?

**Comment by cottrell** [comment]
Posted an issue on cloudpickle https://github.com/cloudpipe/cloudpickle/issues/168

**Comment by cottrell** [comment]
I think the summary is that with cloudpickle it sounds like "You just need to make sure that cloudpickle_example is on the Python path of the remote dask workers.". Currently, I think the only way to set the PYTHONPATH on dask workers is to specify it at cluster (worker) creation time?

**Comment by jonashaag** [comment]
Just hit a similar issue. Problem was that dependencies were not available in worker environment. So, a user error.

However the error message wasn't really helpful here since from the traceback I assumed there must be an error in the *client-using code*, not the worker. There is no indication that the error is coming from a worker. Maybe we can improve this?
