### ISSUE TITLE
Msgpack compression error with tornado==5.0.1

### ISSUE THREAD

**Issue by bnaul** [dask/distributed#1846]
I can't quite figure out what kind of arguments are causing this but maybe it will be more obvious to someone else. Downgrading to `tornado==4.5.3` resolves. Other versions are `python-snappy==0.5.1` and `distributed==1.21.3`.

```
distributed.scheduler - ERROR - argument 1 must be read-only bytes-like object, not bytearray
Traceback (most recent call last):
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/scheduler.py", line 1918, in handle_client
    msgs = yield comm.read()
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/comm/tcp.py", line 203, in read
    msg = yield from_frames(frames, deserialize=self.deserialize)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/comm/utils.py", line 75, in from_frames
    res = _from_frames()
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(frames, deserialize=deserialize)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/protocol/core.py", line 96, in loads
    msg = loads_msgpack(small_header, small_payload)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/protocol/core.py", line 168, in loads_msgpack
    payload = decompress(payload)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/distributed/protocol/compression.py", line 50, in _fixed_snappy_decompress
    return snappy.decompress(data)
  File "/Users/brettnaul/miniconda3/envs/model/lib/python3.6/site-packages/snappy.py", line 91, in uncompress
    return _uncompress(data)
TypeError: argument 1 must be read-only bytes-like object, not bytearray
```

**Comment by mrocklin** [comment]
I believe that this was resolved
in 454d30f269f2f74de8b7c9a0302f4aa57ddd6c69 .  I recommend trying master

**Comment by bnaul** [comment]
Whoops, searched around a little bit but not for the right term I guess.
