### ISSUE TITLE
upload_file crash

### ISSUE THREAD

**Issue by apatlpo** [dask/distributed#1869]

**Comment by mrocklin** [comment]
Can you try starting your client with the following:

    client = Client(..., timeout='20s')

and then seeing how the restart does?

**Comment by mrocklin** [comment]
For the file issue I'm not surprised to see things not work well on an NFS system.  See http://dask.pydata.org/en/latest/setup/hpc.html#no-local-storage

If you have an NFS then maybe just use normal techniques like PYTHONPATH or installing modules rather than use upload_file

**Comment by apatlpo** [comment]
With 20s:
```
distributed.client - ERROR - Restart timed out after 20.000000 seconds
```
With 60s:
```
distributed.batched - INFO - Batched Comm Closed: in <closed TCP>: BrokenPipeError: [Errno 32] Broken pipe
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://10.148.0.106:8786' processes=33 cores=132>>
Traceback (most recent call last):
  File "/home1/datahome/aponte/.miniconda3/envs/pangeo/lib/python3.6/site-packages/tornado/ioloop.py", line 1209, in _run
    return self.callback()
  File "/home1/datahome/aponte/.miniconda3/envs/pangeo/lib/python3.6/site-packages/distributed/client.py", line 846, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat'})
  File "/home1/datahome/aponte/.miniconda3/envs/pangeo/lib/python3.6/site-packages/distributed/batched.py", line 106, in send
    raise CommClosedError
```
the message repeats itself several times

**Comment by mrocklin** [comment]
How are you starting your workers?  What kind of system are you on?

**Comment by apatlpo** [comment]
I am on a cluster PBS : https://wwz.ifremer.fr/pcdm/Equipement 
I run `./launch-dask.sh ${N_WORK_NODES}` following https://pangeo-data.github.io/pangeo/setup_guides/cheyenne.html
It was working fine until a recent update xarray/dask/...

**Comment by mrocklin** [comment]
> It was working fine until a recent update xarray/dask/...

Would you be willing to use `git bisect` to find the cause?  "No" is a fine answer

**Comment by apatlpo** [comment]
I started doing this but am right away confused.

The working version is dask 0.15.4 and distributed 1.19.3

The failing version is dask 0.17.2 and distributed 1.18.1+288.g31c470e

Isn't 31c470e based on the latest distributed version?

**Comment by mrocklin** [comment]
Correct.  You would only be bisecting in the distributed repository.  You
would no longer use
https://github.com/dask/distributed/commit/31c470e83ca5c66787be151e9c39f1f9b29f523a
at all, instead you would bound your search by a commit that you knew
worked (like version 1.19.3) and a commit that you knew did not work (like
version 1.21.4) and then you would use git bisect to search within that
range to find the offending commit.  This process is very useful, but can
be confusing at first.

**Comment by apatlpo** [comment]
Am I supposed to this simultaneously for dask AND distributed?

**Comment by mrocklin** [comment]
Hopefully there is enough flexibility that everything will work smoothly
with a single recent version of Dask.

Also, you have no obligation to do this.  It would be useful, but if it
proves to be too difficult then we can probably find the issue some other
way with more time.

**Comment by apatlpo** [comment]
Hum, distributed version 1.19.3 does not seem to be compatible with latest dask.

The combination does not even produce a scheduler.json

The following error on the scheduler side occurs:
```
  File "/home1/datahome/aponte/.miniconda3/envs/pangeo/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home1/datahome/aponte/.miniconda3/envs/pangeo/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home1/datahome/aponte/.miniconda3/envs/pangeo/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home1/datahome/aponte/distributed/distributed/cli/dask_mpi.py", line 57, in main
    services=services)
  File "/home1/datahome/aponte/distributed/distributed/scheduler.py", line 376, in __init__
    **kwargs)
  File "/home1/datahome/aponte/distributed/distributed/node.py", line 37, in __init__
    deserialize=deserialize, io_loop=self.io_loop)
  File "/home1/datahome/aponte/distributed/distributed/core.py", line 117, in __init__
    pc = PeriodicCallback(self.monitor.update, 500, io_loop=self.io_loop)
TypeError: __init__() got an unexpected keyword argument 'io_loop'
Terminated
```

**Comment by apatlpo** [comment]
argh, this is a distributed-tornado compatibility issue in fact, see #1172

The bisect seems difficult to me

**Comment by apatlpo** [comment]
Unless you see an easier alternative, I'll try a manual bisect with conda install to narrow down where the problem arise

**Comment by mrocklin** [comment]
Versions may not be sufficiently granular to identify the problem.  Ideally
we would be able to find the exact commit in git where the error was
introduced.  That may prove to be too difficult though.

**Comment by mrocklin** [comment]
Going back to the beginning here a bit.  Can you verify that your workers actually connect and work normally before you try to restart?  Is it just restarting that is the problem?

**Comment by apatlpo** [comment]
@rabernat , have you encountered issues (slower responsiveness, restart time outs,  unability to use upload_file) on habanero with dask versions above 0.16.0 ?

**Comment by apatlpo** [comment]
I have reverted to the latest version of dask (0.17.2 / distributed 1.21.4).

- If I don't specify a timeout, the number of workers is constantly fluctuating.
- If I do specify a timeout, the number of workers freezes.
- When I try to do a restart, workers die

Here is the log for one worker:
[dask-worker.o966682.log](https://github.com/dask/distributed/files/1862997/dask-worker.o966682.log)

I am not sure what else I could try.

**Comment by rabernat** [comment]
In my experience, restarting workers on a cluster has never actually worked reliably. The minute I have a worker die, I usually just kill the whole cluster and start over. I could never summon the motivation to debug this deeply.

However, your experience sounds worse than what I am used to. A properly configured HPC cluster can perform very well, provided that the workers don't run out of memory or experience errors causing them to die.

**Comment by apatlpo** [comment]
This does not sound too optimistic.

I reverted to using latest distribution (04e7e7a7d6d3cee11ef2a4f2f4d7622d9a21e2eb) which includes the #1865.

Here is the behavior that I observe now:

- workers show up in dask dash board but in jupyter notebooks, client tells me however that there are no workers
- I have multiple FileNotFoundError errors in worker logs that seem to indicate that workers are deleting each other work directories. Example:
```
(pangeon) aponte@datarmor2:~/iwave_sst/datarmor> grep worker-i0oaruup dask*
dask-worker.o967959:FileNotFoundError: [Errno 2] No such file or directory: '/home1/datawork/aponte/dask/worker-i0oaruup/storage'
dask-worker.o967962:distributed.diskutils - WARNING - Found stale lock file and directory '/home1/datawork/aponte/dask/worker-i0oaruup', purging
```

**Comment by mrocklin** [comment]
You might consider not using your home directory for scratch space.  I
recommend using the --local-directory keyword to dask-worker (however
you're launching dask-worker).  Some more information here:
http://dask.pydata.org/en/latest/setup/hpc.html#no-local-storage

**Comment by apatlpo** [comment]
I am using a work directory where I have a confortable amount of space with the following command:
```
mpirun --np 7 dask-mpi --nthreads 4 \
     --memory-limit 1e10 \
     --interface ib0 \
     --local-directory ${DATAWORK}/dask \
     --scheduler-file=${SCHEDULER}
```

**Comment by mrocklin** [comment]
Ideally this would live on locally attached storage.  Network storage isn't
particularly good for frequently used scratch space like this, no matter
how large it is.

**Comment by apatlpo** [comment]
The use of this storage in particular has never been an issue for earliers dask versions (0.15.4 for example).
Modifying config.yaml according to
```
worker-memory-target: false  # don't spill to disk
worker-memory-spill: false  # don't spill to disk
worker-memory-pause: 0.80  # fraction at which we pause worker threads
worker-memory-terminate: 0.95  # fraction at which we terminate the worker
```
had not effect

**Comment by mrocklin** [comment]
I thought you had tried older dask versions and seen that it worked fine?

If you have locally attached storage I recommend trying specifying a
--local-directory that is not on the network

In general I'm sorry that you're having trouble.  I don't know what's going
on with your system.  I'm trying to propose some things to try but I'm
unable to spend a lot of time tracking down what's going on in your case.

**Comment by mrocklin** [comment]
I also have no idea if the directories are a problem, I'm just on this
because you suggested it above that they were clobbering each other.  This
is not terribly surprising when running on slow NFS systems that aren't
terribly consistent

**Comment by mrocklin** [comment]
Maybe someone else with more experience using Dask on these systems can
help.

**Comment by apatlpo** [comment]
Regarding the local directory, the only last thing I have not tried is using my home directory.
I'll give it a shot, regardless of one of your comment above.

Except for rabernat, do you have in mind people I could ping about this?

**Comment by mrocklin** [comment]
You could ask on the pangeo issue tracker.  There are a number of HPC users
there.  https://github.com/pangeo-data/pangeo/issues

**Comment by guillaumeeb** [comment]
I can only support @mrocklin comments on shared file system. Always use the local-directory option to point to a server local storage like /tmp. With pbs you may have an environment variable to use like TMPDIR or PBS_TMPDIR.
