### ISSUE TITLE
worker issues on slurm network

### ISSUE THREAD

**Issue by leej3** [dask/distributed#1878]
I didn't know what issue to attach this to so am starting a new one. I was having a lot of intermittent issues trying to get dask working on my cluster where the workers were being killed once they were sent something to compute. i was trying to use dask-jobqueue, but manually setting up a scheduler and workders using dask-scheduler etc showed the same behaviour. The recent commit a3dd444200a96df97fa3c049591b195e49d24934 fixed my problem but was still sluggish. One of the staff members running the cluster suggested constraining the set of nodes to draw from. When I constrained to nodes on the 10g network (--constraint=10g) this problem went away. Hopefully this helps with some of the other issues I've been seeing as I was troubleshooting this.

John

**Comment by mrocklin** [comment]
Without more information I'm not sure how people can help.  In your situation I would look at the exact steps you took to set things up, the software environment you have on your client, scheduler, and worker nodes (perhaps they aren't the same) and also look at the logs for the scheduler and workers.

**Comment by mrocklin** [comment]
If you're able to share this information then please do.  If not then I suggest that we close this issue. 

I apologize for the late response.

**Comment by leej3** [comment]
I though this problem was fixed by constraining the dask-workers to a pool of nodes that were on the same network (10g vs infiniband or 1g). In attempting to replicate this it looks like it is not. I've attempted to include the relevant details. Let me know if I have not. I'm not sure how to get the environment of the workers. Do you mean the output of env or is the conda environment included at the bottom of this post sufficient? 

```python
from dask_jobqueue import SLURMCluster
from dask.distributed import Client
from dask import delayed
import time

def inc(x):
    import time
    time.sleep(5)
    return x + 1

def dec(x):
    import time
    time.sleep(3)
    return x - 1

def add(x, y):
    import time
    time.sleep(7)
    return x + y
```

# A failed run


```python
# setup a scheduler. the cluster object will manage this It's important to constrain the workers to ones that default to the same networking. We can't mix infiniband with 10g ethernet nodes. The constraint argument to sbatch allows us to specify the ethernet nodes
cluster = SLURMCluster(
    queue='quick',
    memory =  "12g",
    processes=1,
    threads = 4)

# start two workers
cluster.start_workers(2)

c = Client(cluster)

x = delayed(inc)(1)
y = delayed(dec)(2)
total = delayed(add)(x, y)
fut = c.compute(total)
c.gather(fut)
```

    3


```python
!cat dask-worker.err
```

    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.23.118:53814'
    distributed.nanny - INFO - Failed to start worker process.  Restarting
    distributed.diskutils - WARNING - Found stale lock file and directory '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-8r_v5eas', purging
    distributed.diskutils - WARNING - Found stale lock file and directory '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-clzxtc32', purging
    distributed.worker - INFO -       Start worker at:    tcp://10.1.23.118:38742
    distributed.worker - INFO -          Listening to:    tcp://10.1.23.118:38742
    distributed.worker - INFO -              nanny at:          10.1.23.118:53814
    distributed.worker - INFO -              bokeh at:           10.1.23.118:8789
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.81:59854
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-8d3jstw5
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.81:59854
    distributed.worker - INFO - -------------------------------------------------
     go
        main()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 243, in main
        loop.run_sync(run)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/ioloop.py", line 582, in run_sync
        return future_cell[0].result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 236, in run
        yield [n._start(addr) for n in nannies]
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 849, in callback
        result_list.append(f.result())
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 155, in _start
        response = yield self.instantiate()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 223, in instantiate
        self.process.start()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 363, in start
        self._wait_until_started())
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
        yielded = self.gen.send(value)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 471, in _wait_until_started
        assert msg == 'started', msg
    AssertionError: {'address': 'tcp://10.1.31.5:36531', 'dir': '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-4do6oun9'}
    distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-2, started daemon)>



```python
!cat dask-worker.out
```

# What I thought to be the fix

Suggested by my HPC staff: Constrain the worker pool to the same network architecture.  This is relevant for clusters with a heterogenous pool of nodes on the same partition. In our case here are some details about the quick partition/queue:
Partition   Features
-------------------------------
quick       cpu56,core28,g256,ssd400,x2695,ibfdr,ccr
quick       cpu56,core28,g256,ssd800,x2680,ibfdr,ccr
quick       cpu24,core12,g24,sata100,x5660,1g
quick       cpu16,core8,g24,sata200,x5550,1g
quick       cpu32,core16,g128,ssd800,x2650,10g,nimh
quick       cpu32,core16,g64,sata400,x2670,1g
quick       cpu56,core28,g256,ssd400,x2695,ibfdr,gpuk80,ccr
quick       cpu32,core16,g128,sata400,x2670,1g
quick       cpu16,core8,g72,sata200,x5550,1g

```python
# setup a scheduler. the cluster object will manage this It's important to constrain the workers to ones that default to the same networking. We can't mix infiniband with 10g ethernet nodes. The constraint argument to sbatch allows us to specify the ethernet nodes
cluster = SLURMCluster(
    queue='quick',
    memory =  "12g",
    processes=1,
    threads = 4,
    job_extra = ['--constraint=10g'])

# start two workers
cluster.start_workers(2)
c = Client(cluster)

x = delayed(inc)(1)
y = delayed(dec)(2)
total = delayed(add)(x, y)
fut = c.compute(total)
c.gather(fut)
```

    3

```python
!cat dask-worker.err
```

    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.22.181:44629'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.22.181:47902'
    distributed.nanny - INFO - Failed to start worker process.  Restarting
    distributed.nanny - INFO - Failed to start worker process.  Restarting
    distributed.diskutils - WARNING - Found stale lock file and directory '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-4do6oun9', purging
    distributed.worker - INFO -       Start worker at:    tcp://10.1.22.181:49202
    distributed.worker - INFO -          Listening to:    tcp://10.1.22.181:49202
    distributed.worker - INFO -              nanny at:          10.1.22.181:44629
    distributed.worker - INFO -              bokeh at:           10.1.22.181:8789
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.81:43598
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-9ri6822v
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.81:43598
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -       Start worker at:    tcp://10.1.22.181:36733
    distributed.worker - INFO -          Listening to:    tcp://10.1.22.181:36733
    distributed.worker - INFO -              nanny at:          10.1.22.181:47902
    distributed.worker - INFO -              bokeh at:          10.1.22.181:39260
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.81:43598
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-juzuas0n
    distributed.worker - INFO - -------------------------------------------------
    distributed.dask_worker - INFO - End worker
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.81:43598
    distributed.worker - INFO - -------------------------------------------------
    tornado.application - ERROR - Exception in Future <Future finished exception=AssertionError({'address': 'tcp://10.1.22.181:36733', 'dir': '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-juzuas0n'},)> after timeout
    Traceback (most recent call last):
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 936, in error_callback
        future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
        yielded = self.gen.send(value)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 471, in _wait_until_started
        assert msg == 'started', msg
    AssertionError: {'address': 'tcp://10.1.22.181:36733', 'dir': '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-juzuas0n'}
    Traceback (most recent call last):
      File "/data/rodgersleejg/python/envs/dask_minimal/bin/dask-worker", line 11, in <module>
        sys.exit(go())
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 252, in go
        main()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 243, in main
        loop.run_sync(run)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/ioloop.py", line 582, in run_sync
        return future_cell[0].result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/cli/dask_worker.py", line 236, in run
        yield [n._start(addr) for n in nannies]
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 849, in callback
        result_list.append(f.result())
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 155, in _start
        response = yield self.instantiate()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 223, in instantiate
        self.process.start()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 363, in start
        self._wait_until_started())
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
        yielded = self.gen.send(value)
      File "/data/rodgersleejg/python/envs/dask_minimal/lib/python3.6/site-packages/distributed/nanny.py", line 471, in _wait_until_started
        assert msg == 'started', msg
    AssertionError: {'address': 'tcp://10.1.22.181:49202', 'dir': '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-9ri6822v'}
    distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-2, started daemon)>



```python
!cat dask-worker.out
```

**Comment by leej3** [comment]
so current status is it seems to work either way but may not be particularly happy about it. If the network constraint is in fact an issue then the problem will be intermittent anyway.

**Comment by mrocklin** [comment]
Can you upgrade your version of distributed and then try again?

conda install distributed

or

pip install distributed --upgrade

**Comment by leej3** [comment]
It certainly looks a lot cleaner... So is the constraint irrelevant? Let me know if you'd like me to test anything else.

So after: 
conda env export > dask_minimal.yml
conda install -y distributed
conda env export > dask_minimal_after_upgrade.yml


```python
!diff dask_minimal.yml dask_minimal_after_upgrade.yml
```

    23c23
    <   - distributed=1.21.4=py36_0
    ---
    >   - distributed=1.21.6=py36_0



```python
from dask_jobqueue import SLURMCluster
from dask.distributed import Client
from dask import delayed
import time

def inc(x):
    import time
    time.sleep(5)
    return x + 1

def dec(x):
    import time
    time.sleep(3)
    return x - 1

def add(x, y):
    import time
    time.sleep(7)
    return x + y
```

# Run without specifying 10g constraint


```python
# setup a scheduler. the cluster object will manage this It's important to constrain the workers to ones that default to the same networking. We can't mix infiniband with 10g ethernet nodes. The constraint argument to sbatch allows us to specify the ethernet nodes
cluster = SLURMCluster(
    queue='quick',
    memory =  "12g",
    processes=1,
    threads = 4)

# start two workers
cluster.start_workers(2)

c = Client(cluster)

x = delayed(inc)(1)
y = delayed(dec)(2)
total = delayed(add)(x, y)
fut = c.compute(total)
c.gather(fut)
```

    3


```python
!cat dask-worker.err
```

    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.23.139:50852'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.23.139:54169'
    distributed.diskutils - INFO - Found stale lock file and directory '/spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-9ri6822v', purging
    distributed.worker - INFO -       Start worker at:    tcp://10.1.23.139:39392
    distributed.worker - INFO -          Listening to:    tcp://10.1.23.139:39392
    distributed.worker - INFO -       Start worker at:    tcp://10.1.23.139:47256
    distributed.worker - INFO -              nanny at:          10.1.23.139:54169
    distributed.worker - INFO -          Listening to:    tcp://10.1.23.139:47256
    distributed.worker - INFO -              bokeh at:          10.1.23.139:39996
    distributed.worker - INFO -              nanny at:          10.1.23.139:50852
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.69:34299
    distributed.worker - INFO -              bokeh at:           10.1.23.139:8789
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.69:34299
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-iriooe__
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-u7027evm
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.69:34299
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.69:34299
    distributed.worker - INFO - -------------------------------------------------



```python
!cat dask-worker.out
```

# Run with 10g constraint specified


```python
# setup a scheduler. the cluster object will manage this It's important to constrain the workers to ones that default to the same networking. We can't mix infiniband with 10g ethernet nodes. The constraint argument to sbatch allows us to specify the ethernet nodes
cluster = SLURMCluster(
    queue='quick',
    memory =  "12g",
    processes=1,
    threads = 4,
    job_extra = ['--constraint=10g'])

# start two workers
cluster.start_workers(2)
c = Client(cluster)

x = delayed(inc)(1)
y = delayed(dec)(2)
total = delayed(add)(x, y)
fut = c.compute(total)
c.gather(fut)
```

    3


```python
!cat dask-worker.err
```

    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.22.153:58527'
    distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.22.153:48276'
    distributed.worker - INFO -       Start worker at:    tcp://10.1.22.153:41949
    distributed.worker - INFO -          Listening to:    tcp://10.1.22.153:41949
    distributed.worker - INFO -              nanny at:          10.1.22.153:58527
    distributed.worker - INFO -              bokeh at:           10.1.22.153:8789
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.69:57157
    distributed.worker - INFO -       Start worker at:    tcp://10.1.22.153:54114
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -          Listening to:    tcp://10.1.22.153:54114
    distributed.worker - INFO -              nanny at:          10.1.22.153:48276
    distributed.worker - INFO -              bokeh at:          10.1.22.153:49620
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO - Waiting to connect to:     tcp://10.1.21.69:57157
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-o6e_gjir
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -               Threads:                          4
    distributed.worker - INFO -                Memory:                   12.00 GB
    distributed.worker - INFO -       Local Directory: /spin1/home/linux/rodgersleejg/dask_setup/dask-worker-space/worker-lv0dppey
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.69:57157
    distributed.worker - INFO - -------------------------------------------------
    distributed.worker - INFO -         Registered to:     tcp://10.1.21.69:57157
    distributed.worker - INFO - -------------------------------------------------



```python
!cat dask-worker.out
```

# The environment


```python
!conda env export
```

    name: dask_minimal
    channels:
    - defaults
    - conda-forge
    - bioconda
    dependencies:
    - alabaster=0.7.10=py36h306e16b_0
    - asn1crypto=0.24.0=py36_0
    - babel=2.5.3=py36_0
    - backcall=0.1.0=py36_0
    - bleach=2.1.3=py36_0
    - bokeh=0.12.14=py36_0
    - ca-certificates=2018.03.07=0
    - certifi=2018.1.18=py36_0
    - cffi=1.11.5=py36h9745a5d_0
    - chardet=3.0.4=py36h0f667ec_1
    - click=6.7=py36h5253387_0
    - cloudpickle=0.5.2=py36_1
    - cryptography=2.2.2=py36h14c3975_0
    - cytoolz=0.9.0.1=py36h14c3975_0
    - dask=0.17.2=py36_0
    - dask-core=0.17.2=py36_0
    - decorator=4.3.0=py36_0
    - distributed=1.21.6=py36_0
    - docutils=0.14=py36hb0f60f5_0
    - entrypoints=0.2.3=py36h1aec115_2
    - gmp=6.1.2=h6c8ec71_1
    - heapdict=1.0.0=py36_2
    - html5lib=1.0.1=py36h2f9c1c0_0
    - idna=2.6=py36h82fb2a8_1
    - imagesize=1.0.0=py36_0
    - intel-openmp=2018.0.0=8
    - ipykernel=4.8.2=py36_0
    - ipython=6.3.1=py36_0
    - ipython_genutils=0.2.0=py36hb52b0d5_0
    - jedi=0.12.0=py36_0
    - jinja2=2.10=py36ha16c418_0
    - jsonschema=2.6.0=py36h006f8b5_0
    - jupyter_client=5.2.3=py36_0
    - jupyter_core=4.4.0=py36h7c827e3_0
    - jupyterlab=0.31.12=py36_0
    - jupyterlab_launcher=0.10.5=py36_0
    - libedit=3.1=heed3624_0
    - libffi=3.2.1=hd88cf55_4
    - libgcc-ng=7.2.0=hdf63c60_3
    - libgfortran-ng=7.2.0=hdf63c60_3
    - libsodium=1.0.16=h1bed415_0
    - libstdcxx-ng=7.2.0=hdf63c60_3
    - locket=0.2.0=py36h787c0ad_1
    - markupsafe=1.0=py36hd9260cd_1
    - mistune=0.8.3=py36_0
    - mkl=2018.0.2=1
    - mkl_fft=1.0.1=py36h3010b51_0
    - mkl_random=1.0.1=py36h629b387_0
    - msgpack-python=0.5.6=py36h6bb024c_0
    - nbconvert=5.3.1=py36hb41ffb7_0
    - nbformat=4.4.0=py36h31c9010_0
    - ncurses=6.0=h9df7e31_2
    - notebook=5.4.1=py36_0
    - numpy=1.14.2=py36hdbf6ddf_1
    - numpydoc=0.8.0=py36_0
    - openssl=1.0.2o=h20670df_0
    - packaging=17.1=py36_0
    - pandas=0.22.0=py36hf484d3e_0
    - pandoc=1.19.2.1=hea2e7c5_1
    - pandocfilters=1.4.2=py36ha6701b7_1
    - parso=0.2.0=py36_0
    - partd=0.3.8=py36h36fd896_0
    - pexpect=4.5.0=py36_0
    - pickleshare=0.7.4=py36h63277f8_0
    - pip=9.0.1=py36_5
    - prompt_toolkit=1.0.15=py36h17d85b1_0
    - psutil=5.4.3=py36h14c3975_0
    - ptyprocess=0.5.2=py36h69acd42_0
    - pycparser=2.18=py36hf9f622e_1
    - pygments=2.2.0=py36h0d3125c_0
    - pyopenssl=17.5.0=py36h20ba746_0
    - pyparsing=2.2.0=py36hee85983_1
    - pysocks=1.6.8=py36_0
    - python=3.6.4=hc3d631a_3
    - python-dateutil=2.7.2=py36_0
    - pytz=2018.3=py36_0
    - pyyaml=3.12=py36hafb9ca4_1
    - pyzmq=17.0.0=py36h14c3975_0
    - readline=7.0=ha6073c6_4
    - requests=2.18.4=py36he2e5f8d_1
    - send2trash=1.5.0=py36_0
    - setuptools=38.5.1=py36_0
    - simplegeneric=0.8.1=py36_2
    - six=1.11.0=py36h372c433_1
    - snowballstemmer=1.2.1=py36h6febd40_0
    - sortedcontainers=1.5.9=py36_0
    - sphinx=1.7.2=py36_0
    - sphinxcontrib=1.0=py36h6d0f590_1
    - sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
    - sqlite=3.22.0=h1bed415_0
    - tblib=1.3.2=py36h34cf8b6_0
    - terminado=0.8.1=py36_1
    - testpath=0.3.1=py36h8cadb63_0
    - tk=8.6.7=hc745277_3
    - toolz=0.9.0=py36_0
    - tornado=5.0=py36_0
    - traitlets=4.3.2=py36h674d592_0
    - typing=3.6.4=py36_0
    - urllib3=1.22=py36hbe7ace6_0
    - wcwidth=0.1.7=py36hdf4376a_0
    - webencodings=0.5.1=py36h800622e_1
    - wheel=0.30.0=py36hfd4bba0_1
    - xz=5.2.3=h55aa19d_2
    - yaml=0.1.7=had09818_2
    - zeromq=4.2.5=h439df22_0
    - zict=0.1.3=py36h3a3bf81_0
    - zlib=1.2.11=ha838bed_2
    - pip:
      - dask-jobqueue==0.1.0
      - docrep==0.2.2
      - ipython-genutils==0.2.0
      - jupyter-client==5.2.3
      - jupyter-core==4.4.0
      - jupyterlab-launcher==0.10.5
      - mkl-fft==1.0.0
      - mkl-random==1.0.1
      - prompt-toolkit==1.0.15
    prefix: /data/rodgersleejg/python/envs/dask_minimal

**Comment by mrocklin** [comment]
I don't know what is going on with your network constraint.  My guess is
that the true answer is due to a complex relationship of many things.  If
the most recent release resolves your problem then I'm inclined to ignore
the historical problem and move on :)
