### ISSUE TITLE
Cannot pickle function decorated with @delayed

### ISSUE THREAD

**Issue by masdeseiscaracteres** [dask/distributed#1891]
I still do not know what is going on exactly. Similar to #725.

Minimal example:
```python-traceback
In[273]: # This fails
    ...: from dask import delayed
    ...: import pickle
    ...: @delayed
    ...: def foo():
    ...:     pass
    ...: 
    ...: pickle.dumps(foo)
Traceback (most recent call last):
  File "Z:\Documents\envs\env\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-273-d7120832da2b>", line 6, in <module>
    pickle.dumps(foo)
_pickle.PicklingError: Can't pickle <function foo at 0x0000000023532950>: it's not the same object as __main__.foo

In[274]: # but this works
    ...: from dask import delayed
    ...: import pickle
    ...: def foo():
    ...:     pass
    ...: 
    ...: foo2 = delayed(foo)
    ...: 
    ...: pickle.dumps(foo2)
Out[274]: b'\x80\x03cdask.delayed\nDelayedLeaf\nq\x00)\x81q\x01(c__main__\nfoo\nq\x02X(\x00\x00\x00foo-4d00ed56-d6fd-4164-816a-e066f7820ef7q\x03NNtq\x04b.'

In[275]: %load_ext watermark
    ...: %watermark -vm -p dask,toolz
    ...: 
The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
CPython 3.5.4
IPython 6.2.1

dask 0.17.2
toolz 0.9.0

compiler   : MSC v.1900 64 bit (AMD64)
system     : Windows
release    : 7
machine    : AMD64
processor  : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
CPU cores  : 6
interpreter: 64bit
```

**Comment by masdeseiscaracteres** [comment]
Sorry, I mistakenly opened it here. This issue is in fact related to `dask` not `dask.distributed`. Closing and opening a new one in `dask`.
