### ISSUE TITLE
Intermittent "RuntimeError: generator ignored GeneratorExit" at shutdown

### ISSUE THREAD

**Issue by gsakkis** [dask/distributed#1896]
The distribute client often (but not always) ends up raising `RuntimeError` at program exit time. Sometimes the error message is simply
```
Exception ignored in: <generator object add_client at 0x7f52711ae3b8>
RuntimeError: generator ignored GeneratorExit
```
without a traceback, sometimes it is followed by a traceback like the following:
```
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/home/miniconda3/envs/distenv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 179, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/miniconda3/envs/distenv/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/distenv/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/miniconda3/envs/distenv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 200, in read
    convert_stream_closed_error(self, e)
  File "/home/miniconda3/envs/distenv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

It's not hard to reproduce it, just reading a csv file and calling `compute()` on it (or a simple expression on it) demonstrates the problem about half the time. 
<details><summary>Small example</summary>

Run with input a sample uncompressed csv file from the [star2002 dataset].(https://sdm.lbl.gov/fastbit/data/samples.html)

```python
import sys
import numpy as np
import dask.dataframe
import distributed

dtypes = {
    'antiNucleus':  np.int,
    'eventFile':    np.uint,
    'eventNumber':  np.int,
    'eventTime':    np.double,
    'histFile':     np.uint,
    'multiplicity': np.int,
    'NaboveLb':     np.int,
    'NbelowLb':     np.int,
    'NLb':          np.int,
    'primaryTracks':np.int,
    'prodTime':     np.double,
    'Pt':           np.single,
    'runNumber':    np.int,
    'vertexX':      np.single,
    'vertexY':      np.single,
    'vertexZ':      np.single,
}

if __name__ == '__main__':
    client = distributed.Client()
    df = dask.dataframe.read_csv(sys.argv[1], dtype=dtypes, names=list(dtypes.keys()))
    s = ((df['vertexX']**2 + df['vertexX']**2 + df['vertexX']**2)**0.5).mean()
    print(s.compute())
```
</details>

**Comment by mrocklin** [comment]
This was recently fixed in master: https://github.com/dask/distributed/pull/1895

    pip install git+https://github.com/dask/distributed --upgrade --no-deps

**Comment by gsakkis** [comment]
Just a heads up, the fix doesn't seem to work when creating and passing a `LocalCluster` explicitly, i.e. `client = distributed.Client(distributed.LocalCluster())`.
