### ISSUE TITLE
Queue get(timeout=4) generates exceptions and scheduler eventually dies.

### ISSUE THREAD

**Issue by darindf** [dask/distributed#1911]
I have taken the following code to illustrate the issue. The queue get generates exceptions in the scheduler and worker processes which will then cause the scheduler to abort.

To run the code start the dask-scheduler and dask-worker on the local machine and run `python dask-ps`

```
# ==== dask-ps

import dask
from distributed import LocalCluster, Client, worker_client, Variable, Queue, fire_and_forget
import numpy as np
import time
import tornado

D = 10


def parameter_server():
    beta = np.zeros(D)
    with worker_client() as c:
        betas = Variable('betas', client=c)
        stop = Variable('stop', client=c)
        updates = Queue('updates', client=c)

        print('setting beta')
        [future_beta] = c.scatter([beta])
        betas.set(future_beta)

        while not stop.get():
            update = None
            try:
                update = updates.get(timeout=4).result()
            except tornado.util.TimeoutError as e:
                continue
            print("PS: received update: %s" % update)


if __name__ == '__main__':

    client = Client()
    betas = Variable('betas')
    stop = Variable('stop')
    updates = Queue('updates')
    stop.set(False)

    # start parameter server
    #res_ps = client.submit(parameter_server, workers=['ps'], pure=False)
    fire_and_forget(client.submit(parameter_server,  pure=False))
    time.sleep(60)  # show scheduler and worker queue exceptions

```

The the following errors repeatably on the dask-worker processes.

```
2018-04-09 12:23:03,014 - distributed.utils - ERROR -
Traceback (most recent call last):
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\utils.py", line 238, in f
    result[0] = yield make_coro()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\queues.py", line 207, in _get
    batch=batch)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\core.py", line 475, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\core.py", line 375, in send_recv
    six.reraise(*clean_exception(**response))
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\core.py", line 297, in handle_comm
    result = yield result
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\queues.py", line 114, in get
    record = yield self.queues[name].get(timeout=timeout)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
tornado.util.TimeoutError

```

And on the dask-scheduler

```
2018-04-09 12:23:02,915 - distributed.core - ERROR -
Traceback (most recent call last):
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\core.py", line 297, in handle_comm
    result = yield result
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\queues.py", line 114, in get
    record = yield self.queues[name].get(timeout=timeout)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
tornado.util.TimeoutError
```
Which will eventually fail/terminate with the error

```
2018-04-09 12:23:03,030 - distributed.scheduler - INFO - End scheduler at 'tcp://:8786'
Traceback (most recent call last):
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ddeforest\AppData\Local\conda\conda\envs\build\Scripts\dask-scheduler.exe\__main__.py", line 9, in <module>
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\cli\dask_scheduler.py", line 148, in go
    main()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\distributed\cli\dask_scheduler.py", line 136, in main
    loop.start()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\site-packages\tornado\platform\asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\asyncio\base_events.py", line 1395, in _run_once
    event_list = self._selector.select(timeout)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "c:\users\ddeforest\appdata\local\conda\conda\envs\build\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```

**Comment by mrocklin** [comment]
Thank you for the excellent bug report and the reproducible example.  I'm able to reproduce this on my machine.  I won't personally have time to look at it more deeply for the next couple days but would be happy to take a look afterwards.  If you're interested in tracking it down before then please don't hesitate, I'd be happy to help.

**Comment by mrocklin** [comment]
I believe that this has been resolved in https://github.com/dask/distributed/pull/1922

Closing.  Happy to reopen if the problem persists.

Thanks again for the reproducible example.

**Comment by darindf** [comment]
I have gotten the latest github master branch and tested.

The dask-worker no longer generates messages, so that is a positive change.

The dask-scheduler on the other hand, exhibits the same behavior as before and fatally terminates.

```
tornado.util.TimeoutError
2018-04-19 09:23:51,300 - distributed.core - ERROR -
Traceback (most recent call last):
  File "c:\users\ddeforest\documents\distributed\distributed\core.py", line 297, in handle_comm
    result = yield result
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ddeforest\documents\distributed\distributed\queues.py", line 123, in get
    record = yield self.queues[name].get(timeout=timeout)
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
tornado.util.TimeoutError
2018-04-19 09:23:51,309 - distributed.scheduler - INFO - End scheduler at 'tcp://:8786'
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\envs\build\Scripts\dask-scheduler-script.py", line 11, in <module>
    load_entry_point('distributed', 'console_scripts', 'dask-scheduler')()
  File "c:\users\ddeforest\documents\distributed\distributed\cli\dask_scheduler.py", line 148, in go
    main()
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ddeforest\documents\distributed\distributed\cli\dask_scheduler.py", line 136, in main
    loop.start()
  File "c:\ProgramData\Anaconda3\envs\build\lib\site-packages\tornado\platform\asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "c:\ProgramData\Anaconda3\envs\build\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "c:\ProgramData\Anaconda3\envs\build\lib\asyncio\base_events.py", line 1396, in _run_once
    event_list = self._selector.select(timeout)
  File "c:\ProgramData\Anaconda3\envs\build\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "c:\ProgramData\Anaconda3\envs\build\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```

**Comment by mrocklin** [comment]
Thanks for following up @darindf .  I may have improved the situation a bit in #1950 

Things are still imperfect, the scheduler emits unwanted warnings in logs, but hopefully everything should run smoothly.

**Comment by darindf** [comment]
I'm trying to incorporate this change into [gensim](https://github.com/RaRe-Technologies/gensim/pull/2035) as one of two alternate implementations as this approach allows me to create a server that can respond to requests, much like the tensorflow dask implementation does.  Thanks for looking into this

**Comment by mrocklin** [comment]
Thanks.  I'm glad to hear it.  BTW, feel free to mention things like that
earlier rather than later.   Supporting other projects in the Python
ecosystem is high on my priority list, so knowledge like that helps me to
focus attention.

I'll look into your work in a bit.  I'm looking forward to it.
