### ISSUE TITLE
Log_error infinite loop

### ISSUE THREAD

**Issue by EemeliSaari** [dask/distributed#1929]
Hello,

I came across this problem when developing with a LocalCluster and Jupyter Notebook. I had started the LocalCluster like so: [setup network](http://distributed.readthedocs.io/en/latest/setup.html#using-the-command-line) with 4 workers. I then connected to this cluster from the notebook with the lines:

`client = Client('<address>:8786')
client`

The following issue arrived when doing ANYTHING dask related. Loading dataframe, computing or running submits to the client.

---

distributed.utils - ERROR - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/distributed/utils.py", line 623, in log_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/distributed/bokeh/scheduler.py", line 562, in update
    if self.index and self.source.data['start']:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f4b974bdf28>, <Future finished exception=ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',)>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bokeh/util/tornado.py", line 96, in on_done
    log.error("".join(format_exception(*future.exc_info())))
AttributeError: 'Future' object has no attribute 'exc_info'

---

This Error would then run in the screen in a continuous loop updating the null_wrapper value and all the results from the computations couldn't be retrieved. All the Dask processes would still continue in the dashboard and they would finish up normally.
Also running the Dask processes normally, without a LocalCluster, worked just fine. 

After I interrupted the scheduler process I got the following:

^Cdistributed.scheduler - INFO - End scheduler at 'tcp://:8786'
Future exception was never retrieved
future: <Future finished exception=ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/bokeh/server/session.py", line 51, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/bokeh/server/session.py", line 157, in with_document_locked
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bokeh/document/document.py", line 1074, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/usr/local/lib/python3.5/dist-packages/bokeh/document/document.py", line 1060, in _with_self_as_curdoc
    return f()
  File "/usr/local/lib/python3.5/dist-packages/bokeh/document/document.py", line 1073, in invoke
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/distributed/bokeh/scheduler.py", line 562, in update
    if self.index and self.source.data['start']:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

---

I then went and fixed that part from the source code in the distributed/bokeh/scheduler.py line 562 added:

`if self.index and any(self.source.data['start']):`

This seems to have fixed the issue for me. Sorry if this is already a known issue but I couldn't find it.

**Lib versions:**
- python = 3.5.2
- bokeh = 0.12.15
- dask = 0.17.1
- distributed = 1.21.2
- tornado = 5.0

**Machine:**
- Ubuntu 16 64-bit

**Comment by mrocklin** [comment]
I recommend updating to the latest version of dask and distributed, where I
believe that this issue has been resolved.

**Comment by EemeliSaari** [comment]
It fixed the problem. Thank you!
