### ISSUE TITLE
Getting distributed.client.AllExit when skipping errors with client.gather

### ISSUE THREAD

**Issue by knkski** [dask/distributed#1932]
I have code that looks something like this:

```python
import itertools
from distributed import Client

def multiply(n):
    if n >= 20:
        raise ValueError('n must be below 20!')

    return n * 2

def chunks(iterable, chunk_size):
    iterable = iter(iterable)
    chunk = list(itertools.islice(iterable, chunk_size))
    while chunk:
        yield chunk
        chunk = list(itertools.islice(iterable, chunk_size))

def run():
    client = Client()

    print('Starting.')

    for i, chunk in enumerate(chunks(range(30), 5)):
        print(f'Processing chunk #{i}.')
        futures = [client.submit(multiply, nums) for nums in chunk]

        client.gather(futures, errors='skip')

    print('Done.')

if __name__ == '__main__':
    run()
```

In reality, `range(30)` is an iterator reading chunks of lines from a file, and `multiply` is transforming those chunks into something that is then stored in a database. The `if n >= 20: raise ValueError('n must be below 20!')` corresponds to some checking that a record is valid for storing in the database.

The trouble that I'm running into is that skipping the errors makes `client.gather` log numerous `distributed.client.AllExit` exceptions: 

```python
Starting.
Processing chunk #0.
Processing chunk #1.
Processing chunk #2.
Processing chunk #3.
Processing chunk #4.
distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (20)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (22)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (21)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (24)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (23)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61236: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61237: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61235: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61235: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61242: n must be below 20!
distributed.client - WARNING - Couldn't gather keys {'multiply-1b99c5e166ac42aa9bfd6be36a60fce4': []}
Processing chunk #5.
distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (25)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (26)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (29)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (27)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.worker - WARNING -  Compute Failed
Function:  multiply
args:      (28)
kwargs:    {}
Exception: ValueError('n must be below 20!',)

distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61236: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61235: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61235: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61242: n must be below 20!
distributed.scheduler - ERROR - error from worker tcp://127.0.0.1:61237: n must be below 20!
distributed.client - WARNING - Couldn't gather keys {'multiply-52e4fa19c34936a0780e58dd4d74de2a': [], 'multiply-af1b7816ad71e2246aac96c884100950': []}
Done.
tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x10e9c7ac8> exception was never retrieved: Traceback (most recent call last):
  File "/virtualenv/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/virtualenv/lib/python3.6/site-packages/distributed/client.py", line 1335, in wait
    raise AllExit()
distributed.client.AllExit
```

It appears that the script does actually complete despite the errors, so I guess this is either a bug report that unnecessary errors are being displayed, or a feature request for something like this:

    results, errors = client.gather(futures, errors='return')

In this trivial example, it's easy to ignore the `distributed.client.AllExit` message, but when thousands or more records are rejected as invalid, it gets to be really noisy.

**Comment by mrocklin** [comment]
Thank you for the excellent issue and reproducible example @knkski .  I appreciate it.  You also have my apologies for the slow response here.  

If you have a chance to try out a possible fix in https://github.com/dask/distributed/pull/1936 your feedback there would be welcome.

**Comment by knkski** [comment]
@mrocklin: That looks good to me, thanks!
