### ISSUE TITLE
Small logging error

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#1982]
looks like you don't want parens around the args. (distributed version 1.21.8)

--- Logging error ---
Traceback (most recent call last):
  File " envs/a2/lib/python3.5/logging/__init__.py", line 986, in emit
    msg = self.format(record)
  File " envs/a2/lib/python3.5/logging/__init__.py", line 836, in format
    return fmt.format(record)
  File " envs/a2/lib/python3.5/logging/__init__.py", line 573, in format
    record.message = record.getMessage()
  File " envs/a2/lib/python3.5/logging/__init__.py", line 336, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "<string>", line 1, in <module>
  File " envs/a2/lib/python3.5/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File " envs/a2/lib/python3.5/multiprocessing/spawn.py", line 119, in _main
    return self._bootstrap()
  File " envs/a2/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File " envs/a2/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File " envs/a2/lib/python3.5/site-packages/distributed/process.py", line 174, in _run
    target(*args, **kwargs)
  File " envs/a2/lib/python3.5/site-packages/distributed/nanny.py", line 556, in _run
    loop.run_sync(run)
  File " envs/a2/lib/python3.5/site-packages/tornado/ioloop.py", line 453, in run_sync
    self.start()
  File " envs/a2/lib/python3.5/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File " envs/a2/lib/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File " envs/a2/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File " envs/a2/lib/python3.5/site-packages/tornado/gen.py", line 1152, in inner
    self.run()
  File " envs/a2/lib/python3.5/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File " envs/a2/lib/python3.5/site-packages/distributed/client.py", line 1418, in _gather
    log("Couldn't gather %s keys, rescheduling %s", (len(response['keys']), response['keys']))
Message: "Couldn't gather %s keys, rescheduling %s"

**Comment by mrocklin** [comment]
Thanks!  https://github.com/dask/distributed/pull/1983
