### ISSUE TITLE
Support for sortedcontainers 2.0.0

### ISSUE THREAD

**Issue by michcio1234** [dask/distributed#1991]
It seems that a recent version of `sortedcontainers` broke something. Here's what recently started to happen to my dask-scheduler after a client submits a job:
```
dask-scheduler    | distributed.scheduler - ERROR - 'SortedDict' object has no attribute 'iloc'
dask-scheduler    | Traceback (most recent call last):
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3247, in transition_waiting_processing
dask-scheduler    |     ws = self.decide_worker(ts)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3225, in decide_worker
dask-scheduler    |     worker = self.workers[self.workers.iloc[self.n_tasks % len(self.workers)]]
dask-scheduler    | AttributeError: 'SortedDict' object has no attribute 'iloc'
dask-scheduler    | distributed.scheduler - ERROR - Error transitioning "('read-parquet-4d5dcec6962fbc6a1b3db55df3684d42', 0)" from 'waiting' to 'processing'
dask-scheduler    | Traceback (most recent call last):
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3786, in transition
dask-scheduler    |     recommendations = func(key, *args, **kwargs)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3247, in transition_waiting_processing
dask-scheduler    |     ws = self.decide_worker(ts)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3225, in decide_worker
dask-scheduler    |     worker = self.workers[self.workers.iloc[self.n_tasks % len(self.workers)]]
dask-scheduler    | AttributeError: 'SortedDict' object has no attribute 'iloc'
dask-scheduler    | distributed.scheduler - ERROR - 'SortedDict' object has no attribute 'iloc'
dask-scheduler    | Traceback (most recent call last):
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1965, in handle_client
dask-scheduler    |     result = handler(**msg)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1458, in update_graph
dask-scheduler    |     self.transitions(recommendations)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3845, in transitions
dask-scheduler    |     new = self.transition(key, finish)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3786, in transition
dask-scheduler    |     recommendations = func(key, *args, **kwargs)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3247, in transition_waiting_processing
dask-scheduler    |     ws = self.decide_worker(ts)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3225, in decide_worker
dask-scheduler    |     worker = self.workers[self.workers.iloc[self.n_tasks % len(self.workers)]]
dask-scheduler    | AttributeError: 'SortedDict' object has no attribute 'iloc'
dask-scheduler    | distributed.scheduler - ERROR - Exception in handle_client
dask-scheduler    | Traceback (most recent call last):
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1965, in handle_client
dask-scheduler    |     result = handler(**msg)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 1458, in update_graph
dask-scheduler    |     self.transitions(recommendations)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3845, in transitions
dask-scheduler    |     new = self.transition(key, finish)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3786, in transition
dask-scheduler    |     recommendations = func(key, *args, **kwargs)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3247, in transition_waiting_processing
dask-scheduler    |     ws = self.decide_worker(ts)
dask-scheduler    |   File "/opt/conda/lib/python3.5/site-packages/distributed/scheduler.py", line 3225, in decide_worker
dask-scheduler    |     worker = self.workers[self.workers.iloc[self.n_tasks % len(self.workers)]]
dask-scheduler    | AttributeError: 'SortedDict' object has no attribute 'iloc'
dask-scheduler    | distributed.scheduler - INFO - Close client connection: Client-328dead4-5cf3-11e8-8001-0242ac180004
```
After some searching I've found this pretty new issue: https://github.com/grantjenks/python-sortedcontainers/issues/92 which seems to describe the problem that causes my issue. 
Documentation on `sortedcontainers` update can be found here: https://github.com/grantjenks/python-sortedcontainers/blob/master/HISTORY.rst#id2

**Comment by mrocklin** [comment]
Thank you for raising this issue and tracking down the problem.  I've chimed in here https://github.com/grantjenks/python-sortedcontainers/issues/92#issuecomment-390645171

**Comment by grantjenks** [comment]
Author of sortedcontainers here. I've deployed v2.0.2 to PyPI which adds the ".iloc" attribute back to sorted dict. Sorry for the break!

**Comment by mrocklin** [comment]
I believe that, with @grantjenks 's help, this is now resolved.
