### ISSUE TITLE
diagnostics.progress doesn't support TLS authenticated connections

### ISSUE THREAD

**Issue by michaelgriffiths-mclaren** [dask/distributed#2032]
**Version: 0.17.4**

I'm trying to display a ProgressBar within a Juypter notebook, I'm using a remote cluster which is authenticated with TLS.  Calling the progress() method with a future throws the exception `TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)`

The below snippet can recreate the issue, note that execution without the progress() function works fine.

```
from time import sleep
from distributed import Client
from distributed.diagnostics import progress
from distributed.security import Security

sec = Security(tls_ca_file='rootCA.crt',
               tls_client_cert='client.crt',
               tls_client_key='client.key',
               require_encryption=True)

client = Client('tls://<IP_ADDR>:8786', security=sec)

futures = client.map(sleep, [1] * 100)
progress(futures, notebook=True)
```

Full stack trace:
```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f944cbf4bf8>, <tornado.concurrent.Future object at 0x7f944d46eac8>)
Traceback (most recent call last):
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/distributed/diagnostics/progressbar.py", line 188, in listen
    self.comm = yield connect(self.scheduler)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/distributed/comm/core.py", line 185, in connect
    quiet_exceptions=EnvironmentError)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/distributed/comm/tcp.py", line 303, in connect
    kwargs = self._get_connect_args(**connection_args)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/distributed/comm/tcp.py", line 336, in _get_connect_args
    ctx = _expect_tls_context(connection_args)
  File "/opt/anaconda/envs/Python3/lib/python3.6/site-packages/distributed/comm/tcp.py", line 282, in _expect_tls_context
    raise TypeError("TLS expects a `ssl_context` argument of type "
TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)
```

**Comment by mrocklin** [comment]
Thanks for the error report.  I believe that this is now fixed in
https://github.com/dask/distributed/pull/2035

If you have a chance to give it a try that would be welcome.

On Thu, Jun 7, 2018 at 10:05 AM, Michael Griffiths <notifications@github.com
