### ISSUE TITLE
KeyError in scheduler for task that's submitted from within a joblib.Parallel call

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#2034]
I'm seeing a key error in the distributed scheduler, where a tasks is apparently forgotten while it has dependents.

code:

<details>

```python
import dask  # noqa
import distributed
import logging
from dask_ml.datasets import make_classification
from dask_ml.wrappers import Incremental
from dask_ml.metrics import get_scorer
from sklearn.linear_model import SGDClassifier

import sklearn.model_selection
import dask_ml.model_selection  # noqa
import dask_ml.joblib  # noqa
from sklearn.externals import joblib
import numpy as np  # noqa

from distributed import Client

handler = logging.FileHandler("bug.log", mode="w")
FORMAT = '[%(asctime)-15s] %(filename)s - %(lineno)d - %(message)s'
formatter = logging.Formatter(FORMAT)
handler.setLevel(logging.INFO)
handler.setFormatter(formatter)

loggers = [
    logging.getLogger(__name__),
    logging.getLogger('distributed.client'),
    logging.getLogger('distributed.core'),
    logging.getLogger('distributed.scheduler'),
]
for logger in loggers:
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

logger = loggers[0]

# KeyError: "('astype-lt-getitem-fe947b8291fa5d0276b0b63d123fa1f0', 1)"


def main():
    logger.info('#' * 80)
    logger.info("Starting")
    logger.info("#" * 80)
    cluster = distributed.LocalCluster(n_workers=2, processes=False)
    client = Client(cluster)  # noqa
    dask.config.set(**{'distributed.scheduler.transition-log-length': 1000})

    X, y = make_classification(n_samples=100_000, chunks=50_000)
    logger.info("%0.2f GBs, %s blocks", X.nbytes / 1e9, X.numblocks)

    clf = SGDClassifier(random_state=0)
    scorer = get_scorer('accuracy', compute=True)
    inc = Incremental(clf, scoring='accuracy')
    param_grid = {
        'alpha': [0.1, 10],
    }

    gs1 = sklearn.model_selection.GridSearchCV(inc, param_grid, iid=False,
                                               refit=False, verbose=2, cv=2,
                                               scoring=scorer,
                                               n_jobs=-1)

    with joblib.parallel_backend('dask'):
        gs1.fit(X, y, classes=[0, 1])
    print("Random... OK")
    client.close()


__spec__ = 'bug.py'


if __name__ == '__main__':
    main()

```

</details>

run: `python -m pdb bug.py`

Raises first with `distributed.core - ERROR - "('astype-lt-getitem-f3343717f65b5a2d7d21c3162096a6f7', 0)"`

Full output

<details>

```python
python bug.py
Fitting 2 folds for each of 2 candidates, totalling 4 fits
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 8 concurrent workers.
[CV] alpha=0.1 .......................................................
[CV] alpha=0.1 .......................................................
[CV] alpha=10 ........................................................
[CV] alpha=10 ........................................................
distributed.core - ERROR - "('astype-lt-getitem-f3343717f65b5a2d7d21c3162096a6f7', 0)"
Traceback (most recent call last):
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 375, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1355, in update_graph
    ts = self.tasks[key]
KeyError: "('astype-lt-getitem-f3343717f65b5a2d7d21c3162096a6f7', 0)"
distributed.core - ERROR - "('astype-lt-getitem-f3343717f65b5a2d7d21c3162096a6f7', 0)"
Traceback (most recent call last):
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 321, in handle_comm
    result = yield result
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1922, in add_client
    yield self.handle_stream(comm=comm, extra={'client': client})
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 375, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1355, in update_graph
    ts = self.tasks[key]
KeyError: "('astype-lt-getitem-f3343717f65b5a2d7d21c3162096a6f7', 0)"
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x110f3dd08>, <Future finished exception=CancelledError(['_fit_and_score-batch-dd043c7d6d2c4a54bd3f7b7da330b4d1'],)>)
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 781, in _discard_future_result
    future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/taugspurger/sandbox/distributed/distributed/joblib.py", line 241, in callback_wrapper
    result = yield _wait([future])
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 3345, in _wait
    raise CancelledError(cancelled)
concurrent.futures._base.CancelledError: ['_fit_and_score-batch-dd043c7d6d2c4a54bd3f7b7da330b4d1']
distributed.core - ERROR - 'Client-d53d2f0c-6a62-11e8-be52-186590cd1c87'
Traceback (most recent call last):
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 318, in handle_comm
    result = handler(comm, **msg)
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1677, in stimulus_cancel
    self.cancel_key(key, client, force=force)
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1683, in cancel_key
    cs = self.clients[client]
KeyError: 'Client-d53d2f0c-6a62-11e8-be52-186590cd1c87'
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x110ab70d0>, <Future finished exception=CancelledError(['_fit_and_score-batch-53b25566c6a44001ad0caab659968a73'],)>)
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 781, in _discard_future_result
    future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/taugspurger/sandbox/distributed/distributed/joblib.py", line 241, in callback_wrapper
    result = yield _wait([future])
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 3345, in _wait
    raise CancelledError(cancelled)
concurrent.futures._base.CancelledError: ['_fit_and_score-batch-53b25566c6a44001ad0caab659968a73']
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x110f42510>, <Future finished exception=CancelledError(['_fit_and_score-batch-5c6c492c8d484fda8b588188a8871996'],)>)
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 781, in _discard_future_result
    future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/taugspurger/sandbox/distributed/distributed/joblib.py", line 241, in callback_wrapper
    result = yield _wait([future])
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 3345, in _wait
    raise CancelledError(cancelled)
concurrent.futures._base.CancelledError: ['_fit_and_score-batch-5c6c492c8d484fda8b588188a8871996']
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x110f81158>, <Future finished exception=CancelledError(['_fit_and_score-batch-f4f4f82e1cdc4d4f8c99558e53bcd8d8'],)>)
Traceback (most recent call last):
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/ioloop.py", line 781, in _discard_future_result
    future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/taugspurger/sandbox/distributed/distributed/joblib.py", line 241, in callback_wrapper
    result = yield _wait([future])
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 3345, in _wait
    raise CancelledError(cancelled)
concurrent.futures._base.CancelledError: ['_fit_and_score-batch-f4f4f82e1cdc4d4f8c99558e53bcd8d8']
Traceback (most recent call last):
  File "/Users/taugspurger/sandbox/scikit-learn/sklearn/externals/joblib/parallel.py", line 850, in retrieve
    self._output.extend(job.get())
  File "/Users/taugspurger/sandbox/distributed/distributed/joblib.py", line 251, in get
    return ref().result()
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 194, in result
    raise result
concurrent.futures._base.CancelledError: _fit_and_score-batch-dd043c7d6d2c4a54bd3f7b7da330b4d1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 71, in <module>
    main()
  File "bug.py", line 62, in main
    gs1.fit(X, y, classes=[0, 1])
  File "/Users/taugspurger/sandbox/scikit-learn/sklearn/model_selection/_search.py", line 660, in fit
    cv.split(X, y, groups)))
  File "/Users/taugspurger/sandbox/scikit-learn/sklearn/externals/joblib/parallel.py", line 955, in __call__
    self.retrieve()
  File "/Users/taugspurger/sandbox/scikit-learn/sklearn/externals/joblib/parallel.py", line 870, in retrieve
    backend.abort_everything(ensure_ready=ensure_ready)
  File "/Users/taugspurger/sandbox/distributed/distributed/joblib.py", line 261, in abort_everything
    self.client.cancel(self.task_futures)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 1799, in cancel
    force=force)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 652, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/taugspurger/sandbox/distributed/distributed/utils.py", line 275, in sync
    six.reraise(*error[0])
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/taugspurger/sandbox/distributed/distributed/utils.py", line 260, in f
    result[0] = yield make_coro()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 1778, in _cancel
    yield self.scheduler.cancel(keys=keys, client=self.id, force=force)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 552, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 446, in send_recv
    six.reraise(*clean_exception(**response))
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/taugspurger/sandbox/distributed/distributed/core.py", line 318, in handle_comm
    result = handler(comm, **msg)
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1677, in stimulus_cancel
    self.cancel_key(key, client, force=force)
  File "/Users/taugspurger/sandbox/distributed/distributed/scheduler.py", line 1683, in cancel_key
    cs = self.clients[client]
KeyError: 'Client-d53d2f0c-6a62-11e8-be52-186590cd1c87'
```
</details>

Haven't had a chance to minimize the example yet.

**Comment by mrocklin** [comment]
Are there particular versions that I would need to install to reproduce this?

**Comment by TomAugspurger** [comment]
Sorry, this would be dask-ml master.

I can reproduce with scikit-learn 0.19.1.

**Comment by mrocklin** [comment]
Any joblib constraints?

**Comment by TomAugspurger** [comment]
Nope, thanks to scikit-learn vendoring it :)

**Comment by mrocklin** [comment]
Possibly resolved in https://github.com/dask/distributed/pull/2036
