### ISSUE TITLE
KeyError in distributed joblib

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#2058]
I haven't been able to reproduce the locally yet.

This is on distributed, dask, & dask-ml master, and the scikit-learn / joblib we used at the sprint.

I'm doing

```python
%%time
with joblib.parallel_backend("dask"):
    gs.fit(X, y, classes=[0, 1])
```

with X and y being dask arrays (so can't pre-scatter).

The behavior I observe is

1. Make the call, tasks show up in the dashboard
2. A short time later, the tasks go black / gray, indicating they failed
3. The notebook is hanging
4. ctrl-C to interrupt (the keyboard interrupt you see in the exception below)

```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fc37ad6fbf8>, <Future finished exception=AssertionError("yield from wasn't used with future",)>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/joblib.py", line 204, in maybe_to_futures
    f = call_data_futures[arg]
  File "/opt/conda/lib/python3.6/site-packages/distributed/joblib.py", line 67, in __getitem__
    ref, val = self._data[id(obj)]
KeyError: 140477560921584

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/distributed/joblib.py", line 244, in callback_wrapper
    callback(result)  # gets called in separate thread
  File "/home/jovyan/src/scikit-learn/sklearn/externals/joblib/parallel.py", line 326, in __call__
    self.parallel.dispatch_next()
  File "/home/jovyan/src/scikit-learn/sklearn/externals/joblib/parallel.py", line 746, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/jovyan/src/scikit-learn/sklearn/externals/joblib/parallel.py", line 774, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/jovyan/src/scikit-learn/sklearn/externals/joblib/parallel.py", line 731, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/conda/lib/python3.6/site-packages/distributed/joblib.py", line 234, in apply_async
    func, args = self._to_func_args(func)
  File "/opt/conda/lib/python3.6/site-packages/distributed/joblib.py", line 224, in _to_func_args
    args = list(maybe_to_futures(args))
  File "/opt/conda/lib/python3.6/site-packages/distributed/joblib.py", line 212, in maybe_to_futures
    [f] = self.client.scatter([arg], broadcast=3)
AssertionError: yield from wasn't used with future

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/distributed/joblib.py in maybe_to_futures(args)
    203                     try:
--> 204                         f = call_data_futures[arg]
    205                     except KeyError:

/opt/conda/lib/python3.6/site-packages/distributed/joblib.py in __getitem__(self, obj)
     66     def __getitem__(self, obj):
---> 67         ref, val = self._data[id(obj)]
     68         if ref() is not obj:

KeyError: 140477560921344

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<timed exec> in <module>()

~/src/scikit-learn/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    658                                   error_score=self.error_score)
    659           for parameters, (train, test) in product(candidate_params,
--> 660                                                    cv.split(X, y, groups)))
    661 
    662         # if one choose to see train score, "out" will contain train score info

~/src/scikit-learn/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    943                 self._iterating = self._original_iterator is not None
    944 
--> 945             while self.dispatch_one_batch(iterator):
    946                 pass
    947 

~/src/scikit-learn/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    772                 return False
    773             else:
--> 774                 self._dispatch(tasks)
    775                 return True
    776 

~/src/scikit-learn/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    729         with self._lock:
    730             job_idx = len(self._jobs)
--> 731             job = self._backend.apply_async(batch, callback=cb)
    732             # A job can complete so quickly than its callback is
    733             # called before we get here, causing self._jobs to

/opt/conda/lib/python3.6/site-packages/distributed/joblib.py in apply_async(self, func, callback)
    232     def apply_async(self, func, callback=None):
    233         key = '%s-batch-%s' % (joblib_funcname(func), uuid4().hex)
--> 234         func, args = self._to_func_args(func)
    235 
    236         future = self.client.submit(func, *args, key=key, **self.submit_kwargs)

/opt/conda/lib/python3.6/site-packages/distributed/joblib.py in _to_func_args(self, func)
    222         tasks = []
    223         for f, args, kwargs in func.items:
--> 224             args = list(maybe_to_futures(args))
    225             kwargs = dict(zip(kwargs.keys(), maybe_to_futures(kwargs.values())))
    226             tasks.append((f, args, kwargs))

/opt/conda/lib/python3.6/site-packages/distributed/joblib.py in maybe_to_futures(args)
    210                             # more workers need to reuse this data concurrently
    211                             # beyond the initial broadcast arity.
--> 212                             [f] = self.client.scatter([arg], broadcast=3)
    213                             call_data_futures[arg] = f
    214 

/opt/conda/lib/python3.6/site-packages/distributed/client.py in scatter(self, data, workers, broadcast, direct, hash, maxsize, timeout, asynchronous)
   1771                              broadcast=broadcast, direct=direct,
   1772                              local_worker=local_worker, timeout=timeout,
-> 1773                              asynchronous=asynchronous, hash=hash)
   1774 
   1775     @gen.coroutine

/opt/conda/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    650             return future
    651         else:
--> 652             return sync(self.loop, func, *args, **kwargs)
    653 
    654     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    271     else:
    272         while not e.is_set():
--> 273             e.wait(10)
    274     if error[0]:
    275         six.reraise(*error[0])

/opt/conda/lib/python3.6/threading.py in wait(self, timeout)
    549             signaled = self._flag
    550             if not signaled:
--> 551                 signaled = self._cond.wait(timeout)
    552             return signaled
    553 

/opt/conda/lib/python3.6/threading.py in wait(self, timeout)
    297             else:
    298                 if timeout > 0:
--> 299                     gotit = waiter.acquire(True, timeout)
    300                 else:
    301                     gotit = waiter.acquire(False)

KeyboardInterrupt: 
```

**Comment by TomAugspurger** [comment]
cc @ogrisel in case you can make anything out of the traceback alone.  Otherwise, I'm trying to reproduce locally now.

**Comment by mrocklin** [comment]
@TomAugspurger can you include the context of how this was called?  I want to verify that this isn't happening within a Tornado coroutine, such as within a `@gen_cluster` style test.

**Comment by TomAugspurger** [comment]
edited the original post. I'm happy to debug things.

**Comment by TomAugspurger** [comment]
Hmm, the cluster I'm on has mismatched dask versions somehow. Going to try updating those to match.

**Comment by TomAugspurger** [comment]
joblib may be a red herring here... I'm able to reproduce on the cluster without it

```python
from dask.distributed import Client
from distributed import wait
from dask_ml.datasets import make_classification

client = Client("tcp://104.154.73.194:8786")
client

# X, y = make_classification(n_samples=20_000_000, n_features=100, chunks=40_000)
X, y = make_classification(n_samples=15000, n_features=10, chunks=100)

X, y = client.persist([X, y])
wait(X);

def func(x, ind):
    return x[ind].sum().compute()

ind = [0, 10, 20, 30]

f = client.submit(func, X, ind)
wait(f)
```

`f.result()` raises with


```pytb
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<ipython-input-10-007d59320aa9> in <module>()
----> 1 f.result()

/opt/conda/lib/python3.6/site-packages/distributed/client.py in result(self, timeout)
    190                                   raiseit=False)
    191         if self.status == 'error':
--> 192             six.reraise(*result)
    193         elif self.status == 'cancelled':
    194             raise result

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

<ipython-input-8-ca45a53c05bb> in func()
     13 
     14 def func(x, ind):
---> 15     return x[ind].sum().compute()
     16 
     17 ind = [0, 10, 20, 30]

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute()
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute()
    398     keys = [x.__dask_keys__() for x in collections]
    399     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 400     results = schedule(dsk, keys, **kwargs)
    401     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    402 

/opt/conda/lib/python3.6/site-packages/distributed/client.py in get()
   2145                                          fifo_timeout=fifo_timeout,
   2146                                          retries=retries,
-> 2147                                          user_priority=priority,
   2148                                          )
   2149         packed = pack_data(keys, futures)

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _graph_to_futures()
   2076                 for v in s:
   2077                     if v not in self.futures:
-> 2078                         raise CancelledError(v)
   2079 
   2080             dependencies = {k: get_dependencies(dsk, k) for k in dsk}

CancelledError: ('normal-462aa172a476cc7b0b0d2b0a5371c902', 0, 0)
```

**Comment by mrocklin** [comment]
Can you try distributed master and see if this is resolved there?  I'm
unable to reproduce and it looks similar to a recent fix.

**Comment by TomAugspurger** [comment]
I'm on distributed https://github.com/TomAugspurger/distributed/tree/joblib-autoscatter-flag (which is distributed master + some logging in joblib.distributed)

Narrowing down further, here's a dask + distributed example (no dask-ml) that errors.

```python
X = da.random.uniform(size=(100, 10), chunks=50)
X = client.persist(X)
wait(X);

def func(x, ind):
    return x[ind].sum().compute()

ind = [0, 10, 20, 30]

f = client.submit(func, X, ind)
```

The fact that this doesn't reproduce locally leads me to suspect it's an issue with the deployment, not distributed.

**Comment by TomAugspurger** [comment]
Hmm, this isn't right `client.get_versions()` is reporting   `('distributed', '1.16.2+589.ge0baf905')` for all the workers and scheduler. Hopefully that's it.

**Comment by mrocklin** [comment]
Master is at 1.22.0.  Versioneer can also be a bit odd when operating from
github if a fork doesn't have the relevant tags.  You might try fetching
tags from dask, and pushing to your fork.

Also, if you branched off more than a few days ago then I recommend pulling
from master

**Comment by TomAugspurger** [comment]
So I'm working through the following setup.

1. Update the dask-docker images to latest and build those (in minikube):

```diff
diff --git a/base/Dockerfile b/base/Dockerfile
index 92f79a2..e2012ef 100644
--- a/base/Dockerfile
+++ b/base/Dockerfile
@@ -8,8 +8,8 @@ RUN conda update conda && conda install "conda=4.4.7"
 RUN conda install --yes \
     python-blosc \
     cytoolz \
-    dask==0.17.4  \
-    distributed==1.21.8 \
+    dask==0.18.0  \
+    distributed==1.22.0 \
     nomkl \
     numpy==1.14.2 \
     pandas==0.22.0 \
diff --git a/notebook/Dockerfile b/notebook/Dockerfile
index a62b44b..4abd775 100644
--- a/notebook/Dockerfile
+++ b/notebook/Dockerfile
@@ -11,8 +11,8 @@ RUN conda update conda && conda install "conda=4.4.7"
 RUN conda install --yes \
     python-blosc \
     cytoolz \
-    dask==0.17.4 \
-    distributed==1.21.8 \
+    dask==0.18.0 \
+    distributed==1.22.0 \
     nomkl \
     numpy==1.14.2 \
     pandas==0.22.0 \
```
2. Helm deployment with those images:

```yaml
scheduler:
    image:
        repository: "tomaugspurger/dask"
        tag: "latest"
        pullPolicy: "Never"

worker:
  image:
    repository: "tomaugspurger/dask"
    tag: "latest"
    pullPolicy: "Never"
  replicas: 1

jupyter:
  image:
    repository: "tomaugspurger/dask-notebook"
    tag: "latest"
    pullPolicy: "Never"
```
3. Run the following

```python
from distributed import wait, Client
import dask.array as da


def func(x):
    return x.sum().compute()


def main(scheduler):
    client = Client(scheduler)
    X = da.random.uniform(size=(100, 10), chunks=50)
    y = client.persist(X)
    wait(y)

    fut = client.submit(func, y)
    print(fut.result())


if __name__ == '__main__':
    import sys
    main(sys.argv[1])
```

as `python bug.py tcp://192.168.99.100:31286`

And the traceback is

```pytb
Traceback (most recent call last):
  File "bug.py", line 21, in <module>
    main(sys.argv[1])
  File "bug.py", line 16, in main
    print(fut.result())
  File "/Users/taugspurger/sandbox/distributed/distributed/client.py", line 192, in result
    six.reraise(*result)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "bug.py", line 6, in func
    return x.sum().compute()
  File "/opt/conda/lib/python3.6/site-packages/dask/base.py", line 156, in compute
  File "/opt/conda/lib/python3.6/site-packages/dask/base.py", line 400, in compute
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 2147, in get
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 2078, in _graph_to_futures
concurrent.futures._base.CancelledError: ('da.random.uniform-f481fae2e4a067302fe54b5efdea6392', 0, 0)
```

The error does not occur when using `docker-compose up` with the `docker-compose.yaml` from `dask/dask-docker`.

**Comment by TomAugspurger** [comment]
Ah interesting... If I run that script from the `dask-jupyter` pod, things are fine. Has to be something with my environment...

**Comment by TomAugspurger** [comment]
Breakthrough! (kind of).

It seems like the *name* of the origin Client created by the user matters.

When I use the "external" IP of the scheduler, this raises the CancellationError

```python
from distributed import Client, wait
import dask.array as da

client = Client('tcp://35.224.126.117:8786')

X = client.persist(da.random.uniform(size=(100, 10), chunks=50))
wait(X)

fut = client.submit(lambda x: x.sum().compute(), X)
wait(fut);
```

But, when I use the `dask-scheduler:8786` name that something (kubernetes I assume) is forwarding, things work!

```python
from distributed import Client, wait
import dask.array as da

client = Client('dask-cluster-scheduler:8786')  # <helm deployment name>-scheduler:8786

X = client.persist(da.random.uniform(size=(100, 10), chunks=50))
wait(X)

fut = client.submit(lambda x: x.sum().compute(), X)
wait(fut);
```

**Comment by mrocklin** [comment]
Any chance that there is a different dask cluster running on your kubernetes cluster?  It might be interesting to compare the result of `client.scheduler_info()` in both cases.

**Comment by TomAugspurger** [comment]
> Any chance that there is a different dask cluster running on your kubernetes cluster?

I don't think so. This is a freshly created cluster, and I've only done `helm install ` on it.

Here's the diff of the two scheduler infos

```diff
diff --git a/a b/b
index 79b85ec..ed0bd65 100644
--- a/a
+++ b/b
@@ -12,9 +12,9 @@
    'pid': 20,
    'cpu': 2.0,
    'memory': 52473856,
-   'time': 1529512330.9301662,
-   'read_bytes': 549.0768218641791,
-   'write_bytes': 944.412133606388,
+   'time': 1529512333.4300387,
+   'read_bytes': 548.7236623644762,
+   'write_bytes': 943.8046992668991,
    'num_fds': 46,
    'executing': 0,
    'in_memory': 10,
```

Nothing interesting there.

**Comment by mrocklin** [comment]
OK, that seems odd to me.  I don't at first glance see what's going on.  i wonder that now that you've determined that the scheduler address has something to do with it if you're able to reproduce it locally by fooling around with different scheduler addresses locally.  For example you might use `127.0.0.2` as a novel alias for localhost.

**Comment by mrocklin** [comment]
The logic within get_client also seems a bit finicky about addresses.  I would try to see if I could reproduce this locally first though, just to reduce iteration times.

**Comment by TomAugspurger** [comment]
Ah, good idea. I was going to try with a local helm deployment.

---

Setup:

1. `bug.py` with

```python
from distributed import wait, Client
import dask.array as da


def main(scheduler):
    client = Client(scheduler)
    X = client.persist(da.random.uniform(size=(100, 10), chunks=50))
    wait(X)

    fut = client.submit(lambda x: x.sum().compute(), X)
    print(fut.result())


if __name__ == '__main__':
    import sys
    main(sys.argv[1])
```

2. Start scheduler: `dask-scheduler --host=127.0.0.1 --port=8786 `
3. Start worker: `dask-worker 127.0.0.1:8786`
4. Output

```
$ python bug.py 127.0.0.1:8786 
505.08135536508803
$ python bug.py localhost:8786 
# ...
concurrent.futures._base.CancelledError: ('uniform-45e0df19fda79f3c1488f027479848ba', 1, 0)
```

**Comment by TomAugspurger** [comment]
I'll rewrite that to be suitable for a unit test, and then check on a fix.

**Comment by mrocklin** [comment]
If you can use the asynchronous gen_cluster style tests then you will be
able to inspect state everywhere, use breakpoints, etc., which can be very
helpful in cases like this.

**Comment by dhirschfeld** [comment]
Interesting. I've observed an (intermittent?) KeyError/Cancelled bug with `dask-ml` but haven't gotten around to tracking it down. Hopefully it's the same issue as already resolved here!

I'll report back if I continue to observe the problem and will make sure to test `1.22.1`  when it's released...

**Comment by asifali22** [comment]
Given the below code:
```
from sklearn.externals.joblib import parallel_backend
import dask_ml.joblib

with parallel_backend('dask'):
    pass
```
I keep getting this error:
```
Traceback (most recent call last):
  File "diya_libs/ek_aur_main.py", line 25, in <module>
    with parallel_backend('dask'):
  File "/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 97, in parallel_backend
    backend = BACKENDS[backend](**backend_params)
KeyError: 'dask'
```
But when I change `dask` to `distributed` it works.
```
with parallel_backend('distributed'):
    pass
```
Does it make any difference on performance or any other metrics?
@mrocklin  @TomAugspurger  Please suggest.

**Comment by TomAugspurger** [comment]
@asifali22 what versions of distributed and joblib?

**Comment by ogrisel** [comment]
With scikit-learn 0.20.rc1 you can just do:

```python
from sklearn.externals.joblib import parallel_backend

with parallel_backend('dask'):
    pass
```

as long as you have an active distributed client instance.

**Comment by ebo** [comment]
ok.  colour me befuddles.  I had the above code snippet working momentarily in a new clean miniconda environment.  Then I installed bokeh (so that I could visualize the execution to make sure it was doing what I was expecting).  After that I was not able to get it to work no matter what I did.  Now it is giving --  KeyError: 'dask'

As a note, I have tried running this using the system supplied distributed package, as well as distributed and dask-ml master using "pip install -e ..."

Suggestions?

**Comment by ebo** [comment]
As a note, I just hacked ~/miniconda3_7/envs/dask-ml/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py where it was dieing at the line:

--> 102         backend = BACKENDS[backend](**backend_params)
    103     old_backend_and_jobs = getattr(_backend, 'backend_and_jobs', None)

and dumped the following variables:

params:
basestring: <class 'str'>
backend: dask
BACKENDS: {'multiprocessing': <class 'sklearn.externals.joblib._parallel_backends.MultiprocessingBackend'>, 'threading': <class 'sklearn.externals.joblib._parallel_backends.ThreadingBackend'>, 'sequential': <class 'sklearn.externals.joblib._parallel_backends.SequentialBackend'>}

----------

it looks like dask and distributed are no longer registered as backends.  Any idea why that might have changed?  I'll keep digging, but this feels like the gofer in Caddy Shack.

**Comment by ebo** [comment]
ok.  Might have found it.  I just reinstalled dask-ml with pip and it works again.  I guess that installing bokeh overwrote something that dask-ml was expecting and it was incompatible.  Not sure what that was other than reinstalling dask-ml also uninstalled and reinstalled sklearn.
