### ISSUE TITLE
thread.lock error on Client

### ISSUE THREAD

**Issue by sdswart** [dask/distributed#2067]
Upon upgrading to version 1.22.0 a new client connection from an IPython console (python 3.6) results in the error:
TypeError: can't pickle _thread.lock objects

```python
from distributed import Client 
client = Client("192.168.0.145:8786")
```

result:

```
distributed.Client('192.168.0.145:8786')
Traceback (most recent call last):

  File "<ipython-input-5-dcc417779e1e>", line 1, in <module>
    distributed.Client('192.168.0.145:8786')

  File "C:\ProgramData\Anaconda3\lib\site-packages\distributed\client.py", line 544, in __init__
    dask.set_options(get=self.get)

  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\context.py", line 26, in set_options
    return config.set(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\config.py", line 232, in __init__
    self.old = copy.deepcopy(config)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 247, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "C:\ProgramData\Anaconda3\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)

TypeError: can't pickle _thread.lock objects
```

Versions:
dask - '0.18.0'
distributed - '1.21.0'
sys - '3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]'

Thanks for your help

**Comment by mrocklin** [comment]
Interesting.  I suspect that you have something in your config.  What else
have you done in this Python process?  Have you use dask.config.set or
dask.set_options at all?

**Comment by sdswart** [comment]
I haven't made any changes to config, but after checking the versions again, I see that the scheduler was running on distributed 1.22.0, but my local environment was still using distributed 1.21.0. 

After upgrading the local environment to 1.22.0, the problem has been resolved.

I'll close this issue.
