### ISSUE TITLE
Variable couldn't deserialize when LocalCluster use threads and not processes

### ISSUE THREAD

**Issue by sami72** [dask/distributed#2077]
m trying to gracefully close a task It seems that Variable can't be deserialise when using LocalCluster with threads and not processes This is the code that i use

```
from distributed import Client, LocalCluster
cluster = LocalCluster(processes=False)
client = Client(cluster)

from dask.distributed import Variable
import time 

stop = Variable()
stop.set(False)

def my_task():
    while True:
        if stop.get():
            return

        else:
            print "hello"
            time.sleep(10)
    print "main loop exit"

future = client.submit(my_task)

time.sleep(120)
stop.set(True)
```

This would fail with the following error
```

In [3]: distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/distributed/worker.py", line 1266, in add_task
    self.tasks[key] = _deserialize(function, args, kwargs, task)
  File "/anaconda/lib/python2.7/site-packages/distributed/worker.py", line 642, in _deserialize
    function = pickle.loads(function)
  File "/anaconda/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/anaconda/lib/python2.7/site-packages/distributed/variable.py", line 212, in __setstate__
    client = Client(address, set_as_default=False)
  File "/anaconda/lib/python2.7/site-packages/distributed/client.py", line 578, in __init__
    self.start(timeout=timeout)
  File "/anaconda/lib/python2.7/site-packages/distributed/client.py", line 698, in start
    sync(self.loop, self._start, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/distributed/utils.py", line 253, in sync
    six.reraise(*error[0])
  File "/anaconda/lib/python2.7/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda/lib/python2.7/site-packages/distributed/client.py", line 778, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda/lib/python2.7/site-packages/distributed/client.py", line 815, in _ensure_connected
    connection_args=self.connection_args)
  File "/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda/lib/python2.7/site-packages/distributed/comm/core.py", line 196, in connect
    _raise(error)
  File "/anaconda/lib/python2.7/site-packages/distributed/comm/core.py", line 179, in _raise
    raise IOError(msg)
IOError: Timed out trying to connect to 'inproc://10.196.73.29/81901/1' after 10 s: connect() didn't finish in time
```

this will work if cluster is defined like this

`cluster = LocalCluster(processes=True)`

**Comment by mrocklin** [comment]
This appears to be fixed in latest release.  I don't know why.  Closing.
