### ISSUE TITLE
pandas is now a mandatory dependency for dscheduler

### ISSUE THREAD

**Issue by ogrisel** [dask/distributed#209]
If pandas is not installed I get an infinite loop with the following logs:

```
tornado.httpclient.HTTPError: HTTP 500: Internal Server Error
bokeh.util.tornado - ERROR - Error thrown from periodic callback: HTTPError(500, 'Internal Server Error', HTTPResponse(_body=None,buffer=<_io.BytesIO object at 0x7f17202a1e08>,code=500,effective_url='http://localhost:9786/tasks.json',error=HTTPError(...),headers=<tornado.httputil.HTTPHeaders object at 0x7f17204ffe48>,reason='Internal Server Error',request=<tornado.httpclient.HTTPRequest object at 0x7f1720578da0>,request_time=0.005105733871459961,time_info={}))
distributed.utils - ERROR - No module named 'pandas'
Traceback (most recent call last):
  File "/volatile/ogrisel/code/distributed/distributed/utils.py", line 229, in log_errors
    yield
  File "/volatile/ogrisel/code/distributed/distributed/http/scheduler.py", line 79, in get
    from ..diagnostics.scheduler import tasks
  File "/volatile/ogrisel/code/distributed/distributed/diagnostics/scheduler.py", line 6, in <module>
    import pandas as pd
ImportError: No module named 'pandas'
```

If think this is not intended? The diagnostics callback should probably be disabled when  pandas is not available, no?

**Comment by mrocklin** [comment]
We can definitely resolve this.  Fixing now.
