### ISSUE TITLE
KeyError on release / exception never retrieved

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#2126]
On lastest distributed master, there's some sort of race condition where I'm getting

```
[16:03:33.254 ERROR  ] Future <tornado.concurrent.Future object at 0x7fd1e96ae080> exception was never retrieved: Traceback (most recent call last):
  File "lib/python3.5/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "src/distributed/distributed/worker.py", line 590, in delete_data
    self.release_key(key)
  File "src/distributed/distributed/worker.py", line 2016, in release_key
    self.dependents[dep].remove(key)
KeyError: '<task>'
```

Stemming from

            for dep in self.dependencies.pop(key, ()):
                if dep in self.dependents:
                    self.dependents[dep].remove(key)  # <--- here
                    if not self.dependents[dep] and self.dep_state[dep] in ('waiting', 'flight'):
                        self.release_dep(dep)

Cannot repro it simply yet. But the behavior is that K2 depends on K1;  K2 is being released; but K1 does not have K2 as recorded in its dependents set (instead, it has a K2' which *ought* to be K2, but has a different hash suffix).

**Comment by mrocklin** [comment]
A reproducer would be welcome.  You might also want to look at the story of
the keys

    w.story(key, dep)

**Comment by adamklein** [comment]
I see what's happening via print-debugging but still haven't reproduced simply yet.  Here's the gist:

```
1) submit task A, submit task B that depends on A
2) (re)submit task A, submit task C that depends on A 
 ... at this point, dependents[A] = {B, C} ...
3) task A is released via delete_data -> release_dep -> dependents.pop(A) => dependents[A] = {}
4) (re)submit task A, submit task D that depends on A
... at this point, dependents[A] ={D}
5) release_key(B) -> calls problematic logic
  for dep in self.dependencies[B]:   # gives A
      self.dependents[dep].remove(B)   # cannot remove B, because {B, C} were removed in step 3
```

**Comment by adamklein** [comment]
Ok, I have a repro (finally). Every few iterations this will yield the KeyError:

```
import time

from distributed import LocalCluster, Client, worker_client, get_worker


def inc_func(x):
    return x + 1


def add_func(x, y):
    return x + y


def on_worker():
    with worker_client() as wc:
        pins = []
        addr = get_worker().address

        for k in range(8):
            fut = wc.submit(inc_func, 0, workers=[addr], allow_other_workers=False)
            fut = wc.submit(add_func, fut, k)

            time.sleep(0.01)

            if k % 3 == 0:
                pins.append(fut)

            if k % 7 == 0:
                pins.pop()

        return wc.gather(pins)


if __name__ == '__main__':
    lc = LocalCluster(n_workers=1)
    c = Client(lc)

    for i in range(100):
        f = c.submit(on_worker)
        print(f.result())
        c.restart()

    lc.close()
```

As mentioned, I traced via prints the add/remove/pop on self.dependents in worker.py as follows:

```
line/statement
592   print("{} {} deleting key {}".format(os.getpid(), threading.get_ident(), key))
1330 print("{} {} Setting up new deps set for {}".format(os.getpid(), threading.get_ident(), dep))
1333 print("{} {} Added dep: {} -> {}".format(os.getpid(), threading.get_ident(), key, dep))
2022 print("{} {} releasing {} and removing from dep {} set {}".format(os.getpid(), threading.get_ident(), key, dep, self.dependents[dep]))
2085 print("{} {} popped dep {} -> {}".format(os.getpid(), threading.get_ident(), dep, popped))
```

Here is my log output of one run:

```
26438 140063662425856 Setting up new deps set for inc_func-46b133cc61b67247ac67c52f96efcb1d
26438 140063662425856 Added dep: add_func-8d11bf62c6ed2f937677335fd4ce0cde -> inc_func-46b133cc61b67247ac67c52f96efcb1d
26438 140063662425856 deleting key inc_func-46b133cc61b67247ac67c52f96efcb1d
26438 140063662425856 popped dep inc_func-46b133cc61b67247ac67c52f96efcb1d -> {'add_func-8d11bf62c6ed2f937677335fd4ce0cde'}
26438 140063662425856 deleting key add_func-8d11bf62c6ed2f937677335fd4ce0cde
26438 140063662425856 Setting up new deps set for inc_func-46b133cc61b67247ac67c52f96efcb1d
... NOTE: this next add_func will not be found in inc_func's dependents, because ...
26438 140063662425856 Added dep: add_func-e83adcfc6a82a4ad39cf030c5fc2ccd5 -> inc_func-46b133cc61b67247ac67c52f96efcb1d
  ... these next three lines reset inc_funcs dependents set ...
26438 140063662425856 deleting key inc_func-46b133cc61b67247ac67c52f96efcb1d
26438 140063662425856 popped dep inc_func-46b133cc61b67247ac67c52f96efcb1d -> {'add_func-e83adcfc6a82a4ad39cf030c5fc2ccd5'}
26438 140063662425856 Setting up new deps set for inc_func-46b133cc61b67247ac67c52f96efcb1d
26438 140063662425856 Added dep: add_func-da2108b29bfa47a1c6c4f14c0e69c7dc -> inc_func-46b133cc61b67247ac67c52f96efcb1d
.... so releasing add_func won't find itself in inc_func's set ...
26438 140063662425856 releasing add_func-e83adcfc6a82a4ad39cf030c5fc2ccd5 and removing from dep inc_func-46b133cc61b67247ac67c52f96efcb1d set {'add_func-da2108b29bfa47a1c6c4f14c0e69c7dc'}
[21:35:52.638 ERROR  ] Future <tornado.concurrent.Future object at 0x7f6300c5eeb8> exception was never retrieved: Traceback (most recent call last):
  File "/nas/dft/ire/aklein/envs/a2/lib/python3.5/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/nas/dft/ire/aklein/src/distributed/distributed/worker.py", line 590, in delete_data
    self.release_key(key)
  File "/nas/dft/ire/aklein/src/distributed/distributed/worker.py", line 2023, in release_key
    self.dependents[dep].remove(key)
KeyError: 'add_func-e83adcfc6a82a4ad39cf030c5fc2ccd5'
```

**Comment by adamklein** [comment]
This looks pretty subtle, but I *think* what is needed is this:

            for dep in self.dependencies.pop(key, ()):
                if dep in self.dependents:
                    self.dependents[dep].remove(key)
                    if not self.dependents[dep] and self.dep_state[dep] in ('waiting', 'flight'):
                        self.release_dep(dep)
    
            # --- suggested new code ---
            for _, deps in self.dependencies.items():
                if key in deps:
                    deps.remove(key)

Ie, if we remove a key A, no other key B should have key A in its dependency set? Because If that invariant is not true, then otherwise, the problematic line `self.dependents[A].remove(B)` can arise for some B since `release_dep(A)` -> `self.dependents.pop(A)` -> `self.dependents[A] = {}`

**Comment by adamklein** [comment]
Thanks!!

**Comment by mrocklin** [comment]
Thanks for tracking it down.  Happy to finally have time to resolve this!
