### ISSUE TITLE
Exception: KeyError: 'cpu'

### ISSUE THREAD

**Issue by spirali** [dask/distributed#213]
Hello,

I have tried to use `distributed` and I get the following error:

```
/home/spirali/.local/lib/python2.7/site-packages/dask-0.8.1-py2.7.egg/dask/array/numpy_compat.py:31: RuntimeWarning: divide by zero encountered in divide
  or not np.allclose(np.divide(1, .5, dtype='i8'), 2)
distributed.scheduler - INFO - Start Scheduler at:        158.196.27.72:8786
distributed.scheduler - INFO -            http at:        158.196.27.72:9786
distributed.scheduler - INFO -  Start Bokeh UI at:        http://158.196.27.72:8787/status/
/home/spirali/.local/lib/python2.7/site-packages/dask-0.8.1-py2.7.egg/dask/array/numpy_compat.py:31: RuntimeWarning: divide by zero encountered in divide
  or not np.allclose(np.divide(1, .5, dtype='i8'), 2)
bokeh.command.subcommands.serve - INFO - Check for unused sessions every 50 milliseconds
bokeh.command.subcommands.serve - INFO - Unused sessions last for 1 milliseconds
bokeh.command.subcommands.serve - INFO - Starting Bokeh server on port 8787 with applications at paths ['/status', '/tasks']
distributed.core - INFO - Connection from 127.0.0.1:46764 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:46765 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:46787 to Scheduler
distributed.scheduler - INFO - Register 127.0.0.1:33457
distributed.scheduler - INFO - Starting worker compute stream, 127.0.0.1:33457
distributed.utils - ERROR - 'cpu'
Traceback (most recent call last):
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/utils.py", line 229, in log_errors
    yield
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/diagnostics/bokeh/status/server_lifecycle.py", line 44, in workers
    resource_append(messages['workers']['plot-data'], msg)
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/diagnostics/worker_monitor.py", line 60, in resource_append
    lists[k].append(mean(pluck(k, L)) / 100)
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/diagnostics/worker_monitor.py", line 66, in mean
    seq = list(seq)
KeyError: 'cpu'
bokeh.util.tornado - ERROR - Error thrown from periodic callback: KeyError('cpu',)
distributed.utils - ERROR - 'cpu'
Traceback (most recent call last):
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/utils.py", line 229, in log_errors
    yield
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/diagnostics/bokeh/status/server_lifecycle.py", line 44, in workers
    resource_append(messages['workers']['plot-data'], msg)
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/diagnostics/worker_monitor.py", line 60, in resource_append
    lists[k].append(mean(pluck(k, L)) / 100)
  File "/home/spirali/.local/lib/python2.7/site-packages/distributed-1.9.1-py2.7.egg/distributed/diagnostics/worker_monitor.py", line 66, in mean
    seq = list(seq)
KeyError: 'cpu'
```
(after that, the same error is repeated few times per second)

I have installed the current version from github (python setup.py install --user) and then executed:
```
dscheduler
```
and 
```
dworker localhost:8786
```

My system: Ubuntu 15.04; Python 2.7.9

Thank you,
Stanislav Bohm

**Comment by mrocklin** [comment]
I suspect that this is because you don't have `psutil` installed.  We should probably add it to requirements.txt

**Comment by mrocklin** [comment]
Can you `pip install psutil` and try again?

**Comment by mrocklin** [comment]
I've just added `pustil` to conda/pip requirements

**Comment by spirali** [comment]
Thank you, now it works for me.

**Comment by mrocklin** [comment]
Thanks for the error report!
