### ISSUE TITLE
Avoiding "worker already exists" error

### ISSUE THREAD

**Issue by rsignell-usgs** [dask/distributed#2145]
I ran a workflow I've run before, and today it's giving my "worker already exists" errors part way through the computation.    The reproducible notebook is here: https://gist.github.com/rsignell-usgs/8b3c6ac42cc93589b0248e62b0058f2f

Details of the error are here:
```python-traceback
distributed.utils - ERROR - Worker already exists tcp://192.168.166.134:34563
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 644, in log_errors
    yield
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 1225, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://192.168.166.134:34563
distributed.core - ERROR - Worker already exists tcp://192.168.166.134:34563
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 321, in handle_comm
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 1225, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://192.168.166.134:34563
```
![2018-07-30_9-02-13](https://user-images.githubusercontent.com/1872600/43413780-f80eb13e-93fe-11e8-9366-428d2c17bbcc.png)

Am I doing anything wrong, or is there a way to avoid this error?

version info:
```
jovyan@jupyter-rsignell-2dusgs:~$ conda list distributed
cons# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
distributed               1.22.0                   py36_0    conda-forge
jovyan@jupyter-rsignell-2dusgs:~$ conda list dask
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
dask                      0.18.2                     py_0    conda-forge
dask-core                 0.18.2                     py_0    conda-forge
dask-glm                  0.1.0                         0    conda-forge
dask-kubernetes           0.4.0                      py_0    conda-forge
dask-ml                   0.7.0            py36h470a237_0    conda-forge
dask-tensorflow           0.0.2                      py_0    conda-forge
```

**Comment by mrocklin** [comment]
Can you verify that your distributed versions are the same everywhere?
client.get_versions(check=True)

**Comment by rsignell-usgs** [comment]
@mrocklin, no errors from `client.get_versions(check=True)`.  

<details>
```
client.get_versions(check=True)

{'scheduler': {'host': (('python', '3.6.5.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.4.0-1052-aws'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')),
  'packages': {'required': (('dask', '0.18.2'),
    ('distributed', '1.22.0'),
    ('msgpack', '0.5.6'),
    ('cloudpickle', '0.5.3'),
    ('tornado', '5.0.2'),
    ('toolz', '0.9.0')),
   'optional': (('numpy', '1.14.5'),
    ('pandas', '0.23.3'),
    ('bokeh', '0.12.16'),
    ('lz4', '1.1.0'),
    ('blosc', '1.4.4'))}},
 'workers': {'tcp://192.168.136.217:41702': {'host': (('python',
     '3.6.5.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '4.4.0-1052-aws'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'en_US.UTF-8'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')),
   'packages': {'required': (('dask', '0.18.2'),
     ('distributed', '1.22.0'),
     ('msgpack', '0.5.6'),
     ('cloudpickle', '0.5.3'),
     ('tornado', '5.0.2'),
     ('toolz', '0.9.0')),
    'optional': (('numpy', '1.14.5'),
     ('pandas', '0.23.3'),
     ('bokeh', '0.12.16'),
     ('lz4', '1.1.0'),
     ('blosc', '1.4.4'))}},
  'tcp://192.168.138.228:44715': {'host': (('python', '3.6.5.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '4.4.0-1052-aws'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'en_US.UTF-8'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')),
   'packages': {'required': (('dask', '0.18.2'),
     ('distributed', '1.22.0'),
     ('msgpack', '0.5.6'),
     ('cloudpickle', '0.5.3'),
     ('tornado', '5.0.2'),
     ('toolz', '0.9.0')),
    'optional': (('numpy', '1.14.5'),
     ('pandas', '0.23.3'),
     ('bokeh', '0.12.16'),
     ('lz4', '1.1.0'),
     ('blosc', '1.4.4'))}},
  'tcp://192.168.162.183:40381': {'host': (('python', '3.6.5.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '4.4.0-1052-aws'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'en_US.UTF-8'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')),
   'packages': {'required': (('dask', '0.18.2'),
     ('distributed', '1.22.0'),
     ('msgpack', '0.5.6'),
     ('cloudpickle', '0.5.3'),
     ('tornado', '5.0.2'),
     ('toolz', '0.9.0')),
    'optional': (('numpy', '1.14.5'),
     ('pandas', '0.23.3'),
     ('bokeh', '0.12.16'),
     ('lz4', '1.1.0'),
     ('blosc', '1.4.4'))}},
  'tcp://192.168.166.162:46255': {'host': (('python', '3.6.5.final.0'),
    ('python-bits', 64),
    ('OS', 'Linux'),
    ('OS-release', '4.4.0-1052-aws'),
    ('machine', 'x86_64'),
    ('processor', 'x86_64'),
    ('byteorder', 'little'),
    ('LC_ALL', 'en_US.UTF-8'),
    ('LANG', 'en_US.UTF-8'),
    ('LOCALE', 'en_US.UTF-8')),
   'packages': {'required': (('dask', '0.18.2'),
     ('distributed', '1.22.0'),
     ('msgpack', '0.5.6'),
     ('cloudpickle', '0.5.3'),
     ('tornado', '5.0.2'),
     ('toolz', '0.9.0')),
    'optional': (('numpy', '1.14.5'),
     ('pandas', '0.23.3'),
     ('bokeh', '0.12.16'),
     ('lz4', '1.1.0'),
     ('blosc', '1.4.4'))}}},
 'client': {'host': [('python', '3.6.5.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.4.0-1052-aws'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')],
  'packages': {'required': [('dask', '0.18.2'),
    ('distributed', '1.22.0'),
    ('msgpack', '0.5.6'),
    ('cloudpickle', '0.5.3'),
    ('tornado', '5.0.2'),
    ('toolz', '0.9.0')],
   'optional': [('numpy', '1.14.5'),
    ('pandas', '0.23.3'),
    ('bokeh', '0.12.16'),
    ('lz4', '1.1.0'),
    ('blosc', '1.4.4')]}}}
```
</details>
I'm using the same Docker container for both my jupyterhub notebook and the dask workers:

**Comment by rsignell-usgs** [comment]
I tried again today and the notebook worked: https://nbviewer.jupyter.org/gist/rsignell-usgs/8b3c6ac42cc93589b0248e62b0058f2f
albeit with some errors of this type:

distributed.worker - ERROR - Could not serialize object of type ImplicitToExplicitIndexingAdapter Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 38, in dumps result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL) File "/opt/conda/lib/python3.6/site-packages/xarray/backends/common.py", line 533, in __getstate__ del state['_ds'] KeyError: '_ds' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 196, in serialize header, frames = dumps(x) File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 54, in pickle_dumps return {'serializer': 'pickle'}, [pickle.dumps(x)] File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 51, in dumps return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL) File "/opt/conda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 895, in dumps cp.dump(obj) File "/opt/conda/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 268, in dump return Pickler.dump(self, obj) File "/opt/conda/lib/python3.6/pickle.py", line 409, in dump self.save(obj) File "/opt/conda/lib/python3.6/pickle.py", line 521, in save self.save_reduce(obj=obj, *rv) File "/opt/conda/lib/python3.6/pickle.py", line 634, in save_reduce save(state) File "/opt/conda/lib/python3.6/pickle.py", line 476, in save f(self, obj) # Call unbound method with explicit self File "/opt/conda/lib/python3.6/pickle.py", line 821, in save_dict self._batch_setitems(obj.items()) File "/opt/conda/lib/python3.6/pickle.py", line 847, in _batch_setitems save(v) File "/opt/conda/lib/python3.6/pickle.py", line 521, in save self.save_reduce(obj=obj, *rv) File "/opt/conda/lib/python3.6/pickle.py", line 634, in save_reduce save(state) File "/opt/conda/lib/python3.6/pickle.py", line 476, in save f(self, obj) # Call unbound method with explicit self File "/opt/conda/lib/python3.6/pickle.py", line 821, in save_dict self._batch_setitems(obj.items()) File "/opt/conda/lib/python3.6/pickle.py", line 847, in _batch_setitems save(v) File "/opt/conda/lib/python3.6/pickle.py", line 521, in save self.save_reduce(obj=obj, *rv) File "/opt/conda/lib/python3.6/pickle.py", line 634, in save_reduce save(state) File "/opt/conda/lib/python3.6/pickle.py", line 476, in save f(self, obj) # Call unbound method with explicit self File "/opt/conda/lib/python3.6/pickle.py", line 821, in save_dict self._batch_setitems(obj.items()) File "/opt/conda/lib/python3.6/pickle.py", line 847, in _batch_setitems save(v) File "/opt/conda/lib/python3.6/pickle.py", line 521, in save self.save_reduce(obj=obj, *rv) File "/opt/conda/lib/python3.6/pickle.py", line 634, in save_reduce save(state) File "/opt/conda/lib/python3.6/pickle.py", line 476, in save f(self, obj) # Call unbound method with explicit self File "/opt/conda/lib/python3.6/pickle.py", line 821, in save_dict self._batch_setitems(obj.items()) File "/opt/conda/lib/python3.6/pickle.py", line 847, in _batch_setitems save(v) File "/opt/conda/lib/python3.6/pickle.py", line 496, in save rv = reduce(self.proto) File "/opt/conda/lib/python3.6/site-packages/xarray/backends/common.py", line 533, in __getstate__ del state['_ds'] KeyError: '_ds' Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 1774, in gather_dep who=self.address) File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run yielded = self.gen.throw(*exc_info) File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 610, in send_recv_from_rpc result = yield send_recv(comm=comm, op=key, **kwargs) File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py",

which I'm hoping I don't need to worry about?

**Comment by matanster** [comment]
@mrocklin 

> Can you verify that your distributed versions are the same everywhere?
client.get_versions(check=True)

Shouldn't it be easy for dask to verify that internally when nodes connect? if not at build level granularity then at a release version level?

**Comment by NicWayand** [comment]
Hi @mrocklin, I got this same error but running `client.get_versions(check=True)` shows that cloudpickle is different between client and the workers. This is on polar.pangeo.io. What is the best way to avoid these conflicts?
```
ValueError: Mismatched versions found

cloudpickle
+------------------------+---------+
|                        | version |
+------------------------+---------+
| client                 | 0.6.1   |
| tcp://10.28.23.7:42038 | 0.5.6   |
| tcp://10.28.52.3:37960 | 0.5.6   |
| tcp://10.28.53.3:35364 | 0.5.6   |
| tcp://10.28.54.3:45307 | 0.5.6   |
| tcp://10.28.55.3:41325 | 0.5.6   |
| tcp://10.28.56.3:45631 | 0.5.6   |
| tcp://10.28.57.3:42623 | 0.5.6   |
| tcp://10.28.58.3:44033 | 0.5.6   |
| tcp://10.28.59.3:40006 | 0.5.6   |
| tcp://10.28.63.3:40605 | 0.5.6   |
| tcp://10.28.64.3:34306 | 0.5.6   |
| tcp://10.28.65.3:43675 | 0.5.6   |
| tcp://10.28.66.3:34612 | 0.5.6   |
+------------------------+---------+
```

**Comment by mrocklin** [comment]
In your situaiton I would either downgrade the cloudpickle on your jupyter
notebook image or upgrade the version of cloudpickle on your worker image.

You might also consider using the same image everywhere.  This is generally
handled in your config files.  If you're using dask-kubernetes (as I
suspect that you are) then you probably have a worker-template.yaml file
floating around that specifies the docker image you use for workers.

**Comment by NicWayand** [comment]
Thanks @mrocklin, I don't see a `worker-template.yaml` file in my https://github.com/NicWayand/example.pangeo.io-deploy repo, but maybe it has a different name? Is it defined here https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/worker-template.yaml ?

**Comment by mrocklin** [comment]
Yes, it's
image: pangeo/notebook:ede11f6
