### ISSUE TITLE
Issues running larger version of working computation

### ISSUE THREAD

**Issue by RPrudden** [dask/distributed#2164]
### Description
I am trying to run some analysis of an NWP ensemble dataset on Dask. A relatively small version of the analysis runs without an issue, either locally or on a distributed cluster, although running it locally is quite slow.

When I run a version on about 25x more data, it fails on the distributed cluster. In my notebook, I get warnings about closed streams, a TimeoutError, and a number of errors concerning keys. 

I'm not certain what causes the issue. My best guess is that the computation graph is too large, and the whole graph never reached the scheduler. 

For reference, the cluster I used was an adaptive one with 30-50 workers, with around 16GB of memory per worker.

#### Setup code
```python
def apply_filters(a, scale_min=0, scale_max=7):
    k = 10
    scales = np.logspace(scale_min, scale_max, num=k, base=2, endpoint=True)
    return da.stack([gaussian_filter(a, s) for s in scales])

z = zarr.open('low_type_cloud_area_fraction.zarr')
zarr_dask_array = da.from_array(z, z.chunks)

zarr_dask_array = zarr_dask_array.rechunk((1, 1, 1, 548, 421))
filt = zarr_dask_array.map_blocks(apply_filters, new_axis=[0],
                                  chunks=(10,1,1,1,548,421))
diffs = filt[:-1] - filt[1:]

ens_mean = diffs.mean(axis=1)
ens_var = ((diffs - diffs.mean(axis=1)[:,None])**2).mean(axis=1)
rel_var = ens_var / (da.absolute(diffs).mean(axis=1) + 0.00001)
```

#### Works
```python
n = 37//5
s = np.random.randint(1,60,4)
x = np.logspace(0, 7, num=10, base=2, endpoint=True)[:-1]
res = rel_var[:,s,::5].mean(axis=(1,3,4)).T
res = res.compute()
```

#### Fails
```python
n = 37
s = np.random.randint(1,60,20)
x = np.logspace(0, 7, num=10, base=2, endpoint=True)[:-1]
res = rel_var[:,s,:].mean(axis=(1,3,4)).T
res = res.compute()
```

### Errors

In the Jupyter notebook where I was running the code, the compute cell returned some warnings 
```
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:42126 remote=tcp://100.96.59.79:41685>
```
followed by a TimeoutError and a selection of the following errors:

```
KeyError: "('absolute-mean_chunk-956de8d4ce84846ed408102bf0c3d337', 0, 7, 51, 24, 0, 0)"
distributed.core - ERROR - "('mean_chunk-950ae422642516afb9c5aee168022277', 0, 4, 50, 27, 0, 0)"
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 375, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 2055, in handle_long_running
    ts = self.tasks[key]
```
```
ValueError: Worker already exists tcp://100.96.83.26:40951
distributed.core - ERROR - Worker already exists tcp://100.96.83.26:40951
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 321, in handle_comm
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.6/site-packages/distributed/scheduler.py", line 1225, in add_worker
    raise ValueError("Worker already exists %s" % address)', 0, 1, 19, 23, 0, 0)"
```
```
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('absolute-8caf7df57af7bcba652a9cf0eee07592', 0, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('absolute-3384b39da447b5991c0cbaa2ee25bbf3', 0, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-76e69129c97e5f7e31db960c26c65e53', 3, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-76e69129c97e5f7e31db960c26c65e53', 4, 0, 0, 0, 0, 0)"}
distributed.utils - ERROR - "('sub-47b63a6bd1268f7c814f69f7dcb81249', 2, 0, 0, 0, 0, 0)"

KeyError: "('absolute-mean_chunk-956de8d4ce84846ed408102bf0c3d337', 0, 2, 16, 20, 0, 0)"
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sum-aggregate-f0cef08f48ac43b07ac8e3bce3f1b205', 1, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sum-aggregate-2f7cb9e829e4310ffb57a5a865b42d1e', 0, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sum-aggregate-2f7cb9e829e4310ffb57a5a865b42d1e', 1, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sum-aggregate-f0cef08f48ac43b07ac8e3bce3f1b205', 0, 0, 0, 0, 0, 0)"}
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.95.11:41863'], ('sum-aggregate-a0898c5e8dec7c1926c7ead885779a5c', 8, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sum-aggregate-329535822663a2f14ac3dbad2448433f', 5, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('absolute-14d99b0b592e9cfc3a71324236475d45', 0, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-e6758a84da44535732ef97447f5bdef3', 1, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-943d6c62001e7ee43f8d94da1d83a80d', 0, 0, 0, 0, 0, 0)"}
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.95.11:41863'], ('sum-aggregate-671746769a0acd864d701a10227ed292', 8, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-e1c2bab43c3af16496480b9e9fe96510', 2, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('absolute-ea2e4dd7a5990dfcee29952a60d2957c', 3, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-e1c2bab43c3af16496480b9e9fe96510', 8, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('sub-e1c2bab43c3af16496480b9e9fe96510', 3, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('absolute-ea2e4dd7a5990dfcee29952a60d2957c', 8, 0, 0, 0, 0, 0)"}
distributed.scheduler - CRITICAL - Tried writing to closed comm: {'op': 'lost-data', 'key': "('absolute-ea2e4dd7a5990dfcee29952a60d2957c', 2, 0, 0, 0, 0, 0)"}
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.90.10:40579'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 1, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.95.11:41863'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 0, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.90.10:40579'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 4, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.90.10:40579'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 3, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.90.10:40579'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 5, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.90.10:40579'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 8, 0, 0, 0, 0, 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://100.96.90.10:40579'], ('sub-f991b335f9b5f3298ea6dd4152158bfd', 2, 0, 0, 0, 0, 0)
NoneType: None
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:32974 remote=tcp://100.96.116.13:34267>
distributed.core - ERROR - 'tcp://100.96.84.31:34753'

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:44104 remote=tcp://100.96.95.11:41863>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:42746 remote=tcp://100.96.90.10:40579>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:44106 remote=tcp://100.96.95.11:41863>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:44110 remote=tcp://100.96.95.11:41863>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:55296 remote=tcp://100.96.111.14:43077>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:53692 remote=tcp://100.96.96.12:44193>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://100.96.59.79:36698 remote=tcp://100.96.79.55:43895>
```

There were also errors on the workers:

```+ dask-worker --nthreads 1 --no-bokeh --memory-limit 16G --death-timeout 60
distributed.nanny - INFO -     Start Nanny at: 'tcp://100.96.97.12:35437'
distributed.worker - INFO -    Start worker at:  tcp://100.96.97.12:37365
distributed.worker - INFO -     Listening to:  tcp://100.96.97.12:37365
distributed.worker - INFO -       nanny at:     100.96.97.12:35437
distributed.worker - INFO - Waiting to connect to:  tcp://100.96.59.79:41685
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -        Threads:             1
distributed.worker - INFO -        Memory:          16.00 GB
distributed.worker - INFO -    Local Directory: /home/jovyan/dask-worker-space/worker-5k_xiocr
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -     Registered to:  tcp://100.96.59.79:41685
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.client - WARNING - Couldn't gather 6 keys, rescheduling {"('sub-e6143dcbe994471a236ae3da3ffd732b', 1, 0, 0, 0, 0, 0)": (), "('sub-e6143dcbe994471a236ae3da3ffd732b', 7, 0, 0, 0, 0, 0)": (), "('sub-e6143dcbe994471a236ae3da3ffd732b', 6, 0, 0, 0, 0, 0)": (), "('sub-e6143dcbe994471a236ae3da3ffd732b', 4, 0, 0, 0, 0, 0)": (), "('sub-e6143dcbe994471a236ae3da3ffd732b', 3, 0, 0, 0, 0, 0)": (), "('sub-e6143dcbe994471a236ae3da3ffd732b', 2, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 5 keys, rescheduling {"('sub-95ec78e4c9f3804e377907a404f60d30', 0, 0, 0, 0, 0, 0)": (), "('sub-95ec78e4c9f3804e377907a404f60d30', 8, 0, 0, 0, 0, 0)": (), "('sub-95ec78e4c9f3804e377907a404f60d30', 1, 0, 0, 0, 0, 0)": (), "('sub-95ec78e4c9f3804e377907a404f60d30', 6, 0, 0, 0, 0, 0)": (), "('sub-95ec78e4c9f3804e377907a404f60d30', 7, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('absolute-fdec59cafade1602f2b98fcc112629b4', 1, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('absolute-d141ea809e57ac6e786070eb610f6337', 3, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 2 keys, rescheduling {"('sub-3903b1b2de78971e86ca47612b184e63', 3, 0, 0, 0, 0, 0)": (), "('sub-3903b1b2de78971e86ca47612b184e63', 4, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('absolute-d141ea809e57ac6e786070eb610f6337', 4, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 4 keys, rescheduling {"('sub-cc17bfd6b9cdd8e34cef9e6d67eb896f', 7, 0, 0, 0, 0, 0)": (), "('sub-cc17bfd6b9cdd8e34cef9e6d67eb896f', 4, 0, 0, 0, 0, 0)": (), "('sub-cc17bfd6b9cdd8e34cef9e6d67eb896f', 3, 0, 0, 0, 0, 0)": (), "('sub-cc17bfd6b9cdd8e34cef9e6d67eb896f', 6, 0, 0, 0, 0, 0)": ()}
distributed.utils_perf - INFO - full garbage collection released 70.73 MB from 3089 reference cycles (threshold: 10.00 MB)
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('absolute-e289e83fc0cdf0e5e3fbc1190c2fc74a', 1, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('sub-cc17bfd6b9cdd8e34cef9e6d67eb896f', 8, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 2 keys, rescheduling {"('sub-2d9d827e69c108d9092eba7ea8b686ac', 4, 0, 0, 0, 0, 0)": (), "('sub-2d9d827e69c108d9092eba7ea8b686ac', 7, 0, 0, 0, 0, 0)": ('tcp://100.96.83.27:37591',)}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('sub-1fd33683326429ebee46716d0ed75dbd', 1, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 2 keys, rescheduling {"('sum-aggregate-f01947b0fb08d1eb90e1fe6c4e64ce21', 8, 0, 0, 0, 0, 0)": (), "('sum-aggregate-f01947b0fb08d1eb90e1fe6c4e64ce21', 1, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 2 keys, rescheduling {"('sum-aggregate-8d06be54d9ef3aba62d7166400c3deee', 8, 0, 0, 0, 0, 0)": (), "('sum-aggregate-8d06be54d9ef3aba62d7166400c3deee', 0, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('sub-1fd33683326429ebee46716d0ed75dbd', 5, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('sum-aggregate-7547ee612b9e154c63df6dde3c71564e', 0, 0, 0, 0, 0, 0)": ()}
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {"('sum-aggregate-328ab9323702be80896603dfc7cb194e', 1, 0, 0, 0, 0, 0)": ()}
distributed.worker - INFO - Stopping worker at tcp://100.96.97.12:37365
rpc error: code = Unknown desc = Error: No such container: d5240c834149706aae3a24a3190a9337b6dce7be02309a0ce5ec140f1d8a1b3c%
```

**Comment by mrocklin** [comment]
My first guess is that your workers are dying for some reason.  I would
check worker logs or the logs of your cluster manager to see if that's the
case.

Also, for NWP questions you might find that the XArray mailing list or the
Pangeo issue tracker has more people that are able and willing to help.

**Comment by mrocklin** [comment]
This seems to have gone stale.  I imagine that you've moved on @RPrudden .  OK to close?

Also, for the future I suspect that you'll have better luck getting high quality responses if you're able to reduce your problem to a minimal reproducible example.  This makes it much more likely that maintainers will try your code to see what occurred.  (no expectation though, just a suggestion)

**Comment by RPrudden** [comment]
Yes, I'm not sure of the exact cause but I'm pretty sure it was a memory issue.
