### ISSUE TITLE
KeyError in Scheduler.update_graph

### ISSUE THREAD

**Issue by sdrave** [dask/distributed#2187]
Hi, there seems to be an issue with the cleanup logic added to `Scheduler.update_graph` in #1840.

For instance, when I execute

```python
import time

def foo():
    return 'foo'

def bar(x):
    return x + 'bar'

def baz(x):
    time.sleep(100)
    return x + 'baz'

if __name__ == '__main__':
    from distributed import Client, LocalCluster
    cluster = LocalCluster()
    c = Client(cluster)
    x = c.submit(foo)
    y = c.submit(bar, x)
    y.result()
    z = c.submit(baz, y)
    del y
    time.sleep(1)
    f = c.submit(bar, x)
```

I get with distributed 1.22.1 the following error:

```
Traceback (most recent call last):
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/distributed/core.py", line 320, in handle_comm
    result = yield result
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/distributed/scheduler.py", line 1924, in add_client
    yield self.handle_stream(comm=comm, extra={'client': client})
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/distributed/core.py", line 374, in handle_stream
    handler(**merge(extra, msg))
  File "/home/stephan/.virtualenvs/pymor/lib/python3.5/site-packages/distributed/scheduler.py", line 1357, in update_graph
    for dep in dependencies[key]:
KeyError: 'foo-b55e006af80e0cfdc1a300901102086d'
```

The problem seems to be that the code assumes that each dependency is again a key in the `dependencies` dict, which is not the case in this example.

**Comment by mrocklin** [comment]
Thank you for the excellent reproducible minimal example @sdrave .  This is great.

Is this something that you'd like to take a shot at resolving?  If not I can probably look at it in a day or two.

**Comment by mrocklin** [comment]
I believe that I have resolved this in https://github.com/dask/distributed/pull/2196
