### ISSUE TITLE
Traceback in Distributed logs from Graph Dashboard plugin

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#2193]
Saw this traceback popup in the Distributed logs while looking at the Graph Dashboard. This was early in a very busy computation. So not much had completed yet.

```python
distributed.utils - ERROR - '<' not supported between instances of 'NoneType' and 'tuple'
Traceback (most recent call last):
  File "/opt/conda3/lib/python3.6/site-packages/distributed/utils.py", line 644, in log_errors
    yield
  File "/opt/conda3/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 1107, in graph_doc
    graph = GraphPlot(scheduler, sizing_mode='stretch_both')
  File "/opt/conda3/lib/python3.6/site-packages/distributed/bokeh/scheduler.py", line 612, in __init__
    self.layout = GraphLayout(scheduler)
  File "/opt/conda3/lib/python3.6/site-packages/distributed/diagnostics/graph_layout.py", line 38, in __init__
    priority=priority)
  File "/opt/conda3/lib/python3.6/site-packages/distributed/diagnostics/graph_layout.py", line 42, in update_graph
    stack = sorted(dependencies, key=priority.get, reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**Comment by jrbourbeau** [comment]
Reopening as @ncclementi reported seeing this with the latest `distributed` release (2021.09.1). There's also this PR https://github.com/dask/distributed/pull/2337 which was an attempt to fix this issue

**Comment by ncclementi** [comment]
I'll leave here a minimal reproducible example. The code comes form the dask-tutorial for reference. I run into this when using joblib with dask as a backend. 

```python
import dask.distributed
client = dask.distributed.Client(n_workers=4)

from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import joblib

X, y = make_classification(n_samples=10000, n_features=4, random_state=0)

estimator = SVC(gamma='auto', random_state=0, probability=True)
param_grid = {
    'C': [0.001, 10.0],
    'kernel': ['rbf', 'poly'],
}

grid_search = GridSearchCV(estimator, param_grid, verbose=2, cv=2, n_jobs=-1)

with joblib.parallel_backend("dask", scatter=[X, y]):
    grid_search.fit(X, y)
```

When clicking on the Graph tab on the dashboard, I get the following traceback
```
distributed.utils - ERROR - '<' not supported between instances of 'NoneType' and 'tuple'
Traceback (most recent call last):
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/utils.py", line 638, in log_errors
    yield
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py", line 3117, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py", line 1947, in __init__
    self.layout = GraphLayout(scheduler)
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/diagnostics/graph_layout.py", line 38, in __init__
    self.update_graph(
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/diagnostics/graph_layout.py", line 48, in update_graph
    stack = sorted(tasks, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
tornado.application - ERROR - Uncaught exception GET /graph (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/graph', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/bokeh/server/views/session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/bokeh/server/contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/bokeh/application/application.py", line 195, in initialize_document
    h.modify_document(doc)
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py", line 3117, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py", line 1947, in __init__
    self.layout = GraphLayout(scheduler)
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/diagnostics/graph_layout.py", line 38, in __init__
    self.update_graph(
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/diagnostics/graph_layout.py", line 48, in update_graph
    stack = sorted(tasks, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
Exception ignored in: <function TaskGraph.__del__ at 0x12752fe50>
Traceback (most recent call last):
  File "/Users/ncclementi/mambaforge/envs/dask-mini-tutorial-v1/lib/python3.9/site-packages/distributed/dashboard/components/scheduler.py", line 2118, in __del__
    self.scheduler.remove_plugin(self.layout)
AttributeError: 'TaskGraph' object has no attribute 'layout'
```
