### ISSUE TITLE
Dask Scheduler does not start Web UI

### ISSUE THREAD

**Issue by dcieslak19973** [dask/distributed#2215]
$ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://10.13.81.78:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-m2AlCn
distributed.scheduler - INFO - --------------------------------------------
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'write_bytes'
Traceback (most recent call last):
  File "/home/cieslakd/python/lib/python/distributed-1.22.1+18.g58de8b6-py2.7.egg/distributed/core.py", line 340, in handle_comm
    result = yield result
  File "/home/cieslakd/python/lib/python/tornado-5.1-py2.7-linux-x86_64.egg/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/cieslakd/python/lib/python/tornado-5.1-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/cieslakd/python/lib/python/tornado-5.1-py2.7-linux-x86_64.egg/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)

---------------------------
$ dask-scheduler --port 8786 --bokeh-port 8787
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://10.13.81.78:8786
distributed.scheduler - INFO - Local Directory:      /tmp/scheduler-wGKjiq
distributed.scheduler - INFO - -----------------------------------------------
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'write_bytes'
Traceback (most recent call last):
  File "/home/cieslakd/python/lib/python/distributed-1.22.1+18.g58de8b6-py2.7.egg/distributed/core.py", line 340, in handle_comm
    result = yield result
  File "/home/cieslakd/python/lib/python/tornado-5.1-py2.7-linux-x86_64.egg/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/cieslakd/python/lib/python/tornado-5.1-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/cieslakd/python/lib/python/tornado-5.1-py2.7-linux-x86_64.egg/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'write_bytes'

**Comment by mrocklin** [comment]
In the latest release we added a warning if the dashboard doesn't start properly.  Closing.

**Comment by jtromans** [comment]
I'm on the latest version of Dask and the web dashboard is still failing silently if there is an issue with a dependency for the Bokeh dashboard. In my case I had to update Pillow (PIL).

**Comment by mrocklin** [comment]
I think that this may have recently been fixed by
https://github.com/dask/distributed/pull/2444 ?

**Comment by cottrell** [comment]
FYI, there seems to be no warning again: dask-scheduler, version 2.5.1

**Comment by quasiben** [comment]
The warning is in a debug message:
https://github.com/dask/distributed/blob/00ac6f0dbae52aa085834b2e4f3a513e02463008/distributed/scheduler.py#L905

If you change the config to `debug` the message would appear:

```
distributed:
  logging:
    distributed: debug
```
