### ISSUE TITLE
Queue.get() hangs in certain situations

### ISSUE THREAD

**Issue by cicdw** [dask/distributed#2247]
It seems that when submitting large numbers of tasks through a `worker_client`,  `queue.get()` becomes unresponsive to `timeout`:

```python
from distributed import Client, worker_client
import random
import time


def work(arg, q):
    while True:
        try:
            print(f'pulling ticket from {q.client}')
            ticket = q.get(timeout=1) # I expect a TimeoutError here
            break
        except Exception:
            print(f'couldnt get from {q.client}')
            
    # do some work
    time.sleep(1 + random.random())
    # return ticket
    print(f'returning ticket to {q.client}')
    q.put(ticket)
    return arg


def ll():
    return list(range(200))


def submit(fn, args, **kwargs):
    with worker_client() as client:
        futures = []
        for arg in args:
            futures.append(client.submit(fn, arg, **kwargs, pure=False))
    return futures


with Client() as client:
    q = Queue(maxsize=3, client=client)
    q.put(0); q.put(1); q.put(2)
    args = client.submit(ll)
    res = client.submit(submit, work, args, q=q, pure=False)
    final = client.gather(res)
    print(client.gather(final))
```
This produces the following output and an indefinite hang:
```python
pulling ticket from <Client: scheduler='tcp://127.0.0.1:49265'>
pulling ticket from <Client: scheduler='tcp://127.0.0.1:49265'>
pulling ticket from <Client: scheduler='tcp://127.0.0.1:49265'>
pulling ticket from <Client: scheduler='tcp://127.0.0.1:49265' processes=4 cores=4>
```

Notice the different `repr` for the clients; this leads me to believe that [the scheduler address gets lost](https://github.com/dask/distributed/blob/master/distributed/client.py#L649-L663) in communication somewhere (although this might be a red herring).

Whenever I terminate this process, some errors do bubble up:
```python-traceback
Unhandled exception in thread started by 
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/ipykernel/iostream.py", line 97, in _event_pipe
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:
...
  File "zmq/backend/cython/socket.pyx", line 328, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
```

This is related to the number of tasks being submitted combined with the use of queues:
- the above code runs smoothly whenever I decrease the output of `ll()` to `range(100)`
- the above code runs smoothly if I do a `if q` check and don't actually pass a `Queue`

This is working off of master, `distributed.__version__ == '1.23.1+5.g2fdb48fa'`

**Comment by cicdw** [comment]
Ok, sorry for the noise, but I believe the seeming "hang" here is just because the output is being swallowed somewhere down the line by a subprocess; I think the actual issue is related to pickling / unpickling `Queues` and the above example setup a race condition of some kind; here's a smaller, easier-to-digest example which will just run forever:

```python
from distributed import Client, Queue
import pickle
import time

def putter(obj, things):
    time.sleep(2)
    q = pickle.loads(pickle.dumps(obj))
    for t in things:
        q.put(t)

def pick_unpick(obj):
    q = pickle.loads(pickle.dumps(obj))
    while True:
        try:
            ans = q.get(timeout=1)
        except Exception:
            time.sleep(0.5)
    q.put(ans)
    return ans

with Client() as client:
    q = Queue(maxsize=3, client=client)
    loop = client.submit(pick_unpick, q)
    puts = client.submit(putter, q, [1, 2, 3])
    print(loop.result())
```
The pickle / unpickle step here is just meant to replicate what would happen if a queue is sent as an argument to a function which is run in a subprocess.

**Comment by cicdw** [comment]
For posterity: changing `ulimit -n 7168` in my terminal session made everything run smoothly --> everything I thought I was seeing was a symptom of my system being clogged and the errors weren't bubbling up.

**Comment by mrocklin** [comment]
It's surprising to see that you're using thousands of file descriptors.  Do
you have thousands of workers?  If not then we might want to investigate
what's happening here.
