### ISSUE TITLE
Freezes when running in another process

### ISSUE THREAD

**Issue by SuJiaKuan** [dask/distributed#2249]
When I start a local cluster, scatter variables and submit a task through client, it works fine. But if I allocate other process to scatter through client, the process freezes at this function call and never returns. How to solve the problem? Is it a bug?

Python version: `3.6.5`
Dask version: `0.18.0`

Here is my code:
```python
from multiprocessing import Process

from dask.distributed import LocalCluster
from dask.distributed import Client
from dask.distributed import get_client


def add(a, b):
    return a + b


def another_process():
    client = get_client()
    a = client.scatter(3) # Freeze here.
    b = client.scatter(4)
    result = client.submit(add, a, b)
    print(result.result())


def main():
    cluster = LocalCluster(n_workers=1)

    with Client(cluster) as client:
        a = client.scatter(3)
        b = client.scatter(4)
        result = client.submit(add, a, b)
        print(result.result()) # Works fine, outputs 7.

        process = Process(target=another_process)
        process.daemon = True
        process.start()
        process.join()

if __name__ == '__main__':
    main()
```

**Comment by SuJiaKuan** [comment]
I have also tried using the cluster address to create the client by `get_client()` function and `Client` class, both of them don't work.

1. Function `get_client()` , it causes the same freezing problem.

```python
from multiprocessing import Process

from dask.distributed import LocalCluster
from dask.distributed import Client
from dask.distributed import get_client


def add(a, b):
    return a + b


def another_process(address):
    client = get_client(address=address)
    a = client.scatter(3) # Freeze here.
    b = client.scatter(4)
    result = client.submit(add, a, b)


def main():
    cluster = LocalCluster(n_workers=1)

    with Client(cluster) as client:
        a = client.scatter(3)
        b = client.scatter(4)
        result = client.submit(add, a, b)
        print(result.result()) # Works fine, outputs 7.

        process = Process(target=another_process,
                          args=(cluster.scheduler.address,))
        process.daemon = True
        process.start()
        process.join()


if __name__ == '__main__':
    main()
```

2. Class `Client`, it causes timeout error when creating the client

```python
from multiprocessing import Process

from dask.distributed import LocalCluster
from dask.distributed import Client


def add(a, b):
    return a + b


def another_process(address):
    client = Client(address=address) # Timeout error here.
    a = client.scatter(3)
    b = client.scatter(4)
    result = client.submit(add, a, b)


def main():
    cluster = LocalCluster(n_workers=1)

    with Client(cluster) as client:
        a = client.scatter(3)
        b = client.scatter(4)
        result = client.submit(add, a, b)
        print(result.result()) # Works fine, outputs 7.

        process = Process(target=another_process,
                          args=(cluster.scheduler.address,))
        process.daemon = True
        process.start()
        process.join()


if __name__ == '__main__':
    main()
```

Timeout error message:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "issue.py", line 12, in another_process
    client = Client(address=address)
  File "/home/feabries/.local/lib/python3.6/site-packages/distributed/client.py", line 608, in __init__
    self.start(timeout=timeout)
  File "/home/feabries/.local/lib/python3.6/site-packages/distributed/client.py", line 731, in start
    sync(self.loop, self._start, **kwargs)
  File "/home/feabries/.local/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/home/feabries/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/feabries/.local/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/home/feabries/.local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/feabries/.local/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/feabries/.local/lib/python3.6/site-packages/distributed/client.py", line 819, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/home/feabries/.local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/feabries/.local/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/feabries/.local/lib/python3.6/site-packages/distributed/client.py", line 860, in _ensure_connected
    self._update_scheduler_info())
  File "/home/feabries/.local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.util.TimeoutError: Timeout
```

**Comment by SuJiaKuan** [comment]
I have tried forkserver multiprocessing context within daks.distibuted and multiprocessing context with `spawn`. They both worked! Thanks a lot!
> I tried using the forkserver multiprocessing context within dask.distributed and things worked fine:
> 
> ```python
> from dask.distributed import LocalCluster
> from dask.distributed import Client
> from distributed.utils import mp_context
> 
> 
> def add(a, b):
>     return a + b
> 
> 
> def another_process(address):
>     client = Client(address=address) # Timeout error here.
>     a = client.scatter(3)
>     b = client.scatter(4)
>     result = client.submit(add, a, b)
> 
> 
> def main():
>     cluster = LocalCluster(n_workers=1)
> 
>     with Client(cluster) as client:
>         a = client.scatter(3)
>         b = client.scatter(4)
>         result = client.submit(add, a, b)
>         print(result.result()) # Works fine, outputs 7.
> 
>         process = mp_context.Process(target=another_process,
>                           args=(cluster.scheduler.address,))
>         process.daemon = True
>         process.start()
>         process.join()
> 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> This makes me think that the problem is probably in forking the process with the current client still active. If you have any suggestions on how to resolve this that effort would be welcome. Otherwise I recommend using a multiprocessing mechanism other than fork. The simplest solution here is probably to set the multiprocessing context to 'spawn'
> 
> ```python
> context = multiprocessing.get_context('spawn')
> context.Process(...)
> ```
