### ISSUE TITLE
tornado.util.TimeoutError: Worker failed to start

### ISSUE THREAD

**Issue by jamesstidard** [dask/distributed#2279]
I'm trying to use a dask distributed client in a [sanic](https://github.com/huge-success/sanic) web server but am receiving a `tornado.util.TimeourError`.

Sanic uses the UVEventLoop, though can also use the `asyncio` loop when you pass `SANIC_NO_UVLOOP=true` [on install](https://github.com/huge-success/sanic#installation) (or you could just `pip uninstall uvloop` post install). Trying to create a async client with either loop fails for me with this same error.

Here's my source:

```python
from distributed.asyncio import AioClient
from sanic import Sanic
from sanic.response import text


app = Sanic(__name__)

@app.listener('before_server_start')
async def before_server_start(p_app, loop):
    # sanic creates a worker app per process.
    # attach a dask client per process
    p_app.dask_client = await AioClient()

@app.listener('after_server_stop')
async def after_server_stop(p_app, loop):
    await p_app.dask_client.close()

@app.route('/')
async def root(request):
    a, b = 1, 1
    result = await request.app.dask_client.submit(a.__add__, b)
    return text(result)

app.run(worker=1, port=8000, host='0.0.0.0')
```

and the exception I get is:
```sh
[2018-10-01 15:56:37 +0100] [8772] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-10-01 15:56:37 +0100] [8785] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-10-01 15:56:37 +0100] [8791] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-10-01 15:56:37 +0100] [8787] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-10-01 15:56:37 +0100] [8789] [INFO] Goin' Fast @ http://127.0.0.1:8000
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 883, in callback
    result_list.append(f.result())
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/path/to/venv/lib/python3.7/site-packages/distributed/deploy/local.py", line 208, in _start_worker
    yield w._start()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/path/to/venv/lib/python3.7/site-packages/distributed/nanny.py", line 157, in _start
    response = yield self.instantiate()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/path/to/venv/lib/python3.7/site-packages/distributed/nanny.py", line 226, in instantiate
    self.process.start()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/path/to/venv/lib/python3.7/site-packages/distributed/nanny.py", line 370, in start
    yield self.process.start()
  File "/path/to/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/path/to/venv/lib/python3.7/site-packages/distributed/process.py", line 35, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/path/to/venv/lib/python3.7/site-packages/distributed/process.py", line 184, in _start
    process.start()
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "~/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
tornado.application - ERROR - Multiple exceptions in yield list
...
<repeats>
```

I'm running the following setup:
Ubuntu 18.04.1
dask 0.19.2
distributed 1.23.2
tornado 5.1.1
sanic 0.8.3

**Comment by mrocklin** [comment]
Python doesn't like it when you start processes during import.  If you want to use multiple processes then your Client() call will have to be within an `if __name__ == '__main__':` block.  Alternatively you could try things without processes using `Client(processes=False)`

**Comment by jamesstidard** [comment]
@mrocklin Ah, that works! You are a God. Thanks for the quick response. 

I'm actually getting a different problem with my main application, but stumbled on this trying to reproduce in a minimal app - so I may be posting another problem shortly where I'm getting a `AttributeError: module 'resource' has no attribute 'getrlimit'` and a `AttributeError: 'LocalCluster' object has no attribute 'scheduler'`.

Thanks again
