### ISSUE TITLE
Worker failed to start

### ISSUE THREAD

**Issue by PhenoloBoy** [dask/distributed#2285]
I'm testing the dask distributed over a linux machine. If I create the scheduler and the worker using the command line everything seems run properly; if I try to create the client through the API I get is the error:

```
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
      File "/home/maraspi/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
      yielded = self.gen.send(value)
      File "/home/maraspi/anaconda3/lib/python3.6/site-packages/distributed/deploy/local.py", line 217, in _start_worker
      raise gen.TimeoutError("Worker failed to start")
      tornado.gen.TimeoutError: Worker failed to start
```
I've tried to downgrade Tornado to 4.5.3 but I get the same problem.
Has any one get the same problem?

**Comment by mrocklin** [comment]
I recommend providing a minimal reproducible example

**Comment by PhenoloBoy** [comment]
I omitted as it's just like this:
```
def main():
    client = Client()

if __name__ == '__main__':
    main()
```
I've omitted the entire error log baut seems pretty the same for each worker. If someone needs it I can post.

**Comment by mrocklin** [comment]
Unfortunately I'm unable to reproduce the problem.  You might consider providing a minimal conda or pip environment file that recreates the error

**Comment by PhenoloBoy** [comment]
Here the conda environment file :
```
name: dask_time
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=0.13.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - click=7.0=py36_0
  - cloudpickle=0.5.6=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=0.19.2=py36_0
  - dask-core=0.19.2=py36_0
  - distributed=1.23.2=py36_0
  - heapdict=1.0.0=py36_2
  - intel-openmp=2019.0=118
  - jinja2=2.10=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - locket=0.2.0=py36_1
  - markupsafe=1.0=py36h14c3975_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - msgpack-python=0.5.6=py36h6bb024c_1
  - ncurses=6.1=hf484d3e_0
  - numpy=1.15.2=py36h1d66e8a_1
  - numpy-base=1.15.2=py36h81de0dd_1
  - openssl=1.0.2p=h14c3975_0
  - packaging=18.0=py36_0
  - pandas=0.23.4=py36h04863e7_0
  - partd=0.3.8=py36_0
  - pip=10.0.1=py36_0
  - psutil=5.4.7=py36h14c3975_0
  - pyparsing=2.2.1=py36_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.4.3=py36_0
  - six=1.11.0=py36_1
  - sortedcontainers=2.0.5=py36_0
  - sqlite=3.25.2=h7b6447c_0
  - tblib=1.3.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h7b6447c_0
  - wheel=0.32.0=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zict=0.1.3=py36_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - msgpack==0.5.6
prefix: /home/maraspi/anaconda3/envs/dask_time
```

**Comment by mrocklin** [comment]
Still unable to reproduce.  

```python
mrocklin@carbon:~/workspace/dask-examples$ source activate dask_time
mrocklin@carbon:~/workspace/dask-examples$ python 
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'/home/mrocklin/Software/anaconda/envs/dask_time/bin/python'
>>> from dask.distributed import Client
>>> client = Client()
>>> client.submit(lambda x: x + 1, 10).result()
11
```

**Comment by mrocklin** [comment]
Any further information here @PhenoloBoy ?

**Comment by PhenoloBoy** [comment]
Still not official but seems that's a problem comes by the lacknes of root rights; seems that workers can be created without any problem while master/server can't be. I would like, if not a problem, to keep the issue open until I don't get the confirmation from our internal IT staff.

**Comment by PhenoloBoy** [comment]
Solved, the client was pointing to the project directory that's under the profile mounted under a network directory, this is so slow that timeout the creation of scheduler.
