### ISSUE TITLE
dask-mpi does not execute simple example

### ISSUE THREAD

**Issue by iparask** [dask/distributed#2287]
I am starting `Dask` using `dask-mpi` on SDSC Comet. Specifically, I use the command:

```
ibrun -np 24 dask-mpi --nthreads 1 --intreface ib0
```
The scheduler and the workers seem to start based on the output:
```
[iparask@comet-14-02 dask]$ ibrun -np 24 dask-mpi --nthreads 1 --interface ib0
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:32956'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:33193'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:43796'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:45798'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:42914'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:36739'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:34604'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:34531'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:40649'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:42919'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:39533'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:39461'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:38987'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:43902'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:34655'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:38086'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:43257'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:43518'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:34403'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:35574'
distributed.scheduler - INFO - Clear task state
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:40778'
distributed.scheduler - INFO -   Scheduler at:  tcp://10.22.252.157:8786
distributed.scheduler - INFO -       bokeh at:        10.22.252.157:8787
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:44007'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.22.252.157:42158'
```
I then execute the following in another terminal:
```
[iparask@comet-14-02 dask]$ ipython
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.
Caching the list of root modules, please wait!
(This will only be done once - type '%rehashx' to reset cache!)

In [1]: from distributed import Client
In [2]: import dask
In [3]: daskClient = Client('10.22.252.157:8786')
In [4]: def inc(x):
   ...:     return x+1
   ...:
   ...:
In [5]: x = dask.delayed(inc,pure=True)(10)
In [6]: y = dask.compute(x,get=daskClient.get)
```
I see that the client connects:
```
distributed.scheduler - INFO - Receive client connection: Client-d94ae34a-c806-11e8-8491-fb4fc5d6201a
distributed.core - INFO - Starting established connection
```
but y is never computed. I would like to avoid using `dask-jobqueue` because that submits a number of single node jobs, while I want to submit a single job and get all the nodes at once.

**Comment by mrocklin** [comment]
+1 on @guillaumeeb 's comment.  I recommend turning off nanny's with the `--no-nanny` flag

**Comment by iparask** [comment]
Thank you both! I realized that my mpi4py installation installed mpich also that messed with the MPI installation Comet offers.

Although, I corrected that I still get the following errors from worker processes:
```
distributed.worker - INFO - -------------------------------------------------
Traceback (most recent call last):
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/bin/dask-mpi", line 11, in <module>
    sys.exit(go())
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/cli/dask_mpi.py", line 101, in go
    main()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/cli/dask_mpi.py", line 87, in main
    loop.run_sync(run)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 576, in run_sync
    return future_cell[0].result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/cli/dask_mpi.py", line 82, in run
    yield worker._start(addr)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 466, in _start
    yield self._register_with_scheduler()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/worker.py", line 308, in _register_with_scheduler
    connection_args=self.connection_args)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/comm/core.py", line 186, in connect
    quiet_exceptions=EnvironmentError)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/distributed/comm/tcp.py", line 330, in connect
    **kwargs)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/tcpclient.py", line 226, in connect
    addrinfo = yield self.resolver.resolve(host, port, af)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/netutil.py", line 378, in resolve
    None, _resolve_addr, host, port, family)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 166, in run_in_executor
    return self.asyncio_loop.run_in_executor(executor, func, *args)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/asyncio/base_events.py", line 639, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/oasis/projects/nsf/unc100/iparask/Anaconda/anaconda3/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
Any idea what might be the issue?

**Comment by guillaumeeb** [comment]
Looks like a system limitation again. You should contact your HPC cluster admin and ask if there is some limitation enforced on the nodes or queue you are using for job submission.

**Comment by iparask** [comment]
Okay, thank you. I am closing for the moment and I will reopen if necessary
