### ISSUE TITLE
Dask.destributed Client() specific - Could not serialize object of type DataFrame

### ISSUE THREAD

**Issue by WolVesz** [dask/distributed#2317]
Hello All, 

I am consistently getting the following error when I include:

```
cluster = LocalCluster()
client = Client(cluster) 
```
If I run the same code without using the Client() at all (aka none of the above code), the task runs fine. However, I would prefer to use the above scheduler, as it seems that not including the above code results in a large amount of leaked memory which, over times causes the memory usage to be enormous, which based on the script, it should not be. From looking around a ton of other issues, it looks like this memory leak is a well known issue with the default scheduler, but is commonly resolved with the Client() scheduler. Any Ideas on how to resolve the below error? 

Note, I did update all the packages (Dask and its dependents) using pip earlier today and I am still getting the error.  Also note that Client(processes = False) works without issue, however I would very much prefer (processes = True) for the performance gain.   

```
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/core.py", line 53, in dumps
    for key, value in data.items()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/core.py", line 54, in <dictcomp>
    if type(value) is Serialize}
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 157, in serialize
    raise TypeError(msg)
TypeError: Could not serialize object of type DataFrame
distributed.comm.utils - ERROR - Could not serialize object of type DataFrame
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/comm/utils.py", line 40, in _to_frames
    context=context))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/core.py", line 53, in dumps
    for key, value in data.items()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/core.py", line 54, in <dictcomp>
    if type(value) is Serialize}
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 157, in serialize
    raise TypeError(msg)
TypeError: Could not serialize object of type DataFrame
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/batched.py", line 94, in _background_send
    on_error='raise')
  File "/home/sholt/.local/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/sholt/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/sholt/.local/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/comm/tcp.py", line 221, in write
    'recipient': self._peer_addr})
  File "/home/sholt/.local/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/sholt/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/sholt/.local/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/comm/utils.py", line 49, in to_frames
    res = _to_frames()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/comm/utils.py", line 40, in _to_frames
    context=context))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/core.py", line 53, in dumps
    for key, value in data.items()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/core.py", line 54, in <dictcomp>
    if type(value) is Serialize}
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/distributed/protocol/serialize.py", line 157, in serialize
    raise TypeError(msg)
TypeError: Could not serialize object of type DataFrame

```

**Comment by ederome** [comment]
Hello,
    We've been testing recently with Dask two dataframes with about 10 million rows in each of them, containing approximately 20 columns each, first by reading them from MS SQL Server, and then calling the MERGE method on them, with joins. 
To use dask, we actually use MODIN, which itself calls DASK under the hood as you know. We could not use the multi processes to True (default) because it hangs. But we managed to use the multi thread approach, like below. But unfortunately that second approach gives then a "Could not serialize object of type DataFrame" error, from the same python script mentionned by WolVesz (serialize.py) in oct. 2018 !  Here's how we do the import below, and wondering if this issue is still on-going, any resolution ? 

from distributed import Client
client = Client(processes=False)
from distributed import LocalCluster 
client = LocalCluster(processes=False)
import modin.pandas as pd

See error stack in file attached. 

![ErrorSerializeDataframe](https://user-images.githubusercontent.com/265837/95334520-3b5f4b80-087c-11eb-95dd-fdbf6c7cdc89.jpg)

**Comment by quasiben** [comment]
I am not that familiar with Modin.  But in general we don't see this issue. In fact, I would recommend closing this as there wasn't much follow up from the original author.  @mrocklin's earlier suggestion still stands:

> Maybe it contains something not serializable, like a lock?  

You could also verify objects are serializable with `serialize`:

```python
In [1]: from distributed.protocol import serialize

In [2]: serialize([1, 2, 3])
Out[2]:
({'serializer': 'pickle'},
 [b'\x80\x05\x95\x0b\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01K\x02K\x03e.'])

In [3]: import threading

In [4]: lock = threading.Lock()

In [5]: serialize(lock)
Out[5]:
({'serializer': 'error'},
 [b'Could not serialize object of type lock.',
  b'Traceback (most recent call last):\n  File "/Users/bzaitlen/miniconda3/envs/dask-dev/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 49, in dumps\n    result = pickle.dumps(x, **dump_kwargs)\nTypeError: can\'t pickle _thread.lock objects\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/bzaitlen/miniconda3/envs/dask-dev/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 258, in serialize\n    header, frames = dumps(x, context=context) if wants_context else dumps(x)\n  File "/Users/bzaitlen/miniconda3/envs/dask-dev/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 64, in pickle_dumps\n    protocol=context.get("pickle-protocol", None) if context else None,\n  File "/Users/bzaitlen/miniconda3/envs/dask-dev/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 60, in dumps\n    result = cloudpickle.dumps(x, **dump_kwargs)\n  File "/Users/bzaitlen/miniconda3/envs/dask-dev/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 72, in dumps\n    cp.dump(obj)\n  File "/Users/bzaitlen/miniconda3/envs/dask-dev/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 540, in dump\n    return Pickler.dump(self, obj)\nTypeError: can\'t pickle _thread.lock objects\n'])

distributed.protocol.pickle - INFO - Failed to serialize <unlocked _thread.lock object at 0x7fe60886a180>. Exception: can't pickle _thread.lock objects
``` 
I'd suggest building a minimal reproducer and filing a new issue and I'd be happy to take a look.

@mrocklin thoughts on closing this ?

**Comment by mrocklin** [comment]
Yeah, to reiterate my comment from before, Dask can only move things around that are serializable.  All of pandas, cudf, and dask dataframes are serializable.  I'm not sure what is happening in this particular case.  The next step here is for someone to provide a minimal reproducible example (see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) 

I'm happy to close, but also happy to wait a bit to see if @ederome can produce something.  Alternatively @ederome you might want to check in with the Modin folks and verify that what you're trying to do is possible.
