### ISSUE TITLE
Unable to import distributed 1.24.1 with tornado < 5 on python 3.6

### ISSUE THREAD

**Issue by rwedge** [dask/distributed#2351]
It looks like some code depends on tornado 5.0

Steps to recreate:
1. Install packages
```bash
pip install distributed==1.24.1 tornado==4.5.3
```
2. Import distributed
```python
import distributed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/__init__.py", line 5, in <module>
    from .actor import Actor, ActorFuture
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/actor.py", line 4, in <module>
    from .client import Future, default_client
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/client.py", line 44, in <module>
    from .batched import BatchedSend
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/batched.py", line 10, in <module>
    from .core import CommClosedError
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/core.py", line 20, in <module>
    from .comm import (connect, listen, CommClosedError,
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/comm/__init__.py", line 9, in <module>
    from .core import connect, listen, Comm, CommClosedError
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/comm/core.py", line 12, in <module>
    from ..utils import parse_timedelta
  File "/home/roy/venv/lib/python3.5/site-packages/distributed/utils.py", line 1390, in <module>
    asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy())
AttributeError: module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'
```

[Looks like](https://www.tornadoweb.org/en/stable/asyncio.html#tornado.platform.asyncio.AnyThreadEventLoopPolicy) 'AnyThreadEventLoopPolicy' was added in tornado 5.0.

**Comment by rwedge** [comment]
@mrocklin Sure
