### ISSUE TITLE
to_json Fails with Distributed Scheduler and Passed S3 Session

### ISSUE THREAD

**Issue by ericness** [dask/distributed#2352]
I've been trying to write a dataframe to S3 using `to_json` and the distributed scheduler on a single node. It works fine when I let `s3fs.S3FileSystem` create a boto session for the connection, but when I pass a session in using `storage_options`, the code fails with the error message below. The code also works successfully for the default single-machine scheduler whether a session is passed in or not.

```
import pandas as pd
from dask.distributed import Client
from dask import dataframe as dd
import boto3


def write_dataframe():
    """Writes dataframe"""

    # Use distributed scheduler
    Client()

    df = dd.from_pandas(
        pd.DataFrame(
            data={
                'a': range(1000),
                'b': range(1000)
            }
        ),
        npartitions=4
    )

    df.to_json(
        filename='s3://my-bucket/test*.json.gz',
        storage_options={'session': boto3.Session(profile_name='myprofile')}
    )


if __name__ == '__main__':
    write_dataframe()

```

Error message:

```
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/core.py", line 53, in dumps
    for key, value in data.items()
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/core.py", line 54, in <dictcomp>
    if type(value) is Serialize}
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 157, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type tuple.', '(<function write_json_partition at 0x10e6262f0>, "(\'from_pandas-e602432ec131d6238006ae8d5408d0e5\', 1)", <dask.bytes.core.OpenFile object at 0x110f9d5f8>, (<class \'dict\'>, [[\'orient\', \'records\'], [\'lines\', True]]))')
distributed.comm.utils - ERROR - ('Could not serialize object of type tuple.', '(<function write_json_partition at 0x10e6262f0>, "(\'from_pandas-e602432ec131d6238006ae8d5408d0e5\', 1)", <dask.bytes.core.OpenFile object at 0x110f9d5f8>, (<class \'dict\'>, [[\'orient\', \'records\'], [\'lines\', True]]))')
Traceback (most recent call last):
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/comm/utils.py", line 40, in _to_frames
    context=context))
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/core.py", line 53, in dumps
    for key, value in data.items()
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/core.py", line 54, in <dictcomp>
    if type(value) is Serialize}
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 157, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type tuple.', '(<function write_json_partition at 0x10e6262f0>, "(\'from_pandas-e602432ec131d6238006ae8d5408d0e5\', 1)", <dask.bytes.core.OpenFile object at 0x110f9d5f8>, (<class \'dict\'>, [[\'orient\', \'records\'], [\'lines\', True]]))')
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/batched.py", line 94, in _background_send
    on_error='raise')
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/comm/tcp.py", line 221, in write
    'recipient': self._peer_addr})
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/comm/utils.py", line 47, in to_frames
    res = yield offload(_to_frames)
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/ericness/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/ericness/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/ericness/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/comm/utils.py", line 40, in _to_frames
    context=context))
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/core.py", line 53, in dumps
    for key, value in data.items()
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/core.py", line 54, in <dictcomp>
    if type(value) is Serialize}
  File "/Users/ericness/anaconda3/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 157, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type tuple.', '(<function write_json_partition at 0x10e6262f0>, "(\'from_pandas-e602432ec131d6238006ae8d5408d0e5\', 1)", <dask.bytes.core.OpenFile object at 0x110f9d5f8>, (<class \'dict\'>, [[\'orient\', \'records\'], [\'lines\', True]]))')
```

**Comment by martindurant** [comment]
This is expected behaviour: the `session` object cannot be serialised and passed between processes. What you instead need to do, is specify the set of arguments to pass through s3fs to boto, so that the session can be correctly set up in each process. The contents of `storage_options` are passed through to the s3fs [constructor](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem), which should cover all the types of option you might want to pass.

**Comment by martindurant** [comment]
In your case, `storage_options={'profile_name': 'myprofile'}` I think may be it.
