### ISSUE TITLE
CommClosedError: in <closed TCP>: Stream is closed (Client.run)

### ISSUE THREAD

**Issue by fabidick22** [dask/distributed#2368]
Hi,
I'm trying to send a function to all the workers in my distributed cluster, but I'm getting the following error:
- What am I doing wrong?

```python
from dask.distributed import Client
cli = Client("172.19.18.88:8786")
cli
```

<table style="border: 2px solid white;">
<tr>
<td style="vertical-align: top; border: 0px solid white">
<h3>Client</h3>
<ul>
  <li><b>Scheduler: </b>tcp://172.19.18.88:8786
  <li><b>Dashboard: </b><a href='http://172.19.18.88:8787/status' target='_blank'>http://172.19.18.88:8787/status</a>
</ul>
</td>
<td style="vertical-align: top; border: 0px solid white">
<h3>Cluster</h3>
<ul>
  <li><b>Workers: </b>2</li>
  <li><b>Cores: </b>16</li>
  <li><b>Memory: </b>8.14 GB</li>
</ul>
</td>
</tr>
</table>

## Example 1

```python
import os
cli.run(os.getpid)
```

    {'tcp://172.19.18.61:35829': 8711, 'tcp://172.19.18.90:46199': 9018}

## Example 2

```python
def get_status(dask_worker):
    return dask_worker.status

def get_data():
    return range(10)

# the two functions return the same error
```

```python
cli.run(get_status)
```

    ---------------------------------------------------------------------------

    StreamClosedError                         Traceback (most recent call last)

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
        176         try:
    --> 177             n_frames = yield stream.read_bytes(8)
        178             n_frames = struct.unpack('Q', n_frames)[0]

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1132                     try:
    -> 1133                         value = future.result()
       1134                     except Exception:

    StreamClosedError: Stream is closed

    
    During handling of the above exception, another exception occurred:

    CommClosedError                           Traceback (most recent call last)

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
        573                 comm = yield self.live_comm()
    --> 574                 result = yield send_recv(comm=comm, op=key, **kwargs)
        575             except (RPCClosed, CommClosedError) as e:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1132                     try:
    -> 1133                         value = future.result()
       1134                     except Exception:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1140                         try:
    -> 1141                             yielded = self.gen.throw(*exc_info)
       1142                         finally:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
        450         if reply:
    --> 451             response = yield comm.read(deserializers=deserializers)
        452         else:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1132                     try:
    -> 1133                         value = future.result()
       1134                     except Exception:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1140                         try:
    -> 1141                             yielded = self.gen.throw(*exc_info)
       1142                         finally:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
        197             if not shutting_down():
    --> 198                 convert_stream_closed_error(self, e)
        199         else:

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/comm/tcp.py in convert_stream_closed_error(obj, exc)
        125     else:
    --> 126         raise CommClosedError("in %s: %s" % (obj, exc))
        127 

    CommClosedError: in <closed TCP>: Stream is closed

    
    During handling of the above exception, another exception occurred:

    CommClosedError                           Traceback (most recent call last)

    <ipython-input-8-c75e1d4a1e25> in <module>
    ----> 1 cli.run(get_status)
    

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/client.py in run(self, function, *args, **kwargs)
       2130          '192.168.0.101:9000': 'running}
       2131         """
    -> 2132         return self.sync(self._run, function, *args, **kwargs)
       2133 
       2134     @gen.coroutine

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
        663             return future
        664         else:
    --> 665             return sync(self.loop, func, *args, **kwargs)
        666 
        667     def __repr__(self):

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
        275             e.wait(10)
        276     if error[0]:
    --> 277         six.reraise(*error[0])
        278     else:
        279         return result[0]

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
        691             if value.__traceback__ is not tb:
        692                 raise value.with_traceback(tb)
    --> 693             raise value
        694         finally:
        695             value = None

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/utils.py in f()
        260             if timeout is not None:
        261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
    --> 262             result[0] = yield future
        263         except Exception as exc:
        264             error[0] = sys.exc_info()

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1131 
       1132                     try:
    -> 1133                         value = future.result()
       1134                     except Exception:
       1135                         self.had_exception = True

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1139                     if exc_info is not None:
       1140                         try:
    -> 1141                             yielded = self.gen.throw(*exc_info)
       1142                         finally:
       1143                             # Break up a reference to itself

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/client.py in _run(self, function, *args, **kwargs)
       2078                                                             args=dumps(args),
       2079                                                             kwargs=dumps(kwargs)),
    -> 2080                                                    workers=workers, nanny=nanny)
       2081         results = {}
       2082         for key, resp in responses.items():

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1131 
       1132                     try:
    -> 1133                         value = future.result()
       1134                     except Exception:
       1135                         self.had_exception = True

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1139                     if exc_info is not None:
       1140                         try:
    -> 1141                             yielded = self.gen.throw(*exc_info)
       1142                         finally:
       1143                             # Break up a reference to itself

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
        575             except (RPCClosed, CommClosedError) as e:
        576                 raise e.__class__("%s: while trying to call remote method %r"
    --> 577                                   % (e, key,))
        578 
        579             self.comms[comm] = True  # mark as open

    CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'broadcast'

```python

```

Thanks in advance!

**Comment by mrocklin** [comment]
Can you try client.get_versions(check=True)  to verify that you have
consistent versions across your client and workers?

**Comment by mrocklin** [comment]
My guess was that you had mismatched versions between your workers and
client.  That doesn't appear to be the case though (everything is fine).

I don't know why you would get the error that you're getting.  My next
guess would be some sort of connectivity issue.  I recommend looking at the
logs for all of the workers to see if something was printed out there.

**Comment by fabidick22** [comment]
It does not print any errors in the workers, only the schduler!
![error_cluster](https://user-images.githubusercontent.com/8176821/48869674-18bd0a00-edac-11e8-952a-66b74a8b2434.png)

**Comment by fabidick22** [comment]
<h4>I can see that if my environment is not distributed everything works correctly!</h4>


```python
from dask.distributed import Client
# cli = Client("172.19.18.88:8786")
cli = Client()
cli
```




<table style="border: 2px solid white;">
<tr>
<td style="vertical-align: top; border: 0px solid white">
<h3>Client</h3>
<ul>
  <li><b>Scheduler: </b>tcp://127.0.0.1:45239
  <li><b>Dashboard: </b><a href='http://127.0.0.1:8787/status' target='_blank'>http://127.0.0.1:8787/status</a>
</ul>
</td>
<td style="vertical-align: top; border: 0px solid white">
<h3>Cluster</h3>
<ul>
  <li><b>Workers: </b>8</li>
  <li><b>Cores: </b>8</li>
  <li><b>Memory: </b>8.29 GB</li>
</ul>
</td>
</tr>
</table>



## Example 1


```python
import os
cli.run(os.getpid)
```




    {'tcp://127.0.0.1:34187': 19106,
     'tcp://127.0.0.1:36405': 19109,
     'tcp://127.0.0.1:37181': 19107,
     'tcp://127.0.0.1:37483': 19101,
     'tcp://127.0.0.1:39185': 19111,
     'tcp://127.0.0.1:42509': 19099,
     'tcp://127.0.0.1:43279': 19103,
     'tcp://127.0.0.1:44057': 19098}



## Example 2


```python
def get_status(dask_worker):
    return dask_worker.status

def get_data():
    return range(10)

# the two functions return the same error
```


```python
cli.run(get_status)
```




    {'tcp://127.0.0.1:34187': 'running',
     'tcp://127.0.0.1:36405': 'running',
     'tcp://127.0.0.1:37181': 'running',
     'tcp://127.0.0.1:37483': 'running',
     'tcp://127.0.0.1:39185': 'running',
     'tcp://127.0.0.1:42509': 'running',
     'tcp://127.0.0.1:43279': 'running',
     'tcp://127.0.0.1:44057': 'running'}




```python

```

**Comment by fabidick22** [comment]
I'm trying the same thing but only with one example and I have a different error! (or so I think)

```python
from dask.distributed import Client
cli = Client("172.19.18.88:8786")
# cli = Client()
cli
```




<table style="border: 2px solid white;">
<tr>
<td style="vertical-align: top; border: 0px solid white">
<h3>Client</h3>
<ul>
  <li><b>Scheduler: </b>tcp://172.19.18.88:8786
  <li><b>Dashboard: </b><a href='http://172.19.18.88:8787/status' target='_blank'>http://172.19.18.88:8787/status</a>
</ul>
</td>
<td style="vertical-align: top; border: 0px solid white">
<h3>Cluster</h3>
<ul>
  <li><b>Workers: </b>2</li>
  <li><b>Cores: </b>16</li>
  <li><b>Memory: </b>8.14 GB</li>
</ul>
</td>
</tr>
</table>



## Example 1


```python
def get_status(dask_worker):
    return dask_worker.status
```


```python
cli.run(get_status)
```


    ---------------------------------------------------------------------------

    IndexError                                Traceback (most recent call last)

    <ipython-input-3-c75e1d4a1e25> in <module>
    ----> 1 cli.run(get_status)
    

    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/client.py in run(self, function, *args, **kwargs)
       2130          '192.168.0.101:9000': 'running}
       2131         """
    -> 2132         return self.sync(self._run, function, *args, **kwargs)
       2133 
       2134     @gen.coroutine


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
        663             return future
        664         else:
    --> 665             return sync(self.loop, func, *args, **kwargs)
        666 
        667     def __repr__(self):


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
        275             e.wait(10)
        276     if error[0]:
    --> 277         six.reraise(*error[0])
        278     else:
        279         return result[0]


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
        691             if value.__traceback__ is not tb:
        692                 raise value.with_traceback(tb)
    --> 693             raise value
        694         finally:
        695             value = None


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/utils.py in f()
        260             if timeout is not None:
        261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
    --> 262             result[0] = yield future
        263         except Exception as exc:
        264             error[0] = sys.exc_info()


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1131 
       1132                     try:
    -> 1133                         value = future.result()
       1134                     except Exception:
       1135                         self.had_exception = True


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/tornado/gen.py in run(self)
       1145                             exc_info = None
       1146                     else:
    -> 1147                         yielded = self.gen.send(value)
       1148 
       1149                     if stack_context._state.contexts is not orig_stack_contexts:


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/distributed/client.py in _run(self, function, *args, **kwargs)
       2084                 results[key] = resp['result']
       2085             elif resp['status'] == 'error':
    -> 2086                 six.reraise(*clean_exception(**resp))
       2087         raise gen.Return(results)
       2088 


    ~/virtualEnv/daskEnv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
        690                 value = tp()
        691             if value.__traceback__ is not tb:
    --> 692                 raise value.with_traceback(tb)
        693             raise value
        694         finally:


    /home/userw1/virtualEnv/daskEnv/bin/dask-worker in get_status()
          1 def get_status(dask_worker):
    ----> 2     return dask_worker.status
    

    IndexError: tuple index out of range


### Error output from worker 1
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Run out-of-band function 'get_status'
distributed.worker - WARNING -  Run Failed
Function: get_status
args:     ()
kwargs:   {'dask_worker': <Worker: tcp://172.19.18.61:34563, running, stored: 0, running: 0/8, ready: 0, comm: 0, waiting: 0>}
Traceback (most recent call last):
  File "/home/userw1/virtualEnv/daskEnv/lib/python3.5/site-packages/distributed/worker.py", line 1044, in run
    result = function(*args, **kwargs)
  File "<ipython-input-2-5bbcc3df64bf>", line 2, in get_status
IndexError: tuple index out of range

### Error output from worker 2
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Run out-of-band function 'get_status'
XXX lineno: 2, opcode: 124
distributed.worker - WARNING -  Run Failed
Function: get_status
args:     ()
kwargs:   {'dask_worker': <Worker: tcp://172.19.18.90:45997, running, stored: 0, running: 0/8, ready: 0, comm: 0, waiting: 0>}
Traceback (most recent call last):
  File "/home/userw2/virtualEnv/daskEnv/lib/python3.5/site-packages/distributed/worker.py", line 1044, in run
    result = function(*args, **kwargs)
  File "<ipython-input-2-5bbcc3df64bf>", line 2, in get_status
SystemError: unknown opcode

### output from scheduler (nothing)
distributed.scheduler - INFO - Register tcp://172.19.18.61:34563
distributed.scheduler - INFO - Starting worker compute stream, tcp://172.19.18.61:34563
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://172.19.18.90:45997
distributed.scheduler - INFO - Starting worker compute stream, tcp://172.19.18.90:45997
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-6534074c-eddc-11e8-9250-fc4dd4d87da7
distributed.core - INFO - Starting established connection
