### ISSUE TITLE
client.sync(client.scheduler.terminate) does not shut down Scheduler

### ISSUE THREAD

**Issue by kmpaul** [dask/distributed#2426]
This is related to #600, though that issue specifically pertained to shutting down the workers (though it was mentioned that shutting down the scheduler remotely was also not possible).

I have tried the `client.sync(client.scheduler.terminate)`.  The workers successfully shut down and their processes terminate.  However, the scheduler process does not terminate.  The output looks normal:

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://128.117.10.165:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory: /var/folders/6c/yts2b01x3rj8wgdkzlwtqpzcslvb49/T/scheduler-ide6w1iz
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tcp://128.117.10.165:53026
distributed.scheduler - INFO - Starting worker compute stream, tcp://128.117.10.165:53026
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://128.117.10.165:53031
distributed.scheduler - INFO - Starting worker compute stream, tcp://128.117.10.165:53031
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-df6e97dc-02ff-11e9-ae7e-4a000271b150
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-42b0437a-0300-11e9-ae7e-4a000271b150
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
```

but, as you can see in the last 2 lines, the scheduler looks like it starts the process of shutting down but does not complete.  It hangs at this stage.

I'm looking for a robust way of shutting down the scheduler from the client.  Any ideas (including suggestions for development) are welcome.  (i.e., I'm happy to help.)

**Comment by kmpaul** [comment]
Also, I just noticed I get the following errors when I run `client.sync(client.scheduler.terminate)`:

```
---------------------------------------------------------------------------
StreamClosedError                         Traceback (most recent call last)
~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    179         try:
--> 180             n_frames = yield stream.read_bytes(8)
    181             n_frames = struct.unpack('Q', n_frames)[0]

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:

StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

CommClosedError                           Traceback (most recent call last)
~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    579                 comm = yield self.live_comm()
--> 580                 result = yield send_recv(comm=comm, op=key, **kwargs)
    581             except (RPCClosed, CommClosedError) as e:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    456         if reply:
--> 457             response = yield comm.read(deserializers=deserializers)
    458         else:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    200             if not shutting_down():
--> 201                 convert_stream_closed_error(self, e)
    202         else:

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/comm/tcp.py in convert_stream_closed_error(obj, exc)
    128     else:
--> 129         raise CommClosedError("in %s: %s" % (obj, exc))
    130

CommClosedError: in <closed TCP>: Stream is closed

During handling of the above exception, another exception occurred:

CommClosedError                           Traceback (most recent call last)
<ipython-input-3-c688637385da> in <module>
----> 1 client.sync(client.scheduler.terminate)

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    668             return future
    669         else:
--> 670             return sync(self.loop, func, *args, **kwargs)
    671
    672     def __repr__(self):

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1131
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

~/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    581             except (RPCClosed, CommClosedError) as e:
    582                 raise e.__class__("%s: while trying to call remote method %r"
--> 583                                   % (e, key,))
    584
    585             self.comms[comm] = True  # mark as open

CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'terminate'
```

**Comment by mrocklin** [comment]
Indeed.  It looks like the scheduler stops but the event loop continues.
I'll take a look to see if there is a nice way to handle things gracefully
here.

I'll also try to give you a workaround shortly.

**Comment by kmpaul** [comment]
Being new to the guts of Dask, I'm a bit slow, but I have been digging into this.

I've noticed that the `Scheduler.close()` function seems to be hanging at the `self.rpc.close()` call.  You might be able to find out what is going on faster than me, but I'm going to dig further.

**Comment by kmpaul** [comment]
That's [here](https://github.com/dask/distributed/blob/879cdb35c52135cd53ff89c36c485311b7801004/distributed/scheduler.py#L1196)

**Comment by mrocklin** [comment]
On this branch: https://github.com/dask/distributed/pull/2427

You should be able to get this to work with the following:

```python
from tornado import gen
from dask.distributed import Client
client = Client('localhost:8786')
async def stop(dask_scheduler):
    await gen.sleep(0.1)
    await dask_scheduler.close()
    loop = dask_scheduler.loop
    loop.add_callback(loop.stop)
client.run_on_scheduler(stop, wait=False)
```

If you want to be a bit harsher, you can also do this on any recent release

```python
import sys
client.run_on_scheduler(sys.exit, 0)
```

**Comment by kmpaul** [comment]
@mrocklin Thanks for this!  I feel like this is making progress.

This definitely shuts down the scheduler and the workers in one command,  but (using your branch) I get the following error from the scheduler process (all logs shown):

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://128.117.10.165:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory: /var/folders/6c/yts2b01x3rj8wgdkzlwtqpzcslvb49/T/scheduler-toivogj9
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tcp://128.117.10.165:59563
distributed.scheduler - INFO - Starting worker compute stream, tcp://128.117.10.165:59563
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-4c296dda-0395-11e9-8995-4a000271b150
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Run out-of-band function 'stop_scheduler'
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
distributed.scheduler - INFO - End scheduler at 'tcp://:8786'
Exception ignored in: <generator object add_client at 0x11a89b200>
Traceback (most recent call last):
  File "/Users/kpaul/distributed/distributed/scheduler.py", line 2039, in add_client
    self.remove_client(client=client)
  File "/Users/kpaul/distributed/distributed/scheduler.py", line 2078, in remove_client
    remove_client_from_events
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/ioloop.py", line 638, in call_later
    return self.call_at(self.time() + delay, callback, *args, **kwargs)
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 145, in call_at
    functools.partial(stack_context.wrap(callback), *args, **kwargs))
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/asyncio/base_events.py", line 549, in call_later
    timer = self.call_at(self.time() + delay, callback, *args)
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/asyncio/base_events.py", line 559, in call_at
    self._check_closed()
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 180, in read
    n_frames = yield stream.read_bytes(8)
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 201, in read
    convert_stream_closed_error(self, e)
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 129, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 180, in read
    n_frames = yield stream.read_bytes(8)
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 201, in read
    convert_stream_closed_error(self, e)
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 129, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

And if I run these commands from within ipython, I get this additional error when I exit ipython:

```
tornado.application - ERROR - Exception in Future <Future cancelled> after timeout
Traceback (most recent call last):
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 970, in error_callback
    future.result()
concurrent.futures._base.CancelledError
```

**Comment by kmpaul** [comment]
Actually, when I run your commands in a stand-alone script, I get the following logs and error message from the scheduler:

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://128.117.10.165:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory: /var/folders/6c/yts2b01x3rj8wgdkzlwtqpzcslvb49/T/scheduler-kfn1ags6
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Register tcp://128.117.10.165:56319
distributed.scheduler - INFO - Starting worker compute stream, tcp://128.117.10.165:56319
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-b6ba5e62-0396-11e9-8ada-4a000271b150
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Run out-of-band function 'stop'
distributed.scheduler - INFO - Remove client Client-b6ba5e62-0396-11e9-8ada-4a000271b150
distributed.scheduler - INFO - Remove client Client-b6ba5e62-0396-11e9-8ada-4a000271b150
distributed.scheduler - INFO - Close client connection: Client-b6ba5e62-0396-11e9-8ada-4a000271b150
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
distributed.scheduler - INFO - End scheduler at 'tcp://:8786'
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed',)>
Traceback (most recent call last):
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 180, in read
    n_frames = yield stream.read_bytes(8)
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kpaul/Software/miniconda3/envs/dask-mpi-test/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 201, in read
    convert_stream_closed_error(self, e)
  File "/Users/kpaul/distributed/distributed/comm/tcp.py", line 129, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

**Comment by mrocklin** [comment]
Yeah, there is probably a nicer way to clean things up.  

I suspect that you'll still be able to make progress on your broader mission, even given those logged warnings.  They'll look ugly for a while, but we can probably clean them up concurrently.

**Comment by kmpaul** [comment]
Ok.  I think I'm starting (emphasis on "starting") to wrap my head around asynchronous programming.

I moved the `gen.sleep` call to just before closing the loop.  That seems to have removed the error from the scheduler during shutdown.

So, just to be clear, the code I am using that seems to work on my Mac without any errors is:

```python
from tornado import gen
from dask.distributed import Client
client = Client(scheduler_file='scheduler.json')
async def stop(dask_scheduler):
    await dask_scheduler.close()
    await gen.sleep(0.1)
    loop = dask_scheduler.loop
    loop.add_callback(loop.stop)
client.run_on_scheduler(stop, wait=False)
```

**Comment by kmpaul** [comment]
And, just for my own edification, what does the `wait=False` argument do on the `client.run_on_scheduler` call?  

When I try to run my script with `wait=True` I get a `distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed` error and a `concurrent.futures._base.CancelledError`.  My noob intuition tells me that these errors come from the python exit process shutting down the TCP stream too early...  So...  why is it `wait=True` that gives the error?  I had thought that the `wait` parameter should enable waiting until...well...everything is closed before progressing/shutting down?  I'm missing something, so I'm just curious.

**Comment by kmpaul** [comment]
@mrocklin Thanks for your timely help on this!  I'm closing this issue.  I think I can move forward.

**Comment by mrocklin** [comment]
And, just for my own edification, what does the wait=False argument do on the client.run_on_scheduler call?

https://github.com/dask/distributed/pull/2429

**Comment by kmpaul** [comment]
Thanks!  That's great.
