### ISSUE TITLE
Distributed + HDFS error: 'HDFileSystem' object has no attribute 'conf'

### ISSUE THREAD

**Issue by greati** [dask/distributed#2434]
I have a cluster with three instances (Ubuntu 16), one running the scheduler and the other two with one worker process each. Packages versions are:
- dask==1.0.0
- distributed==1.25.1
- hdfs3==0.3.0
- tornado==5.1.1
- python==3.7.1

When I run the following code:

```python
dataset_path = 'hdfs://<host>:<port>/data/test.csv'
df = dd.read_csv(dataset_path, error_bad_lines=False)
df.head()
```

I get the following messages in the workers console:

```bash
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\x9d\x08\x00\x00\x00\x00\x00\x00\x8c\x13dask.dataframe.core\x94\x8c\tsafe_head\x94\x93\x94(\x8c\x14dask.dataframe.utils\x94\x8c\ncheck_meta\x94\x93\x94(\x8c\x12dask.compatibility\x94\x8c\x05apply\x94\x93\x94\x8c\x15dask.dataframe.io.csv\x94\x8c\x10pandas_read_text\x94\x93\x94]\x94(\x8c\x11pandas.io.parsers\x94\x8c\x08read_csv\x94\x93\x94(\x8c\x0fdask.bytes.core\x94\x8c\x14read_block_from_file\x94\x93\x94h\x10\x8c\x08OpenFile\x94\x93\x94(\x8c\x10dask.bytes.hdfs3\x94\x8c\x15HDFS3HadoopFileSystem\x94\x93\x94)\x81\x94}\x94(\x8c\x08protocol\x94\x8c\x04hdfs\x94\x8c\x02fs\x94\x8c\nhdfs3.core\x94\x8c\x0cHDFileSystem\x94\x93\x94)\x81\x94}\x94(\x8c\x04host\x94\x8c\x0b10.7.40.100\x94\x8c\x05token\x94N\x8c\x04port\x94M(#\x8c\x04pars\x94N\x8c\x04user\x94N\x8c\x0cticket_cache\x94Nubub\x8c\x15/data/urc_alarmes.csv\x94\x8c\x02rb\x94NNNt\x94R\x94K\x00J\x00\x90\xd0\x03C\x01\n\x94t\x94C\x98\xef\xbb\xbfDate_Time;FracSec;Event_Type;Event_SubType;Category;Area;Node;Unit;Module;Module_Description;Attribute;State;Event_Level;Desc1;Desc2;IsArchived;Ord\r\n\x94\x8c\x08builtins\x94\x8c\x04dict\x94\x93\x94]\x94(]\x94(\x8c\x0ferror_bad_lines\x94\x89e]\x94(\x8c\x05dtype\x94h2]\x94(]\x94(\x8c\x07FracSec\x94\x8c\x07float64\x94e]\x94(\x8c\nIsArchived\x94h;e]\x94(\x8c\x03Ord\x94h;ee\x86\x94e]\x94(\x8c\x03sep\x94\x8c\x01;\x94ee\x86\x94h2]\x94(]\x94(\x8c\x07FracSec\x94\x8c\x05numpy\x94\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94K\x00K\x01\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94be]\x94(\x8c\x04Area\x94hJ\x8c\x02O8\x94K\x00K\x01\x87\x94R\x94(K\x03\x8c\x01|\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94be]\x94(\x8c\nIsArchived\x94hMe]\x94(\x8c\x04Unit\x94hMe]\x94(\x8c\x03Ord\x94hMe]\x94(\x8c\x04Node\x94hTe]\x94(\x8c\rEvent_SubType\x94hMe]\x94(\x8c\x06Module\x94hTe]\x94(\x8c\x05Desc2\x94hTe]\x94(\x8c\x05Desc1\x94hTe]\x94(\x8c\tAttribute\x94hTe]\x94(\x8c\nEvent_Type\x94hTe]\x94(\x8c\x12Module_Description\x94hTe]\x94(\x8c\x08Category\x94hTe]\x94(\x8c\x05State\x94hTe]\x94(\x8c\x0bEvent_Level\x94hTe]\x94(\x8c\tDate_Time\x94hTee\x86\x94]\x94(hthGhjh`hnhQh^hZhbhlhhhphrhfhdhXh\\eeh2]\x94(]\x94(\x8c\x07enforce\x94\x89e]\x94(\x8c\x04path\x94Ne]\x94(\x8c\x0cwrite_header\x94\x89ee\x86\x94t\x94\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94)\x81\x94}\x94(\x8c\t_metadata\x94]\x94\x8c\x05_data\x94\x8c\x15pandas.core.internals\x94\x8c\x0cBlockManager\x94\x93\x94)\x81\x94(]\x94(\x8c\x18pandas.core.indexes.base\x94\x8c\n_new_Index\x94\x93\x94h\x8d\x8c\x05Index\x94\x93\x94}\x94(\x8c\x04name\x94N\x8c\x04data\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x11\x85\x94hT\x89]\x94(hthGhjh`hnhQh^hZhbhlhhhphrhfhdhXh\\et\x94bu\x86\x94R\x94h\x8f\x8c\x19pandas.core.indexes.range\x94\x8c\nRangeIndex\x94\x93\x94}\x94(\x8c\x05start\x94K\x00\x8c\x04step\x94K\x01h\x93N\x8c\x04stop\x94K\x00u\x86\x94R\x94e]\x94(h\x97h\x9aK\x00\x85\x94h\x9c\x87\x94R\x94(K\x01K\x05K\x00\x86\x94hM\x89C\x00\x94t\x94bh\x97h\x9aK\x00\x85\x94h\x9c\x87\x94R\x94(K\x01K\x0cK\x00\x86\x94hT\x89]\x94t\x94be]\x94(h\x8fh\x91}\x94(h\x93Nh\x94h\x97h\x9aK\x00\x85\x94h\x9c\x87\x94R\x94(K\x01K\x05\x85\x94hT\x89]\x94(hGh`hZhXh\\et\x94bu\x86\x94R\x94h\x8fh\x91}\x94(h\x93Nh\x94h\x97h\x9aK\x00\x85\x94h\x9c\x87\x94R\x94(K\x01K\x0c\x85\x94hT\x89]\x94(hthjhnhQh^hbhlhhhphrhfhdet\x94bu\x86\x94R\x94e}\x94\x8c\x060.14.1\x94}\x94(\x8c\x06blocks\x94]\x94(}\x94(\x8c\x08mgr_locs\x94h\x97h\x9aK\x00\x85\x94h\x9c\x87\x94R\x94(K\x01K\x05\x85\x94hJ\x8c\x02i8\x94K\x00K\x01\x87\x94R\x94(K\x03hNNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C(\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x94t\x94b\x8c\x06values\x94h\xb0u}\x94(h\xd3h\x97h\x9aK\x00\x85\x94h\x9c\x87\x94R\x94(K\x01K\x0c\x85\x94h\xda\x89C`\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x94t\x94bh\xdeh\xb6ue\x8c\x04axes\x94h\x8cust\x94b\x8c\x04_typ\x94\x8c\tdataframe\x94ub\x8c\x0cfrom_delayed\x94t\x94K\x05\x87\x94.'
Traceback (most recent call last):
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 87, in __setstate__
    self.connect()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 95, in connect
    conf = self.conf.copy()
AttributeError: 'HDFileSystem' object has no attribute 'conf'
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/core.py", line 132, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 184, in deserialize
    return loads(header, frames)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads
    return pickle.loads(b''.join(frames))
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 87, in __setstate__
    self.connect()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 95, in connect
    conf = self.conf.copy()
AttributeError: 'HDFileSystem' object has no attribute 'conf'
distributed.core - ERROR - 'HDFileSystem' object has no attribute 'conf'
Traceback (most recent call last):
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/core.py", line 386, in handle_stream
    msgs = yield comm.read()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/utils.py", line 79, in from_frames
    res = _from_frames()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/core.py", line 132, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 184, in deserialize
    return loads(header, frames)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads
    return pickle.loads(b''.join(frames))
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 87, in __setstate__
    self.connect()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 95, in connect
    conf = self.conf.copy()
AttributeError: 'HDFileSystem' object has no attribute 'conf'
distributed.worker - ERROR - 'HDFileSystem' object has no attribute 'conf'
Traceback (most recent call last):
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/worker.py", line 661, in handle_scheduler
    self.ensure_computing])
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/core.py", line 386, in handle_stream
    msgs = yield comm.read()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/utils.py", line 79, in from_frames
    res = _from_frames()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/core.py", line 132, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 184, in deserialize
    return loads(header, frames)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads
    return pickle.loads(b''.join(frames))
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 87, in __setstate__
    self.connect()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 95, in connect
    conf = self.conf.copy()
AttributeError: 'HDFileSystem' object has no attribute 'conf'
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7faafc756378>, <Future finished exception=AttributeError("'HDFileSystem' object has no attribute 'conf'")>)
Traceback (most recent call last):
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/worker.py", line 661, in handle_scheduler
    self.ensure_computing])
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/core.py", line 386, in handle_stream
    msgs = yield comm.read()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/utils.py", line 79, in from_frames
    res = _from_frames()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/core.py", line 132, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 184, in deserialize
    return loads(header, frames)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads
    return pickle.loads(b''.join(frames))
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 87, in __setstate__
    self.connect()
  File "/home/roadrunner/miniconda3/envs/dask/lib/python3.7/site-packages/hdfs3/core.py", line 95, in connect
    conf = self.conf.copy()
AttributeError: 'HDFileSystem' object has no attribute 'conf'
```

**Comment by mrocklin** [comment]
My first guess is that you have a version mismatch.  You might want to try
client.get_versions(check=True) .  If that errs then it might point you in
a good direction.

**Comment by greati** [comment]
Thank you! There were three version mismatches; I solved them and everything works fine now.
