### ISSUE TITLE
scatter without workers fails

### ISSUE THREAD

**Issue by danpf** [dask/distributed#2454]
This is with dask-jobqueue as the cluster for a Client.

given something similar to this:
```
myclust = SLURMCluster(cores=1, memory="2GB", queue='myqu')
myclust.adapt(minimum=0, maximum=10)
client = await Client(myclust, asychronous=True)
[myfut] = await client.scatter([mydata])
tasks = [client.submit(mytask, x, myfut) for x in range(20)]
```
 
i get the error 
```
distributed.core - ERROR - No workers found
Traceback (most recent call last):
  File "/home/danpf/git/distributed/distributed/core.py", line 346, in handle_comm
    result = yield result
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/danpf/git/distributed/distributed/scheduler.py", line 2277, in scatter
    raise gen.TimeoutError("No workers found")
tornado.util.TimeoutError: No workers found
```

if you do this without being asynchronous it just stalls forever (or a long time i never waited that long)

A fix would be for scattering to impose a sort of 'number_of_cores' minimum, but looking at how ncores and so on are generated it doesn't appear to be an easy fix at fist glance.

**Comment by crusaderky** [comment]
I have the same problem - a kubernetes setup where the scheduler is on 24/7, while the (beefy and costly) workers go up and down on demand. Using ``adapt(minimum=1)`` would be a very expensive proposition for me.

There is an easy workaround though:
instead of
```python
scattered = client.scatter(x)
```
I can just write
```python
def dummy(x):
    return x

scattered = client.submit(dummy, x)
```
The adaptive client will fire up 1 node and keep it up for as long as either the 'scattered' variable is descoped or the client is disconnected.

On a related topic, I confess I do not understand the benefit of scatter() vs. the dummy function approach.
