### ISSUE TITLE
worker doesn't shutsown when cluster.scale_up is used 

### ISSUE THREAD

**Issue by redsum** [dask/distributed#2458]
using this code 

```
from distributed import Client, LocalCluster, Worker
cluster = LocalCluster(processes=True, n_workers=1)
cluster.scale_up(5)
cluster.close()
```
dask workers doesn't shutdown , they go into closing state but doesn't die
ps -ef | grep -i dask 
```
lmn      21126 19797 10 Jan10 pts/9    02:51:42 dask-worker [closing]
lmn      21137 19797 10 Jan10 pts/9    02:58:44 dask-worker [closing]
lmn      21145 19797 10 Jan10 pts/9    02:51:31 dask-worker [closing]
lmn      21151 19797 10 Jan10 pts/9    02:51:27 dask-worker [closing]
lmn      25264 19797 10 Jan10 pts/9    02:51:58 dask-worker [closing]
```

**Comment by mrocklin** [comment]
Reproduced.  A fix for this would be welcome.

I notice also that the workers have a 60s death-timeout.  After 60s they *should* kill themselves regardless.  It's also possible that this is failing though.

**Comment by tomzx** [comment]
I'm not sure if this is related, but I face a somewhat similar problem. I have `--death-timeout 60` but the workers do not die. I have the following logs in the `dask-worker`

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f73349dba10>>, <Task finished coro=<Worker.heartbeat() done, defined at /usr/local/lib/python3.7/site-packages/distributed/worker.py:855> exception=OSError("Timed out trying to connect to 'tcp://10.200.49.225:8786' after 10 s: Timed out trying to connect to 'tcp://10.200.49.225:8786' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x7f72fc339190>: ConnectionRefusedError: [Errno 111] Connection refused")>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 221, in connect
    _raise(error)
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 204, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.200.49.225:8786' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x7f72fc339190>: ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.7/site-packages/distributed/worker.py", line 864, in heartbeat
    metrics=await self.get_metrics(),
  File "/usr/local/lib/python3.7/site-packages/distributed/core.py", line 735, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/usr/local/lib/python3.7/site-packages/distributed/core.py", line 869, in connect
    connection_args=self.connection_args,
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/core.py", line 204, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://10.200.49.225:8786' after 10 s: Timed out trying to connect to 'tcp://10.200.49.225:8786' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x7f72fc339190>: ConnectionRefusedError: [Errno 111] Connection refused
```

It appears the `dask-worker` process is stuck in a loop and will produce this error every 10 seconds.

**Comment by mrocklin** [comment]
@tomzx I encourage you to provide a minimal reproducible example.  There isn't much the maintainers can efficiently do without one unfortunately.
