### ISSUE TITLE
'Future' object has no attribute 'memory_usage'

### ISSUE THREAD

**Issue by gsakkis** [dask/distributed#2460]
```
import dask.dataframe as dd
import pandas as pd
from dask.distributed import Client

if __name__ == '__main__':
    client = Client()
    df = pd.DataFrame({'A': range(1, 11)})
    ddf = dd.from_pandas(df, npartitions=2)
    print(ddf.memory_usage().compute())

    pddf = ddf.persist()
    print(pddf.memory_usage().compute())
```
```
A         80
Index    164
dtype: int64
distributed.worker - WARNING -  Compute Failed
Function:  subgraph_callable
args:      ()
kwargs:    {}
Exception: AttributeError("'Future' object has no attribute 'memory_usage'",)

distributed.worker - WARNING -  Compute Failed
Function:  subgraph_callable
args:      ()
kwargs:    {}
Exception: AttributeError("'Future' object has no attribute 'memory_usage'",)

Traceback (most recent call last):
  File "mem.py", line 12, in <module>
    print(pddf.memory_usage().compute())
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/base.py", line 397, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/distributed/client.py", line 2338, in get
    direct=direct)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/distributed/client.py", line 1662, in gather
    asynchronous=asynchronous)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/distributed/client.py", line 676, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/distributed/client.py", line 1503, in _gather
    traceback)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/optimization.py", line 942, in __call__
    dict(zip(self.inkeys, args)))
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 132, in _get_recursive
    res = cache[x] = _get_recursive(dsk, dsk[x], cache)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 136, in _get_recursive
    args2 = [_get_recursive(dsk, k, cache) for k in args]
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 136, in <listcomp>
    args2 = [_get_recursive(dsk, k, cache) for k in args]
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 126, in _get_recursive
    return [_get_recursive(dsk, k, cache) for k in x]
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 126, in <listcomp>
    return [_get_recursive(dsk, k, cache) for k in x]
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 132, in _get_recursive
    res = cache[x] = _get_recursive(dsk, dsk[x], cache)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/core.py", line 137, in _get_recursive
    return func(*args2)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/dataframe/core.py", line 3684, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/home/gsk/projects/miniconda3/envs/myenv/lib/python3.6/site-packages/dask/utils.py", line 694, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
AttributeError: 'Future' object has no attribute 'memory_usage'
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-1, started daemon)>
distributed.nanny - WARNING - Worker process 6135 was killed by unknown signal
```

**Comment by mrocklin** [comment]
I'm able to reproduce.  Thank you for the excellent bug report @gsakkis 

@jcrist @TomAugspurger any chance either of you have time to look into this?

**Comment by gsakkis** [comment]
No, it's probably different then, I'm getting it on v1.0.0:
```
dask==1.0.0
distributed==1.25.2
```

**Comment by TomAugspurger** [comment]
Taking a look now.

**Comment by TomAugspurger** [comment]
a47e905675bc0ff8d1da1ac89b8214e548534d5a was the commit breaking this.

So, as a temporary workaround, set the `fuse_subgraphs=False` config.

```python
    with dask.config.set(fuse_subgraphs=False):
        print(pddf.memory_usage().compute())
```

**Comment by mrocklin** [comment]
Yeah, it looks like `Future` objects are getting pulled into subgraph callables, which the optimization routines can't inspect (or at least that's my guess)

```
distributed/tests/test_collections.py::test_gh2460
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/mrocklin/workspace/distributed/distributed/worker.py(2100)execute()
-> self.exceptions[key] = result['exception']
(Pdb) pp key
("('from_pandas-series-groupby-sum-chunk-memory_usage-ac35f72721bff85cecd6bebd84ee216c', "
 '0)')
(Pdb) pp self.tasks
{"('from_pandas-f42bf07c4c4c8e11a5f8ed2e2dae12fd', 1)": (<function execute_task at 0x10887b950>,
                                                         (    A
5   6
6   7
7   8
8   9
9  10,),
                                                         {}),
 "('from_pandas-series-groupby-sum-chunk-memory_usage-ac35f72721bff85cecd6bebd84ee216c', 0)": (subgraph_callable,
                                                                                               (),
                                                                                               {})}
(Pdb) pp self.tasks["('from_pandas-series-groupby-sum-chunk-memory_usage-ac35f72721bff85cecd6bebd84ee216c', 0)"]
(subgraph_callable, (), {})
(Pdb) pp self.tasks["('from_pandas-series-groupby-sum-chunk-memory_usage-ac35f72721bff85cecd6bebd84ee216c', 0)"][0]
subgraph_callable
(Pdb) pp self.tasks["('from_pandas-series-groupby-sum-chunk-memory_usage-ac35f72721bff85cecd6bebd84ee216c', 0)"][0].dsk
{('memory_usage-ac35f72721bff85cecd6bebd84ee216c', 0): (subgraph_callable,
                                                        <Future: status: pending, key: ('from_pandas-f42bf07c4c4c8e11a5f8ed2e2dae12fd', 0)>,
                                                        'from_pandas-f42bf07c4c4c8e11a5f8ed2e2dae12fd'),
 ('series-groupby-sum-chunk-f6d2e309a0f2e4745fa2238cfb751d81', 0, 0, 0): (<function apply at 0x107d33488>,
                                                                          <function _apply_chunk at 0x31b279ea0>,
                                                                          [('memory_usage-ac35f72721bff85cecd6bebd84ee216c',
                                                                            0),
                                                                           (subgraph_callable,
                                                                            ('memory_usage-ac35f72721bff85cecd6bebd84ee216c',
                                                                             0),
                                                                            'index',
                                                                            'memory_usage-ac35f72721bff85cecd6bebd84ee216c')],
                                                                          {'chunk': <methodcaller: sum>,
                                                                           'columns': None})}
```

Here is a test and a pdb statement to get to the situation above (I recommend the test regardless).

```diff
diff --git a/distributed/tests/test_collections.py b/distributed/tests/test_collections.py
index cb51d62c..877a4db2 100644
--- a/distributed/tests/test_collections.py
+++ b/distributed/tests/test_collections.py
@@ -173,3 +173,12 @@ def test_sparse_arrays(c, s, a, b):
     future = c.compute(s.sum(axis=0)[:10])

     yield future
+
+
+@gen_cluster(client=True)
+def test_gh2460(c, s, a, b):
+    df = pd.DataFrame({'A': range(1, 11)})
+    ddf = dd.from_pandas(df, npartitions=2)
+
+    ddf = ddf.persist()
+    yield c.compute(ddf.memory_usage())
diff --git a/distributed/worker.py b/distributed/worker.py
index 12b41ca1..6eb1051f 100644
--- a/distributed/worker.py
+++ b/distributed/worker.py
@@ -2096,6 +2096,7 @@ class Worker(ServerNode):
                     self.transition(key, 'rescheduled', report=False)
                     self.release_key(key, report=False)
                 else:
+                    import pdb; pdb.set_trace()
                     self.exceptions[key] = result['exception']
                     self.tracebacks[key] = result['traceback']
                     logger.warning(" Compute Failed\n"
```

cc @jcrist

**Comment by jcrist** [comment]
@TomAugspurger, I'm going to take care of this.
