### ISSUE TITLE
Failing sometimes when executing jupyter notebooks

### ISSUE THREAD

**Issue by AakashGfude** [dask/distributed#2479]
I am using dask Futures to execute all the jupyter notebooks. It works fine few times, but other times there are errors like the one pasted below as well as sometime there are cases similar to [https://github.com/dask/distributed/issues/2467](url) , where the execution completes but there is this tornado error.

`[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 206, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/home/aakashgc/Documents/jupyter_client/jupyter_client/jupyter_client/session.py", line 924, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'6d861900582d835681f045fc4b905f6c4fa2f595ffd9d41d26f48af1da8e25f0'
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aakashgc/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 467, in initialize
    self.init_sockets()
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 239, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 181, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
distributed.worker - WARNING -  Compute Failed
Function:  preprocess
args:      ({'cells': [{'cell_type': 'markdown', 'metadata': {}, 'source': '# Inline\n\nA test suite for inline items'}, {'cell_type': 'markdown', 'metadata': {}, 'source': '## Code\n\nHere is some inline python `import numpy as np` that should be displayed\n\nand some text that is not code `here`'}, {'cell_type': 'markdown', 'metadata': {}, 'source': '## Math\n\nInline maths with inline role: $ x^3+\\frac{1+\\sqrt{2}}{\\pi} $\n\nInline maths using dollar signs (not supported yet): \\$x^3+frac{1+sqrt{2}}{pi}\\$ as the\nbackslashes are removed.'}], 'metadata': {'filename': 'inline.rst', 'kernelspec': {'display_name': 'Python', 'language': 'python3', 'name': 'python3'}, 'title': 'Inline'}, 'nbformat': 4, 'nbformat_minor': 2}, {'metadata': {'path': '_build/jupyter/executed/Python', 'filename': 'inline', 'start_time': 1548302206.8783436}})
kwargs:    {}
Exception: RuntimeError('Kernel died before replying to kernel_info')

tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f193458f400>, <Future finished exception=RuntimeError('Kernel died before replying to kernel_info')>)
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 3634, in track_future
    result = yield future._result()
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 206, in _result
    six.reraise(*exc)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 359, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/home/aakashgc/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 304, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(cwd=path)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 258, in start_new_kernel
    kc.wait_for_ready(timeout=self.startup_timeout)
  File "/home/aakashgc/Documents/jupyter_client/jupyter_client/jupyter_client/blocking/client.py", line 120, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info

`

There is some conflict between the ports of the workers and the zmq ports for jupyter kernel ?
How do you suggest I go about this. Should I restart the worker again when it fails like this. ? 
What is the standard way of restarting it.

The code which I have written looks as follows :- 

```
from dask.distributed import Client, LocalCluster,

self.cluster = LocalCluster()
self.client = Client(self.cluster.scheduler.address)

```

```
future = self.client.submit(ep.preprocess, notebook, {"metadata":  .... })
self.futures.append(future)
```

The above submit function runs in loop for each notebook

**Comment by AakashGfude** [comment]
> What versions of tornado / jupyter / ipython?

tornado version is 5.1
ipython version is 6.5.0
jupyter version is 4.4.0

**Comment by AakashGfude** [comment]
I have upgraded IPython now to 7.2.0. but the errors are still there. The error messages change, probably because of my setup as it has a lot of moving pieces. The current error is :- 

`tornado.application - ERROR - Exception in Future <Future cancelled> after timeout
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 970, in error_callback
    future.result()
concurrent.futures._base.CancelledError
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 177, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 198, in read
    convert_stream_closed_error(self, e)
  File "/home/aakashgc/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
`

Maybe it is hard to debug from your end just looking at these messages. To be honest, I have started using and knowing about dask since this week and I am also new to the Python ecosystem. 

What do you suggest I should learn or go through to tackle these kind of errors. And what would be your diagnosis for these errors?

Thank you for your help

**Comment by AakashGfude** [comment]
Ok. I have the issue, but want clarification and ramification as to why this is happening.

As I had mentioned, I am using 

`self.cluster = LocalCluster()
self.client = Client(self.cluster)
`

when I changed it to only have 

`self.client = Client()`

the errors vanished. The doc says they are basically the same thing though.
