### ISSUE TITLE
Cross platform workers not able to connect 

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#250]
I need to have a set of win32 workers, which I am using a virtual machine to host. It seems that, even though network connectivity is fine, when you run a scheduler on a linux host and try to connect to it from a windows worker the connection cannot be resolved - worker just hangs on "Waiting to connect to:"

Any thoughts?

**Comment by nfaggian** [comment]
Furthermore a traceback when starting the scheduler in windows:

~~~
distributed.utils - ERROR - unpack requires a bytes object of length 4
Traceback (most recent call last):
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\distributed\utils.py", line 237, in log_errors
    yield
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\distributed\bokeh\tasks\server_lifecycle.py", line 45, in task_events
    msgs = yield read(stream)
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\tornado\gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\distributed\core.py", line 222, in read
    n_frames = struct.unpack('L', n_frames)[0]
struct.error: unpack requires a bytes object of length 4
distributed.utils - ERROR - unpack requires a bytes object of length 4
Traceback (most recent call last):
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\distributed\utils.py", line 237, in log_errors
    yield
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\distributed\bokeh\status\server_lifecycle.py", line 71, in progress
    msg = yield read(stream)
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\tornado\gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "C:\Users\IEUser\Anaconda3\lib\site-packages\distributed\core.py", line 222, in read
    n_frames = struct.unpack('L', n_frames)[0]
struct.error: unpack requires a bytes object of length 4

Interrupted, shutting down

~~~

**Comment by mrocklin** [comment]
Looks like the `struct` datatype conventions are platform specific.  We currently incorrectly assume that unsigned longs are eight bytes long.   Should be a quick fix.

**Comment by mrocklin** [comment]
Should be fixed in #251

Thank you for the bug report and the useful error message.

**Comment by nfaggian** [comment]
OK - I will check that out and try it!

**Comment by nfaggian** [comment]
Works! Suggest you merge it in...
