### ISSUE TITLE
KeyError with joblib and sklearn cross_validate

### ISSUE THREAD

**Issue by robbisg** [dask/distributed#2532]
I have a kubernetes cluster, with image pulled from https://www.github.com/robbisg/docker-dask-k8s.

using
```python
import numpy as np
from dask.distributed import Client
#import joblib
from sklearn.datasets import load_digits
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC

from sklearn.externals import joblib
digits = load_digits()
 
param_space = {
    'C': np.logspace(-6, 6, 13),
     'gamma': np.logspace(-8, 8, 17),
     'tol': np.logspace(-4, -1, 4),
     'class_weight': [None, 'balanced'],
 }

model = SVC(kernel='rbf')
search = RandomizedSearchCV(model, param_space, cv=3, n_iter=50, verbose=10, n_jobs=-1)

#import joblib
with joblib.parallel_backend('dask'):
    search.fit(digits.data, digits.target)
```
Everything works fine
```
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 6 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.7s
[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.8s
```
and so on.

When I use:
```python
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
from sklearn.metrics.scorer import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC

from sklearn.externals import joblib

diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
lasso = linear_model.Lasso()

with joblib.parallel_backend('dask', scatter=[X, y]):
    cv_results = cross_validate(lasso, X, y, cv=15, return_train_score=False, verbose=1)
```
The notebook hangs on, without any response. When I interrupt the notebook I had this:
```
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 6 concurrent workers.
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fcf2fa9f400>, <Future finished exception=AssertionError("yield from wasn't used with future",)>)
Traceback (most recent call last):
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 182, in maybe_to_futures
    f = call_data_futures[arg]
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 48, in __getitem__
    ref, val = self._data[id(obj)]
KeyError: 140527823034688
```
I will post the full TraceBack, if you want. I don't know if it is a scikit-learn, dask or joblib issue.

**Comment by mrocklin** [comment]
cc @ogrisel

**Comment by ogrisel** [comment]
@robbisg this is probably a joblib issue. Please feel free to report it there.

BTW, even it was not broken, the explicit scattering should probably not accelerate the processing for this code: the connector does an implicit scattering of the CV chunked data automatically.

**Comment by robbisg** [comment]
Thank you @ogrisel !

I re-ran the example without ```scatter```.
This is the full Traceback (after stopping the kernel).
```
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 12 concurrent workers.
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f74d437fd08>, <Future finished exception=AssertionError("yield from wasn't used with future",)>)
Traceback (most recent call last):
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 182, in maybe_to_futures
    f = call_data_futures[arg]
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 48, in __getitem__
    ref, val = self._data[id(obj)]
KeyError: 140139753187168

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 223, in callback_wrapper
    callback(result)  # gets called in separate thread
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 213, in apply_async
    func, args = self._to_func_args(func)
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 202, in _to_func_args
    args = list(maybe_to_futures(args))
  File "/home/robbis/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py", line 190, in maybe_to_futures
    [f] = self.client.scatter([arg])
AssertionError: yield from wasn't used with future
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py in maybe_to_futures(args)
    181                     try:
--> 182                         f = call_data_futures[arg]
    183                     except KeyError:

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py in __getitem__(self, obj)
     47     def __getitem__(self, obj):
---> 48         ref, val = self._data[id(obj)]
     49         if ref() is not obj:

KeyError: 140139753095216

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-7-15c89f79b36e> in <module>
     14 
     15 with joblib.parallel_backend('dask'):
---> 16     cv_results = cross_validate(lasso, X, y, cv=15, return_train_score=False, verbose=1)

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    238             return_times=True, return_estimator=return_estimator,
    239             error_score=error_score)
--> 240         for train, test in cv.split(X, y, groups))
    241 
    242     zipped_scores = list(zip(*scores))

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    918                 self._iterating = self._original_iterator is not None
    919 
--> 920             while self.dispatch_one_batch(iterator):
    921                 pass
    922 

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    757                 return False
    758             else:
--> 759                 self._dispatch(tasks)
    760                 return True
    761 

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    714         with self._lock:
    715             job_idx = len(self._jobs)
--> 716             job = self._backend.apply_async(batch, callback=cb)
    717             # A job can complete so quickly than its callback is
    718             # called before we get here, causing self._jobs to

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py in apply_async(self, func, callback)
    211     def apply_async(self, func, callback=None):
    212         key = '%s-batch-%s' % (_funcname(func), uuid4().hex)
--> 213         func, args = self._to_func_args(func)
    214 
    215         future = self.client.submit(func, *args, key=key, **self.submit_kwargs)

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py in _to_func_args(self, func)
    200         tasks = []
    201         for f, args, kwargs in func.items:
--> 202             args = list(maybe_to_futures(args))
    203             kwargs = dict(zip(kwargs.keys(),
    204                               maybe_to_futures(kwargs.values())))

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/sklearn/externals/joblib/_dask.py in maybe_to_futures(args)
    188                             # more workers need to reuse this data
    189                             # concurrently.
--> 190                             [f] = self.client.scatter([arg])
    191                             call_data_futures[arg] = f
    192 

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/distributed/client.py in scatter(self, data, workers, broadcast, direct, hash, maxsize, timeout, asynchronous)
   1872                              broadcast=broadcast, direct=direct,
   1873                              local_worker=local_worker, timeout=timeout,
-> 1874                              asynchronous=asynchronous, hash=hash)
   1875 
   1876     @gen.coroutine

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    673             return future
    674         else:
--> 675             return sync(self.loop, func, *args, **kwargs)
    676 
    677     def __repr__(self):

~/miniconda3/envs/neuropy_orig/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    273     else:
    274         while not e.is_set():
--> 275             e.wait(10)
    276     if error[0]:
    277         six.reraise(*error[0])

~/miniconda3/envs/neuropy_orig/lib/python3.6/threading.py in wait(self, timeout)
    549             signaled = self._flag
    550             if not signaled:
--> 551                 signaled = self._cond.wait(timeout)
    552             return signaled
    553 

~/miniconda3/envs/neuropy_orig/lib/python3.6/threading.py in wait(self, timeout)
    297             else:
    298                 if timeout > 0:
--> 299                     gotit = waiter.acquire(True, timeout)
    300                 else:
    301                     gotit = waiter.acquire(False)

KeyboardInterrupt:
```
Pods have these packages ```pip freeze```.
```
adal==1.2.1
asn1crypto==0.24.0
backcall==0.1.0
bleach==3.1.0
blosc==1.7.0
bokeh==1.0.4
bz2file==0.98
cachetools==3.1.0
certifi==2018.11.29
cffi==1.12.0
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
cryptography==2.5
cycler==0.10.0
Cython==0.29.5
cytoolz==0.9.0.1
dask==1.1.1
dask-jobqueue==0.4.1
dask-kubernetes==0.7.0
decorator==4.3.2
defusedxml==0.5.0
distributed==1.25.3
docrep==0.2.5
entrypoints==0.3
google-auth==1.6.2
HeapDict==1.0.0
idna==2.8
imbalanced-learn==0.4.3
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.2
Jinja2==2.10
joblib==0.13.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.0.1
kubernetes==8.0.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mistune==0.8.4
mne==0.17.0
msgpack==0.6.1
nbconvert==5.4.1
nbformat==4.4.0
nibabel==2.3.3
nilearn==0.5.0
nitime==0.7
notebook==5.7.4
numpy==1.16.1
oauthlib==3.0.1
packaging==19.0
pandas==0.24.1
pandocfilters==1.4.2
parso==0.3.4
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
prometheus-client==0.5.0
prompt-toolkit==2.0.8
psutil==5.5.0
ptyprocess==0.6.0
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycparser==2.19
Pygments==2.3.1
PyJWT==1.7.1
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.3
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
scikit-learn==0.20.2
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
sortedcontainers==2.1.0
tblib==1.3.2
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.54.0
widgetsnbextension==3.4.2
zict==0.1.3
```
These are logs on pods
```
[...]
+ dask-worker --nthreads 2 --no-bokeh --memory-limit 1G --death-timeout 180
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.244.1.37:35747'
distributed.worker - INFO -       Start worker at:    tcp://10.244.1.37:34041
distributed.worker - INFO -          Listening to:    tcp://10.244.1.37:34041
distributed.worker - INFO -              nanny at:          10.244.1.37:35747
distributed.worker - INFO - Waiting to connect to: tcp://192.168.30.248:43857
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                 1000.00 MB
distributed.worker - INFO -       Local Directory:           /worker-p_0gnrr8
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to: tcp://192.168.30.248:43857
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
```

**Comment by robbisg** [comment]
I update the thread since I figure out that it may be an issue with the number of splits of the cross_validation with respect to the number of pods deployed:

I use ```pods = cluster.scale(6)``` with ```--nthreads=2``` and using the snippet below (with ```cv=6```) everything is fine

```python
with joblib.parallel_backend('dask'):
    cv_results = cross_validate(lasso, X, y, cv=6, n_jobs=-1, verbose=10)
    pass
```

While with ```cv=7``` the system hangs.
```python
with joblib.parallel_backend('dask'):
    cv_results = cross_validate(lasso, X, y, cv=7, n_jobs=-1, verbose=10)
    pass
```
@ogrisel , if you'd like I can try to fix it if you give me some hints (and think that is quite easy)!

OT:
Running the above code without importing joblib from the bundled scikit external library, cause the usage of ```LokyBackend``` .

**Comment by jakirkham** [comment]
Am no longer seeing this issue with the reproducer provided. Also it appears PR ( https://github.com/joblib/joblib/pull/914 ) (potentially related) has already been merged and released. Going to go ahead and close.

If you are still seeing issues, please feel free to report a new issue. Thanks again for raising this to us 🙂
