### ISSUE TITLE
test_only_local_access deadlocks with no network access

### ISSUE THREAD

**Issue by QuLogic** [dask/distributed#2552]
In builders, there is no access to the network. When tests get to `test_only_local_access`, it seems to get stuck. If I enable the network locally, the test works again, but this is not possible on a real builder.

I'm not sure what the test does, but at least from the name, I guess I should not run it when there's no network. But it should probably not get stuck if possible.

**Comment by mrocklin** [comment]
Hrm, do you happen to have a traceback?  I would be curious to know where it is getting stuck.  It is not very different from many other tests.  It should certainly work fine without internet access.  Not having a network of any sort is another matter, but hopefully it would work fine on loopback.

**Comment by QuLogic** [comment]
After about 10 minutes, I hit Ctrl+C, and then got this failure from pytest:
```
====================================================================== FAILURES ======================================================================
_______________________________________________________________ test_only_local_access _______________________________________________________________

loop = <tornado.platform.asyncio.AsyncIOLoop object at 0xe9eca08c>

    def test_only_local_access(loop):
        with LocalCluster(scheduler_port=0, silence_logs=False,
                          diagnostics_port=None, loop=loop) as c:
>           sync(loop, assert_can_connect_locally_4, c.scheduler.port)

distributed/deploy/tests/test_local.py:323: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

loop = <tornado.platform.asyncio.AsyncIOLoop object at 0xe9eca08c>, func = <function assert_can_connect_locally_4 at 0xef9befa4>, args = (40389,)
kwargs = {}, f = <function sync.<locals>.f at 0xe9dcbfa4>

    def sync(loop, func, *args, **kwargs):
        """
        Run coroutine in loop running in separate thread.
        """
        # Tornado's PollIOLoop doesn't raise when using closed, do it ourselves
        if PollIOLoop and ((isinstance(loop, PollIOLoop) and getattr(loop, '_closing', False)) or
                (hasattr(loop, 'asyncio_loop') and loop.asyncio_loop._closed)):
            raise RuntimeError("IOLoop is closed")
    
        timeout = kwargs.pop('callback_timeout', None)
    
        e = threading.Event()
        main_tid = get_thread_identity()
        result = [None]
        error = [False]
    
        @gen.coroutine
        def f():
            try:
                if main_tid == get_thread_identity():
                    raise RuntimeError("sync() called from thread of running loop")
                yield gen.moment
                thread_state.asynchronous = True
                future = func(*args, **kwargs)
                if timeout is not None:
                    future = gen.with_timeout(timedelta(seconds=timeout), future)
                result[0] = yield future
            except Exception as exc:
                error[0] = sys.exc_info()
            finally:
                thread_state.asynchronous = False
                e.set()
    
        loop.add_callback(f)
        if timeout is not None:
            if not e.wait(timeout):
                raise gen.TimeoutError("timed out after %s s." % (timeout,))
        else:
            while not e.is_set():
>               e.wait(10)

distributed/utils.py:275: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <threading.Event object at 0xe9f06e0c>, timeout = 10

    def wait(self, timeout=None):
        """Block until the internal flag is true.
    
        If the internal flag is true on entry, return immediately. Otherwise,
        block until another thread calls set() to set the flag to true, or until
        the optional timeout occurs.
    
        When the timeout argument is present and not None, it should be a
        floating point number specifying a timeout for the operation in seconds
        (or fractions thereof).
    
        This method returns the internal flag on exit, so it will always return
        True except if a timeout is given and the operation times out.
    
        """
        with self._cond:
            signaled = self._flag
            if not signaled:
>               signaled = self._cond.wait(timeout)

/usr/lib/python3.7/threading.py:552: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Condition(<unlocked _thread.lock object at 0xe9fa7278>, 0)>, timeout = 10

    def wait(self, timeout=None):
        """Wait until notified or until a timeout occurs.
    
        If the calling thread has not acquired the lock when this method is
        called, a RuntimeError is raised.
    
        This method releases the underlying lock, and then blocks until it is
        awakened by a notify() or notify_all() call for the same condition
        variable in another thread, or until the optional timeout occurs. Once
        awakened or timed out, it re-acquires the lock and returns.
    
        When the timeout argument is present and not None, it should be a
        floating point number specifying a timeout for the operation in seconds
        (or fractions thereof).
    
        When the underlying lock is an RLock, it is not released using its
        release() method, since this may not actually unlock the lock when it
        was acquired multiple times recursively. Instead, an internal interface
        of the RLock class is used, which really unlocks it even when it has
        been recursively acquired several times. Another internal interface is
        then used to restore the recursion level when the lock is reacquired.
    
        """
        if not self._is_owned():
            raise RuntimeError("cannot wait on un-acquired lock")
        waiter = _allocate_lock()
        waiter.acquire()
        self._waiters.append(waiter)
        saved_state = self._release_save()
        gotit = False
        try:    # restore state no matter what (e.g., KeyboardInterrupt)
            if timeout is None:
                waiter.acquire()
                gotit = True
            else:
                if timeout > 0:
>                   gotit = waiter.acquire(True, timeout)
E                   KeyboardInterrupt

/usr/lib/python3.7/threading.py:300: KeyboardInterrupt

During handling of the above exception, another exception occurred:

loop = <tornado.platform.asyncio.AsyncIOLoop object at 0xe9eca08c>

    def test_only_local_access(loop):
        with LocalCluster(scheduler_port=0, silence_logs=False,
                          diagnostics_port=None, loop=loop) as c:
>           sync(loop, assert_can_connect_locally_4, c.scheduler.port)

distributed/deploy/tests/test_local.py:323: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
distributed/deploy/local.py:361: in __exit__
    self.close()
distributed/deploy/local.py:300: in close
    result = self.sync(self._close, callback_timeout=timeout)
distributed/deploy/local.py:172: in sync
    return sync(self.loop, func, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

loop = <tornado.platform.asyncio.AsyncIOLoop object at 0xe9eca08c>
func = <bound method LocalCluster._close of LocalCluster('tcp://127.0.0.1:40389', workers=4, ncores=4)>, args = (), kwargs = {}
f = <function sync.<locals>.f at 0xe3788a4c>

    def sync(loop, func, *args, **kwargs):
        """
        Run coroutine in loop running in separate thread.
        """
        # Tornado's PollIOLoop doesn't raise when using closed, do it ourselves
        if PollIOLoop and ((isinstance(loop, PollIOLoop) and getattr(loop, '_closing', False)) or
                (hasattr(loop, 'asyncio_loop') and loop.asyncio_loop._closed)):
            raise RuntimeError("IOLoop is closed")
    
        timeout = kwargs.pop('callback_timeout', None)
    
        e = threading.Event()
        main_tid = get_thread_identity()
        result = [None]
        error = [False]
    
        @gen.coroutine
        def f():
            try:
                if main_tid == get_thread_identity():
                    raise RuntimeError("sync() called from thread of running loop")
                yield gen.moment
                thread_state.asynchronous = True
                future = func(*args, **kwargs)
                if timeout is not None:
                    future = gen.with_timeout(timedelta(seconds=timeout), future)
                result[0] = yield future
            except Exception as exc:
                error[0] = sys.exc_info()
            finally:
                thread_state.asynchronous = False
                e.set()
    
        loop.add_callback(f)
        if timeout is not None:
            if not e.wait(timeout):
>               raise gen.TimeoutError("timed out after %s s." % (timeout,))
E               tornado.util.TimeoutError: timed out after 20 s.

distributed/utils.py:272: TimeoutError
---------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:40389
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:36795'
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:37653'
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:44817'
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:43303'
/usr/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/builddir/build/BUILD/distributed-1.26.0/distributed/config.py:20: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:34455
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:34455
distributed.worker - INFO -              nanny at:            127.0.0.1:36795
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    3.93 GB
distributed.worker - INFO -       Local Directory: /builddir/build/BUILD/distributed-1.26.0/dask-worker-space/worker-4wuyf9ox
distributed.worker - INFO - -------------------------------------------------
/usr/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/builddir/build/BUILD/distributed-1.26.0/distributed/config.py:20: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:42827
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:42827
distributed.worker - INFO -              nanny at:            127.0.0.1:37653
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    3.93 GB
distributed.worker - INFO -       Local Directory: /builddir/build/BUILD/distributed-1.26.0/dask-worker-space/worker-rmb1xiee
distributed.worker - INFO - -------------------------------------------------
/usr/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/builddir/build/BUILD/distributed-1.26.0/distributed/config.py:20: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:35995
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:35995
distributed.worker - INFO -              nanny at:            127.0.0.1:44817
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    3.93 GB
distributed.worker - INFO -       Local Directory: /builddir/build/BUILD/distributed-1.26.0/dask-worker-space/worker-sj_y94rb
distributed.worker - INFO - -------------------------------------------------
/usr/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/builddir/build/BUILD/distributed-1.26.0/distributed/config.py:20: YAMLLoadWarning: 
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:38095
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:38095
distributed.worker - INFO -              nanny at:            127.0.0.1:43303
distributed.scheduler - INFO - Register tcp://127.0.0.1:42827
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    3.93 GB
distributed.worker - INFO -       Local Directory: /builddir/build/BUILD/distributed-1.26.0/dask-worker-space/worker-t54u259h
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:42827
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://127.0.0.1:35995
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:35995
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://127.0.0.1:34455
distributed.scheduler - INFO - Register tcp://127.0.0.1:38095
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:34455
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:38095
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:40389
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
Exception in thread IO loop:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/utils.py", line 355, in run_loop
    loop.start()
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/utils_test.py", line 116, in start
    orig_start()
  File "/usr/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1199, in inner
    self.run()
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/utils_test.py", line 1110, in assert_cannot_connect
    comm.abort()
  File "/usr/lib/python3.7/site-packages/_pytest/python_api.py", line 714, in __exit__
    fail(self.message)
  File "/usr/lib/python3.7/site-packages/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'OSError'>

======================================== 1 failed, 15 skipped, 1255 deselected, 2 warnings in 672.41 seconds =========================================
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0xe9c1808c>: ConnectionRefusedError: [Errno 111] Connection refused')>
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/comm/tcp.py", line 340, in connect
    **kwargs)
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.7/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib/python3.7/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/comm/tcp.py", line 351, in connect
    convert_stream_closed_error(self, e)
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0xe9c1808c>: ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by QuLogic** [comment]
Now also hanging in `test_hostport` on 1.27.1.

**Comment by QuLogic** [comment]
I had to hit Ctrl+C 3 times, but here's the backtrace for it. It seems like the test doesn't really cope with failure as well it should.
```pytb
distributed/cli/tests/test_dask_scheduler.py::test_hostport ^C^C^C
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/usr/lib64/python3.7/threading.py:300: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --fulltrace)
Traceback (most recent call last):
  File "/usr/bin/pytest-3", line 11, in <module>
    load_entry_point('pytest==4.4.1', 'console_scripts', 'pytest')()
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 79, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.7/site-packages/_pytest/main.py", line 242, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python3.7/site-packages/_pytest/main.py", line 235, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/usr/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.7/site-packages/_pytest/terminal.py", line 656, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 73, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 325, in teardown_all
    self._pop_and_teardown()
  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 297, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 315, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/usr/lib/python3.7/site-packages/_pytest/runner.py", line 305, in _callfinalizers
    fin()
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 859, in finish
    six.reraise(*e)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 851, in finish
    func()
  File "/usr/lib/python3.7/site-packages/_pytest/fixtures.py", line 802, in _teardown_yield_fixture
    next(it)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/utils_test.py", line 153, in loop
    sleep(0.1)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/client.py", line 4454, in _close_global_client
    c.close(timeout=2)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/client.py", line 1268, in close
    sync(self.loop, self._close, fast=True)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/utils.py", line 292, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x7ff2c7177748>: ConnectionRefusedError: [Errno 111] Connection refused')>
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/comm/tcp.py", line 358, in connect
    ip, port, max_buffer_size=MAX_BUFFER_SIZE, **kwargs
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python3.7/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.7/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/comm/tcp.py", line 370, in connect
    convert_stream_closed_error(self, e)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/comm/tcp.py", line 139, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x7ff2c7177748>: ConnectionRefusedError: [Errno 111] Connection refused
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x7ff2c696a4e0>: ConnectionRefusedError: [Errno 111] Connection refused')>
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/comm/tcp.py", line 358, in connect
    ip, port, max_buffer_size=MAX_BUFFER_SIZE, **kwargs
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python3.7/site-packages/tornado/tcpclient.py", line 232, in connect
    af, addr, stream = yield connector.start(connect_timeout=timeout)
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python3.7/site-packages/tornado/tcpclient.py", line 112, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/comm/tcp.py", line 370, in connect
    convert_stream_closed_error(self, e)
  File "/builddir/build/BUILD/distributed-1.27.1/distributed/comm/tcp.py", line 139, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x7ff2c696a4e0>: ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by QuLogic** [comment]
At least from the stderr output, it seems like the problem is that it connect even when it shouldn't:
```pytb
  File "/builddir/build/BUILD/distributed-1.26.0/distributed/utils_test.py", line 1110, in assert_cannot_connect
    comm.abort()
  File "/usr/lib/python3.7/site-packages/_pytest/python_api.py", line 714, in __exit__
    fail(self.message)
  File "/usr/lib/python3.7/site-packages/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'OSError'>
```
So it's possibly something about #2554, and brokenness for exiting when it fails.

**Comment by QuLogic** [comment]
These have apparently been fixed.
