### ISSUE TITLE
awaiting AioClient created with a cluster fails.

### ISSUE THREAD

**Issue by jonmorton** [dask/distributed#2620]
On latest dask and python 3.7, f I run `await AioClient(cluster)`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jon/finesse/cli/__main__.py", line 5, in <module>
    cli()
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jon/finesse/env/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/jon/finesse/cli/bulk.py", line 34, in shardar_sep
    engine.run(fns.bulk_load_csv(engine, path, shardar_sep_observer))
  File "/home/jon/finesse/fns/engine.py", line 47, in run
    asyncio.run(func)
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/jon/finesse/fns/ingest/csv.py", line 26, in bulk_load_csv
    c = await AioClient(cluster)
  File "/home/jon/finesse/env/lib/python3.7/site-packages/distributed/asyncio.py", line 111, in __await__
    return to_asyncio_future(self._started).__await__()
AttributeError: 'AioClient' object has no attribute '_started'
```

Creating a client without awaiting it sorta works.

**Comment by jonmorton** [comment]
ah, it is because `LocalCluster` also requires an asynchronous=True argument as well. Didn't see that in the example.
