### ISSUE TITLE
Dask Worker launched by CLI hangs after deconnexion with Scheduler

### ISSUE THREAD

**Issue by jjerphan** [dask/distributed#2666]
I am currently having a problem with Workers launched using the [Python API](http://docs.dask.org/en/latest/setup/python-advanced.html).

Workers are launched in a script using:
```python
scheduler_address = os.getenv('DASK_SCHEDULER_ADDRESS')
scheduler_port = os.getenv('DASK_SCHEDULER_PORT', 8687)
death_time_out = os.getenv('DASK_WORKER_DEATH_TIME_OUT', 30)

logging.info("Launching Dask Worker via Python API")

scheduler = "%s:%s" % (scheduler_address, scheduler_port)

worker = Worker(scheduler, death_timeout=death_time_out)
worker.start()

loop = IOLoop.current()
loop.start()

logging.info("Exiting Dask Worker")

sys.exit()
```

Tasks are being executed but as usual but if there is a deconnexion with the distant Scheduler, the Worker hangs and then crash. Here is the following trace:
```
distributed.worker - INFO - Comm closed
distributed.worker - INFO - Waiting to connect to:     tcp://10.12.3.232:8786
distributed.worker - INFO - Waiting to connect to:     tcp://10.12.3.232:8786
distributed.worker - INFO - Waiting to connect to:     tcp://10.12.3.232:8786
distributed.worker - INFO - Stopping worker at tcp://10.12.3.233:43575
tornado.application - ERROR - Exception in Future <tornado.concurrent.Future object at 0x7f3f2d2de750> after timeout
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 970, in error_callback
    future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/distributed/core.py", line 640, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/distributed/core.py", line 753, in connect
    connection_args=self.connection_args)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/distributed/comm/core.py", line 215, in connect
    _raise(error)
  File "/usr/lib/python2.7/site-packages/distributed/comm/core.py", line 195, in _raise
    raise IOError(msg)
IOError: Timed out trying to connect to 'tcp://10.12.3.232:8786' after 10 s: connect() didn't finish in time
```
But the process associated to this script does not return. More precisely, it hangs at:
```python
loop.start()
```

and the next statement, i.e:
```python
logging.info("Exiting Dask Worker")
```
is not executed.

Tornado `IOLoop` provided a way to handle exception before
```python
    def handle_callback_exception(self, callback):
        """This method is called whenever a callback run by the `IOLoop`
        throws an exception.

        By default simply logs the exception as an error.  Subclasses
        may override this method to customize reporting of exceptions.

        The exception itself is not passed explicitly, but is available
        in `sys.exc_info`.

        .. versionchanged:: 5.0

           When the `asyncio` event loop is used (which is now the
           default on Python 3), some callback errors will be handled by
           `asyncio` instead of this method.

        .. deprecated: 5.1

           Support for this method will be removed in Tornado 6.0.
        """
        app_log.error("Exception in callback %r", callback, exc_info=True)
```

but this is not the case anymore.

Is this issue known?

Is there a way to monitor the state of the Worker in some way and exit accordingly?

**Comment by jjerphan** [comment]
[`tornado.ioloop.IOLoop.run_sync`](https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop.run_sync) behavior is interesting because it does handle exception. I am trying to find a way to add such a handling.

**Comment by mrocklin** [comment]
Unfortunately at first glance nothing comes to mind.  At this point what I think would help most would be a minimal test that demonstrates the failure. 

Also, as a warning, please note that the dask.distributed project is likely to drop Python 2 soonish.

**Comment by mrocklin** [comment]
Also I apologize for the long delay in response

**Comment by jjerphan** [comment]
It's fine for the response delay.

I got this error in a quite specific containerised environment.
I'll try to post an example when I can.

**Comment by jjerphan** [comment]
Coming up with the same environment may necessitate some time for me.

I found a workaround to fix this problem : use a watchdog on the current state of the Worker that stops the process when needed i.e. when the connection with the Dask Scheduler is lost and thus when the Worker stops.

This can be done as follows :
```python
scheduler_address = os.getenv('DASK_SCHEDULER_ADDRESS')
scheduler_port = os.getenv('DASK_SCHEDULER_PORT', 8687)
death_time_out = os.getenv('DASK_WORKER_DEATH_TIME_OUT', 30)

scheduler = "%s:%s" % (scheduler_address, scheduler_port)

worker = Worker(scheduler, death_timeout=death_time_out)

pid = os.getpid()

def worker_watchdog():
    """
    A routine that watches the state of the Worker
    that is spawned and that kills it when possible.

    This is used to resolve a teardown problem when
    the connection between the Scheduler and the Worker
    ends.

    :return:
    """
    delay = 2  # seconds

    while True:
        sleep(delay)
        logging.info("Dask Worker status : %s" % worker.status)
        if worker.status in ('closing', 'closed'):
            logging.info("Exiting the Dask Worker via watchdog")
            os.kill(pid, signal.SIGKILL)

worker_watchdog_thread = Thread(target=worker_watchdog)
# We activate the daemon explicitly so that this thread
# is stopped when the main process exits.
# see: https://docs.python.org/2/library/threading.html#threading.Thread.daemon
worker_watchdog_thread.daemon = True

logging.info("Launching Dask Worker via Python API")
worker.start()

logging.info("Launching Worker Watchdog Thread")
worker_watchdog_thread.start()

loop = IOLoop.current()
loop.start()

logging.info("Exiting the Dask Worker normally")
```

Note that the process is killed with:
```python
os.kill(pid, signal.SIGKILL)
```
On my setup, using:
```python
os.kill(pid, signal.SIGTERM)
```
was not working, but you may want to try.
