### ISSUE TITLE
Predict Keras model in a Dask Actor omits "munmap_chunk(): invalid pointer"

### ISSUE THREAD

**Issue by Ireneruru** [dask/distributed#2682]
Hi, we want to predict Keras model in an actor of Dask. And we predict the model batch by batch. 
But it randomly omits the error 

> munmap_chunk(): invalid pointer

in the line 
`                raw = self.model.predict(data)
`
LIke sometimes it omits the error during the 3 iterations and sometimes 16. 

Could you please give any intuition of why this happens. Is Dask compatible with Keras enough?
We would appreciate any help!

And our code is like this:

` def run(self):

        with tf.Graph().as_default():
            with tf.Session() as sess:
                K.set_session(sess)
                self.model = load_model(self.model_path)
                outputs = [self.model.layers[l].output for l in self.layers]
                self.model = Model(inputs = self.model.input, outputs = outputs)
                sub = list(self.subs.keys())[0]
                item = self.subs[sub].get()
                for pub_name in self.pubs:
                    self.pubs[pub_name]['Content'] = {}
                data = item[1]
                indices = item[0]
                raw = self.model.predict(data)
`

**Comment by TomAugspurger** [comment]
A minimal example here would be appreciated. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports.

Are you able to try a similar exercise (predicting in a different thread / processes) using just Python's thread / processes pools?

**Comment by mrocklin** [comment]
Any update here @Ireneruru ?

**Comment by Ireneruru** [comment]
`from dask.distributed import Client

c = Client(n_workers = 1, threads_per_worker = 1)

class KerasActor(object):
    def __init__(self):
        import tensorflow as tf
        from keras.models import Model, load_model
        model = load_model("vgg16_imagenet.h5")
        outputs = [model.layers[47].output]
        self.model = Model(inputs = model.input, outputs = outputs)
        self.model._make_predict_function()

    def run(self):
        import numpy as np
        data = np.zeros((64,224,224,3))
        outputs = self.model.predict(data, batch_size=64)
        return outputs


actor = c.submit(KerasActor, actor=True).result()
while True:
    out = actor.run()
    print(out.result().shape)
    print("OK")
`


This is the short example and error information is as below.

/home/Yiru/.local/lib/python2.7/site-packages/bokeh/themes/theme.py:131: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  json = yaml.load(f)
/home/Yiru/.local/lib/python2.7/site-packages/distributed/bokeh/core.py:74: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn("\n" + msg)
tf.estimator package not installed.
tf.estimator package not installed.
Using TensorFlow backend.
2019-05-10 04:52:54.578704: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-05-10 04:52:55.340259: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-10 04:52:55.340596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2019-05-10 04:52:55.340629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-05-10 04:52:55.705514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-10 04:52:55.705577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-05-10 04:52:55.705586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-05-10 04:52:55.705829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15123 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
(64, 14, 14, 512)
OK
(64, 14, 14, 512)
OK
munmap_chunk(): invalid pointer
tornado.application - ERROR - Exception in callback <functools.partial object at 0x7fe28478e0a8>
Traceback (most recent call last):
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/actor.py", line 156, in wait_then_add_to_queue
    x = yield run_actor_function_on_worker()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/actor.py", line 138, in run_actor_function_on_worker
    kwargs={k: to_serialize(v) for k, v in kwargs.items()},
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/actor.py", line 194, in func
    result = yield self.rpc.proxy(worker=self._address, msg=msg)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/core.py", line 739, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/core.py", line 533, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/comm/tcp.py", line 214, in read
    convert_stream_closed_error(self, e)
  File "/home/Yiru/.local/lib/python2.7/site-packages/distributed/comm/tcp.py", line 141, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
CommClosedError: in <closed TCP>: Stream is closed
distributed.nanny - WARNING - Worker process 19832 was killed by signal 6
distributed.nanny - WARNING - Restarting worker

**Comment by Ireneruru** [comment]
I have solved this issue. The problem is mainly about tensorflow and python2. I changed the python version from 2 to 3. The issue is not here.

**Comment by TomAugspurger** [comment]
Thanks for checking.
