### ISSUE TITLE
clients no longer awaitable on init

### ISSUE THREAD

**Issue by danpf** [dask/distributed#2707]
minimal example
```
import asyncio

from distributed import Client


async def check():
    client = await Client(asynchronous=True)
    print(client)


loop = asyncio.get_event_loop()
loop.run_until_complete(check())
loop.close()
```

the temporary solution is:
```
    client = Client(asynchronous=True)
```

but the `await` style is in the documentation so this would be a breaking change for a lot of people.
http://distributed.dask.org/en/latest/asynchronous.html#basic-operation

can anyone else reproduce this?

**Comment by mrocklin** [comment]
What error occurs for you @danpf ?

**Comment by danpf** [comment]
sorry should have added before.
```
/home/danpf/git/distributed/distributed/bokeh/core.py:57: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)
/home/danpf/git/distributed/distributed/bokeh/core.py:57: UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 883, in callback
    result_list.append(f.result())
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/deploy/local.py", line 259, in _start_worker
    silence_logs=self.silence_logs, **kwargs)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/asyncio/tasks.py", line 599, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/nanny.py", line 158, in _start
    response = yield self.instantiate()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/nanny.py", line 236, in instantiate
    self.process.start()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/nanny.py", line 383, in start
    yield self.process.start()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/git/distributed/distributed/process.py", line 35, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/danpf/git/distributed/distributed/process.py", line 184, in _start
    process.start()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 883, in callback
    result_list.append(f.result())
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/deploy/local.py", line 259, in _start_worker
    silence_logs=self.silence_logs, **kwargs)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/asyncio/tasks.py", line 599, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/nanny.py", line 158, in _start
    response = yield self.instantiate()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/nanny.py", line 236, in instantiate
    self.process.start()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1145, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/danpf/git/distributed/distributed/nanny.py", line 383, in start
    yield self.process.start()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/site-packages/tornado/gen.py", line 1137, in run
    value = future.result()
  File "/home/danpf/git/distributed/distributed/process.py", line 35, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/danpf/git/distributed/distributed/process.py", line 184, in _start
    process.start()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/home/danpf/.local/share/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
````
this goes on for ~20,000 lines

**Comment by mrocklin** [comment]
I recommend that you do a google search for the freeze_support line.
That's a Python and processes thing, not a Dask thing.

**Comment by danpf** [comment]
I'm an Idiot, was importing a bad script, and then my bad minimal example just reinforced idiocy. Sorry.

**Comment by mrocklin** [comment]
You're in good company.  I think we've all made that mistake.
