### ISSUE TITLE
Repeated creation of new Client with new LocalCluster takes longer and longer

### ISSUE THREAD

**Issue by jurajmichalak1** [dask/distributed#2729]
I'm using Dask distributed to parallelize some operations in my service. I need separate processes because of python GIL. My service fails often because Dask client throws following exception:
```
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 639, in __init__
    self.start(timeout=timeout)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 762, in start
    sync(self.loop, self._start, **kwargs)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 850, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 891, in _ensure_connected
    self._update_scheduler_info())
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
tornado.util.TimeoutError: Timeout
```
In my logs I found out that creating cluster and client takes very long (many seconds). What I don't like. So I tested Dask distributed using following simple source in jupyter-notebook and it behaves exactly same as in my service process. First few times Dask LocalCluster and Client is started quite fast but repeating multiple times causes to slow down and finally it starts throwing Timeout exception (default value for Tornado connect is 10s):

```
from dask.distributed import Client, LocalCluster, as_completed
import timeit
timer  = timeit.default_timer

lc, cl, cls = [], [], []
for i in range(15):
    start = timer()
    cluster = LocalCluster(n_workers=20, processes=True, threads_per_worker=1, diagnostics_port=("0.0.0.0", 8787), memory_limit=1048576000)
    duration = round(timer() - start,2)
    print("LocalCluster took {}.".format(duration))
    lc.append(duration)

    start = timer()
    client = Client(cluster)
    duration = round(timer() - start,2)
    print("Client(cluster) took {}.".format(duration))
    cl.append(duration)

    start = timer()
    client.close()
    cluster.close(timeout=6000)
    duration = round(timer() - start,2)
    print("close took {}.".format(duration))
    cls.append(duration)

print("LocalCluster() init: ",lc)
print("Client() init:       ",cl)
print("close:               ",cls)
```

My output is following:
```
LocalCluster() init:  [1.81, 0.99, 0.79, 0.98, 0.93, 1.1, 0.99, 1.34, 1.59, 4.9, 4.47, 6.23]
Client() init:        [0.03, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.02, 16.69, 19.58]
close:                [0.1, 0.1, 0.11, 0.12, 0.14, 0.15, 0.14, 0.22, 0.37, 5.64, 5.73]
```

Do you know what can be the reason of this behavior. It seems that real worker processes are started very fast. How do I enable better logging of Dask to try find out the reason for such slowdown?

I installed lastest conda with:
Python 3.7.3
dask 1.1.4
distributed 1.26.0
tornado 6.0.2

**Comment by TomAugspurger** [comment]
Could you try out distributed master? Locally, I see these times:

```
LocalCluster() init:  [1.46, 0.39, 0.4, 0.4, 0.37, 0.39, 0.4, 0.44, 0.37, 0.39, 0.41, 0.47, 0.42, 0.45, 0.43]
Client() init:        [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.02]
close:                [0.21, 0.19, 0.22, 0.2, 0.2, 0.2, 0.23, 0.2, 0.21, 0.21, 0.22, 0.22, 0.22, 0.26, 0.28]
```

**Comment by jurajmichalak1** [comment]
I tried with master of distributed and behavior was similar to yours. I was very happy but then I executed that loop "for i in range(15):" again in my jupyter notebook (still same process - I did't restart jupyter-notebook python kernel, I just executed same cell again) and it started to throw exceptions:
```
LocalCluster took 0.27.
Client(cluster) took 0.01.
close took 0.15.

distributed.scheduler - ERROR - Error in reevaluate occupancy
Traceback (most recent call last):
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_common.py", line 341, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/faceboard/fix/distributed/distributed/scheduler.py", line 4668, in reevaluate_occupancy
    if self.proc.cpu_percent() < 50:
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/__init__.py", line 1107, in cpu_percent
    pt2 = self._proc.cpu_times()
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1706, in cpu_times
    values = self._parse_stat_file()
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_common.py", line 344, in wrapper
    return fun(self)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1560, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_common.py", line 586, in open_binary
    return open(fname, "rb", **kwargs)
OSError: [Errno 24] Too many open files: '/proc/30008/stat'
--- Logging error ---
tornado.application - ERROR - Exception in callback functools.partial(<bound method Scheduler.reevaluate_occupancy of <Scheduler: "tcp://127.0.0.1:45091" processes: 20 cores: 20>>, worker_index=0)
Traceback (most recent call last):
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_common.py", line 341, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/faceboard/fix/distributed/distributed/scheduler.py", line 4668, in reevaluate_occupancy
    if self.proc.cpu_percent() < 50:
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/__init__.py", line 1107, in cpu_percent
    pt2 = self._proc.cpu_times()
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1706, in cpu_times
    values = self._parse_stat_file()
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1514, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_common.py", line 344, in wrapper
    return fun(self)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_pslinux.py", line 1560, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/psutil/_common.py", line 586, in open_binary
    return open(fname, "rb", **kwargs)
OSError: [Errno 24] Too many open files: '/proc/30008/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/ipykernel/iostream.py", line 97, in _event_pipe
    event_pipe = self._local.event_pipe
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/faceboard/anaconda3/lib/python3.7/logging/__init__.py", line 1037, in emit
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/ipykernel/iostream.py", line 400, in write
    self.pub_thread.schedule(lambda : self._buffer.write(string))
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/ipykernel/iostream.py", line 203, in schedule
    self._event_pipe.send(b'')
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/ipykernel/iostream.py", line 101, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/zmq/sugar/context.py", line 146, in socket
  File "/home/faceboard/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 59, in __init__
    super(Socket, self).__init__(*a, **kw)
  File "zmq/backend/cython/socket.pyx", line 328, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
...
...
```
Funny is that I found I gave you low number for loop repeating 15 :). Because when I changed to 20 it did 15 cycles successfully and than got frozen on 16th execution of loop.

On another machine with older tornado, dask but I checked out latest distributed (master) and it became frozen in execution for longer than 5 minutes (jupyter cell with that loop) and I'm still waiting.

So I have following problems:

1. Why does repeated execution on jupyter notebook of cell with my loop end with exceptions?
2. Why does loop with > range(15) gets frozen after 15 executions?

Thank you in advance.

**Comment by TomAugspurger** [comment]
The "too many open files" sounds like http://distributed.dask.org/en/latest/faq.html?highlight=too%20many%20open%20files#too-many-open-file-descriptors

**Comment by jurajmichalak1** [comment]
Thank you very much for your help. Increasing max open files limit (ulimit -n) fixed my problems.
For better explanation for other people to learn I would add:
```
Closed sockets transit to a TIME_WAIT to make sure that all the data was transmitted during the connection, a final acknowledgment (ACK) should finalize the data transfer. This state delays the release of the file descriptor allocated to it. The duration of this TIME_WAIT period is defined in the kernel parameter named tcp_time_wait _interval on Unix systems.
```
Unfortunately I was using default low limit of open files (1024).
Were you able to reproduce that strange frozen behavior where user is not able to reveal source of the problem "Too many files" or you don't use such low limit for max open files (ulimit -n) on your system?

**Comment by jurajmichalak1** [comment]
FYI: But the problem is different in older version of distributed (1.26) and creation time still raises and ends with TimeoutError. I will test official newest version and use it for deployment of my project.

**Comment by TomAugspurger** [comment]
I'm on a Mac which I think has a higher default limit.
