### ISSUE TITLE
RuntimeError when using ssl security with python

### ISSUE THREAD

**Issue by frthesea** [dask/distributed#2749]
I got the following error when trying to use ssl certificates:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.6/site-packages/distributed/client.py", line 712, in __init__
    self.start(timeout=timeout)
  File ".../python3.6/site-packages/distributed/client.py", line 858, in start
    sync(self.loop, self._start, **kwargs)
  File ".../python3.6/site-packages/distributed/utils.py", line 331, in sync
    six.reraise(*error[0])
  File ".../python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File ".../python3.6/site-packages/distributed/utils.py", line 316, in f
    result[0] = yield future
  File ".../python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File ".../python3.6/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File ".../python3.6/site-packages/distributed/client.py", line 954, in _start
    yield self._ensure_connected(timeout=timeout)
  File ".../python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File ".../python3.6/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File ".../python3.6/site-packages/distributed/client.py", line 1010, in _ensure_connected
    connection_args=self.connection_args,
  File ".../python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File ".../python3.6/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File ".../python3.6/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File ".../python3.6/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File ".../python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File ".../python3.6/site-packages/distributed/comm/tcp.py", line 353, in connect
    self._check_encryption(address, connection_args)
  File ".../python3.6/site-packages/distributed/comm/tcp.py", line 339, in _check_encryption
    "refusing communication from/to %r" % (self.prefix + address,)
RuntimeError: encryption required by Dask configuration, refusing communication from/to 'tcp://127.0.0.1:8786'
```
and the program I used was the following:
```python
from distributed import Client
from distributed.security import Security

sec = Security(tls_ca_file='dask_ca.pem',
               tls_client_cert='dask_cert.pem',
               tls_client_key='dask_key.pem',
               require_encryption=True)

client = Client("127.0.0.1:8786", security=sec)
```

I also tried to start the cluster using command line as mentioned in the documentation:
http://distributed.dask.org/en/latest/tls.html

```bash
dask-scheduler --host ip:8786 --tls-ca-file dask-ca.pem --tls-cert dask-cert.pem --tls-key dask-key.pem
```
and it worked just fine. Is there any reason that the python code was not working?
Thanks

**Comment by TomAugspurger** [comment]
If you change `client = Client("127.0.0.1:8786", security=sec)` to `client = Client("tls://127.0.0.1:8786", security=sec)` (add the `tls://`) it may work. tcp is the default protocol.

**Comment by TomAugspurger** [comment]
@frthesea did you have a chance to try it out with the `tls://` protocol explicitly provided?

**Comment by frthesea** [comment]
Yes, I tested with `tls://` but got connection timeout error, I'm guessing there are some network issues with my machine so I will try solve that and test again. Thanks for your reply!

**Comment by TomAugspurger** [comment]
Thanks. Closing this, but we'll reopen if issue persist.
