### ISSUE TITLE
add_worker() got an unexpected keyword argument 'ncores'

### ISSUE THREAD

**Issue by Kyrremann** [dask/distributed#2818]
I'm having a difficult time trying to figure out what I'm doing wrong.

This is my Jupyter notebook:
```
from dask_kubernetes import KubeCluster

cluster = KubeCluster.from_yaml('pod.yaml')
cluster.scale_up(1)  # specify number of nodes explicitly
```

And when I try to run it I get the following error:
```
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'ncores'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 412, in handle_comm
    result = yield result
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'ncores'
```

I'm running `dask-kubernetes==0.9.0` and `distributed==2.0.1`, but my guess is that one of my libraries are calling an outdated version of the other :/

My `pod.yaml` looks like this:
```
kind: Pod
metadata:
  labels:
    app: dask
spec:
  restartPolicy: Never
  containers:
  - image: customImage
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
    name: dask
```

**Comment by TomAugspurger** [comment]
Can you do `client.get_versions` before the scale up? You're correct that these changed recently, but dask-kubernetest 0.9 should be compatible with distributed 2.x

**Comment by Kyrremann** [comment]
Tried it, and got this. Doesn't look right.
```
<bound method Client.get_versions of <Client: scheduler='tcp://192.168.88.22:42875' processes=0 cores=0>>
```

**Comment by mrocklin** [comment]
```python
client.get_versions()
```

**Comment by Kyrremann** [comment]
Sorry, should have seent that.
```
{'scheduler': {'host': (('python', '3.6.7.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.19.50-coreos-r1'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')),
  'packages': {'required': (('dask', '2.0.0'),
    ('distributed', '2.0.1'),
    ('msgpack', '0.6.1'),
    ('cloudpickle', '0.8.1'),
    ('tornado', '5.1.1'),
    ('toolz', '0.9.0')),
   'optional': (('numpy', '1.16.2'),
    ('pandas', '0.24.2'),
    ('bokeh', '1.2.0'),
    ('lz4', None),
    ('dask_ml', None),
    ('blosc', None))}},
 'workers': {},
 'client': {'host': [('python', '3.6.7.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.19.50-coreos-r1'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')],
  'packages': {'required': [('dask', '2.0.0'),
    ('distributed', '2.0.1'),
    ('msgpack', '0.6.1'),
    ('cloudpickle', '0.8.1'),
    ('tornado', '5.1.1'),
    ('toolz', '0.9.0')],
   'optional': [('numpy', '1.16.2'),
    ('pandas', '0.24.2'),
    ('bokeh', '1.2.0'),
    ('lz4', None),
    ('dask_ml', None),
    ('blosc', None)]}}}
```

**Comment by TomAugspurger** [comment]
OK that all looks good I think.

In the past, I've had trouble with the `imagePullPolicy` caching old images.  Can you try getting a shell on the image that gave the error, and check `dask-worker --version` (that was added in distributed 2.0)

**Comment by Kyrremann** [comment]
Back at work again, the `--version` isn't working. I get `ValueError: missing port number in address 'version'`.

I'v never used Dask before, so it would be strange if I had old images cached on my node.

**Comment by Kyrremann** [comment]
Solved it! I added `dask` and `distributed` as packaged to install in the Docker image. Not sure why the previous listed it as installed :/
