### ISSUE TITLE
SpecCluster fails to scale down

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2836]
When running `cluster.scale(0)` on a `SpecCluster` with one worker I get the following traceback.

```python-traceback
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f0a7af89518>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /home/nfs/jtomlinson/Projects/dask/distributed/distributed/deploy/spec.py:179> exception=KeyError(0)>)
Traceback (most recent call last):
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/deploy/spec.py", line 187, in _correct_state_internal
    await self.scheduler_comm.retire_workers(workers=list(to_close))
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/core.py", line 675, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/core.py", line 550, in send_recv
    six.reraise(*clean_exception(**response))
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 361, in handle_comm
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2825, in retire_workers
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2825, in <setcomp>
KeyError: 0
```

I'm using the branch from #2827.

The `SpecCluster` lists my single worker:

```
cluster.workers
{0: <ECS Task Worker: status=running>}
```

But if I try to list the workers through the scheduler comm I get nothing back

```
await cluster.scheduler_comm.workers()

```

The worker shows in the dashboard and I can send work to it. I just don't seem to be able to kill it.

Any thoughts?

**Comment by quasiben** [comment]
@mrocklin do you have thoughts on what's going on here with SpecCluster ?

**Comment by mrocklin** [comment]
My brief attempts to reproduce this with the following diff didn't work (things still passed)

```diff
diff --git a/distributed/deploy/tests/test_spec_cluster.py b/distributed/deploy/tests/test_spec_cluster.py
index 0c062d3d..c41f57b1 100644
--- a/distributed/deploy/tests/test_spec_cluster.py
+++ b/distributed/deploy/tests/test_spec_cluster.py
@@ -105,6 +105,10 @@ async def test_scale():
         await cluster
         assert len(cluster.workers) == 1

+        cluster.scale(0)
+        await cluster
+        assert not cluster.workers
```

**Comment by jacobtomlinson** [comment]
This seems to be related to my worker name issue from #2879

**Comment by zaccharieramzi** [comment]
@jacobtomlinson I ran into a similar issue, can you explain a bit more what happened and how to fix it?
