### ISSUE TITLE
Failed to deserialize module on EMR

### ISSUE THREAD

**Issue by manugarri** [dask/distributed#2842]
First of all, I apologize if this issue is more related to dask-yarn, I saw similar issues here.

I am running dask-yarn in emr following the bootstrap action provided in the documentation.
Besides that I have a python module named `transforms` (a very simple folder structure with a few .py files) that I package into an egg (that I can import locally with no issue).  This package contains a list of individual tasks to process each row of a dataframe.

I am packaging my transforms module like this:

```
def setup_transforms(transformer):
    dist = setup(
        name="transforms",
        packages=find_packages(include=["transforms", "transforms.*"]),
        version="1.0",
        script_args=["--quiet", "bdist_egg"],
    )
    dist_path = dist.dist_files[0][-1]
    transformer.dask_client.upload_file(dist_path)
```
(transformer is just a class with some business logic on it plus a dask client attribute)

I am trying to use it like this:

```
import dask.dataframe as dd
input = dd.read_json....
for transform in transforms_list:
  output = output.apply(transform, axis=1)
```
When I create my YarnCluster I distribute this egg with `client.upload_file`. When I run the code above and process the output I **sometimes** get the following error in EMR stderr:

```
...
...
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/dask/bag/core.py", line 813, in to_textfiles
    **kwargs
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/dask/bag/core.py", line 275, in to_textfiles
    out.compute(**kwargs)
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/dask/base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/distributed/client.py", line 2527, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/distributed/client.py", line 1823, in gather
    asynchronous=asynchronous,
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/distributed/client.py", line 763, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/distributed/utils.py", line 332, in sync
    six.reraise(*error[0])
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/distributed/client.py", line 1680, in _gather
    six.reraise(type(exception), exception, traceback)
  File "/home/hadoop/miniconda/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
distributed.scheduler.KilledWorker: ("('astype-bag-from-delayed-loads-dumps-to_bag-to-textfiles-10c1b8900a004799b81e4581668d73c5', 5)", <Worker 'tcp://10.0.2.199:41169', memory: 0, processing: 4>)
Command exiting with ret '1'
```

If i check the workers logs I get a bunch of these in one of the workers (and none on the rest):
```
distributed.protocol.pickle - INFO - Failed to deserialize 
...BUNCH OF BYTES 
...
Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1563215017121_0001/container_1563215017121_0001_01_000003/environment/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 61, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'transforms'
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1563215017121_0001/container_1563215017121_0001_01_000003/environment/lib/python3.6/site-packages/distributed/protocol/core.py", line 126, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1563215017121_0001/container_1563215017121_0001_01_000003/environment/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 190, in deserialize
    return loads(header, frames)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1563215017121_0001/container_1563215017121_0001_01_000003/environment/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
    return pickle.loads(b"".join(frames))
  File "/mnt/yarn/usercache/hadoop/appcache/application_1563215017121_0001/container_1563215017121_0001_01_000003/environment/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 61, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'transforms'

```
The weird thing is that this behaviour happens **sometimes**, not always, sometimes the job runs without issue, and it always works with a local client.

This seems to be a recurrent issue  #1341, #344 and #1200

I just want to make sure if this is an issue on my end (im not packaging the module correctly) or if this is a known limitation of dask (as it seems to be hinted by @konrad-roze at #1341

**Comment by manugarri** [comment]
I discovered the reason, answering for future reference.

 The method `upload_file()` is not blocking, which is not an issue for simple files/modules, but my transform module has some dependencies (some s3 downloads) that happen at the global level. This meant by the time the transforms were due to compute, **sometimes** (depending on the speed of s3 downloads) the transforms module hadnt been initialized which means it wasnt available for some of the workers.

To make sure all modules were imported in all workers in a blocking fashion I added a test function to be run on each of the workers:

```
        def test_setup():
            try:
                from transforms import product_transforms
                return len(product_transforms)
            except ModuleNotFoundError:
                pass
```

Then i check this output 


```
        while 1:
            test_result = transformer.dask_client.run(test_setup)
            if all([
                    len(test_result) >= transformer.n_workers,
                    set(test_result.values()) == set([n_transforms])
            ]):
                transformer.log("SETUP TRANSFORMS DONE")
                break
            else:
                transformer.log("SETUP TRANSFORMS NOT DONE, SLEEPING", test_result)
                transformer.log(test_result)
                time.sleep(30)
```
