### ISSUE TITLE
"can not serialize 'Future' object" when putting Future in Queue

### ISSUE THREAD

**Issue by OliverColeman** [dask/distributed#2852]
According to [the docs](https://docs.dask.org/en/latest/futures.html#queues) a `Queue` will accept a `Future`. If I have a Future returned by `Client.scatter()` applied to a "complex" object and attempt to `put()` in a Queue, it fails with `TypeError: can not serialize 'Future' object`, for example:

```python
from dask.distributed import Client, Queue
import numpy as np
daskClient = Client()
queue = Queue()
data = [ np.array([1, 2, 3]) for i in range(3) ]
future = daskClient.scatter(data)
queue.put(future)
```

Is this a bug or am I doing something wrong?

dask 2.1.0
distributed 2.1.0
python 3.6.8

Full error log:
```
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 31, in dumps
    small_header, small_payload = dumps_msgpack(msg)
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 159, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/opt/conda/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 282, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 288, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 261, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Future' object
distributed.comm.utils - ERROR - can not serialize 'Future' object
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 45, in _to_frames
    msg, serializers=serializers, on_error=on_error, context=context
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 31, in dumps
    small_header, small_payload = dumps_msgpack(msg)
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 159, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/opt/conda/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 282, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 288, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 261, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Future' object
Traceback (most recent call last):
  File "/workspace/code/axlearning/misc/testdask.py", line 9, in <module>
    queue.put(future)
  File "/opt/conda/lib/python3.6/site-packages/distributed/queues.py", line 207, in put
    return self.client.sync(self._put, value, timeout=timeout, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 763, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 332, in sync
    six.reraise(*error[0])
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/distributed/queues.py", line 202, in _put
    data=value, timeout=timeout, name=self.name
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 741, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 533, in send_recv
    yield comm.write(msg, serializers=serializers, on_error="raise")
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 237, in write
    context={"sender": self._local_addr, "recipient": self._peer_addr},
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 54, in to_frames
    res = yield offload(_to_frames)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 45, in _to_frames
    msg, serializers=serializers, on_error=on_error, context=context
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 31, in dumps
    small_header, small_payload = dumps_msgpack(msg)
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 159, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/opt/conda/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 282, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 288, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 261, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Future' object
```

**Comment by quasiben** [comment]
@OliverColeman I believe `Queues` are no longer fully supported:
https://distributed.dask.org/en/latest/queues.html?highlight=queue#data-streams-with-queues

Can you add a bit more detail of what you were trying to accomplish with a Queue ?

**Comment by mrocklin** [comment]
Dask queues are still definitely supported.  We just no longer support
Python queues.

You can put individual futures into a queue.  You can also put
msgpack-serializeable data into a queue.  it looks like currently you can't
put complex objects (like the list of futures you have as a result of the
scatter command) into a queue.

**Comment by mrocklin** [comment]
See the docstring here:
```
Init signature: Queue(name=None, client=None, maxsize=0)
Docstring:
Distributed Queue

This allows multiple clients to share futures or small bits of data between
each other with a multi-producer/multi-consumer queue.  All metadata is
sequentialized through the scheduler.

Elements of the Queue must be either Futures or msgpack-encodable data
(ints, strings, lists, dicts).  All data is sent through the scheduler so
it is wise not to send large objects.  To share large objects scatter the
data and share the future instead.
```

and inspect the type of `future` in your example.

**Comment by OliverColeman** [comment]
Okay, I've misunderstood the `scatter()` API, specifically I missed this critical bit: 

> Output type matches input type.

So passing a list returns a list of Futures. Passing a dict returns a dict with Futures as values. Trying to pass these to `Queue.put()` results in msgpack falling over on the embedded Futures. If I wrap the same data in an object instance it works:
```
from dask.distributed import Client, Queue
import numpy as np

class T(object):
    pass    
        
if __name__ == '__main__':
    daskClient = Client()
    queue = Queue()
    data = T()
    data.data = {
        "a": np.array([1, 2]),
        "b": np.array([3, 4]),
    }
    data = daskClient.scatter(data)
    queue.put(data)
    print (queue.get().result().data) # => {'a': array([1, 2]), 'b': array([3, 4])}
```
Now my question is: is there a way to `scatter()` lists and dicts as a single `Future` without having to wrap them in an object instance?

**Comment by mrocklin** [comment]
The magic wrapping only happens once, so try the following:

```python
[future] = client.scatter([list_of_objects])
```

**Comment by OliverColeman** [comment]
It really looks like `scatter()` is returning a Future for every item in a list:
`[future] = client.scatter(['a', 'b'])` results in:
```
Traceback (most recent call last):
  File "misc/testdask.py", line 8, in <module>
    [future] = daskClient.scatter(['a', 'b'])
```
`print(client.scatter(['a', 'b']))` gives: 
`[<Future: status: finished, type: str, key: str-cfea63879ac12dfbea87b362984813f1>, <Future: status: finished, type: str, key: str-78eda4bf88e86fa6d02ecf7927018080>]`

**Comment by mrocklin** [comment]
Right, so if `["a", "b"]` is the object that you want to turn into a future then you would do the following:

```python
[future] = client.scatter([["a", "b"]])
```

**Comment by OliverColeman** [comment]
Ahh I see, that works, thank you very much :)
