### ISSUE TITLE
Queue get timeout logging exception to console even when caught

### ISSUE THREAD

**Issue by OliverColeman** [dask/distributed#2855]
I need to use a short timeout on `Queue.get()`. There doesn't seem to be a way to prevent the exception that is raised by the timeout from being printed to the console, which is unworkable when the timeout is on the order of a second or so...
```
    queue = Queue()
    try:
        item = queue.get(timeout=1)
    except Exception as err:
        pass
```
produces
```
distributed.core - ERROR - 
Traceback (most recent call last):
  File "/home/axl1/.local/lib/python3.5/site-packages/distributed/core.py", line 412, in handle_comm
    result = yield result
  File "/home/axl1/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/axl1/.local/lib/python3.5/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/axl1/.local/lib/python3.5/site-packages/distributed/queues.py", line 131, in get
    record = yield self.queues[name].get(timeout=timeout)
  File "/home/axl1/.local/lib/python3.5/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
tornado.util.TimeoutError
```

**Comment by jcrist** [comment]
Thanks for the excellent issue, I'm able to reproduce.  The log here is coming from in the scheduler, where all exceptions from handlers are logged - I'm not sure if this is intentional or not. @mrocklin, if an RPC method fails and we want to raise the exception on the server, but don't necessarily want to log the exception on the scheduler, is there a standard pattern for that? All handlers I've seen just raise exceptions which are logged then serialized.

**Comment by mrocklin** [comment]
> but don't necessarily want to log the exception on the scheduler, is there a standard pattern for that? 

Not that I know of unfortunately.

**Comment by OliverColeman** [comment]
Is there anything I can easily do from my end at this point to disable these log messages?

**Comment by jcrist** [comment]
Unfortunately there's not much you can easily do. You could silence the logger for `distributed.core`, but that may result in missing import information.
