### ISSUE TITLE
Attribute error when calling SpecCluster.adapt()

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2858]
When calling `cluster.adapt()` on a `SpecCluster` (in this case `FargateCluster` from jacobtomlinson/dask-cloud) I'm getting a traceback error where the adaptive code is trying to talk to the scheduler. 

I think this is a confusion between `scheduler` and `scheduler_comm` in `SpecCluster`. But as the call is not within `SpecCluster` but a level higher in `Cluster` I'm not initially sure how to resolve.

cc @mrocklin 

```python-traceback
In [3]: cluster.adapt(minimum=1, maximum=20)                                                                                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a0f85347b68c> in <module>
----> 1 cluster.adapt(minimum=1, maximum=20)

~/Projects/dask/distributed/distributed/deploy/cluster.py in adapt(self, **kwargs)
     77             self._adaptive_options = {}
     78         self._adaptive_options.update(kwargs)
---> 79         self._adaptive = Adaptive(self.scheduler, self, **self._adaptive_options)
     80         return self._adaptive
     81 

~/Projects/dask/distributed/distributed/deploy/adaptive.py in __init__(self, scheduler, cluster, interval, startup_cost, scale_factor, minimum, maximum, wait_count, target_duration, worker_key, **kwargs)
    120         self.target_duration = parse_timedelta(target_duration)
    121 
--> 122         self.scheduler.handlers["adaptive_recommendations"] = self.recommendations
    123 
    124     def stop(self):

AttributeError: 'Scheduler' object has no attribute 'handlers'

In [4]: tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7ff704708898>>, <Future finished exception=AttributeError("'Scheduler' object has no attribute 'adaptive_target'")>)
Traceback (most recent call last):
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/nfs/jtomlinson/miniconda3/envs/dask-csp/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/deploy/adaptive.py", line 259, in _adapt
    recommendations = self.recommendations()
  File "/home/nfs/jtomlinson/Projects/dask/distributed/distributed/deploy/adaptive.py", line 209, in recommendations
    n = self.scheduler.adaptive_target(target_duration=self.target_duration)
AttributeError: 'Scheduler' object has no attribute 'adaptive_target'
```

**Comment by mrocklin** [comment]
Yup.  It looks like this bit of the code is still assuming that the
scheduler is local.  Instead of directly mutating the scheduler.handlers
state we probably need to either send some signal up to the scheduler, or
have this on all the time.  I'll take a look, but possibly not before early
next week.
