### ISSUE TITLE
Missing dependency: Paramiko 

### ISSUE THREAD

**Issue by hnykda** [dask/distributed#292]
Hello,

when I tried to run cluster, I've got an error about `paramiko` missing. When I installed that, it worked. Hence, I think it should be at least written somewhere in the manual.

```
$ dcluster 127.0.0.1 127.0.0.1 suzanne suzanne
/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

---------------------------------------------------------------
                    Distributed v1.10.2

Worker nodes:
  0: 127.0.0.1
  1: 127.0.0.1
  2: suzanne
  3: suzanne

scheduler node: 127.0.0.1:8786
---------------------------------------------------------------


Exception in thread Thread-15:
Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/distributed/cluster.py", line 31, in async_ssh
    import paramiko
ImportError: No module named 'paramiko'
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/distributed/cluster.py", line 31, in async_ssh
    import paramiko
ImportError: No module named 'paramiko'


Exception in thread Thread-17:
Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/distributed/cluster.py", line 31, in async_ssh
    import paramiko
ImportError: No module named 'paramiko'
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/distributed/cluster.py", line 31, in async_ssh
    import paramiko
ImportError: No module named 'paramiko'
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/mathbs/lib/python3.5/site-packages/distributed/cluster.py", line 31, in async_ssh
    import paramiko
ImportError: No module named 'paramiko'

```

**Comment by mrocklin** [comment]
Sure, can I interest you in writing a small message in the docs and submitting a PR?  OK if not, just trying to tempt you into contributing :)

**Comment by hnykda** [comment]
Well, I could, but I am not sure where it should be. Shouldn't we just put paramiko into `requirements.txt`?

**Comment by mrocklin** [comment]
I hesitate to add a required dependency for a small feature like dcluster.  Many of the larger users prefer to keep the dependency list small.  dcluster and paramiko are optional.
