### ISSUE TITLE
Distributed 2.2.0 Local cluster works ok on small data set, larger data set fails.

### ISSUE THREAD

**Issue by apiszcz** [dask/distributed#2945]
tornado 6.0.3, dask and distributed 2.2.0 on windows

Local system
start with
                cluster = LocalCluster()
                client = Client(cluster)

- monitoring with 8767 with small data set, job completes everything executes and completes.
- using a larger data set i get the following error/stacktrace
- Is there a debugging approach to determine the cause.

```
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
Traceback (most recent call last):
  File "lib\distributed\utils.py", line 180, in ignoring
    yield
  File "lib\distributed\client.py", line 1649, in _gather
    quiet_exceptions=AllExit,
  File "lib\distributed\utils.py", line 218, in All
    result = await tasks.next()
  File "C:\g\testapp\lib\python\lib\asyncio\futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\g\testapp\lib\python\lib\asyncio\tasks.py", line 310, in _wakeup
    future.result()
  File "C:\g\testapp\lib\python\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\g\testapp\lib\python\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "lib\distributed\client.py", line 1641, in wait
    raise AllExit()
distributed.client.AllExit

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "lib\_TESTING\TESTING.py", line 1300, in <module>
    main()
  File "lib\_TESTING\TESTING.py", line 1285, in main
    om2.run(oc, ol, ou, modes, src)
  File "lib\_TESTING\TESTING.py", line 467, in run
    self.create(oc, ol, ou, modes, src)
  File "lib\_TESTING\TESTING.py", line 506, in create
    'f1','f2','f3','f4'].sum().reset_index().compute()
  File "lib\dask\base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "lib\dask\base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "lib\distributed\client.py", line 2511, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "lib\distributed\client.py", line 1811, in gather
    asynchronous=asynchronous,
  File "lib\distributed\client.py", line 752, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "lib\distributed\utils.py", line 327, in sync
    six.reraise(*error[0])
  File "C:\g\testapp\lib\python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "lib\distributed\utils.py", line 312, in f
    result[0] = yield future
  File "lib\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\g\testapp\lib\python\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\g\testapp\lib\python\lib\asyncio\tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "lib\distributed\client.py", line 1667, in _gather
    six.reraise(type(exception), exception, traceback)
  File "C:\g\testapp\lib\python\lib\site-packages\six.py", line 693, in reraise
    raise value
distributed.scheduler.KilledWorker: ("('series-groupby-sum-agg-reset_index-39f993b410b522cfd8542c537a546a4d', 0)", <Worker 'tcp://127.0.0.1:50179', memory: 0, processing: 1>)
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
Traceback (most recent call last):
  File "C:\g\testapp\lib\python\lib\multiprocessing\queues.py", line 236, in _feed
    send_bytes(obj)
  File "C:\g\testapp\lib\python\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\g\testapp\lib\python\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
```

**Comment by TomAugspurger** [comment]
What do you observe on the dashboard?

**Comment by apiszcz** [comment]
on a browser at http://localhost:8787/status

**Comment by TomAugspurger** [comment]
Yes, does anything there stand out?

**Comment by apiszcz** [comment]
not really i can try to record and provide if that would help, it looks fine until the very end and the stack trace appears and no output files are generated.

**Comment by apiszcz** [comment]
![image](https://user-images.githubusercontent.com/1430861/62795129-069f0b00-baa4-11e9-931d-4312d8578cea.png)

**Comment by mrocklin** [comment]
@apiszcz it looks like you might need more help than we're able to provide and still have time to maintain the library.  If you're able to provide a minimal reproducible example (see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) then we can probably help further.  Until then, I can only recommend that you look through some tutorials, and maybe read some documentation about the dashboard.

**Comment by apiszcz** [comment]
ok tx

**Comment by apiszcz** [comment]
noting for the issue
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 25.12 GB -- Worker memory limit: 34.30 GB

**Comment by apiszcz** [comment]
moving where i invoke .compute appears to be narrowing the problem to this statement.
df.goupby(['f1','f2'....])[f10,f11,f12].sum().reset_index.compute()
continuing to test test.
