### ISSUE TITLE
Better handling of tasks that cause the worker to exit

### ISSUE THREAD

**Issue by ogrisel** [dask/distributed#301]
The following seems to hang forever:

```python
>>> from distributed import Executor
>>> import sys
>>> e = Executor('localhost:8786')
>>> e.submit(sys.exit, 1).result()
```

in the background this causes the dscheduler logs to output many errors such as:

```
distributed.scheduler - ERROR - Stream is closed
Traceback (most recent call last):
  File "/home/ogrisel/code/distributed/distributed/scheduler.py", line 1545, in heartbeat
    io_loop=self.loop)
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ogrisel/code/distributed/distributed/core.py", line 439, in send_recv_from_rpc
    result = yield send_recv(stream=stream, op=key, **kwargs)
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ogrisel/code/distributed/distributed/core.py", line 333, in send_recv
    response = yield read(stream)
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ogrisel/code/distributed/distributed/core.py", line 241, in read
    n_frames = yield stream.read_bytes(8)
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/ogrisel/.virtualenvs/py35/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed
```

I think each worker process should have a unique `uuid4` that is passed as a metadata to any Future object returned by those workers and the nannies should report to the scheduler the `uuid4` of any process that crashed when executing a task so that the scheduler can ban those tasks and update the Future objects to mark them as failed with an informative error message instead of hanging for ever.

**Comment by ogrisel** [comment]
A similar issue happens if the submitted function causes a segfault:

```python
>>> from distributed import Executor
>>> from faulthandler import _sigsegv
>>> e.submit(_sigsegv).result()
```

I assume the same would also happen if the submitted task causes the worker process to get killed by the OOM killer of the operating system.

**Comment by mrocklin** [comment]
I agree that we should definitely improve cases like these.

Workers *do* have a unique ID (either uuid or user supplied) and the scheduler does know what workers have what data.  

Banning tasks on worker failure is a bit ambiguous, we would probably only want to ban after multiple workers have died while trying to compute the task.  Otherwise we destroy resilience to worker failure.

**Comment by ogrisel** [comment]
I missed the ID when glancing at the code. Indeed trying a limited number of times before reporting the failure to the caller is a good idea.

**Comment by mrocklin** [comment]
This would probably be an extra dictionary on the scheduler, something like the following in `__init__`:

    self.failures = defaultdict(lambda: 0)

We would increment this for all tasks in `self.processing[address]` when we call `remove_worker` *if* we call it a bad situation (we should probably add a kwarg to `remove_worker` if it is called unexpectedly.)  If a task's failure count grows to some large number (perhaps 3) then we `report` a message down to the client that it failed, perhaps with some custom exception.

I can do this late next week.  I also think it'd be a decent task for you if you're interested in getting into how the scheduler works and if you have spare time (which is, of course, unlikely.)  This touches many pieces of the scheduler, but in a light way.  It would be good to have more developers exposed to how the scheduler works internally.

**Comment by minrk** [comment]
IPython's scheduler has this notion:

- A task has a `retries` property (default: 0)
- If a task fails and has retries left, it is assigned to a new worker (if it failed for other reasons and the worker didn't die, it will never be retried on that worker)
- If an engine dies while running a task, the scheduler injects an artificial "EngineDied" exception and treats that as a regular failure.
- When retries are exhausted, propagate the exception to the user

So the default behavior is that if a worker dies, the user sees that bubble up as an EngineDied exception. If retries is given, then a truly bad task that always segfaults will take down `retries` workers before showing the exception to the user. Under no circumstances should engine death result in hangs for the client.

**Comment by ogrisel** [comment]
Unfortunately I don't think I will have the time to dive into the code in the coming weeks.

**Comment by mrocklin** [comment]
@minrk if retries is given and the exception is more mundane, like `ZeroDivisionError`, will IPyParallel still retry?

**Comment by minrk** [comment]
IPython will, yes, but I'm not sure it should. Engine death is the only case I have encountered in the real world where I have seen a task that should be retried, so handling only that makes the most sense to me, at least as a starting point. I thought some things like temporary resource availability issues might come up, but they don't seem to, so I would probably hold off on supporting that until someone shows up with a real need for it (and a PR!).

**Comment by ogrisel** [comment]
+1
