### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by anaskras** [dask/distributed#3123]
```
(myenv_name) C:\Users\USER_NAME\dask_cluster>dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Local Directory: C:\Users\USER_NAME\AppData\Local\Temp\scheduler-3s6ed687
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://1#.1#.6#.2#:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.utils - ERROR - 'int' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\USER_NAME\.conda\envs\myenv_name\lib\site-packages\distributed\utils.py", line 662, in log_errors
    yield
  File "C:\Users\USER_NAME\.conda\envs\myenv_name\lib\site-packages\distributed\scheduler.py", line 1469, in add_worker
    metrics=metrics,
  File "C:\Users\USER_NAME\.conda\envs\myenv_name\lib\site-packages\distributed\scheduler.py", line 1356, in heartbeat_worker
    self.bandwidth * (1 - frac) + metrics["bandwidth"]["total"] * frac
TypeError: 'int' object is not subscriptable
distributed.core - ERROR - 'int' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\USER_NAME\.conda\envs\myenv_name\lib\site-packages\distributed\core.py", line 403, in handle_comm
    result = await result
  File "C:\Users\USER_NAME\.conda\envs\myenv_name\lib\site-packages\distributed\scheduler.py", line 1469, in add_worker
    metrics=metrics,
  File "C:\Users\USER_NAME\.conda\envs\myenv_name\lib\site-packages\distributed\scheduler.py", line 1356, in heartbeat_worker
    self.bandwidth * (1 - frac) + metrics["bandwidth"]["total"] * frac
TypeError: 'int' object is not subscriptable
```

**Comment by mrocklin** [comment]
I suspect that your scheduler and worker versions are different.  Can you
verify that `distributed.__version__` is the same for each?

**Comment by anaskras** [comment]
I've checked, the version is 2.5.2 for scheduler and workers

**Comment by TomAugspurger** [comment]
I'm a bit confused about the scheduler logs. Do you start any `dask-worker` processes that connect to the scheduler?

**Comment by birdsarah** [comment]
I can confirm that I had this exact problem when I had a scheduler and worker versions different (in my case caused by shipping the wrong conda packed environment when using dask yarn)
