### ISSUE TITLE
Intermittent `distributed.utils - ERROR - 'cpu'`

### ISSUE THREAD

**Issue by andersy005** [dask/distributed#3147]
I just upgraded to the latest distributed/dask versions, and I am getting this intermittent keyError that's difficult to characterize precisely and debug. I was wondering if anyone knows what's the root cause for this issue?

```python
distributed.utils - ERROR - 'cpu'
Traceback (most recent call last):
  File "/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
    yield
  File "/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/dashboard/scheduler.py", line 594, in update
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
  File "/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/dashboard/scheduler.py", line 594, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
KeyError: 'cpu'
distributed.utils - ERROR - 'cpu'
Traceback (most recent call last):
  File "/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
    yield
  File "/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/dashboard/scheduler.py", line 594, in update
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
  File "/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/dashboard/scheduler.py", line 594, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
KeyError: 'cpu'
```

```bash
$ conda list distributed
# packages in environment at /glade/work/abanihi/softwares/miniconda3/envs/analysis:
#
# Name                    Version                   Build  Channel
distributed               2.5.2                      py_0    conda-forge

$ conda list dask
# packages in environment at /glade/work/abanihi/softwares/miniconda3/envs/analysis:
#
# Name                    Version                   Build  Channel
dask                      2.5.2                      py_0    conda-forge
dask-core                 2.5.2                      py_0    conda-forge
dask-jobqueue             0.7.0                      py_0    conda-forge
dask-mpi                  2.0.0                    py37_0    conda-forge
````

**Comment by TomAugspurger** [comment]
Just to verify, `client.get_versions(check=True)` is OK?

**Comment by TomAugspurger** [comment]
https://github.com/dask/distributed/pull/3140 looks related, but it's clear to me that that fixed this.

**Comment by mrocklin** [comment]
I'm taking a look now.  I think I see a way where this could happen.  @andersy005 does this only happen just when a worker comes online?

**Comment by andersy005** [comment]
> does this only happen just when a worker comes online?

It's hard to tell, but I've only noticed the issue when using adaptive scaling.

**Comment by andersy005** [comment]
This issue can be closed. I haven't been able to reproduce this error. So, it might have been fixed :)

**Comment by jrbourbeau** [comment]
Thanks for following up @andersy005! Feel free to re-open if the error pops up again
