### ISSUE TITLE
Hang on dask.array Program with 2 Nodes

### ISSUE THREAD

**Issue by lightsighter** [dask/distributed#3157]
I have a very simple implementation of linear regression (attached, see below) using the dask.array interface that was working a few months ago with Dask 1.14 but I've since upgraded and now it is hanging with Dask 2.6 when I run it on two nodes. If I run on just a single node it works fine. If I go back to Dask 1.14 it also works. I always see the program run at least a few iterations (usually 4-6) before hanging. I flush all stdout calls so I know precisely how far I've made it before things hang.

I'm running on two NVIDIA DGX boxes each of which are connected by both ethernet and Infiniband (it's unclear to me which network is being used for UDP/TCP communication). Both nodes are running Ubuntu 18.04 LTS and have a shared IBM GPFS file system. I'm using python 3.6 from anaconda. I setup my Dask cluster from inside my slurm job as follows:

scontrol show hostname > hostfile.txt
dash-ssh --hostfile hostfile.txt --nthreads 8 --nprocs 1 &

where hostfile.txt contains the network names of the two nodes. I run my program as follows:

python hang_linreg.py -s 1 -i 100 -f 32 -n 100  --cluster $SLURMD_NODENAME:8786 --profile linreg_hang.html

Given that this still works with an older version of Dask, but hangs with the most recent version I'm inclined to believe that the issue is with Dask itself. Please let me know if there is additional information that I can provide to help with debugging.

[hang_linreg.txt](https://github.com/dask/distributed/files/3747644/hang_linreg.txt)

**Comment by quasiben** [comment]
We need a bit more information.  What version of distributed are you using ?  Where is the hang taking place ?  Can you confirm simple dask array operations work on the cluster you've setup ?

**Comment by lightsighter** [comment]
> What version of distributed are you using ?

I said this in the original post. 2.6 hangs, 1.14 works fine.

> Where is the hang taking place ?

It's non-deterministic which dask.array call it hangs in. I've seen it hang in all calls in the main loop.

> Can you confirm simple dask array operations work on the cluster you've setup ?

Yes, the computation always starts running, makes it through the initialization and first few iterations before it hangs.

**Comment by quasiben** [comment]
> I said this in the original post. 2.6 hangs, 1.14 works fine.

Sorry, I was distinguishing between dask and distributed.  

Hangs an be really tricky to debug.  If you can, I would suggest trying with a version between 2.6 and 1.14 and see if where in the version stack the hang manifests

**Comment by lightsighter** [comment]
Aren't they the same thing? One is just a sub module of the other. If you track versions for those differently then please point me at website that shows downloads for each of the different versions you want me to try.

**Comment by quasiben** [comment]
Distributed and dask are intimately related but distributed is not a submodule of dask.   You can see dask releases [here](https://github.com/dask/dask/releases) and distributed releases [here](https://github.com/dask/distributed/releases) .  Can you report back the versions of dask and distributed you are using:

> pip freeze | grep 'dask\|distributed'

**Comment by jrbourbeau** [comment]
@lightsighter could you try looking through the scheduler and worker logs to see if anything stands out? Note you may need to [increase the logging verbosity](https://docs.dask.org/en/latest/configuration.html#specify-configuration) to get the needed information

**Comment by lightsighter** [comment]
(py36) mbauer:/gpfs/fs1/mbauer$ pip freeze | grep 'dask'
dask==2.6.0
(py36) mbauer:/gpfs/fs1/mbauer$ pip freeze | grep 'distributed'
distributed==2.6.0

What is the division of responsibilities between the dask and the distributed modules? Do you have some tests with dask.array that run on distributed in your CI?

I checked that my ~/.config/dask/distributed.yml file has logging set to "info", but my call to dask-ssh doesn't dump anything to standard error, so as far as I can tell nothing is being logged by the output. Is there something I can pass on the command line to cause logging to be dumped verbosely? It's also unclear to me that dask is even finding my home directory because my home directory is not mounted on the compute nodes (as is common on most supercomputers), only the GPFS file system is available on the compute nodes. This hasn't been a problem in the past and I doubt it is a problem now. I also looked in the worker directories but they just had a single 'storage' sub directory and nothing else in them.

**Comment by TomAugspurger** [comment]
Distributed is one of Dask’s schedulers. 

https://docs.dask.org/en/latest/configuration.html documents where dask looks for config. You can also use the environment variable style. Dask-jobqueue may be worth looking into if it’s applicable to your system.

**Comment by lightsighter** [comment]
What is the environment variable(s) that Dask uses to configure its logging output levels? The only two that I see listed on that page are these:

> export DASK_DISTRIBUTED__SCHEDULER__WORK_STEALING=True
> export DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES=5

I don't see any links that point to a list of all the environment variables that Dask accepts and Google search does not reveal a list either.

**Comment by lightsighter** [comment]
Ok, it looks like there is some sort of weird scheme in the environment variable parser that converts environment variables to something analogous to the YAML file, but I still can't find a full spec for the YAML grammar that you accept.

**Comment by TomAugspurger** [comment]
The rules are at https://docs.dask.org/en/latest/configuration.html

> Dask searches for all environment variables that start with DASK_, then transforms keys by converting to lower case and changing double-underscores to nested structures.

So something like `DASK_DISTRIBUTED__LOGGING__DISTRIBUTED=DEBUG` should work.

**Comment by lightsighter** [comment]
Attached is a log file from a hung run. It includes both the call to dask-ssh and the call to run my linear regression example.
[dask.log](https://github.com/dask/distributed/files/3771049/dask.log)

**Comment by TomAugspurger** [comment]
Do simple computations like

```
def inc(x):
    return x + 1

client.map(inc, range(100))
```

work?

**Comment by lightsighter** [comment]
Yes that works fine:

`(py36) mbauer@prm-dgx-32:/gpfs/fs1/mbauer/Legate/examples/dask/temp$ cat ../test.py 

from dask.distributed import Client

def inc(x):
    return x + 1

client = Client("prm-dgx-32:8786")
client.map(inc, range(100))
(py36) mbauer@prm-dgx-32:/gpfs/fs1/mbauer/Legate/examples/dask/temp$ python ../test.py
(py36) mbauer@prm-dgx-32:/gpfs/fs1/mbauer/Legate/examples/dask/temp$ [ scheduler prm-dgx-32:8786 ] : distributed.scheduler - INFO - Receive client connection: Client-b85269c0-f7bc-11e9-b901-a81e84f29b65
[ scheduler prm-dgx-32:8786 ] : distributed.core - INFO - Starting established connection
[ scheduler prm-dgx-32:8786 ] : distributed.scheduler - INFO - Remove client Client-b85269c0-f7bc-11e9-b901-a81e84f29b65
[ scheduler prm-dgx-32:8786 ] : distributed.scheduler - INFO - Remove client Client-b85269c0-f7bc-11e9-b901-a81e84f29b65
[ scheduler prm-dgx-32:8786 ] : distributed.scheduler - INFO - Close client connection: Client-b85269c0-f7bc-11e9-b901-a81e84f29b65`

You did see the errors in the logfile yesterday right?

`[ worker prm-dgx-11 ] :     raise IOError(msg)
[ worker prm-dgx-11 ] : OSError: Timed out trying to connect to 'tcp://127.0.1.1:44491' after 10 s: Timed out trying to connect to 'tcp://127.0.1.1:44491' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x7f8d50657ba8>: ConnectionRefusedError: [Errno 111] Connection refused
[ worker prm-dgx-11 ] : distributed.worker - INFO - Can't find dependencies for key ('sum-sum-aggregate-1b912898a2a51eb040ec908c5cfa5359', 0)
[ worker prm-dgx-11 ] : distributed.worker - INFO - Dependent not found: ('zeros-51f8e95ae264899e0f4e52b67cd69ca2', 0) 0 .  Asking scheduler
[ worker prm-dgx-11 ] : distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.1.1:44491`

**Comment by lightsighter** [comment]
Is there something else I can be trying here or reporting in order to figure out what is causing this hang? Some of my work is currently completely blocked by this hang.

**Comment by jrbourbeau** [comment]
I see you're getting an timeout `OSError`, is it possible there's some sort of network connection issue?

**Comment by lightsighter** [comment]
dask-ssh started up the cluster fine. Also MPI and GASNet both work fine and they use a service called PMI to bootstrap themselves which involves running UDP over the same ethernet cables that Dask should be using. Remember also that Dask 1.14 still works too on the very same machine.

**Comment by jrbourbeau** [comment]
I'm not sure what next steps should be taken for further debugging. Perhaps @mrocklin or @TomAugspurger have thoughts on how to proceed?

**Comment by mrocklin** [comment]
Looking briefly at the log here

```
[ scheduler prm-dgx-11:8786 ] : distributed.scheduler - INFO - Receive client connection: Client-317fc1d4-f6fe-11e9-942c-a81e84cca6e5
[ scheduler prm-dgx-11:8786 ] : distributed.core - INFO - Starting established connection
[ worker prm-dgx-11 ] : distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.1.1:44491
[ worker prm-dgx-11 ] : Traceback (most recent call last):
[ worker prm-dgx-11 ] :   File "/gpfs/fs1/mbauer/anaconda2/envs/py36/lib/python3.6/site-packages/distributed/comm/core.py", line 221, in connect
[ worker prm-dgx-11 ] :     _raise(error)
[ worker prm-dgx-11 ] :   File "/gpfs/fs1/mbauer/anaconda2/envs/py36/lib/python3.6/site-packages/distributed/comm/core.py", line 204, in _raise
[ worker prm-dgx-11 ] :     raise IOError(msg)
[ worker prm-dgx-11 ] : OSError: Timed out trying to connect to 'tcp://127.0.1.1:44491' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x7f8d50657ba8>: ConnectionRefusedError: [Errno 111] Connection refused

```

It looks like it's trying to connect to localhost for some reason.  You might want to try setting the network interface with the `--interface` keyword.  (assuming that this is supported in dask-ssh)

**Comment by lightsighter** [comment]
This version of dask-ssh doesn't support an interface option:

```
(py36) $ dask-ssh --version
dask-ssh, version 2.6.0
(py36) $ dask-ssh --help
Usage: dask-ssh [OPTIONS] [HOSTNAMES]...

  Launch a distributed cluster over SSH. A 'dask-scheduler' process will run
  on the first host specified in [HOSTNAMES] or in the hostfile (unless
  --scheduler is specified explicitly). One or more 'dask-worker' processes
  will be run each host in [HOSTNAMES] or in the hostfile. Use command line
  flags to adjust how many dask-worker process are run on each host
  (--nprocs) and how many cpus are used by each dask-worker process
  (--nthreads).

Options:
  --scheduler TEXT           Specify scheduler node.  Defaults to first
                             address.
  --scheduler-port INTEGER   Specify scheduler port number.  [default: 8786]
  --nthreads INTEGER         Number of threads per worker process. Defaults to
                             number of cores divided by the number of
                             processes per host.
  --nprocs INTEGER           Number of worker processes per host.  [default:
                             1]
  --hostfile PATH            Textfile with hostnames/IP addresses
  --ssh-username TEXT        Username to use when establishing SSH
                             connections.
  --ssh-port INTEGER         Port to use for SSH connections.  [default: 22]
  --ssh-private-key TEXT     Private key file to use for SSH connections.
  --nohost                   Do not pass the hostname to the worker.
  --log-directory PATH       Directory to use on all cluster nodes for the
                             output of dask-scheduler and dask-worker
                             commands.
  --remote-python TEXT       Path to Python on remote nodes.
  --memory-limit TEXT        Bytes of memory that the worker can use. This can
                             be an integer (bytes), float (fraction of total
                             system memory), string (like 5GB or 5000M),
                             'auto', or zero for no memory management
                             [default: auto]
  --worker-port INTEGER      Serving computation port, defaults to random
  --nanny-port INTEGER       Serving nanny port, defaults to random
  --remote-dask-worker TEXT  Worker to run.  [default:
                             distributed.cli.dask_worker]
  --version                  Show the version and exit.
  --help                     Show this message and exit.
```

In my current dask-ssh invocation I'm using the `--hostfile`, `--nthreads`, and `--nprocs` options. As far as I can tell, dask-ssh runs correctly and doesn't report any errors. The timeout errors only start once I actually begin running a client that connects to the cluster. My ssh-keys are already set up and I can ssh-between all the nodes without needing to type in any passwords.

**Comment by lightsighter** [comment]
What is the next thing for me to try?

**Comment by mrocklin** [comment]
You could try the `dask.distributed.SSHCluster` Python class, which is more fully featured.

Also cc'ing @JohnZed and @trivialfis , both of whom I think have successfully used the system that you're trying to use.

You could also try https://mpi.dask.org

**Comment by trivialfis** [comment]
Sorry I never actually use this one.  At first I just do everything manually with all little bit help from srun.  Now I sometimes work with the jobqueue library.

**Comment by trivialfis** [comment]
I can share my jobqueue config if you like.

**Comment by lightsighter** [comment]
@mrocklin dask.distributed.SSHCluster hangs the same way that it does using dask-ssh. The code starts running, makes progress for a few iterations, and then hangs. I tried using dask-mpi back in March but could never figure out what goes in the scheduler.json file. Everything I try caused Dask to crash. I don't remember the details.

@trivialfis I'll ping you on the NVIDIA slack to get your script.

**Comment by mrocklin** [comment]
> but could never figure out what goes in the scheduler.json file

Nothing goes there.  The Dask scheduler process writes to that file and the
workers read from it.

**Comment by lightsighter** [comment]
I talked with @trivialfis some more. His job scripts all do single node jobs, not multi-node jobs. He often runs many of them in parallel, but they aren't being directed by a single client.

I will try dask-mpi tomorrow.

Is there anyway I can break into a debugger and poke around for you guys to figure out what is going wrong? All this just trying different things feels kind of pointless like we're taking random shots in the dark to figure out what is going wrong and not trying to root cause the problem.

**Comment by mrocklin** [comment]
> I talked with @trivialfis some more. His job scripts all do single node jobs, not multi-node jobs. He often runs many of them in parallel, but they aren't being directed by a single client.

Given that he's working on dask-xgboost I find this a little bit surprising.  Are you sure that they aren't single node jobs that are all connecting to a centralized scheduler?  This is how dask-jobqueue works.

> Is there anyway I can break into a debugger and poke around for you guys to figure out what is going wrong? All this just trying different things feels kind of pointless like we're taking random shots in the dark to figure out what is going wrong and not trying to root cause the problem.

Yes, unfortunately that's commonly the way of things with large HPC machines.  They tend to have made custom networking and NFS choices which make diagnosing issues much more specific to the machine at hand.  When you use MPI these decisions have all been made by the infrastructure maintainers.  When you don't there are many more available options.  

Here is an example of a more painful experience with Summit: https://blog.dask.org/2019/08/28/dask-on-summit

If you can get access to a couple of compute nodes some time I'd be happy to jump on a screenshare with you and try to diagnose networking issues.

**Comment by trivialfis** [comment]
Sorry the the ambiguity.  That script was me simply modifying the demo from local cluster to job queue cluster when I was reached.  Previously for benchmarking I manually perform the connection by launching scheduler and workers by hand.  
At some point using jobqueue with n processes works with correct all reduce result after altering network interface.  But I tried to reproduce it yesterday it hangs for no reason.

**Comment by mrocklin** [comment]
Do you still have the lines you used to manually start the dask-scheduler
and dask-worker commands?  Those might help out.

**Comment by trivialfis** [comment]
I will flag the email and try it tomorrow again at work.(I can't connect it from home without a Windows machine...)  Thanks for the patience.

**Comment by trivialfis** [comment]
Nope.  Couldn't allocate any node today.

**Comment by trivialfis** [comment]
@mrocklin @lightsighter For normal usage, I just login with many ssh connections, launch scheduler with one of them:
```
dask-scheduler --scheduler-file=scheduler.json
```
And in other terminals (ssh login virtual shell):
```
srun dask-cuda-worker --scheduler-file=scheduler.json
```
Possibly with threads and memory configuration.  This is a screenshot that dask loading a huge csv file with pandas as backend:
![Screenshot from 2019-11-12 11-14-50](https://user-images.githubusercontent.com/16746409/68638838-c38a8300-053d-11ea-885d-e70b9c8a42e5.png)

**Comment by trivialfis** [comment]
Feel free to reach me if I can be of further assistance.
