### ISSUE TITLE
Scheduler traceback using latest win64 Anaconda.

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#316]
Getting this traceback when I start a scheduler on a windows host and try to connect to it from a linux workstation. 

~~~
distributed.core - ERROR - No module named 'backports_abc'
Traceback (most recent call last):
  File "C:\anaconda\lib\site-packages\distributed\core.py", line 206, in handle_
stream
    result = yield gen.maybe_future(handler(stream, **msg))
  File "C:\anaconda\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\anaconda\lib\site-packages\tornado\concurrent.py", line 232, in resul
t
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\anaconda\lib\site-packages\tornado\gen.py", line 282, in wrapper
    yielded = next(result)
  File "C:\anaconda\lib\site-packages\distributed\scheduler.py", line 1565, in f
eed
    setup = pickle.loads(setup)
ImportError: No module named 'backports_abc'
~~~

**Comment by mrocklin** [comment]
Do both systems have the same libraries installed and run under the same versions of Python?

**Comment by nfaggian** [comment]
OK I think the problem is as you suggest, different versions of python and also the library.

**Comment by mrocklin** [comment]
OK, that would certainly explain things.  Closing for now.  Please reopen if the problem persists.
