### ISSUE TITLE
daskdev/dask:latest docker image won't start dask-scheduler

### ISSUE THREAD

**Issue by ceberly** [dask/distributed#3167]
Using the latest docker image for daskdev/dask:latest the `dask-scheduler` command will not start because of the addition of this line:

 https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L885

As you can see below, `dask.config.get("distributed.scheduler.bandwidth")` results in an integer value (`100000000`) and the subsequent call to `parse_bytes` fails. This is confirmed on os x docker and azure container services.

```
% docker pull daskdev/dask:latest
latest: Pulling from daskdev/dask
Digest: sha256:bfa86b3df452ec5f4a010b53bd03650e3deabddf066576a70610e72a06021beb
Status: Image is up to date for daskdev/dask:latest

% docker run --rm -it daskdev/dask:latest  bash

-- add print statement to line 885
(base) root@42d1778bdd1f:/# vim /opt/conda/lib/python3.7/site-packages/distributed/scheduler.py 
(base) root@42d1778bdd1f:/# dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
100000000
Traceback (most recent call last):
  File "/opt/conda/bin/dask-scheduler", line 10, in <module>
    sys.exit(go())
  File "/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_scheduler.py", line 241, in go
    main()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_scheduler.py", line 218, in main
    **kwargs
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 886, in __init__
    self.bandwidth = parse_bytes(dask.config.get("distributed.scheduler.bandwidth"))
  File "/opt/conda/lib/python3.7/site-packages/dask/utils.py", line 1164, in parse_bytes
    s = s.replace(" ", "")
AttributeError: 'int' object has no attribute 'replace'
```

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue @ceberly! I've opened a PR to update the dask docker images to `dask==2.6.0` (the latest release) which should resolve the issue you're seeing

**Comment by jrbourbeau** [comment]
With the updates to `dask-docker`, I'm able to run `dask-scheduler` inside a `daskdev/dask:latest` container without getting the `AttributeError` 👍 

@ceberly I'm going to close this issue, but feel free to re-open if problems persist

**Comment by ceberly** [comment]
Works now, thank you @jrbourbeau and company for the quick fix!
