### ISSUE TITLE
LRU dumps_function error

### ISSUE THREAD

**Issue by anishkej** [dask/distributed#3176]
I know this is a very vague error, but I'm using SGECluster from dask_jobqueue. This used to work for me when I was on dask=1.2.2, distributed=1.28.1

Any ideas?  I've included the full exception and all my installed packages.  Thanks!

```Traceback (most recent call last):
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/worker.py", line 3156, in dumps_function
    result = cache[func]
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/zict/lru.py", line 48, in __getitem__
    result = self.d[key]
KeyError: <function bar at 0x7ff5a37e3b90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 41, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 505, in save_module
    if _is_dynamic(obj):
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1379, in _is_dynamic
    pkgpath = parent.__path__
AttributeError: module 'pyfoo.foo' has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bar.py", line 609, in <module>
    main(sys.argv[1:])
  File "bar.py", line 589, in main
    scFv_tasks = [client.submit(bar, *args) for args in arguments]
  File "bar.py", line 589, in <listcomp>
    scFv_tasks = [client.submit(bar, *args) for args in arguments]
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/client.py", line 1452, in submit
    actors=actor,
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/client.py", line 2426, in _graph_to_futures
    "tasks": valmap(dumps_task, dsk3),
  File "cytoolz/dicttoolz.pyx", line 179, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 204, in cytoolz.dicttoolz.valmap
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/worker.py", line 3193, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/worker.py", line 3158, in dumps_function
    result = pickle.dumps(func)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/foo/anaconda3/envs/foo/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 505, in save_module
    if _is_dynamic(obj):
  File "/foo/anaconda3/envs/foo/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1379, in _is_dynamic
    pkgpath = parent.__path__
AttributeError: module 'pyfoo.foo' has no attribute '__path__'
```

Also, here are the versions of all of my packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
blosc                     1.16.3               hd408876_0
bokeh                     1.3.4                    py37_0
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py37_1
click                     7.0                      py37_0
cloudpickle               1.2.2                      py_0
cytoolz                   0.10.0           py37h7b6447c_0
dask                      2.3.0                      py_0
dask-core                 2.3.0                      py_0
dask-jobqueue             0.6.3                      py_0    conda-forge
decorator                 4.4.0                    py37_1
distributed               2.3.2                      py_1
docrep                    0.2.7                      py_0    conda-forge
freetype                  2.9.1                h8a8886c_1
fsspec                    0.4.0                      py_0
h5py                      2.9.0            py37h7918eee_0
hdf5                      1.10.4               hb1b8bf9_0
heapdict                  1.0.0                    py37_2
intel-openmp              2019.4                      243
ipykernel                 5.1.2            py37h39e3cac_0
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.15.1                   py37_0
jinja2                    2.10.1                   py37_0
jpeg                      9b                   h024ee3a_2
jupyter_client            5.3.1                      py_0
jupyter_core              4.5.0                      py_0
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.0.10               h2733197_2
locket                    0.2.0                    py37_1
lz4-c                     1.8.1.2              h14c3975_0
markupsafe                1.1.1            py37h7b6447c_0
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.14           py37ha843d7b_0
mkl_random                1.0.2            py37hd81dba3_0
msgpack-python            0.6.1            py37hfd86e86_1
ncurses                   6.1                  he6710b0_1
numpy                     1.16.5           py37h7e9f1db_0
numpy-base                1.16.5           py37hde5b4d6_0
olefile                   0.46                     py37_0
openssl                   1.1.1d               h7b6447c_1
packaging                 19.1                     py37_0
pandas                    0.25.1           py37he6710b0_0
parso                     0.5.1                      py_0
partd                     1.0.0                      py_0
pexpect                   4.7.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.1.0            py37h34e0f95_0
pip                       19.2.2                   py37_0
prompt_toolkit            2.0.9                    py37_0
psutil                    5.6.3            py37h7b6447c_0
ptyprocess                0.6.0                    py37_0
pygments                  2.4.2                      py_0
pyparsing                 2.4.2                      py_0
python                    3.7.4                h265db76_1
python-blosc              1.7.0            py37h7b6447c_0
python-dateutil           2.8.0                    py37_0
pytz                      2019.2                     py_0
pyyaml                    5.1.2            py37h7b6447c_0
pyzmq                     18.1.0           py37he6710b0_0
readline                  7.0                  h7b6447c_5
scipy                     1.3.1            py37h7c811a0_0
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0
snappy                    1.1.7                hbae5bb6_3
sortedcontainers          2.1.0                    py37_0
sqlite                    3.29.0               h7b6447c_0
tblib                     1.4.0                      py_0
tk                        8.6.8                hbc83047_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37h7b6447c_0
traitlets                 4.3.2                    py37_0
wcwidth                   0.1.7                    py37_0
wheel                     0.33.4                   py37_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.3.1                he6710b0_3
zict                      1.0.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0
```

**Comment by TomAugspurger** [comment]
What is `pyfoo.foo`? Can it / it's contents be pickled with `cloudpickle.dumps`?

**Comment by jrbourbeau** [comment]
Just checking in here @anishkej, could you provide more information about what `pyfoo.foo` is? Are you able to serialize it or it's contents with `cloudpickle.dumps`?

**Comment by jrbourbeau** [comment]
Closing for now. @anishkej feel free to re-open this issue if you're able to provide more information or a minimal example (https://blog.dask.org/2018/02/28/minimal-bug-reports)
