### ISSUE TITLE
UnBoundLocalError when using the --no-bokeh flag

### ISSUE THREAD

**Issue by mackaiver** [dask/distributed#318]
Not sure if this is the same issue as #269 but I'll post it here anyways. 
As the title states I get an error when executing without bokeh

```
[awesomeuser@bestcluster ~]$dscheduler --port 12801 --no-bokeh
distributed.scheduler - INFO - Scheduler at:       10.194.169.142:12801
distributed.scheduler - INFO -      http at:       10.194.169.142:9786
^CTraceback (most recent call last):
  File "/home/guest/kbruegge/anaconda3/bin/dscheduler", line 6, in <module>
    sys.exit(distributed.cli.dscheduler.go())
  File "/home/guest/kbruegge/anaconda3/lib/python3.5/site-packages/distributed/cli/dscheduler.py", line 109, in go
    main()
  File "/home/guest/kbruegge/anaconda3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/guest/kbruegge/anaconda3/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/guest/kbruegge/anaconda3/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/guest/kbruegge/anaconda3/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/guest/kbruegge/anaconda3/lib/python3.5/site-packages/distributed/cli/dscheduler.py", line 102, in main
    bokeh_proc.terminate()
UnboundLocalError: local variable 'bokeh_proc' referenced before assignment
distributed.scheduler - INFO - Remove client None
```

This happens whenever I exit the process. Pressing ctrl+c or similar.

**Comment by mrocklin** [comment]
Are you on master or on the latest release?

**Comment by mackaiver** [comment]
Hi, 
I'm on release `distributed==1.10.2` on PyPi.

**Comment by mrocklin** [comment]
I believe that this is fixed on master, which should be released in week or two.  Try the following until then

    pip install git+https://github.com/dask/distributed.git --upgrade

**Comment by mrocklin** [comment]
A newer version of dask.distributed with this fixed has been released.  Closing.  Please reopen if the problem persists.
