### ISSUE TITLE
cannot set WRITEABLE flag to True of this array

### ISSUE THREAD

**Issue by dcherian** [dask/distributed#3252]
My colleague is seeing the following error on distirbuted 2.8.0. It looks related to #3180 and this set of lines

https://github.com/dask/distributed/blob/35551998d7350cd5ae6a5c24970d8437fd8d521d/distributed/protocol/numpy.py#L110-L114

```
distributed.worker - INFO - Start worker at: tcp://10.12.205.19:34307

distributed.worker - INFO - Listening to: tcp://10.12.205.19:34307

distributed.worker - INFO - dashboard at: 10.12.205.19:34094

distributed.worker - INFO - Waiting to connect to: tcp://128.117.181.211:37309

distributed.worker - INFO - -------------------------------------------------

distributed.worker - INFO - Threads: 1

distributed.worker - INFO - Memory: 25.00 GB

distributed.worker - INFO - Local Directory: /glade/scratch/deppenme/dask-tmp/worker-k05sxxku

distributed.worker - INFO - -------------------------------------------------

distributed.worker - INFO - Registered to: tcp://128.117.181.211:37309

distributed.worker - INFO - -------------------------------------------------

distributed.worker - ERROR - cannot set WRITEABLE flag to True of this array 

Traceback (most recent call last): File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/worker.py", line 894, in handle_scheduler comm, every_cycle=[self.ensure_communicating, self.ensure_computing] File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/core.py", line 447, in handle_stream msgs = await comm.read() File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/comm/tcp.py", line 208, in read frames, deserialize=self.deserialize, deserializers=deserializers 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/comm/utils.py", line 63, in from_frames res = await offload(_from_frames) File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/utils.py", line 1371, in offload return await loop.run_in_executor(_offload_executor, fn, *args, **kwargs) File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/comm/utils.py", line 51, in _from_frames frames, deserialize=deserialize, deserializers=deserializers File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads value = _deserialize(head, fs, deserializers=deserializers) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize return loads(header, frames) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 54, in dask_loads return loads(header, frames) 
File "/glade/work/deppenme/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/protocol/numpy.py",
 line 113, in deserialize_numpy_ndarray x.setflags(write=writeable) ValueError: cannot set WRITEABLE flag to True of this array
```

This is coming out of a complicated analysis pipeline with xarray, zarr and dask so we don't have a minimal example yet. We could work to find one if you have some pointers on what to look for.

**Comment by TomAugspurger** [comment]
Just to clarify, this doesn't happen with distributed 2.7.0?

**Comment by dcherian** [comment]
Yes. i just confirmed that the same code works with 2.7.0

**Comment by TomAugspurger** [comment]
Thanks. cc @jrbourbeau if you have any guesses on this.

**Comment by jrbourbeau** [comment]
Thanks for reporting @dcherian, this is indeed a bug introduce in #3180. Looks like arrays cannot be set to writeable if they don't own their memory and their underlying base object is read-only (to avoid writing to readonly memory).

Here's an example which works fine prior to the changes in #3180, but fails with `ValueError: cannot set WRITEABLE flag to True of this array` after those changes are included:

```python
import numpy as np
from distributed.protocol import serialize, deserialize

x = np.arange(3)
# Create zero-strided array
y = np.broadcast_to(x, (3, 3))

assert x.flags.writeable == True     # arange produces writeable arrays
assert y.flags.writeable == False    # broadcase_to produces read-only arrays

# Make y writeable and it's base object (x) read-only
y.setflags(write=True)
x.setflags(write=False)

# Serialize / deserialize y
z = deserialize(*serialize(y))
```

Any idea if this situation pops up in your workflow @dcherian? I'm looking for a fix now

**Comment by dcherian** [comment]
Hmmm.. i just looked over my colleague's code. There's a lot of broadcasting multiplications and divisions happening so my answer is "quite likely maybe" ;)

Sorry I can't help more.

**Comment by TomAugspurger** [comment]
@jrbourbeau for a fix, when we serialize we might skip this optimization with the `x.base.flags.writable` is False? That check for `.base` may need to be done recursively, if you have a writable view of a writable view of a readonly array...

FWIW, I find it strange that you can do

```python
x.setflags(write=False)
```

when there are writable views on `x` but that's probably a larger issue :)

**Comment by mrocklin** [comment]
This might be a good time to use git bisect

**Comment by mrocklin** [comment]
Ah, sorry, that e-mail went out later than expected.  It sounds like you
all have already found the cause.

**Comment by jrbourbeau** [comment]
Unfortunately there are some...interesting cases where we can't rely on inspecting the flags of the underlying `base` object

```python
In [1]: import numpy as np

In [2]: x = np.array([10, 20, 30, 40, 50])

In [3]: y = np.lib.stride_tricks.as_strided(x, strides=(0,) + x.strides, shape=(3,) + x.shape)

In [4]: y
Out[4]:
array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [5]: y.base
Out[5]: <numpy.lib.stride_tricks.DummyArray at 0x10a17c828>

In [6]: y.base.flags
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-9b5d815436a4> in <module>
----> 1 y.base.flags

AttributeError: 'DummyArray' object has no attribute 'flags'
```

It looks like we can pass `shape` directly to `np.ndarray` and it will handle any needed broadcasting and flags appropriately. That actually allows us to simplify the code added in #3180. I'll push an update to #3253 for review
