### ISSUE TITLE
Simultaneous --lifetime shutdown led to errors

### ISSUE THREAD

**Issue by simaster123** [dask/distributed#3257]
It looks like, in trying to gracefully shutdown two workers at the same time, the scheduler tried to move data from one of the to-be-restarted workers to the other to-be-restarted worker.  This led to various errors and the two workers didn't recover.  See my logs below.  A worker at server 192.168.0.152 and a worker at 192.168.0.167 were both being shutdown simultaneously.

Apologies, that this is a hard one to create an MCVE for.

2019-11-21 22:11:31,540 - INFO - 192.168.0.152 ssh - distributed.worker - INFO - Closing worker gracefully: tcp://192.168.0.152:39595
2019-11-21 22:11:34,498 - INFO - 192.168.0.167 ssh - distributed.worker - INFO - Closing worker gracefully: tcp://192.168.0.167:34425
2019-11-21 22:11:34,710 - INFO - 192.168.0.152 ssh - distributed.worker - INFO - Stopping worker at tcp://192.168.0.152:39595
2019-11-21 22:11:34,826 - INFO - 192.168.0.152 ssh - distributed.worker - INFO - Comm closed
2019-11-21 22:11:34,829 - INFO - 192.168.0.152 ssh - distributed.worker - WARNING - Could not find data: {"('read-parquet-5e4f95d26b332bf3f3cc415c1f946e99', 127)": ['tcp://192.168.0.167:34425']} on workers: ['tcp://192.168.0.167:34425'] (who_has: {"('read-parquet-5e4f95d26b332bf3f3cc415c1f946e99', 127)": ['tcp://192.168.0.167:34425']})
2019-11-21 22:11:35,432 - INFO - 192.168.0.167 ssh - distributed.worker - ERROR - failed during get data with tcp://192.168.0.167:34425 -> tcp://192.168.0.152:39595
2019-11-21 22:11:35,434 - INFO - 192.168.0.167 ssh - Traceback (most recent call last):
2019-11-21 22:11:35,436 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 184, in read
2019-11-21 22:11:35,438 - INFO - 192.168.0.167 ssh -     n_frames = await stream.read_bytes(8)
2019-11-21 22:11:35,441 - INFO - 192.168.0.167 ssh - tornado.iostream.StreamClosedError: Stream is closed
2019-11-21 22:11:35,443 - INFO - 192.168.0.167 ssh - 
2019-11-21 22:11:35,446 - INFO - 192.168.0.167 ssh - During handling of the above exception, another exception occurred:
2019-11-21 22:11:35,450 - INFO - 192.168.0.167 ssh - 
2019-11-21 22:11:35,452 - INFO - 192.168.0.167 ssh - Traceback (most recent call last):
2019-11-21 22:11:35,459 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/worker.py", line 1204, in get_data
2019-11-21 22:11:35,461 - INFO - 192.168.0.167 ssh -     response = await comm.read(deserializers=serializers)
2019-11-21 22:11:35,462 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 204, in read
2019-11-21 22:11:35,469 - INFO - 192.168.0.167 ssh -     convert_stream_closed_error(self, e)
2019-11-21 22:11:35,475 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 132, in convert_stream_closed_error
2019-11-21 22:11:35,477 - INFO - 192.168.0.167 ssh -     raise CommClosedError("in %s: %s" % (obj, exc))
2019-11-21 22:11:35,483 - INFO - 192.168.0.167 ssh - distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
2019-11-21 22:11:35,848 - INFO - 192.168.0.152 ssh - distributed.nanny - INFO - Worker closed
2019-11-21 22:11:36,396 - INFO - 192.168.0.152 ssh - distributed.nanny - WARNING - Restarting worker

2019-11-21 22:11:37,465 - INFO - 192.168.0.167 ssh - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f9c6ee3c6a0>>, <Task finished coro=<Worker.close_gracefully() done, defined at /home/dan/.local/lib/python3.7/site-packages/distributed/worker.py:1101> exception=CommClosedError('in <closed TCP>: Stream is closed')>)
2019-11-21 22:11:37,468 - INFO - 192.168.0.167 ssh - Traceback (most recent call last):
2019-11-21 22:11:37,469 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 184, in read
2019-11-21 22:11:37,471 - INFO - 192.168.0.167 ssh -     n_frames = await stream.read_bytes(8)
2019-11-21 22:11:37,473 - INFO - 192.168.0.167 ssh - tornado.iostream.StreamClosedError: Stream is closed
2019-11-21 22:11:37,480 - INFO - 192.168.0.167 ssh - 
2019-11-21 22:11:37,482 - INFO - 192.168.0.167 ssh - During handling of the above exception, another exception occurred:
2019-11-21 22:11:37,485 - INFO - 192.168.0.167 ssh - 
2019-11-21 22:11:37,487 - INFO - 192.168.0.167 ssh - Traceback (most recent call last):
2019-11-21 22:11:37,489 - INFO - 192.168.0.167 ssh -   File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 743, in _run_callback
2019-11-21 22:11:37,491 - INFO - 192.168.0.167 ssh -     ret = callback()
2019-11-21 22:11:37,494 - INFO - 192.168.0.167 ssh -   File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 767, in _discard_future_result
2019-11-21 22:11:37,496 - INFO - 192.168.0.167 ssh -     future.result()
2019-11-21 22:11:37,498 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/worker.py", line 1115, in close_gracefully
2019-11-21 22:11:37,500 - INFO - 192.168.0.167 ssh -     await self.scheduler.retire_workers(workers=[self.address], remove=False)
2019-11-21 22:11:37,503 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/core.py", line 748, in send_recv_from_rpc
2019-11-21 22:11:37,505 - INFO - 192.168.0.167 ssh -     result = await send_recv(comm=comm, op=key, **kwargs)
2019-11-21 22:11:37,509 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/core.py", line 531, in send_recv
2019-11-21 22:11:37,511 - INFO - 192.168.0.167 ssh -     response = await comm.read(deserializers=deserializers)
2019-11-21 22:11:37,514 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 204, in read
2019-11-21 22:11:37,517 - INFO - 192.168.0.167 ssh -     convert_stream_closed_error(self, e)
2019-11-21 22:11:37,519 - INFO - 192.168.0.167 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 132, in convert_stream_closed_error
2019-11-21 22:11:37,521 - INFO - 192.168.0.167 ssh -     raise CommClosedError("in %s: %s" % (obj, exc))
2019-11-21 22:11:37,522 - INFO - 192.168.0.167 ssh - distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
2019-11-21 22:11:38,953 - INFO - 192.168.0.167 ssh - distributed.worker - INFO - Comm closed

**Comment by mrocklin** [comment]
Hrm, I wonder if it would suffice to put an `asyncio.Lock` around the `Scheduler.retire_workers` function, to make sure that it wasn't called concurrently with itself.  Any interest in trying this out?

**Comment by mrocklin** [comment]
I've tried this here: https://github.com/dask/distributed/pull/3259

**Comment by mrocklin** [comment]
@simaster123 does that PR resolve your problem?
