### ISSUE TITLE
closed connection? 

### ISSUE THREAD

**Issue by Casyfill** [dask/distributed#3272]
I am running Dask Cluster on k8s, and just bumped to daskdev/dask:2.8.0 for scheduler,
custom image with the below specs for workers.

```
- dask=2.8.1
- distributed=2.8.1 
- dask-glm=0.2.0
- dask-kubernetes=0.9.2
- dask-ml=1.1.1
- dask-xgboost=0.1.9
```

Both are running python 3.7. My client has the same settings and python, and code below does not show any issues
```python
client = Client('tcp://dask-adaptive-scheduler.staging2.mydomain.cloud:8786')
client.get_versions(check=True);
```

But when I run the `dask_ml.model_selection.RandomizedSearchCV`, my dashboard shows there is no workers. When I check pods, there is a worker called dask-adaptive-dask-workerttlcv, which throws the error below in stdout:
```
tornado.application - ERROR - Exception in callback <function Worker._register_with_scheduler.<locals>.<lambda> at 0x7f8bb81779d8>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 855, in <lambda>
    lambda: self.batched_stream.send({"op": "keep-alive"}),
  File "/opt/conda/lib/python3.7/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
```

where should I dig? 
Previous version, dask=2.4.0, worked fine with the same k8s settings

**Comment by mrocklin** [comment]
Did you resolve this @Casyfill ?  If so, what was the problem?

**Comment by Casyfill** [comment]
Well, that one seemed to be just a  stale worker from the previous version and I hoped that killing it will fix everything. I do have a worker now, but scheduler has this in the logs:

```
distributed.utils - ERROR - 'coroutine' object is not subscriptable
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 663, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/shared.py", line 380, in update
    data = profile.plot_data(self.state, profile_interval)
  File "/opt/conda/lib/python3.7/site-packages/distributed/profile.py", line 232, in plot_data
    traverse(state, 0, 1, 0)
  File "/opt/conda/lib/python3.7/site-packages/distributed/profile.py", line 195, in traverse
    if not state["count"]:
TypeError: 'coroutine' object is not subscriptable
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f37bbf68fd0>>, <Future finished exception=TypeError("'coroutine' object is not subscriptable")>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/opt/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/shared.py", line 409, in <lambda>
    self.doc().add_next_tick_callback(lambda: self.update(prof, metadata))
  File "/opt/conda/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 97, in func
    return input_function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/shared.py", line 380, in update
    data = profile.plot_data(self.state, profile_interval)
  File "/opt/conda/lib/python3.7/site-packages/distributed/profile.py", line 232, in plot_data
    traverse(state, 0, 1, 0)
  File "/opt/conda/lib/python3.7/site-packages/distributed/profile.py", line 195, in traverse
    if not state["count"]:
TypeError: 'coroutine' object is not subscriptable
/opt/conda/lib/python3.7/site-packages/bokeh/util/callback_manager.py:155: RuntimeWarning: coroutine 'Scheduler.get_profile_metadata' was never awaited
  def invoke():
/opt/conda/lib/python3.7/site-packages/bokeh/document/document.py:483: RuntimeWarning: coroutine 'Scheduler.get_profile' was never awaited
```

**Comment by Casyfill** [comment]
and it seems this blocks scheduler from proceeding with actual job

**Comment by mrocklin** [comment]
I suspect that you were on master.  you might want to pull again (as of a few hours ago) or better yet, walk back to the latest release.

**Comment by mrocklin** [comment]
that seems like a different error regardless though.  It seems like the original issue here was a non-issue.  I'm going to close this.  If you think that you've come across something new, the let's raise a new issue.

**Comment by Casyfill** [comment]
Thanks!

Just to make sure Which master are you referring to? Couse I only use official `daskdev/dask` image, which I suspecd wasn't updated to 2.8.1 😬

**Comment by mrocklin** [comment]
Then I must be incorrect.
