### ISSUE TITLE
WindowsError on dscheduler - no bokeh.bat file

### ISSUE THREAD

**Issue by philastrophist** [dask/distributed#328]
So having the conda installation of `distributed` fail with another `WindowsError`, I have run `pip install git+https://github.com/dask/distributed.git --upgrade` to get the hopefully corrected version. 

However, running `dscheduler` results in:

```
distributed.scheduler - INFO - Scheduler at:       192.168.112.81:8786
distributed.scheduler - INFO -      http at:       192.168.112.81:9786
distributed.scheduler - WARNING - Could not start Bokeh web UI
Traceback (most recent call last):
  File "C:\Users\User\Anaconda\lib\site-packages\distributed\cli\dscheduler.py", line 92, in main
    bokeh_proc = subprocess.Popen(args)
  File "C:\Users\User\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\User\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Inserting my one `.bat` script:
```
@echo off
set PYFILE=%~f0
set PYFILE=%PYFILE:~0,-4%-script.py
"%~f0\..\..\python.exe" "%PYFILE%" %*
```
does not work. Instead it complains that it can't find the bokeh-script.py

**Comment by mrocklin** [comment]
Do you have bokeh installed?  Do things stop working entirely?

**Comment by philastrophist** [comment]
I reinstalled bokeh and now it seems to work. Thanks
