### ISSUE TITLE
Assertion error in graceful close when using lifetime flag

### ISSUE THREAD

**Issue by simaster123** [dask/distributed#3286]
I got the error below.  This seems to happen randomly.  Many nodes restart fine.  The error prevents the worker from restarting in the cluster.

I launch the workers using paramiko and the following command (including the workers on the scheduler node):

            stdin, stdout, stderr = ssh_client.exec_command('sudo dask-worker ' +
                                                            ' --name ' + comp_name +
                                                            ' --memory-limit 0 ' +
                                                            ' --nprocs 10 ' +
                                                            ' --nthreads 1 ' +
                                                            ' --local-directory ' + local_dir + ' ' +
                                                            ' --lifetime \'' 1200 seconds\' ' +
                                                            ' --lifetime-stagger \'10 minutes\' ' +
                                                            ' --lifetime-restart ' +
                                                            ' tcp://' + dask_scheduler_ip, get_pty=True)

The error I get:

```
2019-11-29 15:10:36,213 - INFO - 192.168.0.164 ssh - distributed.worker - INFO - Closing worker gracefully: tcp://192.168.0.165:33745
2019-11-29 15:10:49,629 - WARNING - 192.168.0.164 ssh - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fed0803b8d0>>, <Task finished coro=<Worker.close_gracefully() done, defined at /home/dan/.local/lib/python3.7/site-packages/distributed/worker.py:1108> exception=AssertionError()>)
2019-11-29 15:10:49,630 - WARNING - 192.168.0.164 ssh - Traceback (most recent call last):
2019-11-29 15:10:49,631 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
2019-11-29 15:10:49,633 - WARNING - 192.168.0.164 ssh -     ret = callback()
2019-11-29 15:10:49,634 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
2019-11-29 15:10:49,635 - WARNING - 192.168.0.164 ssh -     future.result()
2019-11-29 15:10:49,636 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/worker.py", line 1122, in close_gracefully
2019-11-29 15:10:49,638 - WARNING - 192.168.0.164 ssh -     await self.scheduler.retire_workers(workers=[self.address], remove=False)
2019-11-29 15:10:49,639 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/core.py", line 749, in send_recv_from_rpc
2019-11-29 15:10:49,640 - WARNING - 192.168.0.164 ssh -     result = await send_recv(comm=comm, op=key, **kwargs)
2019-11-29 15:10:49,641 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/core.py", line 548, in send_recv
2019-11-29 15:10:49,643 - WARNING - 192.168.0.164 ssh -     raise exc.with_traceback(tb)
2019-11-29 15:10:49,644 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/core.py", line 404, in handle_comm
2019-11-29 15:10:49,645 - WARNING - 192.168.0.164 ssh -     result = await result
2019-11-29 15:10:49,646 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/scheduler.py", line 3147, in retire_workers
2019-11-29 15:10:49,648 - WARNING - 192.168.0.164 ssh -     delete=False,
2019-11-29 15:10:49,649 - WARNING - 192.168.0.164 ssh -   File "/home/dan/.local/lib/python3.7/site-packages/distributed/scheduler.py", line 2909, in replicate
2019-11-29 15:10:49,650 - WARNING - 192.168.0.164 ssh -     assert count > 0
2019-11-29 15:10:49,652 - WARNING - 192.168.0.164 ssh - AssertionError
```

**Comment by jacobtomlinson** [comment]
Before we dig into this have you tried the built-in `dask-ssh` support? https://docs.dask.org/en/latest/setup/ssh.html

**Comment by mrocklin** [comment]
Closing due to lack of response.  @simaster123 if you come back to this let us know and we'll reopen.
