### ISSUE TITLE
KeyError: 'snappy' while running on dask remote cluster

### ISSUE THREAD

**Issue by karims** [dask/distributed#3317]
I am running the following code on remote Dask cluster:

```
from timeit import default_timer as timer
from dask.distributed import Client, as_completed
import dask.dataframe as dd

client = Client('x.x.x.x:8786') #  I use the actual scheduler IP which is remote
storage_options = {
        'client_kwargs': {'aws_access_key_id': 'xxx', 'aws_secret_access_key': 'yyy', 'endpoint_url': 'some-url-aws'},
        'use_ssl': False
     }
pq_loc = 's3://file/location/sample_pq_files/'

df = dd.read_parquet(pq_loc, engine='pyarrow', index=False, storage_options=storage_options)
client.persist(df)

flat_list = [12.0805, 13.8588] # will filter out rows which contain these values

# want to pass this function to cluster to compute for each column
def gen_boundaries(col_name):
    df_filtered = df[~df[col_name].isin(flat_list)]
    corr = df[col_name].corr(df_filtered['target'])
    return corr
futures = client.map(gen_boundaries, ['var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5','var_6', 'var_7', 'var_8', 'var_9'])

start = timer()
for future in as_completed(futures):
    y = future.result()
    print(client.compute(y).result())
end = timer()
print('~~~~ time for gathering futures', end-start)
```

I get the following error:

``` 
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/protocol/core.py", line 130, in loads
    fs = decompress(head, fs)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/protocol/compression.py", line 185, in decompress
    for c, frame in zip(header['compression'], frames)]
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/protocol/compression.py", line 185, in <listcomp>
    for c, frame in zip(header['compression'], frames)]
KeyError: 'snappy'
Traceback (most recent call last):
  File "/Users/apple/Library/Preferences/PyCharmCE2018.1/scratches/scratch_6.py", line 43, in <module>
    y = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/client.py", line 193, in result
    raiseit=False)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/client.py", line 675, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/client.py", line 218, in _result
    result = yield self.client._gather([self])
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/client.py", line 1522, in _gather
    response = yield future
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/client.py", line 1571, in _gather_remote
    response = yield self.scheduler.gather(keys=keys)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/core.py", line 580, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/core.py", line 457, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 207, in read
    deserializers=deserializers)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/comm/utils.py", line 82, in from_frames
    res = _from_frames()
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/comm/utils.py", line 68, in _from_frames
    deserializers=deserializers)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/protocol/core.py", line 130, in loads
    fs = decompress(head, fs)
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/protocol/compression.py", line 185, in decompress
    for c, frame in zip(header['compression'], frames)]
  File "/Users/apple/PycharmProjects/daskrecipies/venv/lib/python3.6/site-packages/distributed/protocol/compression.py", line 185, in <listcomp>
    for c, frame in zip(header['compression'], frames)]
KeyError: 'snappy'

Process finished with exit code 1

```

versions used:
tornado              5.1.1  
dask                 2.8.1               
dask-glm             0.2.0               
dask-ml              1.0.0               
dask-xgboost         0.1.7  

Running actual code from Mac. The scheduler and workers are in Cent OS.

**Comment by karims** [comment]
Also I have `python-snappy==0.5.4` on my local as well as same version in scheduler/workers.

**Comment by TomAugspurger** [comment]
What does `client.get_versions(check=True)` report?

**Comment by karims** [comment]
@TomAugspurger : Thank you. I resolved it. I had to do `brew install snappy` on my mac for this to work. `pip install python-snappy` did not help.

**Comment by TomAugspurger** [comment]
Good to hear.
