### ISSUE TITLE
Dask client.persist returns AssertionError when I try to use HashingVectorizer

### ISSUE THREAD

**Issue by DoDzilla-ai** [dask/distributed#3342]
**dask = 2.9.0 
dask-core = 2.9.0 
dask-glm = 0.2.0 
dask-ml = 1.1.1 
distributed = 2.9.0** 
I am trying to vectorize the dask.dataframe with dask HashingVectorizer. I want the vectorization results to stay in the cluster (distributed system). That's why I am using client.persist when I try to transform the data. But for some reason, I am getting the error below.
```
Traceback (most recent call last):
  File "/home/dodzilla/.PyCharm2019.3/config/scratches/scratch_5.py", line 42, in <module>
    fitted_vectorizer = client.persist(vectorizer.fit(combined_data))
  File "/home/dodzilla/.local/lib/python3.6/site-packages/distributed/client.py", line 2860, in persist
    assert all(map(dask.is_dask_collection, collections))
AssertionError
```
A minimal working example can be found below.
```
from stop_words import get_stop_words
from dask_ml.feature_extraction.text import HashingVectorizer as daskHashingVectorizer
import pandas as pd
import dask
import dask.dataframe as dd
from dask.distributed import Client


def convert_dataframe_to_single_text(documents):
    """
    Combine all of the columns into 1 column.
    """
    if type(documents) is dask.dataframe.core.DataFrame:
        cols = documents.columns
        documents['combined'] = documents[cols].apply(func=(lambda row: ' '.join(row.values.astype(str))), axis=1,
                                                      meta=('str'))
        document_texts = documents.drop(cols, axis=1)
    else:
        raise TypeError('Wrong type of data. Expected Pandas DF or Dask DF but received ', type(documents))
    return document_texts

# Init the client.
client = Client('localhost:8786')

# Get stopwords
stopwords = get_stop_words(language="english")

# Create dask dataframe from pandas dataframe
data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':["twenty", "twentyone", "nineteen", "eighteen"]}
df = pd.DataFrame(data)
df = dd.from_pandas(df, npartitions=1)

# Init the vectorizer
vectorizer = daskHashingVectorizer(stop_words=stopwords, alternate_sign=False,
                       norm=None, binary=False,
                       n_features=10000)

# Combine all of to columns into 1 column.
combined_data = convert_dataframe_to_single_text(df)

# Fit the vectorizer.
fitted_vectorizer = client.persist(vectorizer.fit, combined_data)

# Transform the data.
X = client.persist(fitted_vectorizer.transform, combined_data)
```

**Comment by DoDzilla-ai** [comment]
I guess that is not how you use persist.

**Comment by DoDzilla-ai** [comment]
Yup. I was completely wrong. I was confused with the submit, map and persist. Sorry.
