### ISSUE TITLE
Failure to restart LocalCluster workers - pickle error

### ISSUE THREAD

**Issue by adamklein** [dask/distributed#3345]
I am getting a failure on `client.restart()` where the nanny cannot create new processes after it kills the extant ones. It gives a similar error with both `spawn` and `forkserver` multiprocessing methods.  The `restart` is invoked from the driver host while the cluster is executing a collection of computations where tasks are executing and awaiting other tasks.

Unfortunately I can't reproduce in isolation apart from my specific workflow yet. It seems that an `_asyncio.Future` object which is not pickleable might be getting into the multiprocessing message queue somehow.

```
distributed 2.8.1
cloudpickle 1.2.2 
tornado 6.0.3
python 3.6.9
```

```
2019-12-26 17:13:44,582 816305-140151724717824 [WARNING] distributed.nanny nanny.py:616 | Worker process still alive after 1 seconds, killing
2019-12-26 17:13:44,583 816305-140151724717824 [WARNING] distributed.nanny nanny.py:616 | Worker process still alive after 1 seconds, killing
2019-12-26 17:13:44,590 816305-140151724717824 [ERROR] distributed.core core.py:410 | can't pickle _asyncio.Future objects
Traceback (most recent call last):
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 404, in handle_comm
    result = await result
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 346, in restart
    await gen.with_timeout(timedelta(seconds=timeout), _())
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 343, in _
    await self.instantiate()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 522, in start
    await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 202, in _start
    process.start()
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _asyncio.Future objects
2019-12-26 17:13:44,595 816305-140151724717824 [ERROR] distributed.core core.py:410 | can't pickle _asyncio.Future objects
Traceback (most recent call last):
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 404, in handle_comm
    result = await result
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 346, in restart
    await gen.with_timeout(timedelta(seconds=timeout), _())
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 343, in _
    await self.instantiate()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 522, in start
    await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 202, in _start
    process.start()
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _asyncio.Future objects
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=CommClosedError("in <closed TCP>: Stream is closed: while trying to call remote method 'restart'",)>
Traceback (most recent call last):
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/comm/tcp.py", line 186, in read
    lengths = await stream.read_bytes(8 * n_frames)
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/iostream.py", line 436, in read_bytes
    future = self._start_read()
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/iostream.py", line 797, in _start_read
    self._check_closed()  # Before reading, check that stream is not closed.
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/iostream.py", line 1009, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 678, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 532, in send_recv
    response = await comm.read(deserializers=deserializers)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/comm/tcp.py", line 204, in read
    convert_stream_closed_error(self, e)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/comm/tcp.py", line 132, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/utils.py", line 237, in quiet
    yield task
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/gen.py", line 735, in run
    value = future.result()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 681, in send_recv_from_rpc
    "%s: while trying to call remote method %r" % (e, key)
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'restart'
2019-12-26 17:13:44,598 816305-140151724717824 [ERROR] distributed.utils utils.py:668 | can't pickle _asyncio.Future objects
Traceback (most recent call last):
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/utils.py", line 663, in log_errors
    yield
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/scheduler.py", line 2634, in restart
    resps = await gen.with_timeout(timedelta(seconds=timeout), resps)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/utils.py", line 224, in All
    result = await tasks.next()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 678, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 548, in send_recv
    raise exc.with_traceback(tb)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 404, in handle_comm
    result = await result
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 346, in restart
    await gen.with_timeout(timedelta(seconds=timeout), _())
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 343, in _
    await self.instantiate()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 522, in start
    await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 202, in _start
    process.start()
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _asyncio.Future objects
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f779dc593c8>>, <Task finished coro=<Scheduler.restart() done, defined at .../distributed/2/8/1/dist/lib/python3.6/distributed/scheduler.py:2585> exception=TypeError("can't pickle _asyncio.Future objects",)>)
Traceback (most recent call last):
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File ".../tornado/6/0/3/dist/lib/python3.6/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/scheduler.py", line 2634, in restart
    resps = await gen.with_timeout(timedelta(seconds=timeout), resps)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/utils.py", line 224, in All
    result = await tasks.next()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 678, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 548, in send_recv
    raise exc.with_traceback(tb)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/core.py", line 404, in handle_comm
    result = await result
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 346, in restart
    await gen.with_timeout(timedelta(seconds=timeout), _())
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 343, in _
    await self.instantiate()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/nanny.py", line 522, in start
    await self.process.start()
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File ".../distributed/2/8/1/dist/lib/python3.6/distributed/process.py", line 202, in _start
    process.start()
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _asyncio.Future objects
Traceback (most recent call last):
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
Traceback (most recent call last):
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File ".../3/6/x/dist/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
2019-12-26 17:14:12,959 816305-140151724717824 [ERROR] distributed.client client.py:2903 | Restart timed out after 30.000000 seconds
```

**Comment by mrocklin** [comment]
Hi @adamklein !  Indeed, this seems like a bug.  Nothing pops out at me though as to what might be going wrong.  I would probably need more information to be of any use here.

**Comment by adamklein** [comment]
This arose after an upgrade from tornado 4.x to 6.x. Looks like in version 5, they unified tornado `tornado.concurrent.Future` with `asyncio.Future`. And I do see that the implementation of `AsyncProcess` from `distributed/process.py` has a `self._exit_future = Future()`, which might be why `ForkingPickler` cannot dump `obj` (which is an instance of `AsyncProcess`), but then the mystery is why does it work at all (ie, cannot  reproduce)

**Comment by mrocklin** [comment]
I'm curious why it feels the need to serialize a Future object in the first place.  Are we actually passing in such a Future object to the `Process`?  Is this in some side-state that we're closing over accidentally?

**Comment by adamklein** [comment]
So this only happens when using a LocalCluster and after a task has thrown an exception. I still cannot cleanly reproduce, but I can work around by scaling the local cluster down to zero workers and then back up to the original number!

**Comment by adamklein** [comment]
Can't repro, found other workaround.

**Comment by jtlz2** [comment]
@adamklein What was the other workaround?

**Comment by fjetter** [comment]
@jtlz2 if you are encountering a similar problem, I encourage you raising a new ticket.
