### ISSUE TITLE
tuple indices must be integers or slides, not str

### ISSUE THREAD

**Issue by seanlaw** [dask/distributed#3362]
I'm running the following code for STUMPY that leverages Dask:

```
import stumpy as mp
import numpy as np
from dask.distributed import Client
import socket

if __name__ == '__main__':
     hostname = socket.getfqdn()
     client = Client(f'tcp://{hostname}:8786')
     client.restart()
     x = np.random.rand(1000)
     out = mp.stumped(client, x, 50, ignore_trivial=True)
     print(out)
```

This works on a local cluster on the same server but it fails with the following error when distributed across multiple servers:

```
distributed.scheduler - INFO - Receive client connection: Client-53672f58-33c6-11ea-86d1-005056a5c48b
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Send lost future signal to clients
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.157.167.164:33754', name: tcp://10.157.167.164:33754, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://10.157.167.164:33754
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.157.167.187:34416', name: tcp://10.157.167.187:34416, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://10.157.167.187:34416
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.157.167.187:42130', name: tcp://10.157.167.187:42130, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.157.167.187:42130
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.157.167.164:46525', name: tcp://10.157.167.164:46525, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.157.167.164:46525
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Clear task state
distributed.scheduler - ERROR - tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 4036, in transition_processing_memory
    for startstop in startstops
  File "/app/home/miniconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 4037, in <listcomp>
    if startstop["action"] == "compute"
TypeError: tuple indices must be integers or slices, not str
distributed.scheduler - ERROR - Error transitioning '_stump-4fbcc3aaa1fcd54085907321a2a09f44' from 'processing' to 'memory'
Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 4561, in transition
    recommendations = func(key, *args, **kwargs)
  File "/app/home/miniconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 4036, in transition_processing_memory
    for startstop in startstops
  File "/app/home/miniconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 4037, in <listcomp>
    if startstop["action"] == "compute"
TypeError: tuple indices must be integers or slices, not str
distributed.core - ERROR - tuple indices must be integers or slices, not str
```

The servers for the distributed cluster (2 servers with 8 CPUs each) is each instantiated with:

```
nohup dask-worker --nprocs 1 --nthreads 8 some_host_name:8786
```

It's been a while since I've touched the distributed cluster but I also just did a `conda update dask distributed` on all of the servers.

**Comment by mrocklin** [comment]
My guess is that you have a version mismatch between your workers and
client.  Can you verify that the versions of distributed are the same
everywhere?

You might try client.get_versions(check=True)  (this is now on by default
in master)

**Comment by seanlaw** [comment]
@mrocklin You are probably right, and by now, I should know better :D

I'll try resetting everything

**Comment by seanlaw** [comment]
As a repeat offender, I am ashamed. My recidivism rate for committing this offense is too high. Thanks. Closing.

**Comment by mrocklin** [comment]
It's our fault for not telling you that this is going on.  Master should be
better from now on.
