### ISSUE TITLE
Version checking introduced in pull/2627 fails if worker has older version of `distributed`

### ISSUE THREAD

**Issue by ig248** [dask/distributed#3379]
The issue appears if scheduler has `distributed` at SHA>=https://github.com/dask/distributed/commit/32cb96effe9287fdc42dd73be36989be13abe99d and worker is at SHA<https://github.com/dask/distributed/commit/32cb96effe9287fdc42dd73be36989be13abe99d

PR: https://github.com/dask/distributed/pull/2627

It appears that within the spirit of adding version checking, this mis-match should be handled gracefully with an informative error message.

Minimal `docker-compose` example to reproduce:
```
# docker-compose.yaml
version: "3.1"

services:
  scheduler:
    image: daskdev/dask:latest
    command: ["dask-scheduler", "--port", "54321"]
    environment:
      - EXTRA_PIP_PACKAGES=git+https://github.com/dask/distributed@32cb96effe9287fdc42dd73be36989be13abe99d
  worker:
    image: daskdev/dask:latest
    command: ["dask-worker", "tcp://scheduler:54321", "--nthreads", "1", "--no-dashboard"]
```

error trace:
```
scheduler_1  | distributed.scheduler - INFO - Register worker <Worker 'tcp://172.23.0.3:34809', name: tcp://172.23.0.3:34809, memory: 0, processing: 0>
scheduler_1  | distributed.utils - ERROR - 'NoneType' object is not subscriptable
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
scheduler_1  |     yield
scheduler_1  |   File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1720, in add_worker
scheduler_1  |     client_name="This Worker",
scheduler_1  |   File "/opt/conda/lib/python3.7/site-packages/distributed/versions.py", line 105, in error_message
scheduler_1  |     client_versions = client["packages"]
scheduler_1  | TypeError: 'NoneType' object is not subscriptable
scheduler_1  | distributed.core - ERROR - 'NoneType' object is not subscriptable
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 412, in handle_comm
scheduler_1  |     result = await result
scheduler_1  |   File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1720, in add_worker
scheduler_1  |     client_name="This Worker",
scheduler_1  |   File "/opt/conda/lib/python3.7/site-packages/distributed/versions.py", line 105, in error_message
scheduler_1  |     client_versions = client["packages"]
scheduler_1  | TypeError: 'NoneType' object is not subscriptable
```

**Comment by TomAugspurger** [comment]
Thanks. This problem will somewhat take care of itself over time as all workers & schedulers get at least this version.

In the meantime we'd probably accept PRs to make this more graceful, though testing will be a bit hard. Is this something you're interested in working on @ig248?

**Comment by ig248** [comment]
@TomAugspurger yes.

**Comment by ig248** [comment]
Though you are right, as soon as I bump the versions I will never see the issue again... It just happened to cost me a lot of time already :D

**Comment by propername** [comment]
I'm having the same issue after updating my workers and scheduler nodes to dask and distributed 2.10.0

**Comment by mrocklin** [comment]
It looks like @ig248 has a proposed fix here: https://github.com/dask/distributed/pull/3390

I've just been busy recently and haven't had a chance to finish up review.  If you have a chance to try out that PR that would be very welcome.

**Comment by ig248** [comment]
Thanks @mrocklin , after the PR's been merged, it seems to work as intended:

```
# docker-compose.yaml
version: "3.1"

services:
  scheduler:
    image: daskdev/dask:latest
    command: ["dask-scheduler", "--port", "54321"]
    environment:
      - EXTRA_PIP_PACKAGES=git+https://github.com/dask/distributed@master
  worker:
    image: daskdev/dask:latest
    command: ["dask-worker", "tcp://scheduler:54321", "--nthreads", "1", "--no-dashboard"]
```

Logs:
```
scheduler_1  | distributed.scheduler - INFO - Register worker <Worker 'tcp://172.18.0.2:43939', name: tcp://172.18.0.2:43939, memory: 0, processing: 0>
scheduler_1  | distributed.scheduler - INFO - Starting worker compute stream, tcp://172.18.0.2:43939
scheduler_1  | distributed.core - INFO - Starting established connection
worker_1     | distributed.worker - WARNING - Mismatched versions found
worker_1     | 
worker_1     | distributed
worker_1     | +------------------------+--------------------+
worker_1     | |                        | version            |
worker_1     | +------------------------+--------------------+
worker_1     | | This Worker            | 2.9.2              |
worker_1     | | scheduler              | 2.10.0+2.gfecf588c |
worker_1     | | tcp://172.18.0.2:43939 | 2.9.2              |
worker_1     | +------------------------+--------------------+
worker_1     | distributed.worker - INFO -         Registered to:      tcp://scheduler:54321
worker_1     | distributed.worker - INFO - -------------------------------------------------
worker_1     | distributed.core - INFO - Starting established connection
```

**Comment by mrocklin** [comment]
I'm glad to hear it!

**Comment by ig248** [comment]
(froze tags and SHA references in case future civilizations try to run these compose files)
