### ISSUE TITLE
ZeroDivisionError in scheduler dashboard

### ISSUE THREAD

**Issue by mdwint** [dask/distributed#3399]
This occurs when visiting the `/status` page when no workers are running.

```python
Traceback (most recent call last):
  File "/code/.venv/lib/python3.7/site-packages/distributed/utils.py", line 652, in log_errors
    yield
  File "/code/.venv/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1754, in status_doc
    task_progress.update()
  File "/code/.venv/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 97, in func
    return input_function(*args, **kwargs)
  File "/code/.venv/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1435, in update
    d = progress_quads(state)
  File "/code/.venv/lib/python3.7/site-packages/distributed/diagnostics/progress_stream.py", line 105, in progress_quads
    rl = width * r / a + l
ZeroDivisionError: float division by zero
```

(distributed: 2.9.1)

**Comment by jrbourbeau** [comment]
Thanks for reporting @mdwint! I'm not able to reproduce the `ZeroDivisionError` on the current `master` branch or 2.9.1 release. I'm running `dask-scheduler` in my local terminal and then going to http://localhost:8787/status in my browser with no errors subsequently being raised in the terminal. Does that differ from what you're doing?

**Comment by mdwint** [comment]
Hi @jrbourbeau. We're running Dask in Docker on AWS, but I'm not sure if that would have an impact. I'll try to create minimal example locally.

**Comment by jrbourbeau** [comment]
Awesome, thanks @mdwint! That goes a long in debugging and fixing things

**Comment by mdwint** [comment]
This example produces the error:

```python
>>> from distributed import Client, LocalCluster
>>> cluster = LocalCluster(n_workers=0)
>>> client = Client(cluster)
>>> client.submit(lambda: 1)
```

With this session still running, visit http://localhost:8787/status.

The key here is that a client submits work while no workers are available. I suspect that the scheduler's state then holds tasks with some fields set to zero, causing the ZeroDivisionError.

**Comment by jrbourbeau** [comment]
Thanks for the nice reproducible example @mdwint! https://github.com/dask/distributed/pull/3407 should fix the `ZeroDivisionError`
