### ISSUE TITLE
dcluster fails with NameError

### ISSUE THREAD

**Issue by philastrophist** [dask/distributed#340]
dcluster fails with `NameError: name 'compose' is not defined`
However, setting up the cluster with `dworker` and `dscheduler` works fine.

Here's the traceback:
```
[USER@PC1 ~]$ dcluster PC1 PC2

---------------------------------------------------------------
                    Distributed v1.10.2

Worker nodes:
  0: PC1
  1: PC2

scheduler node: PC1:8786
---------------------------------------------------------------


[ worker PC1 ] : /data/USER/anaconda/bin/python -m distributed.cli.dworker PC1:8786 --host PC1 --nthreads 0 --nprocs 1
[ scheduler PC1:8786 ] : /data/USER/anaconda/bin/python -m distributed.cli.dscheduler --port 8786
[ worker PC2 ] : /data/USER/anaconda/bin/python -m distributed.cli.dworker PC1:8786 --host PC2 --nthreads 0 --nprocs 1
[ worker PC2 ] : Traceback (most recent call last):
[ worker PC2 ] :   File "/data/USER/anaconda/lib/python2.7/runpy.py", line 151, in _run_module_as_main
[ worker PC2 ] :     mod_name, loader, code, fname = _get_module_details(mod_name)
[ worker PC2 ] :   File "/data/USER/anaconda/lib/python2.7/runpy.py", line 101, in _get_module_details
[ worker PC2 ] :     loader = get_loader(mod_name)
[ worker PC2 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 464, in get_loader
[ worker PC2 ] :     return find_loader(fullname)
[ worker PC2 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 474, in find_loader
[ worker PC2 ] :     for importer in iter_importers(fullname):
[ worker PC2 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 430, in iter_importers
[ worker PC2 ] :     __import__(pkg)
[ worker PC2 ] :   File "/home/USER/.local/lib/python2.7/site-packages/distributed/__init__.py", line 11, in <module>
[ worker PC2 ] :     from .scheduler import Scheduler
[ worker PC2 ] :   File "/home/USER/.local/lib/python2.7/site-packages/distributed/scheduler.py", line 13, in <module>
[ worker PC2 ] :     from cytoolz import frequencies, topk
[ worker PC2 ] :   File "/data/USER/anaconda/lib/python2.7/site-packages/cytoolz/__init__.py", line 18, in <module>
[ worker PC2 ] :     comp = compose
[ worker PC2 ] : NameError: name 'compose' is not defined
[ scheduler PC1:8786 ] : Traceback (most recent call last):
[ scheduler PC1:8786 ] :   File "/data/USER/anaconda/lib/python2.7/runpy.py", line 151, in _run_module_as_main
[ scheduler PC1:8786 ] :     mod_name, loader, code, fname = _get_module_details(mod_name)
[ scheduler PC1:8786 ] :   File "/data/USER/anaconda/lib/python2.7/runpy.py", line 101, in _get_module_details
[ scheduler PC1:8786 ] :     loader = get_loader(mod_name)
[ scheduler PC1:8786 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 464, in get_loader
[ scheduler PC1:8786 ] :     return find_loader(fullname)
[ scheduler PC1:8786 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 474, in find_loader
[ scheduler PC1:8786 ] :     for importer in iter_importers(fullname):
[ scheduler PC1:8786 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 430, in iter_importers
[ scheduler PC1:8786 ] :     __import__(pkg)
[ scheduler PC1:8786 ] :   File "/home/USER/.local/lib/python2.7/site-packages/distributed/__init__.py", line 11, in <module>
[ scheduler PC1:8786 ] :     from .scheduler import Scheduler
[ scheduler PC1:8786 ] :   File "/home/USER/.local/lib/python2.7/site-packages/distributed/scheduler.py", line 13, in <module>
[ scheduler PC1:8786 ] :     from cytoolz import frequencies, topk
[ scheduler PC1:8786 ] :   File "/data/USER/anaconda/lib/python2.7/site-packages/cytoolz/__init__.py", line 18, in <module>
[ scheduler PC1:8786 ] :     comp = compose
[ scheduler PC1:8786 ] : NameError: name 'compose' is not defined
[ worker PC1 ] : Traceback (most recent call last):
[ worker PC1 ] :   File "/data/USER/anaconda/lib/python2.7/runpy.py", line 151, in _run_module_as_main
[ worker PC1 ] :     mod_name, loader, code, fname = _get_module_details(mod_name)
[ worker PC1 ] :   File "/data/USER/anaconda/lib/python2.7/runpy.py", line 101, in _get_module_details
[ worker PC1 ] :     loader = get_loader(mod_name)
[ worker PC1 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 464, in get_loader
[ worker PC1 ] :     return find_loader(fullname)
[ worker PC1 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 474, in find_loader
[ worker PC1 ] :     for importer in iter_importers(fullname):
[ worker PC1 ] :   File "/data/USER/anaconda/lib/python2.7/pkgutil.py", line 430, in iter_importers
[ worker PC1 ] :     __import__(pkg)
[ worker PC1 ] :   File "/home/USER/.local/lib/python2.7/site-packages/distributed/__init__.py", line 11, in <module>
[ worker PC1 ] :     from .scheduler import Scheduler
[ worker PC1 ] :   File "/home/USER/.local/lib/python2.7/site-packages/distributed/scheduler.py", line 13, in <module>
[ worker PC1 ] :     from cytoolz import frequencies, topk
[ worker PC1 ] :   File "/data/USER/anaconda/lib/python2.7/site-packages/cytoolz/__init__.py", line 18, in <module>
[ worker PC1 ] :     comp = compose
[ worker PC1 ] : NameError: name 'compose' is not defined
[ worker PC2 ] : remote process exited with exit status 1
[ scheduler PC1:8786 ] : remote process exited with exit status 1
[ worker PC1 ] : remote process exited with exit status 1

```

**Comment by mrocklin** [comment]
Looks like the error is coming from cytoolz.  @eriknw.  Perhaps update
cytoolz?

**Comment by eriknw** [comment]
`comp` and `compose` have been in `cytoolz` since the very beginning.  I don't know what is going on.

**Comment by mrocklin** [comment]
@philastrophist does this persist if you update cytoolz?

**Comment by mrocklin** [comment]
conda install cytoolz
or 

    pip install cytoolz

**Comment by mrocklin** [comment]
Closing for now due to lack of response and this seeming to be an environment issue somewhat unrelated to dask.distributed.  Please reopen if the problem persists.
