### ISSUE TITLE
Use dask_ml GridSearchCV on HPC cluster client

### ISSUE THREAD

**Issue by ArthurVINCENT** [dask/distributed#3463]
Hi,
I'm working on a large data-set and I try to find my model hyperparameters thanks to GridSearchCV from dask_ml as presented in the [dask_ml tutorial](https://ml.dask.org/joblib.html)

here is my python code :
```python
import pandas as pd
from sklearn.model_selection import GroupKFold
from dask_ml.model_selection import GridSearchCV
from dask.distributed import Client, progress
from dask_jobqueue import PBSCluster
from sklearn.externals import joblib

df_features = pd.read_sql_query(...)
df_labels = pd.read_sql_query(...)
df_groups = pd.read_sql_query(...)
splitter = list(GroupKFold(n_splits=cv_folds).split(features_values,
                                                    labels_values,
                                                    groups))
clf = RandomForestClassifier()
clf = GridSearchCV(clf,
                   cv_parameters,
                   cv=splitter,
                   return_train_score=True)

cluster = PBSCluster(cores=12,
                     memory="60GB")
cluster.adapt(minimum_jobs=5, maximum_jobs=10)
client = Client(cluster)
with joblib.parallel_backend('dask'):
    clf.fit(features_values, labels_values)
```

then dask asked me to use client.scatter to deploy data on workers as the following :
```bash
(_CVIterableWrapper(cv=[(array([     3,      4, .. ... e, False, True)
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s)
```
But if I use the backend like in the tutorial (with scatter) :
```python
with joblib.parallel_backend('dask', scatter=[features_values, labels_values]):
    clf.fit(features_values, labels_values)
```
then no workers can be found :
```bash
distributed.core - ERROR - No workers found
Traceback (most recent call last):
  File "/.../lib/python3.6/site-packages/distributed/core.py", line 412, in handle_comm
    result = await result
  File "/.../lib/python3.6/site-packages/distributed/scheduler.py", line 2703, in scatter
    raise gen.TimeoutError("No workers found")
tornado.util.TimeoutError: No workers found
```
Any suggestions will be welcome.

**Note** : If I use a smaller dataset, everything works.

**Comment by TomAugspurger** [comment]
Thanks for the report. I'd need to double check, but I don't think you need to use both `joblib.parallel_backend` and `dask_ml.model_selection.GridSearchCV`. Dask-ML's GridSearchCV doesn't use joblib.

Do you have a minimal example that produces the warning about scattering large objects?

I notice that you're using `Adaptive`. If you switch to a fixed set of workers and wait for them before starting the `joblib.parallel_backend`, do you see the exception about "No workers found"?

**Comment by ArthurVINCENT** [comment]
Thanks you for you quick reaction. 

> Do you have a minimal example that produces the warning about scattering large objects?

you can download a minimal example [here](https://filesender.renater.fr/?s=download&token=a6413a95-9a1c-2f7c-1c18-2abeedcd36c8) 130Mo.

Also, the issue occurs even if I set the number of workers by hand `cluster.scale(5)`.

I updated the code snippet to fit the provided data-set.

**Comment by TomAugspurger** [comment]
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports gives some recommendations are writing minimal bug reports. Ideally, it would be a small snippet with extraneous details removed. Does the data need to be read from sqlite to reproduce the issue, or can you use in-memory dataframes?

> Also, the issue occurs even if I set the number of workers by hand cluster.scale(5).

Even if you wait for the works to arrive with `client.wait_for_workers(5)`?

**Comment by ArthurVINCENT** [comment]
thanks you for sharing these recommendations.

here is the minimal code to produce the issue :
```python
columns = [str(col) for col in range(40)]

cv_folds = 5
cv_parameters = {'n_estimators': [50, 100, 150]}

df = pd.DataFrame(index=range(600000), columns=columns)
df = df.fillna(0)
df[columns[0]] = np.random.randint(1, 6, df.shape[0])
df[columns[1]] = np.random.randint(1, 6, df.shape[0])

labels_values = df[columns[0]]
groups = df[columns[1]]
features_values = df[columns[2:-1]]

splitter = list(
    GroupKFold(n_splits=cv_folds).split(features_values, labels_values,
                                        groups))
clf = RandomForestClassifier()
clf = GridSearchCV(clf, cv_parameters, cv=splitter, return_train_score=True)

cluster = PBSCluster(cores=12, memory="60GB")

cluster.scale(5)
client = Client(cluster)
client.wait_for_workers(5)

with joblib.parallel_backend('dask', scatter=[features_values, labels_values]):
    clf.fit(features_values, labels_values)
```

Indeed, thanks to `client.wait_for_workers(5)`, workers are found.

**Comment by TomAugspurger** [comment]
> Indeed, thanks to client.wait_for_workers(5), workers are found.

Good, so we're just deailing with the warning about scattering large bits of data.

I don't have access to an HPC cluster. Are you able to swap out the PBCluster for a `LocalCluster` and still reproduce the problem?

This is starting to sound like https://github.com/dask/dask-ml/issues/516. One problem with pre-scattering is that the large pieces of data in the graph are generated by dask-ml itself, not the user. So we need to make sure that the scattered pieces are just keys to slices of the data, rather than concrete ndarrays.

**Comment by ArthurVINCENT** [comment]
by replacing the `PBSCluster` by `LocalCluster` then the following error occurs :
```bash
File ".../lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File ".../lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File ".../lib/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File ".../lib/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File ".../lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".../lib/python3.6/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File ".../lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File ".../lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

and the program still stuck.

**Comment by mrocklin** [comment]
See https://github.com/dask/distributed/issues/516#issuecomment-306468605

**Comment by mrocklin** [comment]
Also
https://stackoverflow.com/questions/60232708/dask-fails-with-freeze-support-bug/60232709#60232709

**Comment by ArthurVINCENT** [comment]
thanks you, @mrocklin. the issue can be reproduce with the LocalCluster(processes=False,...)

**Comment by mrocklin** [comment]
That's very surprising.  I encourage you to reduce that down to a minimal reproducer and share it here if you have the time.

**Comment by TomAugspurger** [comment]
@ArthurVINCENT have you been able to look at this anymore? I'm not seeing any issues with the following

<details>

```python
import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from distributed import LocalCluster, Client

if __name__ == "__main__":
    columns = [str(col) for col in range(40)]

    cv_folds = 5
    cv_parameters = {'n_estimators': [50, 100, 150]}

    df = pd.DataFrame(index=range(60000), columns=columns)
    df = df.fillna(0)
    df[columns[0]] = np.random.randint(1, 6, df.shape[0])
    df[columns[1]] = np.random.randint(1, 6, df.shape[0])

    labels_values = df[columns[0]]
    groups = df[columns[1]]
    features_values = df[columns[2:-1]]

    splitter = list(
        GroupKFold(n_splits=cv_folds).split(features_values, labels_values,
                                            groups))
    clf = RandomForestClassifier()
    clf = GridSearchCV(clf, cv_parameters, cv=splitter, return_train_score=True)

    cluster = LocalCluster()
    client = Client(cluster)

    with joblib.parallel_backend('dask', scatter=[features_values, labels_values]):
        clf.fit(features_values, labels_values)
```

</details>

**Comment by ArthurVINCENT** [comment]
actually the issue/warning appear if you replace  the import
```python
from sklearn.model_selection import GridSearchCV
````
by 
```python
from dask_ml.model_selection import GridSearchCV
````
Is there any reasons of using sklearn instead of dask_ml ?

I will launch on my huge data-set and I will keep you informed if everything works.

**Comment by TomAugspurger** [comment]
> Is there any reasons of using sklearn instead of dask_ml ?

That's documented in https://ml.dask.org/hyper-parameter-search.html#hyperparameter-drop-in.

**Comment by ArthurVINCENT** [comment]
it seems to work as expect on my large dataset. So, I will use GridSearchCV coming from sklearn instead of dask_ml.

Thanks.
