### ISSUE TITLE
Variable delete raises KeyError

### ISSUE THREAD

**Issue by wojtossfm** [dask/distributed#3492]
It seems that there is an unhandled KeyError in the scheduler variable delete logic.

If using the asynchronous API only visible in the scheduler logs but it does mean that Variables will be "leaking" and staying around instead of being deleted.

It happens regardless of whether you set a value.

Shortest reproduction I can provide is as follows:
```python
from distributed import Client
from distributed import Variable


def main():
    Client()
    Variable().delete()


if __name__ == '__main__':
    main()
```

```python
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f8fe9265be0>>, <Task finished coro=<VariableExtension.delete() done, defined at ./venv/lib/python3.6/site-packages/distributed/variable.py:101> exception=KeyError('variable-68a51209410248fa9f69f84b25f48343',)>)
Traceback (most recent call last):
  File "./venv/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "./venv/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "./venv/lib/python3.6/site-packages/distributed/variable.py", line 110, in delete
    del self.waiting_conditions[name]
KeyError: 'variable-68a51209410248fa9f69f84b25f48343'
```

Python 3.6.10
Reproduced with distributed 2.9.3 and 2.10.0

**Comment by mrocklin** [comment]
@jacobtomlinson based on your interests this may be something you would find educational.
