### ISSUE TITLE
Dask Executor KeyError 'type'

### ISSUE THREAD

**Issue by nocturnaltortoise** [dask/distributed#362]
When trying to create an Executor with Dask Distributed like this: 
```
import dask
from distributed import Executor

executor = Executor('10.0.2.15:8786')
```

I have a dask scheduler running on that IP, terminal output for that looks like:
```
hduser@virtual-14:/usr/local/lib$ dask-scheduler
distributed.scheduler - INFO - Scheduler at:            10.0.2.15:8786
distributed.scheduler - INFO -      http at:            10.0.2.15:9786
distributed.scheduler - INFO - Please install Bokeh to get Web UI
```

When I run the script I get:

```
distributed.utils - ERROR - 'type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 299, in _start
    if ident['type'] == 'Scheduler':
KeyError: 'type'
Traceback (most recent call last):
  File "/home/hduser/wordcount.py", line 4, in <module>
    executor = Executor('10.0.2.15:8786')
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 259, in __init__
    self.start(timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 287, in start
    sync(self.loop, self._start, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 116, in sync
    six.reraise(type(error[0]), error[0], traceback[0])
  File "/usr/lib/python3/dist-packages/six.py", line 536, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.4/dist-packages/distributed/executor.py", line 299, in _start
    if ident['type'] == 'Scheduler':
KeyError: 'type'
```

And the terminal output for the dask-scheduler:

```
distributed.core - INFO - Connection from 10.0.2.15:37392 to Scheduler
distributed.core - INFO - Lost connection: ('10.0.2.15', 37392)
distributed.core - INFO - Close connection from 10.0.2.15:37392 to Scheduler
```

What am I doing wrong here? Both the scheduler and the script that instantiates the executor are running on the same machine. 

Thanks

**Comment by mrocklin** [comment]
Can you verify that both your scheduler and your executor are running under the same version of Python?

**Comment by nocturnaltortoise** [comment]
Ah, thanks, that was the issue, works fine if I run my program with python2.7 instead. Is there a way of telling dask-scheduler to run with python3?

**Comment by mrocklin** [comment]
I usually manage Python environments using something like conda.  When I install distributed in a Python3 environment then `dask-scheduler` runs in Python 3.  

If you are using system Python environments then perhaps you can do something like `pip3 install distributed` or `python3 -m distributed.cli.dask_scheduler` ?

**Comment by mrocklin** [comment]
Closing this as an environment issue.
