### ISSUE TITLE
Key aliasing fails if value is a Future

### ISSUE THREAD

**Issue by jcrist** [dask/distributed#363]
Aliasing in graphs (key pointing to another key, not a task) only works if the aliased value isn't a `Future`. From current master:

```python
In [1]: import distributed

In [2]: distributed.__version__
Out[2]: '1.11.0'

In [3]: exc = distributed.Executor('10.0.0.3:8786')

In [4]: dsk = {'b': 'a', 'a': 1}    # A simple graph with key aliasing

In [5]: exc.get(dsk, 'b')     # Aliasing works if the aliased value is *not* a future
Out[5]: 1

In [6]: a = exc.submit(lambda x: x, 1)

In [7]: dsk = {'b': 'a', 'a': a}    # Recreate the same graph, but with a future

In [8]: exc.get(dsk, 'a')     # Can get the future
Out[8]: 1

In [9]: exc.get(dsk, 'b')     # Can't get the alias
<locks up>
```

Here's the traceback from `dask-scheduler`:

```
distributed.scheduler - ERROR - 'b'
Traceback (most recent call last):
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1424, in handle_messages
    result = self.compute_handlers[op](**msg)
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1151, in update_graph
    stack.extend(self.dependencies[k])
KeyError: 'b'
distributed.utils - ERROR - 'b'
Traceback (most recent call last):
  File "/Users/jcrist/Code/distributed/distributed/utils.py", line 206, in log_errors
    yield
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1424, in handle_messages
    result = self.compute_handlers[op](**msg)
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1151, in update_graph
    stack.extend(self.dependencies[k])
KeyError: 'b'
distributed.scheduler - INFO - Close connection to Scheduler, 906db8d7-4310-11e6-b736-a0999b1aeddf
distributed.core - ERROR - 'b'
Traceback (most recent call last):
  File "/Users/jcrist/Code/distributed/distributed/core.py", line 206, in handle_stream
    result = yield gen.maybe_future(handler(stream, **msg))
  File "/Users/jcrist/anaconda/envs/dask_learn/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/jcrist/anaconda/envs/dask_learn/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/jcrist/anaconda/envs/dask_learn/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1353, in add_client
    yield self.handle_messages(stream, bstream, client=client)
  File "/Users/jcrist/anaconda/envs/dask_learn/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/jcrist/anaconda/envs/dask_learn/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/jcrist/anaconda/envs/dask_learn/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1424, in handle_messages
    result = self.compute_handlers[op](**msg)
  File "/Users/jcrist/Code/distributed/distributed/scheduler.py", line 1151, in update_graph
    stack.extend(self.dependencies[k])
KeyError: 'b'
```

**Comment by jcrist** [comment]
Actually, having a future anywhere in the dependencies of an aliased key causes failures:

```python
In [1]: import distributed

In [2]: exc = distributed.Executor('10.0.0.3:8786')

In [3]: a = exc.submit(lambda x: x, 1)

In [4]: dsk = {'c': 'b', 'b': (lambda x: x, 'a'), 'a': a}

In [6]: exc.get(dsk, 'a')
Out[6]: 1

In [7]: exc.get(dsk, 'b')
Out[7]: 1

In [8]: exc.get(dsk, 'c')
<locks up>
```

Same traceback as above, but here the `KeyError` is for `'c'`.

**Comment by jcrist** [comment]
The issue has to do with `dask.optimize.inline` accidentally removing any aliased keys from the graph. Should have a PR to main dask repo early tomorrow (unless someone else beats me to it :smile:).

**Comment by mrocklin** [comment]
Is there a situation that the Executor should have caught and raised and error for?

**Comment by jcrist** [comment]
`dask.optimize.inline` is called in the executor before sending the graph to the scheduler, which means the error happens in the scheduler at runtime. Perhaps the scheduler should check the validity of requests made by executors (`assert set(keys).issubset(tasks)` would have caught this)? Other than that, I think this is just a bug.

**Comment by jcrist** [comment]
Fixed by https://github.com/dask/dask/pull/1356. Closing.
