### ISSUE TITLE
WARNING - Couldn't gather 1 keys, rescheduling even with --contact-address flag

### ISSUE THREAD

**Issue by devsentient** [dask/distributed#3798]
I'm trying to deploy dask on an AWS Fargate cluster, and am starting workers with the following command:
```
dask-worker --preload /app/common.py tcp://dask_scheduler_service.local:8786 --contact-address tcp://dask_worker_service.local:9000 --listen-address tcp://0.0.0.0:9000
```
The `dask_scheduler_service.local` and `dask_worker_service.local` names are from the service discovery service (cloud map).

I'm able to create a client, submit a job and track its progress on the dashboard. When the workers complete all the tasks, I get a
`WARNING - Couldn't gather 1 keys, rescheduling`
message from the client, and this error from the scheduler:
`ERROR - Workers don't have promised key: ['tcp://xxx.xx.xx.xxx:9000'],`
with the IP of the worker (and not `dask_worker_service.local`)

Anything obvious I'm missing?

**Comment by jacobtomlinson** [comment]
Do you have multiple workers and are they all sitting behind `dask_worker_service.local`?

_Also have you checked out [dask-cloudprovider](https://github.com/dask/dask-cloudprovider)?_

**Comment by devsentient** [comment]
I've removed the cloud map mapping for the workers and the issue persists. I have tried dask-cloudprovider but it does things like remove all my existing task definitions, which we need.

**Comment by devsentient** [comment]
If I direct the worker to the `lo` network interface I get a different error on the scheduler:

```
distributed.core - WARNING - No handler get_data found in Scheduler
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 385, in handle_comm
    handler = self.handlers[op]
KeyError: 'get_data'
distributed.core - ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 403, in handle_comm
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 2827, in gather
    who_has, rpc=self.rpc, close=False, serializers=serializers
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils_comm.py", line 78, in gather_from_workers
    r = await c
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 3224, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 3214, in _get_data
    status = response["status"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jacobtomlinson** [comment]
>  I have tried dask-cloudprovider but it does things like remove all my existing task definitions, which we need.

Oh dear, that's definitely a bug. Have you raised this?

**Comment by impravin22** [comment]
@jacobtomlinson I am facing the same issue. Did you solve the issue? if yes can you please tell me how to solve it? I have posted my problem in stackoverflow too. But didn't find the solution yet.

https://stackoverflow.com/questions/64382706/dask-distributed-scheduler-error-couldnt-gather-keys
