### ISSUE TITLE
distributed.utils - ERROR while running dask.distributed on local cluster

### ISSUE THREAD

**Issue by ghltshubh** [dask/distributed#3804]
I am trying to run the following code on a Power PC with following config:

    Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
    CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
              Kernel: Linux 3.10.0-957.21.3.el7.ppc64le
        Architecture: ppc64-le

single node localcluster with 20 cores.

    import os, subprocess
    from timeit import default_timer as timer
    from dask.distributed import Client, LocalCluster, fire_and_forget, as_completed
    
    def run_client(n_workers):
        files = []
        for dirpaths, dirnames, filenames in os.walk('cap_logs/'):
            if not dirnames:
                files.extend([os.path.join(dirpaths, file) for file in filenames])
    
        def parser(file):
            val = subprocess.run(['./test.sh', file], stdout=subprocess.PIPE)
            return val.stdout.decode()
    
        cluster = LocalCluster(n_workers=n_workers, dashboard_address=None)
        with Client(cluster) as client:
            futures = []
            files = client.scatter(files)
            futures = client.map(parser, files)
            results = [future.result() for future in as_completed(futures)]
            del futures
            cluster.close()
    
    workers = [12, 10, 8, 7, 6, 5, 4, 3, 2, 1]
    times = {}
    for n_workers in workers:
        tic = timer()
        run_client(n_workers)
        toc = timer()
        time = toc - tic
        times[n_workers] = round(time, 2)

It sometimes works fine and sometimes it throws the following error though it still keeps working in background:

```
distributed.utils - ERROR - '<' not supported between instances of 'NoneType' and 'tuple'
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/utils.py", line 664, in log_errors
    yield
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1746, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1124, in __init__
    self.layout = GraphLayout(scheduler)
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 39, in __init__
    self.scheduler, dependencies=dependencies, priority=priority
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 43, in update_graph
    stack = sorted(dependencies, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
tornado.application - ERROR - Uncaught exception GET /graph (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:9999', method='GET', uri='/graph', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1746, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1124, in __init__
    self.layout = GraphLayout(scheduler)
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 39, in __init__
    self.scheduler, dependencies=dependencies, priority=priority
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 43, in update_graph
    stack = sorted(dependencies, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
Exception ignored in: <function TaskGraph.__del__ at 0x10002e41be60>
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/gen011/shubhankar/summitdev/anaconda3/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1283, in __del__
    self.scheduler.remove_plugin(self.layout)
AttributeError: 'TaskGraph' object has no attribute 'layout'
```

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @ghltshubh! Could you produce a minimal reproducible example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)? I can't run the above example as I don't have a `cap_logs/` directory or `test.sh`

**Comment by ghltshubh** [comment]
@jrbourbeau Sorry I forgot to 
They are pretty straight forward: 
create a directory structure for caps_logs as follows (touch file1, file2....):
caps_logs/
|
|-dir1/
|   |
|   |-file1, file2
|
|-dir2/
    |
    |-file3, file4

and the test.sh just echos that file name as i.e. it has only 1 line in it:
`echo $1`

**Comment by jrbourbeau** [comment]
Are those directory and files necessary to produce the `AttributeError`? Here's a modified version of your example which doesn't use any local files:


```python
from dask.distributed import Client, LocalCluster, as_completed

if __name__ == "__main__":

    def run_client(n_workers):
        cluster = LocalCluster(n_workers=n_workers, dashboard_address=None)
        with Client(cluster) as client:
            futures = []
            data = list(range(10))
            data = client.scatter(data)
            futures = client.map(lambda x: x, data)
            results = [future.result() for future in as_completed(futures)]
            del futures
            cluster.close()

    workers = [12, 10, 8, 7, 6, 5, 4, 3, 2, 1]
    for n_workers in workers:
        run_client(n_workers)
```

The above snippet completes successfully for me, does it for you?

**Comment by ghltshubh** [comment]
@jrbourbeau I figured out when exactly that error occurs. So I am also getting the performance report in a separate tab and when I try to go Graph tab it gives a `500: Internal Server Error` on the webpage and the error mentioned above in the jupyter notebook.

**Comment by jacobtomlinson** [comment]
How did you install Dask? Could you share your conda environment?

**Comment by ghltshubh** [comment]
@jacobtomlinson I am using default conda packages. Following is my conda env

```
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
_libgcc_mutex             0.1                        main  
aiohttp                   3.6.2            py37h7b6447c_0  
alabaster                 0.7.12                   py37_0  
anaconda                  custom                   py37_1  
anaconda-client           1.7.2                    py37_0  
anaconda-project          0.8.4                      py_0  
asn1crypto                1.3.0                    py37_0  
astroid                   2.4.0                    py37_0  
astropy                   4.0.1.post1      py37h7b6447c_1  
async-timeout             3.0.1                    py37_0  
attrs                     19.3.0                     py_0  
babel                     2.8.0                      py_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.0                    py37_0  
bitarray                  1.2.1            py37h7b6447c_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                    openblas  
bleach                    3.1.4                      py_0  
blosc                     1.16.3               hd408876_0  
bokeh                     2.0.2                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.3.2            py37heb32a55_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.1.1                      0  
cairo                     1.14.12              h8948797_3  
certifi                   2020.4.5.1               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                      py_0  
cloudpickle               1.4.1                      py_0  
clyent                    1.2.2                    py37_1  
cmake                     3.14.0               h52cb24c_0  
colorama                  0.4.3                      py_0  
conda                     4.8.3                    py37_0  
conda-build               3.18.10                  py37_3  
conda-env                 2.6.0                         1  
conda-package-handling    1.6.1            py37h7b6447c_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0  
cryptography              2.9.2            py37h1ba5d50_0  
curl                      7.69.1               hbc83047_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.17          py37he6710b0_0  
cytoolz                   0.10.1           py37h7b6447c_0  
dask                      2.16.0                     py_0  
dask-core                 2.16.0                     py_0  
dask-labextension         2.0.2                      py_0    conda-forge
dask_labextension         2.0.2                         0    conda-forge
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
distributed               2.16.0                   py37_0  
docutils                  0.16                     py37_0  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                he6710b0_0  
fastcache                 1.1.0            py37h7b6447c_0  
filelock                  3.0.12                     py_0  
flask                     1.1.2                      py_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_0  
fsspec                    0.7.1                      py_0  
future                    0.18.2                   py37_0  
get_terminal_size         1.0.0                         0  
gevent                    1.4.0            py37h7b6447c_0  
glib                      2.63.1               h5a9c865_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                h7f7056e_2  
gmpy2                     2.0.8            py37h10f8cd9_2  
greenlet                  0.4.15           py37h7b6447c_0  
h5py                      2.10.0           py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.0.1                    py37_0  
hypothesis                5.11.0                     py_0  
icu                       58.2                 he6710b0_3  
idna                      2.9                        py_1  
imageio                   2.8.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib_metadata        1.5.0                    py37_0  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.13.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  h14c3975_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.0                   py37_0  
jinja2                    2.11.2                     py_0  
joblib                    0.14.1                     py_0  
jpeg                      9b                   hcb7ba68_2  
json5                     0.9.4                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter-server-proxy      1.4.0                      py_0    conda-forge
jupyter_client            6.1.3                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.1                    py37_0  
jupyterlab                1.2.6              pyhf63ae98_0  
jupyterlab_server         1.1.1                      py_0  
kiwisolver                1.2.0            py37hfd86e86_0  
krb5                      1.17.1               h597af5e_0  
lazy-object-proxy         1.4.3            py37h7b6447c_0  
ld_impl_linux-ppc64le     2.33.1               h0f24833_7  
leveldb                   1.20                 hf484d3e_1  
libarchive                3.3.3                h5d8350f_5  
libcurl                   7.69.1               h20c2e04_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hf62a594_5  
libgcc-ng                 8.2.0                h822a55f_1  
libgfortran-ng            7.3.0                h822a55f_1  
libopenblas               0.3.6                h5a2b251_1  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              8.2.0                h822a55f_1  
libtiff                   4.1.0                h2733197_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_0  
libxml2                   2.9.9                hea5a465_1  
libxslt                   1.1.33               h7d1a2b0_0  
lmdb                      0.9.23               he6710b0_0  
locket                    0.2.0                    py37_1  
lxml                      4.5.0            py37hefd8a0e_0  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h7b6447c_2  
markupsafe                1.1.1            py37h7b6447c_0  
matplotlib                3.1.3                    py37_0  
matplotlib-base           3.1.3            py37h4fdacc2_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h7b6447c_0  
mock                      4.0.2                      py_0  
more-itertools            8.2.0                      py_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            1.0.0            py37hfd86e86_1  
multidict                 4.7.3            py37h7b6447c_0  
multipledispatch          0.6.0                    py37_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.6                      py_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                        py_0  
ninja                     1.9.0            py37hfd86e86_0  
nltk                      3.4.5                    py37_0  
nodejs                    10.13.0              he6710b0_0  
nomkl                     3.0                           0  
nose                      1.3.7                    py37_2  
notebook                  6.0.3                    py37_0  
numexpr                   2.7.1            py37h7ea95a0_0  
numpy                     1.18.1           py37h94c655d_0  
numpy-base                1.18.1           py37h2f8d375_1  
numpydoc                  0.9.2                      py_0  
olefile                   0.46                     py37_0  
openblas                  0.3.6                         1  
openblas-devel            0.3.6                         1  
openpyxl                  3.0.3                      py_0  
openssl                   1.1.1g               h7b6447c_0  
packaging                 20.3                       py_0  
pandas                    1.0.3            py37h0573a6f_0  
pandoc                    2.0.0.1                       1  
pandocfilters             1.4.2                    py37_1  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
patchelf                  0.10                 he6710b0_0  
path                      13.1.0                   py37_0  
path.py                   12.4.0                        0  
pathlib2                  2.3.5                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 he6710b0_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.1.2            py37haac5956_0  
pip                       20.0.2                   py37_3  
pixman                    0.34.0               h1f8d8dc_3  
pkginfo                   1.5.0.1                  py37_0  
pluggy                    0.13.1                   py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.7.1                      py_0  
prompt-toolkit            3.0.4                      py_0  
prompt_toolkit            3.0.4                         0  
psutil                    5.7.0            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.1                      py_0  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h7b6447c_1  
pycparser                 2.20                       py_0  
pycrypto                  2.6.1            py37h14c3975_9  
pycurl                    7.43.0.5         py37h1ba5d50_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.6.1                      py_0  
pylint                    2.5.0                    py37_1  
pyodbc                    4.0.30           py37he6710b0_0  
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.7                      py_0  
pyrsistent                0.16.0           py37h7b6447c_0  
pysocks                   1.7.1                    py37_0  
pytables                  3.6.1            py37h71ec239_0  
pytest                    5.4.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.8.0                      py_0  
pytest-astropy-header     0.1.2                      py_0  
pytest-doctestplus        0.5.0                      py_0  
pytest-openfiles          0.5.0                      py_0  
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.7           ha29dc6b_0_cpython  
python-dateutil           2.8.1                      py_0  
python-libarchive-c       2.9                        py_0  
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py37h7b6447c_0  
pyyaml                    5.3.1            py37h7b6447c_0  
pyzmq                     18.1.1           py37he6710b0_0  
readline                  8.0                  h7b6447c_0  
requests                  2.23.0                   py37_0  
rhash                     1.3.8                h1ba5d50_0  
ruamel_yaml               0.15.87          py37h7b6447c_0  
scikit-image              0.16.2           py37h0573a6f_0  
scikit-learn              0.22.1           py37h22eb022_0  
scipy                     1.4.1            py37habc2bb6_0  
seaborn                   0.10.1                     py_0  
send2trash                1.5.0                    py37_0  
setuptools                46.2.0                   py37_0  
simpervisor               0.3                        py_1    conda-forge
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
six                       1.14.0                   py37_0  
snappy                    1.1.7                h1532aa0_3  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 2.0                        py_0  
sphinx                    3.0.3                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.1                      py_0  
sqlalchemy                1.3.16           py37h7b6447c_0  
sqlite                    3.31.1               hbc83047_1  
statsmodels               0.11.0           py37h7b6447c_0  
sympy                     1.5.1                    py37_0  
tblib                     1.6.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.8                hbc83047_0  
toml                      0.10.0           py37h28b3542_0  
toolz                     0.10.0                     py_0  
torch                     1.3.0a0+ee77ccb          pypi_0    pypi
tornado                   6.0.4            py37h7b6447c_1  
tqdm                      4.46.0                     py_0  
traitlets                 4.3.3                    py37_0  
typed-ast                 1.4.1            py37h7b6447c_0  
typing                    3.6.4                    py37_0  
typing_extensions         3.7.4.1                  py37_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h2c717c6_0  
urllib3                   1.25.8                   py37_0  
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
xgboost                   1.1.0-SNAPSHOT           pypi_0    pypi
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.2.8                      py_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.1.7                h1bed415_2  
yarl                      1.4.2            py37h7b6447c_0  
zeromq                    4.2.5                hf484d3e_0  
zict                      2.0.0                      py_0  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```
