### ISSUE TITLE
MemoryError during serialization of not large objects

### ISSUE THREAD

**Issue by tiagofrepereira2012** [dask/distributed#3806]
Hi, 

I'm trying to use `dask-distributed` and `dask-jobqueue` for my work and very often my code raises a `MemoryError` exception during the serialization of not very large arrays.
I've crafted a very simple example where the issue arises. 

As you can see in the code below, 40 SGE workers (16GB each) are responsible to process 100 np.arrays of `3x400x480` (~4GB in total) in a very simple data structure. Then this data is reduced to the nanny that has 32GB.
This is more than enough memory to handle this job.

```python
import dask
import dask.bag
import numpy as np

# Simple data structure where 1 SampleSet has N Samples
class SampleSet:
    def __init__(self, samples):
        self.samples = samples

class Sample:
    def __init__(self, data):
        self.data = data

# Function 1
def create_samplesets(n_sample_sets, n_samples):
    # Create a list of samplesets
    return [
        SampleSet(
            [Sample(data=None) for _ in range(n_samples)],
        )
        for _ in range(n_sample_sets)
    ]

# Function 2
def create_samples(samplesets):
    # create some random np.arrays
    for sset in samplesets:
        for sample in sset.samples:
            sample.data = np.random.rand(3, 480, 400)

    return samplesets


# Building my graph with 1000 np.arrays of 400x480x3 in total which is ~4GB
data = create_samplesets(100,10)
db = dask.bag.from_sequence(data)
db = db.map_partitions(create_samples)
reduced = dask.delayed(list)(db)


from dask_jobqueue import SGECluster
from dask.distributed import Client
cluster = SGECluster(queue='q_1day',
                     processes=1,
                     cores=1,
                     memory='16GB',
                     log_directory="./logs",
                     resource_spec='q_1day=TRUE,io_big=TRUE',
                     )
cluster.scale(40) # Distributing to 40 nodes with 16GB each
dask_client = Client(cluster)

# Doing the reduction in a machine with 32GB of RAM
reduced = reduced.compute(scheduler=dask_client)

```
However, once this is executed in the cluster I have the following error.
This runs with the local client without any issue.

```sh
Traceback (most recent call last):
  File "test_big_pickle.py", line 54, in <module>
    reduced = reduced.compute(scheduler=dask_client)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/client.py", line 1893, in gather
    asynchronous=asynchronous,
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/client.py", line 1781, in _gather
    response = await future
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/client.py", line 1832, in _gather_remote
    response = await retry_operation(self.scheduler.gather, keys=keys)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/utils_comm.py", line 391, in retry_operation
    operation=operation,
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/utils_comm.py", line 379, in retry
    return await coro()
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/core.py", line 757, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/core.py", line 540, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/comm/tcp.py", line 212, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/comm/utils.py", line 75, in from_frames
    res = _from_frames()
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 80, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type list.
Traceback (most recent call last):
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 38, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class '__main__.SampleSet'>: attribute lookup SampleSet on __main__ failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 191, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 58, in pickle_dumps
    return {"serializer": "pickle"}, [pickle.dumps(x)]
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1083, in dumps
    cp.dump(obj)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 477, in dump
    return Pickler.dump(self, obj)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
MemoryError

```

Follow below the versions of the dask software stack I'm using.
Worth noting I'm using the last cloudpickle version available in the conda-defaults
```sh
dask                      2.12.0                     py_0    defaults
dask-core                 2.12.0                     py_0    defaults
dask-jobqueue             0.7.0                      py_0    defaults
distributed               2.12.0                   py37_0    defaults
cloudpickle               1.4.1                      py_0    defaults
```
Is this a real issue?

Thanks

**Comment by jacobtomlinson** [comment]
I am unable to reproduce with a quick test on a Kubernetes cluster with 40 1vCPU 16GB workers. The data is being reduced to a notebook with 24GB of memory.

![image](https://user-images.githubusercontent.com/1610850/82196720-fb5df300-98f1-11ea-9186-cb3de5ddfc19.png)

I am running `dask==2.16.0` so you may want to try a newer version.

I note that my cluster is showing 8GB of memory usage.

![image](https://user-images.githubusercontent.com/1610850/82197035-614a7a80-98f2-11ea-928e-5c4953b3c2e1.png)

I think your data structure is larger than ~4GB.

`1000x3x400x480 x 64bit Float = ~34GB`.

**Comment by tiagofrepereira2012** [comment]
Thanks for testing this.
I meant `100x3x400x480` (this value is crafted in the code example).

I'll run some tests updating the dask version

**Comment by tiagofrepereira2012** [comment]
Hi @jacobtomlinson,

I've tested with new `dask==2.16.0` and `distributed==2.16.0` and the problem was solved.

However, I have another issue. My works are being killed with `CommClosedError`
```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f5aa712eb90>>, <Task finished coro=<Worker.gather_dep() done, defined at /home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/worker.py:1963> exception=CommClosedError()>)
Traceback (most recent call last):
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/worker.py", line 2068, in gather_dep
    {"op": "missing-data", "errant_worker": worker, "key": d}
  File "/home/tpereira/conda/envs/bob.pipelines/lib/python3.7/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError
```

Well, I'll investigate a bit more and open another issue if necessary.

Thanks again
