### ISSUE TITLE
SSHCluster can't turn dashboard off

### ISSUE THREAD

**Issue by Keou0007** [dask/distributed#3903]
Trying to turn off the dashboard results in a traceback at launch for SSHCluster
```python
from distributed import SSHCluster
cluster = SSHCluster(['localhost']*4, scheduler_options={'dashboard_address':None})
```
<details>
  <summary>Traceback - Click to expand!</summary>
  
```
distributed.deploy.ssh - INFO - distributed.scheduler - INFO - -----------------------------------------------
distributed.deploy.ssh - INFO - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.deploy.ssh - INFO - Traceback (most recent call last):
distributed.deploy.ssh - INFO - File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/node.py", line 232, in start_http_server
distributed.deploy.ssh - INFO - self.http_server.listen(**http_address)
distributed.deploy.ssh - INFO - File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
distributed.deploy.ssh - INFO - sockets = bind_sockets(port, address=address)
distributed.deploy.ssh - INFO - File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/tornado/netutil.py", line 117, in bind_sockets
distributed.deploy.ssh - INFO - socket.getaddrinfo(address, port, family, socket.SOCK_STREAM, 0, flags),
distributed.deploy.ssh - INFO - File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/socket.py", line 918, in getaddrinfo
distributed.deploy.ssh - INFO - for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
distributed.deploy.ssh - INFO - socket.gaierror: [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/shannon/Library/Application Support/JetBrains/PyCharm2020.1/scratches/scratch_1.py", line 19, in <module>
    cluster = SSHCluster(['localhost']*4, scheduler_options={'dashboard_address':None})
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/ssh.py", line 336, in SSHCluster
    return SpecCluster(workers, scheduler, name="SSHCluster", **kwargs)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/spec.py", line 256, in __init__
    self.sync(self._start)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 163, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/utils.py", line 347, in sync
    raise exc.with_traceback(tb)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/utils.py", line 331, in f
    result[0] = yield future
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/spec.py", line 284, in _start
    self.scheduler = await self.scheduler
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/ssh.py", line 203, in start
    raise Exception("Worker failed to start")
Exception: Worker failed to start
distributed.deploy.spec - WARNING - Cluster closed without starting up
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/utils.py", line 198, in ignoring
    yield
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/spec.py", line 611, in close_clusters
    cluster.close(timeout=10)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 84, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 163, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/utils.py", line 347, in sync
    raise exc.with_traceback(tb)
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/utils.py", line 331, in f
    result[0] = yield future
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/spec.py", line 400, in _close
    await super()._close()
  File "/Users/shannon/opt/miniconda3/envs/pywakes/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 73, in _close
    await self._watch_worker_status_comm.close()
AttributeError: 'SpecCluster' object has no attribute '_watch_worker_status_comm'
```

</details>

**Environment**:

- Dask version: 2.17.2
- Python version: 3.8.3
- Operating System: macOS
- Install method (conda, pip, source): conda

**Comment by mrocklin** [comment]
Thank you for the excellent issue @Keou0007 

I have a possible fix in https://github.com/dask/distributed/pull/3907 but this upsets some downstream work in dask-cuda.  I suggest that we wait a little while to see how they feel about it.

**Comment by Keou0007** [comment]
No worries. I usually turn off the dashboard because I don't use it, but it doesn't really hurt anything to have it running, so no impact on my work.
