### ISSUE TITLE
Cancelling task waiting on event breaks tornado

### ISSUE THREAD

**Issue by LunarLanding** [dask/distributed#3908]
**What happened**:
Tornado breaks.
**What you expected to happen**:
The task to cancel silently.
**Minimal Complete Verifiable Example**:

```python
from distributed.client import Client
client = Client(asynchronous=True)

from distributed import Event
import asyncio
e=await Event()
t1 = e.wait()

t = asyncio.create_task(t1)
await asyncio.sleep(1)
t1.close()
```

**Anything else we need to know?**:
The traceback (repeats every few seconds):
```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f61e2ada310>>, <Task finished coro=<Client._update_scheduler_info() done, defined at /home/ma/miniconda3/lib/python3.7/site-packages/distributed/client.py:1137> exception=AssertionError('Already reading')>)
Traceback (most recent call last):
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 1141, in _update_scheduler_info
    self._scheduler_identity = await self.scheduler.identity()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/core.py", line 806, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/core.py", line 589, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/iostream.py", line 436, in read_bytes
    future = self._start_read()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/iostream.py", line 824, in _start_read
    assert self._read_future is None, "Already reading"
AssertionError: Already reading
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f61e2ada310>>, <Task finished coro=<Client._update_scheduler_info() done, defined at /home/ma/miniconda3/lib/python3.7/site-packages/distributed/client.py:1137> exception=AssertionError('Already reading')>)
Traceback (most recent call last):
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 1141, in _update_scheduler_info
    self._scheduler_identity = await self.scheduler.identity()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/core.py", line 806, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/core.py", line 589, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/iostream.py", line 436, in read_bytes
    future = self._start_read()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/iostream.py", line 824, in _start_read
    assert self._read_future is None, "Already reading"
AssertionError: Already reading
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f61e2ada310>>, <Task finished coro=<Client._update_scheduler_info() done, defined at /home/ma/miniconda3/lib/python3.7/site-packages/distributed/client.py:1137> exception=AssertionError('Already reading')>)
Traceback (most recent call last):
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/client.py", line 1141, in _update_scheduler_info
    self._scheduler_identity = await self.scheduler.identity()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/core.py", line 806, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/core.py", line 589, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/iostream.py", line 436, in read_bytes
    future = self._start_read()
  File "/home/ma/miniconda3/lib/python3.7/site-packages/tornado/iostream.py", line 824, in _start_read
    assert self._read_future is None, "Already reading"
```

**Environment**:

- Dask version: 2.18.1
- Python version: 3.7
- Operating System: Linux, WSL
- Install method (conda, pip, source): conda

**Comment by LunarLanding** [comment]
I verified this does not happen if it runs in a worker.
I will attempt to rewrite my logic so asyncio events are used there.
Code that works:

```python
from dask.distributed import Client
client = await Client(asynchronous=True)

import distributed,tornado
from distributed import Event
import asyncio

import asyncio
from functools import wraps

def wrap_async(func):
    @wraps(func)
    def wrapped(*args,**kwargs):
        return asyncio.run(func(*args,**kwargs))
    return wrapped


async def make_new_async_worker_client():
    return await distributed.Client(
        distributed.get_worker().scheduler.address,
        loop=tornado.ioloop.IOLoop.current(),
        asynchronous=True,
        direct_to_workers=True,
        name="worker",
    )
e=await Event()
async def f():
    with (await make_new_async_worker_client()).as_current():
        e.client = Client.current()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()
        return 1
await client.submit(wrap_async(f))
```

**Comment by mrocklin** [comment]
Thank you for the excellent bug report and reproducible error @LunarLanding .  I'm able to reproduce, although oddly I had to be in a Jupyter notebook to see this.  Being in an IPython session didn't trigger this (although that could have something to do with how logs gets spit out). 

Intrestingly, this works ok

```python
from dask.distributed import Client, Event
import asyncio

async def f():
    async with Client(asynchronous=True) as client:
        e = await Event()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()

await f()
```

I wonder if this has something to do with how the IPython kernel handles await.  For example, if it handles things line by line, rather than block by block, then maybe we're creating that asyncio task in a thread-unsafe way?

**Comment by LunarLanding** [comment]
PS: I replicated the issue in an isolated python script. The question remains if this happens when scheduler and client are in different processes/machines. If that solves it, it will make the process of setting up dask a bit more contrived. Anyways, this errors:
```python
#!/usr/bin/env python
from distributed import Event,LocalCluster,Client,get_worker

def is_in_worker():
    try:
        get_worker()
    except ValueError:
        return False
    else:
        return True

import asyncio
async def f():

    cluster = await LocalCluster(asynchronous=True)
    
    async with  Client(cluster.scheduler_address,asynchronous=True):
        e = await Event()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()
        # leave commented out for tornado to break
        # if not is_in_worker():
        #     await e.set()
        #     await asyncio.sleep(.1)
        
        await asyncio.sleep(2)

    await cluster.close()
        
if __name__ == '__main__':
  asyncio.run(f())
```

Below is what I tested before:

My usecase is launching the cluster in one cell of a notebook and then using multiple times in others.
Therefore launching the cluster and closing it as soon as the cancel is launched (happens when the with scope ends) is not an option.
If I separate the cluster and client initialization into different cells, the error does not show up with this:

```python
from dask.distributed import LocalCluster, Client

cluster = await LocalCluster()

#in separate cell
from distributed import Event
import asyncio
async def f():
    async with Client(cluster.scheduler_address,asynchronous=True) as client:
        e = await Event()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()
    
await f()
```

But does appear with this:
```python
from dask.distributed import LocalCluster, Client

cluster = await LocalCluster()

#in separate cell
from distributed import Event
import asyncio
async def f():
    async with Client(cluster.scheduler_address,asynchronous=True) as client:
        e = await Event()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()
        
        await asyncio.sleep(2)
    
await f()
```

If I place cluster and client init in the same cell, I get the same behavior, so I don't think the issue is with the handling of await by jupyter.

```python
from dask.distributed import LocalCluster, Client
from distributed import Event

import asyncio
async def f():
    
    cluster = await LocalCluster(asynchronous=True)
    
    async with Client(cluster.scheduler_address,asynchronous=True) as client:
        e = await Event()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()
        #leave this line in for tornado to break
        await asyncio.sleep(2)
    
await f()
```

Closing the client (and perhaps reopening) on each call to a distributed method would affect any other objects currently using the same client. So I would have to open/close a new client for each call. That does not seem very nice performance wise.
What I am using now because the specifics of my usecase allow me to set the event after it has not triggered, and also to not care about sleeping for 100ms, is this:

```python
from distributed import Event,LocalCluster,Client,get_worker

def is_in_worker():
    try:
        get_worker()
    except ValueError:
        return False
    else:
        return True

import asyncio
async def f():

    cluster = await LocalCluster(asynchronous=True)
    
    async with  Client(cluster.scheduler_address,asynchronous=True):
        e = await Event()
        t = asyncio.create_task(e.wait())
        await asyncio.sleep(1)
        t.cancel()
        if not is_in_worker():
            await e.set()
            await asyncio.sleep(.1)
        
        await asyncio.sleep(2)
await f()
```

**Comment by LunarLanding** [comment]
I am starting to suspect that there is no built-in support for task cancellation in dask rpc protocol.
But I might be completely wrong, I would be grateful for comments.

Taking distributed.Event as an example, it is implemented using a scheduler plugin.
Its wait call is:

In distributed.Event
```python
def wait(self, timeout=None):
	#documentation stripped
	timeout = parse_timedelta(timeout)

	result = self.client.sync(
		self.client.scheduler.event_wait, name=self.name, timeout=timeout,
	)
	return result
```

The client.scheduler object is either  a rpc object or a PooledRPCCall

In PooledRPCCall ( core.py )
```python
def __getattr__(self, key):
        async def send_recv_from_rpc(**kwargs):
            if self.serializers is not None and kwargs.get("serializers") is None:
                kwargs["serializers"] = self.serializers
            if self.deserializers is not None and kwargs.get("deserializers") is None:
                kwargs["deserializers"] = self.deserializers
            comm = await self.pool.connect(self.addr)
            name, comm.name = comm.name, "ConnectionPool." + key
            try:
                result = await send_recv(comm=comm, op=key, **kwargs)
            finally:
                self.pool.reuse(self.addr, comm)
                comm.name = name

            return result

        return send_recv_from_rpc
```

In rpc ( core.py )
```python
def __getattr__(self, key):
        async def send_recv_from_rpc(**kwargs):
            if self.serializers is not None and kwargs.get("serializers") is None:
                kwargs["serializers"] = self.serializers
            if self.deserializers is not None and kwargs.get("deserializers") is None:
                kwargs["deserializers"] = self.deserializers
            try:
                comm = await self.live_comm()
                comm.name = "rpc." + key
                result = await send_recv(comm=comm, op=key, **kwargs)
            except (RPCClosed, CommClosedError) as e:
                raise e.__class__(
                    "%s: while trying to call remote method %r" % (e, key)
                )

            self.comms[comm] = True  # mark as open
            return result

        return send_recv_from_rpc
```

In either there is no special handling of the caller cancelling `send_recv_from_rpc` while `send_recv(comm=comm, op=key, **kwargs)` is still running.

Server-side, throwing a cancellation will also be mis-interpreted as a connection loss, and close the connection:

In Server , core.py:453
```python
logger.debug("Calling into handler %s", handler.__name__)
try:
    result = handler(comm, **msg)
    if inspect.isawaitable(result):
        result = asyncio.ensure_future(result)
        self._ongoing_coroutines.add(result)
        result = await result
except (CommClosedError, CancelledError) as e:
    if self.status == "running":
        logger.info("Lost connection to %r: %s", address, e)
    break
```

I am going to attempt to write a scheduler plugin that implements the following protocol on top of rpc:
If a client cancels a custom call, the cancellation is caught temporarily; then a cancellation request is sent to the server. 

That route will check a table of running custom calls for a match (either generate an id with the initial request or identify it via some other way).
If not present, nothing is done, the response is already on its way.
If present, a cancellation is sent to the custom call future. The cancellation error is caught and wrapped before being sent via the underlying rpc, and re-thrown client-side.
