### ISSUE TITLE
snappy import error

### ISSUE THREAD

**Issue by dumasl** [dask/distributed#3914]
**What happened**:

I'm trying to install a python module named snappy inside a python environment where dask.distributed is already installed. 

I got an import error with distributed module. I'm not sure this is a bug from distributed side, so here I am reporting the issue but quite asking for advice on how to handle this. There are obviously two different snappy module, and it seems to me the one imported from distributed is the one merely installed from a `pip install` instruction. Since snappy does seem to be mandatory for distributed could there be a workaround ? Maybe just an `try ... catch` around the snappy import ? 

Thank you for your help

**What I expected to happen**:

I actually did not know about the snappy import from distributed, so I expected nothing to prevent me from using the snappy module from https://pypi.org/project/snappy/. But it looks like distributed import a snappy module if it can (if installed) to use its compression methods. This leads to thinking the snappy module distributed can rely on is the python-snappy project https://pypi.org/project/python-snappy/.

**Minimal Complete Verifiable Example**:

Everything's fine with no snappy module

```
root@0a8a5ef7b540:/home/ai4geo# python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'snappy'
>>> import distributed
>>> 
```

After having installed snappy I no longer can import distributed
```
root@0a8a5ef7b540:/home/ai4geo# pip install snappy

root@0a8a5ef7b540:/home/ai4geo# python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distributed
Plink failed to import tkinter.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/distributed/__init__.py", line 3, in <module>
    from .actor import Actor, ActorFuture
  File "/usr/local/lib/python3.6/dist-packages/distributed/actor.py", line 6, in <module>
    from .client import Future, default_client
  File "/usr/local/lib/python3.6/dist-packages/distributed/client.py", line 42, in <module>
    from .batched import BatchedSend
  File "/usr/local/lib/python3.6/dist-packages/distributed/batched.py", line 8, in <module>
    from .core import CommClosedError
  File "/usr/local/lib/python3.6/dist-packages/distributed/core.py", line 17, in <module>
    from .comm import (
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/__init__.py", line 25, in <module>
    _register_transports()
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/__init__.py", line 16, in _register_transports
    from . import inproc
  File "/usr/local/lib/python3.6/dist-packages/distributed/comm/inproc.py", line 13, in <module>
    from ..protocol import nested_deserialize
  File "/usr/local/lib/python3.6/dist-packages/distributed/protocol/__init__.py", line 4, in <module>
    from .compression import compressions, default_compression
  File "/usr/local/lib/python3.6/dist-packages/distributed/protocol/compression.py", line 51, in <module>
    "compress": snappy.compress,
AttributeError: module 'snappy' has no attribute 'compress'
```

**Environment**:

- Distributed version: 2.14.0
- Python version: 3.6.9
- Operating System: ubuntu 18.04 bionic
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
That is unfortunate, but I don't think a simple try / except is what we
want either. We don't want to silently fail to use compression when a user
thinks they've enabled it by installing snappy.

**Comment by dumasl** [comment]
Well first thank you for your response.

I understand your point, though that does not make it easier :)

Should I consider this a "bugg" from the python-snappy (google compression module) arguing that this package should have been named differently perhaps ? 

Snappy must be some kind of a fancy keyword I missed along the road as I have found yet another project whose python module is called snappy (https://senbox.atlassian.net/wiki/spaces/SNAP/pages/50855941/Configure+Python+to+use+the+SNAP-Python+snappy+interface). 

Regarding my context I have trouble figuring out a proper way to deal with this. Considering I have no intent to use python-snappy, I thought my best option, was to alter the distributed import of snappy somehow but I get that this does not fit well into most scenarios.

**Comment by dumasl** [comment]
And I must add I understand that it is more of an unfortunate situation than it is a bug

**Comment by TomAugspurger** [comment]
One thing we could easily check is if `import snappy` returns a package that looks like https://snappy.math.uic.edu/installing.html. Then we could raise with a very informative error message.

That doesn't solve the issue of wanting to use distributed in an environment with `snappy` though.

**Comment by dumasl** [comment]
Yes I think that for as many snappy packages there are it would be very bad luck to find two of them with a `compress` module inside. So this is a good way to create a more informative error message.

However, does it really have to be an error ? Would be ok to raise a warning saying snappy could not be imported because it did not look like the snappy compression module ? Obviously warning messages might be overlooked and this could be a problem if somehow the snappy compression module was to change in a way that distributed will then silently fail to import it though it should have, but in that scenario this shall also means that distributed would have had to evolve to match the new snappy compression module API wouldn't it ?

(there is a strong possibility my english might not be quite correct so forgive me for that)
