### ISSUE TITLE
Serialization Error Messages Hidden

### ISSUE THREAD

**Issue by jfenc91** [dask/distributed#3975]
I am running a map_partitions that returns a dataframe with rows that have a large memory footprint. I dug out the following the exception below from the error log.

At first glance it doesn't really make sense because doing a simple test shows that dask can serialize dataframes:
`
>>> from distributed.protocol.serialize import serialize as s
>>> s(pd.DataFrame())
`

However, taking a closer look, it appears that there is a generic Exception catch here: 
https://github.com/dask/distributed/blob/2.21.0/distributed/protocol/serialize.py#L230

and if the on_error is set to raise like in the case of of moving partitions to disk during a map_partitions computation, we never get to see the message that is in the traceback format exception as shown here:

https://github.com/dask/distributed/blob/2.21.0/distributed/protocol/serialize.py#L234-L244

I suspect I am actually getting some sort of memory error, although I really have no way of knowing because the exception is reported as a TypeError

`
2020-07-21T17:12:03.599113035Z Traceback (most recent call last):
2020-07-21T17:12:03.599138316Z   File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
2020-07-21T17:12:03.599143053Z     ret = callback()
2020-07-21T17:12:03.599146719Z   File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
2020-07-21T17:12:03.599150027Z     future.result()
2020-07-21T17:12:03.599153015Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 2688, in memory_monitor
2020-07-21T17:12:03.599161122Z     k, v, weight = self.data.fast.evict()
2020-07-21T17:12:03.599164768Z   File "/usr/local/lib/python3.6/site-packages/zict/lru.py", line 89, in evict
2020-07-21T17:12:03.599192248Z     cb(k, v)
2020-07-21T17:12:03.599196364Z   File "/usr/local/lib/python3.6/site-packages/zict/buffer.py", line 60, in fast_to_slow
2020-07-21T17:12:03.599200149Z     self.slow[key] = value
2020-07-21T17:12:03.599203704Z   File "/usr/local/lib/python3.6/site-packages/zict/func.py", line 41, in __setitem__
2020-07-21T17:12:03.599207077Z     self.d[key] = self.dump(value)
2020-07-21T17:12:03.599210971Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 475, in serialize_bytelist
2020-07-21T17:12:03.599214257Z     header, frames = serialize(x, **kwargs)
2020-07-21T17:12:03.599217334Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 244, in serialize
2020-07-21T17:12:03.59922069Z     raise TypeError(msg, str(x)[:10000])
2020-07-21T17:12:03.599225052Z TypeError: ('Could not serialize object of type DataFrame.', '    distraction.sum.no_resample
`

**Environment**:

- Dask version: 2.21.0
- Python version: Python 3.6.9
- Install method (conda, pip, source): pip

**Comment by jakirkham** [comment]
Could you please supply an [MRE]( http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports )?

**Comment by jfenc91** [comment]
Sure thing @jakirkham !


> root@206a3b217134:/app# python -c "import resource; mem_limit=5e8; resource.setrlimit(resource.RLIMIT_AS, (mem_limit, mem_limit)); import pandas as pd; df = pd.DataFrame([3] *76000); I = {i:i for i in range(42000)}; from distributed.protocol.serialize import serialize as s; f=s(df, on_error='raise');"
> distributed.protocol.pickle - INFO - Failed to serialize        0
> 0      3
> 1      3
> 2      3
> 3      3
> 4      3
> ...   ..
> 75995  3
> 75996  3
> 75997  3
> 75998  3
> 75999  3
> [76000 rows x 1 columns]. Exception:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 244, in serialize
>     raise TypeError(msg, str(x)[:10000])
> TypeError: ('Could not serialize object of type DataFrame.', '       0\n0      3\n1      3\n2      3\n3      3\n4      3\n...   ..\n75995  3\n75996  3\n75997  3\n75998  3\n75999  3\n\n[76000 rows x 1 columns]')

**Comment by brycedrennan** [comment]
This recreates the issue and illustrates how the error is hidden
```python
import pandas as pd
from distributed.protocol.serialize import families, serialize

def bad(*a, **k):
    raise MemoryError("foo")

families["dask"] = (bad, bad, True)

serialize(pd.DataFrame([3] *76), on_error='raise')
```

**Comment by jakirkham** [comment]
Not following. That raises for me. Can you please include how you are installing things?

**Comment by brycedrennan** [comment]
Yes it incorrectly raises a TypeError and hides the real error.  In this case it should raise a MemoryError, but any other serialization error would similarly be hidden and thus hide from the user information about what the real problem is.

**Comment by jfenc91** [comment]
Ya forcing a memory error at a particular spot with small data seems pretty env dependent. Here is a docker example. Hope it helps!

`docker run  python:3.6.9-slim-stretch /bin/bash -c "apt-get update && apt-get install gcc -y && pip install dask distributed pandas && python -c \"import resource; mem_limit=4.88e8; resource.setrlimit(resource.RLIMIT_AS, (mem_limit, mem_limit)); import pandas as pd; df = pd.DataFrame([3] *76000); I = {i:i for i in range(4000)}; from distributed.protocol.serialize import serialize as s; f=s(df, on_error='raise');\""`

**Comment by jakirkham** [comment]
I see. Thanks for clarifying 🙂

IIUC that is intentional as we use that to [check for errors]( https://github.com/dask/distributed/blob/ef168a471a7b6b4dc4b023196afc229cda109608/distributed/protocol/serialize.py#L107-L108 ).

One option might be to handle some specific exceptions differently. If we go this route, is it just `MemoryError` or are there other specific errors we'd like to handle differently? Also what should we be doing in these other cases?

There may be other options, but nothing is coming to me atm. @mrocklin, do you have thoughts here? 😉

**Comment by jfenc91** [comment]
@jakirkham Using explicit [exception chaining](https://www.python.org/dev/peps/pep-3134/) seems like a pythonic approach to providing more visibility here. Is there some reason that is not ideal?

**Comment by jakirkham** [comment]
Are we merely wanting to capture the history? Or are we wanting to handle these exceptions? Still trying to understand the desired outcome here.

**Comment by brycedrennan** [comment]
We're wanting to run dask at scale in a production environment and have useful error messages that don't mislead about what is going wrong.  (like having a MemoryError turn into a TypeError).  I'm working on a PR.
