### ISSUE TITLE
Memory errors cause jobs to hang forever due to lost tasks

### ISSUE THREAD

**Issue by jfenc91** [dask/distributed#4001]
**What happened**:
The job is incomplete yet all workers are inactive. On the job dashboard the scheduler shows that specific workers are processing tasks yet those workers themselves do not believe they have any tasks assigned to them. 

**What you expected to happen**: All jobs or tasks should fail for cause or complete successfully. Having jobs hang is particularly unfortunate in autoscaling situations. If a task fails some configurable retry logic (like what dask already has) can be appreciated. 

**Minimal Complete Verifiable Example**: Unfortunately, I have not been able to distill this out to a finely packaged example. However this seemed serious enough that it should at least be documented and I am providing stack traces as a starting point for an investigation.

> 2020-07-30T17:15:32.557581194Z Traceback (most recent call last):
> 2020-07-30T17:15:32.557646283Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 75, in loads
> 2020-07-30T17:15:32.557654567Z     return pickle.loads(x)
> 2020-07-30T17:15:32.563892273Z MemoryError
> 2020-07-30T17:15:32.564257027Z distributed.protocol.core - CRITICAL - Failed to deserialize
> 2020-07-30T17:15:32.564271549Z Traceback (most recent call last):
> 2020-07-30T17:15:32.564275837Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/core.py", line 130, in loads
> 2020-07-30T17:15:32.564280161Z     value = _deserialize(head, fs, deserializers=deserializers)
> 2020-07-30T17:15:32.564284221Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
> 2020-07-30T17:15:32.564288496Z     return loads(header, frames)
> 2020-07-30T17:15:32.564292221Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
> 2020-07-30T17:15:32.564296429Z     return pickle.loads(x, buffers=buffers)
> 2020-07-30T17:15:32.564300308Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 75, in loads
> 2020-07-30T17:15:32.564304709Z     return pickle.loads(x)
> 2020-07-30T17:15:32.564308605Z MemoryError
> 2020-07-30T17:15:32.564782561Z distributed.worker - ERROR -
> 2020-07-30T17:15:32.564792065Z Traceback (most recent call last):
> 2020-07-30T17:15:32.564796468Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 1983, in gather_dep
> 2020-07-30T17:15:32.564800758Z     self.rpc, deps, worker, who=self.address
> 2020-07-30T17:15:32.564804425Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 3258, in get_data_from_worker
> 2020-07-30T17:15:32.564808582Z     return await retry_operation(_get_data, operation="get_data_from_worker")
> 2020-07-30T17:15:32.564812386Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils_comm.py", line 390, in retry_operation
> 2020-07-30T17:15:32.564816577Z     operation=operation,
> 2020-07-30T17:15:32.564820054Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils_comm.py", line 360, in retry
> 2020-07-30T17:15:32.564824219Z     return await coro()
> 2020-07-30T17:15:32.564827738Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 3245, in _get_data
> 2020-07-30T17:15:32.564841535Z     max_connections=max_connections,
> 2020-07-30T17:15:32.564845179Z   File "/usr/local/lib/python3.6/site-packages/distributed/core.py", line 644, in send_recv
> 2020-07-30T17:15:32.564849305Z     response = await comm.read(deserializers=deserializers)
> 2020-07-30T17:15:32.564853196Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py", line 206, in read
> 2020-07-30T17:15:32.564857364Z     allow_offload=self.allow_offload,
> 2020-07-30T17:15:32.564861532Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/utils.py", line 87, in from_frames
> 2020-07-30T17:15:32.56486568Z     res = _from_frames()
> 2020-07-30T17:15:32.56486939Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/utils.py", line 66, in _from_frames
> 2020-07-30T17:15:32.564873599Z     frames, deserialize=deserialize, deserializers=deserializers
> 2020-07-30T17:15:32.564877466Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/core.py", line 130, in loads
> 2020-07-30T17:15:32.564882347Z     value = _deserialize(head, fs, deserializers=deserializers)
> 2020-07-30T17:15:32.564885906Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
> 2020-07-30T17:15:32.564889877Z     return loads(header, frames)
> 2020-07-30T17:15:32.564893568Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
> 2020-07-30T17:15:32.56489761Z     return pickle.loads(x, buffers=buffers)
> 2020-07-30T17:15:32.564901404Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 75, in loads
> 2020-07-30T17:15:32.564905455Z     return pickle.loads(x)
> 2020-07-30T17:15:32.564909273Z MemoryError
> 2020-07-30T17:15:32.566460817Z distributed.utils - ERROR -
> 2020-07-30T17:15:32.566471093Z Traceback (most recent call last):
> 2020-07-30T17:15:32.566474979Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils.py", line 656, in log_errors
> 2020-07-30T17:15:32.566479211Z     yield
> 2020-07-30T17:15:32.566482409Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 1983, in gather_dep
> 2020-07-30T17:15:32.566486498Z     self.rpc, deps, worker, who=self.address
> 2020-07-30T17:15:32.566490285Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 3258, in get_data_from_worker
> 2020-07-30T17:15:32.566494629Z     return await retry_operation(_get_data, operation="get_data_from_worker")
> 2020-07-30T17:15:32.566498632Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils_comm.py", line 390, in retry_operation
> 2020-07-30T17:15:32.566502865Z     operation=operation,
> 2020-07-30T17:15:32.566506284Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils_comm.py", line 360, in retry
> 2020-07-30T17:15:32.566516146Z     return await coro()
> 2020-07-30T17:15:32.566519844Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 3245, in _get_data
> 2020-07-30T17:15:32.566523844Z     max_connections=max_connections,
> 2020-07-30T17:15:32.566527561Z   File "/usr/local/lib/python3.6/site-packages/distributed/core.py", line 644, in send_recv
> 2020-07-30T17:15:32.566531621Z     response = await comm.read(deserializers=deserializers)
> 2020-07-30T17:15:32.56653541Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py", line 206, in read
> 2020-07-30T17:15:32.566539911Z     allow_offload=self.allow_offload,
> 2020-07-30T17:15:32.566543736Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/utils.py", line 87, in from_frames
> 2020-07-30T17:15:32.566547928Z     res = _from_frames()
> 2020-07-30T17:15:32.566551685Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/utils.py", line 66, in _from_frames
> 2020-07-30T17:15:32.566555919Z     frames, deserialize=deserialize, deserializers=deserializers
> 2020-07-30T17:15:32.566559861Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/core.py", line 130, in loads
> 2020-07-30T17:15:32.566564219Z     value = _deserialize(head, fs, deserializers=deserializers)
> 2020-07-30T17:15:32.566568163Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
> 2020-07-30T17:15:32.566572354Z     return loads(header, frames)
> 2020-07-30T17:15:32.566576027Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
> 2020-07-30T17:15:32.566580218Z     return pickle.loads(x, buffers=buffers)
> 2020-07-30T17:15:32.566584052Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 75, in loads
> 2020-07-30T17:15:32.566588332Z     return pickle.loads(x)
> 2020-07-30T17:15:32.566591841Z MemoryError
> 2020-07-30T17:15:32.594582913Z tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f01da945ac8>>, <Task finished coro=<Worker.gather_dep() done, defined at /usr/local/lib/python3.6/site-packages/distributed/worker.py:1965> exception=MemoryError()>)
> 2020-07-30T17:15:32.59461393Z Traceback (most recent call last):
> 2020-07-30T17:15:32.594619584Z   File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
> 2020-07-30T17:15:32.594624038Z     ret = callback()
> 2020-07-30T17:15:32.594627493Z   File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
> 2020-07-30T17:15:32.594631515Z     future.result()
> 2020-07-30T17:15:32.594634949Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 1983, in gather_dep
> 2020-07-30T17:15:32.594639363Z     self.rpc, deps, worker, who=self.address
> 2020-07-30T17:15:32.594660281Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 3258, in get_data_from_worker
> 2020-07-30T17:15:32.594672261Z     return await retry_operation(_get_data, operation="get_data_from_worker")
> 2020-07-30T17:15:32.59467623Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils_comm.py", line 390, in retry_operation
> 2020-07-30T17:15:32.594681412Z     operation=operation,
> 2020-07-30T17:15:32.594685037Z   File "/usr/local/lib/python3.6/site-packages/distributed/utils_comm.py", line 360, in retry
> 2020-07-30T17:15:32.594688815Z     return await coro()
> 2020-07-30T17:15:32.594692078Z   File "/usr/local/lib/python3.6/site-packages/distributed/worker.py", line 3245, in _get_data
> 2020-07-30T17:15:32.59469656Z     max_connections=max_connections,
> 2020-07-30T17:15:32.594700166Z   File "/usr/local/lib/python3.6/site-packages/distributed/core.py", line 644, in send_recv
> 2020-07-30T17:15:32.594704112Z     response = await comm.read(deserializers=deserializers)
> 2020-07-30T17:15:32.594707614Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py", line 206, in read
> 2020-07-30T17:15:32.594711256Z     allow_offload=self.allow_offload,
> 2020-07-30T17:15:32.59471451Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/utils.py", line 87, in from_frames
> 2020-07-30T17:15:32.594718167Z     res = _from_frames()
> 2020-07-30T17:15:32.594721401Z   File "/usr/local/lib/python3.6/site-packages/distributed/comm/utils.py", line 66, in _from_frames
> 2020-07-30T17:15:32.594724998Z     frames, deserialize=deserialize, deserializers=deserializers
> 2020-07-30T17:15:32.594728638Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/core.py", line 130, in loads
> 2020-07-30T17:15:32.594732284Z     value = _deserialize(head, fs, deserializers=deserializers)
> 2020-07-30T17:15:32.594736923Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
> 2020-07-30T17:15:32.594740794Z     return loads(header, frames)
> 2020-07-30T17:15:32.594744279Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
> 2020-07-30T17:15:32.59474842Z     return pickle.loads(x, buffers=buffers)
> 2020-07-30T17:15:32.59475217Z   File "/usr/local/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 75, in loads
> 2020-07-30T17:15:32.594755911Z     return pickle.loads(x)
> 2020-07-30T17:15:32.594759148Z MemoryError

**Environment**:

- Dask version: 2.21.0
- Python/OS version: running in docker python:3.6.9-slim-stretch
- Install method (conda, pip, source): pip

**Comment by jakirkham** [comment]
Thanks for reporting, Jeff! Sorry you are having trouble.

Is there some short code that could be shared (even if not fully minimized)?

**Comment by jakirkham** [comment]
Friendly nudge @jfenc91 😉

**Comment by ncclementi** [comment]
@jfenc91 Checking in here, are you still having this problem, would you be able to provide an update?
