### ISSUE TITLE
Cluster dies with "failed to deserialize" and "IndexError: pop from empty list"

### ISSUE THREAD

**Issue by Keou0007** [dask/distributed#4099]
**What happened**: 
I use dask to dispatch embarrassingly parallel vtk processing jobs. If the vtk files are large-ish, the dask cluster dies halfway through processing the files.

**What you expected to happen**:
The files should be processed and when all of them are done the dask cluster exits cleanly.

**Minimal Complete Verifiable Example**:
 Minimal example is difficult because of the complexity of my dispatch system, plus the function called in parallel must be part of an installed package or else I get errors saying that vtk objects are not pickle-able.  Nonetheless, I've been able to produce a working example that produces the error fairly simply and consistently.
Download and unzip the attached files. Install the vtktest package (and dependencies) using pip and run the test scripts to see the failure.
[mcve.zip](https://github.com/dask/distributed/files/5183344/mcve.zip)
e.g.

```
$ unzip mcve.zip
$ cd mcve
$ conda create -n vtktest python=3.8 vtk=8 dask distributed psutil tqdm tornado asyncssh
$ conda activate vtktest
$ pip install vtktest/
$ python run_vtk_test_succeeds.py
$ python run_vtk_test_fails.py
```

The two scripts are identical except that the "succeeds" script processes the small vtk file and the "fails" script processes the big vtk file. On my mac, running the above proceedure I get these outputs:

<details><summary>Success</summary>

```
$ python run_vtk_test_succeeds.py 
INFO:vtktest.parallel:launching dask LocalCluster with 4 workers 
DEBUG:asyncio:Using selector: KqueueSelector 
DEBUG:asyncio:Using selector: KqueueSelector 
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0003.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0010.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0011.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0006.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0008.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0001.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0009.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0000.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0007.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0005.vtp) 
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0004.vtp) 
Success! 

```

</details>

<details><summary>Failure</summary>

```
$ python run_vtk_test_fails.py 
INFO:vtktest.parallel:launching dask LocalCluster with 4 workers
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:dask.vtktest.convert:vtk converted in 4.3 s (isoSurfaceCell-big_0001.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 4.3 s (isoSurfaceCell-big_0006.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 4.4 s (isoSurfaceCell-big_0010.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 4.4 s (isoSurfaceCell-big_0008.vtp)
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
distributed.worker - WARNING -  Compute Failed
Function:  inner
args:      ('0.6/isoSurfaceCell-big.vtk', 'isoSurfaceCell-big_0006.vtp')
kwargs:    {}
Exception: IndexError('pop from empty list')

distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
distributed.worker - WARNING -  Compute Failed
Function:  inner
args:      ('0.8/isoSurfaceCell-big.vtk', 'isoSurfaceCell-big_0008.vtp')
kwargs:    {}
Exception: IndexError('pop from empty list')

/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/semaphore.py:252: RuntimeWarning: Closing semaphore semaphore-96153c55c35744e2b1bbc3e17376b4c2 but there remain unreleased leases ['4300952401ee46de90639f352105afb0', '77db9a1d0db74b99a69522788dcbca08', 'db72c24cde334261a2d967ec970cbd93', 'dfae5aff6a434731a22854c89b8dfe8e']
  warnings.warn(
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
Traceback (most recent call last):
  File "run_vtk_test_fails.py", line 34, in <module>
    ret = dmap(convert_vtk, in_out, n_procs=mp.cpu_count(), star=True, p_bar=False)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 135, in dmap
    return _dmap_local(func, args, n_procs, star, p_bar, batch, change_cwd, kwargs)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 189, in _dmap_local
    return _dmap_client(func, args, client, star, p_bar, batch, change_cwd, kwargs)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 364, in _dmap_client
    return client.gather(futures)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 1985, in gather
    return self.sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 833, in sync
    return sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 1850, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 417, in inner
    return ret
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/semaphore.py", line 491, in __exit__
    self.release()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/semaphore.py", line 476, in release
    return self.client.sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 833, in sync
    return sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/core.py", line 883, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/core.py", line 666, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/comm/tcp.py", line 204, in read
    msg = await from_frames(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/comm/utils.py", line 87, in from_frames
    res = _from_frames()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    return protocol.loads(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
```

</details>

Weirdly, sometimes if I then rerun the succeeds script, it will pick up the big vtk files that didn't get deleted when the previous script failed, and successfully process both the small and big files with no errors. Other times it will error again and I have no idea why this happens seemingly randomly. I'd say this is about 50/50.

<details><summary>Second Run Success</summary>

```
$ python run_vtk_test_succeeds.py 
INFO:vtktest.parallel:launching dask LocalCluster with 4 workers
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0003.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0011.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0001.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0006.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0008.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0009.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0000.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.7 s (isoSurfaceCell-small_0007.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0002.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0005.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0010.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.6 s (isoSurfaceCell-small_0004.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.8 s (isoSurfaceCell-big_0011.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 4.3 s (isoSurfaceCell-big_0003.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.5 s (isoSurfaceCell-big_0006.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.5 s (isoSurfaceCell-big_0000.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.6 s (isoSurfaceCell-big_0008.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.9 s (isoSurfaceCell-big_0005.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.8 s (isoSurfaceCell-big_0007.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.3 s (isoSurfaceCell-big_0010.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 5.2 s (isoSurfaceCell-big_0001.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 5.3 s (isoSurfaceCell-big_0004.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.6 s (isoSurfaceCell-big_0002.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 3.6 s (isoSurfaceCell-big_0009.vtp)
Success!
```

</details>

<details><summary>Second Run Failure</summary>

```
$ python run_vtk_test_succeeds.py 
INFO:vtktest.parallel:launching dask LocalCluster with 4 workers
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0010.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0006.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0001.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0008.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0000.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0009.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0007.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0002.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0005.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0004.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0003.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 0.5 s (isoSurfaceCell-small_0011.vtp)
DEBUG:dask.vtktest.convert:vtk converted in 5.3 s (isoSurfaceCell-big_0011.vtp)
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
distributed.worker - WARNING -  Compute Failed
Function:  inner
args:      ('1.1/isoSurfaceCell-big.vtk', 'isoSurfaceCell-big_0011.vtp')
kwargs:    {}
Exception: IndexError('pop from empty list')

DEBUG:dask.vtktest.convert:vtk converted in 5.3 s (isoSurfaceCell-big_0010.vtp)
/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/semaphore.py:252: RuntimeWarning: Closing semaphore semaphore-66fc4b9b312a4b0a8803f6d0bf0faf2e but there remain unreleased leases ['24718da6ebf04627a0dde8bf82dbb1a5', '47ff5f43ba144deb87ae1cb155798202', '51817c2438d24072a7fdaf8184d79b1e', '8fe931500fd14881b42087e90735aaef']
  warnings.warn(
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 4 seconds, killing
Traceback (most recent call last):
  File "run_vtk_test_succeeds.py", line 35, in <module>
    ret = dmap(convert_vtk, in_out, n_procs=mp.cpu_count(), star=True, p_bar=False)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 135, in dmap
    return _dmap_local(func, args, n_procs, star, p_bar, batch, change_cwd, kwargs)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 189, in _dmap_local
    return _dmap_client(func, args, client, star, p_bar, batch, change_cwd, kwargs)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 364, in _dmap_client
    return client.gather(futures)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 1985, in gather
    return self.sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 833, in sync
    return sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 1850, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/vtktest/parallel.py", line 417, in inner
    return ret
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/semaphore.py", line 491, in __exit__
    self.release()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/semaphore.py", line 476, in release
    return self.client.sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 833, in sync
    return sync(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/core.py", line 883, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/core.py", line 666, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/comm/tcp.py", line 204, in read
    msg = await from_frames(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/comm/utils.py", line 87, in from_frames
    res = _from_frames()
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    return protocol.loads(
  File "/Users/shannon/opt/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
```

</details>

**Anything else we need to know?**:

If I run the "fails" script repeatedly, around 25-30% of the time it succeeds with no errors.
I also see the same errors on CentOS 6 and 7, and I see the same errors (or close enough) dispatching to a distributed cluster using an SSHCLuster.

**Environment**:

- Dask version: 2.25.0
- Python version: 3.8.5
- Operating System: macOS, CentOS 6, CentOS 7
- Install method (conda, pip, source): conda

**Comment by mrocklin** [comment]
Thank you for the issue @Keou0007 .  Can I ask you to verify that you have the same version of the `dask` and `distributed` libraries installed on all of the machines?

Also, cc @jakirkham who has been playing around in the protocol/serialization code a bit recently and @quasiben for context.

**Comment by Keou0007** [comment]
yup, versions are the same

**Comment by mrocklin** [comment]
Thanks for checking.  In that case I'm going to defer to @jakirkham who has been modifying this code the most recently if he has time.

**Comment by Keou0007** [comment]
I'd be more than happy to help if there's something I can do, but I've tried tracking this down for a while now and I'm a little out of my depth.

**Comment by Keou0007** [comment]
Thinking about this problem some more, it seems weird to me that something would fail to deserialize based on the size of a file being processed. The file is not passed to the worker, only the path to the file. This suggests to me that during processing of the file something is timing out while the file is being processed, which is causing the deserialisation to fail and this only happens when the file is big. The VTK library, as far as I can tell, does not release the GIL when it passes to it's underlying C code, so perhaps a long running GIL holding process is the cause here?

While this definitely appears to be a bug, possibly there is a timeout setting somewhere I can increase that would prevent this from happening without requiring a change to the code? I have already changed "distributed.scheduler.locks.lease-timeout" to be 1 hr to get rid of timeout errors I was seeing in the Semaphore. Is there another timeout setting somewhere that would impact on tcp connections and heartbeats I could change? I've been searching the docs and source code but not coming up with much.

**Comment by jakirkham** [comment]
Are there some versions of Dask that work for your use case? Are there ones that don't? Can we identify a transition version where it changes?

Is this something that can be reproduced without VTK?

**Comment by jakirkham** [comment]
The fact that this doesn't consistently fail makes me thinking this is some kind of network failure (some packets are lost) as opposed to a serialization issue (reliably broken messages are generated).

**Comment by Keou0007** [comment]
I've done some more looking, digging in on the "compute failed" message. My assumption is that occasionally the worker fails to run the dispatched function for whatever reason and then when the worker is checking the completion of the job (at distributed.worker line 2562), it finds something other than `"task-finished"` in `  result["op"]` and processes the failure accordingly. Whether this is happening because the task has actually failed, or because the worker isn't waiting long enough for the VTK process to finish when the file is big, I'm not sure.
I was able to get all the jobs to complete successfully, even with the failures, by adding "retries=5" argument to my client.submit call to have the scheduler retry the failed tasks, but in that case I still get compute failed tracebacks and the `client.gather(futures)` call never returns, so the program stalls after all the files are processed. See the output below.

<details><summary>output</summary>

```
$ python run_vtk_test_fails.py 
vtktest.parallel 141 INFO launching dask LocalCluster with 4 workers
vtktest.parallel 371 DEBUG dask gathering futures
dask.vtktest.convert 17 DEBUG vtk converted in 4.8 s (isoSurfaceCell-big_0011.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 4.8 s (isoSurfaceCell-big_0001.vtp)
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/envs/vtktest/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/envs/vtktest/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
dask.vtktest.convert 17 DEBUG vtk converted in 4.9 s (isoSurfaceCell-big_0010.vtp)
distributed.worker - WARNING -  Compute Failed
Function:  inner
args:      ('1.1/isoSurfaceCell-big.vtk', 'isoSurfaceCell-big_0011.vtp')
kwargs:    {}
Exception: IndexError('pop from empty list')

dask.vtktest.convert 17 DEBUG vtk converted in 4.9 s (isoSurfaceCell-big_0006.vtp)
distributed.worker - WARNING -  Compute Failed
Function:  inner
args:      ('0.1/isoSurfaceCell-big.vtk', 'isoSurfaceCell-big_0001.vtp')
kwargs:    {}
Exception: IndexError('pop from empty list')

distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/shannon/opt/miniconda3/envs/vtktest/lib/python3.8/site-packages/distributed/protocol/core.py", line 125, in loads
    small_header = frames.pop()
IndexError: pop from empty list
distributed.worker - WARNING -  Compute Failed
Function:  inner
args:      ('1.0/isoSurfaceCell-big.vtk', 'isoSurfaceCell-big_0010.vtp')
kwargs:    {}
Exception: IndexError('pop from empty list')

dask.vtktest.convert 17 DEBUG vtk converted in 3.3 s (isoSurfaceCell-big_0000.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.3 s (isoSurfaceCell-big_0009.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.2 s (isoSurfaceCell-big_0010.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.2 s (isoSurfaceCell-big_0004.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.2 s (isoSurfaceCell-big_0005.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.2 s (isoSurfaceCell-big_0002.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.1 s (isoSurfaceCell-big_0001.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.2 s (isoSurfaceCell-big_0003.vtp)
dask.vtktest.convert 17 DEBUG vtk converted in 3.0 s (isoSurfaceCell-big_0011.vtp)

```
</details>

Digging into the traceback some more, the actual `IndexError` exception comes in at distributed.protocol.core line 125 due to the `frames` list being empty, which all happens as part of the worker heartbeat callback. This is where I start to lose understanding of what's happening and can't follow the trail as well as I'd like. I can't tell if the `loads` function is being run in the worker or the scheduler. Obviously something that's happening here is resulting in a failed tcp message, which manifests as an empty `frames` list producing an index error on pop. The solution is either going to be to figure out why the message is failing and fix that (outside my skill level I think), or to adjust the loads function so that is can handle an empty frames list without throwing an exception. I could probably do the second option myself, but I wouldn't know what an appropriate way of handling such a situation would be, without potentially creating unintended side effects elsewhere.

**Comment by Keou0007** [comment]
> Are there some versions of Dask that work for your use case? Are there ones that don't? Can we identify a transition version where it changes?
> 
> Is this something that can be reproduced without VTK?

I don't think this have ever worked 100% for me. My dispatching system is something I've put together fairly recently and my test case only has small files, so it didn't see these errors till I starting trying to use it in production on larger files.

**Comment by mdering** [comment]
has anyone identified the cause of this?

**Comment by Keou0007** [comment]
I gave up not long after my last post. It was taking too much time and I have higher priorities. I'm no longer using dask in my  work because I could never get it to work reliably and I rewrote other parts of my code to run a lot faster without needing parallelisation beyond a single node.

If anybody has any ideas I'd be happy to test solutions, I still have all the original code. But I'm not going to spend anymore time trying to figure out the problem.

**Comment by showkeyjar** [comment]
sad story, I faced same problem.

**Comment by jakirkham** [comment]
I think we need a minimal reproducer to investigate further. While these errors are (I’m sure) frustrating, those of us developing Dask are flying blind. So are not able to advise (let alone come up with a fix). If someone could come up with and share a minimal reproducer here, that would really help get things moving. Thanks!

**Comment by showkeyjar** [comment]
I think dask has poor of robust design, and many unsuitable warning and error messages.
those make user confused.

for example:
when create a dask client job, some worker may crashed, then it print a message:
`distributed.nanny - WARNING - Restarting worker`
in fact, the task that use dask, has been failed, but user still wait for dask to save the world
it waste time to wait for few minutes even few hours.
as a result the user’s mood is broken!

I don't know why dask has so many unsuitable messages to output.
maybe the developers must eat your own dog food.
