### ISSUE TITLE
Progress bar does not work with SSL

### ISSUE THREAD

**Issue by jennalc** [dask/distributed#4121]
progress() method fails with the following message when SSL is enabled for scheduler and client:

```
ERROR tornado.application - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f24a17a8f50>>, <Task finished coro=<MultiProgressBar.listen() done, defined at /var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/diagnostics/progressbar.py:238> exception=TypeError('TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None')>)
Traceback (most recent call last):
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/diagnostics/progressbar.py", line 260, in listen
    connection_args=self.client().connection_args if self.client else None,
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/comm/core.py", line 318, in connect
    _(), timeout=min(deadline - time(), retry_timeout_backoff)
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/comm/core.py", line 290, in _
    loc, deserialize=deserialize, **connection_args
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/comm/tcp.py", line 346, in connect
    kwargs = self._get_connect_args(**connection_args)
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/comm/tcp.py", line 387, in _get_connect_args
    ctx = _expect_tls_context(connection_args)
  File "/var/conductor/miniconda483/anaconda/envs/e4/lib/python3.7/site-packages/distributed/comm/tcp.py", line 323, in _expect_tls_context
    "  Instead got %s" % str(ctx)
TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None
```

In my environment, edited progressbar.py line 260 to change way connection args are retrieved to:

```
self.comm = await connect(
            self.scheduler, **(self.client().connection_args if self.client else {})
        )
```

After this change, progress bar works well with SSL client.

**Comment by mrocklin** [comment]
Thanks for the report and the fix.  Would you be interested in submitting a
pull request with your change?

**Comment by jennalc** [comment]
Thanks for your quick response @mrocklin 
I am new to using git, so please bare with me a little bit. I have submitted a pull request & checks are running now. I am not sure how to link it to this issue.

**Comment by jrbourbeau** [comment]
Closed by https://github.com/dask/distributed/pull/4122
