### ISSUE TITLE
Exception in thread and deadlock after creating Client

### ISSUE THREAD

**Issue by PedroMDuarte** [dask/distributed#4124]
**What happened**:

I am trying to instantiate and use a Client as part of handling an http request. 

I see the following on the logs:

```
2020-09-24 00:24:37.955 PDT
distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=30, interval=7

2020-09-24 00:24:37.955 PDT
distributed.comm.tcp - DEBUG - Setting TCP user timeout: 100000 ms

2020-09-24 00:24:37.959 PDT
distributed.comm.tcp - DEBUG - Setting TCP keepalive: nprobes=10, idle=30, interval=7

2020-09-24 00:24:37.960 PDT
distributed.comm.tcp - DEBUG - Setting TCP user timeout: 100000 ms

2020-09-24 00:24:37.968 PDT
[c11e9743e076e8d339f5e62f7dd16dc2] established connection to dask cluster: <Client: 'tcp://10.32.0.140:8786' processes=3 threads=12, memory=6.00 GB>

2020-09-24 00:24:38.095 PDT
Exception in thread Thread-19:

2020-09-24 00:24:38.095 PDT
Traceback (most recent call last): File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() File "/usr/local/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.7/asyncio/base_events.py", line 528, in run_forever 'Cannot run the event loop while another loop is running') RuntimeError: Cannot run the event loop while another loop is running
```

**What you expected to happen**:

I was hoping that the client would start normally, and I could use it, but instead the request hangs forever. 

**Minimal Complete Verifiable Example**:

It is hard to come up with a minimal way to reproduce the problem. The issue might have something to do with other threads in the web server. The problem from dask's point of view is that instead of failing more directly it emits the exception traceback (from a thread) and then blocks forever. 

**Anything else we need to know?**:

If you all can think of ways in which I could debug this issue they would be much appreciated. 

**Environment**:

- Dask version: 2.27.0
- Python version: 3.7
- Operating System: linux
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
You would have to provide more information in order for us to be useful.
If you are using Dask within an async environment, such as with asyncio or
tornado then I recommend using Dask in asynchronous mode. See
https://examples.dask.org/applications/async-web-server.html for an example

**Comment by PedroMDuarte** [comment]
Thanks @mrocklin , I have been looking more closely at the problem today and found that it shows up only with recent versions of `gcsfs` and `fsspec`.  

More details:
```
FAILS:
"dask[bag]==2.27.0",
"distributed==2.27.0",
"gcsfs==0.7.1",
"fsspec==0.8.3",

WORKS:
"dask[bag]==2.27.0",
"distributed==2.27.0",
"gcsfs==0.6.2",
"fsspec==0.8.0",
```

From what I can tell gcsfs 0.7 is also running an io loop, which defaults to `asyncio.get_event_loop()` if a loop is not provided explicitly: https://github.com/intake/filesystem_spec/blob/master/fsspec/asyn.py#L133 

This leads to the following question: Would it be ok to use the dask Client's loop as one of the `storage_options` when calling `read_avro`? 

My code is currently doing the following:
```
with Client(address):
    df = dask.bag.read_avro(
        paths,
        storage_options=dict(access="read_only"),
    ).to_dataframe()
    <... operate on dataframe ...>
```
   
I am wondering if it would be reasonable at all to do something like:
```
with Client(address) as client:
    df = dask.bag.read_avro(
        paths,
        storage_options=dict(access="read_only", loop=client.loop),
    ).to_dataframe()
    <... operate on dataframe ...>
```

**Comment by PedroMDuarte** [comment]
Update, I just tried passing `loop=client.loop` on the `storage_options` and that did not work.  Crashes as follows:
```
Traceback (most recent call last):
  <REDACTED>
  File "/usr/local/lib/python3.7/site-packages/dask/bag/avro.py", line 102, in read_avro
    urlpath, mode="rb", storage_options=storage_options
  File "/usr/local/lib/python3.7/site-packages/fsspec/core.py", line 610, in get_fs_token_paths
    fs = cls(**options)
  File "/usr/local/lib/python3.7/site-packages/fsspec/spec.py", line 58, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gcsfs/core.py", line 267, in __init__
    self._session = sync(self.loop, get_client)
  File "/usr/local/lib/python3.7/site-packages/fsspec/asyn.py", line 59, in sync
    asyncio.run_coroutine_threadsafe(f(), loop=loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 846, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
AttributeError: 'AsyncIOLoop' object has no attribute 'call_soon_threadsafe'
```

**Comment by PedroMDuarte** [comment]
To add more context, I tried reproducing in a minimal way on a local shell but could not reproduce. This may indicate that there can be some interaction with other parts of our web server. 

This is what I tried for reproducibility:

```
In [1]: import dask.bag

In [2]: from distributed import Client

In [3]: client = Client()

In [4]: client.loop
Out[4]: <tornado.platform.asyncio.AsyncIOLoop at 0x7f905a2d1550>

In [5]: path = "gs://<REDACTED>"

In [6]: df = dask.bag.read_avro(path, storage_options=dict(access="read_only"))

In [7]: ans = df.compute()

In [8]: len(ans)
Out[8]: 84

In [9]: from gcsfs import GCSFileSystem

In [10]: fs = GCSFileSystem(access="read_only")

In [11]: fs.loop
Out[11]: <_UnixSelectorEventLoop running=True closed=False debug=False>
```

Our webserver is a flask app, run with gunicorn using gevent workers.  It seems that `distributed.Client` is able to start an IO loop in a separate thread under that environment, but `fsspec` fails as it [defaults to the asyncio loop](https://github.com/intake/filesystem_spec/blob/master/fsspec/asyn.py#L135).

**Comment by martindurant** [comment]
Note that distributed uses a Tornado loop, but fsspec expects an asyncio loop. For a long time now, the former is a wrapper of the latter, and you can unwrap it like
```
asyncloop = tornadoloop.asyncio_loop
```

The way in which the two libraries start a new loop is rather similar, since I was, of course, familiar with the distributed code.
