### ISSUE TITLE
Persistent client connection

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/distributed#4149]
I'm creating an aiohttp server that maintains a persistent client connection to the dask distributed scheduler.

Is there a way to hook into the client so I can know when the client has lost connection to the scheduler, and when its attempting to re-establishing connections.

This way I could block/queue up tasks before sending it to the client and report to the user on the web frontend that the scheduler is down, or the client has lost connection.

**Comment by quasiben** [comment]
Would checking `client.status == 'closed'`  or `client.scheduler is None` work for you ?

**Comment by CMCDragonkai** [comment]
It needs to be an async callback? Unless you are suggesting me to asynchronously poll.

On 7 October 2020 12:10:50 am AEDT, Benjamin Zaitlen <notifications@github.com> wrote:
>Would checking `client.status == 'closed'`  or `client.scheduler is
>None` work for you ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/distributed/issues/4149#issuecomment-704258099

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by quasiben** [comment]
A `PeriodicCallback` could work but I misunderstood what you were asking for before.  I'm not sure Dask can do what you are asking -- how would you imagine this working ?  When the connection dies a callback is thrown ?  There is a heartbeat between the client and the scheduler -- perhaps that is a viable route ?

**Comment by CMCDragonkai** [comment]
If dask can be async, one should be able to pass a callback into the client object that would be called if these issues occur.

On 7 October 2020 12:59:06 am AEDT, Benjamin Zaitlen <notifications@github.com> wrote:
>A `PeriodicCallback` could work but I misunderstood what you were
>asking for before.  I'm not sure Dask can do what you are asking -- how
>would you imagine this working ?  When the connection dies a callback
>is thrown ?  There is a heartbeat between the client and the scheduler
>-- perhaps that is a viable route ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/distributed/issues/4149#issuecomment-704288111

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jrbourbeau** [comment]
The `Client`s underlying Tornado IO loop is accessible at `Client.loop`. Perhaps using `Client.loop.add_callback` would work for your use case

**Comment by CMCDragonkai** [comment]
I get periodic polling, but are there any events that are thrown when the client connection is down that I can listen for? I imagine that there's an event emitter pattern somewhere here that occurs when the client loses connection.

**Comment by CMCDragonkai** [comment]
There's a function called `Client._reconnect`.

This function is called by `Client._handle_report`.

The `Client._handle_report` is a function that created as an asynchronous task and added to `self.coroutines`.

```
        self._handle_scheduler_coroutine = asyncio.ensure_future(self._handle_report())
        self.coroutines.append(self._handle_scheduler_coroutine)
```

But only after a single `Client._start` has completed.

There's nothing managing `self.coroutines` except `_start` which adds 1 coroutine that being of `_handle_report` and `_close` which closes and cancels all coroutines.

This means `_handle_report` is a while true loop, which some sort of co-operative multitasking from the asyncio scheduler. It basically does this:

```py
                while True:
                    if self.scheduler_comm is None:
                        break
                    try:
                        msgs = await self.scheduler_comm.comm.read()
                    except CommClosedError:
                        if self.status == "running":
                            logger.info("Client report stream closed to scheduler")
                            logger.info("Reconnecting...")
                            self.status = "connecting"
                            await self._reconnect()
                            continue
                        else:
                            break
```

Notice that `self.scheduler_comm` also as a `comm` property. In other places, we see that `self.scheduler_comm.send` is possible (such as for sending a heartbeat). But this is reading and asynchronous. I'm not sure if this is just waiting for message, and perhaps it's any kind of message.

At any case it appears that the scheduler regularly sends messages to the client. And these messages are read or a `CommClosedError` occurs.

When that occurs, we call `_reconnect()`.

Now reconnection happens repeated until a `timeout` is exhausted.

```
            timeout = self._timeout
            deadline = self.loop.time() + timeout
            while timeout > 0 and self.status == "connecting":
                try:
                    await self._ensure_connected(timeout=timeout)
                    break
```

This timeout parameter is determined by seconds.

So there are a couple options here:

1. If there is a way to set infinite timeout, so that we are always attempting to reconnect.
2. What if the scheduler is set to close, does that mean it's not considered an error, and then the client really does close.
3. When it really does close, it appears to just say `logger.error` but there's no exception. So how do we know when the client really has closed and we have to queue up jobs?

It seems the best way would to make sure that we have infinite timeout, so we are always continuously reconnecting, the client never stops. But I wonder what happens to task submission if the client never stops, but is continuously trying to reconnect.

**Comment by CMCDragonkai** [comment]
I just tried a few different values. A timeout of 0 has a 0 second delay, which means it fails immediately. A timeout of X integer just means seconds.

A timeout of `float('inf')` does not work because:

```
Traceback (most recent call last):
  File "/nix/store/gvc8hw9kprm2l60lz8jg7wd0hs0ydivv-python3.7-distributed-2.30.1/lib/python3.7/site-packages/distributed/client.py", line 1191, in __del__
    self.close()
  File "/nix/store/gvc8hw9kprm2l60lz8jg7wd0hs0ydivv-python3.7-distributed-2.30.1/lib/python3.7/site-packages/distributed/client.py", line 1401, in close
    timeout = self._timeout * 2
AttributeError: 'Client' object has no attribute '_timeout'
```

And `None` just defaults to 10 seconds.

So unfortunately there's no way to set infinite timeout for reconnection & connection attempts.

**Comment by CMCDragonkai** [comment]
My suggestion is to allow an extra value being of `float('inf')` to allow infinite timeout and infinite reconnection. For now I have to use `sys.maxsize` for the maximum of seconds.
