### ISSUE TITLE
"Event loop is closed" in multithreaded environment

### ISSUE THREAD

**Issue by anthonynguyen** [dask/distributed#4317]
**What happened**:

When running the following script, often one or more of the threads will die with a `RuntimeError('Event loop is closed')`. Sometimes it completes as expected, and sometimes it'll even just hang at an arbitrary point.

**What you expected to happen**:

The script should output a bunch of log lines, and end with something like the following (but not exactly):
```
[t0] 28.910681566558363
[t2] 28.34740066976898
[t1] 31.865368307629836
None
None
None
```

**Minimal Complete Verifiable Example**:

```python
#!/usr/bin/env python3
from concurrent import futures
import random
import time

import dask
from dask.distributed import Client, LocalCluster, as_completed


def client_workload(thread_num, j, data):
    stime = random.uniform(2, 4)
    time.sleep(stime)
    size = "<no data>"
    if data is not None:
        size = len(data)
    print(f"[t{thread_num}] -- {j} -- {stime:.2f} -- {size}")
    return stime


def thread_evtloop(thread_num):
    with LocalCluster(n_workers=3) as cluster:
        total = 0
        with Client(cluster.scheduler_address) as client:
            [data_f] = client.scatter(["some long data..."])
            fts = [client.submit(client_workload, thread_num, j, data_f) for j in range(10)]

            for _, result in as_completed(fts, with_results=True):
                total += result

        print(f"[t{thread_num}] {total}")


if __name__ == '__main__':
    with futures.ThreadPoolExecutor() as e:
        fts = [e.submit(thread_evtloop, i) for i in range(3)]

        for d in futures.wait(fts).done:
            print(d.exception())
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.21.0, distributed version 2.30.0
- Python version: 3.7.8
- Operating System: MacOS Catalina 10.15.7
- Install method (conda, pip, source): pip

**Comment by fjetter** [comment]
The original issues still persists. cc @graingert this may connect to your recent event loop work

@ericman93 if you are running your own coroutines on a worker, this is a different issue. Could you please open a new ticket for this with a minimal reproducer?

**Comment by graingert** [comment]
This is the traceback I get:

```
/home/graingert/projects/distributed/distributed/node.py:177: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 34523 instead
  warnings.warn(
/home/graingert/projects/distributed/distributed/node.py:177: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 43249 instead
  warnings.warn(
[t0] -- 0 -- 2.11 -- 17
[t1] -- 8 -- 2.04 -- 17
[t0] -- 8 -- 2.18 -- 17
[t2] -- 1 -- 2.49 -- 17
[t1] -- 0 -- 2.41 -- 17
[t0] -- 5 -- 2.48 -- 17
[t2] -- 6 -- 2.55 -- 17
[t0] -- 7 -- 2.45 -- 17
[t0] -- 6 -- 2.47 -- 17
[t0] -- 4 -- 2.49 -- 17
[t1] -- 6 -- 2.59 -- 17
[t2] -- 8 -- 2.72 -- 17
[t2] -- 0 -- 2.93 -- 17
[t2] -- 7 -- 2.92 -- 17
[t1] -- 9 -- 2.82 -- 17
[t2] -- 9 -- 2.93 -- 17
[t2] -- 2 -- 3.41 -- 17
[t0] -- 2 -- 3.36 -- 17
[t1] -- 7 -- 3.28 -- 17
[t1] -- 2 -- 3.35 -- 17
[t0] -- 1 -- 3.49 -- 17
[t0] -- 9 -- 3.40 -- 17
[t1] -- 3 -- 3.37 -- 17
[t2] -- 3 -- 3.67 -- 17
[t2] -- 5 -- 3.83 -- 17
[t1] -- 1 -- 3.88 -- 17
[t1] -- 4 -- 3.93 -- 17
[t0] -- 3 -- 3.02 -- 17
[t0] 27.460265552908183
[t1] -- 5 -- 3.04 -- 17
2022-06-08 11:55:03,658 - distributed.client - ERROR - Event loop is closed
Traceback (most recent call last):
  File "/home/graingert/projects/distributed/distributed/client.py", line 1423, in _handle_report
    result = handler(**msg)
  File "/home/graingert/projects/distributed/distributed/client.py", line 1445, in _handle_key_in_memory
    state.finish(type)
  File "/home/graingert/projects/distributed/distributed/client.py", line 543, in finish
    self._get_event().set()
  File "/home/graingert/miniconda3/envs/dask-distributed/lib/python3.10/asyncio/locks.py", line 193, in set
    fut.set_result(True)
  File "/home/graingert/miniconda3/envs/dask-distributed/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/home/graingert/miniconda3/envs/dask-distributed/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[t2] -- 4 -- 3.67 -- 17
[t2] 31.11929295066456
```

**Comment by fjetter** [comment]
Indeed, I get the same traceback. 

I think this is unrelated and connected to the way we deal with the handle_report_task during closing https://github.com/dask/distributed/blob/2252287f13ba31f724fbfa492c8343920aa5b2a9/distributed/client.py#L1511-L1520

**Comment by graingert** [comment]
on issue here is that `distributed.as_completed()` binds to the `distributed.default_client().loop` and `default_client()` might not be the correct client for the owning thread.

```python
#!/usr/bin/env python3
from concurrent import futures
import random
import time

import dask
from dask.distributed import Client, LocalCluster, as_completed, default_client


def client_workload(thread_num, j, data):
    stime = random.uniform(2, 4)
    time.sleep(stime)
    size = "<no data>"
    if data is not None:
        size = len(data)
    print(f"[t{thread_num}] -- {j} -- {stime:.2f} -- {size}")
    return stime


def thread_evtloop(thread_num):
    with LocalCluster(n_workers=3) as cluster:
        total = 0
        with Client(cluster.scheduler_address) as client:
            [data_f] = client.scatter(["some long data..."])
            fts = [client.submit(client_workload, thread_num, j, data_f) for j in range(10)]

            assert default_client() is client
            for _, result in as_completed(fts, with_results=True):
                total += result

        print(f"[t{thread_num}] {total}")


if __name__ == '__main__':
    with futures.ThreadPoolExecutor() as e:
        fts = [e.submit(thread_evtloop, i) for i in range(3)]

        for fut in futures.as_completed(fts):
            fut.result()
```

traceback:
```
/home/graingert/projects/distributed/distributed/node.py:177: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 37511 instead
  warnings.warn(
/home/graingert/projects/distributed/distributed/node.py:177: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 39537 instead
  warnings.warn(
[t1] -- 7 -- 2.04 -- 17
[t2] -- 8 -- 2.00 -- 17
[t1] -- 0 -- 2.24 -- 17
[t1] -- 2 -- 2.61 -- 17
[t1] -- 1 -- 2.75 -- 17
[t2] -- 4 -- 2.68 -- 17
[t2] -- 1 -- 2.81 -- 17
[t2] -- 2 -- 2.89 -- 17
[t2] -- 5 -- 2.85 -- 17
[t1] -- 6 -- 3.00 -- 17
[t1] -- 9 -- 2.98 -- 17
[t1] -- 5 -- 3.14 -- 17
[t2] -- 0 -- 3.12 -- 17
[t1] -- 8 -- 3.46 -- 17
[t2] -- 6 -- 3.52 -- 17
[t1] -- 4 -- 3.83 -- 17
[t2] -- 3 -- 3.67 -- 17
[t2] -- 9 -- 3.97 -- 17
[t1] -- 3 -- 3.02 -- 17
[t1] 29.07402734349693
[t2] -- 7 -- 3.83 -- 17
[t2] 31.34143502136328
Traceback (most recent call last):
  File "/home/graingert/projects/distributed/demo.py", line 39, in <module>
    fut.result()
  File "/home/graingert/miniconda3/envs/dask-distributed/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/graingert/miniconda3/envs/dask-distributed/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/graingert/miniconda3/envs/dask-distributed/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/graingert/projects/distributed/demo.py", line 27, in thread_evtloop
    assert default_client() is client
AssertionError
```
