### ISSUE TITLE
Getting an error on registering worker plugin using dask-kubernetes  - TypeError: addresses should be strings or tuples, got None

### ISSUE THREAD

**Issue by stradigi-alexv** [dask/distributed#4340]
In a Kubernetes environment when I create a Dask cluster from the pod_spec template
e.g: 
```
from dask_kubernetes import KubeCluster

cluster = KubeCluster.from_dict(pod_spec=spec_template,
                                            name=name,
                                            namespace=KUBERNETES_NAMESPACE)
```

and  when I try to register a worker plugin by following this doc: https://docs.dask.org/en/latest/setup/custom-startup.html#worker-lifecycle-plugins
```
                with Client(cluster) as client:
                    usage_plugin = UsagePlugin()
                    client.register_worker_plugin(usage_plugin, 'usage_plugin')
```
I'm getting the following error **TypeError: addresses should be strings or tuples, got None**
FYI: without the plugin, everything works fine.
And, when I'm using a **LocalCluser** on my local machine, everything works fine as well

Logs:
```
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://10.0.223.154:34901
distributed.scheduler - INFO -   dashboard at:                     :8787
2020-12-09 20:13:02,264|INFO|dask_utils|create_cluster - DASK Cluster created
distributed.scheduler - INFO - Receive client connection: Client-f0946598-3a5a-11eb-817f-f289319cafde
distributed.core - INFO - Starting established connection
2020-12-09 20:13:02,271|INFO|dask_usage_plugin|__init__ - Initializing usage plugin constructor...
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.0.233.217:40047', name: 0, memory: 0, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.0.233.217:40047
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.0.233.217:40047', name: 0, memory: 0, processing: 1>
distributed.core - INFO - Removing comms to tcp://10.0.233.217:40047
distributed.scheduler - INFO - Lost all workers
distributed.utils - ERROR - addresses should be strings or tuples, got None
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/distributed/utils.py", line 656, in log_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/distributed/scheduler.py", line 2209, in remove_worker
    address = self.coerce_address(address)
  File "/usr/local/lib/python3.6/site-packages/distributed/scheduler.py", line 4950, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
distributed.core - ERROR - addresses should be strings or tuples, got None
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/distributed/core.py", line 528, in handle_comm
    result = await result
  File "/usr/local/lib/python3.6/site-packages/distributed/scheduler.py", line 2209, in remove_worker
    address = self.coerce_address(address)
  File "/usr/local/lib/python3.6/site-packages/distributed/scheduler.py", line 4950, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
^Cdistributed.scheduler - INFO - Remove client Client-f0946598-3a5a-11eb-817f-f289319cafde
distributed.scheduler - INFO - Remove client Client-f0946598-3a5a-11eb-817f-f289319cafde
distributed.scheduler - INFO - Close client connection: Client-f0946598-3a5a-11eb-817f-f289319cafde
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
```

**Environment**:

- Dask version:
```
    "dask==2.30.0",
    "dask-kubernetes==0.10.1",
```
- Python version: 3.6
- Operating System: 
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
```

**Comment by quasiben** [comment]
I think usually this error is due to some other failing.  Is the image you are using also Python 3.6 and matches the dask and distributed versions in the environment you are launching from ?

**Comment by stradigi-alexv** [comment]
Thanks @quasiben for the info, after upgrading all dependencies, it works 
```
    "dask==2.30.0",
    "dask-kubernetes==0.11.0",
    "distributed==2.30.1"
```
