### ISSUE TITLE
"Set changed size during iteration" Error in Worker.put_key_in_memory()

### ISSUE THREAD

**Issue by manuels** [dask/distributed#4371]
I am getting an error in this line: https://github.com/dask/distributed/blob/d54388c92f5cb6643180749f7d30f580609379a2/distributed/worker.py#L1970

Maybe a temporary copy of ts.dependents helps here?

```
Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fa72878fb90>>, <Task finished coro=<Worker.gather_dep() done, defined at [...]/python3.7/site-packages/distributed/worker.py:2000> exception=RuntimeError('Set changed size during iteration')>)
Traceback (most recent call last):
File "[...]/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
  ret = callback()
File "[...]/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
  future.result()
File "[...]/python3.7/site-packages/distributed/worker.py", line 2119, in gather_dep
  self.transition(ts, "memory", value=data[d])
File "[...]/python3.7/site-packages/distributed/worker.py", line 1539, in transition
  state = func(ts, **kwargs)
File "[...]/python3.7/site-packages/distributed/worker.py", line 1605, in transition_flight_memory
  self.put_key_in_memory(ts, value)
File "[...]/python3.7/site-packages/distributed/worker.py", line 1970, in put_key_in_memory
  for dep in ts.dependents:
RuntimeError: Set changed size during iteration
```

**Comment by manuels** [comment]
Maybe that happens because I submit [tasks from tasks](https://docs.dask.org/en/latest/futures.html#submit-tasks-from-tasks)?

Wrapping the loop with this seems to fix the error:
```
while True:
  try:
    for dep in ts.dependents:
      ...
    break
  except RuntimeError as e:
    if e.message == 'Set changed size during iteration':
      continue
    raise e
```

**Comment by mrocklin** [comment]
cc @gforsyth .  This may be the same issue fixed by @fjetter recently

**Comment by gforsyth** [comment]
I think this particular error is fixed in @fjetter's PR in #4360 -- @manuels, short term you can change it to `for dep in list(ts.dependents):` and that should do the trick

**Comment by manuels** [comment]
If with the `while True/try except` block, I run into the issue that some job depenedencies are not started at all. I'm not sure if this is really connected to this issue. Let me try to figure out what is going on on my side and report back.

**Comment by manuels** [comment]
It seems to work fine if I downgrade to v2.30.

**Comment by mdering** [comment]
is this still an issue in 2021.01.1? Has anyone checked or verified?

**Comment by fjetter** [comment]
Judging by the code, this is still a thing. In #4360 I tried to address all of this at once but that just kept on escalating. The temporary copy is probably the best approach here.

A minimal, reproducible example would be great for this.

I believe this is loosely related to #4439

**Comment by mrocklin** [comment]
it's a shot in the dark, but maybe #5285 helps?  Is it easy for you to test your workload against that branch?

**Comment by gerrymanoim** [comment]
Thanks - will try that as soon as I can.

**Comment by jrbourbeau** [comment]
Thanks @gerrymanoim
