### ISSUE TITLE
msgpack error with scheduler optimization

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#4399]
I'll work on getting a smaller reproducer but I am currently seeing the following error with the recent scheduler optimization work.  The error can be reproduced with [this query](https://github.com/rapidsai/gpu-bdb/blob/main/tpcx_bb/queries/q04/tpcx_bb_query_04.py#L160)

```
Traceback (most recent call last):
  File "/datasets/bzaitlen/miniconda3/envs/tpcxbb-20210104-dask-optimized/lib/python3.7/site-packages/xbb_tools/utils.py", line 280, in run_dask_cudf_query
    config=config,
  File "/datasets/bzaitlen/miniconda3/envs/tpcxbb-20210104-dask-optimized/lib/python3.7/site-packages/xbb_tools/utils.py", line 61, in benchmark
    result = func(*args, **kwargs)
  File "tpcx_bb_query_04.py", line 160, in main
    result = result.compute()
  File "/datasets/bzaitlen/GitRepos/dask/dask/base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/datasets/bzaitlen/GitRepos/dask/dask/base.py", line 561, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/datasets/bzaitlen/miniconda3/envs/tpcxbb-20210104-dask-optimized/lib/python3.7/site-packages/distributed/client.py", line 2670, in get
    actors=actors,
  File "/datasets/bzaitlen/miniconda3/envs/tpcxbb-20210104-dask-optimized/lib/python3.7/site-packages/distributed/client.py", line 2588, in _graph_to_futures
    dsk = highlevelgraph_pack(dsk, self, keyset)
  File "/datasets/bzaitlen/miniconda3/envs/tpcxbb-20210104-dask-optimized/lib/python3.7/site-packages/distributed/protocol/highlevelgraph.py", line 130, in highlevelgraph_pack
    return msgpack.dumps({"layers": layers}, default=msgpack_encode_default)
  File "/datasets/bzaitlen/miniconda3/envs/tpcxbb-20210104-dask-optimized/lib/python3.7/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'ParquetSubgraph' object
```

**Comment by jrbourbeau** [comment]
I believe this is related to the discussion over in https://github.com/dask/distributed/issues/4374. We reverted some recent blockwise IO changes in https://github.com/dask/dask/pull/6995 which impacted array workloads, but it looks like we're running into a similar issue with dataframe workloads

**Comment by mrocklin** [comment]
I would expect @rjzamora to know what is going on here.

**Comment by ian-r-rose** [comment]
> I believe this is related to the discussion over in #4374.

Yes, this is the same issue, and is not unique to array workloads: `BlockwiseIO` needs to be made serializable across the board.

**Comment by jrbourbeau** [comment]
Agreed, I'll go ahead and close this issue in favor of continuing the conversation over in https://github.com/dask/distributed/issues/4374 (hope that's okay @quasiben)

**Comment by quasiben** [comment]
Thanks @jrbourbeau !

**Comment by rjzamora** [comment]
Sorry all for the BlockwiseIO serialization problem!  This is completely my oversight.

As mentioned by @ian-r-rose, the new changes are indeed incompatable with the distributed scheduler, because the `__dask_distributed_pack__`/`__dask_distributed_unpack__` definitition does **not** properly serialize/deserialize the `io_deps` argument (a dictionary of IO dependencies, with each element being some kind of IO subgraph).  I tried producing a quick fix a few weeks ago (before taking time off), but ran into some unexpected difficulties.  I'll do my best to come up with something today.
