### ISSUE TITLE
distributed.Client fails unexpectedly with latest dask and distributed versions

### ISSUE THREAD

**Issue by kshitij-mathur-by** [dask/distributed#4412]
When using `dask==2.30.0` and `distributed==2.30.1`, the following code-snippet runs without any issue

```
import dask.bag as db
from distributed import Client

def calculate(x):
    return x
bag = db.from_sequence([1,2,3,4,5]).map(calculate)

with Client():
    dask.compute(bag)

```
However, when running the same code snippet on `dask==2020.12.0` and `distributed==2020.12.0`
```

distributed.core - ERROR - 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 589, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 2286, in update_graph_hlg
    dsk, dependencies, annotations = highlevelgraph_unpack(hlg)
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/protocol/highlevelgraph.py", line 126, in highlevelgraph_unpack
    dumped_hlg, object_hook=msgpack_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 517, in handle_comm
    result = await result
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 3149, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 589, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 2286, in update_graph_hlg
    dsk, dependencies, annotations = highlevelgraph_unpack(hlg)
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/protocol/highlevelgraph.py", line 126, in highlevelgraph_unpack
    dumped_hlg, object_hook=msgpack_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x11722d7b8>, <Task finished coro=<BaseTCPListener._handle_stream() done, defined at /Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py:459> exception=UnicodeDecodeError('utf-8', b"\x80\x04\x95&\x02\x00\x00\x00\x00\x00\x00\x8c\rdask.bag.core\x94\x8c\x05reify\x94\x93\x94(h\x00\x8c\tmap_chunk\x94\x93\x94\x8c\x17cloudpickle.cloudpickle\x94\x8c\r_builtin_type\x94\x93\x94\x8c\nLambdaType\x94\x85\x94R\x94(h\x07\x8c\x08CodeType\x94\x85\x94R\x94(K\x01K\x00K\x01K\x01KCC\x04|\x00S\x00\x94N\x85\x94)\x8c\x01x\x94\x85\x94\x8c\x1e<ipython-input-2-0e7331f056b1>\x94\x8c\tcalculate\x94K\x04C\x02\x00\x01\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94N\x8c\x08__name__\x94\x8c\x08__main__\x94uNNNt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x12_function_setstate\x94\x93\x94h\x1c}\x94}\x94(h\x19h\x13\x8c\x0c__qualname__\x94h\x13\x8c\x0f__annotations__\x94}\x94\x8c\x0e__kwdefaults__\x94N\x8c\x0c__defaults__\x94N\x8c\n__module__\x94h\x1a\x8c\x07__doc__\x94N\x8c\x0b__closure__\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0b__globals__\x94}\x94u\x86\x94\x86R0]\x94\x8c5('from_sequence-7442aaac159c800cde8d80fa5bae3b3e', 4)\x94aN}\x94t\x94\x86\x94.", 0, 1, 'invalid start byte')>)
Traceback (most recent call last):
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 327, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/comm/tcp.py", line 476, in _handle_stream
    await self.comm_handler(comm)
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 517, in handle_comm
    result = await result
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 3149, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 589, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/scheduler.py", line 2286, in update_graph_hlg
    dsk, dependencies, annotations = highlevelgraph_unpack(hlg)
  File "/Users/1025948/anaconda3/lib/python3.7/site-packages/distributed/protocol/highlevelgraph.py", line 126, in highlevelgraph_unpack
    dumped_hlg, object_hook=msgpack_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

```

I am unable to find anything in changelog that can point towards such a breaking change
- Python version: 3.7.3
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @kshitij-mathur-by! This was recently reported over in https://github.com/dask/distributed/issues/4395 and a fix was just merged in https://github.com/dask/distributed/pull/4409

**Comment by kshitij-mathur-by** [comment]
thanks for the quick response @jrbourbeau
