### ISSUE TITLE
sporadic tornado.application error logs when scaling down / stopping LocalCluster

### ISSUE THREAD

**Issue by mariusvniekerk** [dask/distributed#4478]
**What happened**:

When terminating a worker (naturally with adapt() or by stopping a Localcluster) the following error messages appear sporadically.  These are harmless but will trigger alerting mechanisms that act on logging output keys on terms like `Error` and `Exception`.  Additionally since these error messages contain full python tracebacks they add a high amount of spurious noise to logs decreasing their overall usefulness.

```pytb
2021-02-02 09:05:35,040 9871:ERROR:tornado.application: ioloop._run_callback:761 -- Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f8d07787af0>>, <Task finished name='Task-191' coro=<Worker.close() done, defined at /Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/worker.py:1169> exception=CommClosedError('in <closed TCP>: Stream is closed')>)
Traceback (most recent call last):
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/comm/tcp.py", line 187, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/worker.py", line 1193, in close
    await r.close_gracefully()
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/core.py", line 858, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/core.py", line 641, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/comm/tcp.py", line 202, in read
    convert_stream_closed_error(self, e)
  File "/Users/mvanniekerk/miniconda3/envs/fh-parquet/lib/python3.8/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc)) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

Whilst distributed suppresses all these errors and prevents them from accidentally bringing down the application it does not prevent the logging statement at https://github.com/tornadoweb/tornado/blob/master/tornado/ioloop.py#L761 from firing within workers.

**What you expected to happen**:

A relatively crude solution to this problem can be just filtering out these logs using standard python logging filters (the assumption is that regular exceptions that are fatal will still bubble up and bring down the application, so nothing major is lost in filtering them out)

**Minimal Complete Verifiable Example**:

```py
import distributed
import logging
import numpy as np

class TornadoDaskLogFilter(logging.Filter):
    def filter(self, record: LogRecord) -> bool:
        if record.exc_info is not None:
            if record.funcName == '_run_callback' and record.module == 'ioloop':
                # Dask has very natural behavior when scaling that may result in a few
                # tornado streams logging very scary looking errors.
                # Get rid of these if they are non-fatal
                print(f"Suppressed tornado callback error {record}", file=sys.stderr)
                return False

        return True


def setup_logging():
    l = logging.getLogger("tornado.application")
    f = TornadoDaskLogFilter()
    l.addFilter(f)


setup_logging()


with distributed.LocalCluster(n_workers=0) as cluster:
    a = cluster.adapt(minimum=1, maximum=16)
    try:
        with distributed.client(cluster) as client:
            client.register_worker_callbacks(setup_logging)
            futs = [client.submit(time.sleep, x) for x in np.linspace(0, 1, num=1000)]
            for res in distributed.as_completed(futs):
                _ = res.result()
    finally:
        a.stop()

```
**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.01.1 
- Tornado version: 6.1
- Python version: 3.8
- Operating System: osx
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
I just tried this with the latest `main` branch of `dask` and `distributed` and don't see errors logged. @mariusvniekerk could you try again with dev versions of `dask` and `distributed`? 

Also, note I had to make a couple of changes (e.g. add `import`s) to the snippet you posted. Here's what I ran

```python
import time
import sys
import distributed
import logging
import numpy as np

if __name__ == "__main__":

    class TornadoDaskLogFilter(logging.Filter):
        def filter(self, record) -> bool:
            if record.exc_info is not None:
                if record.funcName == '_run_callback' and record.module == 'ioloop':
                    # Dask has very natural behavior when scaling that may result in a few
                    # tornado streams logging very scary looking errors.
                    # Get rid of these if they are non-fatal
                    print(f"Suppressed tornado callback error {record}", file=sys.stderr)
                    return False

            return True


    def setup_logging():
        l = logging.getLogger("tornado.application")
        f = TornadoDaskLogFilter()
        l.addFilter(f)


    setup_logging()


    with distributed.LocalCluster(n_workers=0) as cluster:
        a = cluster.adapt(minimum=1, maximum=16)
        try:
            with distributed.Client(cluster) as client:
                client.register_worker_callbacks(setup_logging)
                futs = [client.submit(time.sleep, x) for x in np.linspace(0, 1, num=1000)]
                for res in distributed.as_completed(futs):
                    _ = res.result()
        finally:
            a.stop()
```

**Comment by ncclementi** [comment]
@mariusvniekerk Checking in here, I'm closing this issue since it seems that the problem has been resolved on the latest Dask versions. (just tested this in 2021.08.0) If you are still having this problem, feel free to re-open the issue with an update so we can help you.
