### ISSUE TITLE
mapping partial functions with future objects not working

### ISSUE THREAD

**Issue by caseyjlaw** [dask/distributed#449]
I am using the executor submit functions in for loops.  I would like use the map function, but it seems that partial and lambda functions can't get pickled.

Here is example code using partial (seems to behave similarly using lambda):

```
import functools
import numpy as np

def make_data(shape):
    return np.random.normal(size=shape)

def adder(data, value):
    return data + value

data = ex.submit(make_data, (10,10))      # get a future for data on a worker
adder_partial = partial(adder, data)         # set up function to map
ex.map(adder_partial, range(5))
```

That code will produce this error:

```
distributed.core - INFO - Failed to serialize <functools.partial object at 0x7fad6f8dc5d0>
Traceback (most recent call last):
  File "/users/claw/miniconda/lib/python2.7/site-packages/distributed/core.py", line 65, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 649, in dumps
    cp.dump(obj)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 231, in save_function
    self.save_function_tuple(obj)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 268, in save_function_tuple
    save((code, closure, base_globals))
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 639, in _batch_appends
    save(x)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 404, in save_instancemethod
    obj=obj)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 549, in save_reduce
    save(args)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 231, in save_function
    self.save_function_tuple(obj)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 273, in save_function_tuple
    save(f_globals)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/users/claw/miniconda/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 567, in save_reduce
    save(state)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/users/claw/miniconda/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle thread.lock objects
```

**Comment by mrocklin** [comment]
Yeah, so the problem here is that you have a `Future` within a Partial.  

The futures themselves are not picklable (they are tied to your Executor).  This is normally not a problem, because the Executor is able to dive through all the inputs and unpack them itself before it sends them to the scheduler.  However, when they're hidden within the partial the Executor can't see them, so it ends up trying to pickle itself.


## Solutions

If the example you've given is indicative of what you're trying to do then let me offer a couple of alternatives:

```python
import numpy as np

def make_data(shape):
    return np.random.normal(size=shape)

data = ex.submit(make_data, (10,10))      # get a future for data on a worker
```

### Use Keyword arguments in map

Keyword arguments are not mapped over.  They get sent to each function just as they are.

```python
def add(x=None, y=None):
    return x + y

futures = ex.map(add, range(5), y=data) 
```

### Use submit

Submit is actually pretty fast, and you can call it thousands of times a second.  There are some scheduling disadvantages to this, but it's unlikely that you'll notice them.

```python
futures [ex.submit(add, data, i) for i in range(5)]
```

**Comment by mrocklin** [comment]
@caseyjlaw does this work for you?  Closing soon if no response.

**Comment by caseyjlaw** [comment]
Feel free to close. I can't test set the moment, but it seems simple
enough. Thanks.

**Comment by mrocklin** [comment]
Great!  Closing.
