### ISSUE TITLE
ValueError when trying to start cythonized scheduler

### ISSUE THREAD

**Issue by gforsyth** [dask/distributed#4524]
**What happened**: I started `dask-scheduler` and got this traceback:

```
$ dask-scheduler --host localhost
Traceback (most recent call last):
  File "/Users/gil/miniforge3/envs/viztracer/bin/dask-scheduler", line 33, in <module>
    sys.exit(load_entry_point('distributed==2021.2.0+7.g383ea0326', 'console_scripts', 'dask-scheduler')())
  File "/Users/gil/miniforge3/envs/viztracer/bin/dask-scheduler", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/__init__.py", line 4, in <module>
    from .actor import Actor, ActorFuture
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/actor.py", line 6, in <module>
    from .client import Future, default_client
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/client.py", line 43, in <module>
    from .batched import BatchedSend
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/batched.py", line 8, in <module>
    from .core import CommClosedError
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/core.py", line 20, in <module>
    from .comm import (
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/comm/__init__.py", line 12, in <module>
    from .core import connect, listen, Comm, CommClosedError
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/comm/core.py", line 16, in <module>
    from ..protocol.compression import get_default_compression
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/protocol/__init__.py", line 6, in <module>
    from .core import dumps, loads, maybe_compress, decompress, msgpack
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/protocol/core.py", line 8, in <module>
    from .serialize import (
  File "distributed/protocol/serialize.py", line 164, in init distributed.protocol.serialize
  File "distributed/protocol/serialize.py", line 161, in distributed.protocol.serialize.register_serialization_family
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/site-packages/distributed/utils.py", line 1187, in has_keyword
    return keyword in inspect.signature(func).parameters
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/inspect.py", line 2296, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/Users/gil/miniforge3/envs/viztracer/lib/python3.8/inspect.py", line 2107, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function dask_dumps>

```

**What you expected to happen**: I expected the scheduler to start

**Minimal Complete Verifiable Example**:

```
$ mamba create -n viztracer viztracer python=3.8 dask distributed compilers Cython uvloop ipython viztracer
$ conda activate viztracer
$ mamba uninstall --force dask distributed
$ python -m pip install .  # in dask/dask master
$ python -m pip install -vv --install-option="--with-cython=profile" .  # in dask/distributed master
```

**Anything else we need to know?**:
This is on a managed enterprise machine so there may be external factors

**Environment**:

- Dask version:
  dask                      2021.2.0+20.g1c9a9622b          pypi_0    pypi
  distributed               2021.2.0+7.g383ea0326          pypi_0    pypi
- Python version: 3.8
- Operating System: OSX 10.15.7
- Install method (conda, pip, source): conda / source

cc @jakirkham if he has any tips / thoughts on this.

**Comment by gforsyth** [comment]
As per a comment from @jrbourbeau I'm going to try this with `conda` instead, to rule out any `mamba` related weirdness

**Comment by gforsyth** [comment]
Welp, using `conda` instead made this go away.

The only thing I noticed in passing was that the `conda` install pulled down a different version of `setuptools` which maybe had something to do with it?  I'm a bit confused, but closing this.

**Comment by gforsyth** [comment]
Ignore all of this -- after cleaning out some cruft from my local copy both `conda` and `mamba` work.  Sorry for the noise.

**Comment by jakirkham** [comment]
Sorry missed this. Though it looks like things got worked out here. If more issues come up, please let me know :)
