### ISSUE TITLE
Effective file size limit for UploadFile if worker joins after registering

### ISSUE THREAD

**Issue by nsmith-** [dask/distributed#4535]
**What happened**:
For sufficiently large zipball files, workers cannot join the cluster after registering an UploadFile plugin.

**What you expected to happen**:
Workers can join even with big files in the workerplugins.

**Minimal Complete Verifiable Example**:

```python
from distributed import LocalCluster, Client
from distributed.diagnostics.plugin import UploadFile


def make_zipball(size):
    import os
    import shutil
    import numpy

    os.mkdir("zipball")
    numpy.save("zipball/data.npy", numpy.random.normal(size=size // 8))
    with open("zipball/__init__.py", "w") as fout:
        fout.write(
            """\
import importlib.resources
import numpy

with importlib.resources.path("zipball", "data.npy") as path:
    moduledata = numpy.load(path)
"""
        )

    shutil.make_archive(
        "zipball",
        "zip",
        base_dir="zipball",
    )
    shutil.rmtree("zipball")
    return "zipball.zip"


def usemodule():
    from zipball import moduledata

    return moduledata.mean()


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} SIZE [ before | after ]")
        exit(0)

    zipball = make_zipball(int(sys.argv[1]))
    with LocalCluster(n_workers=0) as cluster:
        with Client(cluster) as client:
            if sys.argv[2] == "before":
                client.register_worker_plugin(UploadFile(zipball))
            cluster.scale(1)
            client.wait_for_workers(1)
            if sys.argv[2] == "after":
                client.register_worker_plugin(UploadFile(zipball))
            print("Mean value of moduledata:", client.submit(usemodule).result())
```
If run with `python mwe.py 1000 before` or `python mwe.py 1000 after` or `python mwe.py 1000000 after` the cluster behaves OK. If run with `python mwe.py 1000000 before` there will be a crash in the deserialization of (presuably) the plugin data as it is sent back to the worker:
```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/core.py", line 151, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 369, in deserialize
    raise TypeError(
TypeError: Data serialized with dask but only able to deserialize data with ['msgpack']
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/usr/local/lib/python3.8/site-packages/distributed/core.py", line 284, in _
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/distributed/worker.py", line 1166, in start
    await self._register_with_scheduler()
  File "/usr/local/lib/python3.8/site-packages/distributed/worker.py", line 898, in _register_with_scheduler
    response = await future
  File "/usr/local/lib/python3.8/site-packages/distributed/comm/tcp.py", line 212, in read
    msg = await from_frames(
  File "/usr/local/lib/python3.8/site-packages/distributed/comm/utils.py", line 80, in from_frames
    res = _from_frames()
  File "/usr/local/lib/python3.8/site-packages/distributed/comm/utils.py", line 63, in _from_frames
    return protocol.loads(
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/core.py", line 151, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 369, in deserialize
    raise TypeError(
TypeError: Data serialized with dask but only able to deserialize data with ['msgpack']
distributed.nanny - ERROR - Failed while trying to start worker process: Data serialized with dask but only able to deserialize data with ['msgpack']
```

**Anything else we need to know?**:

**Environment**:

- Dask version: `2021.02.0`
- Python version: `3.8.7`
- Operating System: OS X or Linux
- Install method (conda, pip, source): Conda or pip

**Comment by jrbourbeau** [comment]
Thanks for the nice, minimal example @nsmith-! I'm able to reproduce the issue with the latest development version of distributed (https://github.com/dask/distributed/commit/7146449173c0329463ca39b98ba51087278853d5). Though unfortunately I've had a chance to dig much deeper than reproducing the issue

**Comment by eric-valente** [comment]
@jrbourbeau We're struggling with this exact issue... causing big issues.  any thought on how we can work around it for now?

**Comment by jrbourbeau** [comment]
I just tried the example in @nsmith-'s original post with the latest `distributed=2021.3.1` release and am no longer able produce the `TypeError` serialization error. There have been several updates to our serialization code since `2021.02.0` which _may_ have fixed this issue. @eric-valente @nsmith- could you try again with the latest release?

**Comment by nsmith-** [comment]
For me with `2021.4.0` the example does not show any issues. I'm happy to close

**Comment by jrbourbeau** [comment]
Great, thanks for follow up here @nsmith-
