### ISSUE TITLE
CancelledError with collections annotations

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#4542]
Some background: I'm using `Array.map_blocks` in combination with the new `dask.annotations` to set resource restrictions, followed by a getitem, I get a KeyError / CancelledError.

```python
import dask
import dask.array
from distributed import Client, LocalCluster

cluster = LocalCluster(resources={"gpu": 1})
client = Client(cluster)
client

def f(x):
    return x + 1

a = dask.array.ones((4, 100, 100), chunks=(4, 10, 10))


with dask.annotate(resources={"gpu": 1}):
    b = a.map_blocks(f, meta=a._meta)

b[0, 0, 0].compute(optimize_graph=False)
```

```pytb
## -- End pasted text --
distributed.core - ERROR - "('f-3406b3798f8ce70c11bdf0b38247241f', 0, 0, 1)"
Traceback (most recent call last):
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 3658, in update_graph_hlg
    return self.update_graph(
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 3824, in update_graph
    ts = parent._tasks[k]
KeyError: "('f-3406b3798f8ce70c11bdf0b38247241f', 0, 0, 1)"
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 4519, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 3658, in update_graph_hlg
    return self.update_graph(
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 3824, in update_graph
    ts = parent._tasks[k]
KeyError: "('f-3406b3798f8ce70c11bdf0b38247241f', 0, 0, 1)"
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7fc9fc35dc10>, <Task finished name='Task-71' coro=<BaseTCPListener._handle_stream() done, defined at /mnt/c/Users/taugspurger/src/dask/distributed/distributed/comm/tcp.py:468> exception=KeyError("('f-3406b3798f8ce70c11bdf0b38247241f', 0, 0, 1)")>)
Traceback (most recent call last):
  File "/home/taugspurger/miniconda3/envs/dask-dev/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/taugspurger/miniconda3/envs/dask-dev/lib/python3.8/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/comm/tcp.py", line 485, in _handle_stream
    await self.comm_handler(comm)
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 4519, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 3658, in update_graph_hlg
    return self.update_graph(
  File "/mnt/c/Users/taugspurger/src/dask/distributed/distributed/scheduler.py", line 3824, in update_graph
    ts = parent._tasks[k]
KeyError: "('f-3406b3798f8ce70c11bdf0b38247241f', 0, 0, 1)"
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<ipython-input-1-1fc9719314e8> in <module>
     19     b = a.map_blocks(f, meta=a._meta)
     20
---> 21 b[0, 0, 0].compute(optimize_graph=False)

/mnt/c/Users/taugspurger/src/dask/dask/dask/base.py in compute(self, **kwargs)
    280         dask.base.compute
    281         """
--> 282         (result,) = compute(self, traverse=False, **kwargs)
    283         return result
    284

/mnt/c/Users/taugspurger/src/dask/dask/dask/base.py in compute(*args, **kwargs)
    562         postcomputes.append(x.__dask_postcompute__())
    563
--> 564     results = schedule(dsk, keys, **kwargs)
    565     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    566

/mnt/c/Users/taugspurger/src/dask/distributed/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2653                     should_rejoin = False
   2654             try:
-> 2655                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2656             finally:
   2657                 for f in futures.values():

/mnt/c/Users/taugspurger/src/dask/distributed/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1962             else:
   1963                 local_worker = None
-> 1964             return self.sync(
   1965                 self._gather,
   1966                 futures,

/mnt/c/Users/taugspurger/src/dask/distributed/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    836             return future
    837         else:
--> 838             return sync(
    839                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    840             )

/mnt/c/Users/taugspurger/src/dask/distributed/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

/mnt/c/Users/taugspurger/src/dask/distributed/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

~/miniconda3/envs/dask-dev/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

/mnt/c/Users/taugspurger/src/dask/distributed/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1828                         else:
   1829                             raise exception.with_traceback(traceback)
-> 1830                         raise exc
   1831                     if errors == "skip":
   1832                         bad_keys.add(key)

CancelledError: ('getitem-2e4755efdaa343e4dacd80f734b956ae',)
```

I haven't debugged this at all beyond simplifying the example. Perhaps @sjperkins has a guess offhand?

Perhaps relevant: `b.compute(optimize_graph=False)` and `b[0].compute(optimize_graph=False)` both succeed, but `b[0, 0]` fails.

**Comment by jrbourbeau** [comment]
Also cc @ian-r-rose

**Comment by TomAugspurger** [comment]
Thoughts on this as a fix, or is it just papering over the problem?

```diff
diff --git a/distributed/scheduler.py b/distributed/scheduler.py
index 911bf4fb..f7a42b90 100644
--- a/distributed/scheduler.py
+++ b/distributed/scheduler.py
@@ -3821,8 +3821,11 @@ class Scheduler(SchedulerState, ServerNode):
 
             for a, kv in annotations.items():
                 for k, v in kv.items():
-                    ts = parent._tasks[k]
-                    ts._annotations[a] = v
+                    # Tasks might have been culled, in which case
+                    # we don't need to add an annotation.
+                    if k in parent._tasks:
+                        ts = parent._tasks[k]
+                        ts._annotations[a] = v
 
         # Add actors
         if actors is True:
```

The immediate problem, a `KeyError` comes from looking up a task like `(f-<token>, 0, 0, 1)`. But the scheduler only knows about `f-<token>, 0, 0, 0)`, apparently as a result of culling. Here's some state at that point where that `if` condidtion is false

```python
(Pdb) pp k
"('f-f1200760556b15c8dc90d23eca811bb9', 0, 0, 1)"
(Pdb) pp self._tasks
{"('f-f1200760556b15c8dc90d23eca811bb9', 0, 0, 0)": <Task "('f-f1200760556b15c8dc90d23eca811bb9', 0, 0, 0)" released>,
 "('getitem-7dbde99d736ef00c5b270f2bf086d0f8',)": <Task "('getitem-7dbde99d736ef00c5b270f2bf086d0f8',)" released>,
 "('ones-7421ea306f0e34b49be5837b8906d86e', 0, 0, 0)": <Task "('ones-7421ea306f0e34b49be5837b8906d86e', 0, 0, 0)" released>}
```

**Comment by sjperkins** [comment]
> Thoughts on this as a fix, or is it just papering over the problem?
> 
> ```diff
> diff --git a/distributed/scheduler.py b/distributed/scheduler.py
> index 911bf4fb..f7a42b90 100644
> --- a/distributed/scheduler.py
> +++ b/distributed/scheduler.py
> @@ -3821,8 +3821,11 @@ class Scheduler(SchedulerState, ServerNode):
>  
>              for a, kv in annotations.items():
>                  for k, v in kv.items():
> -                    ts = parent._tasks[k]
> -                    ts._annotations[a] = v
> +                    # Tasks might have been culled, in which case
> +                    # we don't need to add an annotation.
> +                    if k in parent._tasks:
> +                        ts = parent._tasks[k]
> +                        ts._annotations[a] = v
>  
>          # Add actors
>          if actors is True:
> ```
> 
> The immediate problem, a `KeyError` comes from looking up a task like `(f-<token>, 0, 0, 1)`. But the scheduler only knows about `f-<token>, 0, 0, 0)`, apparently as a result of culling. Here's some state at that point where that `if` condidtion is false
> 
> ```python
> (Pdb) pp k
> "('f-f1200760556b15c8dc90d23eca811bb9', 0, 0, 1)"
> (Pdb) pp self._tasks
> {"('f-f1200760556b15c8dc90d23eca811bb9', 0, 0, 0)": <Task "('f-f1200760556b15c8dc90d23eca811bb9', 0, 0, 0)" released>,
>  "('getitem-7dbde99d736ef00c5b270f2bf086d0f8',)": <Task "('getitem-7dbde99d736ef00c5b270f2bf086d0f8',)" released>,
>  "('ones-7421ea306f0e34b49be5837b8906d86e', 0, 0, 0)": <Task "('ones-7421ea306f0e34b49be5837b8906d86e', 0, 0, 0)" released>}
> ```

Morning @TomAugspurger. Yes, I think what you've posted above is a reasonable fix: I suspect annotations are being expanded over all layer keys -- even ones that are culled.

I would've guessed the Layer machinery would have removed those keys before annotation expansion over all keys in distributed, but I'm a bit unsure. These seem to be the relevant locations:

1. https://github.com/dask/dask/blob/bb6936d127bc2e24874e9fbb00c608d32edf6835/dask/array/optimization.py#L24-L51
2. https://github.com/dask/dask/blob/bb6936d127bc2e24874e9fbb00c608d32edf6835/dask/highlevelgraph.py#L152-L195
3. https://github.com/dask/dask/blob/bb6936d127bc2e24874e9fbb00c608d32edf6835/dask/highlevelgraph.py#L557-L597

**Comment by sjperkins** [comment]
Hmmm, I wonder if the culling mechanisms are retain annotations, as new layers are created...

**Comment by TomAugspurger** [comment]
I looked at `unpack_highlevelgraph` a bit, and I think we're OK with the diff I added up above.

I don't know quite where, but somewhere in `Scheduler.update_graph`, we decide not to add these tasks (I don't know for sure, but I don't see an explicit "cull" step, so this may be different).

I'll push a PR up.
