### ISSUE TITLE
Specific combination of objects in dask.delayed with distributed client triggers serialization error

### ISSUE THREAD

**Issue by uellue** [dask/distributed#4570]
A serialization error is triggered by a very specific combination of `distributed.Client`, function wrapped in `dask.delayed` and arguments supplied to that delayed function. See code example for details.

**What happened**:

`distributed.core - ERROR - 'tuple' object does not support item assignment`, see full traceback in details.

<details>

```
distributed.core - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.worker - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x000001BF032EC970>>, <Task finished name='Task-22' coro=<Worker.handle_scheduler() done, defined at c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py:988> exception=TypeError("'tuple' object does not support item assignment")>)
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.core - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.worker - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x000001BF032EC970>>, <Task finished name='Task-64' coro=<Worker.handle_scheduler() done, defined at c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py:988> exception=TypeError("'tuple' object does not support item assignment")>)
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.core - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.worker - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x000001BF032EC970>>, <Task finished name='Task-78' coro=<Worker.handle_scheduler() done, defined at c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py:988> exception=TypeError("'tuple' object does not support item assignment")>)
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.core - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
distributed.worker - ERROR - 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x000001BF032EC970>>, <Task finished name='Task-93' coro=<Worker.handle_scheduler() done, defined at c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py:988> exception=TypeError("'tuple' object does not support item assignment")>)
Traceback (most recent call last):
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\worker.py", line 990, in handle_scheduler
    await self.handle_stream(
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\comm\inproc.py", line 199, in read
    msg = nested_deserialize(msg)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 609, in nested_deserialize
    return replace_inner(x)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 601, in replace_inner
    x[k] = replace_inner(v)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 594, in replace_inner
    x[k] = deserialize(v.header, v.frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 384, in deserialize
    return loads(header, frames)
  File "c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\protocol\serialize.py", line 77, in pickle_loads
    buffers[i] = memoryview(bytearray(mv)).cast(mv.format, mv.shape)
TypeError: 'tuple' object does not support item assignment
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-6-efd4b9defb73> in <module>
----> 1 client.compute(d).result()

c:\users\dwebe\.conda\envs\libertem\lib\site-packages\distributed\client.py in result(self, timeout)
    220         if self.status == "error":
    221             typ, exc, tb = result
--> 222             raise exc.with_traceback(tb)
    223         elif self.status == "cancelled":
    224             raise result

KilledWorker: ('whatever-4e70b926-60dd-45a2-958c-b952f59770f1', <Worker 'inproc://192.168.178.84/22596/3', name: 0, memory: 0, processing: 1>)

```

</details>

**What you expected to happen**:

The same as with `processes=True` or `d.compute(scheduler='single-threaded')`:  The result of calling the delayed function.

```
<__main__.ArrayContainer at 0x1bf032dcd60>
```

**Minimal Complete Verifiable Example**:

```python
import distributed as dd
import numpy as np
import dask

# processes=True doesn't trigger the error
client = dd.Client(processes=False)

class ArrayContainer():
    def __init__(self, data):
        self.data = data

# Wrap a NumPy array in the ArrayContainer.
# Wrapping a tuple doesn't trigger the error.
ac = ArrayContainer(
    data=np.ones((1, 1, 1)),
)

def whatever(*args, **kwargs):
    return ac

# Supply a keyword argument to the delayed function.
# Other arguments don't trigger the error
d = dask.delayed(whatever)(bla="abc")

client.compute(d).result()
```

**Environment**:

- Dask version: 2021.3.0. Doesn't happen with 2021.2.0
- Python version: Python 3.8.5
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by uellue** [comment]
@quasiben the example keeps `ac` constant, so it doesn't rely on global state and works perfectly fine with multiprocessing. 

Of course one could implement the functionality of this example by wrapping `ac` directly as a delayed value. This is a minimal reproducer, so the point here is not the end result, but that it triggers an error deep within `distributed` under very specific circumstances. Here is a slightly modified version with a proper closure that should make clear that this is not related to global state, but some issue with serialization/deserialization.

```python
import distributed as dd
import numpy as np
import dask

# processes=True doesn't trigger the error
client = dd.Client(processes=False)

class ArrayContainer():
    def __init__(self, data):
        self.data = data

def whatever_factory():
    # Wrap a NumPy array in the ArrayContainer.
    # Wrapping a tuple doesn't trigger the error.
    ac = ArrayContainer(
        data=np.ones((1, 1, 1)),
    )

    def whatever(*args, **kwargs):
        return ac
    
    return whatever

# Supply a keyword argument to the delayed function.
# Other arguments don't trigger the error
d = dask.delayed(whatever_factory())(bla="abc")

client.compute(d).result()
```

**Comment by jakirkham** [comment]
The serialization error is already a known limitation of MsgPack (what Distributed uses under-the-hood in many cases). See issue ( https://github.com/dask/distributed/issues/3716 )

Since it sounds like we are primarily interested in the serialization error and not this specific use case, am going to close so we can track in aforementioned issue. Though if that misses some other need here, please let us know. Thanks! 😄
