### ISSUE TITLE
Getting `concurrent.futures._base.CancelledError` from simple binary tree built from futures

### ISSUE THREAD

**Issue by cjnolet** [dask/distributed#4612]
I'm getting the following exception from a binary tree that I'm building from futures (based largely on an example in the dask docs that uses delayed instead of futures).

Here's the function in question:
```python
from dask.distributed import default_client
from toolz import first

def tree_reduce(objs, func=sum):

    while len(objs) > 1:
        new_objs = []
        n_objs = len(objs)
        for i in range(0, n_objs, 2):
            inputs = objs[i:i + 2]
            obj = get_client().submit(func, inputs)
            new_objs.append(obj)
        wait(new_objs)
        objs = new_objs

    return first(objs)
```

And my reproducible test:
```python
    n_parts = 15
    client = Client(cluster)

    a = client.scatter(range(n_parts))
    b = tree_reduce(a)
    b = b.result()

    assert(sum(range(n_parts)) == b)
```

The exception is intermittent and happens about 50% of the time:
```python
self = <tornado.gen.Runner object at 0x7f2cf6ce5710>

    def run(self) -> None:
        """Starts or resumes the generator, running until it reaches a
        yield point that is not ready.
        """
        if self.running or self.finished:
            return
        try:
            self.running = True
            while True:
                future = self.future
                if future is None:
                    raise Exception("No pending future")
                if not future.done():
                    return
                self.future = None
                try:
                    exc_info = None
    
                    try:
>                       value = future.result()
E                       concurrent.futures._base.CancelledError
```

I've tried doing a `dask.distributed.wait` after each level of the tree. I've also tried waiting for `b` in the reproducible example before calling `result`. I'm completely stumped as to why this is happening. I'm running this on a workstation with 2x V100s. 

I believe I'm doing something very wrong but I can't figure out what it is.

**Comment by martindurant** [comment]
Moved to distributed. This seems to still be an issue.

**Comment by mvashishtha** [comment]
@jacobtomlinson thank you for looking into the bug.

This seems like a really serious bug. Right now it's causing tests I'm adding to [Modin on dask](https://github.com/modin-project/modin/) to fail often (but not always). Dask users should be able to delete data with a given value and re-store data with the same value.

> I'll start working on a PR for this.

Is there any workaround? What happened to #3641?

**Comment by mvashishtha** [comment]
> Right now it's causing tests I'm adding to [Modin on dask](https://github.com/modin-project/modin/) to fail often (but not always).

It turns out I should have been scattering my objects with [`hash=False`](https://github.com/modin-project/modin/blob/4ec7f6347903f9133c65ebc5b6e0e15553b98577/modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py#L231). Once I started doing that, I worked around the bug.

Still, the bug with `hash=True` seems pretty bad.

**Comment by jacobtomlinson** [comment]
Yeah there hasn't been much activity here for a couple of years. #3641 wasn't an ideal solution and we ended up not going with it. 

It's interesting that not many folks are pinging the issue of giving a 👍, maybe most folks are working around it or not running into it. I'm guessing this is why it hasn't been resolved yet.

cc @grainger @gjoseph92 @crusaderky @hendrikmakait in case they have any interest in this

**Comment by gjoseph92** [comment]
I just tried @jacobtomlinson's reproducer from https://github.com/dask/distributed/issues/4612#issuecomment-604417345 and it still fails.

```
2022-08-01 15:54:39,440 - distributed.scheduler - INFO - State start
2022-08-01 15:54:39,443 - distributed.scheduler - INFO - Clear task state
2022-08-01 15:54:39,444 - distributed.scheduler - INFO -   Scheduler at: inproc://192.168.0.16/3895/1
2022-08-01 15:54:39,444 - distributed.scheduler - INFO -   dashboard at:            localhost:8787
2022-08-01 15:54:39,454 - distributed.worker - INFO -       Start worker at: inproc://192.168.0.16/3895/4
2022-08-01 15:54:39,454 - distributed.worker - INFO -          Listening to:         inproc192.168.0.16
2022-08-01 15:54:39,454 - distributed.worker - INFO -          dashboard at:         192.168.0.16:50082
2022-08-01 15:54:39,454 - distributed.worker - INFO - Waiting to connect to: inproc://192.168.0.16/3895/1
2022-08-01 15:54:39,454 - distributed.worker - INFO - -------------------------------------------------
2022-08-01 15:54:39,454 - distributed.worker - INFO -               Threads:                         16
2022-08-01 15:54:39,454 - distributed.worker - INFO -                Memory:                  32.00 GiB
2022-08-01 15:54:39,454 - distributed.worker - INFO -       Local Directory: /var/folders/rs/wdnmv5lj02x7sh19rg3nyfyr0000gn/T/dask-worker-space/worker-rpvr7b4y
2022-08-01 15:54:39,454 - distributed.worker - INFO - -------------------------------------------------
2022-08-01 15:54:39,468 - distributed.scheduler - INFO - Register worker <WorkerState 'inproc://192.168.0.16/3895/4', name: 0, status: init, memory: 0, processing: 0>
2022-08-01 15:54:39,469 - distributed.scheduler - INFO - Starting worker compute stream, inproc://192.168.0.16/3895/4
2022-08-01 15:54:39,469 - distributed.core - INFO - Starting established connection
2022-08-01 15:54:39,470 - distributed.worker - INFO -         Registered to: inproc://192.168.0.16/3895/1
2022-08-01 15:54:39,470 - distributed.worker - INFO - -------------------------------------------------
2022-08-01 15:54:39,470 - distributed.core - INFO - Starting established connection
2022-08-01 15:54:39,473 - distributed.scheduler - INFO - Receive client connection: Client-89bac764-11e4-11ed-8f37-acde48001122
2022-08-01 15:54:39,474 - distributed.core - INFO - Starting established connection
1
2022-08-01 15:54:39,686 - distributed.scheduler - INFO - User asked for computation on lost data, sum-7b273f79c27b78e8b6f23bc2fa389c28
2022-08-01 15:54:39,698 - distributed.scheduler - INFO - Remove client Client-89bac764-11e4-11ed-8f37-acde48001122
2022-08-01 15:54:39,698 - distributed.scheduler - INFO - Remove client Client-89bac764-11e4-11ed-8f37-acde48001122
2022-08-01 15:54:39,699 - distributed.scheduler - INFO - Close client connection: Client-89bac764-11e4-11ed-8f37-acde48001122
2022-08-01 15:54:39,701 - distributed.worker - INFO - Stopping worker at inproc://192.168.0.16/3895/4
2022-08-01 15:54:39,702 - distributed.scheduler - INFO - Remove worker <WorkerState 'inproc://192.168.0.16/3895/4', name: 0, status: closing, memory: 0, processing: 0>
2022-08-01 15:54:39,703 - distributed.core - INFO - Removing comms to inproc://192.168.0.16/3895/4
2022-08-01 15:54:39,703 - distributed.scheduler - INFO - Lost all workers
2022-08-01 15:54:39,703 - distributed.worker - INFO - Connection to scheduler broken. Closing without reporting. ID: Worker-6adb788a-61cb-4125-8b34-e95b17dde3cd Address inproc://192.168.0.16/3895/4 Status: Status.closing
2022-08-01 15:54:39,705 - distributed.scheduler - INFO - Scheduler closing...
2022-08-01 15:54:39,705 - distributed.scheduler - INFO - Scheduler closing all comms
Traceback (most recent call last):
  File "/Users/gabe/dev/dask-playground/reuse-futures.py", line 23, in <module>
    asyncio.get_event_loop().run_until_complete(f())
  File "/Users/gabe/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/gabe/dev/dask-playground/reuse-futures.py", line 17, in f
    print(await client.submit(sum, a))
  File "/Users/gabe/dev/distributed/distributed/client.py", line 295, in _result
    raise exception
concurrent.futures._base.CancelledError: sum-7b273f79c27b78e8b6f23bc2fa389c28
```
Notice the `User asked for computation on lost data` message in the middle: https://github.com/dask/distributed/blob/4b89e26c044da2bd5ceb9367568a27911589cdf7/distributed/scheduler.py#L3885-L3896

That's where the CancelledError is coming from as well.

My gut feeling here is that this is mostly a client-side issue, not with the scheduler or worker. I haven't looked at this for more than 2min so this is just a guess. But this feels familiar to me with how the client gets reference-counting wrong in a concurrent setting, especially when passing from blocking to event-loop code. A guess:

1. When the `del a` statement completes, the futures are not actually deleted or dereferenced. At least two event loop cycles still have to happen for that to happen on the client. For them to actually be released on the scheduler, there's then the wait for a BatchedSend interval to pass, network time, the scheduler handing the request, etc.
2. `client-releases-keys` (the client->scheduler message) happens over BatchedSend, which ensures message ordering. `scatter` happens over RPC, which is not ordered. So it's probable, on a single machine like this, that the second `scatter` RPC call will reach the scheduler before the first `client-releases-keys` message.
3. `scatter` on the scheduler doesn't do much validation. It doesn't catch the fact that it's been told to scatter a key that it already knows about, which should be a red flag.
4. So basically, the second scatter runs, then the first `client-releases-keys` arrives and deletes the key that we just re-scattered (this is the key problem; the order of these got flipped because they use different RPC mechanisms with different orderings)
5. `submit(sum, a)` is guaranteed to happen after `client-releases-keys`, since they both use batched comms. So at that point, `a` has just been deleted from the scheduler, then you try to make a new task that depends on it, hence the "User asked for computation on lost data".

**Comment by maxbane** [comment]
I think I have another (simpler?) reproducer. [Posted](https://github.com/dask/distributed/issues/3703#issuecomment-1347460987) in #3703, but maybe I should have posted here instead since this issue has more recent activity and they seem to be duplicates.

```python
from dask import distributed
cluster = distributed.LocalCluster(
    n_workers=4, threads_per_worker=2, host="0.0.0.0",
    scheduler_port=0, dashboard_address=':0'
)
client = distributed.Client(cluster)

def nullity(x):
    return None

def identity(x, y):
    return x

for i in range(100):
    # after a few iterations, we'll die with either CancelledError or KilledWorker
    print(f"Iteration {i}")
    y = client.submit(
        nullity,
        client.scatter("smoochies")
    ).result()

    client.submit(
        identity,
        client.scatter("smoochies"),
        y
    ).result()
```

**Comment by fjetter** [comment]
I can confirm that @gjoseph92 s analysis is correct and this is an ordering issue. I see two options

1. Scatter uses the batched comm as well and follows ordering. I'm actually not sure how bad of an idea it is to use the batched comm for the entire data stream. Maybe that's less bad than it sounds. However, it is also entirely possible to just split up the scatter process into two steps. We're doing this already for the `direct` path, see https://github.com/dask/distributed/blob/aca9a5e75ceb0c66faa6dc6db2f6bfd40ab2e8ee/distributed/client.py#L2400-L2406
when communication to workers is allowed, we are scattering to workers and once they all have their data, we're letting the scheduler know the data exists via the update_data call. Note that the `update_data` call is *also* flawed because it still uses an unordered pooled RPC instead of an ordered batched stream, i.e. if we changed update_data to a batched message, this would likely work for direct.
We could implement the same thing for indirect by using the same logic but proxying over the scheduler

2. We could introduce entity tags to the futures and sign every client-wants/releases message, similar to what https://github.com/dask/distributed/pull/7463 introduces for worker<->scheduler communication

**Comment by fjetter** [comment]
Decoupling scatter_to_workers from update_data as suggested above in 1) indeed resolves the race that triggers the cancelled error but it introduces a similar race condition on worker side resulting in data loss.
I think by implementing something like 2.) we can avoid this entire class of race conditions. This would require modifications to `client_releases_keys` and `client_desires_keys` but IIUC not on worker side.

**Comment by ofk123** [comment]
@mvashishtha, I see setting `client.scatter(...hash=False`) does avoid the CancelledError, at least in the few attempts I have done for our current workflow which looks like the MRE below. Would you say this is a safe workaround? Glad to use it if so.

Reproducer:
```
from distributed import Client, LocalCluster
cluster=LocalCluster()
client=Client(cluster)

def function1(x):
    return x*2

def function2(x):
    return x*3

def run1(arr, client):
    arr_sc = client.scatter(arr)
    list_of_submitted_tasks = []
    for _ in range(100):
        submitted = client.submit(function1, arr_sc, pure=False)
        list_of_submitted_tasks.append(submitted)
    gathered = client.gather(list_of_submitted_tasks)
    del arr_sc, list_of_submitted_tasks, submitted
    
def run2(arr, client):
    arr_sc = client.scatter(arr)
    list_of_submitted_tasks = []
    for _ in range(100):
        submitted = client.submit(function2, arr_sc, pure=False)
        list_of_submitted_tasks.append(submitted)
    gathered = client.gather(list_of_submitted_tasks)
    del arr_sc, list_of_submitted_tasks, submitted
    
for i in range(30):
    arr = np.array([1., 2., 3.])*i
    run1(arr, client)
    run2(arr, client)
```
Erroring with:
```
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
Cell In[86], line 28
     26 arr = np.array([1., 2., 3.])*i
     27 run1(arr, client)
---> 28 run2(arr, client)

Cell In[86], line 22, in run2(arr, client)
     20     submitted = client.submit(function2, arr_sc, pure=False)
     21     list_of_submitted_tasks.append(submitted)
---> 22 gathered = client.gather(list_of_submitted_tasks)
     23 del arr_sc, list_of_submitted_tasks, submitted

File /srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/client.py:2291, in Client.gather(self, futures, errors, direct, asynchronous)
   2289 else:
   2290     local_worker = None
-> 2291 return self.sync(
   2292     self._gather,
   2293     futures,
   2294     errors=errors,
   2295     direct=direct,
   2296     local_worker=local_worker,
   2297     asynchronous=asynchronous,
   2298 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/utils.py:339, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    337     return future
    338 else:
--> 339     return sync(
    340         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    341     )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/utils.py:406, in sync(loop, func, callback_timeout, *args, **kwargs)
    404 if error:
    405     typ, exc, tb = error
--> 406     raise exc.with_traceback(tb)
    407 else:
    408     return result

File /srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/utils.py:379, in sync.<locals>.f()
    377         future = asyncio.wait_for(future, callback_timeout)
    378     future = asyncio.ensure_future(future)
--> 379     result = yield future
    380 except Exception:
    381     error = sys.exc_info()

File /srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/gen.py:769, in Runner.run(self)
    766 exc_info = None
    768 try:
--> 769     value = future.result()
    770 except Exception:
    771     exc_info = sys.exc_info()

File /srv/conda/envs/notebook/lib/python3.10/site-packages/distributed/client.py:2155, in Client._gather(self, futures, errors, direct, local_worker)
   2153     else:
   2154         raise exception.with_traceback(traceback)
-> 2155     raise exc
   2156 if errors == "skip":
   2157     bad_keys.add(key)

CancelledError: function2-170f5763-5a5a-4d36-8257-5ec2d782149f
```
