### ISSUE TITLE
Timed out during handshake while connecting to tcp://localhost:9002 after 10 s

### ISSUE THREAD

**Issue by fredms** [dask/distributed#4708]
The local client "local=tcp://127.0.0.1:65441" CAN connect to "remote=tcp://localhost:9002", but failed during handshake later. my knowledge is limited here. Please advise how can I fix this?

I located the place raising error in comm/core.py:
```
try:
        # This would be better, but connections leak if worker is closed quickly
        # write, handshake = await asyncio.gather(comm.write(local_info), comm.read())
        handshake = await asyncio.wait_for(comm.read(), time_left())
        await asyncio.wait_for(comm.write(local_info), time_left())
    except Exception as exc:
        with suppress(Exception):
            await comm.close()
        raise IOError(
            f"Timed out during handshake while connecting to {addr} after {timeout} s"
        ) from exc
```

**Comment by fredms** [comment]
Hi @mrocklin,  I saw this was added 8 months ago. The issue might be small, but I have limited knowledge here. Please advise how can I fix this?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @fredms. Can you provide any additional information about your cluster setup and the code you're running which is triggering the error? With the level of information provided it may be hard for others to help. See https://blog.dask.org/2018/02/28/minimal-bug-reports for crafting minimal bug reports. 

What version of Python / Dask / Distributed are you running? Are you sure it's the same on all the nodes in your cluster? (Sometimes the handshake can fail when there's a version mismatch)

**Comment by fredms** [comment]
Thanks @jrbourbeau . This is usage of AzureMLCluster (it's deprecated, but I maintain a copy in my repo). I would like to do some benchmarking with AML compute. 

python: 3.6.5
dask: 1.0.0
distributed:1.25.1

It failed to create cluster because of handshake exception. The handshake is between local=tcp://127.0.0.1:58240 and remote=tcp://localhost:9002.

I added some outputs for debug in distributed/comm/core.py
########################### Scheduler: 10.1.0.7:8786 ###########################
############################# Not on the same VNET #############################
###################### Running in compute instance? False ######################
###################### scheduler_public_ip: 52.146.52.241 ######################
######################### scheduler_public_port: 50001 #########################
 cmd: ssh -vvv -o StrictHostKeyChecking=no -N -i C:\Users\feli1.REDMOND\.ssh\id_rsa -L 0.0.0.0:9000:10.1.0.7:8888 -L 0.0.0.0:9001:10.1.0.7:8787 -L 0.0.0.0:9002:10.1.0.7:8786 daskfeli1@52.146.52.241 -p 50001 
**core.py, trying to connect to tcp://localhost:9002
core.py, inside connect method
core.py,time left 9.997105121612549, loc is localhost:9002
core.py, I am connected, comm is <TCP  local=tcp://127.0.0.1:58240 remote=tcp://localhost:9002>
core.py,time left2 9.674129247665405
core.py, local_info is {'compression': None, 'python': (3, 6, 5), 'pickle-protocol': 4}, comm <TCP  local=tcp://127.0.0.1:58240 remote=tcp://localhost:9002>**
ERROR:dask_cloudprovider.azureml.azureml:Timed out during handshake while connecting to tcp://localhost:9002 after 10 s
Traceback (most recent call last):
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\site-packages\distributed\comm\core.py", line 325, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\projects\git_repos\dask-cp-mine\dask_cloudprovider\azureml\azureml.py", line 713, in __create_cluster
    await super()._start()
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\site-packages\distributed\deploy\cluster.py", line 73, in _start
    comm = await self.scheduler_comm.live_comm()
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\site-packages\distributed\core.py", line 751, in live_comm
    **self.connection_args,
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\site-packages\distributed\comm\core.py", line 333, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://localhost:9002 after 10 s

**Comment by jrbourbeau** [comment]
It looks like you have a `distributed` version mismatch somewhere. The following part of your output

```
 core.py, local_info is {'compression': None, 'python': (3, 6, 5), 'pickle-protocol': 4}, comm 
```

is using the `local_info` variable added in https://github.com/dask/distributed/pull/4019 which was included in the `distributed==2.23.0` release. I recommend making sure you're using the same version of `distributed` everywhere and then retrying.

**Comment by fredms** [comment]
Thanks. I tried to use the same requirements in my local and remote compute. In the requirements, I specified versions as follows:
adlfs==0.7.3
azureml-core==1.26.0
dask==2021.3.0
dask-ml==1.8.0
distributed==2021.3.0
fastparquet==0.5.0
fsspec==0.9.0
joblib==1.0.1
jupyterlab==3.0.14
lz4==3.1.3
mpi4py==3.0.3
notebook==6.3.0
pyarrow==3.0.0

And the issue still exists:
core.py, trying to connect to tcp://localhost:9002
core.py, inside connect method
core.py,time left 9.999241590499878, loc is localhost:9002
core.py, I am connected, comm is <TCP  local=tcp://127.0.0.1:65104 remote=tcp://localhost:9002>
core.py,time left2 9.685405015945435
core.py, local_info is {'compression': 'lz4', 'python': (3, 6, 5), 'pickle-protocol': 4}, comm <TCP  local=tcp://127.0.0.1:65104 remote=tcp://localhost:9002>
ERROR:dask_cloudprovider.azureml.azureml:Timed out during handshake while connecting to tcp://localhost:9002 after 10 s
Traceback (most recent call last):
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\site-packages\distributed\comm\core.py", line 325, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by fjetter** [comment]
I'm wondering why you are trying to connect to `localhost` if it is a remote compute setup. Is there some kind of proxy active? Maybe this is responsible for the failures.

I would also recommend to increase the timeout using the option `distributed.comm.timeouts.connect` to eliminate slow network.

**Comment by fredms** [comment]
Thanks @fjetter. You're right. we set up port forwarding when starting remote cluster from local ([line 790](https://github.com/fredms/dask-cloudprovider/blob/main/dask_cloudprovider/azureml/azureml.py) ).  I tried to increase the timeout, but I got tornado exceptions:
core.py, trying to connect to tcp://localhost:9002
core.py, inside connect method
core.py,time left 99.9994101524353, loc is localhost:9002
core.py, I am connected, comm is <TCP  local=tcp://127.0.0.1:52164 remote=tcp://localhost:9002>
core.py,t**ime left2 99.17750930786133**
core.py, local_info is {'compression': 'lz4', 'python': (3, 6, 5), 'pickle-protocol': 4}, comm <TCP  local=tcp://127.0.0.1:52164 remote=tcp://localhost:9002>
ERROR:dask_cloudprovider.azureml.azureml:Timed out during handshake while connecting to tcp://localhost:9002 after 100 s
Traceback (most recent call last):
  File "E:\projects\AzureML\anaconda3\envs\bingdask\lib\site-packages\distributed\comm\tcp.py", line 195, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
**tornado.iostream.StreamClosedError: Stream is closed**

**Comment by secrettoad** [comment]
Just sharing here that I also consistently get timeouts and broken port-forwards when forwarding to the dask scheduler with gke and kubectl
