### ISSUE TITLE
inputs contain futures that were created by another client

### ISSUE THREAD

**Issue by rahulsemwaliiita** [dask/distributed#4712]
As per the Dask documentation, client.persist() returns the futures pointing to actively running task in the background. In my code, I am contacting multiple CSV files with persist and wait operation, then converting dask dataframe to dask array. But, before I convert dask dataframe into dask array, I get the following error:

```
[Inputs contain futures that were created by another client.
Task was destroyed but it is pending!
task: <Task pending coro=<Client._run() running at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/client.py:2429> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f052e1ba710>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/tornado/ioloop.py:688]>
Exception ignored in: <generator object sync.<locals>.f at 0x7f071b213e50>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/utils.py", line 340, in f
    assert thread_state.asynchronous > 0
AttributeError: '_thread._local' object has no attribute 'asynchronous']
```

Please, provide any suggestions to rectify the same. The source code is as follows:

```python
from dask.distributed import Client, LocalCluster,wait
import os

cluster=LocalCluster(n_workers=processes, threads_per_worker=1)
client=Client(cluster) 
for i, csv_file in enumerate(os.listdir("path to multiple csv files")):
    df = dd.read_csv(csv_file)
    meta=get_meta(df) #compute meta for each partition
    result=df.map_partitions(lambda part: handle_part(part),meta=meta)
    result1=client.persist(result)
    wait(result1)
    del df
    if i==0:
       result=result1
   else:
       results=result.append(result1)
       results=client.persist(results)
       wait(results)
       del result
       del result1
       result=results
result=client.persist(result)
wait(result)

X=result.to_dask_array(lengths=True)
X=client.persist(X) 
wait(X)
del result

```

**Environment**:

- Dask version: 2021.04.0
- Python version: 3.7
- Operating System: ubuntu 20.04
- Install method (conda, pip, source): conda

**Comment by fjetter** [comment]
I am assuming you are also using `distributed==2021.04.0`? Are there any other exceptions visible? Is your computation stopping / deadlocking / finishing or do you merely see these exceptions logged?

**Comment by rahulsemwaliiita** [comment]
Yes, I am using distributed==2021.04.0. Till now apart from this exception, nothing is visible and this stops my code execution before converting dask dataframe to dask array.

**Comment by fjetter** [comment]
Have you tried reproducing the error without CSV files? See https://blog.dask.org/2018/02/28/minimal-bug-reports 

This would help us reproducing the issue to track it down.

**Comment by rahulsemwaliiita** [comment]
Dear @fjetter, now when I running above code I get following error log:

```
Inputs contain futures that were created by another client.
Exception in thread WorkerMemory:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 196, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/dask_memusage.py", line 66, in _fetch_memory
    worker_to_mem = client.run(_process_memory)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/client.py", line 2500, in run
    return self.sync(self._run, function, *args, **kwargs)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/client.py", line 844, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/client.py", line 2429, in _run
    nanny=nanny,
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 862, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 645, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    convert_stream_closed_error(self, e)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc)) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed

distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
Future exception was never retrieved
future: <Future finished exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 196, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/utils.py", line 250, in quiet
    yield task
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py", line 5230, in send_message
    resp = await send_recv(comm, close=True, serializers=serializers, **msg)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 645, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    convert_stream_closed_error(self, e)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc)) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
Task exception was never retrieved
future: <Task finished coro=<Scheduler.broadcast.<locals>.send_message() done, defined at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py:5226> exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 196, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py", line 5230, in send_message
    resp = await send_recv(comm, close=True, serializers=serializers, **msg)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 645, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    convert_stream_closed_error(self, e)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc)) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Task exception was never retrieved
future: <Task finished coro=<Scheduler.broadcast.<locals>.send_message() done, defined at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py:5226> exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 196, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py", line 5230, in send_message
    resp = await send_recv(comm, close=True, serializers=serializers, **msg)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 645, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    convert_stream_closed_error(self, e)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc)) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Task exception was never retrieved
future: <Task finished coro=<Scheduler.broadcast.<locals>.send_message() done, defined at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py:5226> exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 266, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py", line 5230, in send_message
    resp = await send_recv(comm, close=True, serializers=serializers, **msg)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 643, in send_recv
    await comm.write(msg, serializers=serializers, on_error="raise")
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 282, in write
    convert_stream_closed_error(self, e)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 128, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc)) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
Task exception was never retrieved
future: <Task finished coro=<Scheduler.broadcast.<locals>.send_message() done, defined at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py:5226> exception=OSError('Timed out during handshake while connecting to tcp://127.0.0.1:33401 after 18000 s')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/tornado/iostream.py", line 867, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/tornado/iostream.py", line 1140, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/core.py", line 318, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 206, in read
    convert_stream_closed_error(self, e)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 126, in convert_stream_closed_error
    ) from exc
distributed.comm.core.CommClosedError: in <closed TCP>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py", line 5227, in send_message
    comm = await self.rpc.connect(addr)
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/core.py", line 1014, in connect
    **self.connection_args,
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/core.py", line 325, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:33401 after 18000 s
Task exception was never retrieved
future: <Task finished coro=<Scheduler.broadcast.<locals>.send_message() done, defined at /home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/scheduler.py:5226> exception=CommClosedError('in <closed TCP>: Stream is closed')>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/Dask_2021_04_0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 196, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

```

**Comment by fjetter** [comment]
I do not really understand, yet, what's going on but I suspect the for loop you are writing is somehow causing confusion with the futures/tasks. Every time you call `result = new_result` this looses the reference to the old future which might trigger some race condition.
Have you tried reading all CSVs with one API call instead of looping over the collection?

https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_csv

```python
ddf = dd.read_csv("/path/to/my/directory/*.csv")
ddf = ddf.map_partitions(handle_part)
ddf = client.persist(ddf)  # Consider not persisting this
arr = ddf.to_dask_array()
arr = client.persist(arr)
del ddf # If you persisted it previously, I recommend deleting it again at some point since otherwise you potentially hold twice the memory in RAM
```

**Comment by rahulsemwaliiita** [comment]
Thank you @fjetter for providing the suggestion. Now, everything is working fine. I think you were right that due to the assignment operation the old future reference was lost.
