### ISSUE TITLE
Handle `ts=None` in `_task_to_report_msg`

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#4730]
We've started seeing some tests fail when `ts=None` is passed to `_task_to_report_msg` (e.g. see [this CI build](https://github.com/dask/distributed/pull/4720/checks?check_run_id=2403923283)). Currently if we pass `ts=None` to `_task_to_report_msg` we will attempt to retreive its `._key` attribute:

https://github.com/dask/distributed/blob/f492aa7e7a39270aaf0b58e37ed855c149b68a8f/distributed/scheduler.py#L7063-L7067

which doesn't exist for `None` (see the traceback below). 

It looks like the `_task_to_report_msg` function was added in https://github.com/dask/distributed/pull/4365 (cc @jakirkham) although the corresponding logic may predate that PR. Also cc'ing @fjetter @gforsyth 

<details>
<summary>Traceback:</summary>

```python
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f505ad304d0>, <Task finished coro=<BaseTCPListener._handle_stream() done, defined at /home/runner/work/distributed/distributed/distributed/comm/tcp.py:476> exception=AttributeError("'NoneType' object has no attribute '_key'")>)
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/tcpserver.py", line 297, in <lambda>
    lambda f: f.result())
  File "/home/runner/work/distributed/distributed/distributed/comm/tcp.py", line 493, in _handle_stream
    await self.comm_handler(comm)
  File "/home/runner/work/distributed/distributed/distributed/core.py", line 501, in handle_comm
    result = await result
  File "/home/runner/work/distributed/distributed/distributed/scheduler.py", line 4919, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/home/runner/work/distributed/distributed/distributed/core.py", line 573, in handle_stream
    handler(**merge(extra, msg))
  File "/home/runner/work/distributed/distributed/distributed/scheduler.py", line 6053, in report_on_key
    report_msg: dict = _task_to_report_msg(parent, ts)
  File "/home/runner/work/distributed/distributed/distributed/scheduler.py", line 7067, in _task_to_report_msg
    return {"op": "cancelled-key", "key": ts._key}
AttributeError: 'NoneType' object has no attribute '_key'
```

</details>

**Comment by jakirkham** [comment]
That's interesting as [CI notes `report_on_key` is called first]( https://github.com/dask/distributed/pull/4720/checks?check_run_id=2403923283#step:11:2252 ) (this is the function calling `_task_to_report_msg`). Within `report_on_key`, the following logic should ensure either `ts is not None` or an `AssertionError` is raised

https://github.com/dask/distributed/blob/a2308319d3030da311d41813b6921b74717e5f5c/distributed/scheduler.py#L4310-L4317

So I don't think we should end up with `ts is None`, but maybe I'm overlooking something

**Comment by jakirkham** [comment]
Or are we saying we now have a `key` for which there is no longer an associated `ts` in `_tasks`? If so, that is likely a deeper issue

**Comment by jakirkham** [comment]
NVM think I found the issue. Submitted PR ( https://github.com/dask/distributed/pull/4755 )
