### ISSUE TITLE
Scheduler /system endpoint failure

### ISSUE THREAD

**Issue by chrisroat** [dask/distributed#4749]
**What happened**:

Scheduler sends a 500 for "System" endpoint, and sends the following traceback.   (Note the scheduler itself still seems to be alive and well)

<details>

<summary>traceback</summary>

```
distributed.utils - ERROR - deque index out of range
Traceback (most recent call last):
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/utils.py", line 668, in log_errors
    yield
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/dashboard/components/scheduler.py", line 2169, in systemmonitor_doc
    sysmon = SystemMonitor(scheduler, sizing_mode="stretch_both")
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/dashboard/components/shared.py", line 464, in __init__
    update(self.source, self.get_data())
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/dashboard/components/shared.py", line 536, in get_data
    d = self.worker.monitor.range_query(start=self.last)
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/system_monitor.py", line 123, in range_query
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/system_monitor.py", line 123, in <dictcomp>
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/system_monitor.py", line 123, in <listcomp>
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
IndexError: deque index out of range
tornado.application - ERROR - Uncaught exception GET /system (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/system', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/croat/miniconda3/envs/dask_scheduler_memory2/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/croat/miniconda3/envs/dask_scheduler_memory2/lib/python3.9/site-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/home/croat/miniconda3/envs/dask_scheduler_memory2/lib/python3.9/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/croat/miniconda3/envs/dask_scheduler_memory2/lib/python3.9/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/croat/miniconda3/envs/dask_scheduler_memory2/lib/python3.9/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/home/croat/miniconda3/envs/dask_scheduler_memory2/lib/python3.9/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/dashboard/components/scheduler.py", line 2169, in systemmonitor_doc
    sysmon = SystemMonitor(scheduler, sizing_mode="stretch_both")
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/dashboard/components/shared.py", line 464, in __init__
    update(self.source, self.get_data())
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/dashboard/components/shared.py", line 536, in get_data
    d = self.worker.monitor.range_query(start=self.last)
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/system_monitor.py", line 123, in range_query
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/system_monitor.py", line 123, in <dictcomp>
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
  File "/home/croat/dask_scheduler_memory2/distributed/distributed/system_monitor.py", line 123, in <listcomp>
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
IndexError: deque index out of range
```

</details>

**What you expected to happen**:

View the metrics for the scheduler.

**Minimal Complete Verifiable Example**:

```python
import distributed
distributed.Client()
# Click dashboard link, go to "System"
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.04.01
- Python version: 3.9.2
- Operating System: MacOSX 11.2.3
- Install method (conda, pip, source): source

**Comment by jrbourbeau** [comment]
Thanks for reporting @chrisroat! I tried to trigger the `IndexError` locally with the example you provided but wasn't able to after a few attempts. Do you see this error consistently or sporadically? Also, I know you've been experimenting with various log length, etc. parameters to reduce the scheduler's memory usage recently -- are there any non-default configuration values you're using when you see this error happen?

**Comment by chrisroat** [comment]
It was triggered every time, and I didn't have anything set.  It seemed important, but maybe I jumped the gun in reporting.  I started my environment fresh, and things seem to be OK.  Apologies for the extra work.

**Comment by jrbourbeau** [comment]
No worries! Let us know if it pops up again
