### ISSUE TITLE
Bokeh dashboard not viewable at all

### ISSUE THREAD

**Issue by nickvazz** [dask/distributed#4778]
**What happened**:
Using a docker image for dask, was unable to load the dashboard
![image](https://user-images.githubusercontent.com/8573886/116937956-df488400-ac1e-11eb-8999-4d01db176845.png)

**What you expected to happen**:
To load the bokeh dashboard from the docker container

**Minimal Complete Verifiable Example**:
```Dockerfile
version: '3.2'
networks:
  network:

services:
  dask-scheduler:
    container_name: dask_scheduler
    image: daskdev/dask:2021.3.0
    # image: daskdev/dask:2021.2.0 # This is most recent version that works
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    restart: 'always'
    environment:
      - EXTRA_PIP_PACKAGES=prometheus_client jupyter-server-proxy # not sure if these are breaking something
    command: ['dask-scheduler']
    networks:
    - network
```

## Looks like it comes from here: https://github.com/dask/distributed/blob/main/distributed/scheduler.py#L3338

```python
>>> import distributed.dashboard.scheduler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/distributed/dashboard/scheduler.py", line 13, in <module>
    from .components.scheduler import (
ImportError: cannot import name 'individual_systemmonitor_doc' from 'distributed.dashboard.components.scheduler' (/opt/conda/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py)
>>> 
```

```python
(base) root@dask-scheduler:/# python
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distributed
>>> import distributed.dashboard
>>> import distributed.dashboard.components
>>> import distributed.dashboard.components.scheduler
>>> from distributed.dashboard.components.scheduler import individual_systemmonitor_doc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'individual_systemmonitor_doc' from 'distributed.dashboard.components.scheduler' (/opt/conda/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.3.0 / 2021.3.1 / 2021.4.0 / 2021.4.1
- Python version: 3.8.0
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): Docker container from dockerhub -- [daskdev/dask:2021.3.0](https://hub.docker.com/layers/daskdev/dask/2021.3.0/images/sha256-7b43f5fcab30625ce4e6e27125e8bebda6ba03c6e1c499d374e2e109c60409b8?context=explore)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @nickvazz. Can you confirm you're using the same version of `distributed` everywhere (meaning on the scheduler / workers / client)? If so, what version of `distributed` is it?

**Comment by nickvazz** [comment]
I was running only the scheduler when running into this issue. I hadn't deployed to workers/clients quite yet.

The versions _should_ follow whatever is in the docker release it feels like

```bash
(base) root@dask-scheduler:/# pip list
Package                Version
---------------------- -------------------
aiohttp                3.7.4.post0
anyio                  2.2.0
argon2-cffi            20.1.0
async-generator        1.10
async-timeout          3.0.1
attrs                  20.3.0
bleach                 3.3.0
blosc                  1.9.2
bokeh                  2.1.1
brotlipy               0.7.0
certifi                2020.12.5
cffi                   1.14.4
chardet                4.0.0
click                  7.1.2
cloudpickle            1.6.0
conda                  4.9.2
conda-package-handling 1.7.2
cryptography           3.2.1
cytoolz                0.11.0
dask                   2021.3.0
defusedxml             0.7.1
deprecation            2.1.0
distributed            2021.3.0
entrypoints            0.3
fsspec                 0.8.7
HeapDict               1.0.1
idna                   2.10
ipython-genutils       0.2.0
Jinja2                 2.11.3
jsonschema             3.2.0
jupyter-client         6.1.12
jupyter-core           4.7.1
jupyter-packaging      0.9.2
jupyter-server         1.6.4
jupyter-server-proxy   3.0.2
jupyterlab-pygments    0.1.2
locket                 0.2.0
lz4                    3.1.1
MarkupSafe             1.1.1
mistune                0.8.4
msgpack                1.0.0
multidict              5.1.0
nbclient               0.5.3
nbconvert              6.0.7
nbformat               5.1.3
nest-asyncio           1.5.1
numpy                  1.18.1
olefile                0.46
packaging              20.9
pandas                 1.0.1
pandocfilters          1.4.3
partd                  1.1.0
Pillow                 6.2.1
pip                    21.0.1
prometheus-client      0.10.1
psutil                 5.7.3
ptyprocess             0.7.0
pycosat                0.6.3
pycparser              2.20
Pygments               2.9.0
pyOpenSSL              20.0.1
pyparsing              2.4.7
pyrsistent             0.17.3
PySocks                1.7.1
python-dateutil        2.8.1
pytz                   2021.1
PyYAML                 5.1.2
pyzmq                  22.0.3
requests               2.25.1
ruamel-yaml            0.15.87
Send2Trash             1.5.0
setuptools             49.6.0.post20210108
simpervisor            0.4
six                    1.15.0
sniffio                1.2.0
sortedcontainers       2.3.0
tblib                  1.6.0
terminado              0.9.4
testpath               0.4.4
tomlkit                0.7.0
toolz                  0.11.1
tornado                6.1
tqdm                   4.42.1
traitlets              5.0.5
typing-extensions      3.7.4.3
urllib3                1.26.3
webencodings           0.5.1
wheel                  0.36.2
yarl                   1.6.3
zict                   2.0.0
```

**Comment by quasiben** [comment]
Hmm, I used your docker-compose setup and was able to load the dashboard at `localhost:8787`.  Here's the output from  `docker-compose up`

```
dask_scheduler    | Successfully installed Send2Trash-1.5.0 aiohttp-3.7.4.post0 anyio-2.2.0 argon2-cffi-20.1.0 async-generator-1.10 async-timeout-3.0.1 attrs-20.3.0 bleach-3.3.0 defusedxml-0.7.1 deprecation-2.1.0 entrypoints-0.3 ipython-genutils-0.2.0 jsonschema-3.2.0 jupyter-client-6.1.12 jupyter-core-4.7.1 jupyter-packaging-0.9.2 jupyter-server-1.6.4 jupyter-server-proxy-3.0.2 jupyterlab-pygments-0.1.2 mistune-0.8.4 multidict-5.1.0 nbclient-0.5.3 nbconvert-6.0.7 nbformat-5.1.3 nest-asyncio-1.5.1 pandocfilters-1.4.3 prometheus-client-0.10.1 ptyprocess-0.7.0 pygments-2.9.0 pyrsistent-0.17.3 pyzmq-22.0.3 simpervisor-0.4 sniffio-1.2.0 terminado-0.9.4 testpath-0.4.4 tomlkit-0.7.0 traitlets-5.0.5 webencodings-0.5.1 yarl-1.6.3
dask_scheduler    | + exec dask-scheduler
dask_scheduler    | distributed.scheduler - INFO - -----------------------------------------------
dask_scheduler    | distributed.scheduler - INFO - -----------------------------------------------
dask_scheduler    | distributed.scheduler - INFO - Clear task state
dask_scheduler    | distributed.scheduler - INFO -   Scheduler at:     tcp://173.20.0.2:8786
dask_scheduler    | distributed.scheduler - INFO -   dashboard at:                     :8787
```

And after exec-ing into the container was able to load the function you tried

```
❯ docker exec -it 4de99c5b55cb /bin/bash
(base) root@dask-scheduler:/# conda info -e
# conda environments:
#
base                  *  /opt/conda

(base) root@dask-scheduler:/# python
Python 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask
>>> dask.__version__
'2021.03.0'
>>> from distributed.dashboard.components.scheduler import individual_systemmonitor_doc
>>> individual_systemmonitor_doc
<function individual_systemmonitor_doc at 0x7f693ab5ac10>
>>>
```

**Comment by jrbourbeau** [comment]
`individual_systemmonitor_doc` was removed in the `distributed=2021.4.1` release. @nickvazz could you confirm whether the version of `distributed` you're using in the Python REPL is `2021.3.0` or something else?

**Comment by nickvazz** [comment]
Looks like I needed to clear some caches or something (everything works as it should), thank you for the quick help!
