### ISSUE TITLE
dask-scheduler is failing

### ISSUE THREAD

**Issue by AndrewHannigan** [dask/distributed#4812]
Running `dask-scheduler` fails with the following error message:

```
andrew@NSH-HANNIGANAN:/mnt/c/Users/andrew.hannigan/src/debug_dask$ docker run debug /usr/local/bin/dask-scheduler
Traceback (most recent call last):
  File "/usr/local/bin/dask-scheduler", line 5, in <module>
    from distributed.cli.dask_scheduler import go
  File "/usr/local/lib/python3.8/dist-packages/distributed/cli/dask_scheduler.py", line 120, in <module>
    def main(
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 2467, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 2106, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

Here is my environment to reproduce:

Dockerfile
```
FROM ubuntu:20.04

RUN apt-get update \
    && apt-get --assume-yes install python3.8 python3-pip

RUN python3.8 -m pip install distributed
```

Build and run
```
docker build . --tag debugging_dask
docker run debugging_dask dask-scheduler
```

**Comment by jrbourbeau** [comment]
Thanks for reporting @AndrewHannigan. This is due to changes in the latest `click=8` release and should be resolved by https://github.com/dask/distributed/pull/4810. You should be able to workaround this `ValueError` by either installed the development version of `distributed` or temporarily pinning `click < 8`

**Comment by AndrewHannigan** [comment]
Thanks the quick response - will pin to click<8 for time being

**Comment by jrbourbeau** [comment]
Great, thanks @AndrewHannigan! Closing this issue for now, let us know if you run into any other issues
