### ISSUE TITLE
Attempting to launch with SSHCluster for gpu workers doesn't appear to work

### ISSUE THREAD

**Issue by drobison00** [dask/distributed#4814]
**What happened**:
Attempting to launch a local cluster with SSHCluster fails.

*Note*:
Setting worker_module to `dask_cuda.CUDAWorker` or `dask_cuda.dask_cuda_worker`, as indicated in the SSHCluster docs results in a 'no module named ...' error.

**What you expected to happen**:
A functioning cluster to come up.

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import SSHCluster

# May need to put id_rsa.pub in ~/.ssh/authorized_keys
ssh_cluster = SSHCluster(['localhost', 'localhost'],
                        connect_options={"known_hosts": None, 
                                         "client_keys": "~/.ssh/id_rsa.pub"},
                        scheduler_options={"port": 8786, "dashboard_address": 8787},
                        worker_module='dask_cuda.cuda_worker')
client = Client(ssh_cluster)

distributed.deploy.ssh - INFO - distributed.scheduler - INFO - -----------------------------------------------
distributed.deploy.ssh - INFO - distributed.scheduler - INFO - -----------------------------------------------
distributed.deploy.ssh - INFO - distributed.scheduler - INFO - Clear task state
distributed.deploy.ssh - INFO - distributed.scheduler - INFO -   Scheduler at:   tcp://10.10.100.33:8786
distributed.deploy.ssh - INFO - /home/drobison/anaconda3/envs/rapids-0.19/lib/python3.8/runpy.py:127: RuntimeWarning: 'dask_cuda.cuda_worker' found in sys.modules after import of package 'dask_cuda', but prior to execution of 'dask_cuda.cuda_worker'; this may result in unpredictable behaviour
distributed.deploy.ssh - INFO - warn(RuntimeWarning(msg))
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<_wrap_awaitable() done, defined at /home/drobison/anaconda3/envs/rapids-0.19/lib/python3.8/asyncio/tasks.py:688> exception=Exception('Worker failed to start')>
Traceback (most recent call last):
  File "/home/drobison/anaconda3/envs/rapids-0.19/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/drobison/anaconda3/envs/rapids-0.19/lib/python3.8/site-packages/distributed/deploy/spec.py", line 71, in _
    await self.start()
  File "/home/drobison/anaconda3/envs/rapids-0.19/lib/python3.8/site-packages/distributed/deploy/ssh.py", line 133, in start
    raise Exception("Worker failed to start")
Exception: Worker failed to start
distributed.deploy.ssh - INFO - /home/drobison/anaconda3/envs/rapids-0.19/lib/python3.8/runpy.py:127: RuntimeWarning: 'dask_cuda.cuda_worker' found in sys.modules after import of package 'dask_cuda', but prior to execution of 'dask_cuda.cuda_worker'; this may result in unpredictable behaviour
distributed.deploy.ssh - INFO - warn(RuntimeWarning(msg))

....
~/anaconda3/envs/rapids-0.19/lib/python3.8/site-packages/distributed/deploy/ssh.py in start(self)
    131             line = await self.proc.stderr.readline()
    132             if not line.strip():
--> 133                 raise Exception("Worker failed to start")
    134             logger.info(line.strip())
    135             if "worker at" in line:

Exception: Worker failed to start
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.04.0
- Python version: 3.8.8
- Operating System: Linux Mint 20
- Install method (conda, pip, source): conda

**Comment by drobison00** [comment]
Thanks @quasiben for pointing out that `worker_module='dask_cuda.cli.dask_cuda_worker'` is the correct syntax, which resolves the issue, so this seems like a doc fix rather than a bug.
