### ISSUE TITLE
dask-scheduler fails w/ latest version of click

### ISSUE THREAD

**Issue by jesusch** [dask/distributed#4815]
**What happened**:

```
$ pip install --upgrade dask distributed
$ dask-scheduler
Traceback (most recent call last):
  File "/Users/jesusch/git/tvsquared-backend/.venv/bin/dask-scheduler", line 5, in <module>
    from distributed.cli.dask_scheduler import go
  File "/Users/jesusch/git/tvsquared-backend/.venv/lib/python3.9/site-packages/distributed/cli/dask_scheduler.py", line 120, in <module>
    def main(
  File "/Users/jesusch/git/tvsquared-backend/.venv/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/jesusch/git/tvsquared-backend/.venv/lib/python3.9/site-packages/click/core.py", line 2467, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/Users/jesusch/git/tvsquared-backend/.venv/lib/python3.9/site-packages/click/core.py", line 2106, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```
Downgrading click to `<8` solved this

**Comment by jrbourbeau** [comment]
Thanks for reporting @jesusch. The next `distributed` release (which we're pushing out tomorrow) will contain support for `click >= 8`. In the meantime you can, as you mentioned, pin `click < 8`.
