### ISSUE TITLE
Collection of futures gets TimeoutError

### ISSUE THREAD

**Issue by AlecThomson** [dask/distributed#4831]
**What happened**:
Possibly related to #2880.

I'm using `client.persist` to execute delayed tasks (see rough format in the MCVE). I'll note that I get the same error using `client.compute`. Despite using the same code, I recently encountered an error where I get a `TimeoutError` (see traceback). The error points back to the line where I either call `progress(results)` or `client.gather(results)`.  I've found that putting a `time.sleep` between the `persists` and `progress`/`gather` calls prevents this error, but this also seems like a poor workaround.

Traceback:
```
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/comm/core.py", line 320, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 956, in <module>
    cli()
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 931, in cli
    main(field=args.field,
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 803, in main
    tqdm_dask(futures, desc="Running RMsynth...", disable=(not verbose))
  File "/group/askap/athomson/repos/spiceracs/spiceracs/utils.py", line 61, in tqdm_dask
    TqdmProgressBar(futures, **kwargs)
  File "/group/askap/athomson/repos/spiceracs/spiceracs/utils.py", line 48, in __init__
    loop_runner.run_sync(self.listen)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 510, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 64, in listen
    self.comm = await connect(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/comm/core.py", line 325, in connect
    raise IOError(
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:39589 after 10 s
/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/RMutils/util_misc.py:425: RuntimeWarning: invalid value encountered in log10
  np.exp(a*lnx**5+b*lnx**4+c*lnx**3+d*lnx**2+f*lnx+np.log10(g))]
/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/RMutils/util_misc.py:425: RuntimeWarning: invalid value encountered in log10
  np.exp(a*lnx**5+b*lnx**4+c*lnx**3+d*lnx**2+f*lnx+np.log10(g))]
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
```

**What you expected to happen**:
I'd expect the `progress` or `gather` methods to wait on the execution of the future, and not need a `time.sleep`.

**Minimal Complete Verifiable Example**:
Whilst this matches the structure of my main script (matching the above traceback), this MCVE does not reproduce the error, unfortunately.

```python
from dask import delayed
from dask.distributed import Client, progress, LocalCluster
import time

def inner_job(i):
    return i+1

@delayed
def job(x):
    time.sleep(1)
    y = inner_job(x)
    return y

def main(client):

    njobs = int(1000)
    outputs = []
    for i in range(njobs):
        output = job(i)
        outputs.append(output)

    results = client.persist(outputs)
    print("Running test...")
    progress(results)

def cli():
    cluster = LocalCluster(n_workers=20, dashboard_address=':9999')
    client = Client(cluster)

    main(client)

if __name__ == "__main__":
    cli()
```

**Environment**:

- Dask version: 2021.5.0
- Python version: 3.8.10
- Operating System: SUSE Linux Enterprise Server 12 SP3
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @AlecThomson! From the traceback it looks like there's a third-party `TqdmProgressBar` object where the error is originating from. It would be great if we could reproduce the issue with `dask` / `distributed` alone. Otherwise, it will be difficult to determine if this is a Dask issue or not

**Comment by AlecThomson** [comment]
Ah, sorry @jrbourbeau -- I was experimenting with a progress bar at the same time. The error occurs regardless of how the futures are called. This is the traceback when using `progress(results)` (as above):
```
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/comm/core.py", line 320, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 955, in <module>
    cli()
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 930, in cli
    main(field=args.field,
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 804, in main
    progress(futures)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 439, in progress
    TextProgressBar(futures, complete=complete, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 122, in __init__
    loop_runner.run_sync(self.listen)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 510, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 64, in listen
    self.comm = await connect(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/comm/core.py", line 325, in connect
    raise IOError(
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:34553 after 10 s
```

And now with `client.gather(results)`:
```
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/comm/core.py", line 320, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 955, in <module>
    cli()
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 930, in cli
    main(field=args.field,
  File "/home/athomson/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py", line 804, in main
    progress(futures)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 439, in progress
    TextProgressBar(futures, complete=complete, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 122, in __init__
    loop_runner.run_sync(self.listen)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 510, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/diagnostics/progressbar.py", line 64, in listen
    self.comm = await connect(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/comm/core.py", line 325, in connect
    raise IOError(
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:34553 after 10 s
(spice) athomson@nid00050:/scratch/ja3/athomson/spice_test> python ~/athomson/repos/spiceracs/spiceracs/rmsynth_oncuts.py 1147+06A /scratch/ja3/athomson/spice_test $host -m -o -5 -v 
Testing MongoDB connection...
MongoDB connection succesful!
Saving to /scratch/ja3/athomson/spice_test/cutouts/frequencies.txt
Running RMsynth on 4492 components
Done!
distributed.core - ERROR - Exception while handling op heartbeat_worker
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3861, in heartbeat_worker
    ws._executing = {
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3862, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'rmsynthoncut1d-006073d9-87e8-4fd1-b597-939d6f26d6e1'
distributed.core - ERROR - Exception while handling op heartbeat_worker
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3861, in heartbeat_worker
    ws._executing = {
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3862, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'rmsynthoncut1d-006587f7-8d39-4161-a8b0-3189f15e990e'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2aac2c659190>>, <Task finished name='Task-163' coro=<Worker.heartbeat() done, defined at /group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/worker.py:943> exception=KeyError('rmsynthoncut1d-006073d9-87e8-4fd1-b597-939d6f26d6e1')>)
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/worker.py", line 954, in heartbeat
    response = await retry_operation(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils_comm.py", line 385, in retry_operation
    return await retry(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 862, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 661, in send_recv
    raise exc.with_traceback(tb)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3861, in heartbeat_worker
    ws._executing = {
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3862, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'rmsynthoncut1d-006073d9-87e8-4fd1-b597-939d6f26d6e1'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2aac2c659190>>, <Task finished name='Task-163' coro=<Worker.heartbeat() done, defined at /group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/worker.py:943> exception=KeyError('rmsynthoncut1d-006587f7-8d39-4161-a8b0-3189f15e990e')>)
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/worker.py", line 954, in heartbeat
    response = await retry_operation(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils_comm.py", line 385, in retry_operation
    return await retry(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 862, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 661, in send_recv
    raise exc.with_traceback(tb)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3861, in heartbeat_worker
    ws._executing = {
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3862, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'rmsynthoncut1d-006587f7-8d39-4161-a8b0-3189f15e990e'
distributed.core - ERROR - Exception while handling op heartbeat_worker
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3861, in heartbeat_worker
    ws._executing = {
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3862, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'rmsynthoncut1d-00697d3b-3582-473c-a03f-ade15d338030'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2aac2c659190>>, <Task finished name='Task-163' coro=<Worker.heartbeat() done, defined at /group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/worker.py:943> exception=KeyError('rmsynthoncut1d-00697d3b-3582-473c-a03f-ade15d338030')>)
Traceback (most recent call last):
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/worker.py", line 954, in heartbeat
    response = await retry_operation(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils_comm.py", line 385, in retry_operation
    return await retry(
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 862, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 661, in send_recv
    raise exc.with_traceback(tb)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3861, in heartbeat_worker
    ws._executing = {
  File "/group/askap/athomson/miniconda3/envs/spice/lib/python3.8/site-packages/distributed/scheduler.py", line 3862, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: 'rmsynthoncut1d-00697d3b-3582-473c-a03f-ade15d338030'
```

**Comment by zhangte113** [comment]
I got the same problem with you
 `distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\protocol\core.py", line 107, in loads
    small_payload = frames.pop()
IndexError: pop from empty list
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\comm\core.py", line 319, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\comm\tcp.py", line 221, in read
    allow_offload=self.allow_offload,
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\comm\utils.py", line 80, in from_frames
    res = _from_frames()
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\comm\utils.py", line 64, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\protocol\core.py", line 107, in loads
    small_payload = frames.pop()
IndexError: pop from empty list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:/COSIPY/cosipy/test_dask1.py", line 6, in <module>
    c1 = Client("10.100.207.208:8786")
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\client.py", line 746, in __init__
    self.start(timeout=timeout)
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\client.py", line 954, in start
    sync(self.loop, self._start, **kwargs)
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\utils.py", line 351, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\utils.py", line 334, in f
    result[0] = yield future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\client.py", line 1044, in _start
    await self._ensure_connected(timeout=timeout)
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\client.py", line 1102, in _ensure_connected
    self.scheduler.address, timeout=timeout, **self.connection_args
  File "C:\Users\Administrator\Documents\Python\Python3.7\lib\site-packages\distributed\comm\core.py", line 326, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://10.100.207.208:8786 after 10 s`

I just connected my computer with another computer through `dask-scheduler` and `dask-worker 10.100.207.208:8786`. When I run my code in pycharm, it appeared the error. I did a test, the error only occored while I cun my code in pycharm, however, in jupyter will not appear.

**Comment by fjetter** [comment]
@zhangte113 your issue seems to be triggered by a serialization error and the version you are using is pre-`2021.04.X`. I would suggest to update and see if the issue persists
