### ISSUE TITLE
dask-scheduler CLI fails on click version 8.0.1

### ISSUE THREAD

**Issue by Nihhaar** [dask/distributed#4843]
**What happened**:
Installed dask[complete] package on a fresh machine and ran `dask-scheduler` command. It failed with following error:
```
(daskenv) ubuntu@host:~$ dask-scheduler
Traceback (most recent call last):
  File "/home/ubuntu/daskenv/bin/dask-scheduler", line 5, in <module>
    from distributed.cli.dask_scheduler import go
  File "/home/ubuntu/daskenv/lib/python3.6/site-packages/distributed/cli/dask_scheduler.py", line 122, in <module>
    @click.version_option()
  File "/home/ubuntu/daskenv/lib/python3.6/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/ubuntu/daskenv/lib/python3.6/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/home/ubuntu/daskenv/lib/python3.6/site-packages/click/core.py", line 2110, in __init__
    ) from None
ValueError: 'default' must be a list when 'multiple' is true.
```

**What you expected to happen**:
To work normally as stated in the docs

**Minimal Complete Verifiable Example**:
Same as above.

**Anything else we need to know?**:
I think this is due to a click version compatibility. Works fine when using `click==6.6`. But installed version of click when using `pip3 install dask[complete]` is `click==8.0.1`.

**Environment**: Linux (Ubuntu)

- Dask version: 2021.3.0
- Python version: 3.6
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
Thanks for reporting @Nihhaar. `2021.05.0` has support for click >= 8.   We were able to fix this issue for older versions in conda but not for pypi.  You can either upgrade to restrict to `click < 8` when installing
