### ISSUE TITLE
"500: Internal Server Error" in dask scheduler

### ISSUE THREAD

**Issue by michaeldoron59** [dask/distributed#4851]
I get this log:
dask version = '2021.05.0'
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 671, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in update
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
distributed.utils - ERROR - int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 671, in log_errors
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 2279, in status_doc
    processing.update()
  File "/opt/conda/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 93, in func
    return input_function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in update
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
tornado.application - ERROR - Uncaught exception GET /status (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/status', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line ckages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 2279, in status_doc
    processing.update()
  File "/opt/conda/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 93, in func
    return input_function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in update
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 2279, in status_doc
    processing.update()
  File "/opt/conda/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 93, in func
    return input_function(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in update
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
  File "/opt/conda/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1112, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Looks like some new feature and broken code..
Thanks

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @michaeldoron59. Are you able to provide a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports) that we can run which reproduces the issue?

**Comment by michaeldoron59** [comment]
well, it just happens after I use helm to install it in my gcloud-kubernetes environment. Basically I only run the basic dask-scheduler command and then I try to connect it via my browser.

**Comment by jrbourbeau** [comment]
Do you connect a `Client` to the scheduler after running `dask-scheduler`?

**Comment by michaeldoron59** [comment]
yes, I can connect to the scheduler and it works properly, the only thing that doesn't work is the bokeh monitor.

**Comment by michaeldoron59** [comment]
I just did a rollback to my GKE docker image, and now everything works properly, so it seems that the problem is at your side..

**Comment by michaeldoron59** [comment]
I see that this problem was already in another variation [here](https://github.com/dask/distributed/issues/2474)

**Comment by michaeldoron59** [comment]
@jrbourbeau ?

**Comment by quasiben** [comment]
@jacobtomlinson do you have time to test out latest dask helm chart to see if you can reproduce ?

**Comment by jacobtomlinson** [comment]
With the latest release of the Dask helm chart I am unable to reproduce this.

Steps I tried:
- Deploy Dask helm chart 
- Port forward Jupyter service locally, create a `Client` and do some quick `dask.array` tests
- Port forward the scheduler dashboard service locally and view all tabs.

**Comment by fphammerle** [comment]
I have the same issue on `v2021.05.1`.

Requests to scheduler at http://127.0.0.1:8787/status return HTTP500.
Scheduler's log:
```python
tornado.application - ERROR - Uncaught exception GET /status (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/status', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  [...]
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 1110, in <listcomp>
    cpu = [int(ws.metrics["cpu"]) for ws in workers]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

http://127.0.0.1:8787/workers
```python
tornado.application - ERROR - Uncaught exception GET /workers (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/workers', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  [...]
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 2106, in update
    data["memory_percent"][-1] = ws.metrics["memory"] / ws.memory_limit
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

http://127.0.0.1:8787/system
```python
[...]
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 2167, in systemmonitor_doc
    sysmon = SystemMonitor(scheduler, sizing_mode="stretch_both")
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/dashboard/components/shared.py", line 477, in __init__
    update(self.source, self.get_data())
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/dashboard/components/shared.py", line 573, in get_data
    d = self.worker.monitor.range_query(start=self.last_count)
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/system_monitor.py", line 123, in range_query
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/system_monitor.py", line 123, in <dictcomp>
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
  File "/home/someone/.venv/lib/python3.8/site-packages/distributed/system_monitor.py", line 123, in <listcomp>
    d = {k: [v[i] for i in seq] for k, v in self.quantities.items()}
IndexError: deque index out of range
```

http://127.0.0.1:8787/tasks and http://127.0.0.1:8787/info/main/workers.html look ok

**Comment by jacobtomlinson** [comment]
Without a minimal reproducer like @jrbourbeau suggests in https://github.com/dask/distributed/issues/4851#issuecomment-848215293 we can't start to debug this. I am unable to reproduce so far.

**Comment by fphammerle** [comment]
Thanks for your reply! I am sorry, I didn't test this immediately but
the upgrade from `v2021.05.1` to `v2021.6.0` fixed the issues mentioned here: https://github.com/dask/distributed/issues/4851#issuecomment-855742641
I am now able to open all tabs of the scheduler's dashboard.

**Comment by michaeldoron59** [comment]
> Without a minimal reproducer like @jrbourbeau suggests in [#4851 (comment)](https://github.com/dask/distributed/issues/4851#issuecomment-848215293) we can't start to debug this. I am unable to reproduce so far.

Well I suppose we should try to update and see if the problem being resolved, as it's very complicated to let you a minimal reproducible example..  The only possibility I see here is that some developer will make a meeting with me and I'll let him see the problem. But I think that for now I'll just try to update..

**Comment by ncclementi** [comment]
Hi @michaeldoron59 , checking in to see what's the status of this issue. Where you able to solve the problem with the update?

**Comment by ncclementi** [comment]
After no response to the comment above, I'm closing this issue since it seems the problem has been resolved or it's not present in the latest Dask versions. Please feel free to re-open with a minimal reproducer, otherwise, we can't tart to debug.
