### ISSUE TITLE
Getting error concurrent.futures._base.CancelledError: single_cutoff_forecast using fbprophet

### ISSUE THREAD

**Issue by luanmota** [dask/distributed#4931]
Hey guys! So I'm using prophet with dask and I'm getting stuck in this error:

`Importing plotly failed. Interactive plots will not work.
C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\distributed\client.py:1130: VersionMismatchWarning: Mismatched versions found

+---------+----------------+---------------+---------------+
| Package | client         | scheduler     | workers       |
+---------+----------------+---------------+---------------+
| numpy   | 1.20.2         | 1.19.1        | 1.19.1        |
| python  | 3.8.10.final.0 | 3.8.5.final.0 | 3.8.5.final.0 |
+---------+----------------+---------------+---------------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
Initial log joint probability = -24.2201
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      81       507.814  9.69009e-009       4988.52      0.2792      0.2792      101   
Optimization terminated normally: 
  Convergence detected: absolute parameter change was below tolerance
INFO:prophet:Making 17 forecasts with cutoffs between 2012-02-08 00:00:00 and 2019-12-28 00:00:00
INFO:prophet:Applying in parallel with <Client: 'tls://10.6.61.225:46688' processes=2 threads=4, memory=8.59 GB>
Traceback (most recent call last):
  File "C:/Users/luanm/Desktop/SES/modelos-de-forecast/app/main.py", line 5, in <module>
    resposta = prophet_coss_validation()
  File "C:\Users\luanm\Desktop\SES\modelos-de-forecast\app\Prophet.py", line 53, in prophet_coss_validation
    df_cv = prophet.diagnostics.cross_validation(m, initial='730 days', period='180 days', horizon = '365 days', parallel='dask')
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\prophet\diagnostics.py", line 193, in cross_validation
    predicts = pool.gather(predicts)
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\distributed\client.py", line 1987, in gather
    return self.sync(
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\distributed\client.py", line 833, in sync
    return sync(
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\distributed\utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\distributed\utils.py", line 323, in f
    result[0] = yield future
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\luanm\Anaconda3\envs\modelos-de-forecast\lib\site-packages\distributed\client.py", line 1853, in _gather
    raise exc
concurrent.futures._base.CancelledError: single_cutoff_forecast-9c16d68592673fa9596cbf0d96de9258

Process finished with exit code 1
`

My distributed version is 2.26.0, and I'm using the example code from prophet site to hyperparameter tuning:

`# Python
import itertools
import numpy as np
import pandas as pd

param_grid = {  
    'changepoint_prior_scale': [0.001, 0.01, 0.1, 0.5],
    'seasonality_prior_scale': [0.01, 0.1, 1.0, 10.0],
}

# Generate all combinations of parameters
all_params = [dict(zip(param_grid.keys(), v)) for v in itertools.product(*param_grid.values())]
rmses = []  # Store the RMSEs for each params here

# Use cross validation to evaluate all parameters
for params in all_params:
    m = Prophet(**params).fit(df)  # Fit model with given params
    df_cv = cross_validation(m, cutoffs=cutoffs, horizon='30 days', parallel="dask")
    df_p = performance_metrics(df_cv, rolling_window=1)
    rmses.append(df_p['rmse'].values[0])

# Find the best parameters
tuning_results = pd.DataFrame(all_params)
tuning_results['rmse'] = rmses
print(tuning_results)`

-Prophet version: 1.0.1
- Dask version: 2.26.0
- Python version: 3.8.10.final.0
- Operating System: Windows
- Install method (conda, pip, source): conda

**Comment by fjetter** [comment]
The distributed version `2.26.0` was released on 11th September 2020. Can you please try a more recent version to see if the error persists?

**Comment by jrbourbeau** [comment]
Also cc'ing @TomAugspurger for visibility

**Comment by luanmota** [comment]
@fjetter I will check this possibility with the team because we have others projects running with dask and distributed in this version. Maybe this can take a while.

**Comment by fjetter** [comment]
I would also suggest to try running the scripts with the same environment on client side as installed on the dask cluster. the warning already indicates that there is a difference between numpy and python versions. that can cause issues with data or task serialization

**Comment by TomAugspurger** [comment]
@luanmota you might be able to try a more recent version of dask / distributed using a LocalCluster in a virtual environment. That wouldn't conflict with your team's work.

**Comment by jrbourbeau** [comment]
Closing due to inactivity. @luanmota feel free to re-open if you would like to continue
