### ISSUE TITLE
Memory spike and CancelledError when calling `dataframe.set_index()` on single machine

### ISSUE THREAD

**Issue by jqmp** [dask/distributed#4935]
Hi all, I'm trying to use Dask's distributed scheduler to work with a large dataframe on a single machine, but it's crashing when I try to modify the index. Any ideas what might be causing this?

**What happened**:

I'm using the distributed scheduler on a single machine (a 2019 MacBook Pro, 6 cores, 32GB RAM). When I call `set_index` on a large Dask DataFrame and then try to write the result to Parquet, the main process's memory usage blows up to about 40GB and then fails with a `CancelledError`:

```
/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/worker.py:3693: UserWarning: Large object of size 2.10 MiB detected in task graph:
  [["('to-parquet-a3f2e5760f0b5dfd7d318e5894cc656f', ... _data.pq.dask']
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s)
distributed.batched - INFO - Batched Comm Closed:
Traceback (most recent call last):
  File "/Users/janek/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/janek/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/janek/Development/cms/fail.py", line 18, in <module>
    dd.to_parquet(df, './indexed_data.pq.dask', write_index=True)
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 648, in to_parquet
    out = out.compute(**compute_kwargs)
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/client.py", line 2673, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/client.py", line 1988, in gather
    asynchronous=asynchronous,
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/client.py", line 854, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
concurrent.futures._base.CancelledError
```

**What you expected to happen**:

I expected the re-indexed frame to be written to a file, without using a lot of memory.

**Minimal Complete Example**:

Unfortunately it's not easy to share my dataset, but my failing code looks like this:

```python
import dask.dataframe as dd
from dask.distributed import Client

dask_client = Client('tcp://192.168.7.66:8766')

df = dd.read_parquet('./bad_data.pq.dask')
df = df.set_index('claim_id', shuffle='disk')
dd.to_parquet(df, './indexed_data.pq.dask', write_index=True)
```

This consistently produces a memory blowup and crash. I'm running the cluster separately like this:

```bash
dask-scheduler --dashboard-address :8777 --port 8766
dask-worker tcp://192.168.7.66:8766 --nprocs 4 --nthreads 3 --memory-limit 8GB
```

**Anything else we need to know?**:

 My dataset is somewhat sensitive and I can't put it in the cloud, which is why I'm stuck with a single machine.

The frame in question has about 1 billion rows. For the minimal example above, I've reduced the dataframe to just a single column plus an index, both `int64` and hence both taking about 8GB (according to `df.memory_usage(deep=True)`), and I still get the same failure. However, my full dataset has more columns and uses 300 GB or so, which is why I'm using Dask.

To isolate the problem, I looked into what `set_index()` is doing. It seems to boil down to calling `_calculate_divisions()` and then `set_partition()`, which itself does a `map_partitions(set_partitions_pre, ...)` followed by some other stuff. So, I saved the result of `_calculate_divisions` and then made a test script that just calls `map_partitions(set_partitions_pre, ...)` in the same way and tries to write the result to Parquet. This produces the same failure.

```python
import pickle

import dask.dataframe as dd
from dask.distributed import Client

dask_client = Client('tcp://192.168.7.66:8766')

df = dd.read_parquet('./bad_data.pq.dask')

with open ('./divisions.pkl', 'rb') as f:
    divisions_ = pickle.load(f)
assert divisions_ == tuple(sorted(divisions_))
assert len(divisions_) == df.npartitions + 1

index = 'claim_id'
dtype = df[index].dtype
meta = df._meta._constructor_sliced([0])
divisions = df._meta._constructor_sliced(divisions_, dtype=dtype)

partitions = df[index].map_partitions(
    dd.shuffle.set_partitions_pre, divisions=divisions, meta=meta,
)
df2 = df.assign(_partitions=partitions)

dd.to_parquet(df2, '/Volumes/JS CMS Data/scratch/intermediate_data.pq.dask', write_index=True)
```

**Environment**:

- Dask version: 2021.06.0
- Distributed version: 2021.06.0
- Python version: 3.7.3 (default, Dec  8 2019, 12:38:49) \n[Clang 11.0.0 (clang-1100.0.33.12)]
- Operating System: Mac OS 10.15.7
- Install method: pip

`pyarrow` is installed; `fastparquet` is not.

Thanks!

**Comment by fjetter** [comment]
Does the same happen if you disable the `write_index`? True is the default.

I'm just wondering if the computation is running OOM due to the shuffle itself and not the to_parquet.

cc @rjzamora

**Comment by jqmp** [comment]
Thanks for the reply @fjetter! Yes, the same happens when `write_index=False`.

I'm not an expert but my sense is that the problem is in the computation, not the `to_parquet`. If I replace the `to_parquet()` with, say, `print(df.map_partitions(lambda p: None).compute())`, I still get a failure, but with some differences: the memory blowup happens in the scheduler process instead of the client process, I have manually kill the scheduler, and there are error messages in both the scheduler and worker logs.

Scheduler logs:
```
distributed.scheduler - INFO - Task ('assign-5b246c6c6a6636f3717709a5fabf0ac4', 27380) marked as failed because 3 workers died while trying to run it
distributed.scheduler - INFO - Task ('assign-5b246c6c6a6636f3717709a5fabf0ac4', 30895) marked as failed because 3 workers died while trying to run it
(... repeated many times ...)
distributed.scheduler - INFO - Task ('assign-5b246c6c6a6636f3717709a5fabf0ac4', 0) marked as failed because 3 workers died while trying to run it
distributed.scheduler - INFO - Lost all workers
distributed.core - INFO - Event loop was unresponsive in Scheduler for 65.52s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 22] Invalid argument
```
Worker logs:
```
tornado.application - ERROR - Exception in callback <function Worker.__init__.<locals>.<lambda> at 0x115a0a7b8>
Traceback (most recent call last):
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/worker.py", line 732, in <lambda>
    lambda: self.batched_stream.send({"op": "keep-alive"}), 60000
  File "/Users/janek/Development/cms/.venv/lib/python3.7/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError()
distributed.comm.core.CommClosedError
(... repeated several times)
```

**Comment by fjetter** [comment]
It may just be the case that the dataframe you're trying to shuffle is a bit too big for your machine to handle. Even dask has its limits. Since I don't have a reproducer I can only guess what's wrong but there are two things you may want to try

1. Reduce the number of partitions. You mentioned that the scheduler/client processes grow in memory. that is often caused by graph optimization and (de-)serialization which becomes increasingly expensive for large graphs. Depending on the partitioning of your input data, you may want to reduce the number of tasks in your task graph.

```python
ddf = dd.read_parquet('./bad_data.pq.dask')
# Reduce the number of partitions by 2. Maybe more aggressive repartitioning is necessary, that depends on the input data
ddf = ddf.repartition(npartitions=ddf.npartitions//2)
ddf = ddf.set_index('claim_id', shuffle='disk')
```

2. There is currently a PR open which drastically improves scheduling for high memory pressure situations which might solve your problem. see https://github.com/dask/distributed/pull/4967

**Comment by jqmp** [comment]
Thanks for the suggestions @fjetter! I'm currently traveling but will try both of these ideas when I get home.

**Comment by fjetter** [comment]
Since this is a memory problem it might also be worth checking out the following links. There has been a lot of movement in the memory management space and your example might benefit from it as well.

https://coiled.io/tackling-unmanaged-memory-with-dask/
https://distributed.dask.org/en/latest/worker.html#memory-not-released-back-to-the-os
https://youtu.be/nwR6iGR0mb0
