### ISSUE TITLE
Can not connect to the scheduler with large number of workers

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#499]
I set up a cluster with 25 nodes x32 cores with workers running in threaded mode. The scheduler logs show the following error for each of the workers.

```
Sep 08 18:42:23 conda[15999]: yield
Sep 08 18:42:23 conda[15999]: File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/bokeh/status/main.py", line 62, in progress_update
Sep 08 18:42:23[15999]: nb = nbytes_bar(msg['nbytes'])
Sep 08 18:42:23 [15999]: KeyError: 'nbytes'
Sep 08 18:42:23 [15999]: distributed.utils - ERROR - 'nbytes'
Sep 08 18:42:23  conda[15999]: Traceback (most recent call last):
Sep 08 18:42:23conda[15999]: File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/utils.py", line 207, in log_errors
Sep 08 18:42:23  conda[15999]: yield
Sep 08 18:42:23  conda[15999]: File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/bokeh/status/main.py", line 62, in progress_update
```

Since this, i also cannot connect to the Scheduler

```
e =  Executor('127.0.0.1:8786', set_as_default=True)
```

```
distributed.utils - ERROR - Could not connect to 127.0.0.1:8786
Traceback (most recent call last):
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/core.py", line 303, in connect
    stream = yield gen.with_timeout(timedelta(seconds=timeout), future)
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.gen.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/executor.py", line 371, in ensure_connected
    stream = yield connect(self.scheduler.ip, self.scheduler.port)
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/core.py", line 313, in connect
    raise IOError("Timed out while connecting to %s:%d" % (ip, port))
OSError: Timed out while connecting to 127.0.0.1:8786

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/utils.py", line 103, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/executor.py", line 342, in _start
    yield self.ensure_connected()
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/.miniconda/envs/dask_env/lib/python3.5/site-packages/distributed/executor.py", line 374, in ensure_connected
    (self.scheduler.ip, self.scheduler.port))
OSError: Could not connect to 127.0.0.1:8786

```

I don't get this type of error when i reduce the number of workers (by shutting down nodes)

**Comment by mrocklin** [comment]
The error you're getting is happening in the Bokeh server.  We should definitely resolve it but it's probably only happening on your scheduler machine and it's well isolated from the scheduler itself (they are separate processes)

**Comment by mrocklin** [comment]
You could verify that this wasn't what was causing the issue by starting the scheduler with the flag `--no-bokeh`

I don't suppose there are any other logs coming out of the scheduler that might be of interest?

**Comment by hussainsultan** [comment]
with `--no-bokeh` option, i can connect to the Executor and everything seems to be working.

**Comment by mrocklin** [comment]
That's surprising.  I can fix the issue with the `nbytes` bit fairly easily but it's concerning that things weren't well isolated.  I would be interested in seeing the logs if available (though I assume that these are private)

**Comment by hussainsultan** [comment]
i can collect scheduler logs pretty easily and clean it up for interesting bits.  Its a bit pain to collect workers logs at this time.

**Comment by mrocklin** [comment]
I don't expect the worker logs to contain much of value for this issue.

**Comment by hussainsultan** [comment]
k. will paste em here after a skim.

**Comment by hussainsultan** [comment]
It turns out the logs are pretty hard to clean up for public posting. However, i see the above message repeated over and over again. I think the writing to logs or some scheduler processor that is responsible for popping that up is busy and blocks the scheduler from connecting. Is this plausible? I don't see any code that depends on bokeh webapp for scheduler function so i believe the isolation is pretty clean.

**Comment by mrocklin** [comment]
It should write that message every 100ms or so.  The scheduler should be able to handle writing that volume of logs without an issue.

**Comment by hussainsultan** [comment]
i see. I think this can be closed. I will reopen if i see it again and hopefully with more concrete logs.

**Comment by hussainsultan** [comment]
It appears this error is indeed unrelated to Bokeh server. After carefully testing this on different configurations, the above error happens when i am run dask workers in threaded mode running more than approximately 450 threaded workers.
Here is how i run dask workers on my machines
```
dask-worker scheduler:8786 --nprocs 32
```

The [scheduler-logs](https://github.com/dask/distributed/files/465484/scheduler-cleaned.txt) show that all workers successfully register and start compute streams and go into this `Collecting unused Streams` state.

Everything works fine when i run the workers with single process.

**Comment by mrocklin** [comment]
@hussainsultan I would be interested in the number of active and open connections in the Scheduler's `ConnectionPool`.  If you have IPython on the scheduler node this should be easy to get with the following:

```python
>>> client.start_ipython_scheduler()
>>> %scheduler scheduler.rpc
<ConnectionPool: open=XXX active=XXX>
```

**Comment by hussainsultan** [comment]
is `client = Client('127.0.0.1:8786')` ? Also, how do you install %scheduler magic?

**Comment by mrocklin** [comment]
With the method `start_ipython_scheduler()`

    Client == Executor
