### ISSUE TITLE
Intermittent failure with ipython_scheduler test

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#503]
The test `distributed/tests/test_ipython.py::test_start_ipython_scheduler` seems to hang intermittently.  When it fails locally it doesn't break even with a `KeyboardInterrupt`.  @minrk any thoughts as to where to start looking for the problem?

**Comment by minrk** [comment]
Arg! I'll see what I can dig up. Probably an issue with sockets being slow to connect.

**Comment by mrocklin** [comment]
Interestingly the test_joblib_simple test is also failing with a jupyter related error.

    py.test distributed/tests/test_joblib.py::test_simple[joblib0]

```
Exception in thread Thread-471:
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/jupyter_client/channels.py", line 144, in run
    self.socket.send(b'ping')
  File "zmq/backend/cython/socket.pyx", line 617, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6625)
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6363)
  File "zmq/backend/cython/socket.pyx", line 199, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2492)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Socket operation on non-socket
```

**Comment by minrk** [comment]
Oh, I bet some sockets are not getting properly cleaned up.

**Comment by GenevieveBuckley** [comment]
Is this behavior still occurring, or should we close this issue?
