### ISSUE TITLE
Dask worker dashboard url found on Info page sends 403 response

### ISSUE THREAD

**Issue by niole** [dask/distributed#5042]
**What happened**:

Dask worker dashboard url found on Info page sends 403 response. This is the link:
https://cloud-develop.domino.tech/niole_nelson/dasktests/workspace/60e7772298ec2b0a9cdbe306/dask/ui/proxy/8787/100.96.88.30/status

**What you expected to happen**:

Should be able to see the worker dashboard

**Minimal Complete Verifiable Example**:

1. deploy a dask cluster on a k8s cluster behind a reverse proxy
2. write code that lets the dashboard be visible behind the reverse proxy
3. Install jupyter-server-proxy in the scheduler
3. go to the **Info** page in the dashboard, click on the dashboard link on one of your workers
4. the request fails with a 403

**Anything else we need to know?**:

stack trace on scheduler:
```
tornado.application - ERROR - Uncaught exception in write_error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1681, in _execute
    result = self.prepare()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 489, in prepare
    raise web.HTTPError(403)
tornado.web.HTTPError: HTTP 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1217, in send_error
    self.write_error(status_code, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 571, in write_error
    html = self.render_template('%s.html' % status_code, **ns)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 502, in render_template
    template = self.get_template(name)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/base/handlers.py", line 498, in get_template
    return self.settings['jinja2_env'].get_template(name)
KeyError: 'jinja2_env'
```

the code in jupyter_server that's failing: https://github.com/jupyter-server/jupyter_server/blob/master/jupyter_server/base/handlers.py#L488

Is there a way to configure `allow_remote_access` to be true? https://github.com/jupyter-server/jupyter_server/blob/master/jupyter_server/base/handlers.py#L455

**Environment**:

- Dask version: 
```
>>> dask.__version__
'2021.06.0'
```
- Python version:
```
python --version
Python 3.8.0
```
- Operating System: Linux Debian 10.3
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @niole. From the traceback you posted it seems like this may be a Jupyter configuration issue instead of a Dask issue

> Is there a way to configure allow_remote_access to be true?

IIUC this should be able to be configured with Jupyter's configuration system https://jupyter-notebook.readthedocs.io/en/stable/config.html

**Comment by niole** [comment]
@jrbourbeau it does seem like a jupyter config issue. I have followed the directions in here, but the values are not picked up by jupyter-server. Do you know of someone/a project that has successfully configured this? Maybe that will help me understand what I'm doing wrong

**Comment by niole** [comment]
output from `jupyter-server` command on the dask scheduler:

```
(base) root@dask-60f1abac8c1d3b56c71508e2-dask-scheduler-0:/# jupyter-server --Application.show_config=true
[I 2021-07-16 16:07:24.616 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2021-07-16 16:07:24.660 ServerApp] jupyter_server_proxy | extension was successfully loaded.
Loaded config files:
  /root/.jupyter/jupyter_server_config.py

NotebookApp
  .allow_remote_access = True
ServerApp
  .allow_remote_access = True
  .jpserver_extensions = <LazyConfigValue {'update': {'jupyter_server_proxy': True}}>
```

**Comment by jrbourbeau** [comment]
cc @jacobtomlinson in case you have any thoughts here

**Comment by jacobtomlinson** [comment]
I don't I'm afraid. I think `allow_remote_access` is the right thing to configure.

@yuvipanda any chance I can rope you in here? Where does this config need to go?
