### ISSUE TITLE
distributed.worker - ERROR - ('waiting', 'executing') OR distributed.protocol.core - CRITICAL - Failed to deserialize

### ISSUE THREAD

**Issue by bsesar** [dask/distributed#5047]
**What happened**:

The MCV example below works on dask+distributed 2021.3.0, but an error is reported. The same example does *not* work on later versions, but instead the code either stops with an error (2021.3.1 and 2021.4.0), or just hangs (2021.4.1 and later versions).

**What you expected to happen**:

The code should create a folder called ```output``` with 240 CSV files without reporting any errors.

**Minimal Complete Verifiable Example**:

```python
import multiprocessing.popen_spawn_win32
from dask.distributed import Client
import dask.dataframe as dd
import pandas as pd
from shutil import rmtree
import numpy as np

client = Client()

# create a DataFrame with a string index
Nrows = 83345093
df = pd.DataFrame(np.random.randn(Nrows, 2), columns=list('AB'), index=pd.util.testing.rands_array(16, Nrows, dtype='O'))

# create a Dask DataFrame
ddf = dd.from_pandas(df, npartitions=240)

# dump the DataFrame to CSV
ddf.to_csv('output')
```
When using dask=2021.3.0 and distributed=2021.3.0, the following error is reported, but the ```output``` folder is created with 240 CSV files
```
distributed.worker - ERROR - ('waiting', 'executing')
Traceback (most recent call last):
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\worker.py", line 2689, in execute
    await self.ensure_computing()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\worker.py", line 2561, in ensure_computing
    self.transition(ts, "executing")
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\worker.py", line 1553, in transition
    func = self._transitions[start, finish]
KeyError: ('waiting', 'executing')
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x000002775BDC6F70>>, <Task finished name='Task-10810' coro=<Worker.execute() done, defined at C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\worker.py:2570> exception=KeyError(('waiting', 'executing'))>)
Traceback (most recent call last):
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
```

With dask+distributed 2021.3.1 or 2021.4.0, the code creates the ```output``` folder without any CSV files, it crashes, and a different error is reported

```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\protocol\core.py", line 104, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: 2917822586 exceeds max_bin_len(2147483647)
distributed.core - ERROR - 2917822586 exceeds max_bin_len(2147483647)
Traceback (most recent call last):
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\core.py", line 555, in handle_stream
    msgs = await comm.read()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\tcp.py", line 218, in read
    msg = await from_frames(
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\utils.py", line 80, in from_frames
    res = _from_frames()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\utils.py", line 63, in _from_frames
    return protocol.loads(
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\protocol\core.py", line 104, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: 2917822586 exceeds max_bin_len(2147483647)
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\core.py", line 501, in handle_comm
    result = await result
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\scheduler.py", line 4732, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\core.py", line 555, in handle_stream
    msgs = await comm.read()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\tcp.py", line 218, in read
    msg = await from_frames(
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\utils.py", line 80, in from_frames
    res = _from_frames()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\utils.py", line 63, in _from_frames
    return protocol.loads(
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\protocol\core.py", line 104, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: 2917822586 exceeds max_bin_len(2147483647)
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x000001D8C9476940>, <Task finished name='Task-122' coro=<BaseTCPListener._handle_stream() done, defined at C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\tcp.py:476> exception=ValueError('2917822586 exceeds max_bin_len(2147483647)')>)
Traceback (most recent call last):
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\tornado\tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\tcp.py", line 493, in _handle_stream
    await self.comm_handler(comm)
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\core.py", line 501, in handle_comm
    result = await result
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\scheduler.py", line 4732, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\core.py", line 555, in handle_stream
    msgs = await comm.read()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\tcp.py", line 218, in read
    msg = await from_frames(
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\utils.py", line 80, in from_frames
    res = _from_frames()
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\comm\utils.py", line 63, in _from_frames
    return protocol.loads(
  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\protocol\core.py", line 104, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: 2917822586 exceeds max_bin_len(2147483647)
Traceback (most recent call last):

  File "<ipython-input-3-2760b83d53a5>", line 9, in <module>
    ddf.to_csv('output')

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\dask\dataframe\core.py", line 1465, in to_csv
    return to_csv(self, filename, **kwargs)

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\dask\dataframe\io\csv.py", line 864, in to_csv
    delayed(values).compute(**compute_kwargs)

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\dask\base.py", line 283, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\dask\base.py", line 565, in compute
    results = schedule(dsk, keys, **kwargs)

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\client.py", line 2665, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\client.py", line 1974, in gather
    return self.sync(

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\client.py", line 844, in sync
    return sync(

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\utils.py", line 353, in sync
    raise exc.with_traceback(tb)

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\utils.py", line 336, in f
    result[0] = yield future

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()

  File "C:\Users\--\Anaconda3\envs\work2\lib\site-packages\distributed\client.py", line 1840, in _gather
    raise exc

CancelledError: list-1db0b54c-c12d-4a3f-a18b-b39ea304e229
```
With 2021.4.1 and later versions the code simply hangs at some point and the ```output``` folder does not contain all of the 240 CSV files.

**Anything else we need to know?**:

I have reported similar issues as https://github.com/dask/dask/issues/7848 and #4990.

**Environment**:

- Dask version: works on 2021.3.0 but an error is reported; 2021.3.1 and 2021.4.0 the code crashes; >= 2021.4.1 the code hangs 
- Python version: 3.9.5
- Operating System: Windows Server 2016 64 bits
- Install method (conda, pip, source): conda

**Comment by bsesar** [comment]
@madsbk, could this be related to changes in #4531?

**Comment by fjetter** [comment]
FWIW the computation finishes for me without problems on latest, if I reduce the size of the pandas dataframe. Going for the full 80M rows the conversion from pandas to dask dataframe is extremely slow due to lack of memory on my end.

**Comment by jrbourbeau** [comment]
Thanks for reporting @bsesar! This looks like it might be a duplicate of https://github.com/dask/distributed/issues/4678, which has been fixed in more recent `dask` and `distributed` releases. Could you try updating `dask` and `distributed` to the latest release (`2021.7.0`) to see if the problem still persists?

**Comment by bsesar** [comment]
@fjetter, that's a great observation! :-) I have modified the above code to create Pandas DataFrames with a different number of rows and it seems the latest version of dask+distributed (@jrbourbeau, 2021.7.0) hangs when Pandas DataFrame has more than 28 million rows. I am using a machine with 256 GB of RAM so memory is not an issue.
