### ISSUE TITLE
distributed comp fails when working with matrixes: exception=ModuleNotFoundError("No module named 'scipy'")

### ISSUE THREAD

**Issue by niole** [dask/distributed#5081]
**What happened**:

Doing `dask.array.linalg.inv` fails when running in a distributed compute scenario. An exception is logged on the worker saying "cannot find module 'scipy'".

**What you expected to happen**:
I expect `scipy` to be installed by the `daskdev/dask:2021.7.0` image

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client
import dask.array as da
from datetime import datetime
import os

if __name__ == '__main__':
    service_port = os.environ['DASK_SCHEDULER_SERVICE_PORT']
    service_host = os.environ['DASK_SCHEDULER_SERVICE_HOST']
    client = Client(f'{service_host}:{service_port}')
    
    start = datetime.now()    
    #creating a 2000x2000 array whose values are normally distributed with zero mean and unit variance
    a = da.random.normal(0,1,size=(200, 200),chunks=(100,100))
    #computing the inverse of the array
    inv_a = da.linalg.inv(a).compute() # THIS LINE SEEMS TO NEED SCIPY
    print(inv_a)
    end = datetime.now()
    print(f'test passed {end-start}')

    client.shutdown()
```

**Anything else we need to know?**:
error logs from the worker:
```
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f753a44fb20>>, <Task finished name='Task-1174' coro=<Worker.handle_scheduler() done, defined at /opt/conda/lib/python3.8/site-packages/distributed/worker.py:1017> exception=ModuleNotFoundError("No module named 'scipy'")>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 1019, in handle_scheduler
    await self.handle_stream(
  File "/opt/conda/lib/python3.8/site-packages/distributed/core.py", line 557, in handle_stream
    msgs = await comm.read()
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/tcp.py", line 215, in read
    msg = await from_frames(
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/utils.py", line 79, in from_frames
    res = _from_frames()
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/utils.py", line 62, in _from_frames
    return protocol.loads(
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/core.py", line 105, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/core.py", line 97, in _decode_default
    return merge_and_deserialize(
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 472, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 390, in deserialize
    deserialize(
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 406, in deserialize
    return loads(header, frames)
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 85, in pickle_loads
    return pickle.loads(x, buffers=new)
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 75, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'scipy'
```

**Environment**:

- Dask version: `2021.7.0`
- Python version: `3.8`
- Operating System: 10.3 debian
- Install method (conda, pip, source): `daskdev/dask:2021.7.0` image

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @niole. The `ModuleNotFoundError: No module named 'scipy'` is expected as `scipy` is not included in the `daskdev/dask` image. For example, running

```
$ docker run -i daskdev/dask:2021.7.0 python -c "import scipy"
```

locally on my laptop outputs 

```
Unable to find image 'daskdev/dask:2021.7.0' locally
2021.7.0: Pulling from daskdev/dask
68ced04f60ab: Already exists
9c388eb6d33c: Already exists
96cf53b3a9dd: Already exists
60d0580df18e: Pull complete
cfc28ebaa261: Pull complete
7fcb79428599: Pull complete
Digest: sha256:0591b6784ce2b2bdc3c8a3fc161a2e28a6d1605f6c457f06bf8f5d36a9a8bbc8
Status: Downloaded newer image for daskdev/dask:2021.7.0
+ '[' '' ']'
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
+ '[' '' ']'
+ '[' '' ']'
+ exec python -c 'import scipy'
no environment.yml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
```

If you'd like to have `scipy` installed into the `daskdev/dask` image, I recommended using the `EXTRA_CONDA_PACKAGES` or `EXTRA_PIP_PACKAGES` environment variables (see https://docs.dask.org/en/latest/setup/docker.html#extensibility)

**Comment by niole** [comment]
@jrbourbeau Do you think it makes sense to add `scipy` to the daskdev image because it is a dependency for `dask.array.linalg`?

**Comment by jrbourbeau** [comment]
Looking at the conda-forge channel, `scipy` is ~20 MB large which would increase the `daskdev/dask` docker image by ~10%. I don't think we'd want to increase the image size that much for `scipy` since it's an optional dependency for a relatively small portion of Dask's full API. 

In general we try to keep the `daskdev/dask` image small since a wide variety of groups use them. Instead I'd recommend building your own docker image with the packages you need or using the `EXTRA_*_PACKAGES` extensibility environment variables which are baked into the `daskdev/dask` image

**Comment by niole** [comment]
i see. makes sense @jrbourbeau
