### ISSUE TITLE
Cycle detected in layout in Groups visualization 

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#5100]
I think that this is happening when the graph is empty

```python-traceback
[  287.943434] cloud-init[978]: bokeh.util.tornado - ERROR - Error thrown from periodic callback:
[  287.947840] cloud-init[978]: bokeh.util.tornado - ERROR - Traceback (most recent call last):
[  287.950235] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 526, in callback
[  287.951940] cloud-init[978]:     result_list.append(f.result())
[  287.952196] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
[  287.952648] cloud-init[978]:     result = func(self, *args, **kwargs)
[  287.952874] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/server/session.py", line 195, in with_document_locked
[  287.953102] cloud-init[978]:     return func(*args, **kwargs)
[  287.953806] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/document/document.py", line 1164, in wrapper
[  287.954100] cloud-init[978]:     return doc._with_self_as_curdoc(invoke)
[  287.954560] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/document/document.py", line 1150, in _with_self_as_curdoc
[  287.954759] cloud-init[978]:     return f()
[  287.955011] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/document/document.py", line 1163, in invoke
[  287.955233] cloud-init[978]:     return f(*args, **kwargs)
[  287.955472] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/distributed/dashboard/components/__init__.py", line 78, in <lambda>
[  287.955775] cloud-init[978]:     doc.add_periodic_callback(lambda: update(ref), interval)
[  287.955975] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/core/property/validation.py", line 93, in func
[  287.956194] cloud-init[978]:     return input_function(*args, **kwargs)
[  287.956458] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/distributed/dashboard/components/__init__.py", line 86, in update
[  287.956687] cloud-init[978]:     comp.update()
[  287.956941] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/core/property/validation.py", line 93, in func
[  287.957183] cloud-init[978]:     return input_function(*args, **kwargs)
[  287.957419] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 2038, in update
[  287.957916] cloud-init[978]:     self.nodes_layout, self.arrows_layout = self.update_layout()
[  287.958170] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/bokeh/core/property/validation.py", line 93, in func
[  287.958607] cloud-init[978]:     return input_function(*args, **kwargs)
[  287.958833] cloud-init[978]:   File "/opt/conda/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 1973, in update_layout
[  287.959293] cloud-init[978]:     order = dask.order.order(
[  287.959515] cloud-init[978]:   File "/dask/order.py", line 120, in order
[  287.959998] cloud-init[978]:     raise RuntimeError(
[  287.960259] cloud-init[978]: RuntimeError: Cycle detected between the following keys:
[  287.960473] cloud-init[978]:   ->
[  288.007375] cloud-init[978]: distributed.utils - ERROR - Cycle detected between the following keys:
```

cc @ncclementi

**Comment by ncclementi** [comment]
Where do you see this? to see if I can reproduce it locally. 

In the meantime: I see it's complaining when generating `order` in the `TaskGroupGraph` in particular the error raises  because of this https://github.com/dask/dask/blob/7772ee32352daf800561ac08fc05f4ba1546e88f/dask/order.py#L118

The question would be how to prevent to try to run update when the scheduler is empty, I see that we change the title that displays when there are no task groups here https://github.com/dask/distributed/blob/9975baa54b5d2079891e93f57ed8e0f402ef89d8/distributed/dashboard/components/scheduler.py#L2032-L2033

Would adding a return here do the job?

**Comment by mrocklin** [comment]
It was in a scheduler log of a long dead cluster unfortunately.

> Would adding a return here do the job?

Maybe?
