### ISSUE TITLE
pkg_resources.DistributionNotFound: heapdict

### ISSUE THREAD

**Issue by wsf1990** [dask/distributed#523]
I install distributed by 
```
pip install git+https://github.com/dask/{dask,distributed}.git --upgrade
pip install git+https://github.com/dask/s3fs --upgrade
```
but when I use to start work it show me this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/dask-worker", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: heapdict
```
How can I resolve this?

**Comment by mrocklin** [comment]
I'm surprised that `heapdict` would not have been installed.  Does `pip install heapdict` do anything?

**Comment by wsf1990** [comment]
sure,It work well! thanks!

**Comment by mrocklin** [comment]
You don't happen to have the logs of when you called pip install git+... the first time do you?  I'm concerned if this isn't installing heapdict by default.

**Comment by wsf1990** [comment]
I have 6 mechines to install dask.4 is well and 2 take this error.
