### ISSUE TITLE
test_fail_write_to_disk fails on 32-bit systems

### ISSUE THREAD

**Issue by QuLogic** [dask/distributed#5252]
**What happened**:

When [running tests on a 32-bit system](https://koji.fedoraproject.org/koji/taskinfo?taskID=74314301), `test_fail_write_to_disk` fails:

```
___________________________ test_fail_write_to_disk ____________________________
c = <Client: No scheduler connected>
s = <Scheduler: "tcp://127.0.0.1:33725" workers: 0 cores: 0, tasks: 0>
a = <Worker: 'tcp://127.0.0.1:39547', 0, Status.closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
b = <Worker: 'tcp://127.0.0.1:42475', 1, Status.closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>
    @gen_cluster(client=True)
    async def test_fail_write_to_disk(c, s, a, b):
        class Bad:
            def __getstate__(self):
                raise TypeError()
    
            def __sizeof__(self):
                return int(100e9)
    
        future = c.submit(Bad)
        await wait(future)
    
>       assert future.status == "error"
E       AssertionError: assert 'finished' == 'error'
E         - error
E         + finished
distributed/tests/test_worker.py:905: AssertionError
----------------------------- Captured stderr call -----------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:33725
distributed.scheduler - INFO -   dashboard at:           127.0.0.1:38449
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:39547
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:39547
distributed.worker - INFO -          dashboard at:            127.0.0.1:41927
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:33725
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                  14.64 GiB
distributed.worker - INFO -       Local Directory: /builddir/build/BUILD/distributed-2021.08.1/dask-worker-space/worker-1pquur4d
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:42475
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:42475
distributed.worker - INFO -          dashboard at:            127.0.0.1:43523
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:33725
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                  14.64 GiB
distributed.worker - INFO -       Local Directory: /builddir/build/BUILD/distributed-2021.08.1/dask-worker-space/worker-_cw23ys4
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://127.0.0.1:39547', name: 0, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:39547
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <WorkerState 'tcp://127.0.0.1:42475', name: 1, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:42475
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:33725
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:33725
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-65de15cc-0314-11ec-bb55-525400769539
distributed.core - INFO - Starting established connection
distributed.sizeof - WARNING - Sizeof calculation failed.  Defaulting to 1MB
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-2021.08.1/distributed/sizeof.py", line 14, in safe_sizeof
    return sizeof(obj)
  File "/usr/lib/python3.9/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/dask/sizeof.py", line 22, in sizeof_default
    return getsizeof(o)
OverflowError: Python int too large to convert to C ssize_t
distributed.sizeof - WARNING - Sizeof calculation failed.  Defaulting to 1MB
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-2021.08.1/distributed/sizeof.py", line 14, in safe_sizeof
    return sizeof(obj)
  File "/usr/lib/python3.9/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/dask/sizeof.py", line 22, in sizeof_default
    return getsizeof(o)
OverflowError: Python int too large to convert to C ssize_t
distributed.sizeof - WARNING - Sizeof calculation failed.  Defaulting to 1MB
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-2021.08.1/distributed/sizeof.py", line 14, in safe_sizeof
    return sizeof(obj)
  File "/usr/lib/python3.9/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/dask/sizeof.py", line 22, in sizeof_default
    return getsizeof(o)
OverflowError: Python int too large to convert to C ssize_t
distributed.scheduler - INFO - Remove client Client-65de15cc-0314-11ec-bb55-525400769539
distributed.scheduler - INFO - Remove client Client-65de15cc-0314-11ec-bb55-525400769539
distributed.scheduler - INFO - Close client connection: Client-65de15cc-0314-11ec-bb55-525400769539
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:39547
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:42475
distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://127.0.0.1:39547', name: 0, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://127.0.0.1:39547
distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://127.0.0.1:42475', name: 1, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://127.0.0.1:42475
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
```

It appears that the `__sizeof__` overflows, and Dask then picks a default size that is so small that it doesn't exercise the problem that the test is trying to trigger.

**What you expected to happen**:

Tests pass.

**Minimal Complete Verifiable Example**:

```python
$ pytest -m 'not avoid_ci and not slow and not asyncio' -vra
```

**Environment**:

- Dask version: 2021.8.1
- Python version: 3.9.6
- Operating System: Fedora 34
- Install method (conda, pip, source): sources

**Comment by QuLogic** [comment]
For Fedora, I've added a 
```
@pytest.mark.skipif(sys.maxsize <= 2**32, reason="Broken on 32-bit systems")                                                                                                                                                                                                                                
```
decorator for now.

**Comment by QuLogic** [comment]
I think this also affects `test_value_raises_during_spilling`:
```
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Captured stderr ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
distributed.sizeof - WARNING - Sizeof calculation failed. Defaulting to 0.95 MiB
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-2022.02.1/distributed/sizeof.py", line 15, in safe_sizeof
    return sizeof(obj)
  File "/usr/lib/python3.10/site-packages/dask/utils.py", line 605, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/dask/sizeof.py", line 22, in sizeof_default
    return getsizeof(o)
OverflowError: Python int too large to convert to C ssize_t
distributed.sizeof - WARNING - Sizeof calculation failed. Defaulting to 0.95 MiB
Traceback (most recent call last):
  File "/builddir/build/BUILD/distributed-2022.02.1/distributed/sizeof.py", line 15, in safe_sizeof
    return sizeof(obj)
  File "/usr/lib/python3.10/site-packages/dask/utils.py", line 605, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/dask/sizeof.py", line 22, in sizeof_default
    return getsizeof(o)
OverflowError: Python int too large to convert to C ssize_t
...
+ many other stacks
```

**Comment by bnavigator** [comment]
`test_ensure_spilled_immediately` and `test_fail_to_pickle_target_1` might also be related

**Comment by mrocklin** [comment]
@QuLogic sorry that you haven't gotten much response here.  I think that xfailing these tests make sense.  This functionality isn't critical for operation.  If you have any interest in submitting those xfail lines to the codebase I think that they would be happily merged.

My apologies again for the delay in response.
