### ISSUE TITLE
`to_parquet` with `uint64` index causes workers to die, local scheduler works fine

### ISSUE THREAD

**Issue by DahnJ** [dask/distributed#5400]
### MCVE
If I run

```python
import dask
from dask.distributed import Client, LocalCluster

cluster = LocalCluster()
client = Client(cluster)

df = dask.datasets.timeseries(end='2005-01-01', partition_freq='2W')
df = df.reset_index()
df.index = df.index.astype('uint')  # if I remove this line, everything runs fine
df.to_parquet('sample-timeseries-copied.parq')
```

After some time, workers start randomly dying and eventually the whole processing fails.

Behaviour I've noticed:
- Using a local scheduler, everything seems to run fine
- `to_csv(path, compression='gzip')` runs fine
- There seems to be increasing intensity of workers dying as the computation nears 100%. For small enough data, the intensity never gets big enough and the computation typically manages to finish, albeit with a couple of dead workers. 
- The same happens even with `threads_per_worker=1`

### Dashboard
Note: The dashboard gif is from the first version of my post, when I still thought my pipeline is at fault. Currently, I'm only running `read_parquet` and `to_parquet`, but seeing very similar behaviour.

![](https://i.imgur.com/MFg71yg.gif)

### Logs
It's not clear to me whether the logs contain any information about the nature of the problem. There are thousands of error messages, I sifted through them and found nothing pertaining to my code.

```python
distributed.worker - ERROR - failed during get data with tcp://127.0.0.1:37141 -> tcp://127.0.0.1:41371
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/tornado/iostream.py", line 867, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/root/miniconda3/lib/python3.9/site-packages/tornado/iostream.py", line 1140, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer
```

```python
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:35119
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/tornado/iostream.py", line 867, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/root/miniconda3/lib/python3.9/site-packages/tornado/iostream.py", line 1140, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer
```
```python
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 5192, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/core.py", line 575, in handle_stream
    handler(**merge(extra, msg))
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 4961, in client_releases_keys
    self.transitions(recommendations)
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 6975, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 5478, in send_all
    w = stream_comms[worker]
KeyError: None
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f706e73a700>, <Task finished name='Task-243' coro=<BaseTCPListener._handle_stream() done, defined at /root/miniconda3/lib/python3.9/site-packages/distributed/comm/tcp.py:478> exception=KeyError(None)>)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/root/miniconda3/lib/python3.9/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/comm/tcp.py", line 495, in _handle_stream
    await self.comm_handler(comm)
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 5192, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/core.py", line 575, in handle_stream
    handler(**merge(extra, msg))
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 4961, in client_releases_keys
    self.transitions(recommendations)
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 6975, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/root/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 5478, in send_all
    w = stream_comms[worker]
KeyError: None
```

```python
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py in to_parquet(self, path, *args, **kwargs)
   4538         from .io import to_parquet
   4539 
-> 4540         return to_parquet(self, path, *args, **kwargs)
   4541 
   4542     def to_orc(self, path, *args, **kwargs):

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py in to_parquet(df, path, engine, compression, write_index, append, overwrite, ignore_divisions, partition_on, storage_options, custom_metadata, write_metadata_file, compute, compute_kwargs, schema, **kwargs)
    723     if compute:
    724         if write_metadata_file:
--> 725             return compute_as_if_collection(
    726                 DataFrame, graph, (final_name, 0), **compute_kwargs
    727             )

~/miniconda3/lib/python3.9/site-packages/dask/base.py in compute_as_if_collection(cls, dsk, keys, scheduler, get, **kwargs)
    313     schedule = get_scheduler(scheduler=scheduler, cls=cls, get=get)
    314     dsk2 = optimization_function(cls)(dsk, keys, **kwargs)
--> 315     return schedule(dsk2, keys, **kwargs)
    316 
    317 

~/miniconda3/lib/python3.9/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2741                     should_rejoin = False
   2742             try:
-> 2743                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2744             finally:
   2745                 for f in futures.values():

~/miniconda3/lib/python3.9/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   2018             else:
   2019                 local_worker = None
-> 2020             return self.sync(
   2021                 self._gather,
   2022                 futures,

~/miniconda3/lib/python3.9/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    859             return future
    860         else:
--> 861             return sync(
    862                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    863             )

~/miniconda3/lib/python3.9/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    324     if error[0]:
    325         typ, exc, tb = error[0]
--> 326         raise exc.with_traceback(tb)
    327     else:
    328         return result[0]

~/miniconda3/lib/python3.9/site-packages/distributed/utils.py in f()
    307             if callback_timeout is not None:
    308                 future = asyncio.wait_for(future, callback_timeout)
--> 309             result[0] = yield future
    310         except Exception:
    311             error[0] = sys.exc_info()

~/miniconda3/lib/python3.9/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

~/miniconda3/lib/python3.9/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1883                             exc = CancelledError(key)
   1884                         else:
-> 1885                             raise exception.with_traceback(traceback)
   1886                         raise exc
   1887                     if errors == "skip":

KilledWorker: ("('loc-series-284203bddf3db6b69e723fac62af9853', 559)", <WorkerState 'tcp://127.0.0.1:43397', name: 3, memory: 0, processing: 29>)
```

### Environment
- Dask version: `2021.09.01`, tried also `2021.07.01`
- PyArrow version: `4.0.1`
- Python version: `3.9`
- Operating System: `Linux version 5.4.0-81-generic (buildd@lgw01-amd64-052) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))` 
- Install method (conda, pip, source): `conda`

**Comment by DahnJ** [comment]
I have manged to further isolate the behaviour and edited the issue. I do not know if it solves my original problem (I will try latest on Monday), but at least this way we have a MCVE.

**Comment by DahnJ** [comment]
I have updated to PyArrow `5.0.0` and this no longer seems to happen, closing the issue.

Thanks to @fjetter for helping me realize where the problem could be.
