### ISSUE TITLE
possible to call concurrent.futures.wait on a Future returned by distributed.Executor.submit?

### ISSUE THREAD

**Issue by timodonnell** [dask/distributed#548]
I have somes futures from calling `distributed.Executor.submit`. Is it possible to call Python's `concurrent.futures.wait` function on those?

This is currently what I get when doing this using latest master `distributed`:

```
Traceback (most recent call last):
  File "/Users/tim/miniconda3/envs/py3k/bin/mhcflurry-class1-allele-specific-cv-and-train", line 9, in <module>
    load_entry_point('mhcflurry', 'console_scripts', 'mhcflurry-class1-allele-specific-cv-and-train')()
  File "/Users/tim/sinai/git/mhcflurry/mhcflurry/class1_allele_specific/cv_and_train_command.py", line 175, in run
    go(args)
  File "/Users/tim/sinai/git/mhcflurry/mhcflurry/class1_allele_specific/cv_and_train_command.py", line 232, in go
    alleles=args.alleles)
  File "/Users/tim/sinai/git/mhcflurry/mhcflurry/class1_allele_specific/cross_validation.py", line 194, in cross_validation_folds
    timeout=10)
  File "/Users/tim/miniconda3/envs/py3k/lib/python3.5/concurrent/futures/_base.py", line 257, in wait
    with _AcquireFutures(fs):
  File "/Users/tim/miniconda3/envs/py3k/lib/python3.5/concurrent/futures/_base.py", line 146, in __enter__
    future._condition.acquire()
AttributeError: 'Future' object has no attribute '_condition'
```

**Comment by mrocklin** [comment]
No, but there is a `distributed.wait` function that is API compatible.  Same with as_completed, wait's cousin.

**Comment by timodonnell** [comment]
Got it, thanks
