### ISSUE TITLE
distributed.utils - ERROR - 'op'

### ISSUE THREAD

**Issue by wsf1990** [dask/distributed#549]
When I use
```
from distributed import Executor, progress, wait ,hdfs
e = Executor('geonode3:8786')
e
```
it shown me this error:
```
distributed.utils - ERROR - 'op'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/distributed/utils.py", line 103, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.4/dist-packages/distributed/client.py", line 350, in _start
    yield self.ensure_connected()
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.4/dist-packages/distributed/client.py", line 390, in ensure_connected
    assert msg[0]['op'] == 'stream-start'
KeyError: 'op'
```
My python version is 3.4.how to resolve this? Thanks!

**Comment by mrocklin** [comment]
Can you verify that your workers, scheduler, and client all share the same version of Python

**Comment by wsf1990** [comment]
maybe caused by that.I have 2 and 3 on some client.and just have 2 in some other.So maybe caused by this. thanks!
