### ISSUE TITLE
TypeError when serializing tuples of dataclasses

### ISSUE THREAD

**Issue by orf** [dask/distributed#5495]
**What happened**:

Returning a value of `([dataclass],)` from a task results in a `TypeError` as `__init__` is apparently called.

**What you expected to happen**:

It to not error.

**Minimal Complete Verifiable Example**:

```python
import dask.distributed
import dataclasses

@dataclasses.dataclass()
class Foo:
    x: int

def main():
    return [Foo(x=1)],

def entrypoint():
    client = dask.distributed.get_client()
    results = main()
    return client.compute(results, sync=True)

if __name__ == '__main__':
    from distributed import Client
    with Client() as client:
        client.submit(entrypoint).result()
```

Results in:

```
distributed.worker - WARNING - Compute Failed
Function:  execute_task
args:      ([(<function apply at 0x1081b6040>, <class '__main__.Foo'>, (), (<class 'dict'>, []))])
kwargs:    {}
Exception: 'TypeError("__init__() missing 1 required positional argument: \'x\'")'

distributed.worker - WARNING - Compute Failed
Function:  entrypoint
args:      ()
kwargs:    {}
Exception: 'TypeError("__init__() missing 1 required positional argument: \'x\'")'

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    results, = client.submit(entrypoint).result()
  File "/Users/foo/lib/python3.8/site-packages/distributed/client.py", line 233, in result
    raise exc.with_traceback(tb)
  File "test.py", line 17, in entrypoint
    return client.compute(results, sync=True)
  File "/Users/foo/lib/python3.8/site-packages/distributed/client.py", line 2898, in compute
    result = self.gather(futures)
  File "/Users/foo/lib/python3.8/site-packages/distributed/client.py", line 1969, in gather
    return self.sync(
  File "/Users/foo/lib/python3.8/site-packages/distributed/client.py", line 865, in sync
    return sync(
  File "/Users/foo/lib/python3.8/site-packages/distributed/utils.py", line 327, in sync
    raise exc.with_traceback(tb)
  File "/Users/foo/lib/python3.8/site-packages/distributed/utils.py", line 310, in f
    result[0] = yield future
  File "/Users/foo/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/foo/lib/python3.8/site-packages/distributed/client.py", line 1834, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/foo/lib/python3.8/site-packages/dask/utils.py", line 37, in apply
    return func(*args)
TypeError: __init__() missing 1 required positional argument: 'x'
```

**Anything else we need to know?**:

Returning a plain list works fine.

**Environment**:

- Dask version: 2021.10.0
- Python version: 3.8.12
- Operating System: MacOS, also happens in distributed gateway clusters running Linux
- Install method (conda, pip, source): Pip via Poetry

**Comment by orf** [comment]
This actually surfaces as an absolutely horrible bug. The following code throws an AssertionError, because the dataclass is freshly initalized after the call to `.compute` 😱 

```python
import dask.distributed
import dataclasses

@dataclasses.dataclass()
class Foo:
    a_list: list = dataclasses.field(default_factory=list)

def main():
    bar = Foo()
    bar.a_list.append(123)
    return [bar],

def entrypoint():
    client = dask.distributed.get_client()
    results = main()
    return client.compute(results, sync=True)

if __name__ == '__main__':
    with dask.distributed.Client() as client:
        results, = client.submit(entrypoint).result()
        assert results[0].a_list
```

Could maybe be related to https://github.com/dask/dask/issues/6574#issuecomment-943411814?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue with nice minimal reproducers. My first thought was https://github.com/dask/dask/issues/6574#issuecomment-943411814 is related too. What happens when you add `traverse=False` to your `client.compute` calls?

**Comment by orf** [comment]
It works as expected with `traverse=False` as well as `.gather()`. The snippets above are obviously convoluted reproduction code, and the code they represent doesn't know if the user is returning a collection of dask results that we need to traverse or not.
