### ISSUE TITLE
ValueError: bytes object is too large

### ISSUE THREAD

**Issue by YashPhogat** [dask/distributed#5498]
### Description
I've been getting a "ValueError: bytes object is too large" error while using prefect flow with dask on a dataframe of 4.01GB . How can I fix it?

### Reproducible Example
```python
#!/usr/bin/env python3

import os
import sys
import re
import pandas as pd
import numpy as np
import pickle

import logging

import dask
from dask.distributed import Client
from dask_jobqueue import LSFCluster
import distributed
import warnings

import prefect
from prefect import task, Flow, Parameter
from prefect.tasks.core.function import FunctionTask
from prefect.executors import DaskExecutor
from prefect.engine.flow_runner import FlowRunner

@task
def dump_pickle(obj, filename) -> None:
    """Task to pick an object and dump it to a file
    :param obj: object to pickle
    :param filename: location to dump pickled object
    """
    with open(filename, "wb") as fh:
        pickle.dump(obj, fh)

@task
def dump_csv(tr_data):
    dump_pickle(tr_data, "training_data.pkl")
    return True


def start_cluster():
    """
    Function to launch the workflow on the dask cluster.
    """
    log_path = os.getcwd()
    if not os.path.exists(log_path):
        os.mkdir(log_path) 

    with warnings.catch_warnings(record=True):
        cluster = LSFCluster(
            queue='PD',
            walltime=10000,
            cores=1,
            mem=80*1024*1024*1024,
            memory='80GB',
            lsf_units="k",
            log_directory=log_path,
            local_directory="$TMPDIR",
        )

    cluster.adapt(minimum=1, maximum=16)
    client = Client(cluster)
    return client


def main(args):
    
    flow_args = dict()
    if True:
        logging.info("Dask backend enabled for training. To be used only for local environment.")
        client = start_cluster()
        address = client.scheduler_info()['address']
        result = re.match('tcp://(.*):', address)
        dashboard_port = client.scheduler_info()['services']['dashboard']
        if result is not None:
            dashboard = "http://{0}:{1}".format(result.group(1), dashboard_port)
            print("Dask cluster started. Dashboard at {0}".format(dashboard))
            sys.stdout.flush()
        else:
            raise UserWarning("Warning - could not locate dashboard service.")
        executor = DaskExecutor(client.scheduler_info()['address'], debug=True)
        flow_args['executor'] = executor
        

    with Flow("flow") as flow:
        
        intmat = pd.DataFrame(np.random.randint(0,100,size=(650000, 3)))
        floatmat = pd.DataFrame(np.random.randint(0,100,size=(650000, 799)).astype(np.float64))
        strmat = pd.DataFrame(np.random.randint(0,100,size=(650000, 92)).astype(object))
        tr_data = pd.concat((intmat, floatmat, strmat), axis=1)
        tr_data.columns = range(len(tr_data.columns))
        tr_data["fail"] = np.random.choice(a=[0, 1], size=(650000, 1), p=[0.5, 0.5])
        tr_data["date"] = np.random.choice(pd.date_range('2021-10-01', '2021-10-20'), len(tr_data))
        tr_data.reset_index(inplace=True)
        tr_data = tr_data.rename(columns = {'index':'ID'})

        print("Writing to CSV....")

        WriteDone = dump_csv(tr_data)
          
    runner = FlowRunner(flow)
    with prefect.context():
        result = runner.run(return_tasks=[WriteDone], **flow_args)


if __name__=='__main__':
    main(sys.argv[1:])

```

### Output
```
Dask cluster started. Dashboard at http://10.120.58.62:8787

Writing to CSV....

[2021-11-04 15:59:23-0500] INFO - prefect.FlowRunner | Beginning Flow run for 'flow'
INFO:prefect.FlowRunner:Beginning Flow run for 'flow'

[2021-11-04 15:59:23-0500] INFO - prefect.DaskExecutor | Connecting to an existing Dask cluster at tcp://10.120.58.62:44622
INFO:prefect.DaskExecutor: Connecting to an existing Dask cluster at tcp://10.120.58.62:44622

/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/worker.py:3862: UserWarning: Large object of size 4.01 GiB detected in task graph: 

{'task': <Task: dump_csv>, 'state': None, 'upstrea ... ed_states': {}}
Consider scattering large objects ahead of time with client.scatter to reduce scheduler burden and keep data on workers

    future = client.submit(func, big_data)    # bad
    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good

warnings.warn(distributed.protocol.core - CRITICAL - Failed to Serialize

Traceback (most recent call last):
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/protocol/core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  [Previous line repeated 1 more time]
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large

distributed.comm.utils - ERROR - bytes object is too large
Traceback (most recent call last):
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/utils.py", line 33, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/protocol/core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  [Previous line repeated 1 more time]
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large
distributed.batched - ERROR - Error in batched write

Traceback (most recent call last):
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/tcp.py", line 243, in write
    frames = await to_frames(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/utils.py", line 48, in to_frames
    return await offload(_to_frames)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/utils.py", line 1325, in offload
    return await loop.run_in_executor(_offload_executor, lambda: fn(*args, **kwargs))
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/utils.py", line 1325, in <lambda>
    return await loop.run_in_executor(_offload_executor, lambda: fn(*args, **kwargs))
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/utils.py", line 33, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/protocol/core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  [Previous line repeated 1 more time]
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large

[2021-11-04 16:00:50-0500] ERROR - prefect.FlowRunner | Unexpected error: CancelledError('dump_csv-c951cf9564d3433a835778d9f6ed7988')
Traceback (most recent call last):
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 643, in get_flow_run_state
    final_states = executor.wait(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/prefect/executors/dask.py", line 424, in wait
    return self.client.gather(futures)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/client.py", line 1948, in gather
    return self.sync(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/client.py", line 845, in sync
    return sync(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/client.py", line 1814, in _gather
    raise exc
concurrent.futures._base.CancelledError: dump_csv-c951cf9564d3433a835778d9f6ed7988
ERROR:prefect.FlowRunner:Unexpected error: CancelledError('dump_csv-c951cf9564d3433a835778d9f6ed7988')
Traceback (most recent call last):
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 643, in get_flow_run_state
    final_states = executor.wait(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/prefect/executors/dask.py", line 424, in wait
    return self.client.gather(futures)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/client.py", line 1948, in gather
    return self.sync(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/client.py", line 845, in sync
    return sync(
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/client.py", line 1814, in _gather
    raise exc
concurrent.futures._base.CancelledError: dump_csv-c951cf9564d3433a835778d9f6ed7988
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f0230439040>, <Task finished name='Task-354' coro=<BaseTCPListener._handle_stream() done, defined at /arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/tcp.py:493> exception=ValueError('invalid operation on non-started TCPListener')>)
Traceback (most recent call last):
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/tcp.py", line 499, in _handle_stream
    logger.debug("Incoming connection from %r to %r", address, self.contact_address)
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/tcp.py", line 535, in contact_address
    host, port = self.get_host_port()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/tcp.py", line 516, in get_host_port
    self._check_started()
  File "/arm/tools/ceme/conda_py3.9/1.4.0/linux64/envs/dory/lib/python3.9/site-packages/distributed/comm/tcp.py", line 491, in _check_started
    raise ValueError("invalid operation on non-started TCPListener")
ValueError: invalid operation on non-started TCPListener
```

### Tools Versions

python: 3.9.7.final.0
dask: 2021.08.1
distributed: 2021.08.1
msgpack: 1.0.2

**Comment by jrbourbeau** [comment]
Just checking in here, @YashPhogat does @gjoseph92's suggestion https://github.com/dask/distributed/issues/5498#issuecomment-962172751 help resolve the serialization error you're seeing?

**Comment by YashPhogat** [comment]
Hi @jrbourbeau 

Thanks to @gjoseph92 recommendation. The issue was resolved.
