### ISSUE TITLE
intermittent `OSError: [Errno 98] Address already in use` in bind_sockets(0) 

### ISSUE THREAD

**Issue by graingert** [dask/distributed#5804]
```
___________________________ test_expect_ssl_context ____________________________

args = (), kwargs = {}
loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x7f2ee4328ed0>
injected_func = functools.partial(<function test_expect_ssl_context at 0x7f2ef864de60>)
cor = functools.partial(<function test_expect_ssl_context at 0x7f2ef864de60>)

    def test_func(*args, **kwargs):
        with clean() as loop:
            injected_func = functools.partial(func, *args, **kwargs)
            if iscoroutinefunction(func):
                cor = injected_func
            else:
                cor = gen.coroutine(injected_func)
    
>           loop.run_sync(cor, timeout=timeout)

distributed/utils_test.py:808: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/ioloop.py:576: in run_sync
    return future_cell[0].result()
distributed/comm/tests/test_ws.py:71: in test_expect_ssl_context
    async with listen("wss://", lambda comm: comm, ssl_context=server_ctx) as listener:
distributed/comm/core.py:202: in __aenter__
    await self.start()
distributed/comm/ws.py:338: in start
    self.server.listen(self.port)
/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/tcpserver.py:143: in listen
    sockets = bind_sockets(port, address=address)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

port = 0, address = None, family = <AddressFamily.AF_UNSPEC: 0>, backlog = 128
flags = <AddressInfo.AI_PASSIVE: 1>, reuse_port = False

    def bind_sockets(port, address=None, family=socket.AF_UNSPEC,
                     backlog=_DEFAULT_BACKLOG, flags=None, reuse_port=False):
        """Creates listening sockets bound to the given port and address.
    
        Returns a list of socket objects (multiple sockets are returned if
        the given address maps to multiple IP addresses, which is most common
        for mixed IPv4 and IPv6 use).
    
        Address may be either an IP address or hostname.  If it's a hostname,
        the server will listen on all IP addresses associated with the
        name.  Address may be an empty string or None to listen on all
        available interfaces.  Family may be set to either `socket.AF_INET`
        or `socket.AF_INET6` to restrict to IPv4 or IPv6 addresses, otherwise
        both will be used if available.
    
        The ``backlog`` argument has the same meaning as for
        `socket.listen() <socket.socket.listen>`.
    
        ``flags`` is a bitmask of AI_* flags to `~socket.getaddrinfo`, like
        ``socket.AI_PASSIVE | socket.AI_NUMERICHOST``.
    
        ``reuse_port`` option sets ``SO_REUSEPORT`` option for every socket
        in the list. If your platform doesn't support this option ValueError will
        be raised.
        """
        if reuse_port and not hasattr(socket, "SO_REUSEPORT"):
            raise ValueError("the platform doesn't support SO_REUSEPORT")
    
        sockets = []
        if address == "":
            address = None
        if not socket.has_ipv6 and family == socket.AF_UNSPEC:
            # Python can be compiled with --disable-ipv6, which causes
            # operations on AF_INET6 sockets to fail, but does not
            # automatically exclude those results from getaddrinfo
            # results.
            # http://bugs.python.org/issue16208
            family = socket.AF_INET
        if flags is None:
            flags = socket.AI_PASSIVE
        bound_port = None
        for res in set(socket.getaddrinfo(address, port, family, socket.SOCK_STREAM,
                                          0, flags)):
            af, socktype, proto, canonname, sockaddr = res
            if (sys.platform == 'darwin' and address == 'localhost' and
                    af == socket.AF_INET6 and sockaddr[3] != 0):
                # Mac OS X includes a link-local address fe80::1%lo0 in the
                # getaddrinfo results for 'localhost'.  However, the firewall
                # doesn't understand that this is a local address and will
                # prompt for access (often repeatedly, due to an apparent
                # bug in its ability to remember granting access to an
                # application). Skip these addresses.
                continue
            try:
                sock = socket.socket(af, socktype, proto)
            except socket.error as e:
                if errno_from_exception(e) == errno.EAFNOSUPPORT:
                    continue
                raise
            set_close_exec(sock.fileno())
            if os.name != 'nt':
                try:
                    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                except socket.error as e:
                    if errno_from_exception(e) != errno.ENOPROTOOPT:
                        # Hurd doesn't support SO_REUSEADDR.
                        raise
            if reuse_port:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
            if af == socket.AF_INET6:
                # On linux, ipv6 sockets accept ipv4 too by default,
                # but this makes it impossible to bind to both
                # 0.0.0.0 in ipv4 and :: in ipv6.  On other systems,
                # separate sockets *must* be used to listen for both ipv4
                # and ipv6.  For consistency, always disable ipv4 on our
                # ipv6 sockets and use a separate ipv4 socket when needed.
                #
                # Python 2.x on windows doesn't have IPPROTO_IPV6.
                if hasattr(socket, "IPPROTO_IPV6"):
                    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
    
            # automatic port allocation with port=None
            # should bind on the same port on IPv4 and IPv6
            host, requested_port = sockaddr[:2]
            if requested_port == 0 and bound_port is not None:
                sockaddr = tuple([host, bound_port] + list(sockaddr[2:]))
    
            sock.setblocking(0)
>           sock.bind(sockaddr)
E           OSError: [Errno 98] Address already in use

/usr/share/miniconda3/envs/dask-distributed/lib/python3.7/site-packages/tornado/netutil.py:168: OSError
```

only on python3.7 - should be fixed with https://github.com/tornadoweb/tornado/issues/1860

**Comment by etejedor** [comment]
Not sure whether it's triggered under the same circumstances, but I also observe this error.

I see it when using an 1HTCondorCluster1, and it looks like it's related to the teardown of the workers. It's an intermittent error: sometimes, I see the following error in the worker logs:
```
distributed.worker - INFO - Stopping worker at tcp://188.185.105.127:10000
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://188.185.105.127:60558 remote=tcp://swan006.cern.ch:5277>
Traceback (most recent call last):
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/distributed/batched.py", line 94, in _background_send
    nbytes = yield self.comm.write(
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.worker - WARNING - Heartbeat to scheduler failed
Traceback (most recent call last):
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/distributed/comm/tcp.py", line 205, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed
```

When that error appears on the worker side, I also see the following one on the cluster side:
```
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f312993bb80>, <Task finished name='Task-334' coro=<BaseTCPListener._handle_stream() done, defined at /eos/user/e/etejedor/htcondor/packages/distributed/comm/tcp.py:533> exception=OSError(98, 'Address already in use')>)
Traceback (most recent call last):
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/eos/user/e/etejedor/htcondor/packages/distributed/comm/tcp.py", line 550, in _handle_stream
    await self.comm_handler(comm)
  File "/eos/user/e/etejedor/htcondor/packages/distributed/core.py", line 452, in handle_comm
    await self
  File "/eos/user/e/etejedor/htcondor/packages/distributed/core.py", line 279, in _
    await self.start()
  File "/eos/user/e/etejedor/htcondor/packages/distributed/scheduler.py", line 4089, in start
    await self.listen(
  File "/eos/user/e/etejedor/htcondor/packages/distributed/core.py", line 424, in listen
    listener = await listen(
  File "/eos/user/e/etejedor/htcondor/packages/distributed/comm/core.py", line 212, in _
    await self.start()
  File "/eos/user/e/etejedor/htcondor/packages/distributed/comm/tcp.py", line 508, in start
    sockets = netutil.bind_sockets(
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/devswan/Thu/x86_64-centos7-gcc8-opt/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

Even when I get the errors above, the result of my application seems correct (I can retrieve the value of a future correctly). I either see both errors (client and worker side) or I see none. To me it looks like some miscoordination / lack of proper synchronization between the client / scheduler and the workers.
