### ISSUE TITLE
Handshake timeout error on SGE cluster

### ISSUE THREAD

**Issue by TomMaullin** [dask/distributed#5844]
```
from dask import config
from dask_jobqueue import SGECluster
from dask.distributed import Client, as_completed
import blm_setup, blm_batch, blm_concat, blm_cleanup # my own functions which don't employ dask

# Given a dask distributed client run BLM.
def main(cluster, client):

    # Some generic inputs
    inputs= ... # Function inputs

    # Ask for a node for setup
    cluster.scale(1)

    # Setup does some computation to work out how many jobs to submit
    future_0 = client.submit(blm_setup, inputs, pure=False)
    nb = future_0.result()

    # Ask for 100 workers for next stage of computatiojn
    cluster.scale(100)

    # Empty futures list
    futures = []

    # Run jobs
    for b in (np.arange(nb)+1):

        # Individual job
        future_b = client.submit(blm_batch, b, inputs, pure=False)
        
        # Append to list
        futures.append(future_b)

    # Completed jobs
    completed = as_completed(futures)

    # Wait for results
    for future_b in completed:
        future_b.result()

    # Ask for 1 node for final stage
    cluster.scale(1)

    # Concatenation job
    future_concat = client.submit(blm_concat, inputs, pure=False)

    # Run concatenation job
    future_concat.result()

    # Run cleanup job
    future_cleanup = client.submit(blm_cleanup, inputs_yml, pure=False)

    # Run cleanup job
    future_cleanup.result()

# If running this function
if __name__ == "__main__":

    # Specify cluster setup
    cluster = SGECluster(cores=1,
                         memory="100GB",
                         queue='short.qc',
                         walltime='00:30:00',
                         extra=['--no-dashboard'],
                         interface="ib0",
                         local_directory='FILEPATH') # I have removed the filepath from the original code here. 

    # Connect to cluster
    client = Client(cluster)   

    # Run code
    main(cluster, client)

    # Close the client
    client.close()

```
(Source: [https://github.com/TomMaullin/BLM/tree/dask_update](https://github.com/TomMaullin/BLM/tree/dask_update))

**What happened**: I ran the above code (with the `FILEPATH` replaced appropriately) on the head node of an SGE cluster using `python blm_cluster.py &` (where `blm_cluster` contains the above code). First, it gave me 1 worker and the setup computation seemed to run correctly, then it gave me 100 workers and they seemed to run correctly. Finally it went back down to 1 worker. However, at this stage this error appeared in the log for the one remaining worker:

```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.128.10.26:38442'
distributed.worker - INFO -	  Start worker at:   tcp://10.128.10.26:34295
distributed.worker - INFO -          Listening to:   tcp://10.128.10.26:34295
distributed.worker - INFO -          dashboard at:         10.128.10.26:38150
distributed.worker - INFO - Waiting to connect to:   tcp://10.128.1.241:34386
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                  93.13 GiB
distributed.worker - INFO -	  Local Directory: /well/nichols/users/inf852/BLMdask/dask-worker-space/worker-b_q5vip7
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://10.128.1.241:34386
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b87ac5f4450>>, <Task finished coro=$
Traceback (most recent call last):
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/comm/core.py", line 326, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/worker.py", line 1370, in heartbeat
    raise e
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/worker.py", line 1336, in heartbeat
    for key in self.active_keys
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/core.py", line 902, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/core.py", line 1072, in connect
    comm = await fut
  File "/users/nichols/inf852/miniconda3/envs/BLM/lib/python3.7/site-packages/distributed/comm/core.py", line 333, in connect
    ) from exc
OSError: Timed out during handshake while connecting to tcp://10.128.1.241:34386 after 30 s

```

From this point onwards the final worker doesn't seem to terminate or be doing anything. It says it is running when I do `qstat` but it doesn't seem to be doing anything. 

**What you expected to happen**: I expected the first worker to run my `blm_setup` code. Then 100 workers to run my `blm_batch` code. Then finally one worker should run my `blm_concat` code which combines files created by the `blm_batch` code. 

**Minimal Complete Verifiable Example**: I'm not sure how to reduce the above any further.

**Environment**:

- Dask version: `dask==2022.2.0`, `dask-jobqueue==0.7.3`
- Python version:  3.7.11
- Operating System: CentOS Linux 7
- Install method (conda, pip, source): pip inside a conda environement

**Comment by desh2608** [comment]
I am facing the same problems. Also, it only occurs on some nodes (~50%) of my cluster, and others seem to be working fine. I can submit jobs fine with `qsub` to these same nodes so I know it is not a network issue.

**Comment by jakirkham** [comment]
It's hard to say what the issue might be from this

Sometimes there are restrictions in an institutions' clusters. For example some ports might be disallowed. There could be constraints placed on processes themselves

Given this is around using Dask-Jobqueue and SGE, thinking there might be better advice from folks on that repo/issue tracker, so going to move this over there
