### ISSUE TITLE
connecting to a closed cluster should fail fast

### ISSUE THREAD

**Issue by dchudz** [dask/distributed#5853]
I was recently debugging a bug I wrote in a `Cluster` subclass that led my clusters to close when they shouldn't.

Part of what made debugging hard was the cluster being closed didn't seem to have any effect on the dask Client (or anything else from distributed) trying to use it. 

I think it might be nicer if trying to connect to a closed cluster resulted in an immediate error.

My situation wasn't a LocalCluster, but here's a demonstation of what I mean with a LocalCluster:

<details>
<summary>example</summary>

```python

In [1]: from dask.distributed import Client, LocalCluster

In [2]: cluster = LocalCluster()
client1
In [3]: client1 = Client(cluster)

In [4]: client1.run(lambda: None)
Out[4]:
{'tcp://127.0.0.1:55739': None,
 'tcp://127.0.0.1:55740': None,
 'tcp://127.0.0.1:55745': None,
 'tcp://127.0.0.1:55748': None}

In [5]: cluster.close()

In [6]: client1.run(lambda: None)
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py:1072, in ConnectionPool.connect(self, addr, timeout)
   1071 self._connecting.add(fut)
-> 1072 comm = await fut
   1073 comm.name = "ConnectionPool"

CancelledError:

The above exception was the direct cause of the following exception:

CommClosedError                           Traceback (most recent call last)
Input In [6], in <module>
----> 1 client1.run(lambda: None)

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/client.py:2752, in Client.run(self, function, workers, wait, nanny, on_error, *args, **kwargs)
   2669 def run(
   2670     self,
   2671     function,
   (...)
   2677     **kwargs,
   2678 ):
   2679     """
   2680     Run a function on all workers outside of task scheduling system
   2681
   (...)
   2750     >>> c.run(print_state, wait=False)  # doctest: +SKIP
   2751     """
-> 2752     return self.sync(
   2753         self._run,
   2754         function,
   2755         *args,
   2756         workers=workers,
   2757         wait=wait,
   2758         nanny=nanny,
   2759         on_error=on_error,
   2760         **kwargs,
   2761     )

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py:309, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    307     return future
    308 else:
--> 309     return sync(
    310         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    311     )

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py:376, in sync(loop, func, callback_timeout, *args, **kwargs)
    374 if error:
    375     typ, exc, tb = error
--> 376     raise exc.with_traceback(tb)
    377 else:
    378     return result

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py:349, in sync.<locals>.f()
    347         future = asyncio.wait_for(future, callback_timeout)
    348     future = asyncio.ensure_future(future)
--> 349     result = yield future
    350 except Exception:
    351     error = sys.exc_info()

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/tornado/gen.py:762, in Runner.run(self)
    759 exc_info = None
    761 try:
--> 762     value = future.result()
    763 except Exception:
    764     exc_info = sys.exc_info()

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/client.py:2629, in Client._run(self, function, nanny, workers, wait, on_error, *args, **kwargs)
   2619 async def _run(
   2620     self,
   2621     function,
   (...)
   2627     **kwargs,
   2628 ):
-> 2629     responses = await self.scheduler.broadcast(
   2630         msg=dict(
   2631             op="run",
   2632             function=dumps(function, protocol=4),
   2633             args=dumps(args, protocol=4),
   2634             wait=wait,
   2635             kwargs=dumps(kwargs, protocol=4),
   2636         ),
   2637         workers=workers,
   2638         nanny=nanny,
   2639         on_error="return_pickle",
   2640     )
   2641     results = {}
   2642     for key, resp in responses.items():

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py:902, in PooledRPCCall.__getattr__.<locals>.send_recv_from_rpc(**kwargs)
    900 if self.deserializers is not None and kwargs.get("deserializers") is None:
    901     kwargs["deserializers"] = self.deserializers
--> 902 comm = await self.pool.connect(self.addr)
    903 prev_name, comm.name = comm.name, "ConnectionPool." + key
    904 try:

File ~/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py:1083, in ConnectionPool.connect(self, addr, timeout)
   1081 except asyncio.CancelledError as exc:
   1082     self.semaphore.release()
-> 1083     raise CommClosedError(
   1084         f"ConnectionPool not running. Status: {self.status}"
   1085     ) from exc
   1086 except Exception:
   1087     self.semaphore.release()

CommClosedError: ConnectionPool not running. Status: Status.closed

In [7]: client2 = Client(cluster)

ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/core.py", line 289, in connect
    comm = await asyncio.wait_for(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/tcp.py", line 438, in connect
    convert_stream_closed_error(self, e)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/tcp.py", line 127, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x7fd772068f10>: ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-46663b7c74a0>", line 1, in <module>
    client2 = Client(cluster)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/client.py", line 923, in __init__
    self.start(timeout=timeout)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/client.py", line 1081, in start
    sync(self.loop, self._start, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 376, in sync
    raise exc.with_traceback(tb)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 349, in f
    result = yield future
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/client.py", line 1173, in _start
    await self._ensure_connected(timeout=timeout)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/client.py", line 1232, in _ensure_connected
    comm = await connect(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/core.py", line 315, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://127.0.0.1:55722 after 30 s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/__init__.py", line 123, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 316, in start
    self.shell.mainloop()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 611, in mainloop
    self.interact()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 604, in interact
    self.run_cell(code, store_history=True)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/IPython/core/ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

If you suspect this is an IPython 8.0.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

</details>

It would have been nice if `client2 = Client(cluster)` returned immediately with an error about the cluster being closed, rather than waiting for awhile before giving me `Connection refused`.

(It would also be nicer if the error didn't crash my ipython session, but that seems like a different issue.)

```
distributed                    2022.2.0
```

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/distributed/pull/5855
