### ISSUE TITLE
`dask-scheduler` requires internet to run?

### ISSUE THREAD

**Issue by dchudz** [dask/distributed#5858]
I'd like to be able to run `dask-scheduler` while not connected to the internet, but if I disconnect my computer and then try it, I get this:

```
dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py:135: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to hostname: [Errno 51] Network is unreachable
...
```

`distributed                    2022.2.0`

<details>
<summary>Full error with some tracebacks:
</summary>
<pre>
dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py:135: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to hostname: [Errno 51] Network is unreachable
  warnings.warn(
Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 131, in _get_ip
    sock.connect((host, port))
OSError: [Errno 51] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 208, in main
    loop.run_sync(run)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 204, in run
    await scheduler
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 279, in _
    await self.start()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/scheduler.py", line 4097, in start
    if self.address.startswith("inproc://"):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 354, in address
    self._address = self.listener.contact_address
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/tcp.py", line 573, in contact_address
    host = ensure_concrete_host(host, default_host=self.default_host)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/utils.py", line 122, in ensure_concrete_host
    return default_host or get_ip()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 155, in get_ip
    return _get_ip(host, port, family=socket.AF_INET)
  File "cytoolz/functoolz.pyx", line 476, in cytoolz.functoolz._memoize.__call__
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 140, in _get_ip
    addr_info = socket.getaddrinfo(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 131, in _get_ip
    sock.connect((host, port))
OSError: [Errno 51] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidchudzicki/miniconda3/envs/coiled/bin/dask-scheduler", line 8, in <module>
    sys.exit(go())
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 217, in go
    main()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 212, in main
    logger.info("End scheduler at %r", scheduler.address)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 354, in address
    self._address = self.listener.contact_address
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/tcp.py", line 573, in contact_address
    host = ensure_concrete_host(host, default_host=self.default_host)
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/comm/utils.py", line 122, in ensure_concrete_host
    return default_host or get_ip()
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 155, in get_ip
    return _get_ip(host, port, family=socket.AF_INET)
  File "cytoolz/functoolz.pyx", line 476, in cytoolz.functoolz._memoize.__call__
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/site-packages/distributed/utils.py", line 140, in _get_ip
    addr_info = socket.getaddrinfo(
  File "/Users/davidchudzicki/miniconda3/envs/coiled/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
</pre>
</details>

**Comment by fjetter** [comment]
I cannot reproduce either on OSX 12.1 

If you do not provide an address (e.g. `dask-scheduler --host 127.0.0.1`), we need to look for one. We're opening a UDP socket in the background which should not connect to the internet. However, if this fails, we're using `socket.getaddrinfo(socket.gethostname(), ...)` to infer an address. afaik, getaddrinfo will do a DNS resolve if the hostname is not known but since it's your hostname, that shouldn't happen...

tbh, I'm not entirely sure what's happening there and why it is needed. This part of the code is ancient

**Comment by harrisliuwk** [comment]
Running local dask-scheduler does not require internet access.

By glancing at your log emitted right after `dask-scheduler` command, I'd guess that something related to your global http proxy caused this.

**Comment by dchudz** [comment]
I don't think I'm using a proxy, but I admit I could be confused.

This isn't essential to me and I know I haven't made it possible for anyone else to reproduce, so I'll close the issue.

Thanks/sorry.
