### ISSUE TITLE
KeyError distributed/profile.py

### ISSUE THREAD

**Issue by peterroelants** [dask/distributed#5892]
**What happened**:

I got the following Exception printed while running my code:
```python-traceback
Exception in thread Profile:
Traceback (most recent call last):
  File "./lib/python3.10/site-packages/distributed/profile.py", line 115, in process
    d = state["children"][ident]
KeyError: '_all_objs;./lib/python3.10/site-packages/bokeh/embed/bundle.py;357'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "./lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "./lib/python3.10/site-packages/distributed/profile.py", line 274, in _watch
    process(frame, None, recent, omit=omit)
  File "./lib/python3.10/site-packages/distributed/profile.py", line 119, in process
    "description": info_frame(frame),
  File "./lib/python3.10/site-packages/distributed/profile.py", line 72, in info_frame
    line = linecache.getline(co.co_filename, frame.f_lineno, frame.f_globals).lstrip()
  File "./lib/python3.10/linecache.py", line 31, in getline
    if 1 <= lineno <= len(lines):
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```
The code continues running after the Exception is printed.

I suspect that the `KeyError` is coming from Dask, although I don't have any clue why and how it happens. The `linecache.getline` `TypeError` is a Python bug I think: https://bugs.python.org/msg414346

I cannot reliably reproduce this, and it only happens from time to time. I suspect it happens when I access the Dask Diagnostics UI.

**Environment**:

- Dask version: 2022.02.0
- Bokeh version: 2.4.2
- Python version: 3.10.2
- Operating System: Ubuntu
- Install method: conda-forge

**Comment by jcrist** [comment]
Since this is a distributed issue, I've transferred this to the distributed repo.

Can you also provide the version of distributed you've used? Is there a specific dask workload you have that seems to trigger it, or does it happen for differing workloads? Any further information you can provide on generating a reproducible example would be appreciated.

**Comment by peterroelants** [comment]
It seems to happen only occasionally, I don't know what triggers it, and I haven't been able to create a minimal example that replicates the issue. 
I was using distributed  2022.02.0. However, I switched to 2022.02.1, and I have yet to encounter the issue.

**Comment by jacobtomlinson** [comment]
The last comment here suggests this was resolved in `2022.02.1` and given that there hasn't been any further discussion I'm going to close this out. If folks are still experiencing this feel free to comment and we can reopen it.
