### ISSUE TITLE
No module named 'distributed.pytest_resourceleaks

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#6116]
```
mrocklin@carbon-7:~/workspace/distributed$ mamba env create -f continuous_integration/environment-3.10.yaml 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

done
Installing pip dependencies: ...working... done
mrocklin@carbon-7:~/workspace/distributed$ conda activate dask-distributed
mrocklin@carbon-7:~/workspace/distributed$ py.test distributed/tests/test_worker.py::test_broken_comm
Traceback (most recent call last):
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 746, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named 'distributed.pytest_resourceleaks'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrocklin/mambaforge/envs/dask-distributed/bin/py.test", line 11, in <module>
    sys.exit(console_main())
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1206, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1083, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 529, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode, rootpath)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 546, in _try_load_conftest
    self._getconftestmodules(anchor, importmode, rootpath)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 575, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 623, in _importconftest
    self.consider_conftest(mod)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 704, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 470, in register
    self.consider_module(plugin)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 712, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 719, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 748, in import_plugin
    raise ImportError(
  File "/home/mrocklin/mambaforge/envs/dask-distributed/lib/python3.10/site-packages/_pytest/config/__init__.py", line 746, in import_plugin
    __import__(importspec)
ImportError: Error importing plugin "distributed.pytest_resourceleaks": No module named 'distributed.pytest_resourceleaks'
```

cc @graingert

**Comment by graingert** [comment]
the `distributed.pytest_resourceleaks` module is not shipped with the distributed conda package: https://github.com/dask/distributed/blob/0528d8dc56dd42ef0049ee8293d240acdf909bd7/MANIFEST.in#L19

so you need to run `pip install -e .`

https://github.com/dask/distributed/blob/6a3cbd389143b43c8a21404e08479b8b51f65a64/.github/workflows/tests.yaml#L86

**Comment by mrocklin** [comment]
Thanks.  That resolves my issue.  

I'm going to close this issue.  If this happens to more folks please comment here or :+1: this comment and if this affects enough people we'll consider including this.
