### ISSUE TITLE
futures requirement not automatically installed for Python 2.7

### ISSUE THREAD

**Issue by MathMagique** [dask/distributed#619]
On my Mac, I set up a virtual environment with pyenv:
```
> pyenv virtualenv dask
> pyenv activate dask
> python --version
Python 2.7.11
```
Following the distributed installation guide for `pip`, I do the following:
```
> pip install dask distributed --upgrade
> pip list
backports-abc (0.4)
certifi (2016.9.26)
click (6.6)
cloudpickle (0.2.1)
dask (0.11.1)
distributed (1.13.3)
HeapDict (1.0.0)
locket (0.2.0)
msgpack-python (0.4.8)
pip (8.1.2)
psutil (4.4.2)
setuptools (28.7.1)
singledispatch (3.4.0.3)
six (1.10.0)
tblib (1.3.0)
toolz (0.8.0)
tornado (4.4.2)
wheel (0.30.0a0)
zict (0.0.3)
```
Starting with the quickstart guid, I get the following error message:
```
> python
>>> from distributed import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abc/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/__init__.py", line 5, in <module>
    from .deploy import LocalCluster
  File "/Users/abc/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/deploy/__init__.py", line 3, in <module>
    from .local import LocalCluster
  File "/Users/abc/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/deploy/local.py", line 13, in <module>
    from ..client import Client
  File "/Users/abc/.pyenv/versions/dask/lib/python2.7/site-packages/distributed/client.py", line 4, in <module>
    from concurrent.futures._base import DoneAndNotDoneFutures, CancelledError
ImportError: No module named concurrent.futures._base
```
The error can be resolved by _manually_ installing the `futures` package:
```
> pip install futures
...
Successfully installed futures-3.0.5
> python
>>> from distributed import Client
```
Having a look at setup.py (https://github.com/dask/distributed/blob/master/setup.py#L9-L10), it is a little odd that while `locket` is installed automatically, `futures` is not.

**Comment by mrocklin** [comment]
Thank you for the excellent bug report

**Comment by mrocklin** [comment]
My first attempt failed to reproduce (conda, linux).  Putting up here as a 

```python
mrocklin@carbon:~/workspace/distributed$ conda create -n test3 python=2 pip
Fetching package metadata .......
Solving package specifications: ..........
Using Anaconda Cloud api site https://api.anaconda.org

Package plan for installation in environment /home/mrocklin/Software/anaconda/envs/test3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-9.0.1                  |           py27_0         1.6 MB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0     
    pip:        9.0.1-py27_0 
    python:     2.7.12-1     
    readline:   6.2-2        
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3      

Fetching packages ...
spip-9.0.1-py27  18% |#####                           | ETA:  0:00:01 845.54 kB/pip-9.0.1-py27 100% |################################| Time: 0:00:01 986.58 kB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate test3
#
# To deactivate this environment, use:
# $ source deactivate
#
mrocklin@carbon:~/workspace/distributed$ source activate test3
(test3) mrocklin@carbon:~/workspace/distributed$ pip install -e .
Obtaining file:///home/mrocklin/workspace/distributed
Requirement already satisfied: tornado>=4.2 in /home/mrocklin/workspace/tornado (from distributed==1.14.1)
Collecting toolz>=0.7.4 (from distributed==1.14.1)
  Using cached toolz-0.8.0.tar.gz
Collecting msgpack-python (from distributed==1.14.1)
  Using cached msgpack-python-0.4.8.tar.gz
Requirement already satisfied: cloudpickle>=0.2.1 in /home/mrocklin/workspace/cloudpickle (from distributed==1.14.1)
Collecting dask>=0.12.0 (from distributed==1.14.1)
  Using cached dask-0.12.0-py2.py3-none-any.whl
Collecting click>=6.6 (from distributed==1.14.1)
Collecting six (from distributed==1.14.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting tblib (from distributed==1.14.1)
  Using cached tblib-1.3.0-py2.py3-none-any.whl
Collecting psutil (from distributed==1.14.1)
  Downloading psutil-5.0.0.zip (374kB)
    100% |████████████████████████████████| 378kB 863kB/s 
Collecting locket (from distributed==1.14.1)
  Using cached locket-0.2.0.tar.gz
Collecting zict>=0.1.0 (from distributed==1.14.1)
  Downloading zict-0.1.0-py2.py3-none-any.whl
Collecting futures (from distributed==1.14.1)
  Using cached futures-3.0.5-py2-none-any.whl
Collecting singledispatch (from distributed==1.14.1)
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting certifi (from tornado>=4.2->distributed==1.14.1)
  Using cached certifi-2016.9.26-py2.py3-none-any.whl
Collecting backports_abc>=0.4 (from tornado>=4.2->distributed==1.14.1)
  Using cached backports_abc-0.4-py2.py3-none-any.whl
Collecting heapdict (from zict>=0.1.0->distributed==1.14.1)
  Using cached HeapDict-1.0.0.tar.gz
Building wheels for collected packages: toolz, msgpack-python, psutil, locket, heapdict
  Running setup.py bdist_wheel for toolz ... done
  Stored in directory: /home/mrocklin/.cache/pip/wheels/b0/84/bf/7089262387e8ea60bdefb1fdb84d2ee99427f6d09c9c7ba37d
  Running setup.py bdist_wheel for msgpack-python ... done
  Stored in directory: /home/mrocklin/.cache/pip/wheels/2c/e7/e7/9031652a69d594665c5ca25e41d0fb3faa024e730b590e4402
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/mrocklin/.cache/pip/wheels/67/5c/c3/58a3b52db99b3897a190788d4b6ba7dfef44cff5b3b594cbf1
  Running setup.py bdist_wheel for locket ... done
  Stored in directory: /home/mrocklin/.cache/pip/wheels/7a/de/da/8039d7d9547aabfb95f2deca20948c8eb4c71c3b85405547c2
  Running setup.py bdist_wheel for heapdict ... done
  Stored in directory: /home/mrocklin/.cache/pip/wheels/db/86/e2/b2430d14a9fb006ff6adeee847e383c500efbab2a6ca37490a
Successfully built toolz msgpack-python psutil locket heapdict
Installing collected packages: toolz, msgpack-python, dask, click, six, tblib, psutil, locket, heapdict, zict, futures, singledispatch, distributed, certifi, backports-abc
  Found existing installation: distributed 1.14.1
    Can't uninstall 'distributed'. No files were found to uninstall.
  Running setup.py develop for distributed
Successfully installed backports-abc-0.4 certifi-2016.9.26 click-6.6 dask-0.12.0 distributed futures-3.0.5 heapdict-1.0.0 locket-0.2.0 msgpack-python-0.4.8 psutil-5.0.0 singledispatch-3.4.0.3 six-1.10.0 tblib-1.3.0 toolz-0.8.0 zict-0.1.0
```

Similar results using `python setup.py install`

**Comment by mrocklin** [comment]
As of #746 we now list futures explicitly in requirements.txt
