### ISSUE TITLE
Serialization of self-referencing structures

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#622]
Hello :-)

I stumbled upon a peculiar serialization error that happens with `cloudpickle.`
When a class `X` that has a method which creates an instance of the same class `X` is serialized "fully", cloudpickle fails on an assertion.
By "fully" I mean the situation when cloudpickle pickles lambdas and methods defined in the `__main__` module not with reference, but with the actual bytecode of the function (https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle.py#L222).
Pickle has no problem with this, but it can't serialize lambdas etc., so it fails, `distributed` then tries `cloudpickle` and that fails on the "recursive" structure.

There are some issues about this on the `cloudpickle` repo (https://github.com/cloudpipe/cloudpickle/issues/66) but there is little to no activity there.

The error only appears when the self-referenced class is used in the main module or python prompt, but that may be useful sometimes. I know that it's more of a `cloudpickle` problem, but it would be nice if it could be solved (maybe with the new custom serializers?).

Sample code
```python
from distributed import Client, LocalCluster

class A(object):
    def test(self):
        A()

def main():
    c = LocalCluster(n_workers=2)
    executor = Client(c)
    executor.map(lambda x: x, [A(), A()])
    # or a quick test directly with cloudpickle
    # cloudpickle.dumps(A(), cloudpickle.pickle.HIGHEST_PROTOCOL) 

if __name__ == "__main__":
    main()
```

Stack trace
```
Traceback (most recent call last):
  File "/home/kobzol/projects/pyqit/apps/dfa-cerny-conjecture/test.py", line 19, in <module>
    main()
  File "/home/kobzol/projects/pyqit/apps/dfa-cerny-conjecture/test.py", line 15, in main
    executor.map(lambda x: x, [A(), A()])
  File "/usr/local/lib/python2.7/dist-packages/distributed/client.py", line 759, in map
    loose_restrictions, priority=priority)
  File "/usr/local/lib/python2.7/dist-packages/distributed/client.py", line 1227, in _graph_to_futures
    'tasks': valmap(dumps_task, dsk3),
  File "/usr/local/lib/python2.7/dist-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/usr/local/lib/python2.7/dist-packages/distributed/worker.py", line 787, in dumps_task
    'args': dumps(task[1:])}
  File "/usr/local/lib/python2.7/dist-packages/distributed/core.py", line 66, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/usr/local/lib/python2.7/dist-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python2.7/dist-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python2.7/dist-packages/cloudpickle/cloudpickle.py", line 514, in save_reduce
    save(cls)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/cloudpickle/cloudpickle.py", line 368, in save_global
    self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
  File "/usr/local/lib/python2.7/dist-packages/cloudpickle/cloudpickle.py", line 533, in save_reduce
    self.memoize(obj)
  File "/usr/lib/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo
AssertionError
```

**Comment by mrocklin** [comment]
Yeah, this is a cloudpickle problem.  That's not to say that some dask developers might not help solve it, but it should be tracked over there.

This is out of scope for custom serializers, which are intended to serialize data.  Closing.

**Comment by Kobzol** [comment]
Okay, I'll track the progress there. I understood the custom serializers badly, thanks for the info.
