### ISSUE TITLE
RuntimeError: cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by guziy** [dask/distributed#6276]
**What happened**:
I get the following exception when trying to run a simple example:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/utils.py", line 358, in f
    result = yield future
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/client.py", line 1192, in _start
    await self._ensure_connected(timeout=timeout)
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/client.py", line 1255, in _ensure_connected
    comm = await connect(
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/comm/core.py", line 289, in connect
    comm = await asyncio.wait_for(
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/comm/tcp.py", line 439, in connect
    stream = await self.client.connect(
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/comm/tcp.py", line 424, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 819, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/huziy/Python/anaconda3/envs/py39/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

```

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
from dask_mpi import initialize
from distributed import LocalCluster, Client
import dask


def square(x):
    return x ** 2


def main():
    dask.config.set({"distributed.worker.use-file-locking": False})
    initialize(nthreads=1, dashboard=False)

    cluster = LocalCluster()
    client = Client(cluster)

    with cluster:
        with client:
            futures = client.map(square, range(1000))
            # progress(futures)
            results = client.gather(futures)

    print(results[:20])


if __name__ == '__main__':
    main()

```

**Anything else we need to know?**:
I run the example with mpirun: 
```bash
mpirun -n 2 python src/main.py
```

**Environment**:

- Dask version: 2022.05.0
- Python version: 3.9.12
- Operating System: Linux
- Install method (conda, pip, source): conda

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by guziy** [comment]
this seems to be working

```python
import dask_mpi
from dask_mpi import initialize
from distributed import LocalCluster, Client, progress
import dask


def square(x):
    return x ** 2


def main():
    dask.config.set({"distributed.worker.use-file-locking": False})

    is_client = initialize(nthreads=1, dashboard=False, exit=False)

    with LocalCluster(processes=True, threads_per_worker=1) as cluster:
        with Client(cluster, direct_to_workers=True) as client:
            if is_client:
                futures = client.map(square, range(1000))

                for key, obj in cluster.workers.items():
                    print(f"{key}: {obj}")

                progress(futures)
                results = client.gather(futures)

    print("is_client = ", is_client)

    if is_client:
        print(results[:20])
        dask_mpi.send_close_signal()


if __name__ == '__main__':
    main()

```

**Comment by guziy** [comment]
Sorry, I realize now that `ìnitialize` and `LocalCluster` should not be used together.

**Comment by jtlz2** [comment]
@guziy Any way to do this without the context manager? :\

**Comment by jtlz2** [comment]
@guziy Also - and thanks - how would one do this without mpi, or can I use mpi anyway? Thanks!
