### ISSUE TITLE
CrossFilter worker widget is broken and untested

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#6303]
Dask dashboard -> info -> open any worker -> CrossFilter
Start any computation

Nothing shows up on the widget. On the worker log you can read:
```python
2022-05-08 23:16:33,220 - bokeh.util.tornado - ERROR - Error thrown from periodic callback:
2022-05-08 23:16:33,221 - bokeh.util.tornado - ERROR - Traceback (most recent call last):
  File "/home/crusaderky/miniconda3/envs/distributed39/lib/python3.9/site-packages/distributed/utils.py", line 765, in wrapper
    return func(*args, **kwargs)
  File "/home/crusaderky/miniconda3/envs/distributed39/lib/python3.9/site-packages/distributed/dashboard/components/worker.py", line 360, in update
    d = self.process_msg(msg)
  File "/home/crusaderky/miniconda3/envs/distributed39/lib/python3.9/site-packages/distributed/dashboard/components/worker.py", line 413, in process_msg
    typ = self.worker.types.get(status_key, object).__name__
AttributeError: 'Worker' object has no attribute 'types'
```

``test_worker_bokeh.py::test_basic`` is supposed to test it, but due to subtle timings reasons it never invokes the update() method.

**Comment by quasiben** [comment]
I'm not sure I've ever used the crossfilter.  Have you found it useful ?

**Comment by crusaderky** [comment]
I personally didn't know it existed. I stumbled on it by accident.

**Comment by crusaderky** [comment]
After conversation with @mrocklin, we agreed to remove the widget completely, at least for the time being.
