### ISSUE TITLE
User-defined function given a `Series` with all `NaN` values when used with`DataFrame.apply()`

### ISSUE THREAD

**Issue by multimeric** [dask/distributed#6316]
**What happened**:
When calling `DataFrame.apply(my_func, axis=1)`, and when the computation was actually executed, my apply function was provided with a series in the correct shape, but with each value set to `NaN`

**What you expected to happen**:
The correct values to be provided to the function.

**Minimal Complete Verifiable Example**:
Could not reproduce this consistently

**Anything else we need to know?**:

The full stack trace is below. I reraised the error with a message that includes the values of each row (a Series), which is why all the `NaN`s get printed:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 930, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/biosig/workspace/users/mmilton/DriverGenePipe/driverpipe/task/result.py", line 39, in write
    value_.to_parquet(full_path, **save_kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/dataframe/core.py", line 4990, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 886, in to_parquet
    out = out.compute(**compute_kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/base.py", line 292, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/base.py", line 575, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/distributed/client.py", line 3004, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/distributed/client.py", line 2178, in gather
    return self.sync(
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/distributed/utils.py", line 318, in sync
    return sync(
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/distributed/utils.py", line 385, in sync
    raise exc.with_traceback(tb)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/distributed/utils.py", line 358, in f
    result = yield future
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/distributed/client.py", line 2041, in _gather
    raise exception.with_traceback(traceback)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/utils.py", line 40, in apply
    return func(*args, **kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/dataframe/core.py", line 6431, in apply_and_enforce
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/dask/utils.py", line 1022, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/pandas/core/frame.py", line 8839, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/pandas/core/apply.py", line 727, in apply
    return self.apply_standard()
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/pandas/core/apply.py", line 851, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/pandas/core/apply.py", line 867, in apply_series_generator
    results[i] = self.f(v)
  File "/home/mmilton/.conda/envs/mmilton/envs/driverpipe/lib/python3.9/site-packages/pandas/core/apply.py", line 138, in f
    return func(x, *args, **kwargs)
  File "/biosig/workspace/users/mmilton/DriverGenePipe/driverpipe/task/__init__.py", line 198, in _apply_wrapper
    raise Exception(f"Error when handling row {row}") from e
Exception: Error when handling row uniprot                Q14790
amino_acids               NaN
biotype                   NaN
canonical                 NaN
cdna_end                  NaN
cdna_start                NaN
cds_end                   NaN
cds_start                 NaN
codons                    NaN
consequence_terms         NaN
distance                  NaN
gene_id                   NaN
gene_symbol               NaN
gene_symbol_source        NaN
hgnc_id                   NaN
hgvsc                     NaN
hgvsg                     NaN
hgvsp                     NaN
id                        NaN
impact                    NaN
polyphen_prediction       NaN
polyphen_score            NaN
protein_end               NaN
protein_start             NaN
sift_prediction           NaN
sift_score                NaN
strand                    NaN
swissprot                 NaN
transcript_id             NaN
trembl                    NaN
uniparc                   NaN
uniprot_isoform           NaN
variant_allele            NaN
Name: 2:201266487:A>G, dtype: object

```

So notably this error is intermittent, which makes me think it might be a race condition. Also, when I run the same commands in isolation, my function is given correct values for the row.

**Environment**:

Dask version: dask-2022.5.0 + dask_jobqueue-0.7.3
Python version: 3.9.12
Operating System: Ubuntu 20.04.4 LTS
Install method (conda, pip, source): conda

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by multimeric** [comment]
Also, when this happens, it's triggered by writing the `DataFrame` to parquet. And many of the partitions are successfully written, but others are not. So I end up with a parquet directory that's partially populated:
```
part.0.parquet  part.1.parquet   part.10.parquet  part.11.parquet  part.12.parquet  part.13.parquet  part.14.parquet  part.15.parquet  part.16.parquet  part.17.parquet  part.18.parquet  part.19.parquet
part.2.parquet  part.20.parquet  part.22.parquet  part.3.parquet   part.30.parquet  part.33.parquet  part.34.parquet
```

**Comment by multimeric** [comment]
Hmm, this is possibly an issue on my end.
