### ISSUE TITLE
AttributeError: type object '...' has no attribute '_io_loop' in Actor constructed without a default client

### ISSUE THREAD

**Issue by graingert** [dask/distributed#6477]
see https://github.com/dask/dask-jobqueue/issues/552
when running an actor with a client constructed with `Client(set_as_default=False)` attribute lookup fails with an AttributeError:

```python
import sys
import distributed

class Counter:
    """ A simple class to manage an incrementing counter """
    n = 0

    def __init__(self):
        self.n = 0

    def increment(self):
        self.n += 1
        return self.n

    def add(self, x):
        self.n += x
        return self.n

def main():
    with distributed.Client(set_as_default=False) as client:
        counter = client.submit(Counter, actor=True).result()
        counter.add(1)
        print(f"{counter.n=}")

if __name__ == "__main__":
    sys.exit(main())
```

```pytb
Traceback (most recent call last):
  File "/home/graingert/projects/distributed/foo.py", line 26, in <module>
    sys.exit(main())
  File "/home/graingert/projects/distributed/foo.py", line 22, in main
    counter.add(1)
  File "/home/graingert/projects/distributed/distributed/actor.py", line 215, in func
    actor_future = ActorFuture(io_loop=self._io_loop)
  File "/home/graingert/projects/distributed/distributed/actor.py", line 190, in __getattr__
    attr = getattr(self._cls, key)
AttributeError: type object 'Counter' has no attribute '_io_loop'
```

**Comment by mrocklin** [comment]
I'm fine with this.  Actors require a Client.  If there is no client then
the user should provide one.  Probably we should improve the error message
here
