### ISSUE TITLE
KeyError: 'bytestrings'

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#649]
With investigating the logging issues I've upgraded to master (282b4f5d79f61841fad346751e9903ad8aefe184) and have started seeing the below errors.

I think this happens when a task fails. Sorry this is just a heads-up for now, if I find the time I'll try to add a repro...
```
CRITICAL:c:\dev\code\distributed\distributed\protocol\core.py:Failed to deerialize
Traceback (most recent call last):
  File "c:\dev\code\distributed\distributed\protocol\core.py", line 96, in loads
    bytestrings = set(header['bytestrings'])
KeyError: 'bytestrings'
distributed.scheduler - ERROR - 'bytestrings'
Traceback (most recent call last):
  File "c:\dev\code\distributed\distributed\scheduler.py", line 1002, in handle_messages
    msgs = yield next_message()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Python\envs\py-dev\lib\site-packages\tornado\gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "c:\dev\code\distributed\distributed\core.py", line 217, in read
    msg = protocol.loads(frames, deserialize=deserialize)
  File "c:\dev\code\distributed\distributed\protocol\core.py", line 96, in loads
    bytestrings = set(header['bytestrings'])
KeyError: 'bytestrings'
```

**Comment by mrocklin** [comment]
Can you verify that your workers, scheduler, and client are all updated?  This error would occur if some were still using a slightly older version.

**Comment by dhirschfeld** [comment]
Thanks for the info - I was still running 1.14.1 on my client side so will close this with the assumption that was the problem...
