### ISSUE TITLE
KeyError: 'bytestrings'

### ISSUE THREAD

**Issue by apiszcz** [dask/distributed#658]
3 workers on ubuntu 16.04 (64 bit)
1 scheduler running on ubuntu 16.04 (32 bit)

Test from documentation:

```python
from distributed import Client
client = Client('10.0.1.40:8786')

def square(x):
    return x ** 2

def neg(x):
    return -x

A = client.map(square, range(10))
B = client.map(neg, A)
total = client.submit(sum, B)
total.result()

==
python mapsubmit01.py 
distributed.utils - ERROR - 'bytestrings'
Traceback (most recent call last):
  File "/a/a3/lib/python3.5/site-packages/distributed/utils.py", line 120, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/a/a3/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/a/a3/lib/python3.5/site-packages/distributed/client.py", line 134, in _result
    result = yield self.client._gather([self])
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/a/a3/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/a/a3/lib/python3.5/site-packages/distributed/client.py", line 821, in _gather
    self.futures[key]['event'].clear()
KeyError: 'bytestrings'
Traceback (most recent call last):
  File "mapsubmit01.py", line 13, in <module>
    total.result()
  File "/a/a3/lib/python3.5/site-packages/distributed/client.py", line 108, in result
    result = sync(self.client.loop, self._result, raiseit=False)
  File "/a/a3/lib/python3.5/site-packages/distributed/utils.py", line 134, in sync
    six.reraise(type(error[0]), error[0], traceback[0])
  File "/a/a3/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/a/a3/lib/python3.5/site-packages/distributed/utils.py", line 120, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/a/a3/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/a/a3/lib/python3.5/site-packages/distributed/client.py", line 134, in _result
    result = yield self.client._gather([self])
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/a/a3/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/a/a3/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/a/a3/lib/python3.5/site-packages/distributed/client.py", line 821, in _gather
    self.futures[key]['event'].clear()
KeyError: 'bytestrings'
```

**Comment by mrocklin** [comment]
Can you verify that all of your workers and scheduler and client are running the same version of `distributed`?

**Comment by apiszcz** [comment]
They are different I'll correct that, thank you.


.202
>>> import distributed
>>> distributed.__version__
'1.14.2'



.216
>>> import distributed
>>> distributed.__version__
'1.14.1'

**Comment by apiszcz** [comment]
That corrected the issue. Only one node has .14.1 updated to .14.2 and
examples work. In the start up banner/INFO it might be worth display the
version. Perhaps there is a mode of the web server that displays, I need to
review, thank you.

**Comment by apiszcz** [comment]
The client.get_versions() is helpful to  inspect of all versions in the cluster.

**Comment by mrocklin** [comment]
I'm glad, thank @jreback for that feature :)
