### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by orf** [dask/distributed#6588]
In https://github.com/dask/distributed/pull/6566, the following line was added/moved:

https://github.com/dask/distributed/blob/8aab5e840aa48e9574d286c5119f023a426077dd/distributed/worker_state_machine.py#L1195

We're missing a stimulus_id argument to the format string, which results in a lot of spammy errors from logging:

```
2022-06-16T16:42:29.486762121Z --- Logging error ---
2022-06-16T16:42:29.486764931Z Traceback (most recent call last):
2022-06-16T16:42:29.486767752Z   File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
2022-06-16T16:42:29.486770532Z     msg = self.format(record)
2022-06-16T16:42:29.486773632Z   File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
2022-06-16T16:42:29.486779212Z     return fmt.format(record)
2022-06-16T16:42:29.486782252Z   File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
2022-06-16T16:42:29.486785202Z     record.message = record.getMessage()
2022-06-16T16:42:29.486788192Z   File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
2022-06-16T16:42:29.486791072Z     msg = msg % self.args
2022-06-16T16:42:29.486793722Z TypeError: not enough arguments for format string
```

**Comment by orf** [comment]
cc @crusaderky as you made the change. I can make a PR to remove the `stimulus_id=%s` section

**Comment by crusaderky** [comment]
Thanks for spotting it
