### ISSUE TITLE
scatter to empty adaptive cluster

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#6686]
Client.scatter hangs until there is at least one worker on the cluster.
This is a problem for adaptive clusters that scale down to zero.

#### Expected behaviour
scatter() causes the cluster to scale up to 1 worker

#### Actual behaviour
scatter() hangs forever

**Comment by hendrikmakait** [comment]
Instead of hanging indefinitely, `scatter()` times out with
```
2022-07-15 19:39:12,046 - distributed.core - ERROR - Exception while handling op scatter
Traceback (most recent call last):
  File "/Users/hendrikmakait/projects/dask/distributed/distributed/core.py", line 769, in _handle_comm
    result = await result
  File "/Users/hendrikmakait/projects/dask/distributed/distributed/scheduler.py", line 5041, in scatter
    raise TimeoutError("No valid workers found")
asyncio.exceptions.TimeoutError: No valid workers found
```
thanks to 
https://github.com/dask/distributed/blob/930d3dc023a43990374b5d6a567dfe3ac3dcc428/distributed/scheduler.py#L5030-L5042

**Reproducer:** 
```python3
from __future__ import annotations

from distributed import Client, LocalCluster
from distributed.utils_test import gen_test


@gen_test()
async def test_scatter_scales_up_empty_cluster():
    async with LocalCluster(
        n_workers=0,
        silence_logs=False,
        processes=False,
        dashboard_address=":0",
        asynchronous=True,
    ) as cluster:
        cluster.adapt(minimum=0, maximum=4, interval="10 ms")
        async with Client(cluster, asynchronous=True) as client:
            await client.scatter([0])
```
