### ISSUE TITLE
Python 3.10 test suite unexpected exception message forma

### ISSUE THREAD

**Issue by bnavigator** [dask/distributed#6719]
Follow-up from #5460 

I am still getting errors in Python 3.10 because of an unexpected exception message format:

```
[    3s] + pytest distributed/tests -m 'not avoid_ci' -k 'test_exception_text or test_worker_bad_args or test_run_spec_deserialize_fail'
[    4s] ============================= test session starts ==============================
[    4s] platform linux -- Python 3.10.5, pytest-7.1.1, pluggy-1.0.0 -- /usr/bin/python3.10
[    4s] cachedir: .pytest_cache
[    4s] rootdir: /home/abuild/rpmbuild/BUILD/distributed-2022.7.0, configfile: setup.cfg
[    4s] plugins: timeout-2.0.2, rerunfailures-10.2
[    4s] timeout: 300.0s
[    4s] timeout method: signal
[    4s] timeout func_only: False
[    7s] collecting ... collected 2080 items / 2077 deselected / 3 selected
[    7s] 
[    7s] distributed/tests/test_client.py::test_exception_text FAILED             [ 33%]
[    7s] distributed/tests/test_worker.py::test_worker_bad_args FAILED            [ 66%]
[    7s] distributed/tests/test_worker.py::test_run_spec_deserialize_fail FAILED  [100%]
[    7s] 
[    7s] =================================== FAILURES ===================================
[    7s] _____________________________ test_exception_text ______________________________
[    7s] 
[    7s] c = <Client: No scheduler connected>
[    7s] s = <Scheduler 'tcp://127.0.0.1:40661', workers: 0, cores: 0, tasks: 0>
[    7s] a = <Worker 'tcp://127.0.0.1:42921', name: 0, status: closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
[    7s] b = <Worker 'tcp://127.0.0.1:39569', name: 1, status: closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>
[    7s] 
[    7s]     @gen_cluster(client=True)
[    7s]     async def test_exception_text(c, s, a, b):
[    7s]         def bad(x):
[    7s]             raise Exception(x)
[    7s]     
[    7s]         future = c.submit(bad, 123)
[    7s]         await wait(future)
[    7s]     
[    7s]         ts = s.tasks[future.key]
[    7s]     
[    7s]         assert isinstance(ts.exception_text, str)
[    7s]         assert "123" in ts.exception_text
[    7s] >       assert "Exception(x)" in ts.traceback_text
[    7s] E       assert 'Exception(x)' in '  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_client.py", line -1, in bad\n'
[    7s] E        +  where '  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_client.py", line -1, in bad\n' = <TaskState 'bad-822a7fc4a91bde0ea17b38ddfddb9f71' erred>.traceback_text
[    7s] 
[    7s] distributed/tests/test_client.py:7108: AssertionError
[    7s] ----------------------------- Captured stdout call -----------------------------
...
[    7s] _____________________________ test_worker_bad_args _____________________________
[    7s] 
[    7s] c = <Client: No scheduler connected>
[    7s] s = <Scheduler 'tcp://127.0.0.1:35193', workers: 0, cores: 0, tasks: 0>
[    7s] a = <Worker 'tcp://127.0.0.1:37677', name: 0, status: closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
[    7s] b = <Worker 'tcp://127.0.0.1:46519', name: 1, status: closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>
[    7s] 
[    7s]     @gen_cluster(client=True)
[    7s]     async def test_worker_bad_args(c, s, a, b):
[    7s]         class NoReprObj:
[    7s]             """This object cannot be properly represented as a string."""
[    7s]     
[    7s]             def __str__(self):
[    7s]                 raise ValueError("I have no str representation.")
[    7s]     
[    7s]             def __repr__(self):
[    7s]                 raise ValueError("I have no repr representation.")
[    7s]     
...
[    7s]         tb = await y._traceback()
[    7s] >       assert any("1 / 0" in line for line in pluck(3, traceback.extract_tb(tb)) if line)
[    7s] E       assert False
[    7s] E        +  where False = any(<generator object test_worker_bad_args.<locals>.<genexpr> at 0x7f4e5acfc660>)
[    7s] 
[    7s] distributed/tests/test_worker.py:170: AssertionError
[    7s] ----------------------------- Captured stdout call -----------------------------
[    7s] Dumped cluster state to test_cluster_dump/test_worker_bad_args.yaml
[    7s] ----------------------------- Captured stderr call -----------------------------
...
[    7s] 2022-07-12 19:16:48,365 - distributed.worker - WARNING - Compute Failed
[    7s] Key:       bad_func-0918da27e3428d0131383a867f36344e
[    7s] Function:  bad_func
[    7s] args:      (< could not convert arg to str >)
[    7s] kwargs:    {'k': < could not convert arg to str >}
[    7s] Exception: "ZeroDivisionError('division by zero')"
[    7s] 
...
[    7s] ________________________ test_run_spec_deserialize_fail ________________________
[    7s] 
[    7s] c = <Client: No scheduler connected>
[    7s] s = <Scheduler 'tcp://127.0.0.1:41599', workers: 0, cores: 0, tasks: 0>
[    7s] a = <Worker 'tcp://127.0.0.1:45687', name: 0, status: closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
[    7s] b = <Worker 'tcp://127.0.0.1:41785', name: 1, status: closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>
[    7s] 
[    7s]     @gen_cluster(client=True)
[    7s]     async def test_run_spec_deserialize_fail(c, s, a, b):
[    7s]         class F:
[    7s]             def __call__(self):
[    7s]                 pass
[    7s]     
[    7s]             def __reduce__(self):
[    7s]                 return lambda: 1 / 0, ()
[    7s]     
[    7s]         with captured_logger("distributed.worker") as logger:
[    7s]             fut = c.submit(F())
[    7s]             assert isinstance(await fut.exception(), ZeroDivisionError)
[    7s]     
[    7s]         logvalue = logger.getvalue()
[    7s]         assert "Could not deserialize task" in logvalue
[    7s] >       assert "return lambda: 1 / 0, ()" in logvalue
[    7s] E       assert 'return lambda: 1 / 0, ()' in 'Could not deserialize task <test_worker.test_run_spec_deserialize_fail.<local-b98f6dd9f49be85143d9be10ceb703a4\nTraceback (most recent call last):\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2740, in loads_function\n    result = cache_loads[bytes_object]\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/collections.py", line 23, in __getitem__\n    value = super().__getitem__(key)\n  File "/usr/lib64/python3.10/collections/__init__.py", line 1106, in __getitem__\n    raise KeyError(key)\nKeyError: b\'\\x80\\x04\\x95\\xa0\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x8c\\x17cloudpickle.cloudpickle\\x94\\x8c\\r_builtin_type\\x94\\x93\\x94\\x8c\\nLambdaType\\x94\\x85\\x94R\\x94(h\\x02\\x8c\\x08CodeType\\x94\\x85\\x94R\\x94(K\\x00K\\x00K\\x00K\\x00K\\x02JS\\x00\\x00\\x01C\\x08d\\x01d\\x02\\x1b\\x00S\\x00\\x94NK\\x01K\\x00\\x87\\x94))\\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\\x94\\x8c\\x08<lambda>\\x94Mg\\nC\\x00\\x94))t\\x94R\\x94}\\x94(\\x8c\\x0b__package__\\x94\\x8c\\x00\\x94\\x8c\\x08__name__\\x94\\x8c\\x0btest_worker\\x94\\x8c\\x08__file__\\x94\\x8cQ/home/abuild/rpmbuild/BUILD/dis...x07__doc__\\x94N\\x8c\\x0b__closure__\\x94N\\x8c\\x17_cloudpickle_submodules\\x94]\\x94\\x8c\\x0b__globals__\\x94}\\x94u\\x86\\x94\\x86R0)R\\x94.\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2157, in execute\n    function, args, kwargs = await self._maybe_deserialize_task(ts)\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2127, in _maybe_deserialize_task\n    function, args, kwargs = _deserialize(*ts.run_spec)\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2751, in _deserialize\n    function = loads_function(function)\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2742, in loads_function\n    result = pickle.loads(bytes_object)\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/protocol/pickle.py", line 73, in loads\n    return pickle.loads(x)\n  File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py", line -1, in <lambda>\nZeroDivisionError: division by zero\n'
[    7s] 
[    7s] distributed/tests/test_worker.py:2671: AssertionError
[    7s] ----------------------------- Captured stdout call -----------------------------
[    7s] Dumped cluster state to test_cluster_dump/test_run_spec_deserialize_fail.yaml
[    7s] ----------------------------- Captured stderr call -----------------------------
[    7s] 2022-07-12 19:16:48,476 - distributed.scheduler - INFO - State start
...
[    7s] 2022-07-12 19:16:48,500 - distributed.core - INFO - Starting established connection
[    7s] 2022-07-12 19:16:48,511 - distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\xa0\x02\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\r_builtin_type\x94\x93\x94\x8c\nLambdaType\x94\x85\x94R\x94(h\x02\x8c\x08CodeType\x94\x85\x94R\x94(K\x00K\x00K\x00K\x00K\x02JS\x00\x00\x01C\x08d\x01d\x02\x1b\x00S\x00\x94NK\x01K\x00\x87\x94))\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\x94\x8c\x08<lambda>\x94Mg\nC\x00\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94\x8c\x00\x94\x8c\x08__name__\x94\x8c\x0btest_worker\x94\x8c\x08__file__\x94\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\x94uNNNt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x12_function_setstate\x94\x93\x94h\x18}\x94}\x94(h\x13h\x0c\x8c\x0c__qualname__\x94\x8cFtest_run_spec_deserialize_fail.<locals>.F.__reduce__.<locals>.<lambda>\x94\x8c\x0f__annotations__\x94}\x94\x8c\x0e__kwdefaults__\x94N\x8c\x0c__defaults__\x94N\x8c\n__module__\x94h\x14\x8c\x07__doc__\x94N\x8c\x0b__closure__\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0b__globals__\x94}\x94u\x86\x94\x86R0)R\x94.'
[    7s] Traceback (most recent call last):
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2740, in loads_function
[    7s]     result = cache_loads[bytes_object]
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/collections.py", line 23, in __getitem__
[    7s]     value = super().__getitem__(key)
[    7s]   File "/usr/lib64/python3.10/collections/__init__.py", line 1106, in __getitem__
[    7s]     raise KeyError(key)
[    7s] KeyError: b'\x80\x04\x95\xa0\x02\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\r_builtin_type\x94\x93\x94\x8c\nLambdaType\x94\x85\x94R\x94(h\x02\x8c\x08CodeType\x94\x85\x94R\x94(K\x00K\x00K\x00K\x00K\x02JS\x00\x00\x01C\x08d\x01d\x02\x1b\x00S\x00\x94NK\x01K\x00\x87\x94))\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\x94\x8c\x08<lambda>\x94Mg\nC\x00\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94\x8c\x00\x94\x8c\x08__name__\x94\x8c\x0btest_worker\x94\x8c\x08__file__\x94\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\x94uNNNt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x12_function_setstate\x94\x93\x94h\x18}\x94}\x94(h\x13h\x0c\x8c\x0c__qualname__\x94\x8cFtest_run_spec_deserialize_fail.<locals>.F.__reduce__.<locals>.<lambda>\x94\x8c\x0f__annotations__\x94}\x94\x8c\x0e__kwdefaults__\x94N\x8c\x0c__defaults__\x94N\x8c\n__module__\x94h\x14\x8c\x07__doc__\x94N\x8c\x0b__closure__\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0b__globals__\x94}\x94u\x86\x94\x86R0)R\x94.'
[    7s] 
[    7s] During handling of the above exception, another exception occurred:
[    7s] 
[    7s] Traceback (most recent call last):
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/protocol/pickle.py", line 73, in loads
[    7s]     return pickle.loads(x)
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py", line -1, in <lambda>
[    7s] ZeroDivisionError: division by zero
[    7s] 2022-07-12 19:16:48,512 - distributed.worker - ERROR - Could not deserialize task <test_worker.test_run_spec_deserialize_fail.<local-b98f6dd9f49be85143d9be10ceb703a4
[    7s] Traceback (most recent call last):
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2740, in loads_function
[    7s]     result = cache_loads[bytes_object]
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/collections.py", line 23, in __getitem__
[    7s]     value = super().__getitem__(key)
[    7s]   File "/usr/lib64/python3.10/collections/__init__.py", line 1106, in __getitem__
[    7s]     raise KeyError(key)
[    7s] KeyError: b'\x80\x04\x95\xa0\x02\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\r_builtin_type\x94\x93\x94\x8c\nLambdaType\x94\x85\x94R\x94(h\x02\x8c\x08CodeType\x94\x85\x94R\x94(K\x00K\x00K\x00K\x00K\x02JS\x00\x00\x01C\x08d\x01d\x02\x1b\x00S\x00\x94NK\x01K\x00\x87\x94))\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\x94\x8c\x08<lambda>\x94Mg\nC\x00\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94\x8c\x00\x94\x8c\x08__name__\x94\x8c\x0btest_worker\x94\x8c\x08__file__\x94\x8cQ/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py\x94uNNNt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x12_function_setstate\x94\x93\x94h\x18}\x94}\x94(h\x13h\x0c\x8c\x0c__qualname__\x94\x8cFtest_run_spec_deserialize_fail.<locals>.F.__reduce__.<locals>.<lambda>\x94\x8c\x0f__annotations__\x94}\x94\x8c\x0e__kwdefaults__\x94N\x8c\x0c__defaults__\x94N\x8c\n__module__\x94h\x14\x8c\x07__doc__\x94N\x8c\x0b__closure__\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0b__globals__\x94}\x94u\x86\x94\x86R0)R\x94.'
[    7s] 
[    7s] During handling of the above exception, another exception occurred:
[    7s] 
[    7s] Traceback (most recent call last):
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2157, in execute
[    7s]     function, args, kwargs = await self._maybe_deserialize_task(ts)
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2127, in _maybe_deserialize_task
[    7s]     function, args, kwargs = _deserialize(*ts.run_spec)
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2751, in _deserialize
[    7s]     function = loads_function(function)
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/worker.py", line 2742, in loads_function
[    7s]     result = pickle.loads(bytes_object)
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/protocol/pickle.py", line 73, in loads
[    7s]     return pickle.loads(x)
[    7s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.7.0/distributed/tests/test_worker.py", line -1, in <lambda>
[    7s] ZeroDivisionError: division by zero
...
[    7s] =========================== short test summary info ============================
[    7s] FAILED distributed/tests/test_client.py::test_exception_text - assert 'Except...
[    7s] FAILED distributed/tests/test_worker.py::test_worker_bad_args - assert False
[    7s] FAILED distributed/tests/test_worker.py::test_run_spec_deserialize_fail - ass...
[    7s] ====================== 3 failed, 2077 deselected in 3.66s ======================
```

Full log with all package versions: [distributed-py310-exceptiontestfailures.txt](https://github.com/dask/distributed/files/9096166/distributed-py310-exceptiontestfailures.txt)

**Anything else we need to know?**:
For a way how to reproduce, see https://github.com/dask/distributed/issues/5460#issuecomment-1080623590

**Environment**:

- Dask version: 2022.7.0
- Python version: 3.10.5
- Operating System: openSUSE Tumbleweed rpmbuild vm (`osc build `)
- Install method (conda, pip, source): source / rpm

**Comment by bnavigator** [comment]
I cannot reproduce it anymore in 2022.10.0
