### ISSUE TITLE
str / bytes mismatch in keys

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#676]
I noticed the following ignored exception during e.g. `distributed/tests/test_scheduler.py::test_add_worker`. It seems at some point some of the code paths were converted to use bytestrings as keys (why?), but not all of them, and Python 3 obviously doesn't like it.

(also, some keys can also be tuples... is there a hard rule?)

To me, str keys would feel more natural. Is there a reason I'm missing?

```
ERROR:tornado.application:Future <tornado.concurrent.Future object at 0x7f8fa40a2630> exception was never retrieved: Traceback (most recent call last):
  File "/home/antoine/tornado/tornado/gen.py", line 1043, in run
    yielded = self.gen.send(value)
  File "/home/antoine/distributed/distributed/worker.py", line 563, in compute_one
    self.data[key] = result.pop('result')
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/site-packages/zict/buffer.py", line 61, in __setitem__
    if key in self.slow:
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/_collections_abc.py", line 601, in __contains__
    self[key]
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/site-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/site-packages/zict/file.py", line 34, in __getitem__
    with open(os.path.join(self.directory, key), 'rb') as f:
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by pitrou** [comment]
@mrocklin

**Comment by mrocklin** [comment]
This was me being dumb.  I didn't realize that msgpack would return strings
to us if we asked it to.  All changes were made and then most were reverted.
