### ISSUE TITLE
Improve error when if __name__ == "__main__" is omitted

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#6816]
**What happened**:

When running a small future submitting example the cluster fails to start and dumps reams of tracebacks.

**What you expected to happen**:

Prints the result.

**Minimal Complete Verifiable Example**:

```console
$ conda create -n dask-what python dask distributed -y
$ conda activate dask-what 
```

```python
# what.py
from dask.distributed import Client

f = lambda: 10 + 1

with Client() as client:
    print(client.submit(f).result())
```

```console
$ python what.py
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
2022-08-01 10:44:48,185 - distributed.nanny - ERROR - Failed to start process
```

<details>
<summary>Full traceback</summary>

```python-traceback
/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/node.py:179: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 41555 instead
  warnings.warn(
/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/node.py:179: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 40205 instead
  warnings.warn(
/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/node.py:179: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 37055 instead
  warnings.warn(
/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/node.py:179: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 40399 instead
  warnings.warn(
2022-08-01 10:44:48,184 - distributed.nanny - ERROR - Failed to start process
Traceback (most recent call last):
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/nanny.py", line 436, in instantiate
    result = await self.process.start()
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/nanny.py", line 679, in start
    await self.process.start()
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/process.py", line 38, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/process.py", line 199, in _start
    process.start()
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
2022-08-01 10:44:48,185 - distributed.nanny - ERROR - Failed to start process

... repeated many times until keyboard interrupt

task: <Task pending name='Task-77' coro=<Nanny._on_exit() running at /home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/utils.py:778> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>
Exception ignored in: <coroutine object Nanny._on_exit at 0x7f5117e3c120>
Traceback (most recent call last):
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/utils.py", line 777, in wrapper
  File "/home/jtomlinson/miniconda3/envs/dask-what/lib/python3.10/site-packages/distributed/utils.py", line 792, in __exit__
ImportError: sys.meta_path is None, Python is likely shutting down

... repeated many times
```

</details>

**Comment by quasiben** [comment]
I tried to reproduce but was unable to.  I did notice that you got python 3.10 -- conda decided to give me 3.9.  What version of Dask did conda resolve to ?

**Comment by jacobtomlinson** [comment]
I saw this with Python `3.8` and `3.10` on both Mac and Linux. I started with `2022.7.0` and explored back through every release until December 2021 and it happened every time.

I feel like this could be something to do with my setup, maybe something in my config. But it's weird that it happened on two different systems.

**Comment by quasiben** [comment]
> ImportError: sys.meta_path is None, Python is likely shutting down

Seems odd.  Can you try this in a vanilla shell?  Internet seems to indicate shows up during selenium things so maybe it's an artifact rather that then cause.   Maybe something is wonky in the `~/.config/dask/` ?

**Comment by jacobtomlinson** [comment]
Fixed it! I needed `if __name__ == "__main__":`.

```python
from dask.distributed import Client


if __name__ == "__main__":

    f = lambda: 10 + 1

    with Client() as client:
        print(client.submit(f).result())
```

```console
$ python /tmp/what.py
11
```

**Comment by jacobtomlinson** [comment]
This error message kinda sucked though. I left it running into a log file for 20 seconds or so and ended up with 26k lines of logs that were hard to debug. 

I wonder if we can catch this scenario and raise something more useful before even trying to create the cluster.

**Comment by jrbourbeau** [comment]
Thanks @jacobtomlinson -- improving this error message would be a big win IMO. Closing in favor of https://github.com/dask/distributed/issues/2708 to avoid duplicate issues
