### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by windowshopr** [dask/distributed#6824]
**OVERVIEW**
I'm trying to connect my Raspberry Pi 4b worker to my dask-scheduler. After A LOT of debugging, I was able to get the environment setup below (with the help of [this article](https://raspberrypi.stackexchange.com/questions/8308/how-to-install-latest-scipy-version-on-raspberry-pi) for setting up `scipy`), which matches the dependencies on my scheduler machine (almost):

**ENVIRONMENT**
Raspberry Pi 4b (Bullseye 11)
Python 3.10.5
```
dask==2022.7.0
dask-glm==0.2.0
dask-ml==2022.5.27
deap==1.3.1
distributed==2022.7.0
numba==0.56.0
numpy==1.22.4
pandas==1.4.3
Pillow==9.2.0
scikit-learn==1.1.1
scipy==1.10.0.dev0+1601.f331f2e
tornado==6.1
```

**PROBLEM**
When I run the command `dask-worker tcp://172.16.1.113:8786 --nprocs 1 --nthreads 2 --memory-limit "1GB"` on the Pi, it connects to the scheduler, I can see the worker in the Web UI, however after a few seconds it starts failing with this traceback:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 73, in loads
    return pickle.loads(x)
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from scipy.sparse import issparse
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/sparse/__init__.py", line 267, in <module>
    from ._csr import *
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/sparse/_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import
2022-08-03 21:14:12,045 - distributed.protocol.core - CRITICAL - Failed to deserialize
```

Googling that error message, I see this solution which involves updating the `numpy` version on the Pi (which is good, because the version on my scheduler is `1.23.1` anyway), so I run `pip install numpy==1.23.1` to match the version with the scheduler, which introduces a new repeating error that I'm having a hard time debugging:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/worker.py", line 180, in wrapper
    return await method(self, *args, **kwargs)  # type: ignore
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/worker.py", line 1213, in handle_scheduler
    await self.handle_stream(comm)
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/core.py", line 821, in handle_stream
    msgs = await comm.read()
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 252, in read
    msg = await from_frames(
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/comm/utils.py", line 100, in from_frames
    res = _from_frames()
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/comm/utils.py", line 83, in _from_frames
    return protocol.loads(
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/core.py", line 158, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/core.py", line 138, in _decode_default
    return merge_and_deserialize(
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/serialize.py", line 497, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/serialize.py", line 426, in deserialize
    return loads(header, frames)
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/serialize.py", line 96, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 73, in loads
    return pickle.loads(x)
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 29, in <module>
    from .fixes import parse_version, threadpool_info
  File "/home/pi/.local/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 19, in <module>
    import scipy.stats
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/stats/__init__.py", line 470, in <module>
    from ._stats_py import *
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/stats/_stats_py.py", line 46, in <module>
    from . import distributions
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/stats/_distn_infrastructure.py", line 22, in <module>
    from scipy import optimize
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/__init__.py", line 198, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/optimize/_linprog.py", line 21, in <module>
    from ._linprog_highs import _linprog_highs
  File "/home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/optimize/_linprog_highs.py", line 20, in <module>
    from ._highs._highs_wrapper import _highs_wrapper
ImportError: /home/pi/.local/lib/python3.10/site-packages/scipy-1.10.0.dev0+1601.f331f2e-py3.10-linux-armv7l.egg/scipy/optimize/_highs/_highs_wrapper.cpython-310-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8
```

**ATTEMPTS TO FIX**

**Attempt 1**
I attempted reinstalling `scipy` as I thought there might have been a problem with the build process using that development wheel, so I ran:

`pip uninstall scipy`
`pip install scipy`

...and attempted to load the `dask-worker` again, but it gave the same error, just with the updated `scipy` in the output:

```
ImportError: /home/pi/.local/lib/python3.10/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-310-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8
```

**Attempt 2**
Taken from [here](https://stackoverflow.com/questions/70084134/undefined-symbol-atomic-exchange-8):

```
pip3 uninstall -y grpcio grpcio-tools
sudo apt install -y python3-grpcio python3-grpc-tools
```
No fix.

**Attempt 3**
Taken from [here](https://github.com/opencv/opencv/issues/15278#issuecomment-520893950):

No fix.

Any ideas on how to debug this issue? Would be cool to get my pi connected to my cluster :) Let me know if I missed any other important detail.

**Comment by fjetter** [comment]
You should ensure to ideally install the exact same versions on all your workers, the client and the scheduler.

It looks like this is about scipy and I don't really know much about this but I'm pretty confident that this is not related to distributed. My best guess is that you installed either a wrong scipy package which was not built for the CPU architecture of the Pi (ARM). I suggest trying to get `python -c "import scipy"` and/or `python -c "import numpy"` running in your environment first before trying to run distributed.

I suggest opening an issue with scipy.

**Comment by windowshopr** [comment]
Thanks! Yeah scipy is likely the issue, and you do need to build it from source so it tailors to the arm cpu, which I’ve done following that guide. Maybe the scipy versions don’t match between the scheduler and the pi? And maybe they won’t, if I can’t get the same version onto the pi? 

I’ll open an issue with scipy, however figured I’d start here as technically it IS an issue with getting distributed installed on the pi, but I’ll close this for now, and if I get an answer from scipy, I’ll link the answer here.

**Comment by windowshopr** [comment]
Well, sort of good news!

It was a scipy version mismatch issue. I needed to install version 1.8.1 onto the pi to match the scheduler.

I downloaded the appropriate wheel file from [here](https://www.piwheels.org/simple/scipy/) and pip installed it. Now it starts running, for a while, but then I'm greeted with a new distributed error on the Pi:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/core.py", line 769, in _handle_comm
    result = await result
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/worker.py", line 1695, in get_data
    assert response == "OK", response
AssertionError: {'op': 'get_data', 'keys': {"('pipeline-d3232d90bb3a62a76641728039ef6288', 0, 2)", "('pipeline-e46422431a593a9118b7a38349211552', 0, 1)", "('pipeline-d3232d90bb3a62a76641728039ef6288', 0, 1)", "('variancethreshold-transform-a001e1f2ca47e8b1bfbe7809f84b7346', 0, 2)", "('variancethreshold-transform-a001e1f2ca47e8b1bfbe7809f84b7346', 0, 0)"}, 'who': 'tcp://172.16.1.113:6508', 'max_connections': None, 'reply': True}
```

To clarify, I'm trying to run a TPOT run on my Dask cluster. I have my main machine (which acts as the scheduler and a worker), a second windows machine, and this Pi all connected and "running", but the pi gives me this issue. What does this error mean? Not enough wait time for the result?

**Comment by windowshopr** [comment]
I DISCOVERED THE CULPRIT! NUMBA!!!

Version mismatch. To fix, I ran these commands:

```
sudo apt install llvm-11-dev
sudo ln -s /usr/bin/llvm-config-11 /usr/bin/llvm-config
pip install numba==0.55.2
```

Re-ran the run, and works with no errors!
