### ISSUE TITLE
AssertionError: {'op': 'get_data', 'keys':

### ISSUE THREAD

**Issue by windowshopr** [dask/distributed#6834]
I spoke a bit too soon near the end of my [last issue](https://github.com/dask/distributed/issues/6824#issue-1328021125).

I am trying to get my R Pi 4 (Bullseye 11) to run `distributed` with TPOT and Dask. Every worker has the same dependency versions as the scheduler (and each other) now. 

The Pi is used and runs the TPOT training successfully for a few minutes (random), and then eventually fails with an error that looks like this:

```
2022-08-04 19:45:39,055 - distributed.core - ERROR - Exception while handling op get_data
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/core.py", line 769, in _handle_comm
    result = await result
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/worker.py", line 1695, in get_data
    assert response == "OK", response
AssertionError: {'op': 'get_data', 'keys': {"('pipeline-969e733fa25db8678a6ca6efe0ffd609', 0, 1)", "('pipeline-969e733fa25db8678a6ca6efe0ffd609', 0, 3)"}, 'who': 'tcp://172.16.1.113:11411', 'max_connections': None, 'reply': True}
```

Whenever this happens, the entire dask schedule is halted, and no workers progress, until I `CTRL + C` the RPi4 worker to remove it from the scheduler, and then all machines start working again.

I start the RPi4 worker with the command:

```
dask-worker tcp://172.16.1.113:8786 --nprocs 1 --nthreads 1 --memory-limit "1GB"
```

I keep it at 1 thread instead of the 4 available on the device for now to keep a clean output in my SSH window.

When I re-connect the RPi4 to the scheduler, it works again for a few seconds/minutes, then halts again with similar tracebacks, but they seem to be different each time, in that the `keys`/`values` reflect different TPOT pipelines, however it's all part of the `get_data` `AssertionError` being thrown by distributed. Here are some other tracebacks in case they're relevant for debugging:

```
2022-08-04 19:48:39,446 - distributed.core - ERROR - Exception while handling op get_data
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/core.py", line 769, in _handle_comm
    result = await result
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/worker.py", line 1695, in get_data
    assert response == "OK", response
AssertionError: {'op': 'get_data', 'keys': {"('stackingestimator-fit-d30e1244a41f30325acd9dffcb7510a3', 0, 1)", "('stackingestimator-fit-6663ee2377b45ca1fe278aee195e4e57', 0, 3)"}, 'who': 'tcp://172.16.1.113:11411', 'max_connections': None, 'reply': True}
```

```
2022-08-04 19:48:41,153 - distributed.core - ERROR - Exception while handling op get_data
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/core.py", line 769, in _handle_comm
    result = await result
  File "/home/pi/.local/lib/python3.10/site-packages/distributed/worker.py", line 1695, in get_data
    assert response == "OK", response
AssertionError: {'op': 'get_data', 'keys': {"('pipeline-9ecb2b5dbf4c44516a9badce3e80c18e', 0, 1)", "('pipeline-9ecb2b5dbf4c44516a9badce3e80c18e', 0, 4)", "('pipeline-9ecb2b5dbf4c44516a9badce3e80c18e', 0, 3)"}, 'who': 'tcp://172.16.1.82:50704', 'max_connections': None, 'reply': True}
```

When I look in the output of the Client, I see warnings from distributed after I `CTRL+C` out of the RPi4:

![image](https://user-images.githubusercontent.com/40477419/182984522-c4634cee-a1a5-4727-8898-68d0eb0b5198.png)

What could this be? Is it a memory issue? I'm assuming no as I only designate 1GB per worker out of the 8 available on the device.

Is it a timeout issue? Should I increase timeout values in the `.yaml` file somewhere?

Something else?

**Comment by windowshopr** [comment]
Update

I have since re-installed dask/distributed from source (not pip) on the Rpi4b and it seems to be performing much better. Will need to run it for a while to be sure, but might be fixed!
