### ISSUE TITLE
`KeyError` in `ProfileTimePlot.update`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#6876]
```
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]: 2022-08-11 09:49:57,015 - bokeh.core.property.validation - ERROR - 'start'
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]: Traceback (most recent call last):
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/distributed/utils.py", line 805, in wrapper
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return func(*args, **kwargs)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/distributed/dashboard/components/shared.py", line 295, in update
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     ts = metadata["keys"][self.key]
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]: KeyError: 'start'
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]: 2022-08-11 09:49:57,015 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f455b4cd0c0>>, <Task finished name='Task-5714' coro=<ServerSession.with_document_locked() done, defined at /opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/server/session.py:78> exception=KeyError('start')>)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]: Traceback (most recent call last):
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/tornado/ioloop.py", line 741, in _run_callback
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     ret = callback()
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     future.result()
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/server/session.py", line 95, in _needs_document_lock_wrapper
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     result = func(self, *args, **kwargs)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/server/session.py", line 229, in with_document_locked
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return func(*args, **kwargs)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 450, in wrapper
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return invoke_with_curdoc(doc, invoke)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return f()
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 449, in invoke
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return f(*args, **kwargs)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 179, in remove_then_invoke
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return callback()
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/distributed/dashboard/components/shared.py", line 316, in <lambda>
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     self.doc().add_next_tick_callback(lambda: self.update(prof, metadata))
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/bokeh/core/property/validation.py", line 95, in func
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return input_function(*args, **kwargs)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/distributed/utils.py", line 805, in wrapper
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     return func(*args, **kwargs)
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:   File "/opt/conda/envs/coiled/lib/python3.10/site-packages/distributed/dashboard/components/shared.py", line 295, in update
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]:     ts = metadata["keys"][self.key]
Aug 11 09:49:57 ip-10-0-12-62 cloud-init[1268]: KeyError: 'start'
```
(https://cloud.coiled.io/dask-engineering/clusters/48635/details)

**Comment by bilzard** [comment]
I have the same error on 

```
distributed==2022.5.1
bokeh==2.4.1
```

**Comment by bilzard** [comment]
In my situation, updating distributed and installing dask_cuda solved the issue.

```
!pip install dask-cuda==22.12.0 distributed==2022.11.1
```

**Comment by jrbourbeau** [comment]
Thanks for reporting @bilzard. Looks like https://github.com/dask/distributed/issues/5880 may also be related?

> distributed

Sounds like more recent versions of `distributed` may have resolved this issue. If folks have a reproducer that we could use to confirm, that would be much appreciated. Otherwise, I'm inclined to close unless someone else encounters this issue again

**Comment by bilzard** [comment]
@jrbourbeau I can't exactly tell if it is completely unrelated, but I think it isn't, since I don't touch any of the UIs on the dask's dashboard.

**Comment by jrbourbeau** [comment]
Fair enough, I just saw they had similar tracebacks -- you're right that that doesn't necessarily mean they have the same root cause. By chance, do you have an example code snippet we could use to reproduce the issue? 

Also, @hendrikmakait have you seen this issue recently with more recent versions of `distributed`?

**Comment by bilzard** [comment]
> In my situation, updating distributed and installing dask_cuda solved the issue.
> I don't touch any of the UIs on the dask's dashboard.

Sorry, these are not correct in fact.
I reproduced in `distributed==2022.11.1`.
The error occurs when touching empty task stream.
When I touched the any part of task stream graph, the browser automatically opens `http://localhost:8787/profile?key=start` in the new tab, and the error message shared below were dumped on the jupyter notebook.

<img width="1243" alt="Screen Shot 2022-12-22 at 9 42 53" src="https://user-images.githubusercontent.com/36561962/209030948-5b71b7e6-bde3-4f69-8618-7c11a6e6154d.png">

Error message on the server.
```
2022-12-22 00:48:08,811 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fc98397c5e0>>, <Task finished name='Task-1810' coro=<ServerSession.with_document_locked() done, defined at /usr/local/lib/python3.8/dist-packages/bokeh/server/session.py:78> exception=KeyError('start')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.8/dist-packages/bokeh/server/session.py", line 95, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bokeh/server/session.py", line 229, in with_document_locked
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bokeh/document/callbacks.py", line 450, in wrapper
    return invoke_with_curdoc(doc, invoke)
  File "/usr/local/lib/python3.8/dist-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/usr/local/lib/python3.8/dist-packages/bokeh/document/callbacks.py", line 449, in invoke
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bokeh/document/callbacks.py", line 179, in remove_then_invoke
    return callback()
  File "/usr/local/lib/python3.8/dist-packages/distributed/dashboard/components/shared.py", line 315, in <lambda>
    self.doc().add_next_tick_callback(lambda: self.update(prof, metadata))
  File "/usr/local/lib/python3.8/dist-packages/bokeh/core/property/validation.py", line 95, in func
    return input_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/distributed/utils.py", line 748, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/distributed/dashboard/components/shared.py", line 294, in update
    ts = metadata["keys"][self.key]
KeyError: 'start'
```

**Comment by bilzard** [comment]
> do you have an example code snippet we could use to reproduce the issue

I can't share the full code because of the confidentiality, however, the main process is like that:

```python
train_ds = Dataset(train.to_pandas())
wf = Workflow(feature_cols + target)
train_processed = wf.fit_transform(train_ds)
ranker = XGBoost(train_processed.schema, objective="rank:pairwise")
with Distributed():
    ranker.fit(train_processed)
```

It seems just the UI bug, because the main process didn't failed after this error message.

**Comment by jrbourbeau** [comment]
Thanks @bilzard, that's helpful. I'm able with to reproduce with the current `main` branch of `distributed` if I just create a `LocalCluster`, then navigate to the dashboard, and click on the empty task stream plot. @hendrikmakait do you have bandwidth to look into this one?

**Comment by mrocklin** [comment]
The task stream plot has an empty glyph on it named start when first
starting.  This was due to a historical bug in Bokeh.

When you click on a rectangle in the task stream plot it brings up the
profile plot keyed to all profile history of tasks with that name.  When
you've first started up the scheduler without any tasks run the
profile will be empty.

Probably we shouldn't err here, but should present an empty profile plot.
In practice though, this isn't that big of an issue.  It's a bit awkward
that this situation exists, but it's entirely artificial.
