### ISSUE TITLE
Dask Scheduler is losing the context of annotations

### ISSUE THREAD

**Issue by averri** [dask/distributed#6930]
**What happened**:

The Dask Scheduler is losing the context of annotations, mixing annotations from different client submissions. The best way to describe this is to show an example, so please find the code and explanations below.

**What you expected to happen**:
It's expected that the Dask Scheduler respect the annotations, each task should have the annotations created for them.

**Minimal Complete Verifiable Example**:

Scheduler code, `scheduler.py`:

```python
import asyncio

from dask.distributed import Scheduler
from distributed.diagnostics.plugin import SchedulerPlugin
from distributed.scheduler import TaskState


class PrintTransitionsPlugin(SchedulerPlugin):

    def __init__(self, scheduler: Scheduler):
        self.scheduler = scheduler

    def transition(self, key, start, finish, *args, **kwargs):
        task: TaskState = self.scheduler.tasks[key]
        print(f"Transition: {key}, start: {start}, finish: {finish}, annotations: {task.annotations}")


async def scheduler_code(port=8888, host="0.0.0.0"):
    scheduler = Scheduler(port=port, host=host)
    scheduler.add_plugin(PrintTransitionsPlugin(scheduler))
    scheduler = await scheduler
    await scheduler.finished()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(scheduler_code())
```

Worker code, `worker.py`:

```python
import asyncio

from dask.distributed import Worker

async def worker_code(scheduler_address: str):
    worker = await Worker(scheduler_address)
    await worker.finished()

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(worker_code("tcp://127.0.0.1:8888"))

```

The client code, `client.py`:

```python
import time
from concurrent.futures import ThreadPoolExecutor

from dask import annotate
from distributed import Client, get_client


def get_task_key():
    from distributed.worker import thread_state
    return thread_state.key


def get_annotations():
    try:
        task_key = get_task_key()

        def get_annotations_remote(dask_scheduler):
            nonlocal task_key
            return dask_scheduler.tasks[task_key].annotations

        return get_client().run_on_scheduler(get_annotations_remote)

    except Exception as e:
        print(f"Error whe getting the task state. {str(e)}")
        return "<?>"


def task(x: int):
    print(f"Running task {x}, key={get_task_key()}, annotations={get_annotations()}")
    time.sleep(1)
    return x + 1


def send_task(x: int):
    with Client("localhost:8888") as cli:
        # The request_id and task_key have the same number
        request_id = f"req-{x}"
        task_key = f"task-{x}"
        with annotate(request_id=request_id):
            print(f"Submitting task {task_key}, request_id={request_id}")
            f = cli.submit(task, x, pure=False, key=task_key)
            f.result()


if __name__ == '__main__':
    with ThreadPoolExecutor() as exe:
        for i in range(10):
            exe.submit(send_task, i)

```

Having all the 3 files created, start the scheduler, the worker, and then the client code.  The client will submit 10 tasks at the same time, each task has an annotation named `request_id` with the same number as the `task_key`, just to make it easy to show the issue. 

This is the client's logs:

```
Submitting task task-1, request_id=req-1
Submitting task task-9, request_id=req-9
Submitting task task-0, request_id=req-0
Submitting task task-5, request_id=req-5
Submitting task task-4, request_id=req-4
Submitting task task-7, request_id=req-7
Submitting task task-3, request_id=req-3
Submitting task task-2, request_id=req-2
Submitting task task-6, request_id=req-6
Submitting task task-8, request_id=req-8
```

As designed, each task has the same number as the request_id annotation.

Now, please see the notable portion of the worker's log:

```
Running task 2, key=task-2, annotations={'request_id': 'req-8'}
Running task 8, key=task-8, annotations={'request_id': 'req-8'}
Running task 6, key=task-6, annotations={'request_id': 'req-8'}
Running task 3, key=task-3, annotations={'request_id': 'req-8'}
Running task 4, key=task-4, annotations={'request_id': 'req-3'}
Running task 9, key=task-9, annotations={'request_id': 'req-9'}
Running task 5, key=task-5, annotations={'request_id': 'req-4'}
Running task 0, key=task-0, annotations={'request_id': 'req-5'}
Running task 7, key=task-7, annotations={'request_id': 'req-7'}
Running task 1, key=task-1, annotations={'request_id': 'req-9'}
```

The **task 2** has the wrong annotation, it should have the annotation `{'request_id': 'req-2'}`. The same situation happens with many other tasks.

**Anything else we need to know?**:
Please notice that the reported issue happens when the Dask Scheduler receives multiple client submissions with annotations at the same time. 

**Environment**:

- Dask version: dask[complete]~=2022.7.1
- Python version: 3.10.4
- Operating System: Windows 11
- Install method (conda, pip, source): pip

**Comment by pavithraes** [comment]
@averri Thanks for the question!

I looked at this with @ian-r-rose, and we think this behavior is to be expected. Annotations are set and read using Dask's config system, which is not thread-safe. So, while using the `ThreadPoolExecuted`, we run into an issue with the global state. The pool shares the same global config system. 

Minimal example:

```python
import random
import time
from concurrent.futures import ThreadPoolExecutor

import dask


def do_thing(x):
    with dask.annotate(value=x):
        time.sleep(random.random() / 10.0)
        assert dask.config.get("annotations") == {"value": x}


executor = ThreadPoolExecutor(max_workers=10)

futs = []
for i in range(5):
    futs.append(executor.submit(do_thing, i))

futs
# Output:
#
# [<Future at 0x103cc2490 state=finished raised AssertionError>,
#  <Future at 0x103cb5c10 state=finished returned NoneType>,
#  <Future at 0x103cb5760 state=finished returned NoneType>,
#  <Future at 0x108222460 state=finished raised AssertionError>,
#  <Future at 0x108253040 state=finished raised AssertionError>]
```

However, if you use a `ProcessPoolExecuter` this will work, because each process gets its own config system.

If this helps answer your question, please feel free to close this issue. :)

**Comment by averri** [comment]
Hi @pavithraes, thanks for the information. I think `dask.annotate` should be thread-safe, otherwise, it cannot be used for dispatching workloads to Dask from web frameworks. 

I tried to run another variation of the client code using `ProcessPoolExecutor`, but it's getting a serialization error:

```python
import time
import random
from concurrent.futures import ProcessPoolExecutor
from dask import annotate
from distributed import Client, get_client


def get_task_key():
    from distributed.worker import thread_state
    return thread_state.key


def get_key_and_annotations():
    try:
        task_key = get_task_key()

        def get_annotations_remote(dask_scheduler):
            nonlocal task_key
            return dask_scheduler.tasks[task_key].annotations

        return task_key, get_client().run_on_scheduler(get_annotations_remote)

    except Exception as e:
        print(f"Error whe getting the task state. {str(e)}")
        return "<?>"


def task(x: int):
    print(f"Running task {x}, {get_key_and_annotations()}")
    time.sleep(random.randint(0, 1))
    return x + 1


def send_task(x: int):
    with Client("localhost:8888") as cli:
        # The request_id and task_key have the same number
        request_id = f"req-{x}"
        task_key = f"task-{x}"
        with annotate(request_id=request_id):
            print(f"Submitting task {task_key}, request_id={request_id}")
            f = cli.submit(task, x, pure=False, key=task_key)
            f.result()


if __name__ == '__main__':
    with ProcessPoolExecutor() as exe:
        for i in range(10):
            exe.submit(send_task, i)
```

The following error is happening when running the code above (partial log showing the distinct information):

```
2022-08-23 11:13:47,884 - distributed.worker - ERROR - Could not deserialize task task-8
Traceback (most recent call last):
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\worker.py", line 2738, in loads_function
    result = cache_loads[bytes_object]
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\collections.py", line 23, in __getitem__
    value = super().__getitem__(key)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95\x18\x00\x00\x00\x00\x00\x00\x00\x8c\x0b__mp_main__\x94\x8c\x04task\x94\x93\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\worker.py", line 2155, in execute
    function, args, kwargs = await self._maybe_deserialize_task(ts)
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\worker.py", line 2125, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*ts.run_spec)
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\worker.py", line 2749, in _deserialize
    function = loads_function(function)
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\worker.py", line 2740, in loads_function
    result = pickle.loads(bytes_object)
  File "C:\dev\src\work\eng\distributed-sandbox\.venv\lib\site-packages\distributed\protocol\pickle.py", line 73, in loads
    return pickle.loads(x)
AttributeError: Can't get attribute 'task' on <module '__main__' from 'C:\\dev\\src\\work\\eng\\distributed-sandbox\\src\\dask\\examples\\scheduler_issue\\worker.py'>
```

**Comment by ian-r-rose** [comment]
Thanks for the update @averri. I don't want us to get too lost in the weeds on getting a `ProcessPoolExecutor` working with that example. Dask often doesn't doesn't play very nicely with other concurrency frameworks, and this case of annotations not being thread-safe is a good example.

Would it be fair to consider this issue a feature-request to make annotations-setting thread-safe?

**Comment by averri** [comment]
Hi @ian-r-rose, thanks for your reply. Sure thing. Let me close this one, and I'll open another issue with a feature request.
