### ISSUE TITLE
local_client not available within da.map_blocks function

### ISSUE THREAD

**Issue by vincentschut** [dask/distributed#702]
I'm trying to use local_client within a funtion that is run by da.map_blocks, however, that throws me an error.
I'm working with dask and distributed from git master, updated 1 hour ago.

Is this supposed to work anyway? It would save me a lot of trouble and allow to implement our satellite image processing chain in a very flexible way if this would work...

Simple self-containing example:

```
#!/usr/bin/python3

import numpy as np
import dask.array as da
from distributed import Client, local_client


def map_blocks_subtask(data):
    return data + 10

def map_blocks_launch_test(data, block_id):
    # return data + sum(block_id) # this was for testing if it works without spawning a subtask
    with local_client() as lc:
        f = lc.submit(map_blocks_subtask, data)
        r = f.result()
    return r

if __name__ == '__main__':
    client = Client()
    da_in = da.zeros((2,2), dtype=np.uint8, chunks=(1,1))
    da_out = da.map_blocks(map_blocks_launch_test, da_in)
    result = da_out.compute()
    print(result)
```

And this is the output:

```
distributed.worker - INFO -       Start worker at:       192.168.178.77:35847
distributed.worker - INFO -              nanny at:       192.168.178.77:35823
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                   33.55 GB
distributed.worker - INFO -       Local Directory:        /tmp/nanny-i67ghduz
distributed.worker - INFO - -------------------------------------------------

<-- cut 7 more of these, I run this on an 8-core machine -->

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dask/array/core.py", line 457, in apply_infer_dtype
    o = func(*args, **kwargs)
  File "/home/vincent/PycharmProjects/modis/modask/launch_tasks_from_tasks_001.py", line 25, in map_blocks_launch_test
    with local_client() as lc:
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.5/site-packages/distributed/worker_client.py", line 42, in local_client
    address = thread_state.execution_state['scheduler']
AttributeError: '_thread._local' object has no attribute 'execution_state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/PycharmProjects/modis/modask/launch_tasks_from_tasks_001.py", line 38, in <module>
    da_out = da.map_blocks(map_blocks_launch_test, da_in)
  File "/usr/lib/python3.5/site-packages/dask/array/core.py", line 629, in map_blocks
    dtype = apply_infer_dtype(func, args, kwargs2, 'map_blocks')
  File "/usr/lib/python3.5/site-packages/dask/array/core.py", line 470, in apply_infer_dtype
    raise ValueError(msg)
ValueError: `dtype` inference failed in `map_blocks`.

Original error is below:
------------------------
AttributeError("'_thread._local' object has no attribute 'execution_state'",)

Traceback:
---------
  File "/usr/lib/python3.5/site-packages/dask/array/core.py", line 457, in apply_infer_dtype
    o = func(*args, **kwargs)
  File "/home/vincent/PycharmProjects/modis/modask/launch_tasks_from_tasks_001.py", line 25, in map_blocks_launch_test
    with local_client() as lc:
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.5/site-packages/distributed/worker_client.py", line 42, in local_client
    address = thread_state.execution_state['scheduler']
```

**Comment by mrocklin** [comment]
Thanks for the easy-to-reproduce example.  This is great.

Your example works fine for me *if* I give `map_blocks` the expected dtype of the output:

```python
In [3]: result
Out[3]: 
array([[10, 10],
       [10, 10]], dtype=uint8)
```

If you don't give it the dtype of the output then it tries to run your function locally on a small bit of data to guess the dtype.  Given the somewhat advanced nature of your function this may have failed before.

**Comment by vincentschut** [comment]
Ah, that's good to know and a very workable workaround for us I think. Thanks for the fast response!

**Comment by mrocklin** [comment]
Fast responses are way easier to provide with reproducible examples that I can easily copy-paste to see the issue :)
