### ISSUE TITLE
`No dispatch for <class 'numpy.ndarray'>`

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#7061]
This deserialization error then caused https://github.com/dask/distributed/issues/7060:

```python-traceback
2022-09-23 19:01:53,760 - distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/distributed/protocol/core.py", line 158, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/usr/local/lib/python3.9/site-packages/distributed/protocol/core.py", line 138, in _decode_default
    return merge_and_deserialize(
  File "/usr/local/lib/python3.9/site-packages/distributed/protocol/serialize.py", line 497, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "/usr/local/lib/python3.9/site-packages/distributed/protocol/serialize.py", line 426, in deserialize
    return loads(header, frames)
  File "/usr/local/lib/python3.9/site-packages/distributed/protocol/serialize.py", line 58, in dask_loads
    loads = dask_deserialize.dispatch(typ)
  File "/usr/local/lib/python3.9/site-packages/dask/utils.py", line 632, in dispatch
    raise TypeError(f"No dispatch for {cls}")
TypeError: No dispatch for <class 'numpy.ndarray'>
```

AFAICT, NumPy was installed on the worker. There are plenty of other NumPy keys in memory on the same worker. So I'm not sure why this happened.

Unfortunately, I don't have more information here. Not sure how easily reproducible it is.

**Comment by jrbourbeau** [comment]
Just a shot in the dark, but maybe https://github.com/dask/dask/issues/9181 is related?

**Comment by gjoseph92** [comment]
I think it's likely that that's it. Thanks for the link!

Basically, sounds like our serialization registry isn't threadsafe. But we deserialize in threads. Though we do use a [threadpool of size 1](https://github.com/gjoseph92/distributed/blob/f8b84c08ac6a388324ec22731aa03961fb326153/distributed/utils.py#L1394), we sometimes [deserialize in the main thread](https://github.com/gjoseph92/distributed/blob/f8b84c08ac6a388324ec22731aa03961fb326153/distributed/comm/utils.py#L100) if the data is small enough. So a large and small NumPy array arriving at the same time would be deserialized concurrently from two threads.

**Comment by jrbourbeau** [comment]
Thanks @tasansal. I, or someone else around me, will look into this issue. It's been popping up in a few places.

**Comment by quasiben** [comment]
cc @jakirkham

**Comment by zklaus** [comment]
Just to comment that I have put a PR up at dask/dask#9544 that addresses the problem for me locally. It is a very rough draft, but I'd be interested to know if you think that general approach is worth pursuing.

**Comment by jakirkham** [comment]
Could others here please try PR ( https://github.com/dask/dask/pull/9545 ) and report back how that goes?
