### ISSUE TITLE
pickle error when using python3-style subclass with super().__init__()

### ISSUE THREAD

**Issue by vincentschut** [dask/distributed#708]
I have this base class which does all funky dask stuff, and a subclass inheriting from it. When I use super().__init__() in the subclass' __init__, I get a long backtrace on the final 'compute()'. Apparently it somehow triggers an endless loop while pickling, as the error boils down to "RecursionError: maximum recursion depth exceeded in comparison" and "_pickle.PicklingError: Could not pickle object as excessively deep recursion required.")
When I use an old-style BaseClass.__init__(self) in subclass.__init__, everything works.

Something to do with dask (distributed)? Or is this a cloudpickle limitation?

I'm using dask and distributed from git master, everything including dependencies freshly updated this morning (using "pip3 install --upgrade .", so the deps got updated by pip).

Here's a short reproducable example, with most of my funky stuff removed:

```
from dask.delayed import delayed, compute
import dask.array as da
from distributed import Client
import numpy as np
from pprint import pprint

class DaskInstanceTest():
    def __init__(self, inputs=[], parameters={}, name=None, cache=None):
        pass

    def get_chunk(self):
        d_result = delayed(self.mkarray)()
        return d_result

    def get_da(self):
        da0 = da.from_delayed(self.get_chunk(), shape=(2,2), dtype=float)
        return da0

    def mkarray(self):
        return np.ones((2,2), float)


class DaskInheritanceTest(DaskInstanceTest):
    def __init__(self):
        # this does not work, it gives a "RecursionError: maximum recursion depth exceeded in comparison" while
        # pickling ("_pickle.PicklingError: Could not pickle object as excessively deep recursion required.")
        super().__init__()
        # however, this old style super __init__ call works (comment "super().__init__()" and uncomment the next line):
        #DaskInstanceTest.__init__(self)


if __name__ == '__main__':
    c = Client()

    t2 = DaskInheritanceTest()
    da1 = t2.get_da()
    print(da1)
    a1 = da1.compute()
    print(a1)
```

The backtrace can be summarized by this:

```
(...)
File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 205, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 248, in save_function_tuple
    save((code, closure, base_globals))
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.5/pickle.py", line 770, in save_list
    self._batch_appends(obj)
  File "/usr/lib64/python3.5/pickle.py", line 797, in _batch_appends
    save(tmp[0])
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 368, in save_global
    self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 529, in save_reduce
    save(args)
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 205, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 248, in save_function_tuple
    save((code, closure, base_globals))
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/usr/lib64/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.5/pickle.py", line 769, in save_list
    self.memoize(obj)
  File "/usr/lib64/python3.5/pickle.py", line 431, in memoize
    self.write(self.put(idx))
  File "/usr/lib64/python3.5/pickle.py", line 436, in put
    if self.proto >= 4:
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/PycharmProjects/modis/modask/trial_delayed_002.py", line 198, in <module>
    a1 = da1.compute()
  File "/usr/lib/python3.5/site-packages/dask/base.py", line 78, in compute
    return compute(self, **kwargs)[0]
  File "/usr/lib/python3.5/site-packages/dask/base.py", line 178, in compute
    results = get(dsk, keys, **kwargs)
  File "/usr/lib/python3.5/site-packages/distributed/client.py", line 1358, in get
    restrictions, loose_restrictions, resources=resources)
  File "/usr/lib/python3.5/site-packages/distributed/client.py", line 1301, in _graph_to_futures
    'tasks': valmap(dumps_task, dsk3),
  File "/usr/lib/python3.5/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/usr/lib/python3.5/site-packages/distributed/worker.py", line 784, in dumps_task
    return {'function': dumps_function(task[0]),
  File "/usr/lib/python3.5/site-packages/distributed/worker.py", line 751, in dumps_function
    b = dumps(func)
  File "/usr/lib/python3.5/site-packages/distributed/protocol/pickle.py", line 48, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/usr/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 111, in dump
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
```

**Comment by mrocklin** [comment]
Dask depends on cloudpickle for funky-object serialization.  Can you check to see if your object can be cloudpickled?  If not then you'll either have to find a workaround or raise an issue with cloudpickle.

**Comment by vincentschut** [comment]
indeed simply calling cloudpickle.dumps(instance_of_subclass) already triggers the problem.
Currently the workaround is old-style super __init__ calling, which works OK because I do not (yet) need multiple inheritance and my inheritance model is quite simple.
Should I raise an issue with cloudpickle?

**Comment by mrocklin** [comment]
Perhaps.  A pull request would be better.  The code is pretty hackable and cloudpickle seems to be build by people like you with odd corner cases.  I don't think anyone is actively maintaining it except to ensure support for their projects (like Dask).

**Comment by vincentschut** [comment]
OK, thanks, I'll see what I can do. The workaround is good enough for me currently, it just took a lot of time to find the cause of the issue :-). So maybe I'll at least file an issue at cloudpickle to allow others to google it.
