### ISSUE TITLE
New 32-bit overflow errors in test_steal.py

### ISSUE THREAD

**Issue by bnavigator** [dask/distributed#7174]
**Describe the issue**:

The 32-bit test suite for openSUSE Tumbleweed has new consistently failing tests with overflow errors in test_steal.py:

<details>

```
[  907s] =================================== FAILURES ===================================
[  907s] _________________ test_do_not_steal_communication_heavy_tasks __________________
[  907s] 
[  907s] c = <Client: No scheduler connected>
[  907s] s = <Scheduler 'tcp://127.0.0.1:45301', workers: 0, cores: 0, tasks: 0>
[  907s] a = <Worker 'tcp://127.0.0.1:45957', name: 0, status: closed, stored: 0, running: 0/1, ready: 0, comm: 0, waiting: 0>
[  907s] b = <Worker 'tcp://127.0.0.1:35899', name: 1, status: closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>
[  907s] 
[  907s]     @gen_cluster(client=True)
[  907s]     async def test_do_not_steal_communication_heavy_tasks(c, s, a, b):
[  907s]         # Never steal unreasonably large tasks
[  907s]         steal = s.extensions["stealing"]
[  907s]         x = c.submit(gen_nbytes, int(s.bandwidth) * 1000, workers=a.address, pure=False)
[  907s]         y = c.submit(gen_nbytes, int(s.bandwidth) * 1000, workers=a.address, pure=False)
[  907s]     
[  907s]         def block_reduce(x, y, event):
[  907s]             event.wait()
[  907s]             return None
[  907s]     
[  907s]         event = Event()
[  907s]         futures = [
[  907s]             c.submit(
[  907s]                 block_reduce,
[  907s]                 x,
[  907s]                 y,
[  907s]                 event=event,
[  907s]                 pure=False,
[  907s]                 workers=a.address,
[  907s]                 allow_other_workers=True,
[  907s]             )
[  907s]             for i in range(10)
[  907s]         ]
[  907s]         while not a.state.tasks:
[  907s]             await asyncio.sleep(0.1)
[  907s]         steal.balance()
[  907s]         await steal.stop()
[  907s]         await event.set()
[  907s]         await c.gather(futures)
[  907s] >       assert not b.data
[  907s] E       AssertionError: assert not Buffer<<LRU: 2000032/20140427673 on dict>, <zict.cache.Cache object at 0xd5a30ce8>>
[  907s] E        +  where Buffer<<LRU: 2000032/20140427673 on dict>, <zict.cache.Cache object at 0xd5a30ce8>> = <Worker 'tcp://127.0.0.1:35899', name: 1, status: running, stored: 6, running: 0/2, ready: 0, comm: 0, waiting: 0>.data
[  907s] 
[  907s] distributed/tests/test_steal.py:825: AssertionError
...
[  907s] ----------------------------- Captured stderr call -----------------------------
[  907s] 2022-10-21 18:53:27,034 - distributed.sizeof - WARNING - Sizeof calculation failed. Defaulting to 0.95 MiB
[  907s] Traceback (most recent call last):
[  907s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.10.0/distributed/sizeof.py", line 17, in safe_sizeof
[  907s]     return sizeof(obj)
[  907s]   File "/usr/lib/python3.10/site-packages/dask/utils.py", line 640, in __call__
[  907s]     return meth(arg, *args, **kwargs)
[  907s]   File "/usr/lib/python3.10/site-packages/dask/sizeof.py", line 17, in sizeof_default
[  907s]     return sys.getsizeof(o)
[  907s] OverflowError: Python int too large to convert to C ssize_t
...
[  907s] _____________________ test_steal_communication_heavy_tasks _____________________
[  907s] 
[  907s] c = <Client: No scheduler connected>
[  907s] s = <Scheduler 'tcp://127.0.0.1:34793', workers: 0, cores: 0, tasks: 0>
[  907s] a = <Worker 'tcp://127.0.0.1:41787', name: 0, status: closed, stored: 0, running: 1/1, ready: 0, comm: 0, waiting: 0>
[  907s] b = <Worker 'tcp://127.0.0.1:36797', name: 1, status: closed, stored: 0, running: 0/2, ready: 0, comm: 0, waiting: 0>
[  907s] 
[  907s]     @gen_cluster(
[  907s]         client=True,
[  907s]         config={"distributed.scheduler.default-task-durations": {"blocked_add": 0.001}},
[  907s]     )
[  907s]     async def test_steal_communication_heavy_tasks(c, s, a, b):
...
[  907s]     async def test_steal_communication_heavy_tasks(c, s, a, b):
[  907s]         steal = s.extensions["stealing"]
[  907s]         await steal.stop()
[  907s]         x = c.submit(mul, b"0", int(s.bandwidth), workers=a.address)
[  907s]         y = c.submit(mul, b"1", int(s.bandwidth), workers=b.address)
[  907s]         event = Event()
[  907s]     
[  907s]         def blocked_add(x, y, event):
[  907s]             event.wait()
[  907s] >           return x + y
[  907s] E           MemoryError
[  907s] 
[  907s] distributed/tests/test_steal.py:841: MemoryError
...
[  907s] ----------------------------- Captured stderr call -----------------------------
[  907s] 2022-10-21 18:53:38,873 - distributed.worker - ERROR - failed during get data with tcp://127.0.0.1:39695 -> None
[  907s] Traceback (most recent call last):
[  907s]   File "/usr/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
[  907s]     bytes_read = self.read_from_fd(buf)
[  907s]   File "/usr/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
[  907s]     return self.socket.recv_into(buf, len(buf))
[  907s] ConnectionResetError: [Errno 104] Connection reset by peer
[  907s] 
[  907s] The above exception was the direct cause of the following exception:
[  907s] 
[  907s] Traceback (most recent call last):
[  907s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.10.0/distributed/worker.py", line 1750, in get_data
[  907s]     response = await comm.read(deserializers=serializers)
[  907s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.10.0/distributed/comm/tcp.py", line 241, in read
[  907s]     convert_stream_closed_error(self, e)
[  907s]   File "/home/abuild/rpmbuild/BUILD/distributed-2022.10.0/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
[  907s]     raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
[  907s] distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://127.0.0.1:39695 remote=tcp://127.0.0.1:59578>: ConnectionResetError: [Errno 104] Connection reset by peer
[  907s] --------------------------- Captured stderr teardown ---------------------------
[  907s] 2022-10-21 18:53:39,421 - distributed.utils_perf - WARNING - full garbage collections took 22% CPU time recently (threshold: 10%)
[  907s] ----------------------------- Captured stdout call -----------------------------
[  907s] Dumped cluster state to test_cluster_dump/test_steal_communication_heavy_tasks.yaml
[  907s] ----------------------------- Captured stderr call -----------------------------
[  907s] 2022-10-21 18:53:43,091 - distributed.worker - WARNING - Compute Failed
[  907s] Key:       blocked_add-dc27ff22-8d75-4a5d-8550-51bef79ca9e5
[  907s] Function:  blocked_add
[  907s] args:      (b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[  907s] kwargs:    {'event': <distributed.event.Event object at 0xd59e39e8>}
[  907s] Exception: 'MemoryError()'
[  907s] 
[  907s] 2022-10-21 18:53:43,609 - distributed.worker - WARNING - Compute Failed
[  907s] Key:       blocked_add-c635f89f-4da1-4735-8615-e2b79d1617d7
[  907s] Function:  blocked_add
[  907s] args:      (b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[  907s] kwargs:    {'event': <distributed.event.Event object at 0xd6794aa8>}
[  907s] Exception: 'MemoryError()'
[  907s] 
[  907s] 2022-10-21 18:53:43,658 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:36255'.
[  907s] 2022-10-21 18:53:43,660 - distributed.worker - ERROR - Scheduler was unaware of this worker 'tcp://127.0.0.1:36255'. Shutting down.
[  907s] ----------------------------- Captured stdout call -----------------------------
[  907s] Dumped cluster state to test_cluster_dump/test_steal_communication_heavy_tasks.yaml
[  907s] ----------------------------- Captured stderr call -----------------------------
[  907s] 2022-10-21 18:53:47,451 - distributed.worker - WARNING - Compute Failed
[  907s] Key:       blocked_add-19fe75f4-adeb-4055-902b-0a591780cecb
[  907s] Function:  blocked_add
[  907s] args:      (b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[  907s] kwargs:    {'event': <distributed.event.Event object at 0xd63fa718>}
[  907s] Exception: 'MemoryError()'
[  907s] 
[  907s] 2022-10-21 18:53:47,947 - distributed.worker - WARNING - Compute Failed
[  907s] Key:       blocked_add-5c69ccf6-5a13-457e-8f1a-d94be4e602ed
[  907s] Function:  blocked_add
[  907s] args:      (b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[  907s] kwargs:    {'event': <distributed.event.Event object at 0xd5d21520>}
[  907s] Exception: 'MemoryError()'
[  907s] 
[  907s] ----------------------------- Captured stdout call -----------------------------
[  907s] Dumped cluster state to test_cluster_dump/test_steal_communication_heavy_tasks.yaml
[  907s] ----------------------------- Captured stderr call -----------------------------
[  907s] 2022-10-21 18:53:51,224 - distributed.utils_perf - WARNING - full garbage collections took 19% CPU time recently (threshold: 10%)
[  907s] 2022-10-21 18:53:51,909 - distributed.worker - WARNING - Compute Failed
[  907s] Key:       blocked_add-d2eafe6b-e031-4526-844e-1c439dc62cfd
[  907s] Function:  blocked_add
[  907s] args:      (b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[  907s] kwargs:    {'event': <distributed.event.Event object at 0xd572ae80>}
[  907s] Exception: 'MemoryError()'
[  907s] 
[  907s] 2022-10-21 18:53:52,436 - distributed.worker - WARNING - Compute Failed
[  907s] Key:       blocked_add-73f438c8-504b-40f2-90bc-e30895a50df8
[  907s] Function:  blocked_add
[  907s] args:      (b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[  907s] kwargs:    {'event': <distributed.event.Event object at 0xd5aab868>}
[  907s] Exception: 'MemoryError()'
[  907s] 
[  907s] 2022-10-21 18:53:52,483 - distributed.scheduler - WARNING - Received heartbeat from unregistered worker 'tcp://127.0.0.1:36797'.
[  907s] 2022-10-21 18:53:52,485 - distributed.worker - ERROR - Scheduler was unaware of this worker 'tcp://127.0.0.1:36797'. Shutting down.
[  907s] --------------------------- Captured stderr teardown ---------------------------
[  907s] 2022-10-21 18:53:39,421 - distributed.utils_perf - WARNING - full garbage collections took 22% CPU time recently (threshold: 10%)

```

</details>

**Minimal Complete Verifiable Example**:

```shell
docker run -it --platform linux/386 opensuse/tumbleweed
```

```shell
zypper in tar gzip wget python310-pip python310-numpy python310-pytest python310-pytest-timeout
pip install 'dask[distributed]==2022.10.0'
wget https://github.com/dask/distributed/archive/refs/tags/2022.10.0.tar.gz
tar xf 2022.10.0.tar.gz 
cd distributed-2022.10.0/
pytest distributed/tests/test_steal.py -k heavy
```

**Environment**:

- Dask version: 2022.10.0
- Python version: 3.10.7
- Operating System: openSUSE Tumbleweed "i586"
- Install method (conda, pip, source): source/rpm OR pip

**Comment by bnavigator** [comment]
test no longer exists (#7269)
