### ISSUE TITLE
BUG: crashing the scheduler

### ISSUE THREAD

**Issue by jreback** [dask/distributed#721]
```
In [1]: import distributed
   ...: import dask
   ...: import pandas
   ...: for m in [distributed, dask, pandas]:
   ...:     print("{} -> {}".format(getattr(m, '__name__'), getattr(m, '__version__')))
   ...:
   ...: from distributed import LocalCluster, Client
   ...: import dask.dataframe as dd
   ...:
   ...: c = LocalCluster(nanny=False)
   ...: client = Client(c)
   ...:
   ...: df = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'])
   ...: df.iloc[3:5, 0] = np.nan
   ...: df.iloc[4:6, 1] = np.nan
   ...: df.iloc[5:8, 2] = np.nan
   ...:
   ...: ddf = dd.from_pandas(df, npartitions=4)
   ...: ddf = client.persist(ddf)
   ...: ddf
   ...:
distributed -> 1.14.3
dask -> 0.12.0+42.g0d677ef
pandas -> 0.19.0+149.gac360e9
Out[1]: dd.DataFrame<from_pa..., npartitions=3, divisions=(0, 3, 6, 9)>

In [3]: ddf = ddf.assign(A=ddf['A'].fillna(ddf['B']))
   ...:    ...: ddf = client.persist(ddf)
   ...:    ...: ddf
   ...:
Out[3]: dd.DataFrame<assign-..., npartitions=3, divisions=(0, 3, 6, 9)>

In [4]: ddf.compute()
distributed.client - WARNING - Couldn't gather keys ["('getitem-a3cf210882fa9642f8487360c1f57c6f', 2)", "('getitem-a3cf210882fa9642f8487360c1f57c6f', 1)", "('getitem-a3cf210882fa9642f8487360c1f57c6f', 0)"]
distributed.client - WARNING - Couldn't gather keys ["('getitem-a3cf210882fa9642f8487360c1f57c6f', 2)", "('getitem-a3cf210882fa9642f8487360c1f57c6f', 1)", "('getitem-a3cf210882fa9642f8487360c1f57c6f', 0)"]
distributed.utils - ERROR - maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\dev\distributed\distributed\utils.py", line 130, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "C:\Anaconda\envs\dev\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Anaconda\envs\dev\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Anaconda\envs\dev\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\dev\distributed\distributed\client.py", line 867, in _gather
    st.traceback)
  File "C:\Anaconda\envs\dev\lib\site-packages\six.py", line 659, in reraise
    raise value
RecursionError: maximum recursion depth exceeded
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-4-7320bf6bd4b9> in <module>()
----> 1 ddf.compute()

C:\Anaconda\envs\dev\lib\site-packages\dask-0.12.0+42.g0d677ef-py3.5.egg\dask\base.py in compute(self, **kwargs)
     76             Extra keywords to forward to the scheduler ``get`` function.
     77         """
---> 78         return compute(self, **kwargs)[0]
     79
     80     @classmethod

C:\Anaconda\envs\dev\lib\site-packages\dask-0.12.0+42.g0d677ef-py3.5.egg\dask\base.py in compute(*args, **kwargs)
    176         dsk = merge(var.dask for var in variables)
    177     keys = [var._keys() for var in variables]
--> 178     results = get(dsk, keys, **kwargs)
    179
    180     results_iter = iter(results)

C:\dev\distributed\distributed\client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, **kwargs)
   1359
   1360         try:
-> 1361             results = self.gather(futures)
   1362         except (KeyboardInterrupt, Exception) as e:
   1363             for f in futures.values():

C:\dev\distributed\distributed\client.py in gather(self, futures, errors, maxsize)
    946             return (self.gather(f, errors=errors) for f in futures)
    947         else:
--> 948             return sync(self.loop, self._gather, futures, errors=errors)
    949
    950     @gen.coroutine

C:\dev\distributed\distributed\utils.py in sync(loop, func, *args, **kwargs)
    142         e.wait(1000000)
    143     if error[0]:
--> 144         six.reraise(type(error[0]), error[0], traceback[0])
    145     else:
    146         return result[0]

C:\Anaconda\envs\dev\lib\site-packages\six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660
    661 else:

C:\dev\distributed\distributed\utils.py in f()
    128     def f():
    129         try:
--> 130             result[0] = yield gen.maybe_future(func(*args, **kwargs))
    131         except Exception as exc:
    132             logger.exception(exc)

C:\Anaconda\envs\dev\lib\site-packages\tornado\gen.py in run(self)
   1013
   1014                     try:
-> 1015                         value = future.result()
   1016                     except Exception:
   1017                         self.had_exception = True

C:\Anaconda\envs\dev\lib\site-packages\tornado\concurrent.py in result(self, timeout)
    235             return self._result
    236         if self._exc_info is not None:
--> 237             raise_exc_info(self._exc_info)
    238         self._check_done()
    239         return self._result

C:\Anaconda\envs\dev\lib\site-packages\tornado\util.py in raise_exc_info(exc_info)

C:\Anaconda\envs\dev\lib\site-packages\tornado\gen.py in run(self)
   1019
   1020                     if exc_info is not None:
-> 1021                         yielded = self.gen.throw(*exc_info)
   1022                         exc_info = None
   1023                     else:

C:\dev\distributed\distributed\client.py in _gather(self, futures, errors)
    865                             six.reraise(type(st.exception),
    866                                         st.exception,
--> 867                                         st.traceback)
    868                         except KeyError:
    869                             six.reraise(CancelledError,

C:\Anaconda\envs\dev\lib\site-packages\six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660
    661 else:

RecursionError: maximum recursion depth exceeded
```

**Comment by jreback** [comment]
on windows; this performs the same on distributed 0.14.3. as well.

**Comment by mrocklin** [comment]
I'm unable to reproduce on linux.  Do you happen to have logs?  You can probably achieve this through

    LocalCluster(..., silence_logs=False)

**Comment by jreback** [comment]
```
distributed.scheduler - INFO -   Scheduler at:            127.0.0.1:8786
distributed.scheduler - INFO -        http at:            127.0.0.1:52700
distributed.worker - INFO -       Start worker at:            10.6.4.86:52817
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         16
distributed.worker - INFO -                Memory:                   41.20 GB
distributed.worker - INFO -       Local Directory: C:\Users\jreback\AppData\Local\Temp\worker-7w1tcs84
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Connection from 127.0.0.1:52835 to Scheduler
distributed.scheduler - INFO - Register 10.6.4.86:52817
distributed.core - INFO - Connection from 10.6.4.86:52838 to Worker
distributed.worker - INFO -         Registered to:            127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, 10.6.4.86:52817
distributed.core - INFO - Connection from 127.0.0.1:53066 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:53345 to Scheduler
distributed.scheduler - INFO - Receive client connection: 02eeb902-bb20-11e6-88eb-3417eba1702c
Out[1]: dd.DataFrame<from_pa..., npartitions=3, divisions=(0, 3, 6, 9)>
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-3a814ec1b109002723d425d3d3665ecc', 2)
.....

this is repeating ad-infiinitum
```

**Comment by mrocklin** [comment]
Are you on master (as of an hour ago) https://github.com/dask/distributed/pull/717

**Comment by mrocklin** [comment]
Also, FYI, the scheduler and worker are undergoing heavy churn right now

**Comment by jreback** [comment]
just pulled

```
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.core - INFO - Connection from 10.6.4.86:59750 to Worker
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.core - INFO - Connection from 10.6.4.86:59761 to Worker
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.core - INFO - Connection from 10.6.4.86:59952 to Worker
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.core - INFO - Connection from 10.6.4.86:60151 to Worker
distributed.core - INFO - Connection from 10.6.4.86:60236 to Worker
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.core - INFO - Connection from 10.6.4.86:60411 to Worker
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 2)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 1)
distributed.worker - INFO - Asked to compute prexisting result: ('getitem-28d587553693dcaa7800d4df85c3f3bb', 0)
distributed.core - INFO - Connection from 10.6.4.86:60654 to Worker
distributed.worker - WARNING -  Compute Failed
Function: apply_and_enforce
args:     (<methodcaller: fillna>, [3        NaN
4        NaN
5   -1.42979
Name: A, dtype: float64], {'axis': 0, 'method': None, 'limit': None, 'value': dd.Series<getitem..., npartitions=3, divisions=(0, 3, 6, 9)>}, Series([], Name: A, dtype: float64))
kwargs:   {}
NoneType
distributed.core - INFO - Connection from 10.6.4.86:60821 to Worker
```

**Comment by jreback** [comment]
this was happening in 0.14.3 though

**Comment by jreback** [comment]
in 1.14.3

```
distributed.scheduler - INFO -   Scheduler at:            127.0.0.1:8786
distributed.scheduler - INFO -        http at:            127.0.0.1:61328
distributed.worker - INFO -       Start worker at:            10.6.4.86:61342
distributed.worker - INFO - Waiting to connect to:            127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         16
distributed.worker - INFO -                Memory:                   41.20 GB
distributed.worker - INFO -       Local Directory: C:\Users\jreback\AppData\Local\Temp\worker-hhmytq_9
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Connection from 127.0.0.1:61541 to Scheduler
distributed.scheduler - INFO - Register 10.6.4.86:61342
distributed.core - INFO - Connection from 10.6.4.86:62718 to Worker
distributed.worker - INFO -         Registered to:            127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Starting worker compute stream, 10.6.4.86:61342
distributed.core - INFO - Connection from 127.0.0.1:63467 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:63787 to Scheduler
distributed.scheduler - INFO - Receive client connection: 1bd439e4-bb21-11e6-a9b0-3417eba1702c
Out[10]: dd.DataFrame<assign-..., npartitions=3, divisions=(0, 3, 6, 9)>

In [11]: distributed.core - INFO - Connection from 10.6.4.86:64129 to Worker
distributed.core - INFO - Connection from 127.0.0.1:63819 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:64148 to Scheduler
distributed.core - INFO - Connection from 10.6.4.86:64268 to Worker
distributed.core - INFO - Connection from 10.6.4.86:64363 to Worker
distributed.worker - INFO - Deleted 7 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.core - INFO - Connection from 127.0.0.1:65074 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:65355 to Scheduler
distributed.core - INFO - Connection from 127.0.0.1:65454 to Scheduler
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
distributed.worker - INFO - Deleted 3 keys
```

**Comment by mrocklin** [comment]
The logs in 1.14.3 seem reasonable to me.  Does it not terminate there as well?

`Asked to compute pre-existing result` is a known issue.  It shouldn't be interfering with actual execution though.  

This issue:

```python
Function: apply_and_enforce
args:     (<methodcaller: fillna>, [3        NaN
4        NaN
5   -1.42979
Name: A, dtype: float64], {'axis': 0, 'method': None, 'limit': None, 'value': dd.Series<getitem..., npartitions=3, divisions=(0, 3, 6, 9)>}, Series([], Name: A, dtype: float64))
kwargs:   {}
```

Looks like it might be a dask.dataframe issue.  Does this persist also with the threaded or single-core scheduler?  `foo.compute(get=dask.get)`

On master does it hang or just have those logs?

**Comment by jreback** [comment]
hangs on both (using distributed).

*seems* naively, that it is repeatedly trying to delete keys?

**Comment by jreback** [comment]
The reason I brought this up. Is that this actually crashes our scheduler  and hangs the (remote linux machines). (this is a repro of this)

**Comment by mrocklin** [comment]
Apologies for the delay.  It looks like dask.dataframe.Series.fillna doesn't currently accept other Series objects as inputs for the fill value.

**Comment by quasiben** [comment]
Happy to say this is no longer an issue:

```python
In [2]: import pandas as pd

In [3]: import numpy as np

In [4]: In [1]: import distributed
   ...:    ...: import dask
   ...:    ...: import pandas
   ...:    ...: for m in [distributed, dask, pandas]:
   ...:    ...:     print("{} -> {}".format(getattr(m, '__name__'), getattr(m, '__version__')))
   ...:    ...:
   ...:    ...: from distributed import LocalCluster, Client
   ...:    ...: import dask.dataframe as dd
   ...:    ...:
   ...:    ...: c = LocalCluster(nanny=False)
   ...:    ...: client = Client(c)
   ...:    ...:
   ...:    ...: df = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'])
   ...:    ...: df.iloc[3:5, 0] = np.nan
   ...:    ...: df.iloc[4:6, 1] = np.nan
   ...:    ...: df.iloc[5:8, 2] = np.nan
   ...:    ...:
   ...:    ...: ddf = dd.from_pandas(df, npartitions=4)
   ...:    ...: ddf = client.persist(ddf)
   ...:    ...: ddf
   ...:    ...:
distributed -> 2021.03.0+7.g6adfd3a8
dask -> 2021.03.0+12.ga81a9cdc6
pandas -> 1.2.1
Out[4]:
Dask DataFrame Structure:
                     A        B        C
npartitions=3
0              float64  float64  float64
3                  ...      ...      ...
6                  ...      ...      ...
9                  ...      ...      ...
Dask Name: from_pandas, 3 tasks

In [6]: ddf = ddf.assign(A=ddf['A'].fillna(ddf['B']))

In [7]: ddf = client.persist(ddf)

In [8]: ddf.compute()
Out[8]:
          A         B         C
0  1.238978 -0.928938  0.859873
1 -1.061970  0.280589  0.292445
2 -0.842078 -0.138487  0.431290
3 -2.258762 -2.258762 -2.834810
4       NaN       NaN -0.893345
5  0.411941       NaN       NaN
6 -0.054304  0.228074       NaN
7 -0.062058 -0.319565       NaN
8  0.070556  0.567272  0.903886
9  0.351121  0.244442 -1.245640
```
