### ISSUE TITLE
performance_report fails with bokeh==3.0.0

### ISSUE THREAD

**Issue by wooahn** [dask/distributed#7237]
Hi all, I came across a (hopefully minor) bug:

# Steps to reproduce
1. make a new venv with the following requirements.txt:
```
dask^=2022.10
distributed^=2022.10
bokeh^=3.0
```
2. output of pip list (trimmed):
```
dask 2022.10.2
distributed 2022.10.2
bokeh 3.0.0
```
3. run this script successfully
```python
from distributed import performance_report, Client

with Client(processes=False):
    pass
```

4. fail to run this script:
```python
from distributed import performance_report, Client

with Client(processes=False), performance_report(filename='perf-report-test.html'):
    pass
```

Stacktrace:
```
2022-11-01 14:52:47,767 - distributed.core - ERROR - Exception while handling op performance_report
Traceback (most recent call last):
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/core.py", line 771, in _handle_comm
    result = await result
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/scheduler.py", line 7476, in performance_report
    from distributed.dashboard.components.scheduler import task_stream_figure
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 17, in <module>
    from bokeh.models import (
ImportError: cannot import name 'Panel' from 'bokeh.models' (/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/bokeh/models/__init__.py)
Traceback (most recent call last):
  File "/home/titanium/PycharmProjects/sandbox-pip/perf-report-test.py", line 4, in <module>
    pass
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/client.py", line 5452, in __exit__
    client.sync(self.__aexit__, exc_type, exc_value, traceback, code=code)
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/client.py", line 5440, in __aexit__
    data = await client.scheduler.performance_report(
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/core.py", line 1155, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/core.py", line 945, in send_recv
    raise exc.with_traceback(tb)
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/core.py", line 771, in _handle_comm
    result = await result
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/scheduler.py", line 7476, in performance_report
    from distributed.dashboard.components.scheduler import task_stream_figure
  File "/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/distributed/dashboard/components/scheduler.py", line 17, in <module>
    from bokeh.models import (
ImportError: cannot import name 'Panel' from 'bokeh.models' (/home/titanium/PycharmProjects/sandbox-pip/venv/lib/python3.8/site-packages/bokeh/models/__init__.py)

```

# Steps to check that bokeh==3.0.0 is probably the issue:

1. make a new venv with the following requirements.txt:
```
dask^=2022.10
distributed^=2022.10
bokeh!=3.*
```
2. output of pip list (trimmed):
```
dask 2022.10.2
distributed 2022.10.2
bokeh 2.4.3
```
3. run this script successfully
```python
from distributed import performance_report, Client

with Client(processes=False):
    pass
```

4. run this script successfully
```python
from distributed import performance_report, Client

with Client(processes=False), performance_report(filename='perf-report-test.html'):
    pass
```

**Environment**:

- Python version: 3.8.10
- Operating System: Ubuntu 20.04.5 LTS
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
Yup.  We're still working on Bokeh=3 compatibility.  This will probably
come out the next release in two weeks.

**Comment by wooahn** [comment]
Actually since this is already covered by #7173 I'll go ahead and close this. Thank you!
