### ISSUE TITLE
MIN_BOKEH_VERSION needs update

### ISSUE THREAD

**Issue by cyniphile** [dask/distributed#7244]
**Describe the issue**:

The dask webapp fails under the currently listed min bokeh version, simply rendering the "Dask needs bokeh..." stub page.

**Minimal Complete Verifiable Example**:

```py
from distributed.dashboard import scheduler
```
With bokeh < 2.3.2 I get the following error:

```sh
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/distributed/dashboard/components/scheduler.py", line 15, in <module>
    from bokeh.io import curdoc
  File "/.venv/lib/python3.10/site-packages/bokeh/io/__init__.py", line 23, in <module>
    from .export import export_png, export_svgs
  File "/.venv/lib/python3.10/site-packages/bokeh/io/export.py", line 33, in <module>
    from ..document import Document
  File "/.venv/lib/python3.10/site-packages/bokeh/document/__init__.py", line 35, in <module>
    from .document import DEFAULT_TITLE ; DEFAULT_TITLE
  File "/.venv/lib/python3.10/site-packages/bokeh/document/document.py", line 49, in <module>
    from ..core.templates import FILE
  File "/.venv/lib/python3.10/site-packages/bokeh/core/templates.py", line 42, in <module>
    from jinja2 import Environment, FileSystemLoader, Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/.venv/lib/python3.10/site-packages/jinja2/__init__.py)
```
currently min version is 2.1.1 and should be updated to 2.3.2:
https://github.com/dask/distributed/blob/aa2cd65d84dad9ce58aab78c4f648d65c52ccc9b/distributed/versions.py#L15

**Anything else we need to know?**:
related (which led me to install an older version of Bokeh in the first place): https://github.com/dask/distributed/issues/7173

Also this line:

https://github.com/dask/distributed/blob/02b9430f7bb6eae370394eaac6b4e8f574746c94/distributed/scheduler.py#L3429

made the error harder to diagnose as it catches all import errors, including the one above. Would be nicer if caught only a specific `ModuleNotFound` error only when the problem really is that bokeh isn't installed. 

**Environment**:

- Dask version: 2022.6.1
- Python version: 3.10.6
- Operating System: Macos
- Install method (conda, pip, source): pip

**Comment by ncclementi** [comment]
I'm on distributed main and I can't replicate this problem:
```python
In [1]: import bokeh

In [2]: bokeh.__version__
Out[2]: '2.1.1'

In [3]: from distributed.dashboard import scheduler

In [4]: 
```

**Comment by jrbourbeau** [comment]
Thanks for reporting @cyniphile! We're working on adding a minimum dependency CI build which should fix issues like this. Will keep this issue posted

**Comment by jrbourbeau** [comment]
See https://github.com/dask/distributed/pull/7271 for updating the minimum `bokeh` version
