### ISSUE TITLE
bokeh 3 breaks performance reports

### ISSUE THREAD

**Issue by dchudz** [dask/distributed#7328]
```
Last login: Thu Nov 17 13:12:28 on ttys002
bye
(base)  /Users/davidchudzicki $
ipython
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:43)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from dask.distributed import Client, performance_report

In [2]: client = Client()
/opt/miniconda3/lib/python3.9/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 57217 instead
  warnings.warn(
w
In [3]: with performance_report(filename="dask-report.html"):
   ...:     client.submit(lambda x: x, 1)
   ...:
2022-11-17 13:14:30,974 - distributed.core - ERROR - Exception while handling op performance_report
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libcblas.3.dylib'
  Referenced from: '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
  Reason: tried: '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/bin/../lib/libcblas.3.dylib' (no such file), '/opt/miniconda3/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/site-packages/distributed/core.py", line 771, in _handle_comm
    result = await result
  File "/opt/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 7431, in performance_report
    compute, scheduler, workers = map(
  File "/opt/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py", line 7428, in profile_to_figure
    figure, source = profile.plot_figure(data, sizing_mode="stretch_both")
  File "/opt/miniconda3/lib/python3.9/site-packages/distributed/profile.py", line 456, in plot_figure
    from bokeh.models import HoverTool
  File "/opt/miniconda3/lib/python3.9/site-packages/bokeh/models/__init__.py", line 33, in <module>
    from ..model import Model
  File "/opt/miniconda3/lib/python3.9/site-packages/bokeh/model/__init__.py", line 25, in <module>
    from .data_model import DataModel
  File "/opt/miniconda3/lib/python3.9/site-packages/bokeh/model/data_model.py", line 24, in <module>
    from ..core.has_props import abstract
  File "/opt/miniconda3/lib/python3.9/site-packages/bokeh/core/has_props.py", line 57, in <module>
    from .property.descriptors import PropertyDescriptor, UnsetValueError
  File "/opt/miniconda3/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 106, in <module>
    from .wrappers import PropertyValueColumnData, PropertyValueContainer
  File "/opt/miniconda3/lib/python3.9/site-packages/bokeh/core/property/wrappers.py", line 78, in <module>
    import numpy as np
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/opt/miniconda3/bin/python"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libcblas.3.dylib'
  Referenced from: '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
  Reason: tried: '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/bin/../lib/libcblas.3.dylib' (no such file), '/opt/miniconda3/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
      1 with performance_report(filename="dask-report.html"):
----> 2     client.submit(lambda x: x, 1)

File /opt/miniconda3/lib/python3.9/site-packages/distributed/client.py:5478, in performance_report.__exit__(self, exc_type, exc_value, traceback)
   5476 client = get_client()
   5477 code = client._get_computation_code(self._stacklevel + 1)
-> 5478 client.sync(self.__aexit__, exc_type, exc_value, traceback, code=code)

File /opt/miniconda3/lib/python3.9/site-packages/distributed/utils.py:339, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    337     return future
    338 else:
--> 339     return sync(
    340         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    341     )

File /opt/miniconda3/lib/python3.9/site-packages/distributed/utils.py:406, in sync(loop, func, callback_timeout, *args, **kwargs)
    404 if error:
    405     typ, exc, tb = error
--> 406     raise exc.with_traceback(tb)
    407 else:
    408     return result

File /opt/miniconda3/lib/python3.9/site-packages/distributed/utils.py:379, in sync.<locals>.f()
    377         future = asyncio.wait_for(future, callback_timeout)
    378     future = asyncio.ensure_future(future)
--> 379     result = yield future
    380 except Exception:
    381     error = sys.exc_info()

File /opt/miniconda3/lib/python3.9/site-packages/tornado/gen.py:762, in Runner.run(self)
    759 exc_info = None
    761 try:
--> 762     value = future.result()
    763 except Exception:
    764     exc_info = sys.exc_info()

File /opt/miniconda3/lib/python3.9/site-packages/distributed/client.py:5466, in performance_report.__aexit__(self, exc_type, exc_value, traceback, code)
   5464 if code is None:
   5465     code = client._get_computation_code(self._stacklevel + 1)
-> 5466 data = await client.scheduler.performance_report(
   5467     start=self.start, last_count=self.last_count, code=code, mode=self.mode
   5468 )
   5469 with open(self.filename, "w") as f:
   5470     f.write(data)

File /opt/miniconda3/lib/python3.9/site-packages/distributed/core.py:1163, in PooledRPCCall.__getattr__.<locals>.send_recv_from_rpc(**kwargs)
   1161 prev_name, comm.name = comm.name, "ConnectionPool." + key
   1162 try:
-> 1163     return await send_recv(comm=comm, op=key, **kwargs)
   1164 finally:
   1165     self.pool.reuse(self.addr, comm)

File /opt/miniconda3/lib/python3.9/site-packages/distributed/core.py:953, in send_recv(comm, reply, serializers, deserializers, **kwargs)
    951     _, exc, tb = clean_exception(**response)
    952     assert exc
--> 953     raise exc.with_traceback(tb)
    954 else:
    955     raise Exception(response["exception_text"])

File /opt/miniconda3/lib/python3.9/site-packages/distributed/core.py:771, in _handle_comm()
    769     result = handler(**msg)
    770 if inspect.iscoroutine(result):
--> 771     result = await result
    772 elif inspect.isawaitable(result):
    773     raise RuntimeError(
    774         f"Comm handler returned unknown awaitable. Expected coroutine, instead got {type(result)}"
    775     )

File /opt/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py:7431, in performance_report()
   7428     figure, source = profile.plot_figure(data, sizing_mode="stretch_both")
   7429     return figure
-> 7431 compute, scheduler, workers = map(
   7432     profile_to_figure, (compute, scheduler, workers)
   7433 )
   7435 # Task stream
   7436 task_stream = self.get_task_stream(start=start)

File /opt/miniconda3/lib/python3.9/site-packages/distributed/scheduler.py:7428, in profile_to_figure()
   7426 def profile_to_figure(state):
   7427     data = profile.plot_data(state)
-> 7428     figure, source = profile.plot_figure(data, sizing_mode="stretch_both")
   7429     return figure

File /opt/miniconda3/lib/python3.9/site-packages/distributed/profile.py:456, in plot_figure()
    446 def plot_figure(data, **kwargs):
    447     """Plot profile data using Bokeh
    448
    449     This takes the output from the function ``plot_data`` and produces a Bokeh
   (...)
    454     plot_data
    455     """
--> 456     from bokeh.models import HoverTool
    457     from bokeh.plotting import ColumnDataSource, figure
    459     if "states" in data:

File /opt/miniconda3/lib/python3.9/site-packages/bokeh/models/__init__.py:33, in <module>
     26 log = logging.getLogger(__name__)
     28 #-----------------------------------------------------------------------------
     29 # Imports
     30 #-----------------------------------------------------------------------------
     31
     32 # Bokeh imports
---> 33 from ..model import Model
     34 from . import (
     35     annotations,
     36     axes,
   (...)
     65     widgets,
     66 )
     67 from .annotations import *

File /opt/miniconda3/lib/python3.9/site-packages/bokeh/model/__init__.py:25, in <module>
     18 log = logging.getLogger(__name__)
     20 #-----------------------------------------------------------------------------
     21 # Imports
     22 #-----------------------------------------------------------------------------
     23
     24 # Bokeh imports
---> 25 from .data_model import DataModel
     26 from .model import Model
     27 from .util import Qualified, collect_models, get_class

File /opt/miniconda3/lib/python3.9/site-packages/bokeh/model/data_model.py:24, in <module>
     17 log = logging.getLogger(__name__)
     19 #-----------------------------------------------------------------------------
     20 # Imports
     21 #-----------------------------------------------------------------------------
     22
     23 # Bokeh imports
---> 24 from ..core.has_props import abstract
     25 from .model import Model
     27 #-----------------------------------------------------------------------------
     28 # Globals and constants
     29 #-----------------------------------------------------------------------------

File /opt/miniconda3/lib/python3.9/site-packages/bokeh/core/has_props.py:57, in <module>
     55 from ..util.strings import append_docstring, nice_join
     56 from .property.descriptor_factory import PropertyDescriptorFactory
---> 57 from .property.descriptors import PropertyDescriptor, UnsetValueError
     58 from .property.override import Override
     59 from .property.singletons import Intrinsic, Undefined

File /opt/miniconda3/lib/python3.9/site-packages/bokeh/core/property/descriptors.py:106, in <module>
    104 # Bokeh imports
    105 from .singletons import Undefined
--> 106 from .wrappers import PropertyValueColumnData, PropertyValueContainer
    108 if TYPE_CHECKING:
    109     from typing_extensions import TypeGuard

File /opt/miniconda3/lib/python3.9/site-packages/bokeh/core/property/wrappers.py:78, in <module>
     68 from typing import (
     69     TYPE_CHECKING,
     70     Any,
   (...)
     74     TypeVar,
     75 )
     77 # External imports
---> 78 import numpy as np
     80 if TYPE_CHECKING:
     81     from ...document import Document

File /opt/miniconda3/lib/python3.9/site-packages/numpy/__init__.py:150, in <module>
    147 # Allow distributors to run custom init code
    148 from . import _distributor_init
--> 150 from . import core
    151 from .core import *
    152 from . import compat

File /opt/miniconda3/lib/python3.9/site-packages/numpy/core/__init__.py:48, in <module>
     24     import sys
     25     msg = """
     26
     27 IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
   (...)
     46 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     47         __version__, exc)
---> 48     raise ImportError(msg)
     49 finally:
     50     for envkey in env_added:

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/opt/miniconda3/bin/python"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libcblas.3.dylib'
  Referenced from: '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so'
  Reason: tried: '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/lib/python3.9/site-packages/numpy/core/../../../../libcblas.3.dylib' (no such file), '/opt/miniconda3/bin/../lib/libcblas.3.dylib' (no such file), '/opt/miniconda3/bin/../lib/libcblas.3.dylib' (no such file), '/usr/local/lib/libcblas.3.dylib' (no such file), '/usr/lib/libcblas.3.dylib' (no such file)


In [4]:
```

```
(base)  /Users/davidchudzicki $
pip list | grep bokeh
bokeh                    3.0.2
(base)  /Users/davidchudzicki $
pip list | grep distributed
distributed              2022.11.0
(base)  /Users/davidchudzicki $
```

**Comment by dchudz** [comment]
Oops, closing, I think I might be confused about what the problem is. Spending some more time with it first.

**Comment by mrocklin** [comment]
There are many bokeh three issues being raised right now.  I suspect that
James and team is on it.

**Comment by jrbourbeau** [comment]
This one is interesting. FWIW `bokeh=3.0.2` and `distributed=2022.11.0` should work together (or at least not error). Usually when I see these types of linking errors, it's because I've mixed conda channels -- installing some packages from `conda-forge` and some from `defaults`. @dchudz if you do `mamba list` and see mixed conda channels being used, installing just a single channel (e.g. just `conda-forge`) might resolve this issue

**Comment by dchudz** [comment]
I think James is probably right. Hence my closing this issue! I was hoping I'd closed it before I spent anyone's time.

Of the various bokeh issues going on right now, I think what you see here is not worth looking at.

**Comment by jrbourbeau** [comment]
No worries -- you sent ~15 seconds of my time, which is okay by me : )
