### ISSUE TITLE
NotImplementedError: cannot instantiate 'WindowsPath' on your system

### ISSUE THREAD

**Issue by IndexSeek** [dask/distributed#7460]
While following along with the example demonstrated in (https://github.com/coiled/coiled-from-prefect), specifically in the [coiled_flow.py](https://github.com/coiled/coiled-from-prefect/blob/main/flows/coiled_flow.py) file, I am encountering a `NotImplementedError: cannot instantiate 'WindowsPath' on your system` error. 

If I adjust to using the `cluster_class="dask.distributed.LocalCluster", it resolves the issue, leading me to believe there might be a mismatch in the software environment being used in the Coiled cluster versus that of my local machine. 

The error appears to bubble up from `distributed\client.py`. 

A similar thread is opened on discourse: [NotImplementedError: cannot instantiate ‘WindowsPath’ on your system](https://dask.discourse.group/t/notimplementederror-cannot-instantiate-windowspath-on-your-system/1145) by another user. 

I found a similar issue and a [solution](https://github.com/fastai/fastai/issues/1482#issuecomment-798790974) for fastai, but attempting to use this did not resolve the problem for me. 

**Environment**:

- Dask version: 
   - coiled==0.2.59
   - coiled-runtime==0.2.0
   - dask==2022.11.1
   - dask-glm==0.2.0
   - dask-labextension==6.0.0
   - dask-ml==2022.5.27
   - distributed==2022.11.1
- Python version: 3.10.4
- Operating System: Microsoft Windows 11 Home Version 10.0.22621 Build 22621
- Install method (conda, pip, source): pip

Installation via pip using:
```
pip install coiled-runtime==0.2.0 prefect>=2.7.1 prefect-aws>=0.2.1 prefect-dask>=0.2.2
```

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @IndexSeek. Do you have a traceback you can share?

It's not clear to me if this is a Coiled-specific issue or a more generic Dask issue that occurs when using Windows machines for the client and non-Windows (e.g. Linux) machines for other nodes in the cluster. My guess is the later, but that's just a guess. 

@crusaderky do you have any thoughts here?

**Comment by ntabris** [comment]
It's possible this is a package sync error, since I believe there was a Windows-path-related bug that I think will be fixed in `coiled=0.2.60` (planning to release today), and notebook is using package sync:

https://github.com/coiled/coiled-from-prefect/blob/0a19e2daed1afe3fc43501f1ad4c0be470f9c232/flows/coiled_flow.py#L117

cc @shughes-uk 

I'd need to see full traceback to know if this is the issue or if it's something else.

**Comment by shughes-uk** [comment]
@ntabris not package sync. If I had to guess, this is somehow serializing `WindowsPath` objects on the client and then trying to deserialize them on the cluster, instead of converting them to a more generic `Path`

**Comment by IndexSeek** [comment]
The only modifications I have made to the source code are S3 path adjustments and credential name adjustments. I'm connecting using a Coiled cluster with the following kwargs: 

```
{
    "n_workers": 2,
    "account": Secret.load("coiled-account").get(),
    "name": f"nyc-taxi-uber-lyft-{str(uuid.uuid1())}",
    "backend_options": {"region": "us-east-1"},
    "worker_memory": "16 GiB",
    "scheduler_options": {"idle_timeout": "0.5 hours"},
    "package_sync": True,
}
```

I am firing off the flow by executing: `python .\flows\coiled_flow.py`. 

```
(coiled-from-prefect-py3.10) PS C:\Users\BTyle\Documents\GitHub\coiled-from-prefect> python .\flows\coiled_flow.py
21:06:22.699 | INFO    | prefect.engine - Created flow run 'sensible-galago' for flow 'Check for files'
21:06:23.894 | INFO    | Flow run 'sensible-galago' - Found 1 files that are:  ['s3://STAGE_NAME_HERE/trip data/fhvhv_tripdata_2022-11.parquet']
21:06:24.240 | INFO    | Flow run 'sensible-galago' - Created subflow run 'screeching-unicorn' for flow 'clean-files-from-s3'
21:06:24.242 | INFO    | prefect.task_runner.dask - Creating a new Dask cluster with `coiled._beta.cluster.ClusterBeta`
╭─────────────────────────────────────── Package Sync Notes ───────────────────────────────────────╮
│                                      ╷                                                           │
│   Package                            │ Note                                                      │
│ ╶────────────────────────────────────┼─────────────────────────────────────────────────────────╴ │
│   coiled-runtime                     │ Package ignored, no risk                                  │
│   pywin32                            │ Package ignored, no risk                                  │
│   pywinpty                           │ Package ignored, no risk                                  │
│                                      ╵                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
21:08:07.840 | INFO    | prefect.task_runner.dask - The Dask dashboard is available at A_URL_HERE
21:08:08.119 | INFO    | Flow run 'screeching-unicorn' - Clean data
21:08:10.812 | INFO    | Flow run 'screeching-unicorn' - Created task run 'load_and_clean_data-5ebe95a6-0' for task 'load_and_clean_data'
21:08:11.594 | INFO    | Flow run 'screeching-unicorn' - Submitted task run 'load_and_clean_data-5ebe95a6-0' for execution.
21:08:19.034 | ERROR   | Flow run 'screeching-unicorn' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 636, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "C:\Users\BTyle\Documents\GitHub\coiled-from-prefect\flows\coiled_flow.py", line 125, in clean_data
    return prefect_future.result()
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\futures.py", line 226, in result     
    return sync(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 267, in sync
    return run_async_from_worker_thread(__async_fn, *args, **kwargs)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\from_thread.py", line 49, in run       
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\futures.py", line 237, in _result    
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect_dask\task_runners.py", line 269, in wait
    return await future.result(timeout=timeout)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\distributed\client.py", line 293, in _result 
    raise exc.with_traceback(tb)
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 73, in loads
  File "/opt/coiled/env/lib/python3.10/pathlib.py", line 960, in __new__
NotImplementedError: cannot instantiate 'WindowsPath' on your system
21:08:19.355 | INFO    | Task run 'load_and_clean_data-5ebe95a6-0' - Crash detected! Execution was interrupted by an unexpected exception: NotImplementedError: cannot instantiate 'WindowsPath' on your system
21:08:19.770 | ERROR   | Flow run 'screeching-unicorn' - Finished in state Failed("Flow run encountered an exception. NotImplementedError: cannot instantiate 'WindowsPath' on your system\n")
21:08:19.771 | ERROR   | Flow run 'sensible-galago' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 636, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "C:\Users\BTyle\Documents\GitHub\coiled-from-prefect\flows\coiled_flow.py", line 167, in check_for_files
    clean_data(files, intent=intent)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\flows.py", line 448, in __call__     
    return enter_flow_run_engine_from_flow_call(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 168, in enter_flow_run_engine_from_flow_call
    return run_async_from_worker_thread(begin_run)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\from_thread.py", line 49, in run       
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\client\utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 546, in create_and_begin_subflow_run
    return await terminal_state.result(fetch=True)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 636, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "C:\Users\BTyle\Documents\GitHub\coiled-from-prefect\flows\coiled_flow.py", line 125, in clean_data
    return prefect_future.result()
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\futures.py", line 226, in result     
    return sync(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 267, in sync
    return run_async_from_worker_thread(__async_fn, *args, **kwargs)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\from_thread.py", line 49, in run       
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\futures.py", line 237, in _result    
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect_dask\task_runners.py", line 269, in wait
    return await future.result(timeout=timeout)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\distributed\client.py", line 293, in _result 
    raise exc.with_traceback(tb)
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 73, in loads
  File "/opt/coiled/env/lib/python3.10/pathlib.py", line 960, in __new__
NotImplementedError: cannot instantiate 'WindowsPath' on your system
21:08:19.968 | ERROR   | Flow run 'sensible-galago' - Finished in state Failed("Flow run encountered an exception. NotImplementedError: cannot instantiate 'WindowsPath' on your system\n")
Traceback (most recent call last):
  File "C:\Users\BTyle\Documents\GitHub\coiled-from-prefect\flows\coiled_flow.py", line 173, in <module>
    check_for_files(intent="test_subset")
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\flows.py", line 448, in __call__     
    return enter_flow_run_engine_from_flow_call(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 164, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run  
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\client\utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 244, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 636, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "C:\Users\BTyle\Documents\GitHub\coiled-from-prefect\flows\coiled_flow.py", line 167, in check_for_files
    clean_data(files, intent=intent)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\flows.py", line 448, in __call__     
    return enter_flow_run_engine_from_flow_call(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 168, in enter_flow_run_engine_from_flow_call
    return run_async_from_worker_thread(begin_run)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\from_thread.py", line 49, in run       
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\client\utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 546, in create_and_begin_subflow_run
    return await terminal_state.result(fetch=True)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\engine.py", line 636, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\to_thread.py", line 31, in run_sync    
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "C:\Users\BTyle\Documents\GitHub\coiled-from-prefect\flows\coiled_flow.py", line 125, in clean_data
    return prefect_future.result()
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\futures.py", line 226, in result     
    return sync(
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 267, in sync
    return run_async_from_worker_thread(__async_fn, *args, **kwargs)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\utilities\asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\from_thread.py", line 49, in run       
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\futures.py", line 237, in _result    
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect\states.py", line 89, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\prefect_dask\task_runners.py", line 269, in wait
    return await future.result(timeout=timeout)
  File "C:\Users\BTyle\AppData\Local\pypoetry\Cache\virtualenvs\coiled-from-prefect-NF7DchRU-py3.10\lib\site-packages\distributed\client.py", line 293, in _result 
    raise exc.with_traceback(tb)
  File "/opt/coiled/env/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 73, in loads
  File "/opt/coiled/env/lib/python3.10/pathlib.py", line 960, in __new__
NotImplementedError: cannot instantiate 'WindowsPath' on your system
```

**Comment by crusaderky** [comment]
@IndexSeek does the problem persist if you remove the prefect boilerplate, as shown below?

```python
import uuid

import coiled
import dask.dataframe as dd
import distributed
import pandas as pd

storage_options = {
    "key": "YOUR KEY HERE",
    "secret": "YOUR SECRET HERE",
    "client_kwargs": {"region_name": "us-east-1"},
}
input_path = "s3://nyc-tlc/trip data/fhvhv_tripdata_2019-02.parquet"
output_path = "s3://YOUR BUCKET HERE/coiled-test"

cluster = coiled.Cluster(
    n_workers=1,
    name="nyc-taxi-uber-lyft",
    backend_options={"region": "us-east-1"},
    worker_memory="64 GiB",
    package_sync=True,
)
client = distributed.Client(cluster)

# Load
ddf = dd.read_parquet([input_path])

# Manipulate
yes_no = pd.CategoricalDtype(categories=["Y", "N"])
conversions = {}
for column, dtype in ddf.dtypes.items():
    if dtype == "object":
        conversions[column] = "string[pyarrow]"
    if dtype == "float64":
        conversions[column] = "float32"
    if dtype == "int64":
        conversions[column] = "int32"
    if "flag" in column:
        conversions[column] = yes_no
ddf = ddf.astype(conversions)
ddf = ddf.repartition(partition_size="100MB")

# Write
name_func = lambda x: f"fhvhv_tripdata_{str(uuid.uuid1(clock_seq=int(x)))}.parquet"
dd.to_parquet(
    ddf,
    output_path,
    storage_options=storage_options,
    name_function=name_func,
)
```

**Comment by IndexSeek** [comment]
@crusaderky That worked! It was successful on the first try. 🎉

Does this mean it is likely an issue between the DaskTaskRunner submitting the work to the Dask Cluster? I performed a test using a LocalCluster with the DaskTaskRunner, and all seemed okay with the Prefect flow.

**Comment by crusaderky** [comment]
So it seems. What happens you keep the whole prefect boilerplate but replace all the dask.dataframe stuff with just a hello world? e.g.

`get_client().submit(lambda: "Hello world!").result()`

**Comment by madkinsz** [comment]
I am suspicious of the `Profile` object in our `SettingsContext` which is sent to workers.

We create a copy of the settings to send to workers at https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py#L1231. The `SettingsContext` contains `Settings` and `Profile` information. 

The `Settings` object is defined at https://github.com/PrefectHQ/prefect/blob/main/src/prefect/settings.py#L970 and already has a bunch of `Path` objects, but we have a special reducer attached already to support Cythonized Pydantic versions https://github.com/PrefectHQ/prefect/blob/main/src/prefect/utilities/pydantic.py#L49. Consequently, the settings should be sent as JSON already.

The `Profile` object includes a `source` field that is a path https://github.com/PrefectHQ/prefect/blob/main/src/prefect/settings.py#L1223. The field is optional, but should be set by default since the default profile is stored locally.

**Comment by crusaderky** [comment]
Moving the issue here: https://github.com/PrefectHQ/prefect-dask/issues/70
