### ISSUE TITLE
`'NoneType' object has no attribute 'send'` in client logs

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#7548]
```python-traceback
ERROR:tornado.application:Exception in callback <bound method Client._heartbeat of <Client: 'tls://10.0.32.52:8786' processes=8 threads=32, memory=119.47 GiB>>
Traceback (most recent call last):
  File "/Users/gabe/Library/Caches/pypoetry/virtualenvs/geo-example-e13jEwDC-py3.9/lib/python3.9/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/Users/gabe/Library/Caches/pypoetry/virtualenvs/geo-example-e13jEwDC-py3.9/lib/python3.9/site-packages/distributed/client.py", line 1445, in _heartbeat
    self.scheduler_comm.send({"op": "heartbeat-client"})
AttributeError: 'NoneType' object has no attribute 'send'
```
This is repeated about 20 times. It showed up in the Jupyter logs, but I've seen it plenty of times in the past in other places.

I suspect this happened after the cluster shut itself down, but the notebook was still running. My laptop may also have gone to sleep before the cluster shut itself down, then woken back up after. Can't confirm though, and don't have a reproducer.

* distributed: 2023.2.0
* macOS

The obvious culprit is the `or` statement here:
https://github.com/dask/distributed/blob/be3a62ecf0ad94fdf694d02cc5eeae8c31661d86/distributed/client.py#L1442-L1445

If `self.scheduler_comm` is None, we should not proceed with the rest of the statement, regardless of the cluster status. xref https://github.com/dask/distributed/pull/7429 cc @jrbourbeau.

**Comment by gjoseph92** [comment]
This just happened again and spewed errors into my notebook: 
![image](https://user-images.githubusercontent.com/3309802/219107048-a873c10e-a99c-41dd-b66b-3fae6f93a930.png)

The timestamp in the error says 10:28:10, and [Coiled logs](https://cloud.coiled.io/clusters/157330/lifecycle?account=dask-engineering) my scheduler as shutting down at 10:28:08, so this is almost certainly caused by the scheduler shutting down.

FWIW, I created the client like
```python
cluster = coiled.Cluster(backend_options={'region': 'us-east-1'}, package_sync=True)
client = cluster.get_client()
```
so presumably `self.cluster` [should](https://github.com/dask/distributed/blob/be3a62ecf0ad94fdf694d02cc5eeae8c31661d86/distributed/deploy/cluster.py#L360) [be set](https://github.com/dask/distributed/blob/be3a62ecf0ad94fdf694d02cc5eeae8c31661d86/distributed/client.py#L884-L886). But perhaps the Coiled cluster's `status` was not updated to `closing` yet.

That shouldn't matter though; if `scheduler_comm` is None we shouldn't be trying to send things over it.
