### ISSUE TITLE
Dask distributed performance_report to allow an address parameter

### ISSUE THREAD

**Issue by benjaminhduncan** [dask/distributed#7598]
When a local cluster is created and a client is initialized with the set_as_default=False is is not possible to create a performance report. This issue stems from this [stackoverflow thread](https://stackoverflow.com/questions/75580054/dask-distributed-performance-report-is-not-working-when-client-is-not-default-sc).

```python
import dask.distributed as dd

cluster = dd.LocalCluster(n_workers=2, threads_per_worker=4, memory_limit='5GiB')
client = dd.Client(cluster, set_as_default=False)
    
with dd.performance_report(filename='dask-report.html'):
    print(client)
    print(cluster)
````

This results in the following trace:

> Traceback (most recent call last):
  File “bla/test.py”, line 9, in <module>
    with dd.performance_report(filename='dask-report.html'):
  File "bla/lib/python3.10/site-packages/distributed/client.py", line 5497, in __enter__
    get_client().sync(self.__aenter__)
  File "bla/lib/python3.10/site-packages/distributed/worker.py", line 2771, in get_client
    raise ValueError("No global client found and no address provided")
ValueError: No global client found and no address provided

If an optional _address_ parameters was added and passed through to the _get_client_ call, the user would not have to rely on global scheduler defaults.

**Comment by benjaminhduncan** [comment]
Thanks for the suggestion @fjetter, this solution works well. If this is the intended approach, we can close this feature suggestion.
