### ISSUE TITLE
Retry fetching preload on `ConnectionResetError`

### ISSUE THREAD

**Issue by shughes-uk** [dask/distributed#7661]
When loading remote preloads `ConnectionResetError` should probably be retried. This is killing workers in our clusters sometimes.
```
distributed.preloading - INFO - Creating preload: https://cloud.coiled.io/api/v2/cluster_facing/preload/worker
distributed.preloading - INFO - Downloading preload at https://cloud.coiled.io/api/v2/cluster_facing/preload/worker
Traceback (most recent call last):
  File "/opt/coiled/env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/coiled/env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/cli/dask_spec.py", line 46, in <module>
    main()
  File "/opt/coiled/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/coiled/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/coiled/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/coiled/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/cli/dask_spec.py", line 42, in main
    asyncio.run(run())
  File "/opt/coiled/env/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/coiled/env/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/cli/dask_spec.py", line 36, in run
    servers = await run_spec(_spec, *args)
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/deploy/spec.py", line 680, in run_spec
    workers[k] = cls(*args, **d.get("opts", {}))
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/nanny.py", line 202, in __init__
    self.preloads = preloading.process_preloads(
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/preloading.py", line 244, in process_preloads
    return [
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/preloading.py", line 245, in <listcomp>
    Preload(dask_server, p, argv, file_dir)
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/preloading.py", line 191, in __init__
    self.module = _download_module(name)
  File "/opt/coiled/env/lib/python3.9/site-packages/distributed/preloading.py", line 150, in _download_module
    exec(compiled, module.__dict__)
  File "https://cloud.coiled.io/api/v2/cluster_facing/preload/worker", line 106, in <module>
  File "/opt/coiled/env/lib/python3.9/multiprocessing/pool.py", line 357, in apply
    return self.apply_async(func, args, kwds).get()
  File "/opt/coiled/env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/opt/coiled/env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "https://cloud.coiled.io/api/v2/cluster_facing/preload/worker", line 101, in hacky
  File "/opt/coiled/env/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/coiled/env/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "https://cloud.coiled.io/api/v2/cluster_facing/preload/worker", line 48, in worker_phone_home
  File "/opt/coiled/env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 338, in run
    stream = await self.tcp_client.connect(
  File "/opt/coiled/env/lib/python3.9/site-packages/tornado/tcpclient.py", line 288, in connect
    stream = await stream.start_tls(
  File "/opt/coiled/env/lib/python3.9/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/opt/coiled/env/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

Distributed 2023.3.1+11.g0a88b761

**Comment by gjoseph92** [comment]
@shughes-uk if I'm reading this traceback correctly, the exception is actually happening in the Coiled preload script? (Looks like downloading the preloads also includes `exec`ing them, and the Coiled preload is making requests of its own when eval'd.)

```python-traceback
  File "https://cloud.coiled.io/api/v2/cluster_facing/preload/worker", line 48, in worker_phone_home
  File "/opt/coiled/env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 338, in run
    stream = await self.tcp_client.connect(
  File "/opt/coiled/env/lib/python3.9/site-packages/tornado/tcpclient.py", line 288, in connect
    stream = await stream.start_tls(
  File "/opt/coiled/env/lib/python3.9/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/opt/coiled/env/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

The actual preload-downloading already incudes some retries; hopefully those would catch any transient errors with the actual download: https://github.com/dask/distributed/blob/0a88b761be5887e9a72887c44e80f513cadf7020/distributed/preloading.py#L140-L143

**Comment by jrbourbeau** [comment]
Thanks for the issue @shughes-uk! Just checking in, is there anything to be done on the `distributed` side?

**Comment by shughes-uk** [comment]
Looks like the dask code would retry the default 10 times so I think we're good here. My bad.
