### ISSUE TITLE
ValueError: 'id' cannot be used together with property initializers in RMM

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#7731]
While reviewing #7729 I noticed that there are a bunch of RMM-related errors in CI.

https://github.com/dask/distributed/actions/runs/4573090787/jobs/8073100117

```pytb
2023-03-31 08:32:47,832 - tornado.application - ERROR - Uncaught exception GET /individual-rmm-memory (::1)
HTTPServerRequest(protocol='https', host='localhost:37961', method='GET', uri='/individual-rmm-memory', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/bokeh/server/contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/bokeh/application/application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/bokeh/application/handlers/function.py", line 142, in modify_document
    self._func(doc)
  File "/home/runner/work/distributed/distributed/distributed/dashboard/components/rmm.py", line 205, in rmm_memory_doc
    rmm_load = RMMMemoryUsage(scheduler, sizing_mode="stretch_both")
  File "/home/runner/work/distributed/distributed/distributed/dashboard/components/rmm.py", line 56, in __init__
    memory = figure(
  File "/usr/share/miniconda3/envs/dask-distributed/lib/python3.8/site-packages/bokeh/model/model.py", line 97, in __new__
    raise ValueError("'id' cannot be used together with property initializers")
ValueError: 'id' cannot be used together with property initializers
```

I expect this is related to #7718. @pentschev would you be able to take a look?

**Comment by jacobtomlinson** [comment]
This could also be related to the change in #7413.

**Comment by jrbourbeau** [comment]
Yeah, it looks like CI on https://github.com/dask/distributed/pull/7718 never ran with the new `bokeh` pinning introduced in https://github.com/dask/distributed/pull/7413. @pentschev thanks for taking a look

**Comment by jrbourbeau** [comment]
Removing the `id=` here seems to fix things locally

```diff
diff --git a/distributed/dashboard/components/rmm.py b/distributed/dashboard/components/rmm.py
index d83f9851..5c0db577 100644
--- a/distributed/dashboard/components/rmm.py
+++ b/distributed/dashboard/components/rmm.py
@@ -56,7 +56,7 @@ class RMMMemoryUsage(DashboardComponent):
             memory = figure(
                 title="RMM Memory",
                 tools="",
-                id="bk-rmm-memory-worker-plot",
+                # id="bk-rmm-memory-worker-plot",
                 width=int(width / 2),
                 name="rmm_memory_histogram",
                 **kwargs,
```
