### ISSUE TITLE
syntax error with `-annotated_prio` when `annotated_prio` is dict

### ISSUE THREAD

**Issue by ntabris** [dask/distributed#7737]
Dask/distributed `2023.3.2`.

Seeing this error:

```
(scheduler)     2023-03-31 13:17:16.872000 distributed.core - ERROR - Exception while handling op register-client
  Traceback (most recent call last):
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/core.py", line 831, in _handle_comm
      result = await result
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/scheduler.py", line 5365, in add_client
      await self.handle_stream(comm=comm, extra={"client": client})
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/core.py", line 915, in handle_stream
      handler(**merge(extra, msg))
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/scheduler.py", line 4341, in update_graph
      self._set_priorities(
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/scheduler.py", line 4581, in _set_priorities
      -annotated_prio,
  TypeError: bad operand type for unary -: 'dict'
  Task exception was never retrieved
  future: <Task finished name='Task-11146' coro=<Server._handle_comm() done, defined at /opt/coiled/env/lib/python3.9/site-packages/distributed/core.py:737> exception=TypeError("bad operand type for unary -: 'dict'")>
  Traceback (most recent call last):
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/core.py", line 831, in _handle_comm
      result = await result
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/scheduler.py", line 5365, in add_client
      await self.handle_stream(comm=comm, extra={"client": client})
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/core.py", line 915, in handle_stream
      handler(**merge(extra, msg))
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/scheduler.py", line 4341, in update_graph
      self._set_priorities(
    File "/opt/coiled/env/lib/python3.9/site-packages/distributed/scheduler.py", line 4581, in _set_priorities
      -annotated_prio,
  TypeError: bad operand type for unary -: 'dict'
```

Looks like `annotated_prio` can be `{}`...

https://github.com/dask/distributed/blob/54941387cb58b279a63dcb556ae6448789860118/distributed/scheduler.py#L4575

This was on a Coiled cluster used for Dask benchmarks, so Coiled employees will have access to more detailed information at https://cloud.coiled.io/clusters/181395/details?account=dask-benchmarks

**Comment by jrbourbeau** [comment]
Thanks @ntabris. My guess is this is related to https://github.com/dask/distributed/pull/7564. cc @fjetter for visibility

**Comment by jrbourbeau** [comment]
> Dask/distributed 2023.3.2.

Just wanted to double check that you're sure about this as https://github.com/dask/distributed/pull/7564 is (currently) unreleased

**Comment by ntabris** [comment]
Sorry, yeah, I should have looked more closely at version. `dask` was 2023.3.2 but distributed was `2023.3.2+15.g31b398b6`

**Comment by jrbourbeau** [comment]
No worries -- just wanted to double check. Making a fix attempt over in https://github.com/dask/distributed/pull/7738

**Comment by jrbourbeau** [comment]
Noting it's possible this might be because https://github.com/dask/distributed/pull/7564 needs to go along with it's corresponding change in `dask/dask` https://github.com/dask/dask/pull/9988 (again, haven't looked very deeply yet). That said, I wouldn't, in general, expect a released version of `dask` to work with an unreleased version of `distributed` (and vice versa). I would expect the matching releases and the latest `main` branch to always work together though

**Comment by ntabris** [comment]
Maybe! Though I'm pretty sure the possibility of `-{}` is bad regardless of dask version (though maybe priority would always be set so `get` wouldn't return `{}`).

**Comment by fjetter** [comment]
Closing this since we haven't seen it again. If this error pops up again, please reopen
