### ISSUE TITLE
AttributeError: module 'cupy' has no attribute 'cusparse' 

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#7866]
distributed.protocol.tests.test_cupy.test_serialize_cupy_sparse has started failing on gpuCI:
e.g. https://gpuci.gpuopenanalytics.com/job/dask/job/distributed/job/prb/job/distributed-prb/6658/

```
TypeError: Could not serialize object of type csc_matrix
Traceback (most recent call last):
  File "/workspace/distributed/protocol/pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
  File "/workspace/distributed/protocol/cupy.py", line 88, in reduce_matdescriptor
    return cupy.cusparse.MatDescriptor.create, ()
  File "/opt/conda/envs/dask/lib/python3.9/site-packages/cupy/__init__.py", line 921, in __getattr__
    raise AttributeError(f"module 'cupy' has no attribute {name!r}")
AttributeError: module 'cupy' has no attribute 'cusparse'
```

**Comment by crusaderky** [comment]
ping @jakirkham @rjzamora

**Comment by jrbourbeau** [comment]
Thanks @crusaderky -- just an FYI @charlesbluca mentioned he was looking into this one https://github.com/dask/distributed/pull/7855#issuecomment-1564490135

**Comment by charlesbluca** [comment]
Opened https://github.com/dask/distributed/pull/7868 which unblocked things for me locally

**Comment by jrbourbeau** [comment]
Thanks @charlesbluca!
