### ISSUE TITLE
Scheduler hangs randomly

### ISSUE THREAD

**Issue by csdenboer** [dask/distributed#801]
Hey,

I'm facing problems using parallel_backend. For some reason, the scheduler hangs randomly after few calls. I'm calling parallel_backend as follows:

`with parallel_backend('dask.distributed', scheduler_host='127.0.0.1:8786'):
    ret = Parallel()(fd(X, s, **kwds) for s in _gen_even_slices(len(X), n_jobs))`

I have 2 8-core servers where I start dask-worker as follows:
`dask-worker 10.1.0.4:8786 --nprocs 7 --nthreads 1 --no-bokeh`
They are idle at the moment the scheduler starts hanging. When I cancel the python call after it hangs, the following stacktrace is printed:

Traceback (most recent call last):
  File "/home/christian/.conda/envs/nedtrain35/lib/python3.5/site-packages/joblib/parallel.py", line 684, in retrieve
^C  File "/home/christian/.conda/envs/nedtrain35/lib/python3.5/site-packages/distributed/client.py", line 110, in result
    result = sync(self.client.loop, self._result, raiseit=False)
  File "/home/christian/.conda/envs/nedtrain35/lib/python3.5/site-packages/distributed/utils.py", line 161, in sync
    e.wait(1000000)
  File "/home/christian/.conda/envs/nedtrain35/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/home/christian/.conda/envs/nedtrain35/lib/python3.5/threading.py", line 297, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

The following versions are installed:
- dask                      0.13.0                   py35_0    conda-forge
- distributed               1.15.0                   py35_0    conda-forge
- tornado                   4.4.1                    py35_0

**Comment by mrocklin** [comment]
Hi @csdenboer, are you able to provide a small reproducible example that we can use to generate the failure ourselves?

**Comment by csdenboer** [comment]
It's pretty hard to come up with a small reproducible example. Is there somewhere a log where I can see why a worker failed?

**Comment by csdenboer** [comment]
It does not seem to be the scheduler that is hanging, but the python process from which parallel_backend is called. It 'hangs' after a call to Parallel and the Python process from which it is called starts consuming 150% CPU. This is always the case after many calls did succeed.

**Comment by mrocklin** [comment]
> Is there somewhere a log where I can see why a worker failed?

The dask-scheduler process and dask-worker process should emit logs.  Have you started these?

**Comment by mrocklin** [comment]
Closing this as stale.  Please reopen if you have new information.

**Comment by gouthambs** [comment]
I have encountered similar issues. What I have noticed is that this especially happens when an operation errs on the worker, such as incorrect syntax or wrong imports etc. Unfortunately, I don't have a reproducible example at this point.

**Comment by mrocklin** [comment]
@gouthambs I've been trying to reproduce this here: https://github.com/dask/distributed/pull/1098

Though have not yet succeeded.  If you have any recommendations on how to reproduce this issue or alter those tests I would be much obliged.

**Comment by gouthambs** [comment]
I am trying to create a test case that I can share. Here is a traceback that I observe on the logs after I notice the system hanging. Would this be of any use?
```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000000F93A43F378>, <tornado.concurrent.Future object at 0x000000F935D68860>)
Traceback (most recent call last):
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\ioloop.py", line 604, in _run_callback
    ret = callback()
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\distributed\worker.py", line 1850, in execute
    self.execution_state, key)
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\distributed\worker.py", line 348, in executor_submit
    yield future
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\distributed\worker.py", line 644, in apply_function
    'nbytes': sizeof(result),
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\dask\utils.py", line 585, in __call__
    return impl(arg)
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\distributed\sizeof.py", line 57, in sizeof_pandas_dataframe
    if col.dtype == object:
  File "c:\users\portanalytics_svc\appdata\local\conda\conda\envs\daskenv\lib\site-packages\pandas\core\generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'dtype'
```
My setup is the following:
- Scheduler on windows server 2012R2
- 7 Windows 2012R2 Servers running `dask-worker --nprocs 16 <sched_ip>

**Comment by gouthambs** [comment]
@mrocklin Here you go
Setup:
- Windows Desktop
- `dask-scheduler` running on one CMD prompt
- `dask-worker --nprocs 4 localhost:8786` running on another CMD prompt

CSV Data File (c:\test_sample.csv):
```
,daskid,prob2,prob6,probX
5,818.0,0.0016510619112109905,0.0002888562279065236,0.044747941431480975
4,842.0,0.001157976756105526,0.00018318110468298302,0.058871319086405076
6,789.0,0.0015598275679631864,0.00023427550413875268,0.06389254643336639
3,767.0,0.0028854459461014077,0.0013683705926218592,0.03692031878189761
```


Python Source Code
```
from distributed import Client
import dask.dataframe as dd
import dask, distributed
print(dask.__version__, distributed.__version__)
client = Client('localhost:8786')

df = dd.read_csv(r"c:\test_sample.csv", blocksize=100,
                usecols=['daskid', 'prob2', 'prob6', 'probX'])
print("Columns",df.columns)
print("npartitions ", df.npartitions)
df = client.persist(df)
dft = df[(df.daskid>=660) & (df.daskid<850)]
dft = client.persist(dft)
print("dft len", len(dft))
dft["mx6"] = dft.prob6*dft.probX
dft["mx2"] = dft.prob2*dft.probX

dfr = dft[["prob2", "prob6", "mx6", "mx6"]].compute()
dft = client.persist(dft)
```

You can see that the line:
`dfr = dft[["prob2", "prob6", "mx6", "mx6"]].compute()`

asks for the same column `mx6` twice. But that worker throws an error and hangs. Let me know if you can replicate and hopefully this is relevant to #1098.

**Comment by mrocklin** [comment]
Replicated.  Thank you for your effort in producing this @gouthambs and sorry for my delay in responding (I've been traveling a bit for work recently and just got home.)  I'm playing with this now.

**Comment by gouthambs** [comment]
@mrocklin Good to know that you are able to replicate on your end. This is one example of the error I have encountered. I have come across similar issues where the worker/scheduler hangs because of some error in the code. Hopefully the fix will be generic enough to catch other such issues.
