### ISSUE TITLE
Incompatibility with latest version of bokeh

### ISSUE THREAD

**Issue by mackaiver** [dask/distributed#806]
Hello,

I just installed distributed in new virtual environment.  The bokeh version being installed as a dependency is `0.12.4`. Starting a `dask-scheduler` raises the following exception:

```
(dask) [someuser@somehost ~]$ dask-scheduler 
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Could not launch service: bokeh-8788
Traceback (most recent call last):
  File "/home/kbruegge/anaconda3/envs/dask/lib/python3.5/site-packages/distributed/scheduler.py", line 310, in __init__
    service.listen(port)
  File "/home/kbruegge/anaconda3/envs/dask/lib/python3.5/site-packages/distributed/bokeh/core.py", line 17, in listen
    self.server.start(start_loop=False)
``` 

After downgrading to bokeh `0.12.3` everything seems to work fine.

**Comment by mrocklin** [comment]
Yup.  This is fixed in master.  Planning to roll out a new micro release soon.  Thanks for reporting.
