### ISSUE TITLE
`Event loop stopped before Future completed` on Jupyter shutdown 

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#8219]
If I run JupyterLab on the scheduler with `dask scheduler --jupyter`, then navigate to the the JupyterLab session (same as Bokeh dashboard link, but with `jupyter/lab` instead of `status`), and then shutdown the Jupyter session (File > Shut Down), I get the following output 

```
[I 2023-09-27 13:34:08.341 ServerApp] Shutting down on /api/shutdown request.
[I 2023-09-27 13:34:08.341 ServerApp] Shutting down 4 extensions
2023-09-27 13:34:08,344 - distributed.scheduler - INFO - End scheduler
Traceback (most recent call last):
  File "/Users/james/mambaforge/envs/distributed/bin/dask-scheduler", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/james/mambaforge/envs/distributed/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/mambaforge/envs/distributed/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/james/mambaforge/envs/distributed/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/mambaforge/envs/distributed/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/projects/dask/distributed/distributed/cli/dask_scheduler.py", line 251, in main
    asyncio_run(run(), loop_factory=get_loop_factory())
  File "/Users/james/projects/dask/distributed/distributed/compatibility.py", line 204, in asyncio_run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/james/mambaforge/envs/distributed/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/mambaforge/envs/distributed/lib/python3.11/asyncio/base_events.py", line 651, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

@graingert any idea what might be going on here with the event loop?

**Comment by graingert** [comment]
this is because jupyter_server's shutdown handler abruptly stops the event loop: https://github.com/jupyter-server/jupyter_server/blob/cf8df8a6b26455977f1eb946dc3dead069981ea4/jupyter_server/services/shutdown.py#L24

we could override the shutdown handler to do something else (eg call `await scheduler.close(...)`)
