### ISSUE TITLE
"Print host info" is failing on the macos runners

### ISSUE THREAD

**Issue by graingert** [dask/distributed#8227]
eg https://github.com/dask/distributed/actions/runs/6394414327/job/17355770383?pr=8223

```
Run python continuous_integration/scripts/host_info.py
/Users/runner/work/distributed/distributed/distributed/utils.py:180: RuntimeWarning: Couldn't detect a suitable IP address for reaching '2001:4860:4860::8888', defaulting to hostname: [Errno 65] No route to host
  warnings.warn(
Traceback (most recent call last):
Number of CPUs: 4
  File "/Users/runner/work/distributed/distributed/distributed/utils.py", line 176, in _get_ip
Crude CPU benchmark (higher is better): 13.8
    sock.connect((host, port))
CPU frequency:
OSError: [Errno 65] No route to host
  - current=3190, min=3190, max=3190

Memory:
During handling of the above exception, another exception occurred:
  - active    =   1.71 GiB

  - available =  11.08 GiB
Traceback (most recent call last):
  - free      =   5.46 GiB
  File "/Users/runner/work/distributed/distributed/continuous_integration/scripts/host_info.py", line 53, in <module>
  - inactive  =   2.01 GiB
    main()
  - total     =  14.00 GiB
  File "/Users/runner/work/distributed/distributed/continuous_integration/scripts/host_info.py", line 49, in main
  - used      =   2.91 GiB
    print(f"IPv6: {get_ipv6() if has_ipv6() else 'unavailable'}")
  - wired     =   1.20 GiB
                   ^^^^^^^^^^
IPv4: 192.168.64.21
  File "/Users/runner/work/distributed/distributed/distributed/utils.py", line 207, in get_ipv6
    return _get_ip(host, port, family=socket.AF_INET6)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cytoolz/functoolz.pyx", line 489, in cytoolz.functoolz._memoize.__call__
  File "/Users/runner/work/distributed/distributed/distributed/utils.py", line 185, in _get_ip
    addr_info = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/dask-distributed/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by graingert** [comment]
looks like this isn't happening any more
