### ISSUE TITLE
Test Report CI action is broken

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8345]
The CI action stopped working on Oct 17 (https://github.com/dask/distributed/actions/runs/6544286691) and the test report hasn't been updated since.

```
Traceback (most recent call last):
Getting list of workflow runs...
Found 274 workflow runs
Fetching artifact listing for the 30 most recent workflow runs
Downloading and parsing 687 artifacts...
  File "/home/runner/work/distributed/distributed/continuous_integration/scripts/test_report.py", line 508, in <module>
    main()
  File "/home/runner/work/distributed/distributed/continuous_integration/scripts/test_report.py", line 392, in main
    dfs = list(
  File "/home/runner/work/distributed/distributed/continuous_integration/scripts/test_report.py", line 344, in download_and_parse_artifacts
    jobs_df = get_jobs(r, session=session)
  File "/home/runner/work/distributed/distributed/continuous_integration/scripts/test_report.py", line [14](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:15)9, in get_jobs
    raise ValueError(f"Job names must have 4 components:\n{name_components!r}")
ValueError: Job names must have 4 components:
Empty DataFrame
Columns: []
Index: []
20... 40... 60... 80... 100... 120... 140... [16](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:17)0... [18](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:19)0... [20](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:21)0... [22](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:23)0... [24](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:25)0... [26](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:27)0... [28](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:29)0... [30](https://github.com/dask/distributed/actions/runs/6544286691/job/17770450048#step:7:31)0... 320... 340... 360... 380... 400... 420... 440... 460... 480... 500... 520... 540... 560... 580... 600... 620... 640... 
Error: Process completed with exit code 1.
```

**Comment by hendrikmakait** [comment]
XREF #8270
