### ISSUE TITLE
Script hangs on Client's close

### ISSUE THREAD

**Issue by aulemahal** [dask/distributed#8394]
**Describe the issue**:
My script hangs on the distributed client's closing. The stdout shows some errors, but the python interpreter never exits.

**Minimal Complete Verifiable Example**:
This bug happens semi-randomly. Not all scripts do it, and the current one is way too big to be usefully shared here. It is a long xarray-based processing script. It reads in around 100 zarr files, processes them and merges the output in another 50ish files. However, when the bug happens, the processing is already done and all the output looks good. This does not seem to affect anything in my processing itself. It just fails to quit.
```python3
from dask.distributed import Client
# and multiple other imports

if __name__ == '__main__':
    client = Client(n_workers=6, threads_per_worker=2, memory_limit="8GB", dashboard_address: 8785)
    # large computation
    dask.compute(tasks)
    
    client.close()
```
And it hangs there. Last time, the script "ended" and it hung for at least 36 h before I killed it with a KeyboardInterrupt. Earlier versions of that script did not have a `client.close()` line but they had the same problem.

**Anything else we need to know?**:
The traceback that prints to the console is : 

<details>

```
Traceback (most recent call last):
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 1935, in wait_for
    return await fut
           ^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/comm/tcp.py", line 547, in connect
    stream = await self.client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/tornado/tcpclient.py", line 279, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/comm/core.py", line 342, in connect
    comm = await wait_for(
           ^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 1934, in wait_for
    async with asyncio.timeout(timeout):
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pbourg/portraits_climatiques/preparation/catalog_to_zarr.py", line 623, in <module>
    client.close()
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/client.py", line 1777, in close
    f = self.cluster.close()
        ^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/deploy/spec.py", line 293, in close
    aw = super().close(timeout)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/deploy/cluster.py", line 223, in close
    return self.sync(self._close, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 358, in sync
    return sync(
           ^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 434, in sync
    raise error
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 408, in f
    result = yield future
             ^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/deploy/spec.py", line 448, in _close
    await self._correct_state()
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/deploy/spec.py", line 353, in _correct_state_internal
    await self.scheduler_comm.retire_workers(workers=list(to_close))
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/core.py", line 1311, in send_recv_from_rpc
    comm = await self.live_comm()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/core.py", line 1270, in live_comm
    comm = await connect(
           ^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/comm/core.py", line 368, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://127.0.0.1:35663 after 30 s
```

</details>

After printing this, nothing happens until I kill it with CTRL+C. Which then prints:

<details>

```
^CException ignored in atexit callback: <function _close_global_client at 0x7f10dd7e93a0>
Traceback (most recent call last):
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/client.py", line 6136, in _close_global_client
    c.close(timeout=3)
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/client.py", line 1777, in close
    f = self.cluster.close()
        ^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/deploy/spec.py", line 293, in close
    aw = super().close(timeout)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/deploy/cluster.py", line 223, in close
    return self.sync(self._close, callback_timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 358, in sync
    return sync(
           ^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 431, in sync
    wait(10)
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/site-packages/distributed/utils.py", line 420, in wait
    return e.wait(timeout)
           ^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my/disk/mambaforge/envs/myenv/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
```

**Environment**:

- Dask version: 2023.12.0  (this bug also occurred in an env with dask 2023.10)
- Python version: 3.11.4
- Operating System: Linux (Centos 7)
- Install method (conda, pip, source): conda (mamba forge)

Full env:

<details>

```
# packages in environment at /my/disk/mambaforge/envs/myenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.9                hd590300_0    conda-forge
annotated-types           0.5.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.7.3                h28f7589_1    conda-forge
aws-c-cal                 0.6.1                hc309b26_1    conda-forge
aws-c-common              0.9.0                hd590300_0    conda-forge
aws-c-compression         0.2.17               h4d4d85c_2    conda-forge
aws-c-event-stream        0.3.1                h2e3709c_4    conda-forge
aws-c-http                0.7.11               h00aa349_4    conda-forge
aws-c-io                  0.13.32              h4a1a131_0    conda-forge
aws-c-mqtt                0.9.3                hb447be9_1    conda-forge
aws-c-s3                  0.3.14               hf3aad02_1    conda-forge
aws-c-sdkutils            0.1.12               h4d4d85c_1    conda-forge
aws-checksums             0.1.17               h4d4d85c_1    conda-forge
aws-crt-cpp               0.21.0               hb942446_5    conda-forge
aws-sdk-cpp               1.10.57             h85b1a90_19    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
blosc                     1.21.4               h0f2a231_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
bottleneck                1.3.7           py311hcb2cf0a_0    conda-forge
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9           py311ha362b79_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
cartopy                   0.22.0          py311h320fe9a_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cf_xarray                 0.7.9              pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                hd9d235c_0    conda-forge
cftime                    1.6.2           py311h4c7f6c3_1    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.6           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
clisops                   0.10.0             pyh1a96a4e_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py311h9547e67_0    conda-forge
curl                      8.2.1                hca28451_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.2          py311h459d7ec_0    conda-forge
dask                      2023.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2023.12.0          pyhd8ed1ab_0    conda-forge
datashader                0.16.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.8.0           py311hb755f60_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distributed               2023.12.0          pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
esmf                      8.4.2           mpi_mpich_h8fb3fe9_101    conda-forge
esmpy                     8.4.2              pyhc1e730c_1    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fastprogress              1.0.3              pyhd8ed1ab_0    conda-forge
fiona                     1.9.4           py311hbac4ec9_0    conda-forge
flox                      0.7.2              pyhd8ed1ab_0    conda-forge
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.42.0          py311h459d7ec_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
gdal                      3.7.0           py311h1caf18b_3    conda-forge
geopandas                 0.13.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.13.2             pyha770c72_1    conda-forge
geos                      3.11.2               hcb278e6_0    conda-forge
geotiff                   1.7.1               h22adcc9_11    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.22.5               hf7dbed1_0    conda-forge
gstreamer                 1.22.5               h98fc4e7_0    conda-forge
h5netcdf                  1.2.0              pyhd8ed1ab_0    conda-forge
h5py                      3.9.0           nompi_py311he78b9b8_101    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.1          mpi_mpich_ha2c2bf8_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
intake                    0.7.0              pyhd8ed1ab_0    conda-forge
intake-esm                2023.7.7           pyhd8ed1ab_0    conda-forge
ipykernel                 6.26.0             pyhf8b6a83_0    conda-forge
ipython                   8.14.0             pyh41d4057_0    conda-forge
jedi                      0.19.0             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json-c                    0.16                 hc379101_0    conda-forge
jsonpickle                2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.5.0           py311h38be061_0    conda-forge
kealib                    1.5.1                h3e6883b_4    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py311h4dd048b_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libarrow                  12.0.1           h10ac928_8_cpu    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  15.0.7          default_h7634d5b_3    conda-forge
libclang13                15.0.7          default_h9986a30_3    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgdal                   3.7.0                h4a547c6_3    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgoogle-cloud           2.12.0               h840a212_1    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libgrpc                   1.56.2               h3905398_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libllvm15                 15.0.7               h5cf9203_3    conda-forge
libnetcdf                 4.9.2           mpi_mpich_hde7fb9e_9    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpnetcdf                1.12.3          mpi_mpich_h4ac58e2_101    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.4                 hfc447b1_0    conda-forge
libprotobuf               4.23.3               hd1fb520_0    conda-forge
librttopo                 1.1.0               h0d5128d_13    conda-forge
libsndfile                1.2.2                hbc2eb40_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libspatialite             5.0.1               hca56755_27    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libsystemd0               254                  h3516f8a_0    conda-forge
libthrift                 0.18.1               h8fd135c_2    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.40.1          py311ha6695c7_0    conda-forge
lmoments3                 1.0.6              pyhd8ed1ab_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
loguru                    0.7.0           py311h38be061_0    conda-forge
lz4                       4.3.2           py311h9f220a4_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mapclassify               2.5.0              pyhd8ed1ab_1    conda-forge
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
matplotlib                3.7.2           py311h38be061_0    conda-forge
matplotlib-base           3.7.2           py311h54ef318_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
morecantile               5.0.0              pyhd8ed1ab_0    conda-forge
mpg123                    1.31.3               hcb278e6_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     4.1.2              h846660c_100    conda-forge
msgpack-python            1.0.5           py311ha3edf6b_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     4.0.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
mysql-common              8.0.33               hf1915f5_2    conda-forge
mysql-libs                8.0.33               hca2cd23_2    conda-forge
nc-time-axis              1.4.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.1           mpi_mpich_h17322d4_1    conda-forge
netcdf4                   1.6.4           nompi_py311h9a7c333_101    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
noise                     1.2.2           py311h459d7ec_1005    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.89                 he45b914_0    conda-forge
numba                     0.57.1          py311h96b013e_0    conda-forge
numcodecs                 0.11.0          py311hcafe171_1    conda-forge
numpy                     1.24.4          py311h64a7726_0    conda-forge
numpy_groupies            0.9.22             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openpyxl                  3.1.2           py311h459d7ec_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
orc                       1.9.0                h385abfd_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py311h320fe9a_1    conda-forge
parallelio                2.6.0           mpi_mpich_h79a22d0_102    conda-forge
param                     1.13.0             pyh1a96a4e_0    conda-forge
parse                     1.19.1             pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0          py311h0b84326_0    conda-forge
pint                      0.22               pyhd8ed1ab_1    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
poppler                   23.05.0              hd18248d_1    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.4                 h8972f4a_0    conda-forge
proj                      9.2.1                ha643af7_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py311h2582759_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio-client         16.1                 hb77b528_4    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   12.0.1          py311h39c9aba_8_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydantic                  2.2.1              pyhd8ed1ab_0    conda-forge
pydantic-core             2.6.1           py311h46250e7_0    conda-forge
pygeos                    0.14            py311h54d622a_1    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.6.0           py311ha169711_1    conda-forge
pyqt                      5.15.9          py311hf0fb5b6_4    conda-forge
pyqt5-sip                 12.12.2         py311hb755f60_4    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311hd4cff14_5    conda-forge
pyzmq                     25.1.1          py311h34ded2d_2    conda-forge
qt-main                   5.15.8              h7fe3ca9_15    conda-forge
rasterio                  1.3.8           py311h41e4db2_0    conda-forge
rdma-core                 28.9                 h59595ed_1    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
rechunker                 0.5.2              pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rio-cogeo                 5.0.0              pyhd8ed1ab_0    conda-forge
rioxarray                 0.15.0             pyhd8ed1ab_0    conda-forge
roocs-utils               0.6.4              pyh1a96a4e_0    conda-forge
rtree                     1.0.1           py311h3bb2b0f_2    conda-forge
s2n                       1.3.48               h06160fa_0    conda-forge
scikit-learn              1.3.0           py311hc009520_0    conda-forge
scipy                     1.11.1          py311h64a7726_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py311h54d622a_1    conda-forge
sip                       6.7.11          py311hb755f60_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sparse                    0.14.0             pyhd8ed1ab_0    conda-forge
sqlite                    3.42.0               h2c6b66d_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0          py311h1f0f07a_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tiledb                    2.13.2               hd532e3d_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py311h459d7ec_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucx                       1.14.1               h4a2ce2d_3    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xarray                    2023.7.0           pyhd8ed1ab_0    conda-forge
xarray-datatree           0.0.12             pyhd8ed1ab_0    conda-forge
xarray-spatial            0.3.5              pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xclim                     0.46.3b0                 pypi_0    pypi
xerces-c                  3.2.4                h8d71039_2    conda-forge
xesmf                     0.7.1              pyhd8ed1ab_0    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xscen                     0.7.13b0                  dev_0    <develop>
xyzservices               2023.7.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zarr                      2.16.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.5                h59595ed_0    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

</details>

Sorry I can't have a MWE, but I'll try to answer any question about missing information! 

In addittion from the bug itself, I would be interesed in any elegant solutions to simply workaround the problem. I am currently testing something with the `signal` library that calls `sys.exit()` if the closing takes more than 1 min.
Thanks!

**Comment by jacobtomlinson** [comment]
Given that this has been open for over a year and nobody else has reported the same experience here I'm going to close this out as a tranasient issue. If folks are still running into this problem feel free to comment here and we can reopen.

**Comment by aulemahal** [comment]
Indeed, the issue seems to have disappeared in recent dask versions, thanks.
