### ISSUE TITLE
Scattering data to workers when using Queues

### ISSUE THREAD

**Issue by mackaiver** [dask/distributed#843]
Hello everyone, 

to my understanding it should be possible to distribute data to the worker nodes using the `client.scatter` method. @mrocklin described it in this stackoverflow post [here](http://stackoverflow.com/questions/41471248/how-to-efficiently-submit-tasks-with-large-arguments-in-dask-distributed). And indeed that seems to be working fine when batch processing data. When using queues (similar to #838 ) it does not seem to work. Heres a small example:

```
from queue import Queue
import time
from distributed import Client
from threading import Thread

client = Client('127.0.0.1:8786')


def load_data(q):
    i = 0
    while True:
        q.put(i)
        time.sleep(0.1)
        i += 1


def increment(x, inc=[0, 0, 0]):
    time.sleep(0.5)
    for i in inc:
        x += i
    return x


input_q = Queue(maxsize=100)
data = [1, 2, 3, 4, 5, 6, 7, 8]

remote_data = client.scatter(data)
remote_q = client.scatter(input_q)


inc_q = client.map(increment, remote_q, **{'inc': remote_data})
result_q = client.gather(inc_q)


Thread(target=load_data, args=(input_q,), daemon=True).start()

while True:
    print('latest result: {}'.format(result_q.get()))

```

The dask-scheduler produces some  errors.

```
distributed.scheduler - INFO - Receive client connection: 7e7c6e14-e7ba-11e6-8335-985aebd351e4
distributed.scheduler - ERROR - 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'
Traceback (most recent call last):
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2182, in transition_processing_memory
    s.remove(key)
KeyError: 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'
distributed.scheduler - ERROR - 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'
Traceback (most recent call last):
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2655, in transition
    recommendations = func(key, *args, **kwargs)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2182, in transition_processing_memory
    s.remove(key)
KeyError: 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'
distributed.scheduler - ERROR - 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'
Traceback (most recent call last):
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 1249, in handle_worker
    handler(worker=worker, **msg)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 1191, in handle_task_finished
    r = self.stimulus_task_finished(key=key, **msg)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 719, in stimulus_task_finished
    **kwargs)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2655, in transition
    recommendations = func(key, *args, **kwargs)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2182, in transition_processing_memory
    s.remove(key)
KeyError: 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'
distributed.scheduler - INFO - Remove worker tcp://127.0.0.1:50183
distributed.scheduler - INFO - Plugin failed with exception
Traceback (most recent call last):
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 1249, in handle_worker
    handler(worker=worker, **msg)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 1191, in handle_task_finished
    r = self.stimulus_task_finished(key=key, **msg)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 719, in stimulus_task_finished
    **kwargs)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2655, in transition
    recommendations = func(key, *args, **kwargs)
  File "/Users/kbruegge/Development/distributed/distributed/scheduler.py", line 2182, in transition_processing_memory
    s.remove(key)
KeyError: 'increment-72c55d32d351ec069e5d00cd2bbf4f1c'

During handling of the above exception, another exception occurred:
.
.
.

```

It goes on like this for a while. Then some lines of 

```
distributed.scheduler - INFO - User asked for computation on lost data, increment-385d81d312ae7cfbb71b30ba3249906a
distributed.scheduler - INFO - User asked for computation on lost data, increment-74ceedfca5f3ec3db206b0eeeb68bfb1
distributed.scheduler - INFO - User asked for computation on lost data, increment-7fd9b944879e6900fb10ed810f222067
distributed.scheduler - INFO - User asked for computation on lost data, increment-8f151ea5798ad438e86823b19652200d
.
.
.
```

And then more stacktraces.  
It does work fine when batch processing data. Is there another approach I should take to distribute shared objects to the workers?

**Comment by mackaiver** [comment]
I'm doing this on the latest master branch by the way. Commit 644e97dd555783caa204a5b2fb2fb8c4b610ee4c to be precise.
