### ISSUE TITLE
Cannot read dump: ValueError: int is not allowed for map key when strict_map_key=True

### ISSUE THREAD

**Issue by tekumara** [dask/distributed#8436]
**Describe the issue**:

Reading a cluster dump fails.

**Minimal Complete Verifiable Example**:

```python
>>> from distributed.cluster_dump import DumpArtefact
>>> url = "s3://.../dask-root-8ad03e68-6.dump.msgpack.gz"
>>>
>>> dump = DumpArtefact.from_url(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/distributed/cluster_dump.py", line 140, in from_url
    return DumpArtefact(load_cluster_dump(url, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/distributed/cluster_dump.py", line 106, in load_cluster_dump
    return reader(f)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/msgpack/__init__.py", line 47, in unpack
    return unpackb(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key when strict_map_key=True
```

**Anything else we need to know?**:

I'm using the same docker image, OS and python dependencies when reading the dump that were used to write it.

**Environment**:

- Dask version: see below
- Python version: 3.11.7
- Operating System: linux
- Install method (conda, pip, source): pip

dask==2023.3.2
dask-kubernetes==2023.3.2
distributed==2023.3.2.1
msgpack==1.0.7

**Comment by tekumara** [comment]
A workaround:
```python
import fsspec
import msgpack
from distributed.cluster_dump import DumpArtefact
url = "s3://.../dask-root-8ad03e68-6.dump.msgpack.gz"

kwargs = {}
kwargs.setdefault("compression", "infer")
with fsspec.open(url, "rb", **kwargs) as f:
    dump = DumpArtefact(msgpack.unpack(f, strict_map_key=False))
```

**Comment by hendrikmakait** [comment]
@tekumara: Thanks for reporting this issue, I can reproduce it:
```python
import time

from distributed import Client
from distributed.cluster_dump import load_cluster_dump

if __name__ == "__main__":
    c = Client()
    f = c.submit(lambda x: x, 1, key=(0, 1))
    time.sleep(1)
    c.dump_cluster_state(filename="dask-cluster-dump.msgpack.gz")
    load_cluster_dump("dask-cluster-dump.msgpack.gz")
```

It looks like `msgpack` switched to `strict_map_key=True` as default with `1.0` (https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10).

Would you be interested in contributing a fix?
