### ISSUE TITLE
`Print host info` CI step raises `RuntimeError: 'pmgr' entry was not found in AppleARMIODevice service` for `Mac OS`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8636]
Traceback:

```python
Traceback (most recent call last):
Number of CPUs: 3
  File "/Users/runner/work/distributed/distributed/continuous_integration/scripts/host_info.py", line [5](https://github.com/dask/distributed/actions/runs/8945035724/job/24573207121#step:19:5)3, in <module>
Crude CPU benchmark (higher is better): 69.5
    main()
  File "/Users/runner/work/distributed/distributed/continuous_integration/scripts/host_info.py", line 33, in main
    freqs = psutil.cpu_freq(percpu=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/dask-distributed/lib/python3.12/site-packages/psutil/__init__.py", line 1913, in cpu_freq
    ret = _psplatform.cpu_freq()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/dask-distributed/lib/python3.12/site-packages/psutil/_psosx.py", line 1[8](https://github.com/dask/distributed/actions/runs/8945035724/job/24573207121#step:19:8)2, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
                       ^^^^^^^^^^^^^^^
RuntimeError: 'pmgr' entry was not found in AppleARMIODevice service
Error: Process completed with exit code 1.
```

See CI logs: https://github.com/dask/distributed/actions/runs/8945035724/job/24573207121#step:19:27

**Comment by hendrikmakait** [comment]
https://github.com/dask/distributed/pull/8628 appears to have caused this.

**Comment by hendrikmakait** [comment]
Upstream issue: https://github.com/giampaolo/psutil/issues/2382

**Comment by hendrikmakait** [comment]
> #8628 appears to be the first occurrence of this.

Correlation, not causation: https://github.com/dask/distributed/actions/runs/8972110042/job/24639361479?pr=8637
