### ISSUE TITLE
Propagate reason to client-side `FutureCancelledError` when closing the scheduler

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8830]
`Scheduler.close` takes a `reason` keyword which allows us to provide additional context. However, when it comes to cancelling client-side futures, we simply abort the comm causing the Client to cancel the futures with `reason=scheduler-connection-lost`. It would be great if we could propagate the closing reason to the client and use it when cancelling futures in order to help users understand what's happening. For example, if the scheduler shuts down due to the `idle-timeout` kicking in, it would be great it we told the users that the futures were cancelled because we exceeded the timeout, not because we lost the connection due to some unknown reason.

**Comment by carusyte** [comment]
Been struggling for weeks (months?) why the scheduler connection is lost...
```
2025-01-18 01:38:33 - [master] - marten.utils.logger - ERROR - fit_with_covar-stock_zh_a_hist_em::000037@ta_price_characteristics_view.stdev cancelled for reason: scheduler-connection-lost.
 Client lost the connection to the scheduler. Please check your connection and re-run your work.
 Traceback (most recent call last):
   File "/home/kemove/git/marten/src/marten/utils/worker.py", line 256, in get_result
     r = future.result()
         ^^^^^^^^^^^^^^^
   File "/home/kemove/.pyenv/versions/anaconda3-2024.02-1/lib/python3.11/site-packages/distributed/client.py", line 402, in result
     return self.client.sync(self._result, callback_timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/kemove/.pyenv/versions/anaconda3-2024.02-1/lib/python3.11/site-packages/distributed/client.py", line 418, in _result
     raise exception
 distributed.client.FutureCancelledError: fit_with_covar-stock_zh_a_hist_em::000037@ta_price_characteristics_view.stdev cancelled for reason: scheduler-connection-lost.
 Client lost the connection to the scheduler. Please check your connection and re-run your work.
```

**Comment by rabernat** [comment]
:+1: just hit this issue
