### ISSUE TITLE
OSX Failures

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#890]
```
mrocklin$ py.test  distributed/comm/tests/test_comms.py::test_resolve_address
============================= test session starts ==============================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /Users/mrocklin/workspace/distributed, inifile:
collected 17 items

distributed/comm/tests/test_comms.py F

=================================== FAILURES ===================================
_____________________________ test_resolve_address _____________________________

    def test_resolve_address():
        f = resolve_address

        assert f('tcp://127.0.0.1:123') == 'tcp://127.0.0.1:123'
        assert f('zmq://127.0.0.1:456') == 'zmq://127.0.0.1:456'
        assert f('127.0.0.2:789') == 'tcp://127.0.0.2:789'
        assert f('tcp://0.0.0.0:456') == 'tcp://0.0.0.0:456'
        assert f('tcp://0.0.0.0:456') == 'tcp://0.0.0.0:456'

        if has_ipv6():
            assert f('tcp://[::1]:123') == 'tcp://[::1]:123'
            assert f('zmq://[::1]:456') == 'zmq://[::1]:456'
>           assert f('[::2]:789') == 'tcp://[::2]:789'
E           assert 'tcp://[::0.0.0.2]:789' == 'tcp://[::2]:789'
E             - tcp://[::0.0.0.2]:789
E             ?          ------
E             + tcp://[::2]:789

distributed/comm/tests/test_comms.py:99: AssertionError
=========================== 1 failed in 2.18 seconds ===========================
```

```
air:distributed mrocklin$ py.test  distributed/tests/test_core.py  --verbose
============================================== test session starts ==============================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /Users/mrocklin/anaconda/bin/python
cachedir: .cache
rootdir: /Users/mrocklin/workspace/distributed, inifile:
collected 14 items

distributed/tests/test_core.py::test_server PASSED
distributed/tests/test_core.py::test_rpc PASSED
distributed/tests/test_core.py::test_rpc_inputs PASSED
distributed/tests/test_core.py::test_rpc_with_many_connections PASSED
distributed/tests/test_core.py::test_large_packets SKIPPED
distributed/tests/test_core.py::test_identity PASSED
distributed/tests/test_core.py::test_ports PASSED
distributed/tests/test_core.py::test_coerce_to_address PASSED
distributed/tests/test_core.py::test_connection_pool <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_server_listen <- distributed/utils_test.py FAILED
distributed/tests/test_core.py::test_errors <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_connect_raises <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_send_recv_args <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_ticks <- distributed/utils_test.py SKIPPED

=================================================== FAILURES ====================================================
______________________________________________ test_server_listen _______________________________________________

self = <tornado.gen.Runner object at 0x1045d1860>

    def run(self):
        """Starts or resumes the generator, running until it reaches a
            yield point that is not ready.
            """
        if self.running or self.finished:
            return
        try:
            self.running = True
            while True:
                future = self.future
                if not future.done():
                    return
                self.future = None
                try:
                    orig_stack_contexts = stack_context._state.contexts
                    exc_info = None

                    try:
                        value = future.result()
                    except Exception:
                        self.had_exception = True
                        exc_info = sys.exc_info()

                    if exc_info is not None:
>                       yielded = self.gen.throw(*exc_info)
E                       StopIteration

../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: StopIteration

During handling of the above exception, another exception occurred:

    def test_func():
        with pristine_loop() as loop:
            cor = gen.coroutine(func)
            try:
>               loop.run_sync(cor, timeout=timeout)

distributed/utils_test.py:442:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../anaconda/lib/python3.5/site-packages/tornado/ioloop.py:457: in run_sync
    return future_cell[0].result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/tests/test_core.py:124: in test_server_listen
    yield assert_can_connect_locally_4(server.port)
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/utils_test.py:730: in assert_can_connect_locally_4
    yield futures
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:792: in callback
    result_list.append(f.result())
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1024: in run
    yielded = self.gen.send(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

addr = 'tcp://127.0.0.1:2468', timeout = 0.2

    @gen.coroutine
    def assert_cannot_connect(addr, timeout=None):
        """
        Check that it is impossible to connect to the distributed *addr*
        within the given *timeout*.
        """
        if timeout is None:
            timeout = 0.2
        with pytest.raises(EnvironmentError):
            comm = yield connect(addr, timeout=timeout)
>           comm.abort()
E           Failed: DID NOT RAISE <class 'OSError'>

distributed/utils_test.py:681: Failed
================================ 1 failed, 11 passed, 2 skipped in 2.25 seconds =================================
```

```
air:distributed mrocklin$ py.test  distributed/tests/test_steal.py::test_dont_steal_resource_restrictions
============================================== test session starts ==============================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /Users/mrocklin/workspace/distributed, inifile:
collected 40 items

distributed/tests/test_steal.py F

=================================================== FAILURES ====================================================
_____________________________________ test_dont_steal_resource_restrictions _____________________________________

self = <tornado.gen.Runner object at 0x1047522e8>

    def run(self):
        """Starts or resumes the generator, running until it reaches a
            yield point that is not ready.
            """
        if self.running or self.finished:
            return
        try:
            self.running = True
            while True:
                future = self.future
                if not future.done():
                    return
                self.future = None
                try:
                    orig_stack_contexts = stack_context._state.contexts
                    exc_info = None

                    try:
                        value = future.result()
                    except Exception:
                        self.had_exception = True
                        exc_info = sys.exc_info()

                    if exc_info is not None:
                        yielded = self.gen.throw(*exc_info)
                        exc_info = None
                    else:
>                       yielded = self.gen.send(value)
E                       StopIteration

../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1024: StopIteration

During handling of the above exception, another exception occurred:

    def test_func():
        with pristine_loop() as loop:
            with check_active_rpc(loop, active_rpc_timeout):
>               s, workers = loop.run_sync(lambda: start_cluster(ncores, loop,
                                Worker=Worker, scheduler_kwargs=scheduler_kwargs,
                                worker_kwargs=worker_kwargs))

distributed/utils_test.py:514:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../anaconda/lib/python3.5/site-packages/tornado/ioloop.py:457: in run_sync
    return future_cell[0].result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1021: in run
    yielded = self.gen.throw(*exc_info)
distributed/utils_test.py:468: in start_cluster
    yield [w._start(ncore[0]) for ncore, w in zip(ncores, workers)]
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:1015: in run
    value = future.result()
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:792: in callback
    result_list.append(f.result())
../../anaconda/lib/python3.5/site-packages/tornado/concurrent.py:237: in result
    raise_exc_info(self._exc_info)
<string>:3: in raise_exc_info
    ???
../../anaconda/lib/python3.5/site-packages/tornado/gen.py:285: in wrapper
    yielded = next(result)
distributed/worker.py:220: in _start
    self.listen(addr_or_port)
distributed/core.py:192: in listen
    self.listener.start()
distributed/comm/tcp.py:245: in start
    self.tcp_server.listen(self.port, self.ip)
../../anaconda/lib/python3.5/site-packages/tornado/tcpserver.py:126: in listen
    sockets = bind_sockets(port, address=address)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

port = 0, address = '127.0.0.2', family = <AddressFamily.AF_UNSPEC: 0>, backlog = 128, flags = 1
reuse_port = False

    def bind_sockets(port, address=None, family=socket.AF_UNSPEC,
                     backlog=_DEFAULT_BACKLOG, flags=None, reuse_port=False):
        """Creates listening sockets bound to the given port and address.

        Returns a list of socket objects (multiple sockets are returned if
        the given address maps to multiple IP addresses, which is most common
        for mixed IPv4 and IPv6 use).

        Address may be either an IP address or hostname.  If it's a hostname,
        the server will listen on all IP addresses associated with the
        name.  Address may be an empty string or None to listen on all
        available interfaces.  Family may be set to either `socket.AF_INET`
        or `socket.AF_INET6` to restrict to IPv4 or IPv6 addresses, otherwise
        both will be used if available.

        The ``backlog`` argument has the same meaning as for
        `socket.listen() <socket.socket.listen>`.

        ``flags`` is a bitmask of AI_* flags to `~socket.getaddrinfo`, like
        ``socket.AI_PASSIVE | socket.AI_NUMERICHOST``.

        ``reuse_port`` option sets ``SO_REUSEPORT`` option for every socket
        in the list. If your platform doesn't support this option ValueError will
        be raised.
        """
        if reuse_port and not hasattr(socket, "SO_REUSEPORT"):
            raise ValueError("the platform doesn't support SO_REUSEPORT")

        sockets = []
        if address == "":
            address = None
        if not socket.has_ipv6 and family == socket.AF_UNSPEC:
            # Python can be compiled with --disable-ipv6, which causes
            # operations on AF_INET6 sockets to fail, but does not
            # automatically exclude those results from getaddrinfo
            # results.
            # http://bugs.python.org/issue16208
            family = socket.AF_INET
        if flags is None:
            flags = socket.AI_PASSIVE
        bound_port = None
        for res in set(socket.getaddrinfo(address, port, family, socket.SOCK_STREAM,
                                          0, flags)):
            af, socktype, proto, canonname, sockaddr = res
            if (sys.platform == 'darwin' and address == 'localhost' and
                    af == socket.AF_INET6 and sockaddr[3] != 0):
                # Mac OS X includes a link-local address fe80::1%lo0 in the
                # getaddrinfo results for 'localhost'.  However, the firewall
                # doesn't understand that this is a local address and will
                # prompt for access (often repeatedly, due to an apparent
                # bug in its ability to remember granting access to an
                # application). Skip these addresses.
                continue
            try:
                sock = socket.socket(af, socktype, proto)
            except socket.error as e:
                if errno_from_exception(e) == errno.EAFNOSUPPORT:
                    continue
                raise
            set_close_exec(sock.fileno())
            if os.name != 'nt':
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            if reuse_port:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
            if af == socket.AF_INET6:
                # On linux, ipv6 sockets accept ipv4 too by default,
                # but this makes it impossible to bind to both
                # 0.0.0.0 in ipv4 and :: in ipv6.  On other systems,
                # separate sockets *must* be used to listen for both ipv4
                # and ipv6.  For consistency, always disable ipv4 on our
                # ipv6 sockets and use a separate ipv4 socket when needed.
                #
                # Python 2.x on windows doesn't have IPPROTO_IPV6.
                if hasattr(socket, "IPPROTO_IPV6"):
                    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)

            # automatic port allocation with port=None
            # should bind on the same port on IPv4 and IPv6
            host, requested_port = sockaddr[:2]
            if requested_port == 0 and bound_port is not None:
                sockaddr = tuple([host, bound_port] + list(sockaddr[2:]))

            sock.setblocking(0)
>           sock.bind(sockaddr)
E           OSError: [Errno 49] Can't assign requested address

../../anaconda/lib/python3.5/site-packages/tornado/netutil.py:194: OSError
--------------------------------------------- Captured stderr call ----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:56934
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:56935
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:56934
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    1.29 GB
distributed.worker - INFO -       Local Directory: /var/folders/y9/b466n_bs0qldppk3rc8hdlfm0000gp/T/worker-nr5qedmd
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Register tcp://127.0.0.1:56935
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:56935
distributed.worker - INFO -         Registered to:            tcp://127.0.0.1:56934
distributed.worker - INFO - -------------------------------------------------
=========================================== 1 failed in 1.02 seconds ============================================
```

cc @pitrou

**Comment by pitrou** [comment]
Is it possible to get a printout using "normal" tracebacks (use the `--tb=native` option to py.test)? I really have trouble parsing py.test tracebacks :-)

**Comment by mrocklin** [comment]
Sure

```
air:distributed mrocklin$ py.test  distributed/tests/test_steal.py::test_dont_steal_resource_restrictions --tb=native
============================================== test session starts ==============================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /Users/mrocklin/workspace/distributed, inifile:
collected 40 items

distributed/tests/test_steal.py F

=================================================== FAILURES ====================================================
_____________________________________ test_dont_steal_resource_restrictions _____________________________________
Traceback (most recent call last):
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrocklin/workspace/distributed/distributed/utils_test.py", line 514, in test_func
    s, workers = loop.run_sync(lambda: start_cluster(ncores, loop,
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mrocklin/workspace/distributed/distributed/utils_test.py", line 468, in start_cluster
    yield [w._start(ncore[0]) for ncore, w in zip(ncores, workers)]
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 792, in callback
    result_list.append(f.result())
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/Users/mrocklin/workspace/distributed/distributed/worker.py", line 220, in _start
    self.listen(addr_or_port)
  File "/Users/mrocklin/workspace/distributed/distributed/core.py", line 192, in listen
    self.listener.start()
  File "/Users/mrocklin/workspace/distributed/distributed/comm/tcp.py", line 245, in start
    self.tcp_server.listen(self.port, self.ip)
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 49] Can't assign requested address
--------------------------------------------- Captured stderr call ----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:56973
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:56974
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:56973
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    1.29 GB
distributed.worker - INFO -       Local Directory: /var/folders/y9/b466n_bs0qldppk3rc8hdlfm0000gp/T/worker-818ioobl
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Register tcp://127.0.0.1:56974
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:56974
distributed.worker - INFO -         Registered to:            tcp://127.0.0.1:56973
distributed.worker - INFO - -------------------------------------------------
=========================================== 1 failed in 0.71 seconds ============================================
```

```
air:distributed mrocklin$ py.test  distributed/tests/test_core.py  --verbose --tb=native
============================================== test session starts ==============================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /Users/mrocklin/anaconda/bin/python
cachedir: .cache
rootdir: /Users/mrocklin/workspace/distributed, inifile:
collected 14 items

distributed/tests/test_core.py::test_server PASSED
distributed/tests/test_core.py::test_rpc PASSED
distributed/tests/test_core.py::test_rpc_inputs PASSED
distributed/tests/test_core.py::test_rpc_with_many_connections PASSED
distributed/tests/test_core.py::test_large_packets SKIPPED
distributed/tests/test_core.py::test_identity PASSED
distributed/tests/test_core.py::test_ports PASSED
distributed/tests/test_core.py::test_coerce_to_address PASSED
distributed/tests/test_core.py::test_send_recv_args <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_connection_pool <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_errors <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_server_listen <- distributed/utils_test.py FAILED
distributed/tests/test_core.py::test_connect_raises <- distributed/utils_test.py PASSED
distributed/tests/test_core.py::test_ticks <- distributed/utils_test.py SKIPPED

=================================================== FAILURES ====================================================
______________________________________________ test_server_listen _______________________________________________
Traceback (most recent call last):
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrocklin/workspace/distributed/distributed/utils_test.py", line 442, in test_func
    loop.run_sync(cor, timeout=timeout)
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mrocklin/workspace/distributed/distributed/tests/test_core.py", line 124, in test_server_listen
    yield assert_can_connect_locally_4(server.port)
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mrocklin/workspace/distributed/distributed/utils_test.py", line 730, in assert_can_connect_locally_4
    yield futures
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 792, in callback
    result_list.append(f.result())
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/Users/mrocklin/workspace/distributed/distributed/utils_test.py", line 681, in assert_cannot_connect
    comm.abort()
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/_pytest/python.py", line 1234, in __exit__
    pytest.fail(self.message)
  File "/Users/mrocklin/anaconda/lib/python3.5/site-packages/_pytest/runner.py", line 542, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'OSError'>
================================ 1 failed, 11 passed, 2 skipped in 2.05 seconds =================================
```

```
air:distributed mrocklin$ py.test  distributed/comm/tests/test_comms.py --verbose --tb=native
============================================== test session starts ==============================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /Users/mrocklin/anaconda/bin/python
cachedir: .cache
rootdir: /Users/mrocklin/workspace/distributed, inifile:
collected 16 items

distributed/comm/tests/test_comms.py::test_parse_host_port PASSED
distributed/comm/tests/test_comms.py::test_unparse_host_port PASSED
distributed/comm/tests/test_comms.py::test_resolve_address FAILED
distributed/comm/tests/test_comms.py::test_zmq_client_server_ipv4 <- distributed/utils_test.py SKIPPED
distributed/comm/tests/test_comms.py::test_zmq_client_server_ipv6 <- distributed/utils_test.py SKIPPED
distributed/comm/tests/test_comms.py::test_tcp_comm_closed_implicit <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_tcp_client_server_ipv4 <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_tcp_client_server_ipv6 <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_zmq_comm_closed_explicit <- distributed/utils_test.py SKIPPED
distributed/comm/tests/test_comms.py::test_tcp_many_listeners <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_default_client_server_ipv4 <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_tcp_connect_timeout <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_tcp_specific <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_default_client_server_ipv6 <- distributed/utils_test.py PASSED
distributed/comm/tests/test_comms.py::test_zmq_specific <- distributed/utils_test.py SKIPPED
distributed/comm/tests/test_comms.py::test_tcp_comm_closed_explicit <- distributed/utils_test.py PASSED

=================================================== FAILURES ====================================================
_____________________________________________ test_resolve_address ______________________________________________
Traceback (most recent call last):
  File "/Users/mrocklin/workspace/distributed/distributed/comm/tests/test_comms.py", line 99, in test_resolve_address
    assert f('[::2]:789') == 'tcp://[::2]:789'
AssertionError: assert 'tcp://[::0.0.0.2]:789' == 'tcp://[::2]:789'
  - tcp://[::0.0.0.2]:789
  ?          ------
  + tcp://[::2]:789
================================ 1 failed, 11 passed, 4 skipped in 2.56 seconds =================================
```

**Comment by pitrou** [comment]
Ok, I can diagnose all of these.
As for test_steal, it seems `127.0.0.2` (which is used in the test) cannot be used on OS X:
```
In [15]: socks = netutil.bind_sockets(12345, '127.0.0.2')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-15-1d9b1e2890ee> in <module>()
----> 1 socks = netutil.bind_sockets(12345, '127.0.0.2')

/Users/buildbot/miniconda3/envs/antoine-dask/lib/python3.6/site-packages/tornado/netutil.py in bind_sockets(port, address, family, backlog, flags, reuse_port)
    192 
    193         sock.setblocking(0)
--> 194         sock.bind(sockaddr)
    195         bound_port = sock.getsockname()[1]
    196         sock.listen(backlog)

OSError: [Errno 49] Can't assign requested address
```

**Comment by pitrou** [comment]
Or without going through Tornado:
```
In [16]: sock = socket.socket()

In [17]: sock.bind(('127.0.0.2', 1345))
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-17-920a36acacc3> in <module>()
----> 1 sock.bind(('127.0.0.2', 1345))

OSError: [Errno 49] Can't assign requested address
```

**Comment by pitrou** [comment]
@mrocklin, could you try this patch: https://gist.github.com/pitrou/b99457361e60849fd8f4491ec6700e48 ? It seems to solve it for me here.

**Comment by mrocklin** [comment]
This has been resolved.  Thanks @pitrou !
