### ISSUE TITLE
StreamClosedError: Stream is closed

### ISSUE THREAD

**Issue by abast** [dask/distributed#893]
Using the newest conda release of distributed, the error stack below popped up. It seems, that the computation has not been interrupted, also the bokeh interface does not list any task as "failed". So can I safely ignore this? What happened?
```

distributed.utils - ERROR - Stream is closed
Traceback (most recent call last):
  File "[path]/Anaconda2/lib/python2.7/site-packages/distributed/utils.py", line 120, in f
    See https://github.com/tornadoweb/tornado/issues/1546
  File "[path]r/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/distributed/client.py", line 368, in _start
    'key-in-memory': self._handle_key_in_memory,
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/distributed/client.py", line 402, in ensure_connected
    self._loop_thread = Thread(target=self.loop.start)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/distributed/core.py", line 427, in send_recv_from_rpc
    if kwargs.get('close'):
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/distributed/core.py", line 308, in send_recv
    n_frames = struct.unpack('Q', n_frames)[0]
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File [path]/Anaconda2/lib/python2.7/site-packages/distributed/core.py", line 203, in read
    close_desired = msg.pop('close', False)
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[path]/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
StreamClosedError: Stream is closed
```

**Comment by pitrou** [comment]
Your traceback is a bit weird: it shows lines of code that are not in the given functions, such as:
```
  File "[path]/Anaconda2/lib/python2.7/site-packages/distributed/core.py", line 308, in send_recv
    n_frames = struct.unpack('Q', n_frames)[0]
```

I'm not sure that would explain your problem, but Is it possible that your distributed install is somehow messed up?

Is there a way you can post a simple reproducer for this problem?

**Comment by abast** [comment]
Thanks for having a look at it. I used  `conda update distributed` to get my distributed installation up to date and restarted the scheduler and workers afterwards. But maybe there is still an inconsistency somewhere. I got this error message after about 4h of computing within a rather complex pipeline, so boiling it down to a minimal example will be a challenge.

**Comment by pitrou** [comment]
Perhaps you can try `conda uninstall distributed` followed by `conda install distributed`. One possible explanation for the traceback is that the `.pyc` files are out of sync with the `.py` files.

**Comment by pitrou** [comment]
Also, it's probably better to stop your distributed cluster before running any `conda` operations.

**Comment by abast** [comment]
Right, thanks again. So I reinstalled distributed as you suggested. So far, everything works smooth.

**Comment by abast** [comment]
Everything is still looking good, so I close the issue for now.
