### ISSUE TITLE
Remove Python version conditions from requirements.txt

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#906]
In https://github.com/dask/distributed/pull/746 we added Python version requirements to futures and singledispatch in requirements.txt. 

Unfortunately this interferes with readthedocs, which is still on a very old version of setuptools: https://github.com/rtfd/readthedocs.org/issues/2547

As a result, our documentation is not building.  How can we resolve this?

**Comment by mrocklin** [comment]
One solution would be to remove version requirements from requirements.txt.  Is there anything wrong with installing these libraries when they're already handled by the standard library?

cc @pitrou

**Comment by pitrou** [comment]
The main thing we want to ensure is that the stdlib version keeps precedence, as it's the version that's the most up-to-date (with bug fixes), and possibly more performant too. That seems to be the case, as per a simple test:
```
$ python -c "import concurrent; print(concurrent)"
<module 'concurrent' from '/home/antoine/miniconda3/envs/dask36/lib/python3.6/concurrent/__init__.py'>
$ pip install futures
[...]
Successfully installed futures-3.0.5
$ python -c "import concurrent; print(concurrent)"
<module 'concurrent' from '/home/antoine/miniconda3/envs/dask36/lib/python3.6/concurrent/__init__.py'>
```

**Comment by mrocklin** [comment]
Any other concerns?

**Comment by pitrou** [comment]
Another possible source of annoyance is if one of the projects forgets to release for a newer Python version. `futures` and `singledispatch` are version-agnostic, though, so should be ok.

**Comment by mrocklin** [comment]
```python
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 68, in <module>
    import distributed
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/distributed-1.16.0+8.gf597cd4-py3.5.egg/distributed/__init__.py", line 4, in <module>
    from .core import connect, rpc
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/distributed-1.16.0+8.gf597cd4-py3.5.egg/distributed/core.py", line 23, in <module>
    from tornado import gen
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/tornado/gen.py", line 87, in <module>
    from tornado.concurrent import Future, TracebackFuture, is_future, chain_future
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/tornado/concurrent.py", line 37, in <module>
    from concurrent import futures
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/futures-3.0.5-py3.5.egg/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/futures-3.0.5-py3.5.egg/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/distributed/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 279, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
sphinx.errors.ConfigError: There is a syntax error in your configuration file: invalid syntax (_base.py, line 357)
Did you change the syntax from 2.x to 3.x?

Configuration error:
There is a syntax error in your configuration file: invalid syntax (_base.py, line 357)
Did you change the syntax from 2.x to 3.x?
```

**Comment by pitrou** [comment]
Ah.... So what I think happens is that, with `pip`, the `futures` install doesn't shadow the stdlib, but with `setup.py install` it does :-/

**Comment by pitrou** [comment]
Unfortunately, I have no idea how to solve this.

**Comment by mrocklin** [comment]
OK, we can apply some pressure to the readthedocs folks to use a more modern setuptools library.  If that doesn't work then maybe we point readthedocs to a different branch where we occasionally push a version with an altered requirements.txt

**Comment by jreback** [comment]
fyi there is an option at the bottom of the advanced page in rst to use a python 2 or python 3 interpreter (that then reads the requirements) and creates the env 

i would suppose the python 3 might be more modern

**Comment by mrocklin** [comment]
We've been on Python 3 on readthedocs for a while now except for just now we reverted to Python 2 just to get something up with the current stripped down requirements.txt (which we have to change back).

I suppose we could try the converse suggestion of going backwards to Python 2 long term in hopes that they have a newer setuptools?

**Comment by gforsyth** [comment]
If you don't need any RTD-specific features, you can check out https://github.com/drdoctr/doctr to deploy docs from Travis to github pages (disclaimer: one of my projects)

**Comment by mariusvniekerk** [comment]
Personally used doctr and it works well.

**Comment by mrocklin** [comment]
Readthedocs improved.  Closing.
