### ISSUE TITLE
Bokeh failure with LocalCluster

### ISSUE THREAD

**Issue by pitrou** [dask/distributed#958]
The Bokeh server tries to connect to the scheduler's `inproc` address and fails:
```
>>> cluster = LocalCluster(nanny=False, n_workers=1, threads_per_worker=1)
>>> distributed.utils - ERROR - inproc address '192.168.1.68/26403/1' does not match host ('192.168.1.68') or pid (26594)
Traceback (most recent call last):
  File "/home/antoine/distributed/distributed/utils.py", line 307, in log_errors
    yield
  File "/home/antoine/distributed/distributed/bokeh/background/server_lifecycle.py", line 92, in processing
    comm = yield connect(addr)
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/antoine/distributed/distributed/comm/core.py", line 159, in connect
    quiet_exceptions=EnvironmentError)
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/home/antoine/distributed/distributed/comm/inproc.py", line 278, in connect
    listener = self.manager.get_listener_for(address)
  File "/home/antoine/distributed/distributed/comm/inproc.py", line 53, in get_listener_for
    self.validate_address(addr)
  File "/home/antoine/distributed/distributed/comm/inproc.py", line 66, in validate_address
    % (addr, self.ip, os.getpid()))
ValueError: inproc address '192.168.1.68/26403/1' does not match host ('192.168.1.68') or pid (26594)
```

**Comment by pitrou** [comment]
It seems that might have been overlooked when merging the `inproc` support for LocalCluster, unless that's related to a later change. @mrocklin, what do you think about this?

**Comment by mrocklin** [comment]
I wouldn't worry about this too much right now.  I may try to bring the Bokeh server within the same process if I make make our plots efficient enough.  This would remove the need for communication anyway.

**Comment by pitrou** [comment]
It would be nice to suppress the error, though, since that usually fills several pages in a terminal.

**Comment by mrocklin** [comment]
If the scheduler isn't serving on TCP then the
separate-process-bokeh-server doesn't have the ability to connect.  It
probably shouldn't try.
