### ISSUE TITLE
`Already reading` error from dscheduler

### ISSUE THREAD

**Issue by izaid** [dask/distributed#96]
Okay, so I've set up a fake cluster as per the quickstart:

```
$ dscheduler
$ dworker 127.0.0.1:8786
$ dworker 127.0.0.1:8786
$ dworker 127.0.0.1:8786
```

I then run a simple example, that I think should work:

```
from distributed import Executor
e = Executor('127.0.0.1:8786')
futures = e.map(lambda x: None, range(10))
```

I then get a whole bunch of errors:

```
istributed.scheduler - ERROR - Stream is closed
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/scheduler.py", line 723, in handle_messages
    msg = yield next_message()  # in_queue.get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/core.py", line 190, in read
    msg = yield stream.read_until(sentinel)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
StreamClosedError: Stream is closed
distributed.scheduler - ERROR - Stream is closed
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/scheduler.py", line 723, in handle_messages
    msg = yield next_message()  # in_queue.get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/core.py", line 190, in read
    msg = yield stream.read_until(sentinel)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/iostream.py", line 282, in read_until
    self._try_inline_read()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/iostream.py", line 701, in _try_inline_read
    self._check_closed()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/iostream.py", line 885, in _check_closed
    raise StreamClosedError(real_error=self.error)
StreamClosedError: Stream is closed
distributed.scheduler - INFO - Close connection to Scheduler, 354bf7d7-ca93-11e5-91ae-acbc32bf2b0d
distributed.core - ERROR - Already reading
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/core.py", line 164, in handle_stream
    result = yield gen.maybe_future(handler(stream, **msg))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/scheduler.py", line 691, in control_stream
    yield self.handle_messages(stream, stream)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/scheduler.py", line 723, in handle_messages
    msg = yield next_message()  # in_queue.get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed-1.7.4-py2.7.egg/distributed/core.py", line 190, in read
    msg = yield stream.read_until(sentinel)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/iostream.py", line 278, in read_until
    future = self._set_read_callback(callback)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado-4.3-py2.7-macosx-10.11-x86_64.egg/tornado/iostream.py", line 662, in _set_read_callback
    assert self._read_future is None, "Already reading"
AssertionError: Already reading
```

I've actually used distributed successfully, so I think something is leaving a part of distributed in a bad state.

**Comment by mrocklin** [comment]
This has, I believe, been resolved.  This was caused by the unexpected disconnect of a client.  Everything worked it was just logging a scarier message than was appropriate.  Now it looks like this:

```
mrocklin@notebook:~/workspace/distributed$ dscheduler 
distributed.scheduler - INFO - Start Scheduler at:       10.105.174.217:8786
distributed.scheduler - INFO -            http at:       10.105.174.217:50165
distributed.core - INFO - Connection from 10.105.174.217:45121 to Scheduler
distributed.scheduler - INFO - Register ('10.105.174.217', 34717)
distributed.core - INFO - Connection from 10.105.174.217:45122 to Scheduler
distributed.core - INFO - Connection from 10.105.174.217:45123 to Scheduler
distributed.scheduler - INFO - Connection to Scheduler, f4160734-cf8a-11e5-89c0-60672020cfac
distributed.core - INFO - Lost connection: ('10.105.174.217', 45122)
distributed.core - INFO - Close connection from 10.105.174.217:45122 to Scheduler
distributed.scheduler - INFO - Lost connection to client
distributed.scheduler - INFO - Close connection to Scheduler, f4160734-cf8a-11e5-89c0-60672020cfac
```
