### ISSUE TITLE
Basic Queue example fails intermittently in ensure_connected

### ISSUE THREAD

**Issue by sjperkins** [dask/distributed#980]
The following minimal example:

```python
from __future__ import print_function

import Queue
import time

import distributed
from distributed import LocalCluster, Client, local_client

nworkers  = 5

cluster = LocalCluster(n_workers=nworkers)
client = Client(cluster)


def qux(f):
    result = -1 if f == -1 else f + 5

    with local_client() as c:
       print(c.worker, result)

    return result

input_q = Queue.Queue()
remote_q = client.scatter(input_q)
frob_q = client.map(qux, remote_q)
result_q = client.gather(frob_q)

def feed_data(queue, n):
    for i in range(n):
        queue.put(i)

    queue.put(-1)

import threading

t = threading.Thread(target=feed_data, args=(input_q, 50,))
t.start()

try:
    while True:
        i = result_q.get()
        print(i)

        if i == -1:
            break

except Queue.Empty:
    pass

t.join()

time.sleep(10)

client.shutdown()
cluster.close()
```

intermittently produces the following on 1.16.1 and master branch:

```bash
$ python dask_queue.py 
distributed.deploy.local - INFO - To start diagnostics web server please install Bokeh
<Worker: tcp://127.0.0.1:41633, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 7
<Worker: tcp://127.0.0.1:42136, running, stored: 11, running: 0/2, ready: 0, comm: 0, waiting: 0> 5
<Worker: tcp://127.0.0.1:42136, running, stored: 11, running: 0/2, ready: 0, comm: 0, waiting: 0> 6
<Worker: tcp://127.0.0.1:41633, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 8
<Worker: tcp://127.0.0.1:39148, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 29
<Worker: tcp://127.0.0.1:46208, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 52
<Worker: tcp://127.0.0.1:39148, running, stored: 11, running: 0/2, ready: 0, comm: 0, waiting: 0> 49
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 474, in _start
    yield self.ensure_connected(timeout=timeout)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 509, in ensure_connected
    assert len(msg) == 1
AssertionError
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 474, in _start
    yield self.ensure_connected(timeout=timeout)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 509, in ensure_connected
    assert len(msg) == 1
AssertionError
<Worker: tcp://127.0.0.1:46208, running, stored: 11, running: 0/2, ready: 0, comm: 0, waiting: 0> 11
<Worker: tcp://127.0.0.1:46658, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 13
<Worker: tcp://127.0.0.1:46658, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 23
<Worker: tcp://127.0.0.1:42136, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> <Worker: tcp://127.0.0.1:42136, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 2516

<Worker: tcp://127.0.0.1:46208, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 12
<Worker: tcp://127.0.0.1:39148, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 19
<Worker: tcp://127.0.0.1:42136, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 15
<Worker: tcp://127.0.0.1:46658, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 24
<Worker: tcp://127.0.0.1:46658, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 14
<Worker: tcp://127.0.0.1:39148, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 9
<Worker: tcp://127.0.0.1:41633, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 28
<Worker: tcp://127.0.0.1:46658, running, stored: 10, running: 0/2, ready: 0, comm: 0, waiting: 0> 33
<Worker: tcp://127.0.0.1:41633, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 18
<Worker: tcp://127.0.0.1:39148, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 10
<Worker: tcp://127.0.0.1:46208, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 22
<Worker: tcp://127.0.0.1:46208, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 21
<Worker: tcp://127.0.0.1:41633, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 27<Worker: tcp://127.0.0.1:41633, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 17

<Worker: tcp://127.0.0.1:42136, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 35
<Worker: tcp://127.0.0.1:46658, running, stored: 12, running: 0/2, ready: 0, comm: 0, waiting: 0> 43
<Worker: tcp://127.0.0.1:42136, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 26
<Worker: tcp://127.0.0.1:46208, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 31
<Worker: tcp://127.0.0.1:42136, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 36
<Worker: tcp://127.0.0.1:46208, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 32
<Worker: tcp://127.0.0.1:46658, running, stored: 13, running: 0/2, ready: 0, comm: 0, waiting: 0> 44
<Worker: tcp://127.0.0.1:46658, running, stored: 15, running: 0/2, ready: 0, comm: 0, waiting: 0> 34
<Worker: tcp://127.0.0.1:41633, running, stored: 14, running: 0/2, ready: 0, comm: 0, waiting: 0><Worker: tcp://127.0.0.1:41633, running, stored: 14, running: 0/2, ready: 0, comm: 0, waiting: 0>  3747
<Worker: tcp://127.0.0.1:42136, running, stored: 17, running: 0/2, ready: 0, comm: 0, waiting: 0> 46

<Worker: tcp://127.0.0.1:46658, running, stored: 15, running: 0/2, ready: 0, comm: 0, waiting: 0> 53
<Worker: tcp://127.0.0.1:42136, running, stored: 17, running: 0/2, ready: 0, comm: 0, waiting: 0> -1
<Worker: tcp://127.0.0.1:41633, running, stored: 14, running: 0/2, ready: 0, comm: 0, waiting: 0> 38
<Worker: tcp://127.0.0.1:46658, running, stored: 16, running: 0/2, ready: 0, comm: 0, waiting: 0> 54
<Worker: tcp://127.0.0.1:42136, running, stored: 18, running: 0/2, ready: 0, comm: 0, waiting: 0> 45
<Worker: tcp://127.0.0.1:46208, running, stored: 15, running: 0/2, ready: 0, comm: 0, waiting: 0> <Worker: tcp://127.0.0.1:46208, running, stored: 15, running: 0/2, ready: 0, comm: 0, waiting: 0> 51
41
<Worker: tcp://127.0.0.1:41633, running, stored: 16, running: 0/2, ready: 0, comm: 0, waiting: 0> 48
<Worker: tcp://127.0.0.1:39148, running, stored: 15, running: 0/2, ready: 0, comm: 0, waiting: 0> 40
<Worker: tcp://127.0.0.1:46208, running, stored: 16, running: 0/2, ready: 0, comm: 0, waiting: 0> 42
<Worker: tcp://127.0.0.1:39148, running, stored: 15, running: 0/2, ready: 0, comm: 0, waiting: 0> 39
<Worker: tcp://127.0.0.1:39148, running, stored: 17, running: 0/2, ready: 0, comm: 0, waiting: 0> 50
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
distributed.utils - ERROR - 
Traceback (most recent call last):
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 940, in _gather
    traceback)
  File "dask_queue.py", line 18, in qux
    with local_client() as c:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/worker_client.py", line 48, in worker_client
    sync(wc.loop, wc._start, timeout=timeout)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 204, in sync
    six.reraise(*error[0])
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 474, in _start
    yield self.ensure_connected(timeout=timeout)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 509, in ensure_connected
    assert len(msg) == 1
AssertionError
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 976, in _threaded_gather
    results = self.gather(L, **kwargs)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 1031, in gather
    return sync(self.loop, self._gather, futures, errors=errors)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 204, in sync
    six.reraise(*error[0])
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 940, in _gather
    traceback)
  File "dask_queue.py", line 18, in qux
    with local_client() as c:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/worker_client.py", line 48, in worker_client
    sync(wc.loop, wc._start, timeout=timeout)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 204, in sync
    six.reraise(*error[0])
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 474, in _start
    yield self.ensure_connected(timeout=timeout)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/sperkins/venv/dask/local/lib/python2.7/site-packages/distributed/client.py", line 509, in ensure_connected
    assert len(msg) == 1
AssertionError

^Z
[1]+  Stopped                 python dask_queue.py
```

**Comment by sjperkins** [comment]
Possibly related to #843 and #838

**Comment by mrocklin** [comment]
Thank you for taking the time to produce a minimal example.  How intermittent?  I just ran this 100 times in a loop and haven't yet seen an issue.

**Comment by sjperkins** [comment]
It happened on 5 out of 10 runs on my side.

I also tried with a fresh virtual environment and it occurred 1 out 2 runs.

Let me know if you need more debugging information.

**Comment by mrocklin** [comment]
I'm curious what the messages are.  Are you comfortable slightly modifying your sourcecode?

```diff
+++ b/distributed/client.py
@@ -505,6 +505,11 @@ class Client(object):
         yield comm.write({'op': 'register-client',
                           'client': self.id, 'reply': False})
         msg = yield comm.read()
+        if len(msg) > 1:
+            print(msg)
         assert len(msg) == 1
         assert msg[0]['op'] == 'stream-start'

**Comment by sjperkins** [comment]
It results in this output: 

```
[{'op': 'stream-start'}, {'op': 'stream-closed'}]
[{'op': 'stream-start'}, {'op': 'stream-closed'}]
```

**Comment by sjperkins** [comment]
Ah! Commenting out the with `with local_client() as c:` line seems to stop the problem...

```python
def qux(f):
    result = -1 if f == -1 else f + 5

    #with local_client() as c:
    #   print(c.worker, result)

    return result
```
