### ISSUE TITLE
scheduler crashes if workers are stared with --no-nanny keyword

### ISSUE THREAD

**Issue by abast** [dask/distributed#985]
After setting up the workers with the `--no-nanny` option, I got the following errorstack in the scheduler terminal after submitting a compute job:

```
distributed.scheduler - INFO - Close client connection: 474b4ee8-1583-11e7-a424-0024e87a068c
distributed.core - ERROR - 'nanny'
Traceback (most recent call last):
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/distributed/core.py", line 219, in handle_stream
    result = yield result
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/distributed/scheduler.py", line 1042, in add_client
    yield self.handle_client(stream, client=client)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/distributed/scheduler.py", line 1112, in handle_client
    yield result
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/distributed/scheduler.py", line 1338, in restart
    for addr, d in self.worker_info.items()}
  File "/nas1/Data_arco/prgr/Anaconda2/lib/python2.7/site-packages/distributed/scheduler.py", line 1338, in <dictcomp>
    for addr, d in self.worker_info.items()}
KeyError: 'nanny'
distributed.core - WARNING - Lost connection to ('127.0.0.1', 57154) while sending result: Stream is closed
```

```
distributed.__version__
> 0.15.2
```

**Comment by martindurant** [comment]
You cannot call "restart" is your worker does not have a nanny.
The scheduler should probably check for this and warn/error if you try.

**Comment by mrocklin** [comment]
Restarting workers requires that they have a nanny

**Comment by abast** [comment]
Thanks, that makes sense. Closing.

**Comment by mrocklin** [comment]
As always thanks for raising the issue.  It's nice to have a public record
of this for future readers.

**Comment by martindurant** [comment]
Note that in my experimental work on a cluster management dashboard, done on ly for LocalCluster, I did test for this, since local processes are easily killed and relaunched https://github.com/martindurant/distributed/blob/cluster_monitor/distributed/deploy/local.py#L331
