### ISSUE TITLE
Binary string error on Client connect

### ISSUE THREAD

**Issue by postelrich** [dask/distributed#988]
Was getting this error trying to connect with Client.

```
In [3]: from distributed import Client

In [4]: c = Client('10.202.131.8:8786')
distributed.utils - ERROR - 'op'
Traceback (most recent call last):
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/utils.py", line 193, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/client.py", line 468, in _start
    yield self.ensure_connected(timeout=timeout)
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/client.py", line 504, in ensure_connected
    assert msg[0]['op'] == 'stream-start'
KeyError: 'op'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-c30e6329072d> in <module>()
----> 1 c = Client('10.202.131.8:8786')

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/client.py in __init__(self, address, start, loop, timeout, set_as_default, scheduler_file)
    379
    380         if start:
--> 381             self.start(timeout=timeout)
    382
    383         from distributed.channels import ChannelClient

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/client.py in start(self, **kwargs)
    412         self.loop.add_callback(pc.start)
    413         _global_client[0] = self
--> 414         sync(self.loop, self._start, **kwargs)
    415         self.status = 'running'
    416

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    202         e.wait(1000000)
    203     if error[0]:
--> 204         six.reraise(*error[0])
    205     else:
    206         return result[0]

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
    685             raise value.with_traceback(tb)
--> 686         raise value
    687
    688 else:

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/utils.py in f()
    191                 raise RuntimeError("sync() called from thread of running loop")
    192             yield gen.moment
--> 193             result[0] = yield gen.maybe_future(func(*args, **kwargs))
    194         except Exception as exc:
    195             logger.exception(exc)

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1013
   1014                     try:
-> 1015                         value = future.result()
   1016                     except Exception:
   1017                         self.had_exception = True

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/concurrent.py in result(self, timeout)
    235             return self._result
    236         if self._exc_info is not None:
--> 237             raise_exc_info(self._exc_info)
    238         self._check_done()
    239         return self._result

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/util.py in raise_exc_info(exc_info)

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1019
   1020                     if exc_info is not None:
-> 1021                         yielded = self.gen.throw(*exc_info)
   1022                         exc_info = None
   1023                     else:

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/client.py in _start(self, timeout, **kwargs)
    466         self.scheduler_comm = None
    467
--> 468         yield self.ensure_connected(timeout=timeout)
    469
    470         self.coroutines.append(self._handle_report())

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1013
   1014                     try:
-> 1015                         value = future.result()
   1016                     except Exception:
   1017                         self.had_exception = True

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/concurrent.py in result(self, timeout)
    235             return self._result
    236         if self._exc_info is not None:
--> 237             raise_exc_info(self._exc_info)
    238         self._check_done()
    239         return self._result

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/util.py in raise_exc_info(exc_info)

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1022                         exc_info = None
   1023                     else:
-> 1024                         yielded = self.gen.send(value)
   1025
   1026                     if stack_context._state.contexts is not orig_stack_contexts:

/Users/rich/miniconda2/envs/dist/lib/python3.5/site-packages/distributed/client.py in ensure_connected(self, timeout)
    502         msg = yield comm.read()
    503         assert len(msg) == 1
--> 504         assert msg[0]['op'] == 'stream-start'
    505
    506         bcomm = BatchedSend(interval=10, loop=self.loop)

KeyError: 'op'
```

I tried printing out msg and got `{b'op': b'stream-start'}`. Looks like a python 3 support problem, tornado is returning binary strings.  If I change distributed/client.py:504 to `assert msg[0][b'op'] == b'stream-start'` it connects fine.

**Comment by mrocklin** [comment]
Your scheduler and client are likely running different versions of Python.  This is a common symptom of a Python 2/3 version mismatch.

**Comment by postelrich** [comment]
Yup this was exactly it, thanks.

**Comment by mrocklin** [comment]
I'm making things more robust to this now so that you can use python 2 schedulers with python 3 client/workers etc.
